### ISSUE TITLE
Enable the language server to request the contents of a file that is not yet opened in the client

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode-languageserver-node#1]
For remote language server scenarios, it may be necessary to allow the language server to send a notification (or request?) to the client to request the contents of a file at a given URI.  In this case, the client shouldn't open the file in the client UI, only send the file's contents to the language server.  This will allow interpreted languages like PowerShell to provide cross-file language features when the current file references a file at another location on the client machine.  

I believe this scenario will also require that the client send file watcher events for the requested file just in case the file is changed or deleted on disk.

**Comment by dbaeumer** [comment]
What we added to the latest release is the possibility to send requests from the server to the client. So this could be implemented now using a custom request / response. @daviwil do you still think it should be part of the language server protocol ?

**Comment by daviwil** [comment]
Nope, I can add my own request now thanks to the new server-to-client requests.  I just implemented support for that yesterday in my language server, it works great!  I'll close this issue now.

**Comment by felixfbecker** [comment]
Imo this should be part of the protocol. Currently I just read files from disk, but disk access cannot be assumed in every environment. And reading files is absolutely needed for indexing, finding references etc.

**Comment by dbaeumer** [comment]
@felixfbecker can you please open an issue against the protocol itself.
