### ISSUE TITLE
Is LSP version limited to major.minor only?

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-languageserver-node#1001]
Can you provide details on the LSP version vs LSP implementation version?
As far as I know understand, LSP version is limited to <major>.<minor>. 

From looking at https://www.npmjs.com/package/vscode-languageserver-protocol , it seems like it is ok to use the <micro> part of the version to advance the package version for things like bug fixes.

I just want to confirm that the LSP is limited to <major>.<minor>.

**Comment by dbaeumer** [comment]
The protocol package always reflects the LSP version. We should still use `major.minor.patch` even if we will never use patch since bug fixes are rare in the protocol itself.

**Comment by karthiknadig** [comment]
@dbaeumer I am not sure I understand.

As far as I can tell the LSP spec version is major.minor only. So far there is 3.16 and 3.17.

Where as the LSP node implementation has 3.17.0, 3.17.1, etc using the major.minor.patch format. What happens to LSP node implementation version if there is LSP spec version 3.17.1 (or there is never going to be a LSP spec version 3.17.1). Since there was already a LSP node version 3.17.1, how will the node package be updated to align with LSP spec.

The reason I am asking this is, we are planning on releasing a python package that contains the LSP types generated using the LSP MetaModel. We are figuring out how to version the package, our original intent was that we would tie the major-minor to the LSP Spec version, and use the patch for bugs in the python package itself. But this assumes that the LSP spec version is limited to major-minor only.

**Comment by dbaeumer** [comment]
I see the problem, but I don't want to restrict this. I think we have the same problem here as we have with nodeJS and the typings for it. The version numbers allign in major.minor but not necessarily on patch level since the two things can evolve independently. All I can recommend is to use documentation to make this clear.
