### ISSUE TITLE
Metamodel does not accurately represent registration for semantic tokens

### ISSUE THREAD

**Issue by michaelpj** [microsoft/vscode-languageserver-node#1006]
From the spec:

> Since the registration option handles range, full and delta requests the method used to register for semantic tokens requests is textDocument/semanticTokens and not one of the specific methods described below.

The metamodel does not list the `textDocument/semanticTokens` method, and some (but not all!) of the specific semantic tokens methods list the registration params (specifically `full` and `full/delta` list the registration params, `range` and `refresh` do not).

I'm not sure what the right way to represent this slightly odd situation is.

**Comment by dbaeumer** [comment]
Fix in branch. Request and Notification that have a different registration method now enumerate it.

**Comment by michaelpj** [comment]
I was going to complain that `textDocument/semanticTokens` still isn't listed under `requests`, but of course, you can't make a request to that method, so there's no place to list it except indirectly like this. It's very tempting to assume there's a 1-1 correspondence between requests/notifications and methods...
