### ISSUE TITLE
No documentation is produced in completion item during test run

### ISSUE THREAD

**Issue by gee4vee** [microsoft/vscode-languageserver-node#1012]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.68.1
- OS Version: macOS 12.4

Steps to Reproduce:

1. Generate a completion item in an LSP sample where `documentation` is included in the items.
2. Write a test case expecting `documentation` in the completion items.

Our LSP extension adds `documentation` to the completion items. The documentation can be seen when running the extension manually.

```
      const documentation: MarkupContent = {
        kind: "markdown",
        value: [
          `## Module: ${output.source}, Output: ${output.key}`,
          `${docString}`,
          `${moduleRepoDocString}`,
          `${internalLineDocString}`,
        ].join("\n"),
      };

      return {
        label: `$workitem.${output.source}.outputs.${output.key}`,
        kind: CompletionItemKind.Value,
        data: index + 1,
        preselect: true,
        sortText: "1" + String(index + 1).padStart(4, "0"),
        detail: "Module-level output",
        documentation,
      };
```

However, the completion items produced during a test run have everything except the documentation:

```
{"label":"$workitem.bp-iks-vpc-gen2-cluster.outputs.cluster_id","kind":"Value","detail":"Module-level output","documentation":{},"sortText":"10001","preselect":true,"insertText":"$workitem.bp-iks-vpc-gen2-cluster.outputs.cluster_id"}
```

**Comment by dbaeumer** [comment]
@gee4vee could you please provide me with a GitHub repository I can clone that demos what you are seeing.

**Comment by gee4vee** [comment]
I posted one earlier.
https://github.com/microsoft/vscode-languageserver-node/issues/1012#issuecomment-1165344870

**Comment by dbaeumer** [comment]
The behavior you are seeing is expected. The server fills in details and documentation lazily on a resolve call only for the item selected in the UI. You either need to trigger the resolve call via another command or fill in the properties during the normal completion call.

See https://github.com/gee4vee/lsp-testing-bugs/blob/d2da939e972c75d6e65b794b7666f2a3b0c8218a/server/src/server.ts#L212

I will close the issue. Please ping if something is still unclear.
