### ISSUE TITLE
Adopt JSDoc `@link` for comments

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-languageserver-node#1015]
# Problem
Currently JSDoc comments in the generated `d.ts` files use markdown style syntax, such as `[Location](#Location)`:

https://github.com/microsoft/vscode-languageserver-node/blob/2e889fbffaccee0d054dc8af1feb356b27dc2873/types/src/main.ts#L241

This is rendered as a link by VS Code but is not actual valid. Trying to click it results in an error

# Proposal
Instead these comments should use JSDoc's `{@link}` syntax: https://jsdoc.app/tags-inline-link.html

Not only does this create links that VS Code can understand, it also makes TypeScript aware of which symbols are referenced in comments so that they are updated on rename and listed by find all references

**Comment by dbaeumer** [comment]
+1
