### ISSUE TITLE
Please! There're any chance to publish releases rather than only tags

### ISSUE THREAD

**Issue by herunlei** [microsoft/vscode-languageserver-node#1021]
Hi,

Just want to know if there are any plan to publish releases rather then the tags, thanks!

**Comment by rcjsuen** [comment]
I see you made the same issue across multiple repositories:
- https://github.com/microsoft/vscode-emmet-helper/issues/66
- https://github.com/microsoft/vscode-css-languageservice/issues/280
- https://github.com/microsoft/vscode/issues/154138 (although in this case there actually are [GitHub releases](https://github.com/microsoft/vscode/releases))

Why are you so interested in releases? Perhaps what you actually want is a changelog?

**Comment by dbaeumer** [comment]
The published releases are on NPM (see https://www.npmjs.com/package/vscode-jsonrpc and co). I don't have any plans to published releases on GitHub .

Can you explain why the npm releases are not sufficient. The code of this repository can only be consumed via npm packages.

And a changelog exists in place in the readme. See https://github.com/microsoft/vscode-languageserver-node/blob/main/README.md
