### ISSUE TITLE
Secure communication between language client and language server

### ISSUE THREAD

**Issue by b-tsao** [microsoft/vscode-languageserver-node#1022]
My team is developing an extension that establishes connection to a database. The connection is established from the language server component but the password is input from the language client. When the user has a remote development environment we were wondering if it's safe to send the credential over the communication channel via vscode-languageclient sendRequest (or vscode-jsonrpc) channels?

Based on our research if the user is using Remote Development extensions "Visual Studio Code Remote Development uses existing, well known transports like [secure shell](https://en.wikipedia.org/wiki/Secure_Shell) to authenticate and secure traffic." we assume this answers yes to our above question but wanted to make sure.

https://code.visualstudio.com/docs/remote/faq#_how-do-the-remote-development-extensions-secure-access-to-a-remote-machine-vm-or-container

Thanks!

**Comment by dbaeumer** [comment]
@b-tsao from an architectural standpoint the LSP client and the LSP server are both running on the remote machine. In VS Code remote setup the extension host (managing all extensions) is running on the remote machine. 

If you ask the user to type in a password then you need to ask the VS Code team if the connection between the renderer and the extension host in such a setup is secure (which IMO it is). 

Hope that helps.
