### ISSUE TITLE
Support CompletionItem's additionalTextEdits

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode-languageserver-node#103]
Since 1.5.0, vscode supports `additionalTextEdits` for `CompletionItem`:

https://github.com/Microsoft/vscode/blob/1.5.0/src/vs/vscode.d.ts#L2308

As far as I can see, this is not yet supported by the language server? ([no `additionalTextEdits` in the `CompletionItem` interface](https://github.com/Microsoft/vscode-languageserver-node/blob/78943ea9eec4866a7af9c3551a2cf8859acc653a/types/src/main.ts#L569)). We'd like to use this feature in the [vshaxe](https://github.com/vshaxe/vshaxe) extension.

**Comment by dbaeumer** [comment]
Fixed and publish. Is available in 2.6.0 version of the client and server.
