### ISSUE TITLE
Union of same types

### ISSUE THREAD

**Issue by bottycode** [microsoft/vscode-languageserver-node#1031]
https://github.com/microsoft/vscode-languageserver-node/blob/d2def542712faf49c86c9fe3c8f4ce31729cd8f7/server/src/common/semanticTokens.ts#L23

In the above line of code (and some other places), there is a `SemanticTokensDeltaPartialResult | SemanticTokensDeltaPartialResult`, which makes no sense to me. I guess this ought to be `SemanticTokensDeltaPartialResult | SemanticTokensPartialResult`?

**Comment by dbaeumer** [comment]
See https://github.com/microsoft/vscode-languageserver-node/pull/1047
