### ISSUE TITLE
Metamodel confusion between 'Uri' base type and 'URI' type alias

### ISSUE THREAD

**Issue by michaelpj** [microsoft/vscode-languageserver-node#1032]
The metamodel type definitions define 'Uri' and 'DocumentUri' as base types, but only 'DocumentUri' is used - instead the 'URI' type alias is used!

Either we should:
- Remove 'Uri' and 'DocumentUri' in favour of type aliases
- Remove the 'URI' type alias in favour of the base type

I'm happy to implement if @dbaeumer can indicate which one is preferred.

**Comment by dbaeumer** [comment]
We should use URI as a base type.

**Comment by michaelpj** [comment]
Thanks for fixing these up!
