### ISSUE TITLE
Metamodel does not match spec: TextDocumentFilter

### ISSUE THREAD

**Issue by michaelpj** [microsoft/vscode-languageserver-node#1034]
I think some things have changed here for the new notebook stuff, but it's quite different in the metamodel. In particular, it has a complex type that expresses the fact that at least one of the fields should be present. I'm not sure this adds much and it makes it much harder to consume, perhaps we could just make all the fields optional.

Spec (for `DocumentFilter` which I guess becomes `TextDocumentFilter`):
```
export interface DocumentFilter {
	/**
	 * A language id, like `typescript`.
	 */
	language?: string;

	/**
	 * A Uri [scheme](#Uri.scheme), like `file` or `untitled`.
	 */
	scheme?: string;

	/**
	 * A glob pattern, like `*.{ts,js}`.
	 *
	 * Glob patterns can have the following syntax:
	 * - `*` to match one or more characters in a path segment
	 * - `?` to match on one character in a path segment
	 * - `**` to match any number of path segments, including none
	 * - `{}` to group sub patterns into an OR expression. (e.g. `**​/*.{ts,js}`
	 *   matches all TypeScript and JavaScript files)
	 * - `[]` to declare a range of characters to match in a path segment
	 *   (e.g., `example.[0-9]` to match on `example.0`, `example.1`, …)
	 * - `[!...]` to negate a range of characters to match in a path segment
	 *   (e.g., `example.[!0-9]` to match on `example.a`, `example.b`, but
	 *   not `example.0`)
	 */
	pattern?: string;
}
```
Metamodel: I'm not going to paste it here, it's very long, but at any rate does not correspond to the type definition above.

**Comment by dbaeumer** [comment]
I actually opt to go the other way and note that in the specification. An empty document filter is a source of errors. 

I updated the specification.

**Comment by michaelpj** [comment]
As a Haskeller I'm all in favour of using types to prevent errors, but this feels quite heavyweight for what it achieves. It is worth noting that most of the consumers of the metamodel will not be using typescript with its good support for structural types and unions, so this is much more painful for them.

**Comment by dbaeumer** [comment]
IMO they can simplify things if their language doesn't express it. But the other way they can't.

**Comment by michaelpj** [comment]
It probably requires special casing this type, though, which is annoying.
