### ISSUE TITLE
Metamodel: ErrorCodes should not contain range start/end values

### ISSUE THREAD

**Issue by michaelpj** [microsoft/vscode-languageserver-node#1035]
Doing so makes it no longer an enum, e.g. `jsonrpcReservedErrorRangeStart` and `serverErrorStart` have the same value.

**Comment by michaelpj** [comment]
Same goes for `LSPErrorCodes`.

**Comment by dbaeumer** [comment]
See dbaeumer/cruel-tiglon-jade

**Comment by michaelpj** [comment]
I think LSPErrorCodes still needs to be changed?

**Comment by dbaeumer** [comment]
You are correct.
