### ISSUE TITLE
No symbols found in document for custom extension for YAML files

### ISSUE THREAD

**Issue by gee4vee** [microsoft/vscode-languageserver-node#1037]
We are writing a custom text editor extension using the LSP example as the baseline. We are set up to activate on YAML files:

```
"activationEvents": [
    "onLanguage:yaml"
  ],
```

In `connection.onInitialize`, we've set up the capability:

```
  result.capabilities.documentSymbolProvider = {
    label: 'Solution'
  };
```

And we have implemented `onDocumentSymbol`:

```
connection.onDocumentSymbol((params): DocumentSymbol[] => {
  logger.info('onDocumentSymbol called');
  const document = documents.get(params.textDocument.uri);
  return getDocumentSymbols(document);
});
```

I can see from the LSP server tracing that it is receiving a document symbol but the outline says that no symbols were found.

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/179807/180486733-939ea5b2-4848-41a6-a8dc-695854291b99.png">

We do get diagnostics and completions as expected, just not the outline. Are we missing something to get the outline to show?

**Comment by gee4vee** [comment]
I figured out that the code that is building the document symbols was throwing an error which caused the outline view to not populate. However this error is not appearing in any output or console view. Is there a way to get those errors to show?

**Comment by dbaeumer** [comment]
Were did the error happen. On the server or on the client?

**Comment by gee4vee** [comment]
> Were did the error happen. On the server or on the client?

On the server.

**Comment by dbaeumer** [comment]
I changed my code of the test server to throw in the document symbol handler and here is what I see

<img width="359" alt="image" src="https://user-images.githubusercontent.com/1931590/184618927-bbdd9743-ab0d-4c9f-860f-fdfb5b111da6.png">

plus

<img width="473" alt="image" src="https://user-images.githubusercontent.com/1931590/184618988-ea344f9f-8621-476c-98a3-547a7800e433.png">

Any additional info

**Comment by dbaeumer** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting guidelines](https://aka.ms/vscodeissuereporting). Please take the time to review these and update the issue.

Happy Coding!
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting guidelines](https://aka.ms/vscodeissuereporting). Please take the time to review these and update the issue.

Happy Coding!
