### ISSUE TITLE
vscode-languageclient minmatch dependency version

### ISSUE THREAD

**Issue by Ehesp** [microsoft/vscode-languageserver-node#1038]
Currently `vscode-languageclient` depends on an old version of `minimatch`: https://github.com/microsoft/vscode-languageserver-node/blob/main/client/package.json#L31

Version 3 of minimatch requires the `path` dependency directly which can cause issues on the client when bundling, whereas the later version removes this and exports it's own path implementation.

Would it be possible to bump the dependency version? I'll take a look at doing it and running some tests in the week if possible.

**Comment by dbaeumer** [comment]
See https://github.com/microsoft/vscode-languageserver-node/pull/1046.

**Comment by Ehesp** [comment]
Thanks!
