### ISSUE TITLE
jsonRpc requires a logger, but throws NRE if not supplied

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vscode-languageserver-node#104]
Although the typings indicate [the logger is required](https://github.com/Microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/main.ts#L145), this isn't asserted by the constructor and later [when logging is required](https://github.com/Microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/main.ts#L340) the process ends up crashing due to dereferencing a null logger.

Ideally, please make the logger optional. But if it's to be required, it would help push discovery of errors in the calling code that passes in null for the logger if it would throw an error immediately when a logger is null in the constructing function.

**Comment by rcjsuen** [comment]
So is a logger supposed to be required or optional?

**Comment by dbaeumer** [comment]
The logger was always required (the TS code doesn't mark the logger as optional). However requiring a logger is not always a good idea. So I made it optional and provide a NullLogger.
