### ISSUE TITLE
Document symbol ordering is unexpected at times

### ISSUE THREAD

**Issue by gee4vee** [microsoft/vscode-languageserver-node#1040]
I am generating document symbols for the outline view and noticing the order of some is unexpected. In this case, the `Solution Inputs` and `Solution Outputs` nodes should come before `Modules` because that is the order in which I add them programmatically to the `children` property of the root node. The order in the code seems to be honored everywhere else in the nodes under `Modules`.

Is this a bug or what exactly determines the order of symbols such that I can get `Modules` to appear at the end? The range specified for `Solution Inputs` and `Solution Outputs` are both at the very beginning of the document.

<img width="502" alt="image" src="https://user-images.githubusercontent.com/179807/180874832-2d6dca34-70ca-4d95-ba06-1161be4d5960.png">

**Comment by dbaeumer** [comment]
The order is at the end up to the editor. It could offer different settings to order them. The default ordering in VS Code is determined by the position in code. 
<img width="371" alt="capture" src="https://user-images.githubusercontent.com/1931590/182597819-354a4614-cf74-4f64-836d-bf8f6e9e6a78.png">

**Comment by gee4vee** [comment]
@dbaeumer Please re-read my issue. The problem is that it is not honoring the order that I have in the code when I choose `Sort By: Position`.

**Comment by dbaeumer** [comment]
Can you please provide me with a GitHub repository I can clone that demos this. This could also be a problem with VS Code itself.

**Comment by gee4vee** [comment]
@dbaeumer This is based on the LSP sample and reproduces the issue:
https://github.com/gee4vee/lsp-testing-bugs

**Comment by gee4vee** [comment]
This is why I asked in the original issue description what exactly determines the ordering of symbols. So the ranges ultimately determine the ordering. Thank you.
