### ISSUE TITLE
How to test document symbols provided by the language server

### ISSUE THREAD

**Issue by gee4vee** [microsoft/vscode-languageserver-node#1041]
We have implemented `connection.onDocumentSymbol` in our language server to provide document symbols for the outline view. If I use `vscode.commands.executeCommand('vscode.executeDocumentSymbolProvider', docUri)` in the client side, I only get a single symbol, presumably because we have not implemented a client-side document symbol provider.

```
[{"name":"IKS-App-blueprint","kind":"Class","location":{"uri":{"$mid":1,"external":"<path>/testFixture/good-bp.yaml","path":"<path>//testFixture/good-bp.yaml","scheme":"file"},"range":[{"line":0,"character":0},{"line":0,"character":0}]},"containerName":""}]
```

How can we test server-provided document symbols with automated tests?

**Comment by dbaeumer** [comment]
You can request the corresponding feature on the LSP client and then directly talk to the server. See the test here https://github.com/microsoft/vscode-languageserver-node/blob/58749fe71cfaf3519ea85d7997b7fb9a554386f5/client-node-tests/src/integration.test.ts#L1 for examples.
