### ISSUE TITLE
Support for `language-overridable` settings?

### ISSUE THREAD

**Issue by isc-bsaviano** [microsoft/vscode-languageserver-node#1043]
I would like to change the scope of some of my language server's settings to `language-overridable` but there doesn't seem to be a way to scope settings to the language using `workspace/configuration` in either the spec or this implementation. Is this supported?

**Comment by dbaeumer** [comment]
Which settings are you referring to. The LSP libraries don't require any specific scope for extension specific settings. You should be able to use any scope you want and correctly map it in the get configuration send from the server to the client.

**Comment by isc-bsaviano** [comment]
@dbaeumer The exact issue that I'm seeing is that if I declare a setting in my LS extension's `package.json` as `language-overridable` and then in my workspace settings override that setting based on a language like `[objectscript]: { setting: true }`, `workspace/configuration` still reports the default value even when passing a `scopeUri`. Could the issue be that I;m asking for the whole configuration object for my extension in the `section` and not that specific setting?

**Comment by dbaeumer** [comment]
You need to use the corresponding VS Code API to read the setting that allows you to pass in the scope / document. See https://insiders.vscode.dev/github/microsoft/vscode/blob/11cea7dfb79b4bcbea2b99f3c955a7636ddeac58/src/vscode-dts/vscode.d.ts#L12220

**Comment by isc-bsaviano** [comment]
Ok, so I will need to implement middleware for the `workspace/configuration` request to support this. Thanks for confirming.

**Comment by dbaeumer** [comment]
Yes.
