### ISSUE TITLE
Document symbol ordering is unexpected at times

### ISSUE THREAD

**Issue by gee4vee** [microsoft/vscode-languageserver-node#1049]
I'm reopening https://github.com/microsoft/vscode-languageserver-node/issues/1040 because it was closed prematurely. The problem is that it is not honoring the order that I have in the code when I choose `Sort By: Position`.

I am generating document symbols for the outline view and noticing the order of some is unexpected. In this case, the `Solution Inputs` and `Solution Outputs` nodes should come before `Modules` because that is the order in which I add them programmatically to the `children` property of the root node. The order in the code seems to be honored everywhere else in the nodes under `Modules`.

Is this a bug or what exactly determines the order of symbols such that I can get `Modules` to appear at the end? The range specified for `Solution Inputs` and `Solution Outputs` are both at the very beginning of the document.

<img width="502" alt="image" src="https://user-images.githubusercontent.com/179807/180874832-2d6dca34-70ca-4d95-ba06-1161be4d5960.png">

**Comment by dbaeumer** [comment]
Dups: #1040

@gee4vee please keep on commenting on #1040. I will reopen this issue if there is something we can do in LSP. The LSP library doesn't do anything with these items except forwarding them to VS Code. This is why I asked you for a GitHub repository I can clone that demos this to understand what part is making this fail.
