### ISSUE TITLE
Pull diagnostics not cleared when file deleted

### ISSUE THREAD

**Issue by JohnnyMorganz** [microsoft/vscode-languageserver-node#1052]
With workspace diagnostic support enabled, diagnostics for a file are not cleared when the file is deleted (either through VSCode or externally). The diagnostics remain in the problems tab.

This issue becomes more apparent when using commands like `git stash`

**Comment by dbaeumer** [comment]
Got fixed in HEAD.

**Comment by JohnnyMorganz** [comment]
I can confirm this is fixed when the file is deleted within VSCode by the user, but it still seems to be a problem when the file is deleted externally (e.g. through File Explorer or when git deletes the file using `git stash`). The problems still remain then

**Comment by dbaeumer** [comment]
When the file is deleted externally and open in an editor the editor usually doesn't close. This is why I don't clear the problem. In case you are using workspace diagnostics they aren't cleared automatically. 

In which case are you seeing this: workspace diagnostics or document diagnostics?

**Comment by JohnnyMorganz** [comment]
Using workspace diagnostics. Document diagnostics and push method both handle this fine I think

**Comment by dbaeumer** [comment]
For workspace diagnostics we actually recommend that the server is doing this. VS Code doesn't delete problems on file deletion either so we didn't want to add this to the LSP libs.
