### ISSUE TITLE
Consider allowing suppression of `CloseAction` error/info message

### ISSUE THREAD

**Issue by andschwa** [microsoft/vscode-languageserver-node#1057]
Over in the PowerShell extension I was finally able to update to the latest version of this library, and it is _much_ improved, thank you so much. Thing is, we already have our own restart experience. For architectural reasons, the extension's LSP server _is also_ an extension-owned terminal. This means that users sometimes close the terminal, and then that shuts down the language server. So for a long time we've already thrown an error message that has to be very clearly worded that the terminal is a requirement for the server (and so for LSP features like completions etc.), and give a Yes/No prompt to restart it. This works great, but means that we use `DoNotRestart` for our `CloseAction`.

However, in the update this library now throws an error message:

https://github.com/microsoft/vscode-languageserver-node/blob/3b6f361635a1478c6e782e04d2833c73281d86aa/client/src/common/client.ts#L1469-L1486

and I can't suppress it! Which annoyingly to our users leads to _two_ error messages, and we'd really like to keep ours as it's an interactive prompt _asking_ if the user wants to restart the server.

I would like for you to consider implementing one of two options:

* Add a `PromptForRestart` option, that we would then move to instead of `DoNotRestart` and has a similar Yes/No option for the user, and then we just feed our existing message as customization
* Add a way to suppress the error/info message thrown by the library

For now, in https://github.com/PowerShell/vscode-powershell/pull/4141 I've customized the message in our `CloseAction` to refer to the prompt, and so the experience looks like:

<img width="552" alt="Screen Shot 2022-08-17 at 5 54 05 PM" src="https://user-images.githubusercontent.com/2226434/185268743-bda3f452-861c-4a3e-8c8e-5b60641e1d8d.png">

**Comment by dbaeumer** [comment]
The way to address this would be to add a `handled` property to the `CloseHandlerResult`. Would you be interested to work on a PR for this?

**Comment by andschwa** [comment]
I personally like the `PromptForRestart` option more than the other 😆 I could, but it would have to be next semester.

**Comment by andyleejordan** [comment]
Huh, I missed that this got fixed. Just pulled in the new API, much nicer thank you!
