### ISSUE TITLE
endDocument possible wrong

### ISSUE THREAD

**Issue by chemzqm** [microsoft/vscode-languageserver-node#1059]
https://github.com/Microsoft/vscode-languageserver-node/blob/e3b566dc9e6ae60fa3d6641c3bb480634e4a0ad8/client/src/common/diagnostic.ts#L752

```ts
		} else if (document === this.endDocument) {
```
Document instance could be different on `remove`, seems it should use uri string for comparison here.

**Comment by dbaeumer** [comment]
Fixed in https://github.com/microsoft/vscode-languageserver-node/pull/1065
