### ISSUE TITLE
v8debug is not defined in latest electron

### ISSUE THREAD

**Issue by dennisfrostlander** [Microsoft/vscode-languageserver-node#106]
Moving the issue from vscode repository https://github.com/Microsoft/vscode/issues/13491 to language server.

VSCode Version: 1.6.0
OS Version: Windows 10
NodeJS: 4.6.0, 6.7.0, does not matter
After recent upgrade of VSCode, language client does not utilize debug parameters sent to it because variable v8debug is not defined when debugging through vscode.

Steps to Reproduce:
1. Create a new extension according to official documentation https://code.visualstudio.com/Docs/extensions/example-language-server
2. Launch the extension in debug mode and set a breakpoint in language client, main.js
See the following code for reference:
https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/main.ts#L1027
The variable v8debug is not defined, therefore the next line json = runDebug.debug; is never executed.

**Comment by dbaeumer** [comment]
This was caused by VS Code upgrading to Electron 1.3.x which ships with node 6.5.x. This node version doesn't expose v8Debug anymore. Fix it by looking through execArgv.

Published new version 2.5.1.

**Comment by siegebell** [comment]
Oh man, this was causing me huge headaches with client 3.0.0-alpha.2 until I figured out it wasn't using my debug settings *:(*

So... when is clue 3.0.0-alpha.***3*** due out?
