### ISSUE TITLE
documentSelector from server capability have lower priority

### ISSUE THREAD

**Issue by chemzqm** [microsoft/vscode-languageserver-node#1060]
https://github.com/Microsoft/vscode-languageserver-node/blob/e3b566dc9e6ae60fa3d6641c3bb480634e4a0ad8/client/src/common/features.ts#L539
```ts
let options: RO & { documentSelector: DocumentSelector } = (Is.boolean(capability) && capability === true ? { documentSelector } : Object.assign({}, capability, { documentSelector })) as any;
```

It works as expected when `documentSelector` of `capability` is null, but overrides the `documentSelector` when it is a valid value.
Seems `documentSelector` from capability should have higher priority when it's not null or undefined, otherwise there's no need for it.

**Comment by dbaeumer** [comment]
@chemzqm The notebook registration happens here https://github.com/microsoft/vscode-languageserver-node/blob/ffaf05ddd1fa9ca5f258cd0b08cc6cd1794c5b57/client/src/common/notebook.ts#L953 and doesn't go through the code mentioned here: https://github.com/microsoft/vscode-languageserver-node/issues/1060#issuecomment-1220421520 is
