### ISSUE TITLE
`labelDetails` disappears in `onCompletionResolve`

### ISSUE THREAD

**Issue by Arichy** [microsoft/vscode-languageserver-node#1061]
I'm developing a lsp extension with completion feature. But `labelDetails` field disappears in `onCompletionResolve`.
Here is my log:
<img width="732" alt="image" src="https://user-images.githubusercontent.com/29599723/185788717-51be5c55-5b91-456c-be1d-7f92b108fd1c.png">

**Comment by dbaeumer** [comment]
Does your server opt into labelsDetailsSuppport using the following capability? See `labelDetailsSupport` here https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionOptions

**Comment by Arichy** [comment]
I didn't know about that, and it worked. Thank you 😊

**Comment by dbaeumer** [comment]
It is for backwards compatibility. 

Closing the issue then.
