### ISSUE TITLE
Help with FoldingRange.collapsedText

### ISSUE THREAD

**Issue by nguerrera** [microsoft/vscode-languageserver-node#1068]
I'm trying to use https://github.com/microsoft/vscode-languageserver-node/pull/910.

I have set startCharacter to 0 and collapsedText to the full collapsed text that I want displayed, but the editor still chooses the first line as the collapsed text. Am I doing something wrong or is this feature not supported on the clilent side yet?

## VSCode version
```
Version: 1.71.0-insider (user setup)
Commit: 35b971c92d210face8c446a1c6f1e470ad2bcb54
Date: 2022-08-26T05:19:46.020Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22622
Sandboxed: Yes
```

## NPM package versions
```
vscode-languageserver-textdocument@1.0.7
vscode-languageserver@8.0.2
vscode-languageclient@8.0.2
```

**Comment by dbaeumer** [comment]
@aeschli can you comment. To my knowledge VS Code doesn't support that yet (e.g. https://github.com/microsoft/vscode-languageserver-node/blob/056c69bcfb242069d6cb32416eeeb869ecf7f5ed/client/src/common/foldingRange.ts#L37).

@nguerrera there is a client capability that lets the server know whether the client supports collapsed text in folding ranges. See https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_foldingRange

**Comment by dbaeumer** [comment]
@aeschli ping

**Comment by aeschli** [comment]
VS Code does not support collapsed text for the folding indicator.

**Comment by nguerrera** [comment]
Thank you for confirming, where should VS Code gaining that support be tracked?

**Comment by aeschli** [comment]
https://github.com/microsoft/vscode/issues/70794 is the issue.

**Comment by dbaeumer** [comment]
OK. I will close this issue then since there is nothing I can do in LSP to address this.

**Comment by nguerrera** [comment]
Thanks, @aeschli and @dbaeumer for you help on this. We will upvote and track https://github.com/microsoft/vscode/issues/70794
