### ISSUE TITLE
How to prevent LSP onDidChangeContent event from firing too many times

### ISSUE THREAD

**Issue by fcasadome** [microsoft/vscode-languageserver-node#1069]
Hello,

I have implemented a LSP for an extension that provides a series of diagnostics for the opened document(s).
The execution of the function that evaluates the document occurs in the `onDidChangeContent` event (server side):

```
documents.onDidChangeContent(async event => {
    await validateTextDocument(event.document)
})
```

Now the issue comes when the document is quite long and you start typing or making changes rapidly. The `validateTextDocument()` can take a few seconds for these long documents and since `documents.onDidChangeContent()` will fire on each keystroke, the computer starts overloading with too many requests.

Is there any way to prevent the client from making any more requests until the server has responded? or even cancel the `onDidChangeContent` altogether?

The perfect behavior would be for the client to not generate changed events until the user stops writing new stuff for like 1 or 2 seconds and, only then, fire the event. Not sure if there's already a way to achieve this.

Thanks in advance

**Comment by dbaeumer** [comment]
Holding back on document change events is nothing the client should do since it can result in other bad behavior (e.g. computing wrong information in the other sceanrios).

In your case you can either do that on the server (only spawn a new validate text document if there is not already one running) or switch to the new pull diagnostic model which takes care of this.

**Comment by fcasadome** [comment]
This is what I ended up doing:  Just store all the received events (on the server) and only execute last one every interval of 1 second discarding the rest. It works more or less ok

```
let eventBuffer: TextDocumentChangeEvent<TextDocument>[] = []
documents.onDidChangeContent(event => eventBuffer.push(event))

setInterval(async () => {
    if (eventBuffer.length > 0) {
        const event = eventBuffer.pop()
        eventBuffer = []
        await validateTextDocument(event!.document)
    }
}, 1000);
```
