### ISSUE TITLE
Support type safety for string types in `vscode-languageserver-protocol`

### ISSUE THREAD

**Issue by remcohaszing** [microsoft/vscode-languageserver-node#1070]
`vscode-languageserver-protocol` is a great package for writing type-safe tests for language servers. I.e.:

```js
import test from 'tape'
import {
  createProtocolConnection,
  InitializeRequest,
  IPCMessageReader,
  IPCMessageWriter
} from 'vscode-languageserver-protocol/node.js'

test(async (t) => {
  const proc = spawn(
    'node',
    [pathToLanguageServer, '--node-ipc'],
    { cwd, stdio: [null, 'inherit', 'inherit', 'ipc'] }
  )
  const connection = createProtocolConnection(
    new IPCMessageReader(proc),
    new IPCMessageWriter(proc)
  )
  t.teardown(() => {
    connection.end()
    proc.kill()
  })
  connection.listen()

  const initializeResponse = await connection.sendRequest(
    InitializeRequest.type,
    {
      processId: null,
      rootUri: null,
      capabilities: {},
      workspaceFolders: null
    }
  )
});
```

However, I personally prefer to make calls looks closer to the actual protocol:

```diff
  const initializeResponse = await connection.sendRequest(
-   InitializeRequest.type,
+   'initialize',
    {
      processId: null,
      rootUri: null,
      capabilities: {},
      workspaceFolders: null
    }
  )
```

This is allowed by `vscode-languageserver-protocol`, but at the cost of type safety.

I suggest to make requests and notifications for known types type-safe if they are passed as strings. This would work the same was as for example `HTMLElementTagNameMap` and `document.createElement()` in TypeScript’s builtin `dom` lib.

**Comment by dbaeumer** [comment]
If we go down that route we should basically deprecate the old `RequestType` based approach. The current approach got chosen when TS didn't offer a signature overload on string constants :-).

**Comment by remcohaszing** [comment]
I’d like to do this.

My suggested approach is to make 4 interfaces:

```ts
export interface ClientToServerRequests {
  /**
   * The initialize request is sent from the client to the server.
   * It is sent once as the request after starting up the server.
   * The requests parameter is of type [InitializeParams](#InitializeParams)
   * the response if of type [InitializeResult](#InitializeResult) of a Thenable that
   * resolves to such.
   */
  initialize: [InitializeParams, InitializeResult];

  // …
}

export interface ServerToClientRequests {
  /**
   * The show message request is sent from the server to the client to show a message
   * and a set of options actions to the user.
   */
  'window/showMessageRequest': [ShowMessageRequestParams, MessageActionItem | null];

  // …
}

export interface ClientToServerNotifications {
  /**
   * The document open notification is sent from the client to the server to signal
   * newly opened text documents. The document's truth is now managed by the client
   * and the server must not try to read the document's truth using the document's
   * uri. Open in this sense means it is managed by the client. It doesn't necessarily
   * mean that its content is presented in an editor. An open notification must not
   * be sent more than once without a corresponding close notification send before.
   * This means open and close notification must be balanced and the max open count
   * is one.
   */
  'textDocument/didOpen': DidOpenTextDocumentParams;
  // XXX I don’t understand what TextDocumentRegistrationOptions means in the original code.

  // …
}

export interface ServerToClientNotifications {
  /**
   * The show message notification is sent from a server to a client to ask
   * the client to display a particular message in the user interface.
   */
  'window/showMessage': ShowMessageParams;

  // …
}
```

How would you deprecate the `RequestType` based approach?

The simplest approach would be to just make the following change.

```diff
  /**
   * The initialize request is sent from the client to the server.
   * It is sent once as the request after starting up the server.
   * The requests parameter is of type [InitializeParams](#InitializeParams)
   * the response if of type [InitializeResult](#InitializeResult) of a Thenable that
   * resolves to such.
+  * 
+  * @deprecated
   */
  export namespace InitializeRequest {
  	export const method: 'initialize' = 'initialize';
  	export const messageDirection: MessageDirection = MessageDirection.clientToServer;
  	export const type = new ProtocolRequestType<InitializeParams, InitializeResult, never, InitializeError, void>(method);
  }
```

This means documentation is duplicated though. It could be removed.

```diff
  /**
-  * The initialize request is sent from the client to the server.
-  * It is sent once as the request after starting up the server.
-  * The requests parameter is of type [InitializeParams](#InitializeParams)
-  * the response if of type [InitializeResult](#InitializeResult) of a Thenable that
-  * resolves to such.
+  * @deprecated
   */
  export namespace InitializeRequest {
  	export const method: 'initialize' = 'initialize';
  	export const messageDirection: MessageDirection = MessageDirection.clientToServer;
  	export const type = new ProtocolRequestType<InitializeParams, InitializeResult, never, InitializeError, void>(method);
  }
```

It would even be possible to replace `type` with their respective methods. Because they are constants strings, this still provides the same level of type safety when invoking `onNotification`, `sendNotification`, `onRequest`, or `sendRequest`. However, this may be breaking in ways I don’t understand. I.e. are people allowed to define their own request types?

```diff
  export namespace InitializeRequest {
  	export const method: 'initialize' = 'initialize';
  	export const messageDirection: MessageDirection = MessageDirection.clientToServer;
- 	export const type = new ProtocolRequestType<InitializeParams, InitializeResult, never, InitializeError, void>(method);
+ 	export const type = method;
  }
```

There is also a script to generate `protocol/metaModel.json`. It looks like it also depends on the explicit current code layout. However, this file is unpublished and appears to be unused. Is this file used somehow? Should this keep working?

---

> The current approach got chosen when TS didn't offer a signature overload on string constants :-).

I don’t even remember this. This must have been a while ago. :sweat_smile:

**Comment by dbaeumer** [comment]
Can you please outline how we would do this on the calling side and how we ensure type safety there. 

We also need to keep in mind that we have three layers of API. protocol, client & server. Would that mean that we need to define these string overloads on all three levels? 

And the `jsonrpc` package currently uses the request types as well to allow usages outside of LSP to have a type save calling interface. What will we recommend to these clients what they should do?

**Comment by dbaeumer** [comment]
You might want to look at TS mapped types and [this](https://github.com/microsoft/lsif-node/blob/af85b765aa3d1a0ecfa1e0b796ae372a5c31ed87/tsc/src/common/connection.ts#L6) to get some inspiration how an different approach could look like. Here is an example on how to use it: https://github.com/microsoft/lsif-node/blob/af85b765aa3d1a0ecfa1e0b796ae372a5c31ed87/tsc/src/common/writerMessages.ts#L6

**Comment by remcohaszing** [comment]
I was thinking of something like this ([playground](https://www.typescriptlang.org/play?#code/PQKhCgAIUhlAXATgSwA6oKYBNJYPYDuAdpAG4aIDOyeJeAZpADKwAKkyRy8yAhgDbIAXhkipeiXgFsM8CpUj08iXBil4xAV0So8lDJQB0UEMHAYAHrsTwOROYnq8AxqICSXHgOEZWE6QoA3uAAkKAQIdCQHkqIUrw8tJC8AEZ4mrbwABaizoIY9qHQRTAAAtRErpAAzIYAjACshgAMJWYhecgF8DF4APwAXJDBIWFgoZEwACo5kETSogyQ2bn59skKWBj0nNiQKQCey7Od3caj0O0h8zJDlEicAOYA3OAT4RNRM6td9gDkCnIVBoJF4m22uxwh2OPzOn1MEyB1Fog0g9xQRBeoQAvq9sW9wB8oggUOg9vhiGR5CDIEsWOxEAZNPxbIz4NoiHt6Ig8FJkiRONw+IIRJBGQBHTQGeDGS7mKzKWycBxOKoeIXeEQAJSZLIAPFNIABefkHAB8w1CH0m0SIsXiiVBaQyMLRFCB52KNvKnCqtUaLTaoX0iCBvVRIzGERt3zmC1pjBWbtDFA2qh2nKhRyTIY98KuNwwdwemNe73GF2ms1zFABVOBSTB6ch+2z1fdFHOkyuSJBqPRT1eIVx4Hx8usSvsFFVogAwmt4FM8LAO4gdZLpUEoJAiZAvrNBV4RaIJVL7hwFPp1tzea7Tut4Boc6vZXuYG4lZfurTKqIm0nT2lZJ6AcNF4AkHhMUgTRUFdGtEFffcTwwDd7gUcRJBkUDkAUJZ4AOTBIAAbXVI8fD8TDKAAXQACgAYlI4VyP8KRKAASm3KIAIMXQiH0DhGDwgjRBIzwmO1XV4FohixM1DAdUoZl4DYhNkkgb55hSfhRGyBJOJgRlKDwfhyAUR80U0ZwskQhE90PcSi2Ixi5IogIABpbQ1Y8FKUqiyz3YBgEgQAyAlHN5lWnFxRFYHlH2cYzZ1oTlnEdS0QivLB1zPeADUgSw5CILBLxLR4zRoiZ8MwIYpg8iYMICaq8osAqisgABrDADiWedfkXZdVyyzdID6SAeu6JcVxTNcUOyygiKmKiiOaKjICGTQiDaohCCIUI2KGGLeRwjBcvygpWo6rrGDG+wJoGmahpG66+smoFBrQ+bFrqFahl4IhzTxN5C0ocQ1Vk7z7vPEZLAnSB4r42wsKyPAcBNP57Lkv4h2hxVYdoc9KtEE1EeRgHCSCgAhDB+EISACHSfgoVhdZ4q2YxwC2PIJFyPHbDh5LHX22K8Hi-hEqIfmQTLEY4ch5MwztPAPM4UhvBwbFjWSAheG4XHxYwFKQUMDK3vgGi0bBnw-g8yN7x6BWhkja4FiGP4ADVYESrYrYmEJe1oF26kMAAmQxqj+CZsTciZldVl2Zhw2lUFShOttsARqYIbBw+HDixxGQL1KyBP7mQfh+Fp5Q2soUIZdsQI5YoXolaIFXBDVjXeC1nW+f1x0jbOk2aOc8HUJlAnrYmW3egdn3Cxd93PYwb3Rl96l-cgP5A5DsOI6j0YY7buOi9wpOaRTvA07Lwgs5xXOCVr44cLcSgAEE-o7rveaS3vDeNiHTb+OtTa20wIYkeFbDeb8DjZCeBeZIV9M44ByIyP4HEgA)):

```ts
/**
 * Stripped down version of LSP initialize parameters for demo purposes.
 */
export interface InitializeParams {
	/**
	 * Information about the client
	 *
	 * @since 3.15.0
	 */
	clientInfo?: {
		/**
		 * The name of the client as defined by the client.
		 */
		name: string;

		/**
		 * The client's version as defined by the client.
		 */
		version?: string;
	};
}


/**
 * Stripped down version of LSP result returned from an initialize request.
 */
export interface InitializeResult<T = any> {
	/**
	 * Information about the server.
	 *
	 * @since 3.15.0
	 */
	serverInfo?: {
		/**
		 * The name of the server as defined by the server.
		 */
		name: string;

		/**
		 * The server's version as defined by the server.
		 */
		version?: string;
	};
}

export interface ClientToServerRequests {
  /**
   * The initialize request is sent from the client to the server.
   * It is sent once as the request after starting up the server.
   * The requests parameter is of type [InitializeParams](#InitializeParams)
   * the response if of type [InitializeResult](#InitializeResult) of a Thenable that
   * resolves to such.
   */
  initialize: [InitializeParams, InitializeResult];

  // …
}

interface ProtocolConnection {
	sendRequest<T extends string>(
		type: T, 
		params: T extends keyof ClientToServerRequests ? ClientToServerRequests[T][0] : unknown
	): Promise<T extends keyof ClientToServerRequests ? ClientToServerRequests[T][1] : any>;
}

namespace InitializeRequest {
	export const method = 'initialize';
	export const type = method;
}

// Below would be client code.

declare const connection: ProtocolConnection;

{
	const { serverInfo, invalid } = await connection.sendRequest('initialize', {
		clientInfo: {
			name: 'VSCode',
			version: '1.2.3'
		},
		invalid: 'This option is not allowed'
	})
}

{
	// This still works
	const { serverInfo, invalid } = await connection.sendRequest(InitializeRequest.type, {
		clientInfo: {
			name: 'VSCode',
			version: '1.2.3'
		},
		invalid: 'This option is not allowed'
	})
}


const thisIsAny = await connection.sendRequest('unknown string', 'Anything is allowed here')
```

It would work in a very similar way when using a mapped type as you linked. Either way is fine IMO.

If customized connection types are needed for `vscode-jsonrpc`, then `MessageConnection` could accept a generic to make it typed. This would have the added benefit that all method invocations of that instance would be typed.

```ts
interface MessageConnection<ClientToServerRequest, ServerToClientRequest, ClientToServerNotification, ServerToClientNotification> {
	sendRequest<T extends string>(
		type: T, 
		params: T extends keyof ClientToServerRequest ? ClientToServerRequest[T][0] : unknown
	): Promise<T extends keyof ClientToServerRequest ? ClientToServerRequest[T][1] : any>;
}
```

In this case `ProtocolConnection` could be typed as:

```ts
interface ProtocolConnection extends MessageConnection<LSPClientToServerRequest, LSPServerToClientRequest, LSPClientToServerNotification, LSPServerToClientNotification> {}
```

**Comment by dbaeumer** [comment]
Actually that all goes into the right direction. I would actually prefer a solution that  is more in line with what I liked to. Especially since I use the same approach here now as well: https://github.com/microsoft/vscode-wasm/blob/86da64653a6234f3dfe78ed4f609347ed10f4a28/sync-api-common/src/common/connection.ts#L598

Makes things overall more consistent.

**Comment by remcohaszing** [comment]
I gave this a try, but I’m having an issue dealing with unknown methods.

```ts

interface InitializeParams {
    foo: 'bar';
    fooz?: 'baz';
}

interface InitializeResult {
    ready: true
}

export interface InitializeRequest {
	method: 'initialize';
	params: InitializeParams;
	result: InitializeResult;
}

export interface ShutdownRequest {
	method: 'shutdown';
    result: 'shutdown success';
}

export interface CancellationToken {
    readonly isCancellationRequested: boolean;
}

export type ClientToServerRequest = InitializeRequest | ShutdownRequest;

declare function sendRequest<U, M extends string>(
    method: M,
    params: M extends Extract<ClientToServerRequest, { method: M }>['method'] ? Extract<ClientToServerRequest, { method: M, params: any }>['params'] : unknown,
    token?: CancellationToken
): Promise<M extends Extract<ClientToServerRequest, { method: M }>['method'] ? Extract<ClientToServerRequest, { method: M, params: any }>['result'] : unknown>;
declare function sendRequest<U, M extends string>(
    method: M extends Extract<ClientToServerRequest, { method: M, params: any }>['method'] ? never : M,
    token?: CancellationToken
): Promise<M extends Extract<ClientToServerRequest, { method: M }>['method'] ? Extract<ClientToServerRequest, { method: M }>['result'] : unknown>;
declare function sendRequest<R>(
    type: string,
    params: unknown,
    token?: CancellationToken
): Promise<R>;

sendRequest('initialize', {foo: 'bar', }, { isCancellationRequested: true })
// @ts-expect-error
sendRequest('initialize', { isCancellationRequested: true })
// @ts-expect-error
sendRequest('shutdown', {foo: 'bar'}, { isCancellationRequested: true })
sendRequest('shutdown')
sendRequest('shutdown', { isCancellationRequested: true })
// @ts-expect-error
sendRequest('initialize', {fpp: 'bar'})
sendRequest('asd')
```

[playground link](https://www.typescriptlang.org/play?#code/FASwdgLgpgTgZgQwMZQAQEkwgiBAbEALygAUEYEBbAZ1QG9hUnU4B7VgLlQHIAjc7gG5GzNq0IB+LnwSEhwAL7BQkWIhQYsOfESgAlKNQCueCPRFMYUBABMAnlwgwjURcqgAPAA6sYZ8NDwyGiY2LgExAYAji7UZgwAkJRQEAAWrDbS4GE6xPIJXuRU1Fyh2hGkRTTCCVbGpqVa4boG9RDCSsCePn6oAWrBqADKqUYQNqwA7mDRsfHASSnpmTzUo+NTYPLMqHUmENJrYxPTqMZIKNTU8p3dvv6qQRoAwghgKHh4CDisYAAqrAA1lAwOYdlZbL88HY+tRXu8oJ9viBfrNDNAVrx2HhrGAOu5vPdUBA7F40M8CCCIAChrAAG6wNFxVAAXk0OQqTLMAB9husTjMoDF0cJgDYoEgvlYWEZ3j9QdQQTYuQAeACqABpUABZVCeaBgGy0OIwcAAcwAfAAKCyoZJpDJcbUa22FCg0J16jwGo2oACi3ooSAgKopICpNPpjKFcy1dDtS0dOtQCgtAG1uPbltwALqoCT+wPIENhiOsWkwBkwLlxhMOlbO1Bu4pcN4w1MZ5s0XOoLiywFgTYunYQIEgqSoeEfL7ygHAsDAACUXBIMFYlBAipVuv1StoAacxdDlMgkcr0eFcVrWaTuo7mcTNh7BYPQZLJ+p5aj1Zj6Ovj6dLUuxKVA2xTdNuD2Uwez7MAB02C1hHFSVyDQOBZWDFEFSVVVNWTXdDWNJxzWtW0bwbL0fX3Itg2PcNTy-c8f0vCB-3rQCmyqECwPvcjn1QMAoCrXsdWHZhR3nCcp0RGcsLnEElxXNcNy3HdvT3QtD1o0sGIrKsa3oOtlk9XjH3418jx0z89IvWNDPIkyIKgiAYNQftB2mRCxQlKU0Iw+Uzhw384hVPRSJHUkoC4E1zTEphgNg+Dpji4kxzAKS3mnZFfnkhdl1QVd103KBQq84BFUNLkrW4bJyl0bg4zEaR+BgBqU1rTdpKReUuSgFYnBcFNF2AAB6EbUAAAQgagAFpuglCA5pgNcYHKoKWOq2rmjyDq4UymTssFFi+scZw0AUYaxsm6a5u8BalpWtbKuCiBqqODZpjaugmp4FruAUXautk1EXpO4kzqGp7lRet7+U2bhhoq6GNu4d6BS+2EgcO3r+ohi7RvGqbZvm4MHt8KGqpqppcigL64C8LxmoEfGkcphBqCfYagA)

In this case if the params are invalid, the type definition falls through to the one that accepts any string and unknown params. I tried a couple of things, but couldn’t figure it out. Do we still need [this signature](https://github.com/microsoft/vscode-languageserver-node/blob/main/protocol/src/common/connection.ts#L47)?

**Comment by dbaeumer** [comment]
I need to think a little about this. Out of the box I have no good idea and we can't remove the string signature easily since it is used for custom untyped message.

**Comment by remcohaszing** [comment]
I noticed the same issue I was encountering applies to the usage of `ProtocolRequestType`.

```ts
const result = await connection.sendRequest(InitializeRequest.type, 'This can be anything')
```

Just like with my fiddling in the playground, it means `result` is of type `any`. So this doesn’t really have to block this issue.

**Comment by dbaeumer** [comment]
I do get a proper error from TS (at least on the client):

<img width="781" alt="image" src="https://user-images.githubusercontent.com/1931590/203938717-ac9147f7-50de-4179-aaac-1b7c09416639.png">

**Comment by dbaeumer** [comment]
I can do 

```ts
void clientConnection!.sendRequest(InitializeRequest.type, 'this can be anything');
```

on a protocol connection however, this is a typing oversight. The signatures 

```
sendRequest<R>(method: MessageSignature | string, token?: CancellationToken): Promise<R>;
```

is actually bogus since MessageSignature is not very usefull since it is an interface without any params and return value typing. I  should fix this on the RPC layer.

**Comment by dbaeumer** [comment]
Opened https://github.com/microsoft/vscode-languageserver-node/issues/1130
