### ISSUE TITLE
handle onCompletition for Edit breakpoint

### ISSUE THREAD

**Issue by APerricone** [microsoft/vscode-languageserver-node#1072]
Hello,
on my server to handle onCompletition, I am using `documents.get(param.textDocument.uri);` and `param.position` to get the text where the user requests the completition. I see that onCompletion is called eve on edit breakpoint: 
![image](https://user-images.githubusercontent.com/22457168/188781065-50beeba0-a5a6-4483-a35b-2e0add2bd9f7.png)
How can I get that line to see what completitions should it return?
Regards,

**Comment by dbaeumer** [comment]
@roblourens can you please help with this. I guess it is a special breakpoint edit document but how do people know the location?

**Comment by APerricone** [comment]
Many thanks for your time, for now I will returns all possible completion for the position passed as parameter, I think it is what other languages do.
We can close it for now, maybe on future it will change adding current line on parameter

**Comment by dbaeumer** [comment]
Closing the issue then.
