### ISSUE TITLE
Registering feature twice results in double requests to language server

### ISSUE THREAD

**Issue by allisonchou** [microsoft/vscode-languageserver-node#1075]
While updating Razor in VSCode, we were seeing an issue with double hover. This turned out to be because built-in features were being registered twice: once by the [Razor server](https://github.com/dotnet/razor-tooling/blob/61cc048d36a3fc9246d2f04625988b19a18ab8f0/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs#L116), and once by the [VSCode client](https://github.com/microsoft/vscode-languageserver-node/blob/ed6a6d7da0ad64ebea0b55e4b2f339a1ec7f511f/client/src/common/client.ts#L565).

The VS LSP client doesn't register built-in features by default like VSCode, which is why we do it ourselves on the Razor side. Ideally, since we want to be client agnostic, the Razor team thinks that VSCode should throw away extra registrations when features are registered more than once.

**Comment by dbaeumer** [comment]
There is a different between registering a feature and registering a provider (I agree that the naming is a little bit off when compared to LSP). In VS Code's LSP client features are general support for things like hover, completion provider, .... Registering the feature WILL NOT send any requests to the server. That means that the client is able to handle registrations for a LSP feature like for example hover or completion. 

From what you describe it looks like that you might register the hover feature twice from the server. If you do so then the client will sent two requests. To check this for example for hover set a breakpoint here https://github.com/microsoft/vscode-languageserver-node/blob/8de18faed635819dd2bc631d2c26ce4a18f7cf4a/client/src/common/hover.ts#L52 and see if you hit the code path more than once.

**Comment by allisonchou** [comment]
Thanks for the insight, Dirk! I debugged through some more and I think this is an issue with both O# and Razor registering handlers - https://github.com/OmniSharp/csharp-language-server-protocol/blob/e0cc2012b63757ebf779bf4e86e8835e400b034f/src/Server/LanguageServerHelpers.cs#L147.

Given Razor plans on switching away from O# soon, this should be a non-issue in the near future. Thanks again for your help.
