### ISSUE TITLE
Allow returning custom error message from prepareRename

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-languageserver-node#1085]
When `prepareRename` throws, today you see the following in VS Code:

![Screen Shot 2022-09-21 at 4 55 07 PM](https://user-images.githubusercontent.com/12821956/191629897-a6fe36d6-9e93-4149-a39e-bd3e05fb0708.png)

`xxxx` is my custom error message here.
 
I'd like to show just my custom message and not the `Request textdocument/prepareRename` part. I have not found a way to do this using the current apis 

Refs #699

**Comment by dbaeumer** [comment]
@mjbvz it is not obvious but if your server throws a `ResponseError` the message is returned as is. I only augment the message if I receive a non `RepsonseError` to give an indication what failed. See https://github.com/microsoft/vscode-languageserver-node/blob/501c2b56c56444fd03c762002417c0f2a2166995/jsonrpc/src/common/connection.ts#L874

Can you give that a try?

**Comment by mjbvz** [comment]
Thank you @dbaeumer! That works as expected. I'll close this issue since using `ResponseError` resolved it
