### ISSUE TITLE
VS Code using system language in extensions after installation

### ISSUE THREAD

**Issue by MinusPL** [microsoft/vscode-languageserver-node#1087]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.71.0
- OS Version: Windows 10 Pro 21H2

Steps to Reproduce:

1. Install VS Code
2. Install extension (for example cpptools - messages from IntelliSense will be in system default language, not english)
3. Extension will use system language instead of english which is default, but not in every place

What can be done to workaround this issue:
- Install any language pack, switch to that language by using Change Display Language command and return back to english.
- Change system default language.

It seems VS Code is not setting it's own display language to english properly, and reports system default language in some places.

**Comment by dbaeumer** [comment]
I will fold this issue with https://github.com/microsoft/vscode-languageserver-node/issues/1086.

Now that VS Code will have l10n API we need to offer API as well that an extension can find out the locale/UI language.
