### ISSUE TITLE
Return Promise from `ErrorHandler.closed()`

### ISSUE THREAD

**Issue by adam-fowler** [microsoft/vscode-languageserver-node#1090]
Would it be possible to change `ErrorHandler.close()` to return a `Promise<CloseHandlerResult>` instead of `CloseHandlerResult`? With it returning a `CloseHandlerResult` immediately it limits what extensions can do when the LSP server crashes.

When the LSP server crashes repeatedly I would like to display a dialog  asking the user what they would like to do. Do you want to restart the server, quit running the server, give them a chance to edit their code to fix the issue that caused the LSP server crash. I can't see how I can do this without `closed()` returning a promise.

This is to support using development versions of language compilers and LSP in particular the Swift compiler.

**Comment by kelvin13** [comment]
+1 this is really annoying and i waste a lot of time each day manually reloading the IDE window because of this.

**Comment by dbaeumer** [comment]
From quickly looking at the code I think that should be possible.

Anyone want to look into providing a PR?

**Comment by adam-fowler** [comment]
I had a go myself #1096
