### ISSUE TITLE
View and corresponding custom container not loading in UI.

### ISSUE THREAD

**Issue by david-pa** [microsoft/vscode-languageserver-node#1091]
The reviewer who read my previous issue did not give an appropriate answer to the question, so I am re-posting the question here.

The basic summary is that the changes made to my `package.json` file don't seem to be registering when starting up the extension, and the only feedback I get is that the ID of the view in question, which I am attempting to register in a new custom view container, does not exist.

```
...
"contributes": {
    "viewsContainers": {
			"activitybar": [
				{
					"id": "new-explorer",
					"title": "New Explorer",
					"icon": "media/dep.svg"
				}
			]
		},
    "views": {
			"new-explorer": [
				{
					"id": "newExplorer",
					"name": "New Data",
					"icon": "media/dep.svg",
					"contextualTitle": "New  Explorer"
				}
			]
    }
...
```

Here is a link to the issue I originally posted.
https://github.com/microsoft/vscode/issues/162142

From what I understand, even just registering the view and container in `package.json` should load them into the UI, but will just show them as empty if there is no data provided. I'm not sure why nothing shows up at all.

**Comment by dbaeumer** [comment]
I am closing this one since this repository is about the language server protocol not VS Code itself. Although the issue got closed you will still be able to comment on that issue. Please continue the discussion there.
