### ISSUE TITLE
Confusion about the return values of `DiagnosticPullOptions`

### ISSUE THREAD

**Issue by MariaSolOs** [microsoft/vscode-languageserver-node#1092]
It isn't clear what the return value of this `filter` method is supposed to represent:
https://github.com/microsoft/vscode-languageserver-node/blob/30da06d7820e362a4280b2e51d9922350e473263/client/src/common/diagnostic.ts#L126-L133

Initially I thought that if this method returned `true` then the document should trigger the pull diagnostics request (and that also seems to agree with how other [typical filter methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter#return_value) behave), but then after seeing its use below I now think that if `filter` returns `true` then no pull diagnostics should be requested (?).
https://github.com/microsoft/vscode-languageserver-node/blob/30da06d7820e362a4280b2e51d9922350e473263/client/src/common/diagnostic.ts#L923-L931

What's more confusing is that [`match`](https://github.com/microsoft/vscode-languageserver-node/blob/30da06d7820e362a4280b2e51d9922350e473263/client/src/common/diagnostic.ts#L144-L151) seems to have the opposite meaning, since if the method returns `true` then from the code below it seems like the pull diagnostics request should be triggered:
https://github.com/microsoft/vscode-languageserver-node/blob/30da06d7820e362a4280b2e51d9922350e473263/client/src/common/diagnostic.ts#L818-L822

To avoid further confusion, I ask for a clarification on what the return values of these 2 methods mean, and also document that in their respective JSDocs :)

**Comment by dbaeumer** [comment]
These functions are to be read the following way:

textdocument.filter(mode) =>the text document will be filtered if the function returns true
documentSelector.match(uri) => the document selector matches the uri.

The filter method on an array returns a new array. I see the problem with the call back function however I always treated the callback as keep. 

Hope that clarifies things.

**Comment by MariaSolOs** [comment]
Thanks @dbaeumer for explaining!
