### ISSUE TITLE
How does document setting caching work?

### ISSUE THREAD

**Issue by gee4vee** [microsoft/vscode-languageserver-node#1097]
In [this line of code](https://github.com/microsoft/vscode-extension-samples/blob/main/lsp-sample/server/src/server.ts#L95), what is the life cycle of `documentSettings`? Is it for the entire server or per document? When does the object get initialized and destroyed?

**Comment by dbaeumer** [comment]
This is under full control of the server you are writing. In this example the cache is cleared here: https://github.com/microsoft/vscode-extension-samples/blob/main/lsp-sample/server/src/server.ts#L100
