### ISSUE TITLE
Unknown parameter structure error when using RequestType in VS Code Extension

### ISSUE THREAD

**Issue by sfc-gh-tkojima** [microsoft/vscode-languageserver-node#1098]
I am working on a VS Code extension. This extension uses a language server which is shipped as a separate npm package. 

In an effort to keep the server/client types in sync, the language server package exports custom requests, i.e.

```
import { RequestType } from "vscode-languageserver";

export declare const FooRequest: RequestType<string, string[], void>;
export declare const BarRequest: RequestType<string, string[], void>;
```

I'd like to reuse these in the client, i.e:
```
import { FooRequest } from '@foo/bar/requests';
...

client
  .start()
  .then(() => {
    void client
      .sendRequest(FooRequest, 'test')
      .then((res) => console.log(res));
  });
```

However, when running the extension, an error is thrown: `Unknown parameter structure auto`

I'm guessing that this is because the injected `vscode` module is providing an instance of `vscode-jsonrpc` which conflicts with the one that gets bundled.

Is there an easy way to share request types between server/client for type safety?

**Comment by sfc-gh-tkojima** [comment]
Hmm, seems my suspicion was right... I "fixed" it by modifying webpack config to include all of the vscode-* packages in externals.

```
    externals: {
      vscode: 'commonjs vscode',
      'vscode-languageserver': 'commonjs vscode-languageserver',
      'vscode-jsonrpc': 'commonjs vscode-jsonrpc',
      'vscode-languageserver-protocol': 'commonjs vscode-languageserver-protocol',
      'vscode-languageserver-types': 'commonjs vscode-languageserver-types',
    },
```

would this be a recommended way of fixing this?

**Comment by sfc-gh-tkojima** [comment]
Frustratingly, this doesn't work in non dev environments. VSCode provides these external packages when running with --extensionDevelopmentPath, but not when running a packaged vsix.

**Comment by dbaeumer** [comment]
There are two ways to address this:

- have your own npm packages for the requests. I do this in this repository for the whole protocol package. However that might be an overkill
- share the code between client and server using symbolic links and compile them twice. I do this here https://insiders.vscode.dev/github.com/microsoft/vscode-eslint/blob/4b92c12af15d41f76417bde9571cb56f08ec3d0f/$shared/customMessages.ts#L1 as well and I recommend this for your setup.
