### ISSUE TITLE
Question: why workspace/configuration params is not matched with spec?

### ISSUE THREAD

**Issue by black-desk** [microsoft/vscode-languageserver-node#1103]
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#configurationParams

https://github.com/microsoft/vscode-languageserver-node/blob/e20440f6f7f4dd4b74a40fab8f1ac163d2e98ece/protocol/metaModel.json#L131-L155

https://github.com/microsoft/vscode-languageserver-node/blob/e20440f6f7f4dd4b74a40fab8f1ac163d2e98ece/protocol/src/common/protocol.configuration.ts#L26

Why?

**Comment by dbaeumer** [comment]
Actually the spec is correct. Fixed in code.
