### ISSUE TITLE
Inconsistent Interface for CompletionItem

### ISSUE THREAD

**Issue by nruffing** [microsoft/vscode-languageserver-node#1108]
What is the intended approach to create a ```CompletionItem``` that replaces text?

I would like the completion to replace the entire line where the users cursor is currently located.

When I specify the text and range as a ```TextEdit``` the range seems to be ignored and instead the default current word range is used.
```
const completionItem = {
    label: 'competion item label',
    kind: CompletionItemKind.Text,
    textEdit: TextEdit.replace('new text', range),
}
```

I did a little digging and it looks like in the VS Code API interfaces ```textEdit``` is deprecated with the message ```Use `CompletionItem.insertText` and `CompletionItem.range` instead.```
https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.d.ts#L4515

In the commit that deprecated ```textEdit``` it looks like the range is being ignored which is consistent with what I am experiencing.
https://github.com/microsoft/vscode/commit/c76b721d819648431799f9b38bae80e4e2054cf9

However, the ```CompletionItem``` interface in ```vscode-languageserver-node``` does not have a range property. Does that interface need to be updated?

**Comment by dbaeumer** [comment]
The idea of a completion item is to update the text around the cursor, not to replace the entire line. 

A LSP completion item is correctly converted [here](https://insiders.vscode.dev/github.com/microsoft/vscode-languageserver-node/blob/df9ea01af578e02d910bf0fb4c7d4edcd94d4e55/client/src/common/protocolConverter.ts#L612) to a VS Code completion item. In case the LSP item has a textEdit it will create a VS Code item with an insert text and a range. The reason why the two are different is backwards compatibility.

I am pretty sure this this doesn't even if you use native VS Code API. Have you tried this?

**Comment by dbaeumer** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting guidelines](https://aka.ms/vscodeissuereporting). Please take the time to review these and update the issue.

Happy Coding!
