### ISSUE TITLE
Attach to existing language server process

### ISSUE THREAD

**Issue by jepperaskdk** [microsoft/vscode-languageserver-node#1111]
I'm writing a C++ language server. Is it possible to configure the `ServerOptions` for `LanguageClient` to specify a port/process-id of an already running language server? This way I can run my language server separately with full debugging capabilities.

**Comment by dbaeumer** [comment]
Yes, you can pass-in a function that is called when the server connection is created. That function can do whatever is needed. See https://insiders.vscode.dev/github.com/microsoft/vscode-languageserver-node/blob/df9ea01af578e02d910bf0fb4c7d4edcd94d4e55/client/src/node/main.ts#L126

**Comment by jepperaskdk** [comment]
@dbaeumer Thanks! For reference, this is what I ended up using (language server running with TCP on port 9333):
```
import * as net from 'net';
const options: ServerOptions = () => {
    let socket = net.connect({ port: 9333 });
    let result: StreamInfo = {
        writer: socket,
        reader: socket
    };
    return Promise.resolve(result);
};
```
