### ISSUE TITLE
If diagnostics is CodeAction is `null` or `undefined` you Cannot read properties of null (reading 'map')

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-languageserver-node#1113]
From Protocol definition of CodeAction `diagnostics` is optional:
```json
                {
                    "name": "diagnostics",
                    "type": {
                        "kind": "array",
                        "element": {
                            "kind": "reference",
                            "name": "Diagnostic"
                        }
                    },
                    "optional": true,
                    "documentation": "The diagnostics that this code action resolves."
                },
```

```console
 ERR Cannot read properties of null (reading 'map'): TypeError: Cannot read properties of null (reading 'map')
    at asDiagnostics (c:\GIT\formatters\vscode-isort\dist\webpack:\isort\node_modules\vscode-languageclient\lib\common\protocolConverter.js:34:1)
    at Object.asCodeAction (c:\GIT\formatters\vscode-isort\dist\webpack:\isort\node_modules\vscode-languageclient\lib\common\protocolConverter.js:598:1)
    at c:\GIT\formatters\vscode-isort\dist\webpack:\isort\node_modules\vscode-languageclient\lib\common\client.js:1226:1
    at A.provideCodeActions (c:\Users\Karthik Nadig\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:42766)
```

**Comment by dbaeumer** [comment]
In LSP `null` and `undefined` are different things. If a property can be `null` it must be typed as that. So, in the CodeAction case `diagnostics` can be omitted but NOT set to `null`. 

Do you know the shape of the code action that was converted here?

**Comment by dbaeumer** [comment]
@karthiknadig any additional information?

**Comment by karthiknadig** [comment]
The issue occurs when VS Code asks for CodeActions on a given line. But you return this, which is a organize import action not really a code action for that line:
```
 [
                        {
                            "title": "isort: Organize Imports",
                            "kind": "source.organizeImports",
                            "edit": None,
                            "data": "<file URI>",
                        }
]
```

**Comment by dbaeumer** [comment]
@karthiknadig not sure I understand this. What do you mean by:

> But you return this. 

LSP doesn't generate any code actions.

**Comment by karthiknadig** [comment]
I mean in the server, as a response to the code action request. If you return that particular code action as response that is when you get the error. The request params should have diagnostics set to something, and you return the above as reponse that is when you get the error.

**Comment by dbaeumer** [comment]
Actually the exception seems to happen here: https://github.com/microsoft/vscode-languageserver-node/blob/bb6a6ac6b70dd876d2ea90f12d86a1be5414f440/client/src/common/protocolConverter.ts#L300 which is even more strange since `async` is an imported module. So not sue why this should fail on a object literal.

What I did noticed with 

```json
[
                        {
                            "title": "isort: Organize Imports",
                            "kind": "source.organizeImports",
                            "edit": None,
                            "data": "<file URI>",
                        }
]
```

Is that `edit` can not be `null`. The spec defines it as:

```
	/**
	 * The workspace edit this code action performs.
	 */
	edit?: WorkspaceEdit;
```

which doesn't support `null` as a value.

**Comment by karthiknadig** [comment]
This can be closed now. For two reasons, it seemed to occur due to wrong response from the server, which has been fixed. We also switched to `lsprotocol` library in python which now is strict about cases mentioned above where `"edit": null` was somehow allowed.

If this occurs for any reason, I will provide a more detailed request response content so it should be easier to reproduce.
