### ISSUE TITLE
Need Information About Editor Events for onNotification() Methods

### ISSUE THREAD

**Issue by david-pa** [microsoft/vscode-languageserver-node#1126]
I'm working on something that would need to be able to run a snippet of code located in the client side of the extension, but it needs to be able to run every time the user switches between their open documents in the editor tabs.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/108750899/203435729-df2c003f-4c02-4033-b156-57bbd0d36907.png">

I've been looking at the [LSP documentation](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didOpen), but I couldn't find anything that would be triggered every time a user switches those tabs. Is there any way to detect when the user changes the current open editor window/tab? Basically, I just need to know when `vscode.window.activeTextEditor.document.uri` changes so I can react to the change. Is anything like that current implemented?

I would think `connection.onDidOpenTextDocument` would be the appropriate notification to listen for in the server to catch this event, but the documentation says that, "Open in this sense means it is managed by the client. It doesn’t necessarily mean that its content is presented in an editor."

**Comment by dbaeumer** [comment]
No, this is not possible in LSP. By design LSP doesn't forward any UI events. What we do is on request send informations about the active document if this is necessary for the request.

VS Code does have such an API. It is called tabs API in case you want to have a look there.
