### ISSUE TITLE
JSON no diagnostics

### ISSUE THREAD

**Issue by zardoy** [microsoft/vscode-languageserver-node#1128]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.0
- OS Version: macOS

This problems exists from `1.68.0`. in `1.67.0` everything seems to be fine.

1. Extension code to reproduce:

```ts
// most probably you want to register it to some command
const testContent = '{test: 5}'

vscode.workspace
    .openTextDocument({
        content: testContent,
        language: 'json',
    })
    .then(async doc => {
        await vscode.window.showTextDocument(doc)
    })
```

2. Run this code twice

Actual: First editor has diagnostics and second not
Expected: Both editors have diagnostics

The second call can also open file instead. This was happening to me in stable builds in some cases without any extensions, but the only consistent way I found to reproduce is this ext code.

Attaching gif:

<img alt="23-2022 02-42-58" width="500" src="https://user-images.githubusercontent.com/46503702/203443201-eac6c529-1a44-4ea6-ad53-3c4e231a65d5.gif">

Text changes doesn't produce diagnostics in these editors. Of course, after reload diagnostics will be there.

**Comment by zardoy** [comment]
release status?

**Comment by dbaeumer** [comment]
The issue got fixed in the LSP libraries. I will make new releases of the lib next week and then @aeschli needs to adopt it. So it will be beginning of Dez.

**Comment by zardoy** [comment]
In the latest release bug from STR is now reproducible again. In the latest insiders now we get no diagnostics even with the first API call (whenever you use code mentioned in the body of the issue). Of course I tested with an empty profile.

**Comment by aeschli** [comment]
@zardoy Please file a new issue with steps to reproduce
