### ISSUE TITLE
CompletionItem.textEdit deprecated in client vscode library, but not in server vscode-languageserver/node

### ISSUE THREAD

**Issue by david-pa** [microsoft/vscode-languageserver-node#1132]
I'm trying to setup VSCode completions to be handled by the server in specific instances, and completions are showing up and working just fine, but I want to replace the full string of text at the trigger/request location, rather than just insert the text at the location.

Basically, instead of `object.existing_text` becoming `object.replacement_textexisting_text`, I want to only see `object.replacement_text`.

The solution I found in the `CompletionItem` interface server-side was using a `TextEdit` instance to replace the entire string after figuring out the appropriate range.

<img width="710" alt="image" src="https://user-images.githubusercontent.com/108750899/204931264-e6a1b11a-01a3-45f4-bdba-4d23233d4e45.png">

That seemed to work just fine, but when writing some test cases I saw that in the client via the `vscode` library, the `CompletionItem.textEdit` option is deprecated, and it presents using `range` and `insertText` as an alternative.

<img width="826" alt="image" src="https://user-images.githubusercontent.com/108750899/204931509-78bf71a7-9e8f-40f7-88c5-dd6693b87ab1.png">

That being said, `CompletionItem.range` doesn't seem to be present in the `vscode-languageserver/node` library version of the interface, so I'm a little confused about what is the correct approach here.

I tried the following setup for the server's returned object, but it didn't seem to work. Here, `completionRange` would be the range that covers the entire string of text that needs to be replaced, including the position at which the completion was triggered/requested.
```
return {
      label: `replacement text`,
      kind: CompletionItemKind.Value,
      preselect,
      detail: 'Item detail',
      documentation,
      range: {
        replacing: completionRange,
        inserting: Range.create(completionRange.start, completionRange.start)
      },
      insertText: `replacement text`
    };
```

**Comment by dbaeumer** [comment]
The shape of the Completion item is not the same for LSP and VS Code API. The reason is some sort of backwards compatibility. The conversion of one into the other is handled here: https://github.com/microsoft/vscode-languageserver-node/blob/f02ec883a68c6ee0e07a512c2114847f5f8c9d29/client/src/common/protocolConverter.ts#L547

In our case you should stick to the LSP shape and let the LSP client do the conversion.

**Comment by david-pa** [comment]
So does that mean it's still safe to use CompletionItem.textEdit via the LSP server as the client is converting that information?
