### ISSUE TITLE
Perform websocket request during onDefinition

### ISSUE THREAD

**Issue by christopherchateau** [microsoft/vscode-languageserver-node#1135]
When `connection.onDefinition` is invoked, I'm hoping to send a websocket request and await its response before returning the definition `Location`, which takes the user to that location in VS Code. The execution of `connection.onDefinition` completes before the websocket request/response finishes.

I've experimented with using a callback function. First, by having the callback return the desired `Location`, but that does not trigger that location to open in VS Code. Secondly, I tried having the callback invoke `connection.onDefinition` with updated parameters, and making sure to return the `Location` in this case, but that also does not jump the user to the definition location.

Is it possible to achieve this? Or is there simply no way currently to delay the execution of `connection.onDefinition` or invoke it a subsequent time using a callback function?

**Comment by christopherchateau** [comment]
if anyone ever stumbles upon this, the solution was to return a `new Promise()` from `connection.onDefinition`

**Comment by dbaeumer** [comment]
Yes all request callback can return a Promise which will be awaited before the response is sent back.
