### ISSUE TITLE
Handlers for semantic tokens, inlay hints

### ISSUE THREAD

**Issue by burner1024** [microsoft/vscode-languageserver-node#1165]
It seems there are no builtin handlers for inlay hints, semantic tokens requests. Will there be any?
Actually, inline hints too.

**Comment by dbaeumer** [comment]
They do exist, but they are on a language namespace. See https://github.com/microsoft/vscode-languageserver-node/blob/bb6a6ac6b70dd876d2ea90f12d86a1be5414f440/client-node-tests/src/servers/testServer.ts#L419 for an example.
