### ISSUE TITLE
Language injections for controlling syntax highlighting in string literals

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-languageserver-node#1170]
See details for this issue here: https://github.com/microsoft/vscode-python/issues/20463

The feature request here is to add LSP support for providing language information for string literals.

**Comment by dbaeumer** [comment]
The should be handled by the language server itself not by LSP since a generic approach to this is very hard.

@aeschli has example and guides how to do this. See https://code.visualstudio.com/api/language-extensions/embedded-languages
