### ISSUE TITLE
Inline object definitions vs separate interface definitions

### ISSUE THREAD

**Issue by rhdunn** [microsoft/vscode-languageserver-node#1174]
There are a number of places where the definition of the properties in an object are defined inline to that object instead of as a separate interface. For example:
1. [ShowMessageRequestClientCapabilities](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_showMessageRequest) -- messageActionItem property
2. [InitializeParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initializeParams) -- clientInfo property
3. [ClientCapabilities](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#clientCapabilities) -- workspace, fileOperations, window, general, and staleRequestSupport properties
4. etc.

Is there a rationale in deciding which objects to make interfaces and which to specify inline?

It would be more consistent, readable to implementors (who will need to define interfaces for these anyway), and interoperable for users (having consistent names for these sub-objects) to make all the sub-objects have interface definitons.

**Comment by dbaeumer** [comment]
This got fixed lately by @karthiknadig

**Comment by DanTup** [comment]
@dbaeumer I was just looking to re-generate my code because of this and noticed the file at https://github.com/microsoft/vscode-languageserver-node/blob/main/protocol/metaModel.json says:

```
"version": "3.17.0"
```

But it also contains a lot of `"since": "3.18.0",`. Was this intended/expected?

**Comment by dbaeumer** [comment]
This has always been that way. But all the since `3.18.0` features should be marked as proposed so they might change until we release 3.18. This gives us an easy way to get feedback on preview features without shipping separate 3.18 next builds.

**Comment by DanTup** [comment]
> But all the since `3.18.0` features should be marked as proposed

You're right (except for `MessageType.debug`).

Perhaps there should be a `"proposed": true` field on those items so if we want to exclude them from our code-gen more easily (checking for "@proposed" in the documentation seems to go against the purpose of a structured schema)?
