### ISSUE TITLE
metamodel: documentation contains markdown links to anchors in the spec

### ISSUE THREAD

**Issue by michaelpj** [microsoft/vscode-languageserver-node#1178]
e.g.
```
The [range](#Range) of this selection range.
```

These only really make sense as part of the spec doc. It would be nice if they weren't there. At the moment I'm just stripping them out.

**Comment by dbaeumer** [comment]
@michaelpj could you contribute the code to the extractor?

**Comment by michaelpj** [comment]
I'm not sure what the correct behaviour is tbh.

**Comment by dbaeumer** [comment]
I think we should remove these links from the meta model since things might be different in different languages.

**Comment by dbaeumer** [comment]
These got fixed a while back ago and are now: `{@link Range range}`
