### ISSUE TITLE
Completion request is sometimes sent on stale document contents

### ISSUE THREAD

**Issue by ejgallego** [microsoft/vscode-languageserver-node#1184]
Dear vscode langserver devs,

I'm getting some reports from users that when using `triggerCharacters`, vscode language client is sending the `completion` request before a `didChanges` request when one of the `triggerCharacters` is used.

This is far from good as our server will return stale completion info then.

Moreover, I can't reproduce locally, but I think such users have a way slower machine so it could be some kind of race.

Do you think that it is a valid behavior to send the completion request before the `didChanges` request on an edit?

**Comment by ejgallego** [comment]
After looking a bit at the code, it seems to me that this could actually be a VS Code issue, if that's the case I'd appreciate if you could transfer the issue.

**Comment by dbaeumer** [comment]
Which version of the LSP libraries are you using. I fixed two issues for the upcoming 8.1.0 release (which is available as next.5 right now) were `didChange` requests were sent too late. However this only happened when using full test document sync. Do you use this?

**Comment by ejgallego** [comment]
Hi @dbaeumer , thanks a lot for the help!

Indeed we are using 8.0.2 . @Alitzer, can you try with 8.1.0 and see if the problem goes away?

Yes, we use for now full document sync for `didChanges`, our server client are at https://github.com/ejgallego/coq-lsp

**Comment by Alizter** [comment]
This does appear to resolve our issue. Do you have any idea why this bug is not observed more widely?

**Comment by dbaeumer** [comment]
Most servers use incremental document sync because it is far more efficient (a lot less data to send) and the problem doesn't show up with incremental sync. Have you ever thought about using incremental sync instead.

**Comment by dbaeumer** [comment]
I will close the issue since it seems to be addressed in the upcoming 8.1.0 release.

**Comment by ejgallego** [comment]
Thanks a lot folks for researching and testing this, I'm glad it seems to be solved.

@dbaeumer , incremental sync is in the roadmap for our server, however it is low priority, in our context there is little diference as the overhead of checking itself is way larger, but indeed we will get to it.
