### ISSUE TITLE
Is it possible to include a sub-extension within an existing extension project?

### ISSUE THREAD

**Issue by david-pa** [microsoft/vscode-languageserver-node#1188]
I am currently developing a VSCode extension that leverages the VSCode LSP, and I recently added a custom editor that uses an existing open-source extension project as a base. Here is a brief, simplified view of the file structure:

```
Main Extension Folder (uses npm)
|
|- client
|   |- src
|   |   |- extension.ts (activation function and misc. extension functions)
|
|- server
|   |- src
|   |   |- server.ts (server startup code and misc. handlers)
|
|- graphical-editor (uses yarn)
|   |- glsp-client-vscode (sub-extension's vscode-specific files)
|   |   |- workflow-vscode
|   |   |   |- extension
|   |   |   |   |- index.ts (activation function and misc. extension functions)
|   |   |   |   |- package.json (Sub-extension's VSCode UI contributions, extension metadata, etc.)
|   |   |   |
|   |   |   |- webview (files related to generation of editor's webview)
|   |   |
|   |   |- workflow-glsp (required non-vscode files)
|
|- package.json (Main extension's VSCode UI contributions, extension metadata, etc.)
```
Currently, if I were to start the main extension and this sub-extension together, I think because they both have their own UI contributions or because they have seperate `activate(context: vscode.ExtensionContext)` functions (or perhaps both), it ends up opening two separate windows of VSCode. One of the windows has the main extension displayed, the other the custom editor. What I'm trying to do is get the two to show up as part of the same extension, with the main extension contributing a ViewContainer and a few custom Views, and the sub-extension contributing a custom editor that utilizes a WebView.

Is there currently a way for me to define/include the sub-extension as part of my main extension without copying the files into the client? The current setup of the sub-extension does not lend itself to being restructured (i.e. taking the `extension` directory's files and placing them in the `client -> src` directory), which is the main issue at the moment, as if they can't share a `package.json` file or `activate()` function they can't show up in the same window, as far as I'm aware. It could also be that the launch configuration I set doesn't lend itself to displaying both in one window, but I'm not sure.

**Comment by dbaeumer** [comment]
This is more a VS Code question than a LSP question: but extension can depend on other extensions using the `extensionDependencies` property in the package.json file. So I would separate the two and make one dependent on the other.

**Comment by r3m0t** [comment]
Here's a launch configuration developing two extensions that open in the same window- https://github.com/microsoft/vscode-jupyter/blob/main/pvsc.code-workspace#L48

**Comment by david-pa** [comment]
@dbaeumer As far as testing goes though, the sub-extension would have to be published in the marketplace already and manually installed for the `extensionDependencies` property to find it, correct? But when the main extension is officially published and a user installs it, the sub-extension would be installed automatically without the user needing to manually do so, right?

**Comment by dbaeumer** [comment]
@david-pa all that is correct.
