### ISSUE TITLE
If `CodeAction` has both `edit` and `command`, then the `command` is not executed.

### ISSUE THREAD

**Issue by datho7561** [microsoft/vscode-languageserver-node#1196]
In the LSP specification, it specifies that if both an `edit` and a `command` are provided, then the `edit` is applied first, the the `command`. However, in this case, the `command` doesn't appear to be invoked at all.

The way I tested this is by modifying the value of the resolved code action using `middleware` in the language client options, adding a command field that invokes a trivial command. i.e.

```ts
resolveCodeAction: async (item: CodeAction, token: CancellationToken, _next) => {
  const resolvedCodeAction = await languageClient.sendRequest(
    CodeActionResolveRequest.type,
    await languageClient.code2ProtocolConverter.asCodeAction(item),
    token);
  const modifiedCodeAction = await languageClient.protocol2CodeConverter.asCodeAction(resolvedCodeAction);

  modifiedCodeAction.command = {
    command: "foo",
    title: "foo",
  };
  return modifiedCodeAction;
}
```

where I define

```ts
context.subscriptions.push(commands.registerCommand('foo', () => {
  window.showInformationMessage('foo');
}))
```

Through debugging the extension, I can confirm that the middleware function is invoked, but the info message from the command doesn't pop up.

**Comment by dbaeumer** [comment]
The `command` can't be resolved lazily in VS Code. See the client capability `resolveSupport` here https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_codeAction which VS Code only sets to `edit` here: https://github.com/microsoft/vscode-languageserver-node/blob/d859bb14d1bcb3923eecaf0ef587e55c48502ccc/client/src/common/codeAction.ts#L45

So a command needs to be provided when the code action is created.

**Comment by datho7561** [comment]
Okay, thanks for the help!

**Comment by RblSb** [comment]
> So a command needs to be provided when the code action is created.

@dbaeumer can you lazily resolve arguments to provided `command`? For example `edit` generates function at lazily resolved `pos` in file, and then `command` sets cursor to this `pos`. I cannot find any solution or workaround for this simple task.

**Comment by dbaeumer** [comment]
You can't resolve `args` lazy either.
