### ISSUE TITLE
Can we use CompletionItem#additionalTextEdits to update content after the cursor in the same line?

### ISSUE THREAD

**Issue by angelozerr** [microsoft/vscode-languageserver-node#1198]
We have a language server which provides completions for tags (look like XML). We have the capability to update orphan end tag with  the completion apply.

For instance given this XML (`|` is used to show where completion is triggered):

```xml
<|></>
```

When completion is opened, it show some element like `foo`, `bar`. When `foo` completion item is applied, it update the end tag too to have the following result:

```xml
<foo></foo>
```

To do that we use additionalTextEdits  to update the end tag on the `completionItem/resolve`. It works perfectly except if the user type quickly when completion is opened. We could have this bad result:

```xml
<foo>foo</>
```

I wonder for this usecase (update content after the cursor in the same line) if the solution is to use a command because it seems command is executed on after completion insert according the documentation `An optional command that is executed *after* inserting this completion.`. But the following comment says `Note that additional modifications to the current document should be described with the additionalTextEdits-property.`

My question is it a bug of vscode or should I use command for this usecase. 

Many thanks for your answer.

**Comment by rgrunber** [comment]
According to https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItem

```
        /**
	 * An optional array of additional text edits that are applied when
	 * selecting this completion. Edits must not overlap (including the same
	 * insert position) with the main edit nor with themselves.
	 *
	 * Additional text edits should be used to change text unrelated to the
	 * current cursor position (for example adding an import statement at the
	 * top of the file if the completion item will insert an unqualified type).
	 */
```

I would think from the example, there would be overlap when the main text edit is longer than the distance between the tag element start/end.

**Comment by dbaeumer** [comment]
According to the spec neither additional text edits nor commands can be used for this. All I can think of right now is to use a snippet that replaces `<|></>` with `<foo></foo>` and uses the cursor end position to put the cursor at the right position.

**Comment by dbaeumer** [comment]
Would that work for you?

**Comment by angelozerr** [comment]
> Would that work for you?

Badly no -(

If we use snippet, the only solution to ashow completion is to use choice which is limitated just with string, so we loose:

 * the completion documentation.
 * the capability to generate XML attributes when a completion item is applied.

**Comment by dbaeumer** [comment]
@aeschli do you have an idea. Is this something you solved in HTML?

**Comment by angelozerr** [comment]
> @aeschli do you have an idea. Is this something you solved in HTML?

In HTML there is no this feature https://github.com/redhat-developer/vscode-xml/blob/main/docs/Refactor.md#surround-with-tags-wrap

**Comment by aeschli** [comment]
For HTML, we use the linked editor provider to do that.
It's also there in LSP: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_linkedEditingRange

**Comment by angelozerr** [comment]
> For HTML, we use the linked editor provider to do that.

We use it too, and it works great, but not when you try to open completion, apply it and generate elements with attributes.

**Comment by dbaeumer** [comment]
I am actually out of ideas. You could directly see if there is a suggestions in VS Code itself and then we could start discussing whether we could add something to LSP itself.

**Comment by angelozerr** [comment]
Ok, thanks so much @dbaeumer @aeschli for your feedback.

**Comment by dbaeumer** [comment]
Treating the issue as a question and closing it.
