### ISSUE TITLE
Clarify Spec regarding default behavior for Position.line containing an out-of-range value

### ISSUE THREAD

**Issue by VlkrS** [microsoft/vscode-languageserver-node#1199]
As far as I can tell, the behavior described [here](https://github.com/microsoft/vscode-languageserver-node/blob/d859bb14d1bcb3923eecaf0ef587e55c48502ccc/textDocument/src/main.ts#L25) is not explicitly defined in the LSP specification. 

Could you either clarify this in the specification by explictly mentioning it, or otherwise note that this is only a property of this particular implementation?

**Comment by dbaeumer** [comment]
Actually that is on purpose. It is only a property of this particular implementation.

**Comment by dbaeumer** [comment]
BTW: LSP has no specification for text documents.
