### ISSUE TITLE
what happens when I call onXYZ multiple times?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode-languageserver-node#12]
There are onXYZ-method to register a handler, like `onRename`. I wonder what happens when I register multiple handler and why it's not a property I assign?

**Comment by dbaeumer** [comment]
The problem is that these return results in therefore are not like events. I agree that the on name is misleading but given that we have these names out there for 1 1/2 years now I am reluctant to change. I will close since I think it will never happen :-)

**Comment by dbaeumer** [comment]
To answer the question: the last one wins :-)
