### ISSUE TITLE
bad jasonrpc shutdown: CancellationToken.is breaks on undefined token

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode-languageserver-node#120]
jasonrpc: [CancellationToken.is](https://github.com/Microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/cancellation.ts#L40) does not check for `undefined` before dereferencing a property, while languageclient [calls `shutdown`](https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/main.ts#L187) with an `undefined` token:
```typescript
shutdown: () => connection.sendRequest(ShutdownRequest.type, undefined),
```

**Comment by dbaeumer** [comment]
Thanks @siegebell. Merge the test case. I already fixed the problem on master
