### ISSUE TITLE
Move `CompletionContext` into `vscode-languageserver-types`

### ISSUE THREAD

**Issue by remcohaszing** [microsoft/vscode-languageserver-node#1202]
Currently `CompletionContext` is defined in `vscode-languageserver-protocol`. However, this type is also relevant in other contexts where `vscode-languageserver-types` are relevant, but other exports from `vscode-languageserver-protocol` are not. For example, `monaco.languages.CompletionContext` from `monaco-editor` maps exactly to `CompletionContext` from `vscode-languageserver-protocol`.

Since I maintain several Monaco editor related projects, I would love to see `CompletionContext` available in `vscode-languageserver-types`, so they don’t have to depend on `vscode-languageserver-protocol`.

**Comment by dbaeumer** [comment]
I know that some of the context types made it into types package due to an oversight but in general I would like to keep request specific types in the protocol package. OK for you?

**Comment by remcohaszing** [comment]
I though of it as `vscode-languageserver-types` are the types typically needed by a language service, and `vscode-languageserver-protocol` contains the logic for making a protocol connection. Since I’ve seen language services use `CompletionContext`, I thought it might be misplaced by accident.

I would prefer to have a dependency on `vscode-languageserver-types` if only the types are needed, as that has a smaller dependency tree, notably `vscode-languageserver-protocol` (rightfully) indirectly depends on `@types/node`, which is not ideal for web based projects (but also not **that** big of a deal).

If you say these types belong in `vscode-languageserver-protocol`, then I’ll switch to that as a dependency. Although this makes me wonder why there’s a distinct `vscode-languageserver-types` package then.

**Comment by remcohaszing** [comment]
I’m closing this issue as I’ve migrated my Monaco related libraries to [`monaco-languageserver-types`](https://github.com/remcohaszing/monaco-languageserver-types) and it turns out there are more types I’m missing from `vscode-languageserver-types`.
