### ISSUE TITLE
Adopt `LogOutputChannel` API which finalized in VS Code 1.74

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode-languageserver-node#1206]
See https://code.visualstudio.com/api/references/vscode-api#LogOutputChannel

See also https://github.com/microsoft/vscode/issues/176481 and https://github.com/microsoft/vscode/issues/176479 in which @sandy081 is encouraging adoption of this API.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode-languageserver-node/issues/1116


CC @dbaeumer

**Comment by gjsjohnmurray** [comment]
Sorry for the duplicate. Closing this one.
