### ISSUE TITLE
Change Notification handler's return type signature from void to Thenable<void>

### ISSUE THREAD

**Issue by yf-yang** [microsoft/vscode-languageserver-node#1207]
`void` and `Promise<void>` could be treated the same, but certain eslint rules like [@typescript-eslint/no-misused-promises](https://typescript-eslint.io/rules/no-misused-promises/) disallows such cases to prevent potential bugs. 

When using jsonrpc package, I found it is able to sequentially process async handlers by calling setImmediate, and that is how it works with a request handler that returns a Thenable. However, the return signature of notification handlers are still `void` instead of `Thenable<void>`. Since jsonrpc has the ability to correctly deal with it, can we modify their signature?

**Comment by dbaeumer** [comment]
@yf-yang json-rpc doesn't sequentially process the async handlers. It awaits the result of a response handler to be able to send the result back to the caller however the library doesn't ensure that the next request is executed after a former request has finished. Executing requests in parallel is even something that is explicitly supported in LSP. 

IMO changing the signature of the notification handler's will even cause more confusion. So I am actually not in favor of making that change.

**Comment by yf-yang** [comment]
Yep, you are right. I was considering constructuring a new Promise, it can be guaranteed to be fully dispatched before setTimeout/setImmediate, but I ignored one could also create a promise and resolve it in another setTimeout/setImmediate……

I'm wondering what kind of confusion are you thinking of? In my understanding, a `Thenable<void>` simply means that the handler could be both sync and async, and it is in accordance with `HandlerResult`. Do you mean that replacing it with `Thenable` will cause users to imply that someone is waiting for the handler to return?

Anyway, for my own case, I checked [typescript-language-server](https://github.com/typescript-language-server/typescript-language-server)'s implementation, they just call an async function without awaiting it in a sync notification handler. That could be a workaround.

**Comment by dbaeumer** [comment]
> Do you mean that replacing it with Thenable will cause users to imply that someone is waiting for the handler to return?

Yes, this is what I meant. Users might assume that if something returns a Promise the caller will await it.

**Comment by yf-yang** [comment]
I see. I'll close the issue for now.
