### ISSUE TITLE
Internal error IllegalArgumentException

### ISSUE THREAD

**Issue by LavanyaBurlagadda** [microsoft/vscode-languageserver-node#1208]
When we are using Java Language Server sometimes we are getting this issue reported 

To Our Error Tracking Application we are getting an Error like

Internal Error

In Logs we are getting the below code,

```
Java Language Client-front:   Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Invalid identifier
```

Why are these errors being reported?

**Comment by dbaeumer** [comment]
This repository is about the general LSP library implementations not about a specific language server. Please report the error against https://github.com/Microsoft/vscode-java-pack
