### ISSUE TITLE
Language client attempts to resolve CodeEdit's `edit` when a `command` is provided

### ISSUE THREAD

**Issue by datho7561** [microsoft/vscode-languageserver-node#1216]
Given a language server that supports `codeAction/resolve` for `edit`, if the server returns a code action where `edit` is `null`/`undefined`, but `command` is set, the language client sends a resolve request to try to resolve `edit` when trying to apply the code action. Is this the intended behaviour?

I read through https://github.com/microsoft/vscode-languageserver-node/issues/737, and it seems this behaviour is intentional,  but I would like to confirm.

**Comment by dbaeumer** [comment]
Yes, this is intended behavior since a CodeAction can have an edit and a command. You need to provide an empty edit if you want to avoid the resolve call.
