### ISSUE TITLE
`enabledApiProposals` makes VSCode error

### ISSUE THREAD

**Issue by sumneko** [microsoft/vscode-languageserver-node#1217]
```
[error] [Extension Host] Error: Extension 'sumneko.lua' CANNOT use API proposal: extensionRuntime.
Its package.json#enabledApiProposals-property declares: [] but NOT extensionRuntime.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api sumneko.lua
	at b (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:44827)
	at get extensionRuntime [as extensionRuntime] (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:14104)
	at activate (c:\Users\yijiusun\.vscode\extensions\sumneko.lua-3.6.17-win32-x64\client\out\extension.js:52:39)
	at Ui.db (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:14833)
	at Ui.cb (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:14532)
	at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:12550
	at async f.n (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:6818)
	at async f.m (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:6781)
	at async f.l (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:6238)
```

**Comment by dbaeumer** [comment]
The LSP client is a npm module and not an extension. I keep the `enabledApiProposals` as a documentation thing but it should never be seen by VS Code. Did you copy this into your extension?

**Comment by dbaeumer** [comment]
The LSP client is a npm module and not an extension. I keep the `enabledApiProposals` as a documentation thing but it should never be seen by VS Code. Did you copy this into your extension?

**Comment by sumneko** [comment]
> The LSP client is a npm module and not an extension. I keep the `enabledApiProposals` as a documentation thing but it should never be seen by VS Code. Did you copy this into your extension?

![image](https://user-images.githubusercontent.com/5213431/226828375-1a31ef48-4fe4-4c18-87bc-8cd6b6c84f61.png)

No, it only exists in `vscode-languageclient`

**Comment by dbaeumer** [comment]
Can you provide me with a Github repository I can clone that demos that. I can't reproduce this and I use the client in many locations.

**Comment by sumneko** [comment]
The repository is `https://github.com/LuaLS/vscode-lua`, and you need to run `[buildClient.sh](https://github.com/LuaLS/vscode-lua/blob/master/buildClient.sh)` to build the client.

**Comment by dbaeumer** [comment]
Build it fails for me :-(

```
@dbaeumer ➜ /workspaces/vscode-lua (master) $ ./buildClient.sh
Building VS Code Extension Client...
Compiling TypeScript...

up to date, audited 57 packages in 406ms

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> lsp-sample-client@0.0.1 build
> tsc

src/extension.ts:6:20 - error TS2307: Cannot find module '../3rd/vscode-lua-doc/extension.js' or its corresponding type declarations.

6 import luadoc from "../3rd/vscode-lua-doc/extension.js";
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in src/extension.ts:6
```

**Comment by sumneko** [comment]
You need to `git submodule update --init --recursive` first. My bad.

**Comment by sumneko** [comment]
> I can't reproduce this and I use the client in many locations.

Or maybe you can just check https://marketplace.visualstudio.com/items?itemName=sumneko.lua first?

**Comment by dbaeumer** [comment]
IMO this is a problem of your extension: it somehow uses API from VS Code that is proposed (e.g. API declared here: https://insiders.vscode.dev/github/microsoft/vscode/blob/d08ec5d974b201a3c29bf0010ac736b0c41aad9a/src/vscode-dts/vscode.proposed.extensionRuntime.d.ts#L10) and the message complains that your extension doesn't enable this proposed API 

```
[error] [Extension Host] Error: Extension 'sumneko.lua' CANNOT use API proposal: extensionRuntime.
```

Since you haven't listed it in your package.json

But please be aware that you can't publish an extension which uses proposed API to the market place.

**Comment by dbaeumer** [comment]
I will close the issue since I am very confident that this is NOT caused by the empty proposal in the client package.json.

Please ping if you think otherwise.

**Comment by dbaeumer** [comment]
No problem. You are welcome.
