### ISSUE TITLE
DirectUri with http instead of file protocol

### ISSUE THREAD

**Issue by bartoszkrawczyk2** [microsoft/vscode-languageserver-node#1218]
Hi!

Is it possible to use http? For example:
`rootUri: "https://path/to/directory"` instead of `rootUri: "file:///path/to/directory"`.

I expect serving files via http would be fine, but what about directories? What response should it return?

Thanks

**Comment by dbaeumer** [comment]
In principal yes, if there is a file system provider that can server a FS off an https route. VS Code by default has no such provider so it a normal setup it will fail. But extensions can provide their own.
