### ISSUE TITLE
vscode-languageserver onShutdown method does not allow cancellation by design

### ISSUE THREAD

**Issue by marinsokol5** [microsoft/vscode-languageserver-node#1219]
Hi,

I am trying to write a language server and I am using `vscode-languageserver` package as my building block. 

And I want to have a logic triggering on cancellation upon receiving a shutdown request from the client. 
And I am using [onShutdown](https://github.com/microsoft/vscode-languageserver-node/blob/4d7d8f4229a539f36bc28c634470539bcda8b362/server/src/common/server.ts#L1510) method for that but it doesn't seem to trigger the cancellation from the client. 

Upon diving a bit in the code, it seems that that's intentional, as I see that there is a [new cancellation token being created](https://github.com/microsoft/vscode-languageserver-node/blob/4d7d8f4229a539f36bc28c634470539bcda8b362/server/src/common/server.ts#L1684) instead of propagating the one from the `onRequest` handler. 

I can easily trigger it by doing a manual request handler like 
```
this.connection.onRequest(ShutdownRequest.method, async (token) => {
      let timeoutId: ReturnType<typeof setTimeout> | null = null;
      token.onCancellationRequested(() => {
          // This cancellation will be invoked!!
          if (timeoutId) {
              clearTimeout(timeoutId);
          }
      })
      await new Promise(r => {
          timeoutId = setTimeout(r, 10000)
      });
    });
```

Instead of 

```
this.connection.onShutdown(async (token) => {
    let timeoutId: ReturnType<typeof setTimeout> | null = null;
    token.onCancellationRequested(() => {
        // This cancellation will not be invoked!!
        if (timeoutId) {
            clearTimeout(timeoutId);
        }
    });

    await new Promise(r => {
        timeoutId = setTimeout(r, 50000)
    });
    
});
```

But I am curious into why is this done, is cancellation logic during shutdown handler discouraged?

**Comment by dbaeumer** [comment]
Actually that is on purpose since it would be very unclear what cancel of a shutdown means. Would a client need to send another `initialize` request or not. What state would the server be in. This is why we don't let the server react on cancel. The spec  says

```
Clients must not send any notifications other than exit or requests to a server to which they have sent a shutdown request. Clients should also wait with sending the exit notification until they have received a response from the shutdown request.
```

So clients are even not allowed to send a cancel notification.

**Comment by marinsokol5** [comment]
Thanks a lot @dbaeumer!! 

This actually clicks on a lot of levels now, I haven't perceived the cancellation as a separate notification because of the convenience that these wrappers handle cancellation, but yeah of course it's a separate notifcation to the server... 

That also explains why the [initializeHandler](https://github.com/microsoft/vscode-languageserver-node/blob/4d7d8f4229a539f36bc28c634470539bcda8b362/server/src/common/server.ts#L1648) behaves the same way.
```
Until the server has responded to the initialize request with an [InitializeResult](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initializeResult), the client must not send any additional requests or notifications to the server.
```
