### ISSUE TITLE
Language server no longer starts in debug when client is in debug mode

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-languageserver-node#122]
- run the html extension in vscode as extension out of VSCode
- the html language server can not be attached to, it is not started i debug mode.

Debugging this down I see that  typeof v8debug === 'object'  is evaluating to false.
Must have to do with the latest version of Electron we run on.

Thinking about it, maybe this check should be removed all together. To much magic here.
It should fully be controlled by the user (a setting, like css.trace.server) and/or the code that creates the client.

**Comment by siegebell** [comment]
dup of #106?

**Comment by dbaeumer** [comment]
@aeschli this is fixed in the 2.6.x version of the client library. On which version are you seeing this ?

**Comment by dbaeumer** [comment]
It is also fixed in master. Any objection to close ?
