### ISSUE TITLE
How to use workspace/didChangeWatchedFiles

### ISSUE THREAD

**Issue by vinistock** [microsoft/vscode-languageserver-node#1227]
Hello!

I'm trying to register for watching files from a language server and I must be misunderstanding or doing something wrong.

This is basically what I'm doing:
1. I register the capability using the notification below. I'm doing this when executing `initialized`
2. Then when the server receives `workspace/didChangeWatchedFiles` I just print the notification parameters
3. I manually change some Ruby files to trigger the notification

However, I never receive the notification (nor do I get any errors from the registration). Is there anything obvious I'm missing? Does the server need any static capabilities enabled to use dynamic capability registration or watching files?

```typescript
// Watch every Ruby file for addition, change or removal
{
  message: "client/registerCapability",
  params: {
    registrations: [
      {
        id: "workspace/didChangeWatchedFiles",
        method: "workspace/didChangeWatchedFiles",
        registerOptions: {
          watchers: [
            {
              globPattern: `${currentDir}/**/*.rb`,
              kind: 7
            },
          ],
        },
      },
    ],
  }
}
```

**Comment by r3m0t** [comment]
Is `currentDir` definitely correct?

**Comment by dbaeumer** [comment]
@r3m0t thanks for answering

glob patterns have no variable support. You need to build the pattern using the workspace folder information.

I will close the issue. Please ping if this doesn't help.

**Comment by vinistock** [comment]
The `currentDir` is just a local variable with the workspace folder as a string (e.g.: `/Users/blah/workspace/my_project`). So the resulting pattern is something like `/Users/blah/workspace/my_project/**/*.rb`. I'm trying to use the [global pattern](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#pattern) as opposed to the relative one. Is that not supported?

When you say build the pattern using the workspace folder information, what do you mean?

**Comment by dbaeumer** [comment]
I misunderstood this. I will reopen the issue.

A code pointer to debug this is here: https://insiders.vscode.dev/github/microsoft/vscode-languageserver-node/blob/dbaeumer/adequate-ptarmigan-chocolate/client/src/common/fileSystemWatcher.ts#L49

File watching is only supported relative to the workspace folder. You can't watch an arbitrary folders. So to watch all Ruby files in all open workspace folders you need to use `**/*.rb`

If you want to watch only inside a specific workspace folder or a folder outside the workspace we need to add support for a relative pattern to LSP which we currently don't have.

**Comment by vinistock** [comment]
Thank you for the pointer on how to debug. The issue was that I was not including an `id` when sending `client/registerCapability`, which made the client treat is as a notification and then it couldn't find a handler for it (since it's registered as a request). Including the ID does the trick.
