### ISSUE TITLE
Provide universal request/notification middleware

### ISSUE THREAD

**Issue by tooltitude-support** [microsoft/vscode-languageserver-node#1229]
It would be nice to have a middleware which works independently of what the request/notifications is. I.e. it should just receive JSON objects, and allow to do arbitrary things with the results.

Where it's useful:
- Telemetry/performance measuring
- Middleware for custom requests/notifications
- Ability to intercept many different request kinds in one place, though at the cost of less typed code

**Comment by dbaeumer** [comment]
That got implemented, but not shipped yet. See https://insiders.vscode.dev/github/microsoft/vscode-languageserver-node/blob/main/client/src/common/client.ts#L324
