### ISSUE TITLE
URI type alias in metamodel is unused and base type URI is not defined in the spec

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode-languageserver-node#1238]
Some changes were made in https://github.com/microsoft/vscode-languageserver-node/issues/1032 that I don't really understand. They broke my codegen and I'm not sure the correct to fix it because the spec seems incomplete/inconsistent.

Before this change, there were fields that were defined as URIs (with `URI` being a reference):

```
{
	"name": "href",
	"type": {
		"kind": "reference",
		"name": "URI"
	},
	"documentation": "An URI to open with more information about the diagnostic error."
}
```

This was a reference to a type alias named URI that was defined in `typeAliases` as an alias to the base type `string`:

```
{
	"name": "URI",
	"type": {
		"kind": "base",
		"name": "string"
	},
	"documentation": "A tagging type for string properties that are actually URIs\n\n@since 3.16.0",
	"since": "3.16.0"
},
```

This meant the parser required no special knowledge of what `URI` was, it was just a type alias to an existing base type (string). As far as I can see, this was all consistent and valid.

However now there's a type alias named `URI` that appears to be unused and there are references to a _base_ kind of `URI` that is not defined in the list of base types in the spec (3.17 or 3.18):

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#baseTypes

Should the type alias be removed, and `URI` added to the base types in the spec, or should this remain as a type alias and "base" reverted to "reference"?

@dbaeumer @michaelpj

**Comment by DanTup** [comment]
> Should the type alias be removed

Sorry, I wasn't looking at the latest version of this file - it looks like this _was_ removed. I also see that there are base types defined in metaModel.schema.json.

So actually I think this is all correct (and I just need to handle the new/renamed `URI` base type) - although it is intended that the base types in the published web spec don't match those in the metamodel?

**Comment by dbaeumer** [comment]
I need to publish the latest version on the web-site. Will do this today.

**Comment by DanTup** [comment]
Ah, I didn't realise that section was generated from here too. That all makes sense then (and no rush to publish this on account of me, I have all I need - thanks! 🙂)
