### ISSUE TITLE
Feature request: support multi-range document formatting

### ISSUE THREAD

**Issue by daiyousei-qz** [microsoft/vscode-languageserver-node#1244]
Now that `ProvideDocumentRangeFormattingEditsSignature` with batch formatting support is added in vscode, could we also add support in the language client as well? Reading through the source code, I suppose this is very easy to implement as we only need to check the server capability and forward parameters to the server.

@c-claeys Do you have any plan to implement this? If not, I can help to draft the change.

**Comment by dbaeumer** [comment]
PR absolutely welcome

**Comment by c-claeys** [comment]
I've been on vacation but I was planning on sending a PR now that I'm back. @daiyousei-qz let me know if you'd prefer otherwise you could help review it instead

**Comment by daiyousei-qz** [comment]
> I've been on vacation but I was planning on sending a PR now that I'm back. @daiyousei-qz let me know if you'd prefer otherwise you could help review it instead

Please go ahead. I meant to help if you don't have cycles to work on this. Thank you for proposing this fix to LSP!

**Comment by dbaeumer** [comment]
This is already in.
