### ISSUE TITLE
"Error: Write after end" when stopping a language client which uses a socket connection

### ISSUE THREAD

**Issue by Papierkorb2292** [microsoft/vscode-languageserver-node#1249]
I have a language client that I connect to a language server running in a completely different process. To do this, the language server starts a server socket on a local port which I basically connect to using `connection = net.connect(...)` and by giving `() => Promise.resolve({ writer: connection, reader: connection})` as server options to the `LanguageClient` constructor.

Now, when I want to stop the language client (for example because the user wants to update settings), I call the `.stop` method. After a few seconds however, this results in the following error:
```
rejected promise not handled within 1 second: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
```
While debugging, I have already removed the closing of the connection, so the language client must be doing it. This seems to happen in-between sending the `shutdown` and the `exit` notification, because I'm receiving the first one but not the second. I have also set a breakpoint where the data is written to the stream (the `write` method of the `WritableStreamWrapper` class placed into my `dist/extension.js`), from which I know that the last thing written is the header of the `exit` notification (`'Content-Length: 33\r\n\r\n'`), but not the notification itself.

`connection.writeable` is set to false when the language client calls `connection.end` (after calling `connection.exit`, which should send the exit notification) in `BaseLanguageClient.stop`, which will also call `.end` on the socket returned by `net.connect`. `connection.readable` stays true.

What could be the problem?

**Comment by dbaeumer** [comment]
In the LSP setup a sever doesn't create the socket. The client does. This is to easy the connection setup since otherwise a client would need to wait for the server to create the socket. All the error code handling and shutdown code is written with this assumption.

See https://insiders.vscode.dev/github/microsoft/vscode-languageserver-node/blob/main/client/src/node/main.ts#L379

I will close the issue. Please ping if this doesn't help.
