### ISSUE TITLE
Allow to send extended ClientCapabilities

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode-languageserver-node#125]
Trying to add support for  a [custom protocol extension](https://github.com/sourcegraph/langserver/pull/6) that requires additional flags in `ClientCapabilities` set.
However, I cannot find a way to hook into the `initialize` request to send these additional `ClientCapabilities`. [The request is sent inside the private `initialize`](https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/main.ts#L873), which is called by `start()`. Please add the ability to configure the `ClientCapabilities` that are sent, so we can tell the LS that we added additional request handlers it can use.

**Comment by dbaeumer** [comment]
Please use `nitializationOptions` for this. The ClientCapabilities are owned by the protocol spec.

**Comment by felixfbecker** [comment]
I don't see why `InitializationOptions` should carry this kind of information if it expresses the client's support for a certain capability.
There is a spec for the protocol extension: https://github.com/sourcegraph/language-server-protocol/blob/master/extension-files.md#initialization

**Comment by dbaeumer** [comment]
I have no problems on defining new client capabilities in the spec. However I don't see the advantage of allowing clients to append properties since this opens doors for naming conflicts.

**Comment by felixfbecker** [comment]
The plan was to propose that extension to the standard eventually, but before we first wanted to experiment with it and maybe change it as we meet limitations, to make sure it really fits every use case of every LS (because it is hard to change once it is part of the standard, and then we are stuck with it until the next major protocol version). Part of testing meant building an extension for VS Code to test the LS implementations of the protocol extension - which I was unable to do because of the described limitation.

To avoid naming conflicts we added an `x` prefix to the requests and the capabilities, to make clear it is an extension and to make sure it can't clash with the standard properties (whatever gets accepted in the end). That's a pretty well established pattern, for example for custom HTTP headers and custom MIME types. Allowing to customize `ClientCapabilities` / the `initialize` request is really like allowing to customize every method here.

I don't see harm in allowing to add custom params or properties, as long as they are prefixed and do not break anything, and especially if the plan is to propose it to the standard once it was tested widely enough. Contrary, not allowing this can result in merging proposals not tested end-to-end across a variety of languages, where after a few months we notice this doesn't work for all languages and a different design would have been better.

**Comment by dbaeumer** [comment]
But shouldn't we then first decided on the process/way how to do this before we add API to do it. We had a comparable discussion in VS Code for proposed API and we decided to put means in place that for example and extension can't be published to the market place if it uses proposed API to avoid later breakage and discussion that the API still needs to be supported. Any idea on how this should work ?

**Comment by felixfbecker** [comment]
If you mean discussing the proposal - a lot of discussion went into it. And of course there will be more discussion once it gets actually proposed, but as I said it was important to first get an end-to-end implementation both for testing purposes and also for actually using it as soon as possible.
In this case it was a protocol addition that doesn't actually have such a big use case in VS Code, but where LS run in isolated environments (Sourcegraph, Eclipse Che, ...). I just wanted to implement these additions in a VS Code extension to test the LS locally.
Both proposal and implementation of the protocol addition are written in ways that don't break anything. They are prefixed to avoid naming collisions, are only used by the LS if the client expressed support for it through `ClientCapabilities`, otherwise the LS will fall back to direct file system access. The client will of course work whether or not the LS supports it.
I am not asking to support the protocol additions in VS Code (yet) - I am just asking for a generic API to customize the `LanguageClient` so that I can write a small extension (doesn't even have to get published to the marketplace) to test out custom protocol additions that use extended `ClientCapabilities` to signal support. Maybe you misunderstood me - you might want to take a look at my PR to see the use case: https://github.com/sourcegraph/langserver/pull/6/commits/070a32aa503a3c514556ebecc37a21b9f3bf88e3

**Comment by dbaeumer** [comment]
I do see the use case, however I don't fully understand what the difference is if I let you send these and client options or as intializationOptions. In the client options case with a prefix x you need code adoption as well when the x is removed.

If we want to add this as experimental client options then I would rather have it explicit as 'experimentalClientOptions' and have it transferred as n optional bag.

**Comment by felixfbecker** [comment]
The difference is semantics. `ClientCapabilities` is very clearly defined as the capabilities of the client. Supporting an extension is a capability. That extension doesn't have to be "experimental", it is simply an unofficial extension - _experimental_ still kind of implies that it is official.
I don't see the argument for name clashes. The capability `xcontentProvider` very clearly states that the client supports the xcontent extension. What else should it mean? With what property should it clash? An unknown property in JSON should just be ignored in any implementation.

Think also about the symmetry. A language server can send extended unofficial `ServerCapabilities`, expressing support for extended requests on the server side. Why shouldn't the client be able to do so too?

There is no code adoption "needed" really. When the extension gets proposed to be integrated into the standard (maybe with some slight changes), the old `x` prefixed extension can still be supported in a transition phase by both the client and servers, but deprecated. The standard non-prefixed version can get implemented in a minor release. As it is an extension, it is only used in a small collection of servers (and clients) we have control over. When everything is updated to the standard version, we can do a major release and remove support for the extension (the prefixed version).

In theory, `experimentalClientCapabilities` could work. But I don't see the reason for that added complexity. The extension spans all namespaces of the LSP: It adds a member `xcontent` to the `textDocument/` namespace, it adds a member `xfiles` to the `workspace/` namespace, why shouldn't it add the members `xfilesProvider` and `xcontentProvider` to `ClientCapabilities`. Following your logic, these members should get added to `experimentalTextDocument` and `experimentalWorkspace` instead - this all makes it just more verbose and complex, without adding any benefit. Name clashes are protected against by using a prefix, and the `x` makes it clear that this is unofficial / experimental / an extension.

**Comment by dbaeumer** [comment]
I am not suggesting to have experimentalClientCapabilities as a separate bag. I was more thinging about something like this (I do agree that the name wasn't helping):


```ts
interface ExperimentalClientCapabilites {
   [key: string]: number | boolean | string | ExperimentalClientCapabilites 
}

interface ClientCapabilities {
   experimental: ExperimentalClientCapabilites 
}
``` 

Otherwise it will be very hard to be speced.

In general I have no problems to add filesProvider and contentProvider as official client capabilities to the protocol since having these does make sense to me.
