### ISSUE TITLE
No diagnostics in JSON

### ISSUE THREAD

**Issue by zardoy** [microsoft/vscode-languageserver-node#1252]
Might be similar to https://github.com/microsoft/vscode-languageserver-node/issues/1128

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2 (also insiders)
- OS Version: Windows/macOS

This problems exists from `1.68.0`. in `1.67.0` everything seems to be fine.

1. Extension code to reproduce:

```ts
// most probably you want to register it to some command
const testContent = '{test: 5}'

vscode.workspace
    .openTextDocument({
        content: testContent,
        language: 'json',
    })
    .then(async doc => {
        await vscode.window.showTextDocument(doc)
    })
```

2. Run the code

Actual: Diagnostics are present
Expected: Both editors have diagnostics

Text changes doesn't produce diagnostics in these editors. Of course, after reload diagnostics will be there.
```[tasklist]
### Tasks
```

**Comment by dbaeumer** [comment]
Fixed by https://github.com/microsoft/vscode-languageserver-node/pull/1251

**Comment by zardoy** [comment]
@dbaeumer Was it published? If not do you an eta? (I can still see it happens in current release.)

**Comment by zardoy** [comment]
And by the way thank you for the fix!

**Comment by dbaeumer** [comment]
Sorry, now. I will prepare a new next release.

**Comment by dbaeumer** [comment]
I release new next version. client is 8.2.0-next.2
