### ISSUE TITLE
Request textDocument/documentSymbol failed. TypeError: Cannot read properties of undefined (reading 'range') on MacOS

### ISSUE THREAD

**Issue by Elringus** [microsoft/vscode-languageserver-node#1257]
I'm receiving error reports from users of my language server VS Code extension with the following log:

![image](https://github.com/microsoft/vscode-languageserver-node/assets/2056864/f05a9a9c-f6a0-4ecc-b0be-4e2957c974a3)

They are all running MacOS and the error starts occurring randomly some time after re-installing VS Code and the extension. To this time I've received reports from 4 different users, with the same error and they all were using Mac, so I guess it's OS-specific.

I'm pretty sure this comes somewhere from the `vscode-languageserver` package, but unfortunately I can't reproduce this on my mac test machine to share a more useful stacktrace.

**Comment by dbaeumer** [comment]
This can have various reasons. Most likely is an invalid response data from the server or a type error on the server itself if written in JS/TS. 

Have you tried to look at the bundled code to see if it points to something. You could also generate source maps during bundling and then use those to point to the TS location.

**Comment by dbaeumer** [comment]
Please ping if you have more information about where this happens.

**Comment by Elringus** [comment]
@dbaeumer I've skimmed through this repository sources a bit and was able to pintpoint the issue even with the mangled stacktrace thanks to `.asSymbolInformations` and `.map` hints. Here it is: https://github.com/microsoft/vscode-languageserver-node/blob/43b7c7265de6b0662cfe58576c9d7b894a946ce3/client/src/common/protocolConverter.ts#L879

`location` var is undefined here, because `location` property which value is assigned to it doesn't exist on [DocumentSymbol](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#documentSymbol).

**Comment by Elringus** [comment]
Specifically, I guess this is the root cause:

https://github.com/microsoft/vscode-languageserver-node/blob/43b7c7265de6b0662cfe58576c9d7b894a946ce3/client/src/common/documentSymbol.ts#L106
https://github.com/microsoft/vscode-languageserver-node/blob/43b7c7265de6b0662cfe58576c9d7b894a946ce3/types/src/main.ts#L2946

`DocumentSymbol.is()` doesn't detect actual document symbol on MacOS, so it's treated as `SymbolInformation`, hence the following undefined issue.

**Comment by Elringus** [comment]
Nevermind, it was my bad. `DocumentSymbol` I was sending to the language client had `null` for optional props, while the client checks specifically for `undefined`. And still it somehow worked on Windows and even passed `DocumentSymbol.is` checks in my test env, but failed for some Mac users. The typescript woes.
