### ISSUE TITLE
Workspace diagnostic pull retries continuously even when sending DiagnosticServerCancellationData error

### ISSUE THREAD

**Issue by kralicky** [microsoft/vscode-languageserver-node#1261]
I am writing a language server (in Go) with an associated vscode plugin. I was able to implement the Workspace Diagnostics pull capability successfully, but it appears that vscode repeats the workspace diagnostic request every 2 seconds forever which seems unusual. According to the specification [here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnosticServerCancellationData) I should be able to return `{"retriggerRequest": false}` in the error data to (ostensibly) stop the retry attempt, but it doesn't seem to be working. I confirmed in the debugger that a `LSPCancellationError` is received on the client with the data field matching `DiagnosticServerCancellationData`, but it doesn't appear to do anything differently.

Relevant code here maybe
https://github.com/microsoft/vscode-languageserver-node/blob/f9329674f73896939b6d498a6bae75ffb644e515/client/src/common/diagnostic.ts#L537-L556
and also here but I'm not quite sure if this is related to workspace diagnostics
https://github.com/microsoft/vscode-languageserver-node/blob/f9329674f73896939b6d498a6bae75ffb644e515/client/src/common/diagnostic.ts#L459-L470

**Comment by dbaeumer** [comment]
Actually the workspace diagnostics are designed to be long polling. So there is basically no need to avoid retriggering since the server can keep the request open as long as it wants. That is why ion the spec the [DiagnosticServerCancellationData](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnosticServerCancellationData) is under document diagnostics and not workspace diagnostics. Could you please explain in which use case you need to cancel the request and don't want to be triggered again?

**Comment by kralicky** [comment]
I thought that might have been the case, but couldn't figure out how to get the streaming part to work, and got confused by the cancellation docs. I am using gopls's jsonrpc implementation but they might not have this implemented, since as far as i know they only use the old(?) push model for diagnostics. Do you know of any existing implementations of this I can use as a reference?

**Comment by dbaeumer** [comment]
You can see an example implementation in the test server here: https://insiders.vscode.dev/github/microsoft/vscode-languageserver-node/blob/main/client-node-tests/src/servers/testServer.ts#L457

In general the workspace diagnostic pull is no different than a normal request. What you need to do is to stream the results back using a result progress. With the JS server library we provide this would look like this:

```TS
connection.languages.diagnostics.onWorkspace((_params, _token, _workDoneProgress, resultProgress) => {
	return new Promise(async (resolve) => {
		// Send 1000 diagnostic result progress reports
		for (let i = 0; i < 1000; i++) {
			resultProgress?.report({
				items: [ {
					kind: DocumentDiagnosticReportKind.Full,
					uri: URI.parse('file:///file1.txt').toString(),
					version: 1,
					items: [
						Diagnostic.create(Range.create(1, 1, 1, 1), 'diagnostic', DiagnosticSeverity.Error)
					]
				}]
			});
			// Wait a second before sending the next
			await new Promise((resolve) => setTimeout(resolve, 1000));
		}
		// We are done. Close the long polling stream
		resolve({ items: [] });
	});
});
```

Hope that helps.

**Comment by kralicky** [comment]
I think I am on the right track now, thanks. However, it looks like vscode's implementation of workspace pull doesn't match the specification exactly:
https://github.com/microsoft/vscode-languageserver-node/blob/2041784436fed53f4e77267a49396bca22a7aacf/client/src/common/diagnostic.ts#L573-L587

From https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_diagnostic:


> * diagnostics for a higher document version should win over those from a lower document version (e.g. note that document versions are steadily increasing)
> * diagnostics from a document pull should win over diagnostics form a workspace pull if no version information is provided.

Should vscode be favoring the workspace tracked diagnostics if they have higher version numbers than the document tracked ones?

Also, there appears to be a typo here where the wrong message type is linked (Document instead of Workspace):
![image](https://github.com/microsoft/vscode-languageserver-node/assets/8194899/7f24b8f5-977b-405c-8152-924bb9fab816)

**Comment by kralicky** [comment]
I was able to implement this successfully here: https://github.com/kralicky/protols/blob/f0c9a0410be82f134d910f79b6b3fa46898d773c/pkg/lsp/server.go#L493
The important part is making sure the `workspace/diagnostic` handler blocks until the request is canceled, and while it's blocked it sends updates separately via `$/progress` that contain a `WorkspaceDiagnosticReportPartialResult`. Each report needs to contain the latest complete set of diagnostics for a given file every time it's sent (can this be optimized?) along with a `Version` that increments whenever a file's diagnostics change, regardless of the actual file's revision, since changes in related files can cause other unchanged files to add or remove diagnostics. Not sure if that's the intended way to handle versions though.
There's also document pull requests happening at the same time, and as long as each request (except `workspace/diagnostic`) is responded to in the order they were received, it seems to work.

**Comment by dbaeumer** [comment]
> Should vscode be favoring the workspace tracked diagnostics if they have higher version numbers than the document tracked ones?

No, the idea is really that document pulls are more important than workspace pulls since they were made for that specific document.

I will fix the spec.

Great to hear you got it working

**Comment by dbaeumer** [comment]
For the spec see: https://github.com/microsoft/language-server-protocol/pull/1771

**Comment by dbaeumer** [comment]
Updated the spec. 

I will close the issue for now.
