### ISSUE TITLE
Error proof handling of header in messageBuffer.js

### ISSUE THREAD

**Issue by NagarajKandoor** [microsoft/vscode-languageserver-node#1276]
Below code is bit too harsh in **messageBuffer.js**. 

![image](https://github.com/microsoft/vscode-languageserver-node/assets/22025145/6e88d591-101f-4302-9e8d-96243647b7e8)

**Suggestion**: 
If header doesn't contains (colon symbol) in that case **log info and return.**

**Note**:  My VsCode extension stopped working because server returned validation message was having CRLF and it was more than 3 lines.
https://stackoverflow.com/questions/76652259/vscode-extension-error-message-header-must-separate-key-and-value-using

Thanks
Nagaraj

**Comment by dbaeumer** [comment]
IMOP this will just sweep an error under the carpet and makes it hard to detect follow on errors since the length attribute is mandatory in the header. So I am not a fan of adding this.
