### ISSUE TITLE
Links in the metaModel description sometimes uses markdown style 

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-languageserver-node#1279]
Most links are `{@link Object.memeber <text>}` But some times it is `[Object](link)`

**Comment by dbaeumer** [comment]
The only problematic once I could find are: 
[`general.positionEncodings`](#clientCapabilities) 
[`capabilities.positionEncoding`](#serverCapabilities)

We should point them to a URL. Are you referring to those?

**Comment by karthiknadig** [comment]
```
"documentation": "A request to resolve the type definition locations of a symbol at a given text\ndocument position. The request's parameter is of type [TextDocumentPositionParams]\n(#TextDocumentPositionParams) the response is of type {@link Declaration}\nor a typed array of {@link DeclarationLink} or a Thenable that resolves\nto such."
```
Cases like : `[TextDocumentPositionParams]\n(#TextDocumentPositionParams)`

Also, we probably should remove `\n` from the documentation.

**Comment by dbaeumer** [comment]
I fixed the links. However I am against removing the new lines since it will delete any paragraph structure.
