### ISSUE TITLE
Colons in windows drive letters are over-encoded in file URIs

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode-languageserver-node#1280]
The LSP client appears to send file URIs with over-encoded colons:

> file:///C%3A/Dev/Test%20Projects/dart_application_3

I think this happens because VS Code's own URI class [is doing this](https://github.com/Microsoft/vscode/issues/2990) and it's just being used here:

https://github.com/microsoft/vscode-languageserver-node/blob/f2ff7d55464a1f58f978cb6635bd8865f050553c/client/src/common/codeConverter.ts#L154C62-L154C62

In Dart, I found that some first-party libraries handle this, and some do not. I've been trying to figure out whether it's valid or not (eg. whether the bug is VS Code/here, or in Dart) but the closest I've found to anything definitive is here:

https://url.spec.whatwg.org/#windows-drive-letter

> A Windows drive letter is two code points, of which the first is an [ASCII alpha](https://infra.spec.whatwg.org/#ascii-alpha) and the second is either U+003A (:) or U+007C (|).

> A string starts with a Windows drive letter if all of the following are true:
> 
> - its [length](https://infra.spec.whatwg.org/#string-length) is greater than or equal to 2
> - its first two code points are a [Windows drive letter](https://url.spec.whatwg.org/#windows-drive-letter)
> - its [length](https://infra.spec.whatwg.org/#string-length) is 2 or its third code point is U+002F (/), U+005C (\), U+003F (?), or U+0023 (#).

It also does not include a colon in the "path percent encode set" (only in the userinfo encode set), although it's not to me whether that _forbids_ encoding it.

**Comment by dbaeumer** [comment]
If I remember the discussion we had about this correctly there is no specification how this should be done when encoding drive letters and having `%3A` is equally correct. And VS Code will not change this due to the huge impact this has.

Since I know this can be difficult for server the VS Code client offers a way to intercept all URI -> string conversions and vice versa. So if you want to change how they are send over the wire the best I can suggest is to use that capability. See https://github.com/microsoft/vscode-languageserver-node/blob/f2ff7d55464a1f58f978cb6635bd8865f050553c/client/src/common/client.ts#L370

**Comment by DanTup** [comment]
@dbaeumer that's what I've ended up doing for now - but that is VS Code specific and the goal is for the LSP server to work with all clients (and similarly, clients to work with all servers).

Is your opinion that a) all servers should handle encoded colons, or b) that clients should not send encoded colons (and VS Code extensions should fix up the URI)? I think it would be beneficial to note this one way or the other in the spec so it's clear who should fix any incompatibilities that arise from this.

I'm happy to send a PR that adds a note somewhere if you can confirm which direction you'd prefer it went. Thanks!

**Comment by dbaeumer** [comment]
IMO a server needs to handle all valid encoded URLs. I am not a fan of specing how URLs should be encoded in LSP. 

Add a note to the specification makes total sense to me.

**Comment by DanTup** [comment]
Thanks - I opened https://github.com/microsoft/language-server-protocol/pull/1786 - happy to tweak/rewrite as you'd prefer!
