### ISSUE TITLE
`client/registerCapability` is sent even when the client doesn't support dynamic registration

### ISSUE THREAD

**Issue by bugeats** [microsoft/vscode-languageserver-node#1281]
Said best [here](https://github.com/helix-editor/helix/blob/5ec126d3e27dcfe2544396b664cbad04611ad7eb/helix-term/src/application.rs#L1116):

> Language Servers based on the `vscode-languageserver-node` library often send client/registerCapability even though we do not enable dynamic registration for most capabilities. We should send a MethodNotFound JSONRPC error in this case but that rejects the registration promise in the server which causes an exit. So we work around this by ignoring the request and sending back an OK response.

**Comment by dbaeumer** [comment]
There is little I can do as an implementor of the library. It is up to the server to respect client capabilities and not send requests to the client that the client doesn't support in case the server is advertised as one being used outside VS Code. The server should also  handle the rejected promise from the registration call and should not let it drop to the event loop. So I recommend you are best talking to the owner of the server.

Please ping if you think I misunderstood the issue.

**Comment by dbaeumer** [comment]
But all a server can do is to reject the promise which will not be different to the client returning `MethodNotFound`
