### ISSUE TITLE
TextDocument.positionAt and offsetAt incorrectly include line endings

### ISSUE THREAD

**Issue by mroch** [microsoft/vscode-languageserver-node#1285]
The `Position` docs say that you can't specify a position between an `\r` and `\n`, or after a line ending:

https://github.com/microsoft/vscode-languageserver-node/blob/f2ff7d55464a1f58f978cb6635bd8865f050553c/textDocument/src/main.ts#L19-L20

And that if the `character` is too big it defaults to the line length:

https://github.com/microsoft/vscode-languageserver-node/blob/f2ff7d55464a1f58f978cb6635bd8865f050553c/textDocument/src/main.ts#L40-L41

But these cases do include the line endings:

```js
const document = newDocument('A\nB\rC\r\nD');
assert.equal(document.offsetAt(Positions.create(0, 10)), 2);
assert.equal(document.offsetAt(Positions.create(1, 10)), 4);
assert.equal(document.offsetAt(Positions.create(2, 2)), 6); // between \r and \n
assert.equal(document.offsetAt(Positions.create(2, 3)), 7);
assert.equal(document.offsetAt(Positions.create(2, 10)), 7);
assert.equal(document.offsetAt(Positions.create(3, 10)), 8);

// this should be (2, 1), I think
assert.deepEqual(document.positionAt(6), Positions.create(2, 2)); // between \r and \n
```

I think the line length of each line is 1, so the invalid positions should be treated as `(line, 1)`, and the correct offsets should be 1, 3, 5, 5, 5, 8 respectively

**Comment by dbaeumer** [comment]
@aeschli since you are back from vacation can you please have a look since you originally wrote the code.

**Comment by dbaeumer** [comment]
@aeschli could you please have a look at this.

**Comment by dbaeumer** [comment]
PR got merged and released in new next version.
