### ISSUE TITLE
No type binding for getFeature('workspace/executeCommand')

### ISSUE THREAD

**Issue by limarkxx** [microsoft/vscode-languageserver-node#1289]
No type binding for LanguageClient `.getFeature('workspace/executeCommand')`

**Comment by dbaeumer** [comment]
We can add this for consistency. However since this is a server to client message there will not be much a client can do with the feature.

**Comment by limarkxx** [comment]
The initial motivation for this was working around https://github.com/vimeo/psalm/issues/10094, to [call](https://github.com/psalm/psalm-vscode-plugin/pull/268/commits/f2db8e7d1802c34f146f850a12a71ef858dc567e#diff-93fb658a5a39bdff013a96dd2d3d088f495fbb173e4fbb10285f01612b583d1fR193) `.dispose()` to avoid getting a `command 'test' already exists` error when initializing multiple LSPs in a single project.

**Comment by dbaeumer** [comment]
Fixed for next release
