### ISSUE TITLE
Content-Length property not parsed correctly

### ISSUE THREAD

**Issue by beccamc** [microsoft/vscode-languageserver-node#1305]
For some projects, we are seeing a fatal server shutdown. 

![image](https://github.com/microsoft/vscode-languageserver-node/assets/9122518/9d6439ce-ac48-4e24-8d02-3f9dd75fd30f)

This is because we have some responses from the server not being parsed correctly. Although Content-Length is present, the results have been parsed with "jsonrpc" as the key. Somewhere our results are getting corrupted and are not parsing correctly. 

![image](https://github.com/microsoft/vscode-languageserver-node/assets/9122518/1110cb2e-3454-4850-ae7e-216049150dfc)

I've debugged and logged from the server. The content we are sending looks correct. Here are three calls that were incorrectly parsed on the client. 
```
{"jsonrpc"" => ""2.0","id":277,"method":"workspace/inlayHint/refresh","params":[]}Content-Length: 76"}
{"jsonrpc"" => ""2.0","id":278,"method":"workspace/codeLens/refresh","params":[]}Content-Length: 78"}
{"jsonrpc"" => ""2.0","id":279,"method":"workspace/diagnostic/refresh","params":[]}Content-Length: 82"}
```

If you look at the [MonitorStream.log](https://github.com/microsoft/vscode-languageserver-node/files/12441220/MonitorStream.log), the information being passed from the Roslyn server look correct and are not corrupted. 
> {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"[LanguageServerHost][07:24:25.094][Start]codeLens/resolve"}}Content-Length: 77
> 
> {"jsonrpc":"2.0","id":277,"method":"workspace/inlayHint/refresh","params":[]}Content-Length: 76
> 
> {"jsonrpc":"2.0","id":278,"method":"workspace/codeLens/refresh","params":[]}Content-Length: 78
> 
> {"jsonrpc":"2.0","id":279,"method":"workspace/diagnostic/refresh","params":[]}Content-Length: 82

Given that the results being sent from the server are parse-able and correct, it seems like something is getting corrupted on the client side? Here is the project that this repros consistently with: [ReproNetCode.zip](https://github.com/microsoft/vscode-languageserver-node/files/12441774/ReproNetCode.zip)

**Comment by beccamc** [comment]
I've found the problem, but I don't know what it means. In the middle of the buffer we have this logging inserted..

```
[Info]Begin Processing assembly Assembly-CSharp candidates

[Info]End Processing assembly Assembly-CSharp candidates

[Info]Timing:
Total: 719.7607 msec
  OnVisitSyntaxNode: 0.6842 msec (150) [0.1479]
    HasGhostComponentAttribute: 0.2518 msec (4) [0.001]
```

This is definitely what is messing up the parsing. I took a look at the messageBuffer [tryReadHeaders](https://github.com/microsoft/vscode-languageserver-node/blob/a2954d24a550ea567df3d60d1c8eb86d39707149/jsonrpc/src/common/messageBuffer.ts#L93) parsing. Everything is going normally, and the method is producing `Content-Length : x` until it hits this: 

![image](https://github.com/microsoft/vscode-languageserver-node/assets/9122518/9dc55391-cd93-45fb-8775-e8d3df49d2b8)

Looking at the log of what is sent from the server, this addition isn't coming from the server.  There are three calls in a row that match what the client is trying to parse. Length 1064, 139 and then 196. 

> {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"[LanguageServerHost][04:14:36.761][Start]textDocument/semanticTokens/range"}}Content-Length: 1064
> 
> {"jsonrpc":"2.0","id":13,"result":[{"range":{"start":{"line":6,"character":17},"end":{"line":6,"character":22}},"data":{"SyntaxVersion":"2023-08-28T16:14:36.3575048Z-10020-0","ListIndex":0,"TextDocument":{"uri":"file:///c:/Users/beccam/Downloads/ReproNetCode/ReproNetCode/Assets/Truc.cs"}}},{"range":{"start":{"line":12,"character":13},"end":{"line":12,"character":17}},"data":{"SyntaxVersion":"2023-08-28T16:14:36.3575048Z-10020-0","ListIndex":1,"TextDocument":{"uri":"file:///c:/Users/beccam/Downloads/ReproNetCode/ReproNetCode/Assets/Truc.cs"}}},{"range":{"start":{"line":15,"character":9},"end":{"line":15,"character":14}},"data":{"SyntaxVersion":"2023-08-28T16:14:36.3575048Z-10020-0","ListIndex":2,"TextDocument":{"uri":"file:///c:/Users/beccam/Downloads/ReproNetCode/ReproNetCode/Assets/Truc.cs"}}},{"range":{"start":{"line":21,"character":9},"end":{"line":21,"character":15}},"data":{"SyntaxVersion":"2023-08-28T16:14:36.3575048Z-10020-0","ListIndex":3,"TextDocument":{"uri":"file:///c:/Users/beccam/Downloads/ReproNetCode/ReproNetCode/Assets/Truc.cs"}}}]}Content-Length: 139
> 
> {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"[LanguageServerHost][04:14:36.766][End]textDocument/codeLens"}}Content-Length: 196

This bug was originally reported with Unity projects. Poking around online it does look like this logging may be related?

**Comment by dbaeumer** [comment]
Here is what I guess is happening:

- the extension uses stdio to talk to the server
- inside the server process there is a library or some other code that write to stdio which then messes up the whole communication.

You have two choices:

- somehow redirect stdio to the connection inside the server process if this is possible inside C#.
- or the better solution is to use pipes / file sockets to communicate with the server then you have your own dedicated communication channel. The VS Code LSP client support this with the `--pipe` options `https://github.com/microsoft/vscode-languageserver-node/blob/a2954d24a550ea567df3d60d1c8eb86d39707149/client/src/node/main.ts#L347`

**Comment by beccamc** [comment]
I've resolved this issue by creating the dedicated communication channel. Closing - thanks!
