### ISSUE TITLE
installServerIntoExtension: questionable dependency on launch.json attributes

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-languageserver-node#131]
We've deprecated the launch.json `outDir` attribute in September 2016.
Through https://github.com/Microsoft/vscode/issues/16143#issuecomment-263640877 we've learned that the `installServerIntoExtension` is relying on the `outDir` and fails if the new attribute `outFiles` is used.
I suggest to fix this by removing this brittle code.

**Comment by dbaeumer** [comment]
The code simply checks if the VSCode setup (launch.json and tsconfig.json) is correct in terms to which output destinations they point. If it fails simply the check fails. The language server is not relying on this. It might only make debugging more complicated. 

In general I think code like this should better be in the debugger land :-). The reason I have it is that people complained about not being able to debug and it was most of the time a setup problem.

**Comment by dbaeumer** [comment]
I will remove the check for now since with the new outFiles setting there is a lot of flexibility now. I will keep the check for tsconfig misalignment.
