### ISSUE TITLE
Server: Is there some document about how to receive semantic tokens request?

### ISSUE THREAD

**Issue by imbant** [microsoft/vscode-languageserver-node#1318]
Hi there.

I'm developing a language server. It provides semantic highlight. By I'm not sure how to receive something like `textDocument/semanticTokens/full` from client.

My code like this:
```ts
import { createConnection, ProposedFeatures } from "vscode-languageserver/node";

const connection = createConnection(ProposedFeatures.all);

connection.onInitialize(() => {
  // ...
  return {
    semanticTokensProvider: {
      legend: {
        tokenTypes: ["function", "namespace"], // register legend like the same thing in VS Code example
        tokenModifiers: [],
      },
    },
  }
})

connection.languages.semanticTokens.on(() => {
  // DOESN'T called 
});
```

`connection.languages.semanticTokens.on` doesn't trigger my callback when client open document, change text. I add breakpoints and logs and prove it doesn't work.

I have read [this guide](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide) and I have successfully implemented semantic highlighting through the vs code API. But this is not the same in languageserver-server.
I don't know how to use `connection`. I got `languages.semanticTokens.on` just by intelligent completion. Is there some document about this? Additional, can language server manually update or push semantic tokens to client, for force update?

**Comment by rcjsuen** [comment]
Your code [looks like mine](https://github.com/rcjsuen/dockerfile-language-server-nodejs/blob/dd63322e311996fc19d25c4b2830a9d12a50b288/src/server.ts#L717-L726) so it's probably your client that's the problem.

**Comment by dbaeumer** [comment]
Trigger the request is a client responsibility. All I can recommend right now is to file an issue against the client you are using?

Did you server signal to the client that it supports semantic tokens via the initialize repsonse?

**Comment by imbant** [comment]
@dbaeumer @rcjsuen  Thank you both very much for your suggestions. I will focus on the client.

As my code above, I returned `semanticTokensProvider` in `connection.onInitialize` callback. That is all I did to signal to the client that the server supports semantic tokens. I am working on VS Code, so I use `vscode-languageclient` to implement the client. The client code is just the same as [the official repository](https://github.com/microsoft/vscode-extension-samples/blob/main/lsp-sample/client/src/extension.ts). Is something else I missed?

I know my question is very basic, thank you again for taking the trouble. In fact, I don't know where to look for the documentation for the `vscode-languageserver-node` or `vscode-languageclient` npm package. I currently use these two websites ([LSP](https://microsoft.github.io/language-server-protocol/) and [vs code guide](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide)) and read the interface code to speculate on how to use these tow packages. If there is more detailed information, I think I can understand the problem faster

**Comment by imbant** [comment]
I changed my `InitializeResult` to this. Like [Volar.js](https://github.com/volarjs/volar.js/blob/ab8c913b32cfe6dc5354b3044d7447fa839293fe/packages/language-server/src/common/utils/registerFeatures.ts#L64) did.

```diff
    const result: InitializeResult = {
        capabilities: {
            semanticTokensProvider: {
+             full: false,
+             range: true,
              legend: {
                    tokenTypes: [...tokenTypes],
                    tokenModifiers: [],
                },
            },
        },
    };
```

Then the `onRange` callback can be called

```ts
connection.languages.semanticTokens.onRange()  // works

connection.languages.semanticTokens.on()     // still doesn't work
```

Now I can see the semantic highlight exactly in the position and token type defined by my language server now.

But I still don't know how it works :(

**Comment by rcjsuen** [comment]
@imbant If you want to use `on()` then you should use `full: true` or `full: { delta: false }`. I use the latter [myself](https://github.com/rcjsuen/dockerfile-language-server-nodejs/blob/dd63322e311996fc19d25c4b2830a9d12a50b288/src/server.ts#L254-L277).

**Comment by imbant** [comment]
@rcjsuen I got it. Thanks for your sharing! It happens that my scene needs to support the highlighting of a large amount of code. So `range: true` works well for performance but thanks anyway, I know better how it works

**Comment by rcjsuen** [comment]
> It happens that my scene needs to support the highlighting of a large amount of code. So `range: true` works well for performance but thanks anyway, I know better how it works

I would suggest supporting `full: true` also where possible as not every editor may support `textDocument/semanticTokens/range`. An editor may also choose not to use your semantic tokens information if you only support `range: true`.

https://github.com/microsoft/vscode-languageserver-node/blob/d33ec0fce0bec8addd208651f28c2b96fe065d44/protocol/src/common/protocol.semanticTokens.ts#L47-L56

**Comment by imbant** [comment]
> > It happens that my scene needs to support the highlighting of a large amount of code. So `range: true` works well for performance but thanks anyway, I know better how it works
> 
> I would suggest supporting `full: true` also where possible as not every editor may support `textDocument/semanticTokens/range`. An editor may also choose not to use your semantic tokens information if you only support `range: true`.
> 
> https://github.com/microsoft/vscode-languageserver-node/blob/d33ec0fce0bec8addd208651f28c2b96fe065d44/protocol/src/common/protocol.semanticTokens.ts#L47-L56

It's really a helpful document. I will read it carefully
