### ISSUE TITLE
find/replace not triggering didChange

### ISSUE THREAD

**Issue by nicolasg-da** [Microsoft/vscode-languageserver-node#133]
- VSCode Version: 1.7.2
- OS Version: OS X 10.11.6
- vscode-languageserver-node: 3.0.1-alpha.3

Steps to Reproduce:

    open 3 files with the same string in it.
    Search + replace for that string.
    Language server protocol only fires a change event for one of the changed files.

Same thing happens for a rename request.
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#rename-request

What I expected:

a textDocument/didChange for every file that was changed.

This issue was migrated from https://github.com/Microsoft/vscode/issues/15966 since the problems persist with v. 3.0.1-alpha.3:

**Comment by dbaeumer** [comment]
Got fixed in vscode-languageclient@3.0.1-alpha.12

**Comment by vazexqi** [comment]
@nicolasg-da Were you able to verify the fix? I just ran into this issue with the current version of Visual Studio Code Insiders build.

See Microsoft/language-server-protocol#203 where I have a screenshot and screencast of the issue.

I am _assuming_ that Visual Studio Code Insiders uses the latest vscode-languageserver-node? Or do I need to build my own version?

**Comment by vazexqi** [comment]
Never mind. Disregard my previous question. I made a mistake and didn't check the version of the vscode-languageclient in my plug-in. Used 

```
  "dependencies": {
    "vscode-languageclient": "^3.1.0"
  }
``` and it is reporting it properly now.
