### ISSUE TITLE
With pullDiagnostics is there a way to tun off document diagnostics and only allow workspace diagnostic requests?

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-languageserver-node#1332]

**Comment by dbaeumer** [comment]
Currently not. The reason is that document diagnostics on top of workspace diagnostics are use for prioritization.

**Comment by karthiknadig** [comment]
We have some tools that always perform whole workspace diagnostics. We currently handle this by trying to filter the other file outputs out. But this seems to go against the intent of the tool.

In this case, if we return 'unchanged' for the document request and provide full diagnostics from the workspace request, it should be handled by client in the same way the tool intends to provide diagnostics right?

**Comment by dbaeumer** [comment]
Yes, that should work.
