### ISSUE TITLE
Is there an example with named pipes for communication between LS client and server

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-languageserver-node#1333]

**Comment by dbaeumer** [comment]
The libraries have full support for this. See https://insiders.vscode.dev/github/microsoft/vscode-languageserver-node/blob/main/client/src/node/main.ts#L31. All you need to do is to specify `pipe`. Then the client with pass `--pipe ${pipename}` as an argument to the server process.

In our code base there is no concrete example since our servers are Node and use IPC (which at the end uses named pipes :-)). But servers not written in TS are usually using named pipes.

Anything else you need?

**Comment by karthiknadig** [comment]
@dbaeumer We discussed that you might move `pipename` to be an Environment Variable right?

**Comment by dbaeumer** [comment]
Will very likely not happen since even under Windows there are commands (`[System.IO.Directory]::GetFiles("\\.\\pipe\\")`) every user can execute to list all pipes available in the system. So an env variable doesn't add any value.

**Comment by rgrunber** [comment]
We're planning to implement this in vscode-java also. The draft proposal just sets `TransportKind.pipe` at https://github.com/microsoft/vscode-languageserver-node/blob/4b77bb4d2e47dbfeeed6c263c28054eced60e030/client/src/node/main.ts#L69 for the executable representing the language server process. The server process then just reads `--pipes` to connect to the named pipe.

**Comment by denis-shienkov** [comment]
Hi guys, is it possible to use a custom (external) named pipe (provided by the already running external LSP server), in a form like: 
```
\\.\pipe\qbs-lsp-1884
```
to startup the LanguageClient at all? Or this does not supported yet?

e.g. I faced with this issue: https://github.com/microsoft/vscode-languageserver-node/issues/1570

**Comment by dbaeumer** [comment]
@denis-shienkov this is currently not support. Pipe names are internal and local. However you can implement your own transport to make this happen. See https://github.com/microsoft/vscode-languageserver-node/blob/dbaeumer/probable-muskox-peach/client/src/node/main.ts#L126

**Comment by denis-shienkov** [comment]
@dbaeumer, hi, could you please provide a more info, how to do it? Do you meant a MessageTransports? If yes, then please, give a more in fo about, what's a main idea of this transports (what's needs to be implemented by me, maybe, you have an examples)?

**Comment by dbaeumer** [comment]
Yes. As server options you basically use `(() => Promise<ChildProcess | StreamInfo | MessageTransports | ChildProcessInfo>)`. Easiest is to return a MessageTransport which returns a reader / writer pair that is then used to talk to the LSP server.

**Comment by denis-shienkov** [comment]
Hmm, I tried do it like this:

```
    public constructor(pipeName: string) {
        const serverOptions = this.createMessageTransports(pipeName);
        const clientOptions: LanguageClientOptions = {
            documentSelector: [{ language: 'qbs' }],
        };
        console.info('Starting Qbs language client on pipe: ' + pipeName);
        this.languageClient = new LanguageClient('Qbs', (() => serverOptions), clientOptions);
        this.languageClient
            .start()
            .then(async () => {
                console.info('Qbs language client started on pipe: ' + pipeName);
            })
            .catch((reason) => {
                void vscode.window.showErrorMessage('Cannot start Qbs language server');
                console.error('Unable to start Qbs language client on pipe: ' + pipeName + ', ' + reason);
            });

    }
```

but it fails with:

```
Starting Qbs language client on pipe: \\.\pipe\qbs-lsp-9388
Unable to start Qbs language client on pipe: \\.\pipe\qbs-lsp-9388, Error: listen EADDRINUSE: address already in use \\.\pipe\qbs-lsp-9388
```

**Comment by dbaeumer** [comment]
I never tried reusing the pipe code for non local pipes. So I can't say if it is working? I was more thinking about implementing the server function all by yourself.

**Comment by denis-shienkov** [comment]
WOW, it does work, need to use the createServerPipeTransport() function instead (it uses internally net.createConnection(), instead of net.createServer()). So, we need only to connect to the ready pipe, but do not create it!!

@dbaeumer, Many thanks anyway.
