### ISSUE TITLE
Unable to use import statements in my client

### ISSUE THREAD

**Issue by yogiduzit** [microsoft/vscode-languageserver-node#1334]
My Codemirror (code editor) client is communicating to the `typescript-language-server` over websockets. I am able to get autocomplete, diagnostics etc. In my code editor, I am trying the following:
```
import { Foo } from './bar';
```
and getting an error saying 'Cannot find module bar`.

I researched the documentation and tried this:
```
const typeDeclarationDoc = TextDocument.create('file:///bar', '.ts', 1, 'export interface Foo { ... }');
```

How do I make the language server aware of this file that declares the `Foo` interface?

**Comment by dbaeumer** [comment]
@yogiduzit you are better off asking this question in the project that maintains the `typescript-language-server`. From an LSP client perspective all files that match the document selector used when creating the file are synced to the server.
