### ISSUE TITLE
`CompletionItem#additionalTextEdits` are ignored

### ISSUE THREAD

**Issue by BoykoAlex** [microsoft/vscode-languageserver-node#1335]
Sometimes completion item may not end up resolved when applied and `additionalTextEdits` are therefore ignored.
If use selects a completion item in the list with arrow keys items are resolved and additional edits are applied. However, if user clicks an item in the completion items list with mouse without selecting an item (probably this is the bug - that the item doesn't seem to get selected) i.e. a highlighted item in the list of completions the item isn't resolved and additonal edits never show show up.

Also, curious if restriction editing the completion line can be lifted. Or perhaps additional edits can be applied once the main edit is applied, i.e. edits are applied sequentially: 1. main edit, 2. additional edits. Currently it looks like these edits are applied in parallel.

**Comment by dbaeumer** [comment]
I was not able to reproduce this. Do you have any detailed steps on how to do this?

Please note that a resolve call is only sent once. So if you scroll over items and the later on click on one it will not receive a second resolve call.

**Comment by BoykoAlex** [comment]
@dbaeumer I think it is my bad. Additional edits are applied it seems with a limitation that they must be applied to a line different from where the main edit occurs. As soon as i have same line edit in the list of additional edits all edits are ignored. Consequently, everything looks as designed at this point.

Do you know if this limitation of additional edits being not on the same line with the main edit can be lifted? I saw something about this topic here: https://github.com/microsoft/vscode/issues/96779#issuecomment-627954429

**Comment by dbaeumer** [comment]
I think the same line limitation will not be lifted. Can't you replace more text on the same line?

**Comment by BoykoAlex** [comment]
It is the suffix for a property key that needs to be added based on the property value type. Depending on whether type is a map, list, enum/atomic. There are two options either add the suffix via completion item resolve or fetch java types to determine map, list, enum/atomic or whatever during the properties metamodel generation step (properties indexing). Type fetching during indexing would increase the time it takes to index the properties.
Adding the suffix works fine with the command though... it appears a bit later which is okay... the only annoying part is to undo the change one would hav to invoke undo twice: first - for the suffix, second - for the main edit
