### ISSUE TITLE
Feature Request: itemDefaults for completions to be combined with completion item

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-languageserver-node#1338]
In Pylance, we return a lot of duplicate data in our completion list. We'd like to use the new `itemDefaults` for completions. 

However, some of the data is not duplicated. Only parts of it. But if we send back itemDefaults, they're not combined with the data on each item.

Here's an example completion result:

```jsonc
{
    "itemDefaults": {
         "data": {
              filePath: "root/test.py",
              position: { line: 0, col: 1 },
              workspacePath: "root"
         }
    }
    items: [
         {
             label: "foo",
             kind: 6
             data: {
                  symbolLabel: "foo" 
             }
         },
         {
             label: "bar",
             kind: 6
             data: {
                  symbolLabel: "bar" 
             }
         }
    ]
}
```

When a resolve happens (if we send the data this way), the `filePath`, `position`, and `workspacePath` are lost.

Resolve completionItem:

```jsonc
{
      label: "foo",
      kind: 6
      data: {
            symbolLabel: "foo"  // No filePath, position, or workspacePath
      }
}
```

I believe that's because this line here picks one or the other:
https://github.com/microsoft/vscode-languageserver-node/blob/4b77bb4d2e47dbfeeed6c263c28054eced60e030/client/src/common/protocolConverter.ts#L591

Would it be a breaking change to change this line in the protocolConverter.ts to something like this instead?

```typescript
   const data = {...(defaultData ?? {}), ... (item.data ?? {});
```

If that's agreeable, I can submit a PR. Thanks.

**Comment by rchiodo** [comment]
Or maybe a different change would be to add something to the spec that allows the combination of data. The main goal is to dedupe data on every completionItem.

**Comment by dbaeumer** [comment]
Looks like a dup to https://github.com/microsoft/language-server-protocol/issues/1802 for me.

The spec currently states that if a item defines items available in the items default it is a replace operation and not a merge operation. So changing the code is not an option since it could break existing users.

Lets continue the discussion in the other item
