### ISSUE TITLE
undefined as a cancellation token

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/vscode-languageserver-node#134]
Is it intended that the last parameter of a request is considered to be a cancellation token only if it is defined, even though `cancellationToken` is marked as an optional?

**Comment by dbaeumer** [comment]
@akosyakov not sure I understand this. The cancellationToken is a node API thing and does never how up as a parameter on a request. The is a special request to send cancelation to the server.

**Comment by akosyakov** [comment]
It is passed as the last argument into [MessageConnection.sendRequest](https://github.com/Microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/main.ts#L209).  This method accepts an undefined value as a token, since it is optional. But [implementation](https://github.com/Microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/main.ts#L694) treats the last arg as a parameter if it is undefined rather than the cancellation token.

We have a method that also accepts the cancellation token as the last optional parameter and then delegates to `MessageConnection.sendRequest`. When one calls this method without the token then an undefined value is passed to send `MessageConnection.sendRequest` and it breaks.

**Comment by dbaeumer** [comment]
OK. Now I see. Thanks for clarification. This is definitely a bug. I will look into fixing this.
