### ISSUE TITLE
vscode-jsonrpc version "6.0.0" gives path argument null error

### ISSUE THREAD

**Issue by OjasWadhwani** [microsoft/vscode-languageserver-node#1340]
I'm trying to run a VSCode extension locally using LSP with some custom server logic behind it. It currently throws the error: `Request initialize failed with message: The "path" argument must be of type string. Received null`

The stack trace points to a `vscode-jsonrpc` file (v6.0.0).

**Comment by dbaeumer** [comment]
Can you please provide me with the stack trace. Otherwise it is hard to say what is going on.

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
