### ISSUE TITLE
SemanticTokensBuilder out of sync with `@types/vscode`

### ISSUE THREAD

**Issue by siefkenj** [microsoft/vscode-languageserver-node#1341]
I am not sure exactly what the relationship between this repository and `vscode` is supposed to be, but the documentation here https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide has sample code which does not work with the `SemanticTokensBuilder` provided by this repo.

In particular, the constructor of the class in `@types/vscode` does not match the constructor here.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e3e3dd182af39774f9cb9af61d85fce46a22ec38/types/vscode/index.d.ts#L4217C19-L4217C19

vs

https://github.com/microsoft/vscode-languageserver-node/blob/84285312d8d9f22ee0042e709db114e5415dbdde/server/src/common/semanticTokens.ts#L125

**Comment by dbaeumer** [comment]
The VS Code API is different from the LSP API due to the fact that LSP is a client / server protocol that can be used in languages other than JavaScript/TypeScript as well.

So it is expected that these differences exist.
