### ISSUE TITLE
Completion no longer working

### ISSUE THREAD

**Issue by vinistock** [microsoft/vscode-languageserver-node#1342]
Hello! I noticed recently that part of our LSP completion stopped working. I'm trying to figure out what happened, but I'm having some trouble and I would appreciate some guidance.

VS Code version: 1.83.1
vscode-languageclient version: 9.0.1

We provide completion for two things at the moment: require paths (which are like imports in TypeScript, but for Ruby) and constants. For some reason, only the require path completion stopped working.

Here you can see the behaviour working properly in the beginning of the GIF https://github.com/Shopify/vscode-ruby-lsp?tab=readme-ov-file#features.

This is our server capabilities for completion. The path completion happens on the `/` char (which isn't working anymore). Constant completion happens on any uppercase char and that continues to work fine.

```typescript
{
  triggerCharacters: ["/", "A", "B", "C", "..."], // forward slash + all uppercase chars
  resolveProvider: false,
  completionItem?: {
    labelDetailsSupport?: true;
  }
}
```

For the path completion, we return an array that looks like this.

```typescript
[
  {
    label: "ruby_lsp/listener",
    text_edit: {
      range: { ... },
      new_text: "ruby_lsp/listener",
    },
    kind: 18, // REFERENCE 
  }
]
```

If I turn on verbose tracing for our server, I can see that the completion request is correctly returning an array of items like the one above when I press `/`, but nothing happens in the editor. It's really odd because constant completion continues to work as expected.

I thought it might be related to the `languageDetailsSupport` configuration, but so far no luck. I have tried:

- Adding a `labelDetails` attribute to the response
- Adding a `documentation` attribute to the response
- Adding a `detail` attribute to the response
- Removing the `labelDetailsSupport` capability
- Downgrading `vscode-languageclient`

Any ideas on what I am missing? Should we be returning something else for the path completions?

**Comment by dbaeumer** [comment]
The easiest way to find out what is going on is to debug this. The corresponding code is in `completion.js` in the client modules `lib/common` folder. The code in question is on line 94

```ts
return client.protocol2CodeConverter.asCompletionResult(result, defaultCommitCharacters, token);
```

`result` contains the items return from the server. They are then converted into VS Code items. Would be good to know how many are handed off to VS Code.

**Comment by dbaeumer** [comment]
Let me know how it goes.

**Comment by dbaeumer** [comment]
@vinistock actually the results look fine. I suspect that this is more a VS Code bug. Toi confirm this you could do the following:

- implement a test extension that returns completion items as a hard coded list
- do this using only a VS Code completion item provider.

I can provide you with a skeleton extension if it is of any help

**Comment by vinistock** [comment]
Finally figured out the issue. We switched to using the new Ruby parser recently and I had not realized that it includes the string quotes as part of its node locations. We were returning off by one characters to the editor, which then didn't match the expected contents and VS Code refused to apply them.

It's working now after https://github.com/Shopify/ruby-lsp/pull/1203. Sorry for the confusion and thank you very much for your assistance!
