### ISSUE TITLE
Reformat all code

### ISSUE THREAD

**Issue by sqs** [Microsoft/vscode-languageserver-node#135]
It would make it easier to contribute to this library if the code were formatted according to some standard formatting rules. As these are becoming more popular for TypeScript, I'm finding that I want to keep format-on-save enabled in my editor at all times. But if I do, then when I save it causes erroneous diffs, such as adding a space after the first `:` at https://github.com/Microsoft/vscode-languageserver-node/blob/3f9a09c05975f5039332fa65e71b1bb825df0363/jsonrpc/src/messageWriter.ts#L13.

I would submit a PR to do this myself, but this is a big yet quick change that it seemed would be easier for one of the regular maintainers to do. If you want me to submit a PR this weekend when not as many people will have WIP branches (to avoid merge conflicts), I am happy to do so. :smile:

**Comment by dbaeumer** [comment]
Makes sense to me. I formatted all code and added the corresponding settings.
