### ISSUE TITLE
[Extension Host] TypeError: Cannot read properties of undefined (reading 'stdio')

### ISSUE THREAD

**Issue by Simonl9l** [microsoft/vscode-languageserver-node#1352]
I'm Trying to use `vite` rather than `webpack` for bundling - using [this](https://www.eliostruyf.com/vite-bundling-visual-studio-code-extension/) blog post - and have added a similar question there. As `vite` becomes a more popular alternative this may also help others.

I can run in local/debug fine, but once I package the extension if get the above error in the `vscode` Developer Console. I'm assuming (perhaps incorrectly) that I have a bundling issue but I'm no typescript expert, it's a means to and end to get a VS Code LSP Extension to work for our custom language.

Given the `TransportKind.stdio` as used (below) as I guess this is related.

Any help greatly appreciated.

My package.json has the following dependencies:
```json
{
  "devDependencies": {
    "@types/vscode": "^1.84.0",
    "eslint": "^8.53.0",
    "typescript": "^5.2.2",
    "vite": "^4.5.0",
    "vite-plugin-eslint": "^1.8.1",
    "vite-plugin-static-copy": "^0.17.0"
  },
  "dependencies": {
    "@types/node": "^20.8.10",
    "vscode-languageclient": "^9.0.1",
    "vscode-languageserver-protocol": "^3.17.5",
    "vscode-jsonrpc": "^8.2.0"
  }
}
```

this is my extension activation:
```ts
try {

        let serverModule = context.asAbsolutePath('./out/Server'); 
   
        let debugOptions =  ['--wait-for-debugger'] ; 
        let runExe : Executable = {
            command: serverModule,
            transport: TransportKind.stdio,
            options: {
                env: process.env,
                shell: true,
            }
        };

        let debugExe : Executable = {
            command: serverModule,
            transport: TransportKind.stdio,
            args: debugOptions,
            options: {
                env: process.env,
                shell: true,
            }
        }
        // If the extension is launched in debug mode then the debug server options are used
        // Otherwise the run options are used
        let serverOptions : ServerOptions = {
            run: runExe,
            debug: debugExe
        };

        // Options to control the language client
        let clientOptions: LanguageClientOptions = {
            // Register the server for plain text documents
            documentSelector: [{ scheme: 'file', language: 'plaintext' }],
            synchronize: {
                // Notify the server about file changes to '.csproj files contained in the workspace
                fileEvents: workspace.createFileSystemWatcher('**/.{my ext}')
            }
        };

        // Create the language client and start the client.
        client = new LanguageClient(
            '{my language}',
            '{my description}',
            serverOptions,
            clientOptions
        );

        client.registerProposedFeatures();

        // Start the client. This will also launch the server
        client.start();
    }
    catch(error)
    {
        console.log(error)
    }
```

**Comment by dbaeumer** [comment]
@Simonl9l very hard to say why this fails. Can you provide me with a GitHub repository I can clone that contains a minimal example to reproduce this. Then I can have a look. But since I don't know vite I might not be able to be of good help.

**Comment by r3m0t** [comment]
Looks like your `ServerOptions` are wrong. It should be `{ module: "out.js"}` to run a JS LSP. https://code.visualstudio.com/api/language-extensions/language-server-extension-guide

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
