### ISSUE TITLE
No clear way to write no-op middleware for responses to client-initiated requests

### ISSUE THREAD

**Issue by RobbyCBennett** [microsoft/vscode-languageserver-node#1353]
The way isn't the `languageClient.onRequest('method_here', handler_here)` method, but it's with the `middleware` object in `clientOptions`. However, I just want to use the response. I don't want to augment/mutate it. How do I pass along the response unaltered in the middleware handler? This would be a lot easier if I could find some documentation for this library.

**Comment by dbaeumer** [comment]
If you don't want to alter the result simply return the response from the `next()` handler. 

Soemthing like: https://github.com/microsoft/vscode-eslint/blob/24d2ac45b2fe1b8cc8639038b724ba48610da8e2/client/src/client.ts#L464
