### ISSUE TITLE
Webpack warning

### ISSUE THREAD

**Issue by DoctorKrolic** [microsoft/vscode-languageserver-node#1355]
I'm trying to pack a VS Code extension using webpack. I am on the latest public version of `vscode-languageclient` and I'm getting this warning when I try to build the extension:
```
WARNING in ./node_modules/vscode-languageserver-types/lib/umd/main.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/vscode-languageserver-protocol/lib/common/api.js 23:13-51
 @ ./node_modules/vscode-languageserver-protocol/lib/node/main.js 24:13-37
 @ ./node_modules/vscode-languageclient/lib/common/client.js 9:41-82
 @ ./node_modules/vscode-languageclient/lib/node/main.js 27:17-44
 @ ./src/extension.ts 6:32-64 7:15-61
```
It it a known problem? It it even safe to use webpack in such case or it just generates less efficient code?

**Comment by dbaeumer** [comment]
@aeschli can you help me with this. It is caused by the changes you did to the UMD packaging and I see the same when trying to package my eslint extension.

**Comment by aeschli** [comment]
I think the problem is that webpack doesn't pick up the browser bits.
Make sure to to have
```
resolve: {
			mainFields: ['browser', 'module', 'main'],
```

**Comment by aeschli** [comment]
I assumed you wanted to build a web extension.

If this is a desktop extension, it is
```
resolve: {
			conditionNames: ['import', 'require'],
			mainFields: ['module', 'main'],
```

**Comment by dbaeumer** [comment]
@aeschli Thanks. Your tips worked for me.

**Comment by dbaeumer** [comment]
@DoctorKrolic see @aeschli tips.

**Comment by DoctorKrolic** [comment]
Thanks for tips, the issue is resolved. However, since this required me to explicitly specify additional configuration parameters, I think there are steps that can be done to fully resolve this incident:
1. Can code be changed on your end to avoid this? If you can just change some bits to avoid everyone else specifying additional webpack config parameters, this would be really cool
2. If the first suggestion cannot be done for various reasons (and it is most likelt so), I think it would be benifitial to include this solution into documentation, e.g. create a section in the root `README`, where the issue and its solution are briefly described. This way you would avoid such questions in the future and make this info searchable via search engines and AI assistants, so people can discover this easily

**Comment by aeschli** [comment]
What change was needed?

**Comment by DoctorKrolic** [comment]
The latter one:
```
resolve: {
			conditionNames: ['import', 'require'],
			mainFields: ['module', 'main'],
```

**Comment by TamiTakamiya** [comment]
We also encountered this issue in our VS Code extension build and adding
```
resolve: {
			conditionNames: ['import', 'require'],
			mainFields: ['module', 'main'],
```
fixed the build issue.  However, the extension now started showing another error:
```
crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported
```
We may be able to resolve this specific error, but I wonder if adding those parameters to `resolve` could have changed other behaviors as well.
