### ISSUE TITLE
Migrating language packages on v3.0.0

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/vscode-languageserver-node#136]
Any plans to migrate `monaco-json` and other language packages on v3.0.0? It hurts to use the latest vscode language server with them.

**Comment by dbaeumer** [comment]
Yes, after we have officially published 3.0.0 of the node modules. They are still @next not @latest.

**Comment by dbaeumer** [comment]
@aeschli adopted them to 3.0.2-beta-5 which is the same than 3.0.3 published today.

**Comment by dbaeumer** [comment]
This has happened in the meantime for most of our server.
