### ISSUE TITLE
No clear way to make a response handler for any response such as "textDocument/codeAction"

### ISSUE THREAD

**Issue by RobbyCBennett** [microsoft/vscode-languageserver-node#1361]
The methods `LanguageClient.onRequest` and `LanguageClient.onNotification` both are available to get incoming requests & notifications. However, I don't know how to make a response handler because there is no `LanguageClient.onResponse` method.

The goal is to get the `params` object from a response, which may or may not be change by a response handler, then pass it along to the client.

I've tried `LanguageClientOptions.middleware`, but that seems to be for intercepting outgoing requests & notifications as well, but with more limitations compared to `LanguageClient.onRequest` and `LanguageClient.onNotification`.

**Comment by dbaeumer** [comment]
`LanguageClient.onRequest` and `LanguageClient.onNotification` is for custom request and notification send from the server to the client. 

Standard LSP message in both direction can be intercepted / manipulated by the middleware only. Can you please explain wha you want to achieve and why you can't do it in the middleware?

**Comment by RobbyCBennett** [comment]
What I want to achieve:
To provide a solution [another issue](https://github.com/microsoft/vscode/issues/197261) for my extension, I'm trying to receive the response of a "textDocument/codeAction" request so that I can make them more accessible. I want to take all code actions that the server sends for an area and add them to the right-click context menu. Then, I'll pass them along from my middleware to the languageClient.

Why I can't do it with middleware:
I don't see how to get the response with middleware. Ideally, I would get the full response `result`, but I would be fine with the contents separated out into middleware function parameters. However, I can't get the response result at all. The middleware seems to only be for outgoing messages. There is the `interface GeneralMiddleware` that has the methods `sendRequest` and `sendNotification` but it doesn't have `receiveResponse` (or `receiveNotification`.) There is the `interface CodeActionMiddleware` that has the methods `provideCodeActions` and `resolveCodeAction` but it doesn't have `receiveProvideCodeActions`.

**Comment by RobbyCBennett** [comment]
I made a mistake in my first comment. The `params` object is in a request, but I don't actually want that. I actually want the `result` that is in a response.

**Comment by RobbyCBennett** [comment]
Here are some examples of what I'm thinking that response middleware may look like.

```ts
interface GeneralMiddleware {
    sendRequest?<P, R>(this: void, type: string | MessageSignature, param: P | undefined, token: CancellationToken | undefined, next: (type: string | MessageSignature, param?: P, token?: CancellationToken) => Promise<R>): Promise<R>;
    sendNotification?<R>(this: void, type: string | MessageSignature, next: (type: string | MessageSignature, params?: R) => Promise<void>, params: R): Promise<void>;
    
   // An idea for middleware for a general response
    receiveRequest?<R>(this: void, type: string | MessageSignature, next: (type: string | MessageSignature, result?: R) => Promise<void>, result: R): Promise<void>;
}

export interface CodeActionMiddleware {
    provideCodeActions?: (this: void, document: TextDocument, range: VRange, context: VCodeActionContext, token: CancellationToken, next: ProvideCodeActionsSignature) => ProviderResult<(VCommand | VCodeAction)[]>;
    resolveCodeAction?: (this: void, item: VCodeAction, token: CancellationToken, next: ResolveCodeActionSignature) => ProviderResult<VCodeAction>;

    // An idea for middleware for a response to "textDocument/provideCodeActions"
    receiveProvideCodeActions?: (this: void, result: (VCommand | VCodeAction)[], next: ReceiveProvideCodeActionSignature) => ProviderResult<VCodeAction>;
}
```

**Comment by dbaeumer** [comment]
Get to the response of a request sent to the server simply await the result of the `next()` handler. See https://github.com/microsoft/vscode-languageserver-node/blob/f8a54a2b35e9a2781c711a145be8acc44ca6902f/client/src/common/codeAction.ts#L28

The values returned are in terms of VS Code API objects.

**Comment by RobbyCBennett** [comment]
Thank you very much.
