### ISSUE TITLE
Question: Minimum requirements for LSP server to support semantic highlighting

### ISSUE THREAD

**Issue by dibyendumajumdar** [microsoft/vscode-languageserver-node#1362]
Hi, 

I am writing a LSP server for a language, and my initial goal is to support semantic highlighting. The only capability I provide is semanticTokenProvider. But I find that after "initialize" request, no further requests come from VSCode - apart from notifications such as "initialized" or "shutdown". My guess is that LSP server needs to implement some other capabilities? But I can't tell from the docs what the pre-requisites are for semanticTokenProvider. Grateful for any help figuring this out.

Thanks and Regards
Dibyendu

**Comment by dbaeumer** [comment]
@dibyendumajumdar on the client side you need to let VS Code know for which documents you want to receive that request. Usually you do that by specifying a document selector with the client options. See https://github.com/microsoft/vscode-languageserver-node/blob/f8a54a2b35e9a2781c711a145be8acc44ca6902f/client/src/common/client.ts#L356

**Comment by dibyendumajumdar** [comment]
Hi @dbaeumer  Thank you - I had it but the language id was incorrect; I now see the textDocument/semanticTokens/full request.
