### ISSUE TITLE
Rename is not called if server returns { defaultBehavior: true } in prepareRename

### ISSUE THREAD

**Issue by dibarbet** [microsoft/vscode-languageserver-node#1363]
VSCode Version: 1.84.1
VSCode Language server - 8.1.0

It appears as though if a server returns `{ defaultBehavior: true }` from `textDocument/prepareRename`, the rename dialog is shown but on accept, the server never gets a `textDocument/rename` request.  The dialog then closes with no changes made.
![prepare_rename_fail](https://github.com/microsoft/vscode-languageserver-node/assets/5749229/577299eb-59a4-42c3-aabe-98b0a9f4e8db)

Here's a repro with the vscode extension samples:
https://github.com/dibarbet/vscode-extension-samples/commit/81d9bc1e49c58e281476509baf8c77ca36c11d47

Everything works as expected if textDocument/prepareRename returns a range.  However the client does seem to advertise `prepareSupportDefaultBehavior`

**Comment by dbaeumer** [comment]
Looks like a bug in VS Code itself. I opened https://github.com/microsoft/vscode/issues/198423

**Comment by dbaeumer** [comment]
Bug got fixed in VS Code. Will close the issue.
