### ISSUE TITLE
LS Client does not send `workDoneProgress` token for formatting

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-languageserver-node#1368]
Server capabilities:
```
2023-11-17 14:25:51.522 [info] [Trace - 2:25:51 PM] Received response 'initialize - (0)' in 12646ms.
2023-11-17 14:25:51.522 [info] Result: {
    "capabilities": {
        "positionEncoding": "utf-16",
        "textDocumentSync": {
            "openClose": true,
            "change": 2,
            "willSave": false,
            "willSaveWaitUntil": false,
            "save": false
        },
        "documentFormattingProvider": {
            "workDoneProgress": true
        },
        "documentRangeFormattingProvider": {
            "workDoneProgress": true
        },
        "executeCommandProvider": {
            "commands": []
        },
        "workspace": {
            "workspaceFolders": {
                "supported": true,
                "changeNotifications": true
            },
            "fileOperations": {}
        }
    },
    "serverInfo": {
        "name": "black-server",
        "version": "v0.1.0"
    }
}


2023-11-17 14:25:51.523 [info] [Trace - 2:25:51 PM] Sending notification 'initialized'.
2023-11-17 14:25:51.523 [info] Params: {}

```

The formatting request does not contain a `workDoneProgress` token.

**Comment by dbaeumer** [comment]
VS Code has no general concept for reporting work done progress (e.g. the VS Code API doesn't have the concept of a progress monitor when running format). To stay with this UI design the LSP client doesn't setup a monitor by its own.

This is outlines in the LSP spec. See

> There is no specific client capability signaling whether a client will send a progress token per request. The reason for this is that this is in many clients not a static aspect and might even change for every request instance for the same request type. So the capability is signal on every request instance by the presence of a workDoneToken property.

> To avoid that clients set up a progress monitor user interface before sending a request but the server doesn’t actually report any progress a server needs to signal general work done progress reporting support in the corresponding server capability. For the above find references example a server would signal such a support by setting the referencesProvider property in the server capabilities as follows:

So a server setting the property is not forcing the client to setup a monitor. It is still up to the client to decide whether it sends a monitor or not.

**Comment by karthiknadig** [comment]
Got it.
