### ISSUE TITLE
Client compile error: Type 'TextDocumentSaveReason.Manual' is not assignable to type '1 | 2 | 3'.

### ISSUE THREAD

**Issue by leira** [Microsoft/vscode-languageserver-node#137]
On revision 8d4aa6d. Run `npm run compile` under client folder, got this error:

$ tsc -p ./src
src/codeConverter.ts(176,12): error TS2322: Type 'TextDocumentSaveReason.Manual' is not assignable to type '1 | 2 | 3'.
src/codeConverter.ts(178,12): error TS2322: Type 'TextDocumentSaveReason.AfterDelay' is not assignable to type '1 | 2 | 3'.
src/codeConverter.ts(180,12): error TS2322: Type 'TextDocumentSaveReason.FocusOut' is not assignable to type '1 | 2 | 3'.
src/codeConverter.ts(182,10): error TS2322: Type 'TextDocumentSaveReason.Manual' is not assignable to type '1 | 2 | 3'.

**Comment by dbaeumer** [comment]
Fixed in 3.0.2-beta-1 which will ship today.
