### ISSUE TITLE
`InlineCompletionContext.SelectedCompletionInfo.range` is a JavaScript Array at runtime (type mismatch)

### ISSUE THREAD

**Issue by ealcantara-gitlab** [microsoft/vscode-languageserver-node#1371]
The goal of this issue is to report a bug in the `vscode-languageserver-protocol` library. 

## What is the problem?

When implementing an `InlineCompletionRequest` handler, the completion context included with the request contains a range object that, at runtime, is not a `Range` type as defined in https://github.com/microsoft/vscode-languageserver-node/blob/28badd60c39311684c80d13b4d6607da6b181bfc/types/src/main.ts#L4268. 

Instead, the `range` property is an array with two `Position` objects at runtime. 

## How to reproduce the bug

This is a simplified version of a language-server setup to receive inline completion requests. You can see also see our full implementation [here](https://gitlab.com/gitlab-org/editor-extensions/gitlab-lsp/-/blob/main/src/common/message_handler.ts?ref_type=heads#L252) and [here](https://gitlab.com/gitlab-org/editor-extensions/gitlab-lsp/-/blob/main/src/common/connection.ts?ref_type=heads#L33).

```typescript
import { CompletionItem, Connection, InlineCompletionRequest } from 'vscode-languageserver';
import { createConnection, TextDocuments } from 'vscode-languageserver/node';
import { TextDocument } from 'vscode-languageserver-textdocument';

const connection = createConnection(ProposedFeatures.all);
const documents: TextDocuments<TextDocument> = new TextDocuments(TextDocument);

connection.onRequest(InlineCompletionRequest.type, async (
    params: InlineCompletionParams,
    token: CancellationToken,
  ): Promise<InlineCompletionList> => {
   console.log(params.context.selectedCompletionInfo?.range);
});

documents.listen(connection);
connection.listen();
```

## What is the expected behavior 

The `range` should contain a runtime object that matches its type definition. 

## In which platform is the language server running?

Node.js

## What library versions am I using?

- "vscode-languageserver": "^9.0.1",
- "vscode-languageserver-protocol": "^3.17.5",
- "vscode-languageserver-textdocument": "^1.0.11"

**Comment by dbaeumer** [comment]
Fixed.

**Comment by ealcantara-gitlab** [comment]
Thanks for the quick fix @dbaeumer!
