### ISSUE TITLE
onDefinition handler is not called when onHover handler is

### ISSUE THREAD

**Issue by LordOfDragons** [microsoft/vscode-languageserver-node#1383]
I'm writing a language server. I've got so far setting up symbols, context (range) determination and hovering working. The definition provider is basically also working but there is a strange problem breaking things.

First the relevant code:

- onHover: https://github.com/LordOfDragons/vscode-langext-dragonscript/blob/7018805eefff777117219d9c73879b0970d13cb2/server/src/server.ts#L331
- onDefinition: https://github.com/LordOfDragons/vscode-langext-dragonscript/blob/7018805eefff777117219d9c73879b0970d13cb2/server/src/server.ts#L378C12-L378C24

And here the screenshot images referenced below:
![vscode_lang_server_onDefinition](https://github.com/microsoft/vscode-languageserver-node/assets/310073/bd1c1a6e-d5b5-4420-94d2-ce295ad39011)

Image (1) is the test code the language server is applied to.
Image (2) is onHover called for the toInt() function.
Image (3) is onHover called for the ++ operator.
Image (4) is onDefinition called for the toInt() function.
Image (5) is onDefinition **not** called for the ++ operator.

The bug is thus image (5). For toInt() function both onHover and onDefinition are called but for the ++ operator only onHover is called and onDefinition is never called. The range is correct since onHover is called for ++. Why does the VSCode Node based language server not call onDefinition for some ranges onHover is called for and not others? Is a different logic used for calling onHover and onDefinition?

**Comment by dbaeumer** [comment]
@jrieken although LSP I think this is the default behavior in VS Code. I assume we only call on Definition only on word and not on `++` operator. Is this correct?

**Comment by jrieken** [comment]
Wes

**Comment by LordOfDragons** [comment]
Hm... that's kinda annoying since overloading operators is a common practise in various languages.

**Comment by LordOfDragons** [comment]
@jrieken  Any plans on changing this in the future?

**Comment by dbaeumer** [comment]
@LordOfDragons all I can recommend is to open an issue against VS Code since there is little I can do in the library to fix this.

**Comment by dbaeumer** [comment]
I will close the issue since there is nothing I can do without having this fixed in VS Code.
