### ISSUE TITLE
docker: for builds

### ISSUE THREAD

**Issue by mbana** [Microsoft/vscode-languageserver-node#139]
i have `Dockerfile` that builds all the projects in a container. if you're wanting to include it in the official build ci, i can go ahead and clean it up and make it ready for general use.

might help to reduce compiler errors that intermittently show up. the only limitation that i can think of; the build will run on linux, unless MS have a dev. image that runs in Docker?

**Comment by dbaeumer** [comment]
@mbana we use travis to build in docker on checkin. Locally we build using the tsc compiler. Did you experience any problems with this. For me using docker locally to compile is a little bit an overkill since the tsc setup is easy with npm.

**Comment by mbana** [comment]
i was thinking of having something akin to a pre-commit hook that would compile and push, iff, it didn't err.

ps. w.r.t to WebSockets,

if you don't mind could you feedback your thoughts about http://azure.bana.io/monaco-go/. it's using [`go-langserver`](https://github.com/sourcegraph/go-langserver) on the backend side.

i'd love for some of the patches that i have in my branch to be merged upstream.

are you still busy?

**Comment by dbaeumer** [comment]
As said we use travis for builds and they even run when you create a branch. I will close this since I don't see big advantage of supporting docker locally.
