### ISSUE TITLE
BUG: update `yarn global` syntax for modern yarn berry support

### ISSUE THREAD

**Issue by yuriy-yarosh** [microsoft/vscode-languageserver-node#1393]
`vscode-eslint` extension is incompat with yarn3 yarn4 PnP due to `yarn glabal` command deprecation [over here](https://github.com/microsoft/vscode-languageserver-node/blob/main/server/src/node/files.ts#L196).

I'm getting constantly out of VSCode
![зображення](https://github.com/microsoft/vscode-languageserver-node/assets/6811933/46567150-ec91-4c57-8e1f-d9d32e52e010)

This should be updated to the relevant `dlx` changes, if possible, or refactored completely.

**Comment by dbaeumer** [comment]
Actually `resolveGlobalYarnPath` is deprecated for that reason since things depend on the the package manager used and the corresponding version used and the purpose of this library is not to support all these variation. Clients of the library need to deal with this themselves.
