### ISSUE TITLE
Unexpected `textDocument/didOpen` for notebook cell after workspace changed to untrusted

### ISSUE THREAD

**Issue by debonte** [microsoft/vscode-languageserver-node#1394]
**Repro steps:**
1. Open a workspace containing a Jupyter notebook with at least one Python cell.
2. Open the notebook.
3. Run `Workspaces: Manage Workspace Trust` via the command palette
4. Press the `Don't Trust` button

**Expected:** Notebook switches to restricted mode

**Actual:** Pylance crashes

This issue was originally reported as https://github.com/microsoft/pylance-release/issues/5194. Pylance hit a debug assert because it received messages about notebook cells before the corresponding `notebookDocument/didOpen` was received. In this case, those messages were `textDocument/didOpen` messages for each of the cells of the notebook.

`DidOpenTextDocumentFeature.register` loops over the open documents and sends `textDocument/didOpen` messages. But it skips any for which `this._client.hasDedicatedTextSynchronizationFeature(textDocument)` returns true. Normally this call would return true for notebook cells (because `NotebookDocumentSyncFeature.handles` would return true), but in this scenario it does not.

There are two ways that `NotebookDocumentSyncFeature.handles` could return true, and they both fail:

```typescript
if (this.dedicatedChannel !== undefined && vscode.languages.match(this.dedicatedChannel, textDocument) > 0) {
	return true;
}
```
The code above doesn't return true because within `vscode.languages.match` the `notebook` property on the object returned by `getDocumentData` is `undefined`. And therefore the document can't match our notebook selector of `{ notebookType: '*', language: 'python' }`.

```typescript
for (const provider of this.registrations.values()) {
	if (provider.handles(textDocument)) {
		return true;
	}
}
```
And this code doesn't return true because `this.registrations` hasn't been initialized yet, since `NotebookDocumentSyncFeature.register` hasn't been called yet.

That's as far as I got debugging this.

**Comment by dbaeumer** [comment]
@jrieken FYI since `getDocumentData` is a ext host implementation method. Will continue investigating and will ping if there is something we need to do in the ext host implementation

**Comment by debonte** [comment]
> How is the Python extension configured to handle untrusted workspaces (e.g. what is the capabilities entry in its package.json file)?

```json
       "untrustedWorkspaces": {
            "supported": "limited",
            "description": "Only Partial IntelliSense with Pylance is supported. Cannot execute Python with untrusted files."
        },
```

From https://github.com/microsoft/vscode-python/blob/main/package.json#L10

**Comment by dbaeumer** [comment]
I was able to reproduce this even in a non workspace trust scenario. The underlying reason is with the way matching works for notebook cell documents. I opened https://github.com/microsoft/vscode/issues/202163. I will look into a work around in the LSP libs since this might not be easy to fix in VS Code itself.

**Comment by dbaeumer** [comment]
@debonte there is some problem with the matching of the document selector however I couldn't actually make the Python server crash. Enclosed a screen cast of what I tried. Can you please send me a cast showing the actual crash and the corresponding language server trace.

![cast](https://github.com/microsoft/vscode-languageserver-node/assets/1931590/c771bad9-3d69-4c7e-9817-a270526067c7)

**Comment by debonte** [comment]
https://github.com/microsoft/vscode-languageserver-node/assets/12820898/cf97b0c4-8cad-4110-8bbd-56e89b4826d1

[PylanceServerTrace.txt](https://github.com/microsoft/vscode-languageserver-node/files/13895341/PylanceServerTrace.txt)

This is using:

- VS Code: 1.86.0-insider
- Python: 2023.25.10101826
- Pylance: 2023.12.103
- Jupyter: 2024.1.2024011001

I reduced my settings to just the following and it still repros for me:
```json
{
    "python.trace.server": "verbose",
    "python.analysis.logLevel": "Error",
}
```

**Comment by dbaeumer** [comment]
That scenario is caused by https://github.com/microsoft/vscode/issues/202232 which I can't work around.
