### ISSUE TITLE
connection.languages.inlineCompletion.on not work

### ISSUE THREAD

**Issue by cposture** [microsoft/vscode-languageserver-node#1396]
Based on https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-sample, I want to implement inlineCompletion capability. I made a few modifications to the project:

server.ts，first tell the client that this server supports code completion，then connection.languages.inlineCompletion.on
```ts
const result: InitializeResult = {
capabilities: {
	textDocumentSync: TextDocumentSyncKind.Incremental,
	// Tell the client that this server supports code completion.
	inlineCompletionProvider: {}
}
};

connection.languages.inlineCompletion.on((_params) => {
	return [
		InlineCompletionItem.create('text inline', 'te', Range.create(1,2,3,4))
	];
});
```

I created a new test.txt for debugging and entered "te", but nothing happened, inlinecompletion on function not trigger.I don't know how to locate this problem

thanks~

**Comment by cposture** [comment]
@c-claeys @dbaeumer

**Comment by dbaeumer** [comment]
Inline completions are currently proposed feature so you need to enable it on the client using `client.registerProposedFeatures();`  and on the server using `const connection = createConnection(ProposedFeatures.all);`
