### ISSUE TITLE
Ignoring Server Process Status of 0

### ISSUE THREAD

**Issue by rroessler** [microsoft/vscode-languageserver-node#1403]
In [capturing any server process exit](https://github.com/microsoft/vscode-languageserver-node/commit/c6817d36ffbc9efb17330b19e5e73a2caaa197d9), this declares exit successes of 0 to be shown as an error in output channels. The following is seen regardless of `trace.server` being set to `off`. Should this be changed for emitting an information message instead of an error message for successful exit codes?

**Comment by dbaeumer** [comment]
Yes, that should better be an information message. PR welcome :-)

**Comment by dbaeumer** [comment]
Fix by above PR
