### ISSUE TITLE
problem with priority of onCompletion items

### ISSUE THREAD

**Issue by LordOfDragons** [microsoft/vscode-languageserver-node#1410]
I want to mark certain entries in my completion result as best results, for example because the match the object type required at this code location. I could not find a way to add priority to the completion results.

I tried ordering the returned list but the ordering is ignored.

I then noticed the Java Language Server to place a "star" unicode in front of best results. I can add the star unicode to the text but this does not seem to have an effect so something else.

I then tried altering the filterText value of each entry to contain an artificial value like "a:xxx", "b:yyy" and so forth, hence prefixing with something forcing a sort. This seems to work if the completion list is shown with no filtered elements. Once I type and thus elements are filtered from the completion list this filterText seems to be ignored and the result are again alphabetically sorted.

How can completion results be priorized using LSP?

**Comment by dbaeumer** [comment]
The `sortText` property should do the trick. https://github.com/microsoft/vscode-languageserver-node/blob/2d33852e06ff9f180abd528be464f02b9bbd3079/types/src/main.ts#L2321

**Comment by LordOfDragons** [comment]
Sorry, typo in my description. I tried using the "sortText" (not "filterText") and it didn't work.
