### ISSUE TITLE
Support for Generators using LSP

### ISSUE THREAD

**Issue by H4ad** [microsoft/vscode-languageserver-node#1411]
I have a PR opened to improve the json format extension for VS Code: https://github.com/microsoft/node-jsonc-parser/pull/82 that uses generators to avoid creating a list twice at https://github.com/microsoft/vscode-json-languageservice/blob/5692bed6db771d0f8985f89a9ecd9e3bc96cbc00/src/utils/format.ts#L18-L20

I wonder if it is possible to support returning the `Generator Function` directly from the LSP, in this way, we can reduce the amount of memory needed to make edits in larger files.

In this case, the amount of memory needed to format the `JSON` file will be reduced to `471MB` from `2.2GB` (which is the amount of memory needed today).

I think this feature can be similar to `stream` interface/feature that vscode already have, but maybe we can expose that feature using `Generators` in this way, is much easier to developers to integrate.

**Comment by dbaeumer** [comment]
The support is simple in LSP since it already has support for streaming (see https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#partialResults)

Add something like this to VS Code is hard since its API doesn't support streaming right now. See https://github.com/microsoft/vscode/issues/105870 for the corresponding issue in VS Code.

**Comment by H4ad** [comment]
Oh, I think now I understand, what you are saying is we basically can add support on the LSP of the language itself to `PartialResults`, and if the IDE supports that feature, it will use it.

In this case, `vscode` didn't support yet.

Until a few days ago, I knew nothing about LSP, I recently discovered that this is a protocol and it is being used by many IDEs, not only VSCode, so that's why I initially thought I could ask to `vscode` to add support.

Took me a few days to understand your phrase (and I hope I understand it now).

Anyway, let me know if I understand something incorrectly, I will study more about LSP and see how I can add support to partial results at https://github.com/microsoft/vscode-json-languageservice.

**Comment by H4ad** [comment]
I probably understand something wrong, I found no example of usage of `PartialResults`, or no one ever tried to implement/add support for it, or I'm searching wrong, any thoughts?

**Comment by dbaeumer** [comment]
There is one request kind that support partial results even in VS Code and that is the new pull diagnostics model.

**Comment by dbaeumer** [comment]
This issue has been closed because it has not had recent activity. Please ping if you want to continue working on this.

Happy Coding!
