### ISSUE TITLE
Progress percentage should be an uint according to the spec

### ISSUE THREAD

**Issue by w0rm** [microsoft/vscode-languageserver-node#1412]
Hi folks!

@absynce and I are trying to integrate `elm-language-server` that is based on `vscode-languageserver` with [Zed](https://github.com/zed-industries/zed) and running into the following error:

```
[2024-01-25T20:44:07Z ERROR lsp] error deserializing $/progress request: Error("data did not match any variant of untagged enum ProgressParamsValue", line: 1, column: 127), message: "{\"token\":\"36abce40-63b2-4fa1-8464-030400636f26\",\"value\":{\"kind\":\"report\",\"percentage\":100.00000000000155,\"message\":\"Indexing\"}}"
```

According to [the lsp specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workDoneProgress) the `percentage` should be a uinteger. However, the actual value is a float. This works just fine if the receiving end is not strict about this, but the rust lsp implementation [assumes `percentage` to be a u32](https://docs.rs/lsp-types/latest/lsp_types/struct.WorkDoneProgressReport.html).

Would you be open for a PR that rounds the reported percentage in https://github.com/microsoft/vscode-languageserver-node/blob/c0982bf544bab9600df223146dd75c93c9004dc3/server/src/common/progress.ts#L57 ?

**Comment by dbaeumer** [comment]
I am open for a PR.
