### ISSUE TITLE
Fix ProtocolConverter#asWorkspaceEdit to correctly support workspace edits with snippets

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-languageserver-node#1414]
VS Code version 1.86 support new API to correctly implement the Snippet suppport. Here is what needs to be done:

- update grade to VS Code version 1.86 by adjusting the `client\package.json`. Things that need to be update are the `engine` property and the corresponding `devDependencies/@types/vscode`
- in the client folder run `npm run updateVSCodeVersion`

Change the code in the protocol converter here as follows: https://github.com/microsoft/vscode-languageserver-node/blob/2d33852e06ff9f180abd528be464f02b9bbd3079/client/src/common/protocolConverter.ts#L1088

- instead of calling the `replace` on the result, construct VS Code text edits yourself, correctly converting LSP `SnippetTextEdit` into VS Code `SnippetTextEdit`.
- if the edit as an annotation convert it as well
- mained the converted edits in  an array [TextEdit | SnippetTextEdit, WorkspaceEditEntryMetadata | undefined][]

When all edits are converted call `result.set` with this signature: https://github.com/microsoft/vscode/blob/56ed836ea9bae1602cf83bc286c7480b1370a99f/src/vscode-dts/vscode.d.ts#L3975

**Comment by dbaeumer** [comment]
@MariaSolOs  do you want to give that a try?

**Comment by MariaSolOs** [comment]
> @MariaSolOs do you want to give that a try?

Yes :)
