### ISSUE TITLE
New named structs in metamodel should maybe not be "proposed"?

### ISSUE THREAD

**Issue by michaelpj** [microsoft/vscode-languageserver-node#1416]
I had been defaulting to omitting items with `proposed: true`, since they're not actually usable yet (I assume).

However, recent versions of the metamodel have replaced various anonymous structures with named types. This is great... except the new types are marked as "proposed", which is a bit odd, since they're structurally the same. My naive approach has me omitting those types, which obviously doesn't work.

I think maybe they should just not be "proposed", since they don't actually change the protocol at all and are just a different way of defining the types. 

I can make a PR for this if it's helpful.

**Comment by dbaeumer** [comment]
I am actually OK with removing the proposed on the new introduced names. They don't change the semantic of the protocol.

@karthiknadig any objection?

**Comment by karthiknadig** [comment]
We can remove those. It does not impact he python/rust/c# code generators.

**Comment by dbaeumer** [comment]
@michaelpj PR welcome.

**Comment by michaelpj** [comment]
Does this mean you're not going to use anonymous structs ever again? Can I also delete those types from the metamodel?

**Comment by dbaeumer** [comment]
> Does this mean you're not going to use anonymous structs ever again?

We try to avoid them.

You shouldn't edit the meta model. I will re-generate it when I prepare a new release

**Comment by michaelpj** [comment]
Sorry, I meant "can I remove the `StructureLiteral` type from `metaModel.schema.json`?".

**Comment by michaelpj** [comment]
Ah ignore me, there is precisely one use remaining. It _would_ be a significant improvement for consumers of the metamodel to do away with them entirely, but it sounds like that's not the plan.
