### ISSUE TITLE
Extend predefined semantic token types to include `label`

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode-languageserver-node#1422]
https://github.com/microsoft/vscode-languageserver-node/blob/main/types/src/main.ts#L3805
has the list of predefined semantic token types. That matches the spec https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/

We noticed the list omits `label` which is supported by vscode.
https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#standard-token-types-and-modifiers

Our extension uses the node client library. Am I understanding it correct that there is no way for us to adjust semantic token client-side capability to customize the SemanticTokensLegend and we should make changes to the types/src/main.ts (and spec change??)

**Comment by dbaeumer** [comment]
Different clients can have different token types. However to add it to the VS Code client you need to change the suggested code. For consistency we should also update the specification.

Are you willing to work on the corresponding PRs?
