### ISSUE TITLE
Expected sequence of events for an initialization failure

### ISSUE THREAD

**Issue by vinistock** [microsoft/vscode-languageserver-node#1428]
In the [specification entry for initialize](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialize), it mentions the expected error code and data in case initialization fails.

Based on my understanding, the server should return this if it fails to initialize

```typescript
{
  error: {
    code: 1,
    message: "Failed to initialize!",
    data: { retry: true }
  }
}
```

My question is what needs to happen after returning this response. Are servers expected to exit the process immediately after responding? Should they wait for `shutdown` and `exit` messages?

**Comment by dbaeumer** [comment]
It depends on the value of `retry`. If it is `true` the server should not exit and the client should resend the initialize request. If `false` things can get indeed tricky. I would propose that the server shouldn't exit and the client should send `shutdown` and `exit`

**Comment by vinistock** [comment]
> the client should resend the initialize request
> the client should send shutdown and exit

Do these already happen? Or do they need to be implemented in the client package?

**Comment by dbaeumer** [comment]
They need to be implemented in the client package as `vscode-languageclient` does.
