### ISSUE TITLE
Provide RequestType.create instead of constructor

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-languageserver-node#143]
- consistent with other types where we always have a Namespace
- easier to add a second constructor later

**Comment by dbaeumer** [comment]
I looked into this when adding the constructor but that lets you write something like

```ts
export class RequestType4<P1, P2, P3, P4, R, E, RO> extends AbstractMessageType {
	public static create<P1, P2, P3, P4, R, E, RO>(method: string): RequestType4<P1, P2, P3, P4, R, E, RO> {
		return new RequestType4<P1, P2, P3, P4, R, E, RO>(method);
	}
	private _?: [P1, P2, P3, P4, R, E, RO, _EM];
	constructor(method: string) {
		super(method, 4);
		this._ = undefined;
	}
}
```
```ts
let type = RequestType4.create('method');
```

with no type params and the compiler infers {} for all of them. Since this basically defeats the purpose of the types I didn't add this.  

No further action planned.
