### ISSUE TITLE
Missing `onSemanticTokens` method on `Connection`

### ISSUE THREAD

**Issue by TwitchBronBron** [microsoft/vscode-languageserver-node#1450]
The semantic tokens event registration seems to be missing on the `Connection` class. For most events, I can simply use `on` followed by the name of the event. (like `connection.onCodeAction`, `connection.onReferences`. However, for semantic tokens I have to manually register it. Not a huge deal, but it's a hinderance to discovery. 

```typescript
import { createConnection } from 'vscode-languageserver/node';

const connection = createConnection(ProposedFeatures.all);

//what we currently have to do
connection.onRequest(SemanticTokensRequest.method, ()=> {
    //handle the request
});

//what we should be able to do
connection.onSemanticTokens(() => {
    //handle the request
});
```

**Comment by dbaeumer** [comment]
We put new requests into the language namespace.

See `connection.languages.semanticTokens` for the handlers you can register for semantic tokens.

**Comment by TwitchBronBron** [comment]
Ah. Totally didn't see that. Makes sense. Thanks!
