### ISSUE TITLE
Semantic tokens that are not in ascending order will not be highlighted

### ISSUE THREAD

**Issue by imbant** [microsoft/vscode-languageserver-node#1451]
I pushed a minimum reproducible [demo](https://github.com/imbant/semantic_highlight_demo)

When the order of semantic tokens provided by the language server is inconsistent with the order in the document character stream, non-ascending semantic tokens will not be highlighted. This will not be the case when using language clients based on the VS Code API, and highlighting will not be affected by token order.

## Phenomenon:

![image](https://github.com/imbant/semantic_highlight_demo/assets/17983739/12c64792-0de6-441e-9d19-4ee7c6a30463)

The code for providing semantic tokens between the language server and the client is almost exactly the same.
![image](https://github.com/imbant/semantic_highlight_demo/assets/17983739/d1f42ad0-b5f7-4bf1-98fe-ce2e32a2dd00)

## doubt:

No requirement for the order of semantic tokens was found in the [LSP documentation](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/).
Is this a requirement for LSP? Or is it a bug in the `vscode-languageserver/node` npm package?

**Comment by dbaeumer** [comment]
I guess that this is a bug in the `SemanticsTokenBuilder` in the node npm package.

**Comment by imbant** [comment]
@dbaeumer Thanks for your reply.If you don't mind, I will try to locate and fix this issue on my branch next week.

**Comment by dbaeumer** [comment]
@imbant a PR is highly appreciated :-)

**Comment by imbant** [comment]
https://github.com/microsoft/vscode-languageserver-node/pull/1467

@dbaeumer  Hi. Sorry for late. It is indeed a bug in the `SemanticsTokenBuilder`, I hope this PR can help solve this problem.

I didn’t know which branch I should merge into, so I chose `main`. If you have any questions, please contact me.

**Comment by dbaeumer** [comment]
Main is the right branch. Will have a look at the PR next week.

**Comment by imbant** [comment]
I will close this issue since the PR has been merged
