### ISSUE TITLE
Document symbols in editor do not show after starting VSCode with file open

### ISSUE THREAD

**Issue by LordOfDragons** [microsoft/vscode-languageserver-node#1452]
First things first my language server provides document symbols properly and they work.

If I open an file after the VSCode is started the document symbols are shown in the panel.
If I edit the file the document symbols are updated in the panel.
If I close and immediately reopen the file the document symbols are shown in the panel.
The only thing that does not work is if I open VSCode with a file already open.

My language server has to do some preparation work (parsing a language package and the game engine script package) before it can parse the file and all files in the workspace. This takes a couple of seconds to complete. VSCode asks for document symbols during that time and correctly gets none since they are still calculated. At the time the document symbols are ready VSCode does not ask the language server anymore about them.

So the question is: How can this be fixed? Can the language server send document symbols as it sends diagnostic messages or is there another way to fix this? I would like to find a way to force the update from the language server without the user needing to do something manually.

**Comment by dbaeumer** [comment]
Since the request is async you can answer the request when your server is ready. VS Code is not blocked in that state.

**Comment by dbaeumer** [comment]
If you want to be nice your server can show progress if the initialization happens during the initialize request.

**Comment by LordOfDragons** [comment]
> If you want to be nice your server can show progress if the initialization happens during the initialize request.

How can I do this? I can only print to the console.

**Comment by LordOfDragons** [comment]
> Since the request is async you can answer the request when your server is ready. VS Code is not blocked in that state.

I tried getting this to work but it is not working because "connection.onDocumentSymbol" is not an async function so I can not "wait" inside it until parsing finished. How is one supposed to solve this?

**Comment by dbaeumer** [comment]
The handler you pass in can be an async function. Something like

connection.onDocumentSymbols(async (params) => { ... });

The connection will then await the result of the async function.

**Comment by dbaeumer** [comment]
For the progress you can enable this via a client options: https://github.com/microsoft/vscode-languageserver-node/blob/691fd5d3fabeed5ed8ff9c3608f2d306cb07717e/client/src/common/client.ts#L354

And then the server will receive a progress token in its initialize request like here: https://github.com/microsoft/vscode-languageserver-node/blob/691fd5d3fabeed5ed8ff9c3608f2d306cb07717e/testbed/server/src/server.ts#L107

**Comment by LordOfDragons** [comment]
How is this mapping to an "async/await" system?

**Comment by dbaeumer** [comment]
> How is this mapping to an "async/await" system?

For the handlers yes.

For the work done progress no. The partial result progress maps to async/await hover it is not supported in VS Code.
