### ISSUE TITLE
Two-part Hover info using `MarkupContent`

### ISSUE THREAD

**Issue by michal-kapala** [microsoft/vscode-languageserver-node#1456]
# Question
I'm aiming for a typical hover UI with colorized code element signature/type information and plain markdown docs at the bottom.

![hover info](https://github.com/microsoft/vscode-languageserver-node/assets/48450427/a92b9a92-04c1-488c-8099-d1271155f1c5)

I managed to implement a demo using `Hover.contents: MarkedString[]`:

```ts
export function getHover(analysis: CodeAnalysis, params: HoverParams): Hover {
    return {
        contents: [
            {language: "jitterbit", value: '(function) WriteToOperationLog(string message): string'},
            'Some `text` over here'
        ],
    };
}
```
As `MarkedString` is deprecated, how can I achieve similar behaviour using `MarkupContent`?

Is it even possible given `MarkupKind` currently only supports markdown and plaintext? I think #843 tried to answer that.

**Comment by dbaeumer** [comment]
See also https://github.com/microsoft/vscode-languageserver-node/blob/e1345cca06095d61d3c5c0ff961472d55cbcf798/types/src/main.ts#L2039
