### ISSUE TITLE
Language server is not started until a file is opened

### ISSUE THREAD

**Issue by LordOfDragons** [microsoft/vscode-languageserver-node#1457]
My language server works so far but it is only started if a file matching the file pattern is opened. This is a problem since the language server processes all matching files in the workspace directories. 

This means if a workspace is opened without an open file (or a file from another file type) the entire workspace is not parse nor processed. Hence the extension is never activated. I need to explicitly open a file for the workspace to be parse.

I'm using the default language server project as base that is linked from the official documentation.

How can I force the language server to be started either generally or if a workspace with matching files is opened?

**Comment by dbaeumer** [comment]
This is control by the activation of your extension. See https://code.visualstudio.com/api/references/activation-events on what the options are.
