### ISSUE TITLE
TextDocument method `lineAt` is missing

### ISSUE THREAD

**Issue by buehler** [Microsoft/vscode-languageserver-node#146]
Hey everyone!

Cool package! Thanks for pointing that out @ https://github.com/buehler/typescript-hero/issues/143. I hope my refactoring will run smoothly with those types.

Although, I'm missing a certain method on the `TextDocument` type. The `lineAt` method is not provided and it would be very convenient to have that method.

What are your thoughts about that?

Cheers
Chris

**Comment by dbaeumer** [comment]
@aeschli any plans to add this ?

**Comment by aeschli** [comment]
I didn't had any need for it so far, but I'm not opposed to it. @buehler Do you want to look into a PR?

**Comment by buehler** [comment]
Yea when I get the time, I'd probably implement this.

**Comment by rcjsuen** [comment]
If we added this we'd be introducing a new `TextLine` type to the language server that is not actually referenced or used by the protocol. Does this make sense?

**Comment by rcjsuen** [comment]
@buehler What are you expecting to be returned from this `lineAt` API? For it to behave exactly like VS Code and to return a structure similar/identical to `vscode.TextLine`? Given Microsoft/vscode#2560 I'm not sure we want to directly copy that the structure of `vscode.TextLine`.

**Comment by aeschli** [comment]
I'd rather avoid a new `TextLine` type.
With the new `TextDocument.getText(range) API added by @rcjsuen, it's now simpler to get the text content of a line.  `TextDocument.getText(Range.create(line, -1, line, Number.MAX_VALUE))`

**Comment by buehler** [comment]
Definitely. I think this could be closed by now..

**Comment by rcjsuen** [comment]
@aeschli Okay to close given the [comment above](https://github.com/Microsoft/vscode-languageserver-node/issues/146#issuecomment-356580077)?
