### ISSUE TITLE
Diagnostics pulling doesn't work for notebook cells

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-languageserver-node#1464]
I'm attempting to switch Pylance to use a pull method for diagnostics but I'm not getting `textDocument/diagnostic` messages for notebook cells. 

I believe that's because notebook changes aren't tracked here:
https://github.com/microsoft/vscode-languageserver-node/blob/8e625564b531da607859b8cb982abb7cdb2fbe2e/client/src/common/diagnostic.ts#L1024

And notebook opens aren't tracked here:
https://github.com/microsoft/vscode-languageserver-node/blob/8e625564b531da607859b8cb982abb7cdb2fbe2e/client/src/common/diagnostic.ts#L962

**Comment by dbaeumer** [comment]
Diagnostic pull is not available for notebook cells. It would require a special implementation in the notebook.ts file. It should work for the underlying document of the cell but that is not what you are asking for.

**Comment by rchiodo** [comment]
> It should work for the underlying document of the cell but that is not what you are asking for.

Sorry, I'm not sure what you mean. Are you saying there's an alternative method to get the requests? Or are you saying something still needs to be implemented?

**Comment by rchiodo** [comment]
Please take a look at my [PR](https://github.com/microsoft/vscode-languageserver-node/pull/1465). Thanks.
