### ISSUE TITLE
Diagnostic pulling could support multiple identifiers to allow for two stage diagnostic retrieval

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-languageserver-node#1466]
Right now pull diagnostics are registered with a single identifier per server:

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_pullDiagnostics

```typescript
export interface [DiagnosticOptions](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnosticOptions) extends [WorkDoneProgressOptions](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workDoneProgressOptions) {
	/**
	 * An optional identifier under which the diagnostics are
	 * managed by the client.
	 */
	identifier?: string;
```

This limits a server to having to handle all diagnostics through a single pull request. 

If multiple identifiers were supported, the server could split its diagnostic computations into different chunks, for example, syntax errors and semantic errors.

I'm proposing a new optional field for DiagnosticOptions:

```typescript
/**
 * Diagnostic options.
 *
 * @since 3.17.0
 */
export interface [DiagnosticOptions](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnosticOptions) extends [WorkDoneProgressOptions](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workDoneProgressOptions) {
	/**
	 * An optional identifier under which the diagnostics are
	 * managed by the client.
	 */
	identifier?: string;

	/**
	 * Whether the language has inter file dependencies meaning that
	 * editing code in one file can result in a different diagnostic
	 * set in another file. Inter file dependencies are common for
	 * most programming languages and typically uncommon for linters.
	 */
	interFileDependencies: boolean;

	/**
	 * The server provides support for workspace diagnostics as well.
	 */
	workspaceDiagnostics: boolean;


        /*
         * Additional identifiers that might be returned by the server
         */
       extraIdentifiers?: string[]
}
```

This could allow multiple diagnostic collections per server, which I think would be implemented here:
https://github.com/microsoft/vscode-languageserver-node/blob/8e625564b531da607859b8cb982abb7cdb2fbe2e/client/src/common/diagnostic.ts#L420-L421

**Comment by rchiodo** [comment]
I must be doing the registration wrong then. I'm returning it in my server capabilities:

```typescript
        if (this.client.hasPullDiagnosticsCapability) {
            result.capabilities.diagnosticProvider = {
                identifier: 'pylance',
                documentSelector: null,
                interFileDependencies: true,
                workspaceDiagnostics: initializationOptions.diagnosticMode === 'workspace',
            };
        }
```

**Comment by rchiodo** [comment]
I think this issue is a dupe of https://github.com/microsoft/language-server-protocol/issues/1088, which I believe is asking for the same thing?

**Comment by rchiodo** [comment]
Ah @heejaechang pointed out we could do it this way:
https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/languageServerBase.ts#L1415

The spec says that each [dynamic registration](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#client_registerCapability) has to be a different document selector though. 

Is that true?

**Comment by dbaeumer** [comment]
> I think this issue is a dupe of https://github.com/microsoft/language-server-protocol/issues/1088, which I believe is asking for the same thing?

That request was for the push diagnostics. It basically got added for pull with the identifier.

**Comment by rchiodo** [comment]
Thanks, sounds like it will work then.
