### ISSUE TITLE
codeConverter: Namespace 'vscode' has no exported member 'TextDocumentWillSaveEvent'

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode-languageserver-node#147]
While trying to use the `3.0.2-beta.2` version, I get this error:

```
node_modules/vscode-languageclient/lib/codeConverter.d.ts(12,46): error TS2694: Namespace 'vscode' has no exported member 'TextDocumentWillSaveEvent'.
```

To reproduce, here is my package.json config:

https://github.com/kumarharsh/graphql-for-vscode/blob/05d020e97808e2d608ab4dd927a7d70f199085f3/package.json

Just copy this file, and run `npm install`, then `npm run compile`.

**Comment by kumarharsh** [comment]
I see that this was being caused due to the `engine` property in my extension's package.json set to `^1.4.0`, which did not have `TextDocumentWillSaveEvent` member. After upgrading the engine to `1.6.0` this was fixed.

**Comment by dbaeumer** [comment]
Good to hear.
