### ISSUE TITLE
Incorrect handling of diagnostic pull request cancellation

### ISSUE THREAD

**Issue by Ilyat1337** [microsoft/vscode-languageserver-node#1471]
The current way diagnostic pull request cancellation is handled causes diagnostics to flicker in the editor. Diagnostics completely disappear for a second, and then reappear.

[Here is project to reproduce this bug](https://github.com/Ilyat1337/incorrect-diagnostics-cancellation-handling)

Demo:
![Demo](https://github.com/microsoft/vscode-languageserver-node/assets/48513533/12baac5a-e81b-47f7-8fe7-306fba74eabb)

Steps to reproduce:
- Clone repository and run `npm install`
- Start extension
- Open `client\testFixture`
- Quickly type a few characters and stop typing. Notice how diagnostics disappear and then appear again

Here are sequence of events that cause this issue:
1. The user starts typing, which causes the client to pull diagnostics.
https://github.com/microsoft/vscode-languageserver-node/blob/31fe8fea47fe4ae4e0494413826d33ee898a1ee0/client/src/common/diagnostic.ts#L467
2. The user continues typing, leading to the cancellation of the current request. The server detects cancellation and returns an error with the `RequestCancelled` error code. Client handles error (line 620).
https://github.com/microsoft/vscode-languageserver-node/blob/31fe8fea47fe4ae4e0494413826d33ee898a1ee0/client/src/common/diagnostic.ts#L610-L621
3. For some reason error handler returns `defaultValue`, which is an emty array in this case (line 2034).
https://github.com/microsoft/vscode-languageserver-node/blob/31fe8fea47fe4ae4e0494413826d33ee898a1ee0/client/src/common/client.ts#L2024-L2052
4. The client sets the empty array as the current diagnostics (line 496), causing the editor to update its UI and display zero errors. Afterward, the client retriggers the request (line 502). If it completes successfully, the editor displays the correct diagnostics some time after initially showing zero items.
https://github.com/microsoft/vscode-languageserver-node/blob/31fe8fea47fe4ae4e0494413826d33ee898a1ee0/client/src/common/diagnostic.ts#L494-L503

**Comment by dbaeumer** [comment]
Thanks for the create repository to reproduce the issue and the analysis of what is going on.

**Comment by dbaeumer** [comment]
Fixed via above PR.
