### ISSUE TITLE
Race condition in sendRequest in jsonrpc

### ISSUE THREAD

**Issue by 9at8** [microsoft/vscode-languageserver-node#1474]
https://github.com/microsoft/vscode-languageserver-node/blob/fc5ed68ccb69737a17b1c3c992b9831457b9dc4a/jsonrpc/src/common/connection.ts#L1449-L1450

In the code linked above, if a response is handled before we get a chance to set the responsePromise on the next line, we will never resolve the request.

The fix should be to set the responsePromise before we await on the message write.

**Comment by dbaeumer** [comment]
Thanks for the issue and the PR. Release vscode-jsonrpc@8.2.1. 

Let me know how it goes.
