### ISSUE TITLE
Can you provide a monaco-editor demo

### ISSUE THREAD

**Issue by FoSuCloud** [microsoft/vscode-languageserver-node#1476]
I saw that notebook has been included in the specification [specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/) 
I am happy to see that both python-lsp-server and vscode-languageserver-node support it. notebook, but I don’t know how to use it in monaco-editor. 
Can you provide a demo?

**Comment by dbaeumer** [comment]
To my knowledge the monaco editor has no support for notebooks. It would require the note book editor from VS Code which is different than the text editor.

**Comment by FoSuCloud** [comment]
> To my knowledge the monaco editor has no support for notebooks. It would require the note book editor from VS Code which is different than the text editor.

thanks
