### ISSUE TITLE
vscode-languageserver contains vscode-languageserver/lib/server/src

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-languageserver-node#149]
Version deployed in vscode 1.7:
8.0K	/extensions/html/server/node_modules/vscode-languageserver/bin
8.0K	/extensions/html/server/node_modules/vscode-languageserver/lib/utils
112K	/extensions/html/server/node_modules/vscode-languageserver/lib
136K	/extensions/html/server/node_modules/vscode-languageserver

in vscode 1.9:
4.0K	/extensions/html/server/node_modules/vscode-languageserver/bin
8.0K	/extensions/html/server/node_modules/vscode-languageserver/lib/server/src/utils
 72K	/extensions/html/server/node_modules/vscode-languageserver/lib/server/src
 72K	/extensions/html/server/node_modules/vscode-languageserver/lib/server
 44K	/extensions/html/server/node_modules/vscode-languageserver/lib/shared
 16K	/extensions/html/server/node_modules/vscode-languageserver/lib/utils
268K	/extensions/html/server/node_modules/vscode-languageserver/lib
288K	/extensions/html/server/node_modules/vscode-languageserver

Folder `vscode-languageserver/lib/server/src` looks suspicious.

FYI @dbaeumer

**Comment by dbaeumer** [comment]
Agree. Let me have a look.

**Comment by dbaeumer** [comment]
No idea how this happend. Fixed and published 3.0.4,
