### ISSUE TITLE
FileSystemWatcher and batching

### ISSUE THREAD

**Issue by cdietrich** [microsoft/vscode-languageserver-node#1503]
we are using FileSystemWatcher feature of lsp to track changes of deleted files server side.
in general this works perfectly fine.

but in some cases not all files arrive in the didChangeWatchedFiles event on the server side when files are deleted client side with a small pause.

(there is also no second batch)

how does the watcher/client batch the local delete events on the server?
can i debug the issue locally somehow

**Comment by cdietrich** [comment]
ok reading the code i have found `client/src/common/client.ts`
i wonder what happens when a new event is pushed between the start and end of the 
`sendNotification` await in the trigger
shoudl the trigger first replace the array and then call the sendNotification?

**Comment by EhabY** [comment]
I was able to re-produce this by copy-pasting (in the file system) with some pauses, it dropped one of the changes...

**Comment by cdietrich** [comment]
hmmm the patch is not 100% sufficient.
something the events in a single filesystemwatcher onDidDelete also misses the events even before they are batched

**Comment by cdietrich** [comment]
also can see this in a naive test attempt
https://github.com/cdietrich/fs-watcher-bug/blob/main/src/test/extension.test.ts

**Comment by dbaeumer** [comment]
@cdietrich good catch. That code should definitely be fixed. The bug got introduced when making notification sending async ;-).

I looked at your test case and that definitely looks like a problem in VS Code itself if you don't receive the 1000 delete events since you are not deleting the parent folder.

**Comment by dbaeumer** [comment]
I fixed the problem on the LSP client side. For the VS Code problem I would recommend to open an issue against VS Code. Could you please mention me on it so that I know about the outcome.

**Comment by dbaeumer** [comment]
@EhabY I added your test to the VS Code issue since it only depends on VS Code API.

I will close the issue since the LSP libs can't do something about failing VS Code API.
