### ISSUE TITLE
Question about location of SnippetString / TypedString

### ISSUE THREAD

**Issue by eriklieben** [Microsoft/vscode-languageserver-node#152]
Probably related to this change https://github.com/Microsoft/vscode-languageserver-node/commit/259a30ae215c1d163294f344a3d4223f01635c6d

I am a bit stuck/ lost. I have updated my packages from the beta packages to the regular ones, but are unable to get a reference to the SnippetString or TypedString object. 

old package.json
```
    "vscode-languageclient": "^3.0.1-alpha.13",
    "vscode-languageserver": "^3.0.1-alpha.13",
    "vscode-languageserver-types": "^3.0.1-alpha.9",
```
package.json now
```
    "vscode-languageclient": "^3.0.3",
    "vscode-languageserver": "^3.0.4",
    "vscode-languageserver-types": "^3.0.3",
```
When using any of the below lines:
```
import { TypedString, SnippetString } from 'vscode-languageclient';
import { TypedString, SnippetString } from 'vscode-languageserver';
import { TypedString, SnippetString } from 'vscode-languageserver-types';
```
All return not found / no exported members warnings.

In the client main.ts, the following works, but that doesn't work from within a language server.
```
import { SnippetString } from 'vscode';
let x = new SnippetString('foo=$0');
```

Will this be resolved as soon as v3.0.4 of the vscode-languageserver-types is released?
Or am I doing something wrong? / Is there some sample code available of how to do this correctly?

Thanks in Advance,

Erik

**Comment by dbaeumer** [comment]
Based on feedback we changed the way how snippet strings are treated in the protocol. This was breaking but ok from an alpha release to a final version. The underlying reason for this was to keep the protocol compatible to earlier versions.

Since snippet strings occur in completion items the CompletionItem interface now offers
```
export interface CompletionItem {
	/**
	 * The format of the insert text. The format applies to both the `insertText` property
	 * and the `newText` property of a provided `textEdit`.
	 */
	insertTextFormat?: InsertTextFormat;
}

/**
 * Defines whether the insert text in a completion item should be interpreted as
 * plain text or a snippet.
 */
export namespace InsertTextFormat {
	/**
	 * The primary text to be inserted is treated as a plain string.
	 */
	export const PlainText: 1 = 1;

	/**
	 * The primary text to be inserted is treated as a snippet.
	 *
	 * A snippet can define tab stops and placeholders with `$1`, `$2`
	 * and `${3:foo}`. `$0` defines the final tab stop, it defaults to
	 * the end of the snippet. Placeholders with equal identifiers are linked,
	 * that is typing in one will update others too.
	 *
	 * See also: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/common/snippet.md
	 */
	export const Snippet: 2 = 2;
}

export type InsertTextFormat = 1 | 2;
```

**Comment by octref** [comment]
@dbaeumer Can you reflect that in README? Because the following is no longer true:

> - New type SnippetText
> - CompletionItem.insertText can now also be a SnippetText.

**Comment by dbaeumer** [comment]
Good point. Done.
