### ISSUE TITLE
notebook event is broken. (re-ordering cells)

### ISSUE THREAD

**Issue by heejaechang** [microsoft/vscode-languageserver-node#1525]
repro steps
1. install vscode with the latest python extension prerelease and pylance extension prerelease (this uses `"vscode-languageclient": "^10.0.0-next.8" and "vscode-languageserver": "^10.0.0-next.6"`)
2. create notebook file and open it
3. put this in cells
```
[Cell 1]:
def foo():
    return 1

[Cell 2]:
x = foo()
```
4. move `cell 1` after `cell 2`

Expected Behavior:
`foo()` in `cell 2` shows an error

Actual Behavior:
nothing happens.

...

now, at the `vscode's extensions tab`, use `uninstall -> install specific version` to install `python extension version v2024.9.2024062703` and `pylance extension version v2024.6.100`. these uses `"vscode-languageclient": "^10.0.0-next.2", "vscode-languageserver": "^10.0.0-next.2"`.

retry the repro steps and confirm that things working as expected.

...

when I debug what I see is that, when cells are re-ordered, `vscode.workspace.OnDidChangeNotebookDocument` is raised as expected, but `lsp's OnDidChangeNotebookDocument` doesn't.

...

also, if new cell is added, it always added to the end of notebook, it never added into the middle of the notebook even if UI shows it inserted at the middle. you can repro it by adding `cell 3` between `cell 1` and `cell 2`. `start` index of `structure` will be `2` instead of `1`

**Comment by dbaeumer** [comment]
I broke this when trying to improve the event processing when executing notebooks with lots of cells. Will release a new next version.

**Comment by dbaeumer** [comment]
New versions: client@10.0.0-next.10 and server@10.0.0-next.8

Let me know how it goes.
