### ISSUE TITLE
Should AbstractMessageWriter dispose errorEmitter and closeEmitter?

### ISSUE THREAD

**Issue by nicksnyder** [Microsoft/vscode-languageserver-node#154]
I noticed that neither AbstractMessageWriter nor its subclasses call `dispose` on errorEmitter or closeEmitter. Should they?

If subclasses are responsible for disposing at the appropriate time, then the errorEmitter and closeEmitter properties should be protected and not private.

If it is not necessary to call dispose, then no change is necessary.

**Comment by dbaeumer** [comment]
Good point. Need to clarify if the `close` is the right place to call dispose.
