### ISSUE TITLE
ERR_SOCKET_CLOSED_BEFORE_CONNECTION could not start Language Server

### ISSUE THREAD

**Issue by tiltue** [microsoft/vscode-languageserver-node#1547]
When I try to start my Language Server in my VS Code extension, this error appears. I am using the recommended versions of the npm packages. Did someone experience anything similar? Any help is appreciated, thank you!

![image](https://github.com/user-attachments/assets/c3941956-7d73-4411-8c2a-38536494847f)

**Comment by dbaeumer** [comment]
This most of the time happens when the server crashes during startup. Is the server process running after that?
