### ISSUE TITLE
The server part of the library sends open and change event on open

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-languageserver-node#155]
The library should only send a open even on open notification. The current code does:

```ts
this._onDidOpen.fire({ document });
this._onDidChangeContent.fire(Object.freeze({ document }));
```

@aeschli any objection that I change this. It is IMO bogus and I have no idea why I did it this way.

**Comment by aeschli** [comment]
You talk about the events on TextDocuments, right?

My servers only listen to TextDocuments.onDidChangeContent to trigger a validation (they don't listen to onDidOpen).

```
documents.onDidChangeContent(change => {
	triggerValidation(change.document);
});
```
Would your change break me, or is there a onDidChangeContent guaranteed to follow after a document has opened?

It's also what the [sample](https://github.com/Microsoft/vscode-languageserver-node-example/blob/master/server/src/server.ts) does.

So I'd say it's a risky change.

**Comment by dbaeumer** [comment]
Yes, you would be affected. Good point with the sample. Then we leave it as is.
