### ISSUE TITLE
LanguageKind is marked as proposed and since 3.18, but is referenced from non-proposed TextDocumentItem.languageId

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode-languageserver-node#1565]
When generating classes from the spec, I usually filter out anything marked as `proposed` (since we don't use them and don't want to pollute the generated code with things that might still be changing). When trying to update the generator for 3.18, I found that `LanguageKind` has become an enum (to have some predefined values) and is marked as `proposed`, but it's referenced in non-proposed types (like `TextDocumentItem`).

I think the `@since` and `@proposed` really apply only to the `values` and not the whole `LanguageKind` definition, but that's not clear from the meta model (and more confusingly, a few individual values are marked as proposed and since 3.18 - but if the entire enum is, why do they need tagging specifically?).

(For now I think I'll just special case this, but it would be better to have clearer rules to avoid needing to add special cases if this kind of thing comes up again).

**Comment by dbaeumer** [comment]
Agree that LanguageKind shouldn't have been marked as proposed since it is an implementation detail.
