### ISSUE TITLE
Preserve newline formatting in MarkedString.fromPlainText()

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-languageserver-node#157]
I would like that single newlines in my plain text are preserved when converted to marked string in https://github.com/Microsoft/vscode-languageserver-node/blob/2f9d6055a77d8e9d31ecda03f8b1c54dd5ea0246/types/src/main.ts#L827

My use case is that I have a hover description (for a setting `window.title`) which uses some simple formatting with newlines and these newlines are not preserved in my hover.

See a video of what I mean

![kapture 2017-02-07 at 12 26 35](https://cloud.githubusercontent.com/assets/900690/22689322/ae860a6a-ed30-11e6-9f05-d3398deffc05.gif)

/cc @dbaeumer

**Comment by dbaeumer** [comment]
@aeschli I looked and we don't do anything special here in the client nor the server. Is this something the JSON server needs to fix?

**Comment by bpasero** [comment]
I am not sure this is still an issue after @aeschli fixed my setting keys with enum values.

**Comment by aeschli** [comment]
I fixed it in the JSON language service.
