### ISSUE TITLE
Client error 'Failed to determine file type' after undoing rename with Cmd+Z

### ISSUE THREAD

**Issue by sergeysavchuk** [microsoft/vscode-languageserver-node#1581]
1. Server registers feature of workspace/didRename, e.g. `didRename: { filters: [{ pattern: { glob: '**/*.clientrc', matches: 'file' }}] }`
2. Open a folder with  some .clientrc file
3. Rename the *.clientrc file
4. Undo the previous renaming with the hotkey: Cmd+Z 
5. The client reports error `Failed to determine file type for <path to the renamed *.clientrc file from step 3>`

OS version: macOs 15.1 (24B83)

It can be reproduced by using official lsp-sample with an additional server configuration, please see https://github.com/sergeysavchuk/vscode-extension-samples/tree/undo_renamed_file/lsp-sample  (branch: undo_renamed_file)

Log:
[Error - 11:56:30] Failed to determine file type for file:///Users/<userName>/data/src/test/vscode-rename/testNew.clientrc.
![Image](https://github.com/user-attachments/assets/a6a5a51c-9d5d-4ae2-b01d-594600cf3526)

**Comment by dbaeumer** [comment]
This shouldn't be an error. We should make this an info since we treat the file as a match to not loose anything.
