### ISSUE TITLE
client.onReady is never called

### ISSUE THREAD

**Issue by eriklieben** [Microsoft/vscode-languageserver-node#159]
I am trying to implement the following change https://github.com/Microsoft/vscode-languageserver-node#breaking-changes
```
let client = new LanguageClient(...);
client.onReady().then(() => {
  client.onNotification(...);
  client.sendRequest(...);
);
```
But when I do that, the onReady callback never get's called. When I try the same with a timeout around it, it works. I have the following test code:
```
  client.onReady().then(_ => {
    vscode.window.showInformationMessage('CLIENT READY');
  });
  vscode.window.showInformationMessage('YUP THIS IS EXECUTED');

  setTimeout(() => {
    vscode.window.showInformationMessage('timeout');
    client.onRequest('a', () => {
      vscode.window.showInformationMessage('on request a');
    });
  }, 1000);
```

languageclient/server versions installed
```
    "vscode-languageclient": "^3.0.3",
    "vscode-languageserver": "^3.0.4",
    "vscode-languageserver-types": "^3.0.3",
```

**Comment by dbaeumer** [comment]
@eriklieben I just retested this and it works for me. Please note that the server must return successfully from the initial `initialize` request. If the `initialize` request returns unsuccessful the onReady() promise ends in an error state (error handler fires). Depending on the server you might be able to enable tracing to see if the `initialize` request returned successful.

**Comment by dbaeumer** [comment]
Closing the issue.
