### ISSUE TITLE
Allow server to be started with the --inspect flag set

### ISSUE THREAD

**Issue by danieljholt** [Microsoft/vscode-languageserver-node#162]
When starting the server with the --inspect flag set rather than --debug flag set, the server fails to start and an error is thrown.  This means that a server cannot be debuged using the V8debugger/Chrome/Node2 debugger.

**Comment by dbaeumer** [comment]
@danieljholt what kind of error is thrown.

**Comment by danieljholt** [comment]
@dbaeumer when I set the debug configuration for the client within \src\extension.ts to 

let debugOptions = { execArgv: ["--nolazy" , "--inspect=9229"] };

And then start the client, the server refuses to start and a breakpoint is encountered within \node_modules\vscode-languageclient\lib\main.js at line 793  -  this.onReadyCallbacks.reject(error);

The error code is 9.

**Comment by dbaeumer** [comment]
Actually I am unsure to what degree the node embedded in Electron already support node2 debugger protocol. That might be the issue for the exception.

You can use a separate node executable as well using the runtime configuration (see example below): 

```
let serverOptions = {
	run: { module, transport: TransportKind.ipc },
	debug: { module, runtime: 'C:/Program Files/nodejs/node.exe', transport: TransportKind.ipc, options: debugOptions}
	};
```

**Comment by danieljholt** [comment]
Thanks for the help @dbaeumer, problem solved.  :)
