### ISSUE TITLE
Change isConnectionActive visibility

### ISSUE THREAD

**Issue by vavans** [Microsoft/vscode-languageserver-node#168]
Function `LanguageClient.isConnectionActive` is private.
It would be convenient to switch its visibility to public in order to test the languageclient availability.

**Comment by dbaeumer** [comment]
The API to use is: `client.onReady().then() since the client becomes ready async.`.

@vavans is this sufficient. There is the possibility as well to pass in an error handler on construction to react on errors on the connection.

**Comment by vavans** [comment]
I didn't see the error handlers, i'm going to try it, thanks !

**Comment by dbaeumer** [comment]
@vavans I will close assuming that the errors handlers did the trick for you.

**Comment by vavans** [comment]
Yes it did, thanks !
