### ISSUE TITLE
Multiple language servers

### ISSUE THREAD

**Issue by apazureck** [Microsoft/vscode-languageserver-node#169]
Hi,

The standard script delivered by the language server package does not support to change the output path. Is this intended?

Here my originally posted question in the vscode repo:
https://github.com/Microsoft/vscode/issues/16524

**Comment by dbaeumer** [comment]
You mean with the example. Right?

PRs welcome.

**Comment by dbaeumer** [comment]
I close this issue. I you want to use more than one server you can copy the folder layout of vscode-eslint which doesn't have install scripts and bundles from a root directory.
