### ISSUE TITLE
Support that a Diagnostic can define the owner of a Marker

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-languageserver-node#17]
The API currently doesn't expose the 'owner' of a generated marker in the API.

Should the `owner` of the marker and the `source` be the same, then the API doesn't have to be expanded.

**Comment by dbaeumer** [comment]
The LanguageClientOptions now expose a property diagnosticCollectionName.

**Comment by chrisdias** [comment]
@dbaeumer what would i use diagnosticCollectionName for in the jscs extension?

**Comment by egamma** [comment]
@chrisdias you can choose any identifer but you should document it in the extensions README. Knowing this identifer allows a task to create problems with the same identifier. This avoids that the problem markers from a task that validates all the project files using jscs duplicates problem markers created by the vscode-jscs linter.

For the vscode-tslint linter I will use `tslint` and then use `tslint` as the 'problem owner' in the tasks., see: https://github.com/Microsoft/vscode/blob/master/.vscode/tasks.json#L32
