### ISSUE TITLE
Undefined params for notification should be handled consistent.

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/vscode-languageserver-node#171]
Sometimes for undefined params `{}` is sent, like for `initialized`, and sometimes `undefined`, like for `exit`. It would be nice to be consistent about it that the server side can handle it: https://github.com/eclipse/lsp4j/issues/71.

**Comment by dbaeumer** [comment]
Agree. If a top level param is missing we should send null. We can't send undefined since this is not valid in other programming languages. If a property is missing in an object literal it is missing and in JS therefore undefined.

**Comment by dbaeumer** [comment]
For the initialize request the spec is as follows (mainly to allow further properties)

```ts
export interface InitializedParams {
}

/**
 * The intialized notification is send from the client to the
 * server after the client is fully initialized and the server
 * is allowed to send requests from the server to the client.
 */
export namespace InitializedNotification {
	export const type = new NotificationType<InitializedParams, void>('initialized');
}
```

So I would argue that it is OK to send {}.

@akosyakov ok to close

**Comment by dbaeumer** [comment]
Closing. Haven't received an answer. Please ping if you still thing action needs to be taken.
