### ISSUE TITLE
LanguageClientOptions.documentSelector doesn't support pattern

### ISSUE THREAD

**Issue by WebFreak001** [Microsoft/vscode-languageserver-node#175]
in my LanguageClientOptions I have
```js
documentSelector: [
    { language: "d", scheme: "file" },
    { pattern: "dub.{sdl,json}", scheme: "file" },
    { language: "diet", scheme: "file" }
],
```
and my server receives open, close, change and save notifications for D and diet files, but none of those for dub.json or dub.sdl files. A simple pattern like `test.txt` doesn't work either.

**Comment by dbaeumer** [comment]
It works if the pattern is "**/dub.{sdl,json}" however this will then match every file with this extension.

@jrieken any reason why I need to specify "**". How would someone then limit the pattern to the root of the workspace.

**Comment by jrieken** [comment]
@bpasero will know

**Comment by bpasero** [comment]
If the `**` is replaced with the full path of the workspace root (from http://code.visualstudio.com/docs/extensionAPI/vscode-api#_workspace), it should work, but haven't tried.

**Comment by WebFreak001** [comment]
Using `path.join` and `vscode.workspace.rootPath` or instead using `**` both worked, thanks
