### ISSUE TITLE
Documents out of sync? / Get content of current editor

### ISSUE THREAD

**Issue by apazureck** [Microsoft/vscode-languageserver-node#176]
Hi,

I am having trouble writing a completion provider in my language server. The completion provider only provides the `TextDocumentPositionParms` interface, so I thought I can get the text of the document by getting my synced documents. But if I change something (like putting in spaces) the document I get from my synced documents do not reflect that changes. Even after saving.

Is there another way to get the current document content or to sync them on any change? I have not found  anything. Or do I have to get each changed event on my textdocuments array?

**Server**
```typescript

let documents: TextDocuments = new TextDocuments();

...

connection.onInitialize((params): InitializeResult => {
	connection.console.info("Initializing XML language server");
	connection.console.log("params: " + JSON.stringify(params));

	Global.serverSettings = params.initializationOptions
	Global.workspaceRoot = params.rootPath;
	Global.schemastore = new XmlStorage(Global.serverSettings.storagepath, connection, LogLevel.None);

	return {
		capabilities: {
			// Tell the client that the server works in FULL text document sync mode
			textDocumentSync: documents.syncKind,
			// Tell the client that the server support code complete
			definitionProvider: false,
			completionProvider: {
				resolveProvider: false,
				triggerCharacters: ["<", ">", '"', "'", ".", "/"]
			},
			codeActionProvider: false
		}
	}
});

connection.onCompletion(async (params, token): Promise<CompletionList> => {
	connection.console.info("Completion providing request received");
	// Use completion list, as the return will be called before 
	let cl: CompletionList = {
		isIncomplete: true,
		items: []
	};

	let doc = documents.get(params.textDocument.uri);
...
}
```

**Client**
```typescript
let clientOptions: LanguageClientOptions = {
            // Register the server for xml decuments documents
            documentSelector: ['xml', 'xsd'],
            diagnosticCollectionName: "xmlDiagnostics",
            synchronize: {
                // Synchronize the setting section 'languageServerExample' to the server
                configurationSection: 'ui5ts',
                // Notify the server about file changes to '.clientrc files contain in the workspace
                fileEvents: workspace.createFileSystemWatcher("**/.clientrc")
            },
            initializationOptions: { storagepath: context.asAbsolutePath("schemastore") } as XmlInitOptions
        }
```

**Comment by dbaeumer** [comment]
The server is not allowed to change the document directly. As described in the protocol spec, document content that is open in the editor is owned by the editor. In the case of completions the server should return completion items which describe changes to be done to the document.

You can have a look for an example: http://code.visualstudio.com/docs/extensions/example-language-server

**Comment by apazureck** [comment]
That is not my problem. I don't want to change anything, I in fact just want to return my completion items. But I do not understand, why the changes I made are not reflected in the synced documents. As I understand the example the changes should be reflected in the TextDocuments class, which is fully synced by the language client.

For example:

I want to display the list of xml attributes. This works, it is between the tag and the element:

![grafik](https://cloud.githubusercontent.com/assets/14858596/23509191/4237a062-ff55-11e6-8fa8-e1e77e0bae06.png)

If I put a space at the end, I get the elements in my xml element content:

![grafik](https://cloud.githubusercontent.com/assets/14858596/23509218/5de9e4dc-ff55-11e6-9bb1-52dd2d91d003.png)

And here is what I get when in my language server:

![grafik](https://cloud.githubusercontent.com/assets/14858596/23509346/b2f9bd6c-ff55-11e6-9e2e-de7320417c79.png)

Note on the left side in the watch section the whitespace I added is missing, so my cursor is located on `\r` instead of `>`. If I add 10 more whitespaces, it does not change. The position is moving to the "right", but my added changes are not synced. Saving does not affect the text I get in my language server from my watched documents. Adding non-whitespace characters neither.

The EventParameters for the completion provider do not deliver the full text document, so I have to get it myself. Am I doing something wrong? I thought this would be the way to go.

Hope this makes my problem more clear. I can also sync my code and you can try it for yourself, if you like.

Putting a set of whitespaces in:

**Comment by dbaeumer** [comment]
I am sorry but I don't understand the problem you have. What do you mean by 

> the changes I made.
> If I put a space at the end

How do you make these changes. Where do you put the space. If you need to do a complex edit besides inserted the provided string / label via a CompletionItem then you can use the textEdit property.

**Comment by apazureck** [comment]
I have this Xml tag:

`<Page attributea="foo" attributeb="bar">`

I want to add another Attribute at the end, so I hit the space bar at the end of the xml element

`<Page attributea="foo" attributeb="bar" >` <- Space before the `>`

I press CTRL + SPACE to trigger the completion. I am still IN my xml element, so I want to get my attributes list.

The request goes to my language server.

I get the text from the open document, as described above from my TextDocument object.

I call `.getText()`

My language server does not get this string:
`<Page attributea="foo" attributeb="bar" >` <- Space before the `>`
it gets this string without the changes:
`<Page attributea="foo" attributeb="bar">` <- NO Space before the `>`

It seems the document is not synced to the language server, as I get the text without the changes.

**Comment by dbaeumer** [comment]
This works for me without a problem (none of our Language Servers would work otherwise). You can enable tracing to see if the correct messages are sent over the wire. To enable trace use the setting ${name}.trace.server": "verbose" where ${name} is the name you passed to the LanguageClient constructor in your VS Code extension. There should be something like
```
[Trace - 3:31:06 PM] Sending notification 'textDocument/didChange'.
```
in the trace. 

Is your repository public ?

**Comment by apazureck** [comment]
https://github.com/apazureck/openui5vscodeTypescriptTools/tree/master/ui5xmlserver

I am stuck with this problem for two days now and I don't know how to fix it. I assume I am doing something wrong, but I cannot figure out what it is. Thank you for your help.

**Comment by dbaeumer** [comment]
Have you enabled tracing ? Can you attach the trace here.

**Comment by apazureck** [comment]
Ok, I set it in my user settings:

`"XmlLangServer.trace.server": "verbose"`

I checked my output window on my Development Host, but there is only my stuff:

```
[Info  - 15:51:21] Initializing XML language server
params: {"processId":24784,"rootPath":"c:\\Dev\\LRA5\\LRA5-FrontEnd\\FrontEnd","rootUri":"file:///c%3A/Dev/LRA5/LRA5-FrontEnd/FrontEnd","capabilities":{"workspace":{"applyEdit":true,"didChangeConfiguration":{"dynamicRegistration":false},"didChangeWatchedFiles":{"dynamicRegistration":false},"symbol":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true}},"textDocument":{"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"completionItem":{"snippetSupport":true}},"hover":{"dynamicRegistration":true},"signatureHelp":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"definition":{"dynamicRegistration":true},"codeAction":{"dynamicRegistration":true},"codeLens":{"dynamicRegistration":true},"documentLink":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true}}},"initializationOptions":{"storagepath":"c:\\Dev\\ui5tsextension\\client\\schemastore"},"trace":"off"}
[Info  - 15:51:22] Creating Schema storage.
[Info  - 15:51:22] Found a valid schema. Renaming namespace abbrevation 'xsd to empty abbrevation to make it more readable for programmers.
[Info  - 15:51:22] Converted schema xsd
[Info  - 15:51:22] Found a valid schema. Renaming namespace abbrevation 'xsd to empty abbrevation to make it more readable for programmers.
...
```

No trace here. Do I have to check somewhere else? This is the only output console from my language server.

**Comment by dbaeumer** [comment]
Sorry. Name to lower case. So: `"xmllangserver.trace.server": "verbose"`

I clone the repository but I can't run it. When activating the extension it complains about missing i18n files.

**Comment by apazureck** [comment]
Sorry, hotfixed that. Check it out again.

**Comment by apazureck** [comment]
Ok, lowercase worked. Thank you. I'll have a look what might go wrong here.

**Comment by apazureck** [comment]
Here is my trace:

```
[Trace - 16:27:47] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Dev/LRA5/LRA5-FrontEnd/FrontEnd/test.xml",
        "version": 31
    },
    "contentChanges": [
        {
            "text": "<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\" ?>\r\n<mvc:View \r\n  xmlns=\"sap.m\" \r\n  controllerName=\"ifm.datalink.linerecorder.ams.frontend.controller.agents.Agents\">\r\n  <Page class=\"page\"  id=\"page\" >\r\n\r\n  </Page>"
        }
    ]
}


[Trace - 16:27:47] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///c%3A/Dev/LRA5/LRA5-FrontEnd/FrontEnd/test.xml",
    "diagnostics": []
}


[Trace - 16:27:47] Sending request 'textDocument/completion - (4)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Dev/LRA5/LRA5-FrontEnd/FrontEnd/test.xml"
    },
    "position": {
        "line": 4,
        "character": 21
    }
}


[Trace - 16:27:47] Received notification 'window/logMessage'.
Params: {
    "type": 3,
    "message": "Completion providing request received"
}


[Info  - 16:27:47] Completion providing request received
[Trace - 16:27:47] Received notification 'window/logMessage'.
Params: {
    "type": 1,
    "message": "Error when getting XML completion entries: {}"
}


[Error - 16:27:47] Error when getting XML completion entries: {}
[Trace - 16:27:47] Received response 'textDocument/completion - (4)' in 5ms.
Result: {
    "isIncomplete": true,
    "items": []
}
```
The change events are sent back and the file changes, too, but when I use the TextDocuments to get the whole text from the file it returns an empty string.

I created a new xml file and pasted some code in:

```xml
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<mvc:View 
  xmlns="sap.m" 
  controllerName="ifm.datalink.linerecorder.ams.frontend.controller.agents.Agents">
  <Page class="page"  id="page" >

  </Page>
```

Shouldn't there be some events when I get the file from my synced docs?

**Comment by dbaeumer** [comment]
Have you tried to debug this. Looking at the trace it send the correct version over to the server.

**Comment by dbaeumer** [comment]
I tried to debug this again but now the server complains in initialize about a missing schemastore.

**Comment by apazureck** [comment]
I am trying to reinstall all packages. Maybe it is due to an upgrade to ES6 or something else. I'll try to fix the issues you have starting the whole thing and post a message here, how the outcome was. Thank you for your help so far.

**Comment by apazureck** [comment]
Ok, I just ran a few little tests. The Trace sais the document is in version 16:

```
[Trace - 22:21:41] Sending notification 'textDocument/didSave'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Dev/LRA5/LRA5-FrontEnd/FrontEnd/test.xml",
        "version": 16
    }
}
```

In the debugger, when I get it per documents.get(uri) I get version 1:

```
FullTextDocument {_uri: "file:///c%3A/Dev/LRA5/LRA5-FrontEnd/FrontEnd/test.…", _languageId: "xml", _version: 1 …}
_content:"<?xml version="1.0" encoding="utf-8" standalone="yes" ?>\r\n<mvc:View \r\n  xmlns="sap.m" \r\n  xmlns:core="sap.ui.core"\r\n  xmlns:l="sap.ui.layout" \r\n  xmlns:mvc="sap.ui.core.mvc" \r\n  xmlns:tnt="sap.tnt"\r\n  controllerName="ifm.datalink.linerecorder.ams.frontend.controller.agents.Agents">\r\n  <Page class="page" id="page">"
_languageId:"xml"
_lineOffsets:Array[9] [0, 58, 70 …]
_uri:"file:///c%3A/Dev/LRA5/LRA5-FrontEnd/FrontEnd/test.xml"
_version:1
```

It does not seem to get updated. But shouldn't my file watcher take care of this?

```typescript
let clientOptions: LanguageClientOptions = {
            // Register the server for xml decuments documents
            documentSelector: ['xml', 'xsd'],
            diagnosticCollectionName: "xmlDiagnostics",
            synchronize: {
                // Synchronize the setting section 'languageServerExample' to the server
                configurationSection: 'ui5ts',
                // Notify the server about file changes to '.clientrc files contain in the workspace
                fileEvents: workspace.createFileSystemWatcher("**/*.{xml,xsd}")
            },
            initializationOptions: { storagepath: context.asAbsolutePath("schemastore") } as XmlInitOptions
        }
```

The changes do not get sent to my language server documents. Do you have any idea why this can happen?

**Comment by apazureck** [comment]
Allright, it works! Thank you very much for your help!

I put my `documents.listen(connection)` call to the oninit function in my server.ts. I don't know why it does not connect there when it is in the "root level" of the script, as it did before, but for now it is good enough for me that it works :)

**Comment by dbaeumer** [comment]
This is very strange especially since all my code has the `documents.listen(connection)` call in the root of the script. I would still be interested to understand why this is failing.

**Comment by apazureck** [comment]
I'll try to fix the errors you got when you tried to start the language server. After that I'll put it back where it was and see, if they were causing this behavior. Maybe there was some sideeffect. The imports at the start of the file which load my completionhandler etc. are executed before the `documents.listen(connection)`. I'll post it here, if I find out something more.

**Comment by dbaeumer** [comment]
@apazureck thanks

**Comment by vladdu** [comment]
I have the same problem, and if I put `documents.listen(connection)` at the root, then I get the `connection.onDidOpenTextDocument` notification and its sibling, but not `documents.onDidChangeContent`. If I put the `listen` in the initialize callback, it is the other way around. I will try to debug, but thought that this might shed some light until then.

**Comment by dbaeumer** [comment]
@vladdu since you are able to reproduce this can you share your setup. I would be interested to understand why this fails for you. It doesn't for me.

**Comment by vladdu** [comment]
* clone the languageserver-node example
* in the server, remove comments around the `connection.onDidOpen/Close/Save` callbacks
* in the server add a console.log statement in `documents.onDidChangeContent`
* start the client and server and observe that only `onDidOpen/Close/Save` printouts are there
* move `documents.listenConnection` inside `onInitialize`, run again and observe that only the `documents.onDidChangeContent` printouts are there

**Comment by dbaeumer** [comment]
I tried this again with the LSP and this is not what I see:

![cast](https://user-images.githubusercontent.com/1931590/29668096-42290d86-88df-11e7-840a-7bf6152b102a.gif)


My server code looks like this:
```ts
/* --------------------------------------------------------------------------------------------
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * ------------------------------------------------------------------------------------------ */
'use strict';

import {
	IPCMessageReader, IPCMessageWriter,
	createConnection, IConnection, TextDocumentSyncKind,
	TextDocuments, TextDocument, Diagnostic, DiagnosticSeverity,
	InitializeParams, InitializeResult, TextDocumentPositionParams,
	CompletionItem, CompletionItemKind
} from 'vscode-languageserver';

// Create a connection for the server. The connection uses Node's IPC as a transport
let connection: IConnection = createConnection(new IPCMessageReader(process), new IPCMessageWriter(process));

// Create a simple text document manager. The text document manager
// supports full document sync only
let documents: TextDocuments = new TextDocuments();
// Make the text document manager listen on the connection
// for open, change and close text document events
documents.listen(connection);

// After the server has started the client sends an initialize request. The server receives
// in the passed params the rootPath of the workspace plus the client capabilities. 
let workspaceRoot: string;
connection.onInitialize((params): InitializeResult => {
	workspaceRoot = params.rootPath;
	return {
		capabilities: {
			// Tell the client that the server works in FULL text document sync mode
			textDocumentSync: documents.syncKind,
			// Tell the client that the server support code complete
			completionProvider: {
				resolveProvider: true
			}
		}
	}
});

// The content of a text document has changed. This event is emitted
// when the text document first opened or when its content has changed.
documents.onDidChangeContent((change) => {
	connection.console.log(`${change.document.uri} closed.`);
	validateTextDocument(change.document);
});

connection.onDidOpenTextDocument((params) => {
	connection.console.log(`${params.textDocument.uri} opened.`);
});

connection.onDidChangeTextDocument((params) => {
	connection.console.log(`${params.textDocument.uri} changed: ${JSON.stringify(params.contentChanges)}`);
});

connection.onDidCloseTextDocument((params) => {
	connection.console.log(`${params.textDocument.uri} closed.`);
});


// The settings interface describe the server relevant settings part
interface Settings {
	languageServerExample: ExampleSettings;
}

// These are the example settings we defined in the client's package.json
// file
interface ExampleSettings {
	maxNumberOfProblems: number;
}

// hold the maxNumberOfProblems setting
let maxNumberOfProblems: number;
// The settings have changed. Is send on server activation
// as well.
connection.onDidChangeConfiguration((change) => {
	let settings = <Settings>change.settings;
	maxNumberOfProblems = settings.languageServerExample.maxNumberOfProblems || 100;
	// Revalidate any open text documents
	documents.all().forEach(validateTextDocument);
});

function validateTextDocument(textDocument: TextDocument): void {
	let diagnostics: Diagnostic[] = [];
	let lines = textDocument.getText().split(/\r?\n/g);
	let problems = 0;
	for (var i = 0; i < lines.length && problems < maxNumberOfProblems; i++) {
		let line = lines[i];
		let index = line.indexOf('typescript');
		if (index >= 0) {
			problems++;
			diagnostics.push({
				severity: DiagnosticSeverity.Warning,
				range: {
					start: { line: i, character: index},
					end: { line: i, character: index + 10 }
				},
				message: `${line.substr(index, 10)} should be spelled TypeScript`,
				source: 'ex'
			});
		}
	}
	// Send the computed diagnostics to VSCode.
	connection.sendDiagnostics({ uri: textDocument.uri, diagnostics });
}

connection.onDidChangeWatchedFiles((change) => {
	// Monitored files have change in VSCode
	connection.console.log('We received an file change event');
});


// This handler provides the initial list of the completion items.
connection.onCompletion((textDocumentPosition: TextDocumentPositionParams): CompletionItem[] => {
	// The pass parameter contains the position of the text document in 
	// which code complete got requested. For the example we ignore this
	// info and always provide the same completion items.
	return [
		{
			label: 'TypeScript',
			kind: CompletionItemKind.Text,
			data: 1
		},
		{
			label: 'JavaScript',
			kind: CompletionItemKind.Text,
			data: 2
		}
	]
});

// This handler resolve additional information for the item selected in
// the completion list.
connection.onCompletionResolve((item: CompletionItem): CompletionItem => {
	if (item.data === 1) {
		item.detail = 'TypeScript details',
		item.documentation = 'TypeScript documentation'
	} else if (item.data === 2) {
		item.detail = 'JavaScript details',
		item.documentation = 'JavaScript documentation'
	}
	return item;
});

let t: Thenable<string>;

// Listen on the connection
connection.listen();
```

**Comment by dbaeumer** [comment]
OK. Now I know what the problem is:

The code after commenting out some code hooks a `connection.onDidChangeTextDocument` handler to the connection and hooks the TextDocuments manager on the connection which itself registes a onDidChangeTextDocument handler. The connection has now listener model. It has a single handler model (this is done due to the fact that for requests there must be a response and it would be unclear which response to take if you have more than one handler).

So either the TextDocuments manager or the connection.onDidChangeTextDocument wins depending on what is registered last.

**Comment by vladdu** [comment]
Great! So the solution will be to allow multiple handlers for notifications? 

I believe that for requests there should be an error or something if trying to register a handler when another one is already registered. If a replacement is needed, then one can always unregister the previous one first.

**Comment by dbaeumer** [comment]
To keep it consistent both should stay single handlers. I have no objection to throw something if already registered and to return a disposable to easily unregister. PR welcome :-)

**Comment by vladdu** [comment]
Then I think there should be a warning about that somewhere, and a recommendation about which one of these handlers to install. Maybe the document manager I use installs a handler behind the scenes. Maybe it doesn't, and then I have to do it myself.

**Comment by dbaeumer** [comment]
Agree on the documentation part as well.
