### ISSUE TITLE
NPE in protocolConverter.js

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-languageserver-node#18]
On the the language server have 'onHover' return a promise that resolves to null.
(return Promise.resolve(null))
-> on the client, exception as below

Note, works when returning 'undefined' instead
(Promise.resolve(void 0);)

Cannot read property 'contents' of undefined: TypeError: Cannot read property 'contents' of undefined
    at asHover (/home/martinae/workspaces/vscode/extensions/json/node_modules/vscode-languageclient/lib/protocolConverter.js:64:32)
    at process._tickCallback (node.js:369:9)

**Comment by hoovercj** [comment]
Great to see this fix, I just ran into the issue myself. How often do the NPM packages get updated?

**Comment by hoovercj** [comment]
Also, I see `is.nil` and `is.undefined` checks, but does this properly handle situations where the contents are an empty string?

It seems there is an uncaught exception with the message "Illegal argument" being thrown when `asHover` creates a new `code.Hover` with an empty string. I can't find the code for that constructor though to check. If the hover promise can resolve to a null or undefined object it seems reasonable that empty strings should also be allowed.
