### ISSUE TITLE
SocketMessageWriter/Reader should be exported

### ISSUE THREAD

**Issue by asiandrummer** [Microsoft/vscode-languageserver-node#186]
While working on an IntelliJ plugin for GraphQL language server, I noticed that `vscode-jsonrpc` package implements super helpful classes for doing IPC with sockets, but they weren't being exported. Is this intentional?

If not, fixed in #185.

**Comment by dbaeumer** [comment]
What is exported are the two method: `createClientPipeTransport` and `createServerPipeTransport`. Aren't these sufficient for you?

**Comment by asiandrummer** [comment]
@dbaeumer I haven't seen those methods! I think `createServerPipeTransport` does the trick for me with a few caveats, such as not being able to cleanly separate usages of reader/writer. Obviously that's a nitty stuff - I also think it would be a consistent way to export/import different IPC methods, just like how StreamMessageWriter is being exported.

Feel free to close if you disagree - I can work around with those factory methods.

**Comment by dbaeumer** [comment]
I exported the factory method since setting up the pipe transport itself is not easy. You can't simply instantiate the reader and write. But exporting them for more advantage users makes sense.
