### ISSUE TITLE
CompletionItem range

### ISSUE THREAD

**Issue by bmewburn** [Microsoft/vscode-languageserver-node#188]
Thanks for your work on this project. I don't see a CompletionItem range property. Are the options for now to use either the default word range and deprecated textEdit?
https://code.visualstudio.com/docs/extensionAPI/vscode-api#CompletionItem

**Comment by dbaeumer** [comment]
The protocol differs from the vscode API due to backwards compatibility. In the protocol you need to use the text edit if you want to specify a range. If you want to use a range with a snippet use `insertTextFormat`
