### ISSUE TITLE
Expose 'Save' event for documents

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode-languageserver-node#19]
The language server api doesn't currently expose a save event for documents, it only allows responding to document changes.

https://github.com/Microsoft/vscode/issues/2200

**Comment by egamma** [comment]
There also is a feature request to support a setting that linting only happens on save Microsoft/vscode-tslint#21. 

The issue is that when use lint rules for white space and indent, then the squiggles are nervous.

**Comment by daviwil** [comment]
Yep, would be nice if I could give my users the option of linting only when the file gets saved.  This would be a nice addition!

**Comment by dbaeumer** [comment]
Got implemented for version 2.x
