### ISSUE TITLE
Support new completion item kinds

### ISSUE THREAD

**Issue by WebFreak001** [Microsoft/vscode-languageserver-node#190]
https://code.visualstudio.com/updates/v1_11#_api-improvements
> We added these new completion item kinds: Constant, Struct, and EnumMember completing the existing Enum kind.

Would be nice to have

**Comment by dbaeumer** [comment]
Agree, but they need to go into the spec first and then we can update the implementation.

**Comment by rcjsuen** [comment]
Those three enums were added in 1b36842edf58dfe31f26a62cdf42005cd4b2b237 for #280.

@dbaeumer I think this can be closed?

**Comment by dbaeumer** [comment]
@rcjsuen correct. Thanks for reminding.
