### ISSUE TITLE
How many protocols are actually used by vscode to connect to the language server?

### ISSUE THREAD

**Issue by vczh** [Microsoft/vscode-languageserver-node#192]
I know it is basically jsonrpc, but when I dig into the code, I see it accepts requests via **nodeipc / socket / stdio / pipe**. If I want to use other languages to implement language servers, do I have to support all these ways?

**Comment by dbaeumer** [comment]
@vczh good question: the minimum bar is to support stdio since all programming language and tools have support for this. However stdio comes with the disadvantage that writing normal output to stdout interferes with the protocol. This is why I suggest that a server also implements socket files under Linux/Mac and name pipes under Windows.

**Comment by vczh** [comment]
@dbaeumer 

Thank you for your reply. Do you mean I have a chance to tell vscode which protocol is my favorite protocol, so that it is me who choose the protocol, not vscode? Or I have to tell vscode all supported protocols, and vscode will select one by priority?

**Comment by dbaeumer** [comment]
Neither nor. If you want to use the your server in VS Code you need to provide a VS Code extension which contains some code to start the server. The vscode-languageclient library which is used to start most of the server does have support for all protocol transfers. You you simply pass a flag to control this (see `TransportKind`)

**Comment by vczh** [comment]
@dbaeumer Last question, it seems that the language server protocol doesn't contain anything for token colorization. Do I miss something?

**Comment by dbaeumer** [comment]
@vczh no you don't. There is a feature request to add this but this is not trivial since colorization is very heavy and doing this is a separate process needs some good engineering.

The current approach for a VS Code extension is to use a TM grammer for colorization.

**Comment by vczh** [comment]
@dbaeumer If we separate colorization and auto complete in two different places, how can we use different colors for identifiers, just like VC++ treat types, arguments, macros and variables differently?

**Comment by vczh** [comment]
@dbaeumer I finally find that the fancy colorization only appear in a very limit subset of IDEs. But actually I think if you enable the language server to push a token list with fancy colors, that will solve the performance problem. Since you can still use TextMate and "greening types identifiers" are done async.

**Comment by dbaeumer** [comment]
This is the idea. We talk about syntax colors (TextMate and fast) and semantic coloring (Server based and as fast as possible). But still this needs to be done nicely. The model can't be to push all colors on every edit. That will simply not scale for large files. And it must honor themes.

**Comment by vczh** [comment]
@dbaeumer The point is that you don't need the semantic coloring right after you typed a character. It is acceptable that the semantic colors will be updated in a short while after I stopped typing. So just let the language server decide when the editor need to update those colors. And when the editor gets the list, it can color those tokens when the specified range contains the expected string recorded in the list.
