### ISSUE TITLE
client: Support TransportKind.pipe with external commands

### ISSUE THREAD

**Issue by smarter** [microsoft/vscode-languageserver-node#197]
Currently, `TransportKind.pipe` only works with node modules, but it should be possible to make it work with an external command by adding arguments with the paths of the pipes to the command. I haven't checked but appparently this can work with `server.listen` as long as your careful about the path you use on Windows ("The path must refer to an entry in \\?\pipe\ or \\.\pipe\": https://nodejs.org/api/net.html#net_server_listen_path_backlog_callback)

**Comment by smarter** [comment]
Ah, I see that this is already what `generateRandomPipeName` does. So really the only thing that needs to be done is agree on a convention to pass these pipe names to an external command, like `--pipe-in=xx --pipe-out=xx`

**Comment by dbaeumer** [comment]
Agree. We should handle this transport kind for external commands as well.

**Comment by turbolent** [comment]
It would be great to have support for pipes or sockets. Currently, only the standard input/output transport can be used for non-Node servers, which isn't ideal when e.g. wanting to run the server in a debugger, which uses standard input/output for it's interface.

**Comment by dbaeumer** [comment]
Actually this got addressed in both the library and the specification. See https://microsoft.github.io/language-server-protocol/specifications/specification-current/#implementationConsiderations

Closing the issue. Please ping if you think there is still something missing.
