### ISSUE TITLE
Support ImplementationProvider

### ISSUE THREAD

**Issue by bmewburn** [Microsoft/vscode-languageserver-node#198]
https://code.visualstudio.com/docs/extensionAPI/vscode-api#ImplementationProvider
Hello, is their currently support for this feature?

**Comment by dbaeumer** [comment]
No, but it is in the queue. However the issue is in the protocol repository since besides adding it to the implementation libs we need to spec in the protocol.

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/language-server-protocol/issues/156
