### ISSUE TITLE
Invoking vscode.executeSignatureHelp on completion

### ISSUE THREAD

**Issue by bmewburn** [Microsoft/vscode-languageserver-node#201]
I have been attempting to invoke signature help when a method completion item is selected using the CompletionItem.command property without success.

I supply a snippet string `fn($0)` as the completion item `insertText` and supply Uri and position args for the signature help command but never see any evidence of the command being executed in the client/server trace upon completion. I'm unsure if this is a bug or if I'm using the API incorrectly.

**Comment by rcjsuen** [comment]
@bmewburn What if you use `editor.action.triggerParameterHints` for the property?

**Comment by dbaeumer** [comment]
When you register the signature help provider or return that as a ServerCapability you need to specify the trigger charater to use. Then VS Code will call signature help automatically. See https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol\src\protocol.ts#L476

**Comment by rcjsuen** [comment]
@dbaeumer I don't think that quite accomplishes what is desired. I think what @bmewburn wants is for signature help to be invoked _after_ a completion item has been selected and applied and not for both a `textDocument/completion` and `textDocument/signatureHelp` request to be sent _at the same time_.

I think [Microsoft/language-server-protocol#274](https://github.com/Microsoft/language-server-protocol/issues/274) is probably what @bmewburn is trying to do.

**Comment by dbaeumer** [comment]
@rcjsuen thanks for the clarification. Then I think @jrieken suggestion is the right thing to do and you can set the command id here: https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocolb\main.d.ts#L541

The downside is that this will make the server VS Code specific which you don't want to do. So you can alternatively use the new middleware in the VS Code client and send the command after you have received the completion request from the server.

https://github.com/Microsoft/vscode-languageserver-node/blob/master/client\src\client.ts#L430

**Comment by bmewburn** [comment]
Thanks @rcjsuen triggerParameterHints was what I was looking for. Thanks for the middleware advice @dbaeumer.
