### ISSUE TITLE
Is `client.onReady` necessary?

### ISSUE THREAD

**Issue by nicksnyder** [Microsoft/vscode-languageserver-node#202]
[3.0.3 breaking changes](https://github.com/Microsoft/vscode-languageserver-node#breaking-changes)

>```
>let client = new LanguageClient(...);
>client.onReady().then(() => {
>  client.onNotification(...);
>  client.sendRequest(...);
>);
>```

Is there a reason why consumers of the API should need to call onReady explicitly? Each call to onNotification, sendRequest, etc., could call onReady internally.

**Comment by dbaeumer** [comment]
Then onNotification and onRequest would return a promise. Right now you can be sure that after that calls the handlers are registered since the methods are sync. I thought one onReady() is easier to program against. So you can write something like:

```ts
client.onNotification(....);
client.sendRequest(....); // this request can trigger a notification that is handled by above handler
```

**Comment by nicksnyder** [comment]
> Then onNotification and onRequest would return a promise.

I don't think they would need to (but they could). They would just wait for onReady internally.

> client.onNotification(....);
client.sendRequest(....); // this request can trigger a notification that is handled by above handler

These semantics would still hold if onReady were called internally as long as `onReady` closures are executed in-order (not sure why they wouldn't be).

**Comment by dbaeumer** [comment]
There is no guarantee (spec wise) that the order in which promises are resolved is the same as they are created. If you do (1) p.then() and (2) p.then() it can happen that the callback of (2) is called before callback of (1). To keep things easier implementation wise I decided to have the onReady().

**Comment by nicksnyder** [comment]
Makes sense. Thanks for explaining!
