### ISSUE TITLE
ServerCapabilities.textDocumentSync has no effect when it's set to a TextDocumentSyncOptions instance

### ISSUE THREAD

**Issue by CXuesong** [Microsoft/vscode-languageserver-node#203]
Hi, I come across this problem when trying to build up my own language server with C# step by step, using `vscode-languageclient` to write client-side extension.

According to the language protocol, we have
```c#
interface ServerCapabilities {
	/**
	 * Defines how text documents are synced. Is either a detailed structure defining each notification or
	 * for backwards compatibility the TextDocumentSyncKind number.
	 */
	textDocumentSync?: TextDocumentSyncOptions | number;
	// ...
}
```
That is, I can either give a `number` or a `TextDocumentSync` object to this property, so I composed the response body of `initialize` request as follows
```json
{
    "id": 0,
    "result": {
        "capabilities": {
            "textDocumentSync": {
                "openClose": true,
                "change": 1,
                "willSave": true,
                "willSaveWaitUntil": false,
                "save": null
            },
            "hoverProvider": true,
            "completionProvider": false,
            "signatureHelpProvider": null,
            "definitionProvider": false,
            "referencesProvider": false,
            "documentHighlightProvider": false,
            "documentSymbolProvider": false,
            "workspaceSymbolProvider": false,
            "codeActionProvider": false,
            "codeLensProvider": null,
            "documentFormattingProvider": false,
            "documentRangeFormattingProvider": false,
            "documentOnTypeFormattingProvider": null,
            "renameProvider": false,
            "documentLinkProvider": null,
            "executeCommandProvider": null,
            "experimental": null
        }
    },
    "jsonrpc": "2.0"
}
```
However, no `textDocument/didChange`, `/didSave`, `/didOpen` notifications were sent to the server. I tried to change `textDocumentSync` to
```json
 "textDocumentSync": 1,
```
and everything worked just fine.

After taking a look at [client/src/main.ts:1254](https://github.com/Microsoft/vscode-languageserver-node/blob/e7a665fd75a03d0192a948ae014b1ee5bddee9e2/client/src/main.ts#L1254), I think there might be something wrong with the predicate…
```typescript
} else if (this._capabilites.textDocumentSync !== void 0 && this._capabilites.textDocumentSync === null) {
	textDocumentSyncOptions = this._capabilites.textDocumentSync as TextDocumentSyncOptions;
}
```
Here `this._capabilites.textDocumentSync` can either be `undefined`, `null`, a `number` or a `TextDocumentSyncOptions`, so I guess the predicate should be `this._capabilites.textDocumentSync !== null`.

So… Have I got into some misuderstandings? Thank you!

**Comment by dbaeumer** [comment]
Sounds like a bug

**Comment by dbaeumer** [comment]
It is a bug. Fixed it.

**Comment by dbaeumer** [comment]
Will publish new version 3.2.2 beginning of next week.

**Comment by CXuesong** [comment]
Oh, thank you, dbaeumer :-)

**Comment by dbaeumer** [comment]
Publish 3.2.2
