### ISSUE TITLE
CheckJS marks global variables and text in comments

### ISSUE THREAD

**Issue by sbowler** [Microsoft/vscode-languageserver-node#205]
I'm not quite sure this is the right repo for this, but here goes. Using the latest released vscode I've tried to use the new checkJs compiler option. I'm not finding any way to mark global variables in client side code like lodash as valid so they are not flagged everywhere. Even better would be automatically reading them from ESLint config files, but that's another feature.

In addition it also seems to be scanning and marking items in jsdoc style comments as invalid like 
`* @param {float}`
"Cannot find name float"

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode#26009

**Comment by dbaeumer** [comment]
Actually the right repository for this is vscode.
