### ISSUE TITLE
installServerIntoExtension script works incorrectly if a path to the extension server directory contains spaces.

### ISSUE THREAD

**Issue by adrift2000** [microsoft/vscode-languageserver-node#208]
The problem is here:
cp.execSync('npm update --production --prefix ' + extensionServerDirectory);

It should look like this:
cp.execSync('npm update --production --prefix "' + extensionServerDirectory + '"');

**Comment by alexi2014** [comment]
I experience the same problem with this. Wrapping extensionServerDirectory with quotation marks, as shown by  @adrift2000, solves the problem for me.

**Comment by dbaeumer** [comment]
This script will go away. The new way to go is to have one folder with a client and server sub folder now that we have multiple launch configs and tasks.

**Comment by CestDiego** [comment]
@dbaeumer are the `lsp-samples` updated with this new way? I would like to know what is the best way of going around this

**Comment by dbaeumer** [comment]
The script is deprecated and the lsp-sample demonstrates how the project should be setup now.
