### ISSUE TITLE
Can we have an example of how to setup a connection with remote back end using stream info

### ISSUE THREAD

**Issue by maxhillaert** [microsoft/vscode-languageserver-node#209]
Hi,

Say I have a scala language service that accepts Json RPC requests,  I want to connect to with the LanguageClient.  I assume,  I would need to set the StreamInfo options.   I can't figure out how to do that.   

This doesn't work, but maybe conveys what I'm trying to do :

import * as request from 'request'

 let x = request.post("http://localhost:7676")
  let streamInfo : StreamInfo = {
        reader : x,
        writer: x
    }

**Comment by dbaeumer** [comment]
If you want to use http then you need to send json-rpc over http. There is currently no built in support for this. In addition the protocol is not design to talk to remote servers. The whole protocol for example has no support for multi tenancies. I know that there are team out there that use the protocol that way but the library we maintain doesn't. The easiest in your case would be to use sockets and use the rpc protocol of the json-rpc library directly over the socket. A socket is a readable and writeable stream in Node so you can pass the socket to the reader and writer of the stream info.
