### ISSUE TITLE
Language Service crash & restart doesn't trigger Language Server's onExit and onShutdown, and register provider multiple times

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-languageserver-node#211]
_From @octref on June 2, 2017 3:5_

- VSCode Version: 1.12.2
- OS Version: OS X 10.11.6

For this file: https://github.com/Microsoft/vscode/blob/master/extensions/html/server/src/htmlServerMain.ts

If I add `connection.onExit` or `connection.onShutdown`, none of them will be triggered for server crash & restart.

Manually triggered server crash. Notice none of `exit` or `shutdown` is logged:

![image](https://cloud.githubusercontent.com/assets/4033249/26709072/f4c4d988-471d-11e7-8d9a-78c98ffc7b95.png)

Also, the closed connection does not clear registered providers. And restart & re-registration causes multiple providers to be registered. For example, the `hoverProvider`:

![image](https://cloud.githubusercontent.com/assets/4033249/26709084/137bad70-471e-11e7-808b-9d510dba694a.png)

This is the root cause of https://github.com/Microsoft/vscode/issues/25275#issuecomment-296997278, https://github.com/octref/vetur/issues/110 and https://github.com/octref/vetur/issues/184.

I didn't find any way to unregister providers registered by previous providers, and I think closed connection should dispose all its registered providers by default.

@dbaeumer @aeschli 

_Copied from original issue: Microsoft/vscode#27889_

**Comment by dbaeumer** [comment]
@octref the shutdown request and the exit notification is sent from the client to the server. If the server crashes there is no way we can sent them to the server. Sending them to the restarted server doesn't make sense either. 

If a connection gets closed we cleanup all listeners and provides here: https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/client.ts#L1543

Can you provide me with instructions how to reproduce this (best a workspace to clone). Then I will look why this is not happening for you.

**Comment by octref** [comment]
1. Download this extension and install it. It's built from master here https://github.com/octref/vetur with only one addition that would make the server crash on completion.

  [vetur-0.6.11.vsix.zip](https://github.com/Microsoft/vscode-languageserver-node/files/1048067/vetur-0.6.11.vsix.zip)

2. Clone https://github.com/vuejs/vue-hackernews-2.0

3. Open the vue hn project with VSCode. Then navigate to a vue file, try some completion in the js part. Server will crash and relaunch.

![crash](https://cloud.githubusercontent.com/assets/4033249/26731857/6b9658d8-4783-11e7-9919-c9a762ce50c8.gif)

My server/client are almost identical to that of https://github.com/Microsoft/vscode/tree/master/extensions/html

**Comment by dbaeumer** [comment]
@octref this got already fixed for the upcoming 3.3.0 release. You can test it using the libraries from the next tag.

**Comment by dbaeumer** [comment]
I will release new version end of this week.

**Comment by octref** [comment]
@dbaeumer Sounds good. Thanks!
