### ISSUE TITLE
If args is undefined for Executable then options are ignored

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/vscode-languageserver-node#212]
It seems that typings for `child_process.spawn` is bogus it should be:
```ts
export function spawn(command: string, options?: SpawnOptions): ChildProcess;
export function spawn(command: string, args: string[], options?: SpawnOptions): ChildProcess;
```

at least when I debug an implementation it tests the second argument whether it is an array or an object and treats them differently.

**Comment by dbaeumer** [comment]
Publish 3.3.0-alpha.6
