### ISSUE TITLE
MessageQueue can lose messages when an incoming Request and Response have same ID

### ISSUE THREAD

**Issue by fearthecowboy** [Microsoft/vscode-languageserver-node#217]
The `addMessageToQueue` function adds the incoming message to the `messageQueue` map with the ID from the response or request.

The trouble is if both sides coincidentally send a request to each other with the same ID, and the remote side sends back it's response before the local side can process the message, the incoming request message in the queue is clobbered with the incoming response message.

IE: 
``` yaml

# remote side sends request 
{"jsonrpc":"2.0","method":"ListInputs","params":["session_13"],"id":34}

# local side sends it's own request 
{"jsonrpc":"2.0","id":34,"method":"GetNames","params":null}

# remote side services the request and issues response (before local side processes that item it the message queue)
{"jsonrpc":"2.0","id":34,"result":["bob","mary","julia"]}

# addMessageToQueue clobbers the original request with ID 34
# and the remote side waits forever for a response that is never going to come.
```

The JSON-RPC specification makes no mention of uniqueness--obviously, since neither side would know of the ID generation scheme the other uses.

See: https://github.com/Microsoft/vscode-languageserver-node/blame/master/jsonrpc/src/main.ts#L374

**Comment by dbaeumer** [comment]
@fearthecowboy very nice catch !

**Comment by fearthecowboy** [comment]
Thanks! 

It was weird because we use the JSON-RPC for our IPC communications in AutoRest, and once in a blue moon, we'd get a hang. And then two days ago, we had a test that started failing very reliably in CI so I had to take the time to dig out why...
