### ISSUE TITLE
In-range breaking change in 3.3.1

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode-languageserver-node#218]
This just broke the TS language server, see
https://github.com/sourcegraph/javascript-typescript-langserver/issues/300
https://travis-ci.org/sourcegraph/javascript-typescript-langserver/builds/243177736

**Comment by dbaeumer** [comment]
@felixfbecker this is caused by my renaming an internal method that was never API. Looks like the TS language server is referencing stuff directly from messages.*.

The rename was from isReponseMessage (wring spelling) to isResponseMessage.

Any objection to close this issue.

**Comment by felixfbecker** [comment]
no, I can change it :)
