### ISSUE TITLE
server does not shut down

### ISSUE THREAD

**Issue by vladdu** [Microsoft/vscode-languageserver-node#227]
I'm not sure if this is the right place to report this (also it may be so that I am doing something wrong)

I have a client and server pair created from the example project. It all works fine, but when I stop the debugging session, the server process stays alive. Then when trying to debug again, a new server can't be started because the port is already in use.

If it was a general problem, I suppose more people would have cried, so please help me fix whatever I do wrong. I'm using the stock example code.

**Comment by dbaeumer** [comment]
@vladdu just debugged the example today and it worked for me. How do you start the debug session with the server. If you use VS Code and attach to the server then stopping the debugging session doesn't stop the server. It detaches and leaves the server running. The debugger only `kills` the process if it has launched it.

**Comment by vladdu** [comment]
I am only launching from the client, and do not attach the debugger on the server.

**Comment by dbaeumer** [comment]
How do you start the server?

**Comment by vladdu** [comment]
It's the example code, I don't do anything special. I'm not on that computer right now, so I can't try it again.

By the way, this was with version 1.13, I will try again with newer ones to see if there's any difference.

**Comment by dbaeumer** [comment]
I did quite some development with LSP the last couple of days and I was not seeing this. Do you have any steps to reproduce with the sample. Please be aware that I moved the sample to this repository: https://github.com/Microsoft/vscode-extension-samples

**Comment by vladdu** [comment]
I did a very quick test and it looks it's working. Can't do a full test right now, feel free to close and I will reopen if necessary. Thanks!

**Comment by dbaeumer** [comment]
@vladdu thanks for reaching back. Closing.
