### ISSUE TITLE
LanguageClient doesn't respect uriConverter.code2Protocol option when sending DidChangeWatchedFilesParams

### ISSUE THREAD

**Issue by vazexqi** [Microsoft/vscode-languageserver-node#228]
This is related to https://github.com/Microsoft/vscode-languageserver-node/issues/105.

VS Code sends a non-standard URI on Windows. Instead of sending file:///c:/Us... it sends file:///c%3A/Us... (notice the %3A). We can modify this behavior by providing a [`uriConverter`](https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/client.ts#L455) to `LanguageClientOptions`.  And this works for _almost_ all the different requests that include a URI.

**Where it fails is the `DidChangeWatchedFilesParams`.**

When I receive a `DidChangeWatchedFilesParams` it doesn't go through my custom uriConverter and still has the %3A, necessitating my server to do the conversion for this case.

Is this working-as-design? Or is this an oversight? If you look at the [`Converter` interface](https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/codeConverter.ts#L14) there is no accommodation for `DidChangeWatchedFilesParams`.

Based on the [protocol](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#workspace_didChangeWatchedFiles), I would expect that a client consistently sends the URI in a particular format for all requests that include a URI.

**Comment by dbaeumer** [comment]
This is simply an oversight. @vazexqi would you like to work on a PR to fix this? The code to change is here: https://github.com/Microsoft/vscode-languageserver-node/blob/master/client\src\client.ts#L848-L849

**Comment by vazexqi** [comment]
@dbaeumer See PR #233

**Comment by vazexqi** [comment]
@dbaeumer - Any updates on this? PR already submitted as part of #233

**Comment by dbaeumer** [comment]
Publish 3.4.0-next.16 of the client library.
