### ISSUE TITLE
Piping to stdio and linux using vscode-jsonrpc

### ISSUE THREAD

**Issue by DBosley** [Microsoft/vscode-languageserver-node#229]
After updating the languageserver and jsonrpc dependencies to 3.3.0+ I've had issues piping json data to a running language server. I set console.log points to monitor the data and it appears that none is making it to my server.

This is affecting the TravisCI integration tests with my fork of the [vscode-ng-language-service](https://github.com/DBosley/vscode-ng-language-service) 

Repro Steps: pull down the `vscode-language-server--3.3.0` branch from the above linked repo
on windows, using a bash terminal (git bash works) run these commands from the root of the project:
`./scripts/ci/install.sh`
`./scripts/ci/build.sh`
`./scripts/ci/test.sh`
If it's all working properly, the tests should pass.

Now follow the steps in this link to set up a local travisCI test container in docker (follow steps for the "trusty" node server): 
https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image

Clone the repo into this container and run the same scripts listed above.

Expected: Tests should pass the same way they pass in windows
Actual: no tests pass because the server never receives any data from the mock-host script.

My assessment: it appears to be a problem when using stdio to communicate with the language server. No actual data makes it to the server even though if you run the below command from the "tests" directory, the mock-host outputs the expected data to the console.

`node tools/dist/mock-host --file assets/startup-test.json --pwd $(pwd)`

**Comment by dbaeumer** [comment]
The thing that has changed from 3.2.0 to 3.3.0 is that we now send stuff `more` asynchronously. I have now idea why this in our setup doesn't work with stdio anymore. I tested a simple setup where the client process starts the server process and there stdio works without a problem.

Have you tried to debug our setup to better understand why stdio doesn't work. How do you start the processes ?

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. Thank you for your contributions.
