### ISSUE TITLE
Setting cwd when using streams

### ISSUE THREAD

**Issue by Chillee** [microsoft/vscode-languageserver-node#230]
For example, we have 
```
    const client = new LanguageClient(
      `${language}Proxy`,
      () =>
        Promise.resolve({reader: proxyReadStream, writer: proxyWriteStream}),
      {
        documentSelector: [language],
        uriConverters: {
          code2Protocol: connectionWrapper.uri2Path.bind(connectionWrapper),
          protocol2Code: connectionWrapper.path2Uri.bind(connectionWrapper),
        },
      },
    );
```
However, in VsCode this results in the `rootPath` and `rootURI` attributes in the `initialize` RPC request to be the workspace root. I want to be able to set them to null.

It seems like there is no way to do that currently. Is there?

**Comment by dbaeumer** [comment]
No there is not. Why would you. The value correspond to what VS Code uses?

**Comment by bolinfest** [comment]
I think it's not so much that we want it to be `null`, but we want to set it as the URI for our remote file system that we have configured via https://github.com/Microsoft/vscode/pull/30337.

/cc @jrieken

**Comment by bolinfest** [comment]
Basically, we want things such that after it goes through the converter (`code2Protocol`?) that when the message ends up on the other side of the proxy, it is the proper file path on that remote machine.

**Comment by bolinfest** [comment]
Perhaps the fix needs to happen in VS Code rather than here? If it's passing in `null` to the `LanguageClient` for the `rootUri`, then I suppose we should focus on fixing that instead?

**Comment by dbaeumer** [comment]
The right way to address this then is to have a middleware hook for the initialize request as well. 

PR welcome to add such a hook. See https://github.com/Microsoft/vscode-languageserver-node/blob/master/client\src\client.ts#L422 for the current middleware definition.
