### ISSUE TITLE
Failure to get completion item list while testing

### ISSUE THREAD

**Issue by qballer** [microsoft/vscode-languageserver-node#234]
I'm trying to Implement my own language server and connect it to vscode. 
 
I am trying to implement integration tests: The kind that run the extension host, get the completion items, and make sure the correct suggestion appear.  How can I achieve that? 

outside the scope of tests, during manual running of the extension I get the proper list. 

I've tried two commands so far: 

1. `vscode.executeCompletionItemProvider` - which gets me a list of things but none of my completions. I'm also unsure on how to do that, since registration is in the client, but the server is the provider.  While running `connection.onInitialize` I return the following object: 

```
capabilities: {
            completionProvider: {
                triggerCharacters: ['.', '-', ':', '"']
            }
}
```

2. `editor.action.triggerSuggest`: There I can actually see the suggestion open (for a split of a second) and it doesn't seem to return the right completion.  While this approach may work in the future I don't know where the completion list in the dropdown is stored.

**Comment by dbaeumer** [comment]
@qballer This got simplified this week. There is a new npm module https://www.npmjs.com/package/vscode-languageserver-protocol which only contains the protocol and has only node dependencies. You could integrate this into a test framework, start the server, send the completion requestion and `ensure` the result.

**Comment by dbaeumer** [comment]
Let me know whether this works for you.

**Comment by qballer** [comment]
Wow thats nice. 
My current is solution is doing this: 
https://github.com/wixplosives/stylable-intelligence/blob/master/packages/client/run-test.js

**Comment by qballer** [comment]
In general that kind of test-suite will be great for server client communication. On top of that you will want a few end to end tests that run in the context of vscode. This helps to make sure your lang server works well with vscode. Thing is, trying to query vscode or  language client for current state seems not trivial. For example when I want to test diagnostics this is how I went about it: 
https://github.com/wixplosives/stylable-intelligence/blob/master/packages/client/test/diagnostics.test.ts 

Note that ext!.activate return the client and I query `client._diagnostics._data.get('file://' + casePath)` to get diagnostics.
