### ISSUE TITLE
warning:The Vue Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted

### ISSUE THREAD

**Issue by zzzzzyb** [Microsoft/vscode-languageserver-node#239]
what happen ?

**Comment by rcjsuen** [comment]
I suggest you open a bug with the [vuejs/vetur project](https://github.com/vuejs/vetur/issues).

**Comment by dbaeumer** [comment]
@rcjsuen thanks for pointing @zzzzzyb to the vuejs server project.
