### ISSUE TITLE
languageServer does not permit to check document's _languageId

### ISSUE THREAD

**Issue by kube** [Microsoft/vscode-languageserver-node#24]
From client I can see the `_languageId` of a document, even if it's private.
The problem is that this property is essential in providing the correct completion for the current language.

In my case, for example, I have an extension activationEvent for `['c', 'c++']`, so from my server I need to know if the current document is a C or C++ file to provide correct completion service.

**Comment by dbaeumer** [comment]
Published 1.4.0 npm modules.
