### ISSUE TITLE
configuration api: improve 'getConfiguration' message name

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-languageserver-node#240]
The new message name ([`workspace/getConfiguration`](https://github.com/Microsoft/vscode-languageserver-node/blob/master/server/src/protocol.proposed.ts#L21)) of the proposed configuration API doesn't align with existing messages. It uses a verb, where [normally](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#messages-overview) nouns are used.

Maybe better `workspace.configuration'

Same for the [client capability](https://github.com/Microsoft/vscode-languageserver-node/blob/master/server/src/protocol.proposed.ts#L11)

**Comment by dbaeumer** [comment]
Agree, we should stick with nouns.

**Comment by dbaeumer** [comment]
Actually we do have partly verbs already. `publishDiagnostics`, `showMessage`, ... But never for a get. So I will still change this. to not have a get in the message name.

**Comment by dbaeumer** [comment]
Done.
