### ISSUE TITLE
proposed API: separate workspaceFolders and configuration

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-languageserver-node#241]
https://github.com/Microsoft/vscode-languageserver-node/blob/master/server/src/protocol.proposed.ts#L11 contains both workspaceFolders and configuration APIs

As workspace folders and configuration are separate features, which are not necessarily coupled, ideally, they would be defined separate propose.d.ts files
E.g. `configuration.protocol.proposed.ts` and `workspaceFolders.protocol.proposed.ts`, or in separate node modules.

**Comment by dbaeumer** [comment]
Done.
