### ISSUE TITLE
IConnection.onDefinition - Resouce is not available

### ISSUE THREAD

**Issue by rsKliPPy** [Microsoft/vscode-languageserver-node#242]
Every time I return from `onDefinition`, my client displays `"Unable to open '<filename>': resource is not available"` and opens Developers Tools console, spewing out 5-6 errors about the resource not being available. I know this may be a client error, but after all I am using `vscode-languageserver`, so I thought it would be more appropriate to post here instead of `vscode` repository.

I am writing a language service for a language that has `#include` statements, just like C.
```
#include <header>
```
the idea is to allow the user to `Go to Definition` on the include statement and open the included file in VSCode.

Is it even possible to open new files this way? Does the `uri` property in `Location` have to point to an open file, or even a file in the workspace? What would be the best way to open a file? I've searched and I couldn't find a way to do it from the language server (vscode extension API provides a way to open files though, but that doesn't help me).

Code provided. To clarify:
`firstParsePromise` is there because I parse files asynchronously, so an `onDefinition` request may arrive before the file is parsed the first time. This makes it wait for the first parse.
`data.resolvedInclusions` is guaranteed to contain only URIs of file that do exists on the disk. If they didn't, VSCode would throw an error saying that the file in `Location.uri` doesn't exist. That's not the case here.
```TypeScript
// InclusionDescriptor and ResolvedInclusion definitions
export interface InclusionDescriptor {
    // The included filename
    headerName: string;

    // Where in the file is the #include statement
    start: vscls.Position;
    end: vscls.Position;
};

export interface ResolvedInclusion {
    descriptor: InclusionDescriptor;
    uri: string;
};

connection.onDefinition(async (params) => {
    function inclusionLocation(inclusions: types.ResolvedInclusion[]): vscls.Location {
        for(const inc of inclusions) {
            if( params.position.line === inc.descriptor.start.line
                && params.position.character > inc.descriptor.start.character
                && params.position.character < inc.descriptor.end.character
            ) {
                return vscls.Location.create(inc.uri, {
                    start: { line: 0, character: 0 },
                    end: { line: 0, character: 1 }
                });
            }
        }

        return null;
    };

    let data = documentsData.get(documentsManager.get(params.textDocument.uri));

    if(data.firstParsePromise !== null) {
        return inclusionLocation((await data.firstParsePromise.promise).resolvedInclusions);
    } else {
        return inclusionLocation(data.resolvedInclusions);
    }
});
```

**Comment by dbaeumer** [comment]
This happens when the returned Location points to a uri that doesn't exist. How does inc.uri look like?

**Comment by rsKliPPy** [comment]
I have *just* figured it out. I was about to write a reply that a uri does exist, but then I tried to prepend `file:///` and it worked. So the schema *is* required.

Thanks for your reply nonetheless. 😅

**Comment by dbaeumer** [comment]
It is a uri which has to have a scheme. You might want to consider using our node module vscode-uri which helps you to construct a file URI from an fspath.
