### ISSUE TITLE
Uncaught exception when calling connection.console.info()

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode-languageserver-node#25]
I received the following error when trying to use the `info()` method of the `RemoteConsole` object  while in my completion provider. The other console methods were not affected and operated normally.

`Notification handler 'window/logMessage' failed with message: EPERM: operation not permitted, write`

Essentially the relevant code I was using boiled down to:
```javascript
connection.onCompletion((position: TextDocumentPosition): CompletionItem[] => {
  connection.console.info('...');
});
```

vscode-languageserver: 1.3.1
os: windows 10

**Comment by dbaeumer** [comment]
This is an issue in the extension host. Moving to vscode

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode#3128
