### ISSUE TITLE
Add CompletionItem.commitCharacters

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-languageserver-node#250]
In VSCode it is possible to list commit characters for each completion proposal.

**Comment by dbaeumer** [comment]
@aeschli I added support and released it as 3.5.0-next.2.

However I didn't make it a client capability. The problem might be that a server returns a completion item with commit characters and on resolve it is missing because the client drops it.

Do you think we should add a capability ?

**Comment by aeschli** [comment]
@dbaeumer Thinking about it, better to add a client capability. Can save bandwith and help us for future versions, e.g. if the format of the commitCharacters evolves.

**Comment by dbaeumer** [comment]
OK. Will add it.
