### ISSUE TITLE
installServerIntoExtension doesn't work with yarn workspaces

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/vscode-languageserver-node#251]
It would be nice if `installServerIntoExtension` would work with yarn workspaces. I currently have three packages in a workspace:
- a linter
- a language server
- an extension

With yarn workspaces the linter is symlinked as a dependency into the language server, but I don't get the symlinked version when `installServerIntoExtension` is called, because it fetches the published npm version.

---

Or is there a way where I don't need to use `installServerIntoExtension`?

---

So I removed the usage of `installServerIntoExtension` and it looks like everything still works? For what is it needed exactly?

**Comment by dbaeumer** [comment]
@donaldpipowitch my plan is to fully remove the `installServerIntoExtension` script and either use workspace folders or a single root recommendation. I converted ESLint to have a single folder that contains both the client and the server and doesn't need to copy any files into the extension anymore. (See https://github.com/Microsoft/vscode-eslint). Let me know if this would work for you. 

The script copied js files and npm packages into the extension folder (the client). As said with a more clever layout that is now possible with VS Code this is not needed anymore.

Objections to close ?

**Comment by donaldpipowitch** [comment]
> either use workspace folders or a single root recommendation

This sounds nice. People who prefer yarn can use workspaces and other people could use a single root. +1

**Comment by dbaeumer** [comment]
Great. I will close the item then.
