### ISSUE TITLE
client: languageconnection.initialize called before the server is ready to respond

### ISSUE THREAD

**Issue by untra** [Microsoft/vscode-languageserver-node#254]
I'm currently trying to develop a language server for Elixir. Unfortunately the language server takes a few milliseconds to fully startup, during which time the client sends the `initialize` request, but is never received by the server.

https://github.com/Microsoft/vscode-languageserver-node/blob/aceee693a615d3eda358d9de7e6d2cfca529c330/client/src/client.ts#L2505-L2507

At this point the client sends the [initialize request](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#initialize) to the server. Per the specification: 
> Until the server has responded to the initialize request with an `InitializeResult` the client must not sent any additional requests or notifications to the server.

This puts the client in a state where it is still awaiting a response from the server, and the server is awaiting the original `initialize` request it never received. The client cannot get unstuck from this state.

Possible solutions:
* **The client could timeout the initialize request after x seconds**: assuming the provided `clientOptions` includes a permissive `initializationFailedHandler`, a timeout rejection from this promise will lead to the client [attempting to initialize the connection again](https://github.com/Microsoft/vscode-languageserver-node/blob/aceee693a615d3eda358d9de7e6d2cfca529c330/client/src/client.ts#L2542-L2544).
* **The server can send an `ready` notification to the client**: This is not per the spec, but as the current protocol specification and implementation demonstrate, if a server cannot fully startup before the client is ready is send `initialize`, then the client and server stop communicating and can never reinitialize. This is worthy of a proposal.

I have made a small modification to the languageclient in my project so it times out the initialize request after three seconds. This addressed these issues:
```js
....
this.fillInitializeParams(initParams);
const timeout = (ms) => { return new Promise((resolve, reject) => {
    setTimeout(() => reject(vscode_languageserver_protocol_1.ResponseError), ms);
})};
return Promise.race([
    connection.initialize(initParams),
    timeout(3000)
])
.then((result) => {
    // success
    this._resolvedConnection = connection;
    ...

```

**Comment by dbaeumer** [comment]
@untra how do you communicate with the server. I have never experienced this since the connection should only be resolved when the server is ready to take requests.

**Comment by untra** [comment]
@dbaeumer the serverOptions I am sending point to running a bash script, which starts [escript](https://github.com/JakeBecker/elixir-ls/blob/master/bin/exscript.sh#L27) , eventually starting the elixir application. 

I think somewhere in the escript startup the erlang vm has a few milliseconds where it has resolved the connection, but has not yet started up the supervisors / child applications that can handle the initialize request. During this time the client sends the initialize request, it goes unheard, and the whole language server protocol interaction falls apart with no way to recover.

Other language servers may not have this problem, but this might be specific to how the Erlang VM handles connections. I'm going to ask some more knowledgeable folk about this dilemma, and see if there is a better solution than putting a timeout on the vscode client initialize.

**Comment by dbaeumer** [comment]
Which transport are you using. Stdio, sockets or pipes?

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. Thank you for your contributions.
