### ISSUE TITLE
LanguageClient does not handle IntelliSense correctly for PowerShell static class methods

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode-languageserver-node#26]
We're seeing an issue in the PowerShell extension where our trigger for static .NET class methods is not resulting in the right IntelliSense in VS Code.  To reproduce the issue, try typing this in a PowerShell script file after installing the PowerShell extension on a Windows machine:

```powershell
[DateTime]::
```

After the second `:` we would expect an IntelliSense pane to appear.  Our language server sends the `:` character back as a triggerCharacter in our completionProvider section of the serverCapabilities object in the Initialize response.  Could there be an issue with the double-colon?

Another interesting problem here is that using `Ctrl+Space` after the double-colon results in an empty IntelliSense list even though our server gets the request correctly and returns a list of IntelliSense results.  Can you think of a reason why the results wouldn't be applied in this case?

We're tracking the issue on our side here: https://github.com/PowerShell/PowerShellEditorServices/issues/163

Let me know if it's more appropriate to file this on the Microsoft/vscode repo.

Thanks!

cc @rkeithhill @dfinke

**Comment by dbaeumer** [comment]
I checked that the language server correctly returns the :: and initialized code complete with the value. However to my knowledge VSCode only support trigger characters not trigger strings. Moving to VSCode for commenting

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode#3153

**Comment by daviwil** [comment]
Good to know, thanks Dirk!
