### ISSUE TITLE
Client does not declare clientCapabilities.workspace.applyEdit as being true

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/vscode-languageserver-node#263]
In [863685b](https://github.com/Microsoft/vscode-languageserver-node/commit/863685b0dc160345bb91d7f7bac84cc6b89d8153#diff-79d1f5abc1a9f55a0e9eae588a7fdd56) the capability was commented out and the commented code was then subsequently removed in [4bc789e](https://github.com/Microsoft/vscode-languageserver-node/commit/4bc789ecfca9af5f98188e42ee3302dae2b2a5aa#diff-79d1f5abc1a9f55a0e9eae588a7fdd56). Language servers may incorrectly assume that the client doesn't support certain features since `applyEdit` is `false` so this should be corrected.

**Comment by dbaeumer** [comment]
Closing. PR merged.
