### ISSUE TITLE
Stream read errors result in uncaught exceptions

### ISSUE THREAD

**Issue by hansonw** [microsoft/vscode-languageserver-node#270]
Currently, message errors from StreamMessageReader's onData method end up as uncaught exceptions, which can be very difficult to handle when used in server contexts.

https://github.com/Microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/messageReader.ts#L220

Would it be reasonable to convert such errors into error events (via `this.fireError`) so that the stream owner can perform shutdown / restart steps as necessary? I can submit a PR to do so. cc @ljw1004

**Comment by dbaeumer** [comment]
Yes, but we should clearly defined that the readere then moves into an error state and doesn't process any new onData events since it can not meaningful recover from a missing content length.

**Comment by raxod502** [comment]
Any workaround? It is really really bad if your server crashes just because some LSP stream got broken.

**Comment by dbaeumer** [comment]
The got improved already an errors are now reported on the connection. What esle do you expect the reader to do if it receives a broken message

**Comment by raxod502** [comment]
When an error occurs, the entire Node.js process is crashed for me. Do I have to register an error handler to prevent this from happening, or am I doing something else wrong that is causing me to mistakenly blame this package?

**Comment by dbaeumer** [comment]
Not sure I understand that correctly. The server node process crashes ?

**Comment by raxod502** [comment]
Yes. The Node.js process that is running vscode-languageserver-node crashes.

**Comment by dbaeumer** [comment]
What seems strange to me is that the node process crashes. It shouldn't :-) 

But I am open for a PR that converts the exception into a fireError.

**Comment by dbaeumer** [comment]
OK. Now I understand. Under crash I was assuming a real process crash. 

For the servers I maintain I have a `process.on('uncaughtException', (error: any) => { ... })` handler since exception can occur in other parts of your server as well.

**Comment by dbaeumer** [comment]
This got addressed in the meantime. The exception are now reported via the `onError` event.
