### ISSUE TITLE
No CompletionItem.data property on middleware resolveCompletionItem arg

### ISSUE THREAD

**Issue by bmewburn** [Microsoft/vscode-languageserver-node#282]
The vscode-languageserver-types definition of `CompletionItem` has a data property but the middleware resolveCompletionItem signature accepts a vscode `CompletionItem` and doesn't appear to have a data prop.

**Comment by dbaeumer** [comment]
This is by design. The data types in the middle ware are the VS Code data types. If you need to get to the LSP data types you need to convert them using the converters available in the LSP client.
