### ISSUE TITLE
How to implement commands for exporting all files in the workspace/all changed files?

### ISSUE THREAD

**Issue by christianvoigt** [Microsoft/vscode-languageserver-node#287]
Hi, I am in the middle of writing a language server for Argdown, a Markdown-like DSL for analyzing argumentation. I would like to add export commands that can be executed from the command palette. The commands should export all .argdown files in the workspace to html/dot files (other commands could do the same for all open files or the file in the currently active editor window). But I am not sure how to get the uris to all .argdown files in the command handlers. The only option I am seeing right now is to define an internal command that gets executed by the client if the official command is executed from the command palette so that the client can provide all uris in an argument. Is this the best pattern to use?

I would also like to add a file watcher that automatically exports changed files to dot/html files. The user should be able to activate/deactivate the automatic exports from vscode. The language server has the workspace/didChangeWatchedFiles notification, but I am not sure if I can use this as I need to know if the user currently wants to export files or not. If I am understanding the language server concept right, the server is not supposed to keep such client-specific state variables, as it should be able to react to notifications from different clients. Is that right? Or should I simply set a flag if "startExportingFilesOnChange" and "stopExportingFilesOnChange" commands are executed? 

The alternatives would be to a) either watch files on the client side and execute the export command if files were changed or b) to give up on implementing this with a language server and use a task and my existing command line tool that already supports this (I would like to avoid using a task and the cli, because many of the users will not be programmers and this would probably make the feature inaccessible to them).

I would really appreciate if you could point me in the right direction.

**Comment by dbaeumer** [comment]
LSP servers are not multi tenant / multi client. So you can keep the state whether the user want to export or not. Best would be this is a vscode setting and not a command.

Exporting these files should be done by the server and the server should compute the set to export. The client doesn't necessarily need to know all Argdown files. The contract between client and server in terms of files is:

- files on disk are owned by the server
- file open in the editor are owned by the client and the client guarantees that it notifies the server about any changes in the document.

**Comment by christianvoigt** [comment]
Thanks, that was very helpful for me.
