### ISSUE TITLE
Allow Diagnostic's message to be MarkedString

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-languageserver-node#288]
The use case is to show an error's documentation online.

For example, in `eslint-plugin-vue`, if I'm giving back a `Diagnostic` of `attribute-hyphenation`, I'd like to include in the message something like

```md
[attribute-hyphenation](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/attribute-hyphenation.md)
```

**Comment by rcjsuen** [comment]
@octref You should open a bug against the [Microsoft/language-server-protocol](https://github.com/Microsoft/language-server-protocol/) repository instead if you want to make suggestions to the protocol.

As to your particular problem, please see Microsoft/language-server-protocol#250.

**Comment by octref** [comment]
I see, I didn't find that issue. Thanks for linking.
