### ISSUE TITLE
Does the client output channel really ever need to be cleared?

### ISSUE THREAD

**Issue by davidanthoff** [Microsoft/vscode-languageserver-node#297]
Is [this](https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/client.ts#L2678) line really necessary? We lately have seen a large number of cases where our language server crashes, but we never get to see what it spit out via STDERR before it crashed because the output channel for the language server gets cleared before we can see anything. Makes it almost impossible for us to debug these errors...

**Comment by dbaeumer** [comment]
I removed the clearing code.
