### ISSUE TITLE
HandlerResult<R, E> doesn't let you return a result or an error asynchronously

### ISSUE THREAD

**Issue by dcastro** [Microsoft/vscode-languageserver-node#300]
Basically, in my `onInitialize` handler, I want to return a `Promise<InitializeResult | ResponseError<InitializeError>>`, but I can't.

The handler's type is:

```typescript
RequestHandler<InitializeParams, InitializeResult, InitializeError>
```

Which, after replacing all the type aliases, is the same as:

```typescript
(params: InitializeParams, token: CancellationToken):
    InitializeResult | ResponseError<InitializeError> | Thenable<InitializeResult> | Thenable<ResponseError<InitializeError>>;
```

In other words, your handler is allowed to *synchronously* decide whether it's gonna fail or succeed 

```typescript
(params): InitializeResult | ResponseError<InitializeError> => {
  if (condition) return success; else return error;
}

(params): Promise<InitializeResult> | Promise<ResponseError<InitializeError>> => {
  if (condition) return AsyncSuccessOp();     //where AsyncSuccessOp: Promise<InitializeResult>
  else return AsyncErrorOp();                 //where AsyncErrorOp:   Promise<ResponseError<InitializeError>> 
}
```

but it's not allowed to perform some async operation and _then_ decide whether to fail or succeed

```typescript
async (params): Promise<InitializeResult | ResponseError<InitializeError>> => {
  if (await AsyncCondition()) return await AsyncSuccessOp();
  else return await AsyncErrorOp();
}
```

**Comment by dcastro** [comment]
Note: this is somewhat related to #225, but the suggested solution ("Simply remove the typings") doesn't help the fact that `Promise<InitializeResult | ResponseError<InitializeError>>` should be a possibility but isn't.

**Comment by dbaeumer** [comment]
This is because of returning `Promise<InitializeResult> | Promise<ResponseError<InitializeError>>` is not a valid return value for a async function.

**Comment by dcastro** [comment]
@dbaeumer Thank you for the reply.

I know why it doesn't compile. What I'm saying is, we should support the scenario described in that last snippet (i.e. `Promise<InitializeResult | ResponseError<InitializeError>>`).

**Comment by dcastro** [comment]
In fact, one could write a function from `R | ResponseError<E> | Thenable<R> | Thenable<ResponseError<E>>` to `Thenable<R | ResponseError<E>>`, but not the other way around. Meaning that the second type is capable of encoding all the scenarios described by the first and then some, but first can only decode strictly fewer scenarios.

So, in theory, `R | ResponseError<E> | Thenable<R> | Thenable<ResponseError<E>>` could be entirely replaced by `Thenable<R | ResponseError<E>>` (I'm not suggesting it though, I'm sure there are other technical reasons that I'm missing).

**Comment by dbaeumer** [comment]
The commit that closed this issue adds `Thenable<R | ResponseError<E>>` to the HandlerResult. That should fix this IMO or do I miss something?

**Comment by dcastro** [comment]
@dbaeumer Oh, you're completely right! I hadn't noticed that the issue was closed _with a commit_. Thanks a lot.
