### ISSUE TITLE
Use this language-server outside VSCode

### ISSUE THREAD

**Issue by semanser** [Microsoft/vscode-languageserver-node#301]
Hello. I have a simple question. Is it possible to run this server separately from vscode and for example Vim as a client (with some plugin of course)? Will this provide the same quality of autocomplete and IDE-functions as VSCode does?

**Comment by rcjsuen** [comment]
@semanser This repository houses code for a) writing a language server in TypeScript and b) writing a language server plug-in for VS Code. This repository itself is not a language server.

If you are searching for a C++ or Java language server or whatever programming language, this repository is **not** what you are looking for.

**Comment by dbaeumer** [comment]
@rcjsuen is correct. @semanser you might want to have a look at this page to get on overview of available language servers and who maintains them. https://microsoft.github.io/language-server-protocol/implementors/servers/
