### ISSUE TITLE
Send didOpen requests after LS crashed

### ISSUE THREAD

**Issue by davidanthoff** [Microsoft/vscode-languageserver-node#304]
This is the scenario: I have VS Code open, with a file open with unsaved changes. Now my language server crashes for some reason. VS Code restarts my language server. New LS instance starts up, but as far as I can tell this new instance never receives a ``didOpen`` request with the content of the unsaved file that is open in the editor. So now the state in the editor and the LS have diverged: my LS doesn't know about the unsaved edits in the file.

So I guess one option would be that VS Code sends a ``didOpen`` request when it restarts a LS after a crash for all open files.

Or is there some other way we should handle that?

**Comment by davidanthoff** [comment]
Bump, any advice on this one?

**Comment by dbaeumer** [comment]
Actually the LSP should send open file over when it starts a language server. The corresponding code is here: https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/client.ts#L762

I will look into if something got broken there.

**Comment by dbaeumer** [comment]
OK. This got borken by closing the output channel which then results in an exception when restarting the server which is not handled correctly. I will fix it.

**Comment by davidanthoff** [comment]
Great, thanks! Do we have to wait for the next VS Code release for the fix to show up for us? Or would it be enough that you publish a release of the npm package, and we could use the updated npm package in our extension now already?

**Comment by dbaeumer** [comment]
I need to publish a new npm module which will happen end of this week as a new .next version. The final version will come end of next week.

**Comment by davidanthoff** [comment]
@dbaeumer any news on the publication of the npm module? Would be great if that could happen soonish, we are eager to release a new version of our extension.

**Comment by rcjsuen** [comment]
@davidanthoff I think version `4.0.0-next.11` of `vscode-languageclient` should include the fix.

Can you confirm?

**Comment by dbaeumer** [comment]
Yes, and 4.0.0 official for client and server got published yesterday.

**Comment by davidanthoff** [comment]
Yes, I see it, thanks a lot everyone!

**Comment by davidanthoff** [comment]
So I've just tried to use the new 4.0.0 version, and I get a bunch of errors a la
````
node_modules/vscode-languageclient/lib/colorProvider.d.ts(1,69): error TS2305: Module ''vscode'' has no exported member 'Color'.
node_modules/vscode-languageclient/lib/colorProvider.d.ts(1,86): error TS2305: Module ''vscode'' has no exported member 'ColorPresentation'.
node_modules/vscode-languageclient/lib/colorProvider.d.ts(1,127): error TS2305: Module ''vscode'' has no exported member 'ColorInformation'.
````
Does this need a new release of the ``vscode`` package to work?

**Comment by dbaeumer** [comment]
Sorry. We moved to 1.20.
