### ISSUE TITLE
textDocument/formatting fails to work for multi-root folders using the language server protocol

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-languageserver-node#305]
_From @sean-mcmanus on January 24, 2018 21:50_

Any OS and VS Code version.

1. Open a multi-root workspace.
2. Install an extension that uses the language server protocol and supports textDocument/formatting, such as cpptools (https://github.com/Microsoft/vscode-cpptools ).
3. Format Document on a file in the 2nd workspace folder (files in the 1st workspace folder work correctly).

Bug: Formatting fails. Our language server is returning the correct data, but it gets ignored by VS Code and the document is never updated with the edits from the formatting.

This is https://github.com/Microsoft/vscode-cpptools/issues/1391 .

An example of input/output is:

`************************************************************************************************************************
{
    "jsonrpc": "2.0",
    "id": 3,
    "method": "textDocument/formatting",
    "params": {
        "textDocument": {
            "uri": "file:///f%3A/New%20folder%20%288%29/New%20folder/test14.cpp"
        },
        "options": {
            "tabSize": 4,
            "insertSpaces": false
        }
    }
}
************************************************************************************************************************
Content-Length:375

{
    "jsonrpc": "2.0",
    "id": 3,
    "result": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 43
                },
                "end": {
                    "line": 1,
                    "character": 0
                }
            },
            "newText": " + 0;\r\n"
        }
    ]
}`

_Copied from original issue: Microsoft/vscode#42119_

**Comment by rcjsuen** [comment]
I tried reproducing this with my Dockerfile language server but was unable to.

**Comment by sean-mcmanus** [comment]
@rcjsuen What do you suspect is causing the difference? In our case, we have one language server process per workspace folder. All our other features work correctly with multi-root, and I don't know how we could be messing up formatting.

**Comment by rcjsuen** [comment]
@sean-mcmanus Sorry, I have no idea. Perhaps you could try having one single language server process for the entire VS Code instance? Though maybe your code isn't structured in a way that makes testing that a matter of commenting out a bunch of code.

Does your formatter work on a third workspace folder?

If you remove all the workspace folders and then add the second one first and then the first one second, does it work in the second (but now first) workspace folder?

**Comment by sean-mcmanus** [comment]
We require multiple processes. Formatting doesn't work on the 3rd+ folders only the 1st. Removing folders to 0-1 and adding more doesn't enable formatting until a reload window occurs (extension reloads) in which case the current first/top folder is the only one that has formatting working.

**Comment by azydevelopment** [comment]
Is this in line to be fixed soon? Not having autoformat really messes with checkins and deltas.

**Comment by rcjsuen** [comment]
@azydevelopment Is it broken for your in the Microsoft C/C++ extension or in another extension?

**Comment by azydevelopment** [comment]
Cpp. I originally found it with that and the cpp bug now links here.

**Comment by dbaeumer** [comment]
I tested this with the following example: https://github.com/Microsoft/vscode-extension-samples/tree/master/lsp-multi-server-sample

and it works for me without any problems. I checked in the formatting example under this branch:

https://github.com/Microsoft/vscode-extension-samples/tree/dbaeumer/formatting-305/lsp-multi-server-sample

@sean-mcmanus can you please try to debug this in the CPP extension since I am not able to reproduce this in the above case. Can you spot any difference between our example code and what you do in CPP. I remember that the CPP extension does some additional tweaks in the middle ware so may be it filters the request on the middle ware layer.

**Comment by sean-mcmanus** [comment]
@dbaeumer I don't understand at what point you believe our extension is behaving incorrectly. Are we not passing back the correct JSON? Our extension's typescript is open source and the closed source C++ is just returning the JSON output shown in above. I don't know how to debug this any further on our end, because we appear to be sending the correct database via the language server protocol.

**Comment by dbaeumer** [comment]
@sean-mcmanus as said this works for me in https://github.com/Microsoft/vscode-extension-samples/tree/dbaeumer/formatting-305/lsp-multi-server-sample. Since I know that your client does quite some tweaking in the middleware layer returning the right JSON might not necessarily mean that the result hits the VS Code API. So would you be able to debug this in our client code and see what happens in `DocumentFormattingFeature` in client.js and if the feature forwards the request correctly to the VS Code API.

I am not saying there isn't a bug in our code but I am not able to reproduce the described behaviour.

**Comment by sean-mcmanus** [comment]
I'm still confused. Are you able to clone our repository at https://github.com/Microsoft/vscode-cpptools and debug the issue yourself? The relevant code is https://github.com/Microsoft/vscode-cpptools/blob/master/Extension/src/LanguageServer/client.ts and `\Extension\src\LanguageServer\protocolFilter.ts` and the https://github.com/Microsoft/vscode-cpptools/blob/master/Extension/src/LanguageServer/protocolFilter.ts . I think it would be easier for you to debug the client.js using our extension. I tried debugging client.js but I don't understand what I'm looking for and I don't see any bugs.

![image](https://user-images.githubusercontent.com/19859882/37859270-65820c66-2ece-11e8-9373-e457f89b7bc1.png)

I just see our language server process is sending back the textDocument/formatting message, but it's ignored by VS.

![image](https://user-images.githubusercontent.com/19859882/37859306-d5f3405a-2ece-11e8-8e80-bb149b755781.png)

@bobbrow Implemented the multi-root support so maybe he could explain stuff better.

**Comment by dbaeumer** [comment]
@bobbrow can you please have a look. As I tried to explain in the multi root / multi server example I have everything works as expected. 

And your documentation link about building and debugging the extension is broken (e.g. on page https://github.com/Microsoft/vscode-cpptools/blob/master/CONTRIBUTING.md)

**Comment by dbaeumer** [comment]
Reopening the issue.

**Comment by dbaeumer** [comment]
@sean-mcmanus can you step through the calls, especially the middle ware and see that the call returns to the VS Code API.

**Comment by sean-mcmanus** [comment]
Bob's on vacation...he might be in Wednesday. I created a pull request to fix the broken link, which points to https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Building%20the%20Extension.md .

Sure, I can try to step through the middle ware code again.

**Comment by dbaeumer** [comment]
@sean-mcmanus thanks. When stepping through the middleware please pay attention to the URI's. It could be that they might not point to a valid file location and that therefore the request is dropped silently

**Comment by dbaeumer** [comment]
I debugged this using the instructions provided in comment https://github.com/Microsoft/vscode-languageserver-node/issues/305#issuecomment-378164249 using the following setup

- started extension from source
- copied SampleClangProject to SampleClangProject2
- opened both as workspace folders
- opened SampleClangProject/main.cpp and formated whole document. It works.
- oepned SampleClangProject2/main.cpp and formated whole document. It fails.
- The edits that are finally returned to the VS Code API are an empty array, hence no formatting is happening.

<img width="1128" alt="capture" src="https://user-images.githubusercontent.com/1931590/38244922-80d37baa-373c-11e8-9824-869e77e5bd81.png">

I don't know why this is happening or whether it is the example I choose (however when only having on project open everything is as expected). 

I noticed that formatting goes through `DocumentFormattingAdapter` which is owned by the CPP extensions.

**Comment by rcjsuen** [comment]
I think `DocumentFormattingAdapter` is owned by [VS Code](https://github.com/Microsoft/vscode/blob/2e4bfdb24fd137a1d2e87bd480f283cf7001f19a/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L332). Or does the C++ extension have something with the same name?

**Comment by dbaeumer** [comment]
@rcjsuen yes, you are right. I meant it goes through `invoke3` in protocolFilter.ts.

**Comment by sean-mcmanus** [comment]
Yeah, I debugged it after modifying the javascript to match your screenshot and I see the formatted result for the 2nd workspace folder...same as with the 1st workspace folder, but the document isn't updated with the results. Let me know what the next step is. I'm not sure what empty array you're seeing. The 1st result value is "pending" and then it gets the formatted value later in the ".then".

![image](https://user-images.githubusercontent.com/19859882/38274809-a553e318-3744-11e8-997c-97b234b313c0.png)

**Comment by dbaeumer** [comment]
When I tested it I used the main.cpp from the SampleClangProject project which is formatted when opened in a single folder mode but not in a multi folder mode where I used a copy of it. Can you please try the same example and let me know whether that works for you? Or can you provide me with a GitHub repository to clone with our setup.

**Comment by dbaeumer** [comment]
This is what I am testing:

<img width="1233" alt="capture" src="https://user-images.githubusercontent.com/1931590/38311900-9408c768-3820-11e8-8cf1-142d604859f6.png">

**Comment by dbaeumer** [comment]
And this is what I get if I only have one folder open (SampleClangProject2)

<img width="1232" alt="capture" src="https://user-images.githubusercontent.com/1931590/38312017-e34f2c4a-3820-11e8-82b0-20bc8df89e47.png">

which indeed works correctly.

**Comment by sean-mcmanus** [comment]
Okay, I tried the SampleClangProject and I reproed what you're seeing but that looks like a different bug that I'm investigating (looks like there's a problem with formatting before an edit is made). If you change the argv[1] to argv[1+1] then the result comes back with " +1" but VS Code doesn't format the doc. Also, I'm seeing the formatting fail for the 1st project as well.

**Comment by sean-mcmanus** [comment]
The blank array you hit was a different bug https://github.com/Microsoft/vscode-cpptools/issues/1792 -- causing by "SampleClangProject" incorrectly matching with "SampleClangProject2". I have a branch with the fix see https://github.com/Microsoft/vscode-cpptools/pull/1793 , or you can just work around the issue (i.e. changing your folder names).

**Comment by dbaeumer** [comment]
I was able to reproduce this and there are two issues:

- in VS Code itself. If more than one formatting provider is available for the same document they aren't handled correctly. @jrieken  is aware of this.
- in the CPP extension. The extensions creates n clients to handle the n servers, however is doesn't scope the clients correctly to the workspace folder the server is running on. As a result VS Code has n formatting providers registered and the formatting request for every document is dispatched to all servers (and I think all the other language smarts as well which might be a performance and a result merging problem). The problematic code in the CPP extension is here: https://github.com/Microsoft/vscode-cpptools/blob/master/Extension/src/LanguageServer/client.ts#L374. The code should pass in a pattern to filter correctly for the workspace folder like in this example: https://github.com/Microsoft/vscode-extension-samples/blob/master/lsp-multi-server-sample/client/src/extension.ts#L94

I will close the issue since there is nothing that needs to happen in the LSP library to fix this.

**Comment by jrieken** [comment]
I have pushed https://github.com/Microsoft/vscode/commit/4e2035d4ebbc954f82bf83dc0e8cca3717aeb8f8 for more correct handling on our side

**Comment by dbaeumer** [comment]
@jrieken thanks!

**Comment by bobbrow** [comment]
@dbaeumer, we can't pass in a pattern to filter files because that pattern only selects files under the workspace folder.  C++ users very commonly have header files (e.g. STL headers) and 3rd party libraries living outside the workspace folder.  We implement a `Middleware` to do our own filtering because this feature does not work for C/C++.

**Comment by bobbrow** [comment]
I didn't see a case where messages were sent twice.  It could be related to https://github.com/Microsoft/vscode-cpptools/pull/1793 that we found while debugging your particular example (two folders with partially matching names).

**Comment by bobbrow** [comment]
Thanks for the clarification.  I believe we actually return null in the Middleware, but I'm not sure if that makes a difference on your side.

**Comment by dbaeumer** [comment]
Not in the LSP, more in VS Code itself. You need to check this against the specification of the VS Code API in terms if what each provider does if more than one provider returns results for the same file. As said for some we simply take the first (none null) return result for other we merge them together.
