### ISSUE TITLE
How to read the contents of other files?

### ISSUE THREAD

**Issue by stkb** [Microsoft/vscode-languageserver-node#31]
I'm considering writing a language server for another language, but after going through the docs and example, I'm left with a question:

How should the language server read the contents of associated source files in the project that aren't opened in the editor? Should it just read them from disk itself, or should it be requesting the client for the file contents somehow; and if so, how?

#1 Seems to be related

**Comment by daviwil** [comment]
This one is left up to language server implementors for now.  Though in the future I would imagine that any language-server-as-a-service running in the cloud would need this type of request.

**Comment by stkb** [comment]
Ok thanks for the info!

Well I guess my question's answered so I'll close this now.

**Comment by dbaeumer** [comment]
@stkb Just for completeness: the contract between VSCode and the language server is as follows: 

- if a file is open the truth of a file is inside VSCode. Therefore the language server should never go to disk to read the content of the file. It should always rely on the initial content passed in the open notification and the updates in the update notification

- if a file is closed the truth of the file resides (from a VSCode perspective) on disk. So the language server can read the file from disk. If the language server wants to react properly to file changes to closed files done by another tool the language server can either listen himself to file events or reuse the file events provided by the language server protocol.

**Comment by stkb** [comment]
@dbaeumer Thanks for the extra info. That solidifies it for me.
