### ISSUE TITLE
Support null returned value

### ISSUE THREAD

**Issue by apupier** [Microsoft/vscode-languageserver-node#311]
With current version of the specification, null is supported as return type for document/Hover, textDocument/willSaveWaitUntil and several others.

see https://github.com/Microsoft/language-server-protocol/commit/a286f7adf15a3205cd5051fe1d7684852e12f407#r25753314
and
https://github.com/Microsoft/language-server-protocol/issues/261

At least for document/Hover it is not supported by VS Code client.

**Comment by dbaeumer** [comment]
This is supported. See https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/protocolConverter.ts#L235 and https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.ts#L1400

Please note that the VS Code client API requires `undefined` but the protocol allows `null`.

Can you please elaborate what you think is missing.

**Comment by apupier** [comment]
if I change https://github.com/lhein/camel-language-server/blob/dac029d900df1751b81e7404c2429118feba3680/server/src/main/java/org/apache/camel/tools/lsp/internal/hover/HoverProcessor.java#L55

to
CompletableFuture.completedFuture(null)

then in VS Code, in console log there is:

```
console.ts:123 [Extension Host] Received message which is neither a response nor a notification message:
{
    "jsonrpc": "2.0",
    "id": "1"
}
t.log @ console.ts:123
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:211
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
```

in the output I also have:
```
[Error - 3:25:32 PM] Request textDocument/hover failed.
Error: The received response has neither a result nor an error property.
	at handleInvalidMessage (C:\Users\Aurelien Pupier\.vscode\extensions\apache-camel.vscode-apache-camel-0.0.1\node_modules\vscode-jsonrpc\lib\main.js:511:40)
	at processMessageQueue (C:\Users\Aurelien Pupier\.vscode\extensions\apache-camel.vscode-apache-camel-0.0.1\node_modules\vscode-jsonrpc\lib\main.js:261:17)
	at Immediate.<anonymous> (C:\Users\Aurelien Pupier\.vscode\extensions\apache-camel.vscode-apache-camel-0.0.1\node_modules\vscode-jsonrpc\lib\main.js:242:13)
	at runCallback (timers.js:672:20)
	at tryOnImmediate (timers.js:645:5)
	at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by rcjsuen** [comment]
@apupier Your response doesn't have a `result` parameter.
```
console.ts:123 [Extension Host] Received message which is neither a response nor a notification message:
{
    "jsonrpc": "2.0",
    "id": "1"
}
```
According to the [specification](https://github.com/Microsoft/language-server-protocol/blob/dc229c160f71dec8c563e5014cc4af2f6f4f8d2d/specification.md), the result can be omitted if it's an error. Since you're not sending an error back, you need to include the `result` parameter in your response message.
```TypeScript
interface ResponseMessage extends Message {
	/**
	 * The request id.
	 */
	id: number | string | null;

	/**
	 * The result of a request. This can be omitted in
	 * the case of an error.
	 */
	result?: any;

	/**
	 * The error object in case a request fails.
	 */
	error?: ResponseError<any>;
}
```

**Comment by apupier** [comment]
> Since you're not sending an error back, you need to include the result parameter in your response message.

If I understand well the JSon answer should contains the "result" with a null value?How to represent it?
```
{
    "jsonrpc": "2.0",
    "id": "1",
"result": null
}
```
It will work with all types?
It is to be able to report the issue to LSP4J project to which the protocol handling is delegated.

**Comment by rcjsuen** [comment]
> If I understand well the JSon answer should contains the "result" with a null value?How to represent it?

Here is an example of a request and a response.
```JavaScript
{
  "jsonrpc": "2.0",
  "id": 6,
  "method": "textDocument/hover",
  "params": {
    "textDocument": {
      "uri": "inmemory://model.json"
    },
    "position": {
      "line": 32,
      "character": 6
    }
  }
}
```
```JavaScript
{
  "jsonrpc": "2.0",
  "id": 6,
  "result": null
}
```
> It will work with all types?

It should if it is supported.

> It is to be able to report the issue to LSP4J project to which the protocol handling is delegated.

I think you should talk to the LSP4J team to see what's going on with their JSON-RPC code.

**Comment by dbaeumer** [comment]
@rcjsuen thanks for jumping in. The JSON RPC spec defines that a response must either have a result or an error. It can't miss both. A valid result value is 'null'.

**Comment by dbaeumer** [comment]
I will close the issue since IMO there is nothing the protocol has to change.
