### ISSUE TITLE
trigger rename on workspace/applyEdit?

### ISSUE THREAD

**Issue by willt** [Microsoft/vscode-languageserver-node#313]
I'm trying to figure out how to trigger a rename after a `workspace/applyEdit` request. I'd like to be able to do this for extracting variables and methods. My thought was the language server would send the applyEdit back using a temporary name for the variable or method and then client would select the temporary name and run `editor.action.rename` so the user can choose the name of their variable or method.

I was thinking something like this but im not sure if im on the right track or not.

    languageClient.onReady().then(() => {
        languageClient.onRequest('workspace/applyEdit', params => {
            return Workspace.applyEdit(languageClient.protocol2CodeConverter.asWorkspaceEdit(params.edit)).then(
                (value) => {
                    vscode.window.activeTextEditor.revealRange(new vscode.Range(), vscode.TextEditorRevealType.Default);
                    vscode.commands.executeCommand('editor.action.rename');
                    return { applied: value};
                });
        });
    });

**Comment by dbaeumer** [comment]
Actually that should work. Have you tried it?

**Comment by willt** [comment]
I believe the applyEdit works but the rename command doesn't fire. I haven't had a chance to look at it in a few days so I can do that and report back. I just wasn't sure if that was the right way to do it or not.
Should I test `value` for true before running the rename command?

**Comment by dbaeumer** [comment]
Yes, since it signals whether the edit was applied successful.
