### ISSUE TITLE
don't get documentHighlight request if another language server responds

### ISSUE THREAD

**Issue by martinlippert** [Microsoft/vscode-languageserver-node#318]
I am running my own language server side by side with the Java language server (from Red Hat), bot working on Java source files. But it looks like I am not getting all `document/highlight` requests from the client in that setting.

It looks to me like as soon as the Java language server delivers document highlights for a certain position to the client, by language server doesn't even get the request anymore. If the Java language server doesn't deliver highlights, then my language server is being asked.

That sounds like a bug to me, I think all registered language servers should be asked for document highlights (and the result merged), but maybe I am also doing something wrong. Therefore looking for help here... :-)

Any idea what might be causing this behavior?

**Comment by rcjsuen** [comment]
It certainly sounds like a bug from an API point of view on VS Code's part.

```TypeScript
/**
 * Provide a hover for the given position and document. Multiple hovers at the same
 * position will be merged by the editor. A hover can have a range which defaults
 * to the word range at the position when omitted.
 */
provideHover(model: model.ITextModel, position: Position, token: CancellationToken): Hover | Thenable<Hover>;
```

https://github.com/Microsoft/vscode/blob/c65b881d16d7c42c819ba12686a3afd93403fb6c/src/vs/editor/common/modes.ts#L241-L246

**Comment by martinlippert** [comment]
@rcjsuen the pointer refers to `provideHover`, not `documentHightlight`, the documentation for that one doesn't say anything about multiple providers.

**Comment by rcjsuen** [comment]
@martinlippert Yeah, sorry. I edited my post. :(

**Comment by martinlippert** [comment]
For my case, the same behavior than for document symbols would be much better. At the moment I totally depend on some internals (the Java language server returning some stuff or the ordering of the servers on the client side). Hmmm...

**Comment by rcjsuen** [comment]
Anyway, from VS Code's standpoint the API is honoured.

From an LSP point of view though I don't necessarily disagree with what you say about merging all of the results together. It's when things overlap that it gets weird from a presentation point of view. If one server returns highlighting of `[ab]c` but the other returns a highlight of `a[bc]` then does the client just "mega highlight" `[abc]`?

**Comment by rcjsuen** [comment]
What's going on in LSP4E? Is it sending `textDocument/documentHighlight` requests to all the servers?

**Comment by martinlippert** [comment]
Hm, I think a simple solution would be to just highlight all ranges that you get back, independent of a potential overlap among them. I agree that this could cause some weird presentations, but as long as people are careful when implementing the highlight server part, this should work.

Of course you could think about presenting each provider slightly different on the UI side, so that users would be aware of different highlights, but I would not go down that path right away. Could cause weird presentation issues, too.

**Comment by martinlippert** [comment]
Another solution would be some kind of ranking among the providers, but I am not a big fan of those rankings either.

**Comment by martinlippert** [comment]
LSP4E seems to ask all language servers, but doesn't merge results. From looking at the code it seems like the last one wins and removes the previous results.

**Comment by dbaeumer** [comment]
I think this needs to be clarified in the specification. IMO VS Code definition of taking the first is not a bad choice. Asking more than on document highlight provider with results might cause some UI challenges.

**Comment by rcjsuen** [comment]
If the specification is going to make any claims about this then I think we need to move this discussion to the [Microsoft/language-server-protocol repository](https://github.com/Microsoft/language-server-protocol) to get some more input.

**Comment by martinlippert** [comment]
@dbaeumer Sounds good to me (from the general perspective of the protocol), but my language server heavily depends on multiple language servers running for the same language / file types. So I very much hope for VS Code to continue its support for this use case... :-)

Having said that, I still don't know exactly how to proceed with my desire to send document highlight information from my language server to the client (VSCode) and let the client show them even if there are additional highlights from others. From your explanation, it is totally up to the client whether to support this or not (happy with that). But is there a chance to get support for multiple document highlight results being taken into account by the VS Code client?

**Comment by dbaeumer** [comment]
@martinlippert yes, if VS Code itself supports it. You would see exactly the same behavior if the extension would directly contribute the hover provider. Can you open an issue against VS Code and then we can discuss whether and how we can improve this.

**Comment by dbaeumer** [comment]
Closing as suggested.

**Comment by martinlippert** [comment]
@dbaeumer submitted the referenced issue to VS Code for this. Thanks for the feedback.
