### ISSUE TITLE
Add documentation about non-enumerable properties

### ISSUE THREAD

**Issue by mattacosta** [microsoft/vscode-languageserver-node#325]
**Summary:**
When implementing the LSP using classes, non-enumerable properties are not converted to JSON. Add documentation that these classes must implement `toJSON()` in order to be stringified correctly.

Example:
```ts
import {
  ServerCapabilities as ServerCapabilitiesInterface
} from 'vscode-languageserver';

export class ServerCapabilities implements ServerCapabilitiesInterface {

  protected _textDocumentSync: 0 | 1 | 2 = 1;

  public get textDocumentSync() {
    return this._textDocumentSync;
  }

}
```

**Actual**
`{ _textDocumentSync: 1 }`

**Expected:**
`{ textDocumentSync: 1 }`

**Comment by dbaeumer** [comment]
@mattacosta these interfaces are literal type definitions and not supposed to be implemented. I will add a comment to the interfaces. As said in the specification the protocol is JSON RPC so all transferred data must be JSON and not classes (which aren't supported in JSON).
