### ISSUE TITLE
Errors from rename still not shown in VSCode

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode-languageserver-node#329]
Rename errors passed from a language server still don't seem to reach VSCode. Original issue: https://github.com/Microsoft/vscode-languageserver-node/pull/220. This is using 1.21.0 and vscode-languageclient 4.0.0:

![](https://i.imgur.com/uGNgcAr.png)

I'm not sure which of the two is at fault, but this error shows up in the dev console after a failed rename:

![](https://i.imgur.com/XomZj5i.png)

The example from https://github.com/Microsoft/vscode/issues/37808 seems to work as expected.

________

The issue can easily be reproduced outside of the Haxe extension by making some adjustments to the lsp-sample:

https://github.com/Gama11/vscode-extension-samples/commit/1280db4df548273bef8ba1d9beb1115c611a2ba5

![](https://i.imgur.com/9EanOd5.png)

**Comment by dbaeumer** [comment]
See also https://github.com/Microsoft/vscode/issues/37808

**Comment by Gama11** [comment]
Not sure what you mean? I already linked to that issue:

> The example from Microsoft/vscode#37808 seems to work as expected.

**Comment by dbaeumer** [comment]
That was for me :-)
