### ISSUE TITLE
Initialisation exceptions swallowed

### ISSUE THREAD

**Issue by nwolverson** [Microsoft/vscode-languageserver-node#330]
I just had trouble diagnosing a `LanguageClient` which did not resolve or reject the `onReady` promise, and I could not find an exception noted anywhere.

Similar to [this issue](https://github.com/Microsoft/vscode-extension-samples/issues/45#issuecomment-358378696) - there was an exception in `initializeFeatures` https://github.com/Microsoft/vscode-languageserver-node/blob/020764e3eacc76138ffbf63f09489adbfb9e1be8/client/src/client.ts#L2614 

Is this as simple as moving `then(..., ...)` to `then(...).catch(...)` ?

**Comment by dbaeumer** [comment]
@nwolverson thanks. Since VS Code's Thenable interface doesn't offer a catch I changed it to `then(...).then(undefined, ....)`.
