### ISSUE TITLE
The two-argument form of connection.sendRequest mishandles its params

### ISSUE THREAD

**Issue by rictic** [Microsoft/vscode-languageserver-node#334]
With vscode-languageserver v4.0.0, the following minimized test passes:

```typescript
import {Duplex} from 'stream';
import {InitializeParams, InitializeRequest} from 'vscode-languageserver-protocol';
import {createConnection} from 'vscode-languageserver';
import URI from 'vscode-uri';

class TestStream extends Duplex {
  _write(chunk: string, _encoding: string, done: () => void) {
    this.emit('data', chunk);
    done();
  }

  _read(_size: number) {
  }
}

suite('vscode languageserver initialization', () => {

  test.only('works', async() => {
    const up = new TestStream();
    const down = new TestStream();
    const serverConnection = createConnection(up, down);
    const clientConnection = createConnection(down, up);
    serverConnection.listen();
    clientConnection.listen();

    const init: InitializeParams = {
      rootUri: URI.file(process.cwd()).toString(),
      processId: 1,
      capabilities: {},
      workspaceFolders: null,
    };
    await clientConnection.sendRequest(InitializeRequest.type, init);
  });

});

```

In v4.1.1 it fails with the following error:

```
     Error: Request initialize failed with message: Cannot read property 'workspace' of undefined
      at new ResponseError (node_modules/vscode-jsonrpc/lib/messages.js:46:28)
      at handleResponse (node_modules/vscode-jsonrpc/lib/main.js:430:48)
      at processMessageQueue (node_modules/vscode-jsonrpc/lib/main.js:258:17)
      at Immediate.<anonymous> (node_modules/vscode-jsonrpc/lib/main.js:242:13)
```

What appears to be happening is that the `InitializeRequest` handler in main.ts ([link](https://github.com/Microsoft/vscode-languageserver-node/blob/4beceaf18bec7a29f217fa544ccaa465bc3244d9/server/src/main.ts#L1649)) expects `params` to be an `InitializeParams` but it appears to be `[InitializeParams, undefined]`, so accessing `params.capabilities.workspace` throws.

A quick `git bisect` suggests that the commit that introduced the break is 4beceaf18bec7a29f217fa544ccaa465bc3244d9 where it looks like `...params` was changed to just `params` in a couple of places, which seems a likely culprit.

A workaround is to add an explicit CancellationToken argument to the `sendRequest` invocation:

```typescript
    await clientConnection.sendRequest(InitializeRequest.type, init, CancellationToken.None);
```

**Comment by rictic** [comment]
It appears as though this is not specific to InitializationRequest

**Comment by dbaeumer** [comment]
Thanks. I will have a look right now. I know I changed something here for TS 2.8.1 support.

**Comment by dbaeumer** [comment]
Pushed 4.1.2 and added tests (based on yours) to cover that

**Comment by rictic** [comment]
Thanks!
