### ISSUE TITLE
some types don't have a factory function

### ISSUE THREAD

**Issue by justinwilaby** [microsoft/vscode-languageserver-node#335]
Since interface definitions are wholly useless for JavaScript users, please consider providing concrete Object Models or namespaces that can be constructed and serialized properly to JSON for those who do not wish to use TypeScript. This would allow JS users to take better advantage of type based intellisense and autocompletion, cmd+click capabilities and typed doc block annotations. 

The change is trivial:

```js
 export interface Hover {
  //...
}
```
Would become:
```js
export class Hover {
// ...
}
```
This would allow a JS developer to import the `Hover` class and use it directly.
```
const {Hover} = require('vscode-languageserver-types');

async onHover(event) {
    const {position, textDocument} = event;
    const {uri} = textDocument;
    const document = this.openDocuments[uri];
    return await getHoverInfo(position, document);
  }

async getHoverInfo(position, document) {
  // Do stuff, then
  const hover = new Hover(); 🚀
  hover.contents = 'Provides support for non TypeScript users');
  return hover;
}
```

**Comment by aeschli** [comment]
The use of interfaces for the APIs is on purpose. 
Any object that has the required properties is qualified to represent the object. The use of classes force you to build class hierarchies, instantiate the specific object, forcing a runtime dependency to vscode-languageserver-node.

To have more convenience creating an object: We have already factory functions, e.g. for Position: https://github.com/Microsoft/vscode-languageserver-node/blob/ce3483119b72a751c28da4c5d578a0149011e130/types/src/main.ts#L48:

I see we miss one for Hover, we should add that.

**Comment by justinwilaby** [comment]
Still no good for JS developers since the shape of the `Position` object in not known nor can it be inferred by most IDEs without a prototype.

For example, a typical JS editor other than VSCode will produce something similar to this:

```js
const {Position} = require('vscode-languageserver-types');

const pos = Position.create(); // <--- unknown method 'create' - Collision with interface definition
pos.line <--- unknown property "line"
pos.character <--- unknown property "character"

const position = new Position(); // <--- error Position is not a constructor
Object.getPrototypeOf(Position) // {} <--- empty object with no properties
Object.keys(Object.getPrototypeOf(Position)) // [] <--- empty array - Should be ["line", "character"] for the editor to pick up the properties
Object.keys(Position) // ["create", "is"] <---- all statics but no "line" or "character"

/**
* A doc block example
* @return {Position} <--- unknown type "Position"
*/
function getPositionOfSomething() { // <--- Function never returns Position
  //...
  return {line:3, character:12};
}
```
Without classes that define the shape of these objects within their prototype, JS users are completely left in the dark. No intellisense, no autocomplete, errors and warnings everywhere. The experience is similar to casting absolutely everything as `{}` or `any` in typescript. 

Something like 
```js
class Position {
  constructor(line, character) {
    this.line = line;
    this.character = character;
  }
}
```
is enough to provide JS users with a clearly defined object shape while still allowing developers to opt-in to using classes in TypeScript

**Comment by aeschli** [comment]
Isn't this a limitation of the editor? Also from `return {line:3, character:12};` you can infer type information and e.g. the JavaScript support in VSCode is able to do that. In addition to that, the JavaScript support is also able to use the d.ts files.

**Comment by justinwilaby** [comment]
Yes it is. VSCode and VS are likely the *only* editors that will work since it looks for `.d.ts` files (and even complains when they do not exist for JS only projects). Broader editor support would require the notion that no TS plugins will be available.

I suppose this system is great if the assumption is that all developers consuming this library will be using VSCode and TypeScript. Probably a safe assumption since indeed this is a tooling library for creating extensions on the platform and most MS heroes will have a strong preference for TS.  I suppose I'm looking out for the Atom and Notepad++ Jedi Knights out there 😄 On the other hand, Jedis have no need for code completion and intellisense 😆

**Comment by felixfbecker** [comment]
The method we used for years to hint properties of objects to editors - before classes even existed - was JSDoc. I would be surprised if the editors you are talking about supported classes but not JSDoc. JSDoc had ways to define interfaces that could be used in `@return` annotations iirc. That would probably solve your problem.

**Comment by dbaeumer** [comment]
@aeschli is this still something you consider. Otherwise please close as out of scope.
