### ISSUE TITLE
Node.js 8 causes Travis CI builds to fail with cross-package dependencies

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/vscode-languageserver-node#337]
The current `.travis.yml` uses symbolic links so that the new features introduced in `types` or `protocol` can be used in `client` and/or `server`.

https://github.com/Microsoft/vscode-languageserver-node/blob/8821046a0c20a100da3c9f9ea67436cd34ca8280/.travis.yml#L22-L29

However, as of npm 5 in Node.js 8, these symlinked folders in `node_modules` are getting wiped and replaced by what's in the npm registry. See npm/npm#17287.

This makes new proposals and features impossible to test in CI because the `client` and `server` packages will end up using the "old" `types` and `protocol` from the registry instead of the new stuff that's been added in the repository.

**Comment by dbaeumer** [comment]
I think we should do the following:

- remove the install section.
- add npm scripts to link and base it on `shx` node module. This module is already used in the client lib. We only need to move it up.

**Comment by dbaeumer** [comment]
Alternatively we could check if we could switch to yarn.

**Comment by rcjsuen** [comment]
I've opened #338 which incorporates Dirk's [initial suggestion](https://github.com/Microsoft/vscode-languageserver-node/issues/337#issuecomment-381129384) (instead of switching to yarn).

**Comment by dbaeumer** [comment]
I merged the PR. Closing.
