### ISSUE TITLE
ResponseError.data may be undefined

### ISSUE THREAD

**Issue by nikeee** [Microsoft/vscode-languageserver-node#340]
In [`jsonrpc/src/messages.ts`](https://github.com/Microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/messages.ts#L82-L94):

```TypeScript
export class ResponseError<D> extends Error {

	public readonly code: number;
	public readonly data: D;

	constructor(code: number, message: string, data?: D) {
		super(message);
		this.code = is.number(code) ? code : ErrorCodes.UnknownErrorCode;
		if (data !== void 0) {
			this.data = data;
		}
		Object.setPrototypeOf(this, ResponseError.prototype);
	}
	// ...
```

In the ctor, `data` is of type `D | undefined` and is only assigned to `this.data` if it is not `undefined`. If I read this correctly - does this mean that if `data?: D` is not passed, `this.data` also remains undefined? The spec says about [`interface ResponseError<D>`](https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#response-message) that the `data` can also be undefined.

When compiling with `strictPropertyInitialization`, this is also marked as an error.

There are also several compiler errors in `server/src/main.ts`, e.g. in [_RemoteWorkspaceImpl](https://github.com/Microsoft/vscode-languageserver-node/blob/master/server/src/main.ts#L812-L842) which actually does not check `this._connection` before `this._connection.sendRequest`, but does check in `get connection()`.

I'd file a small PR of these things, if this is considered a problem.

**Comment by dbaeumer** [comment]
I have to admit that I never compiled with `strictPropertyInitialization` so there might be issues with it. In the above mention cases, data can be undefined and therefore the property must be declared as `D | undefined`.

PR is welcome.

**Comment by nikeee** [comment]
Besides PR #341, I created a separate branch for some initialization issues.

You can compare it here:
https://github.com/Microsoft/vscode-languageserver-node/compare/master...nikeee:strictPropertyInitialization?expand=1

You can review it, if you want. I added some assignment assertions (`!`), on some places, where the type system could not guarantee the existence of a field/variable. These locations might reveal some bugs.

There is also `ProtocolCompletionItem.documentationFormat` which might be not initialized when used in the [codeConverter.ts](https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/codeConverter.ts#L306-L310). I did not add any assertions, because I could not find any hint that it is getting assigned properly - maybe you can.

If it fits your standards and expectation, I'd create a PR for that.

**Comment by dbaeumer** [comment]
@nikeee thanks for working on this. A couple of comments:

- for types that have a JS falsify value I would not make the variable optional. I would always assign the falsify value. So for example a boolean shouldn't be optional.
- for properties please don't make them optional. Instead or 'undefined'. This makes it clear in the constructor that there is a property but that currently undefined is assigned. 

Because of the (!) I sometimes regret having moved to strict checking :-). If possible please look if you can restructure the code. For example in closures you can have the value assigned to a const which avoids using !

**Comment by nikeee** [comment]
I updated the stuff you commented on.

> If possible please look if you can restructure the code.

I originally intended not to change the actual behaviour of the running program. However, I don't like these assertions as well, so I'll see if some parts can be restructured somehow.
