### ISSUE TITLE
Possible regression with hover provider

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode-languageserver-node#344]
I recently upgraded a plugin's languageserver-client to v4, and observed this change:

in v3
![2018-05-03 1](https://user-images.githubusercontent.com/760112/39565173-a23a9486-4ed4-11e8-9206-7461f6de04b0.png)

in v4
![2018-05-03](https://user-images.githubusercontent.com/760112/39565178-a6c558ec-4ed4-11e8-8e14-378b4e73e968.png)

There are two hover items, and they earlier had a border between different items. Now, all items are merged into one string. 

This is due to the `asHoverContent()` merging all values of an array of items into one markdown string: https://github.com/Microsoft/vscode-languageserver-node/blob/e9685db42b8813b9aec70b24a70dfbb8cd0d4379/client/src/protocolConverter.ts#L206-L209

The reason I liked the earlier behaviour is because it split the content being hovered and it's *documentation* in visually separate areas. Now, it's a little difficult to make out where the *documentation* starts.

Is this change a regression, or deliberate?

**Comment by dbaeumer** [comment]
This is a regression and is tracked here: https://github.com/Microsoft/vscode-languageserver-node/issues/328

**Comment by kumarharsh** [comment]
Okay. Good to see it's tracked 👍  I thought that issue was related to something else, as the linked lines are probably not the correct ones.
