### ISSUE TITLE
Unhandled methods by language client

### ISSUE THREAD

**Issue by janos-ss** [Microsoft/vscode-languageserver-node#345]
When I call methods from a language server (LSP4J), the client responds with "unhandled method", for example:

Request for workspace folders:
```
{
  "jsonrpc": "2.0",
  "id": "14",
  "method": "workspace/workspaceFolders",
  "params": null
}
```

Response:
```
{
  "jsonrpc": "2.0",
  "id": "14",
  "error": {
    "code": -32601,
    "message": "Unhandled method workspace/workspaceFolders"
  }
}
```

Request for configuration:

```
{
  "jsonrpc": "2.0",
  "id": "13",
  "method": "workspace/configuration",
  "params": {
    "items": [
      {
        "scopeUri": "file:///path/to/example-js/src/main.js",
        "section": "sonarlint"
      }
    ]
  }
}
```

Response:
```
{
  "jsonrpc": "2.0",
  "id": "13",
  "error": {
    "code": -32601,
    "message": "Unhandled method workspace/configuration"
  }
}
```

I tried to follow the [lsp-multi-root-sample](https://github.com/Microsoft/vscode-extension-samples/tree/master/lsp-multi-root-sample) closely, using a custom middleware, but I get the same result.

What am I doing wrong? The only difference I see from the example that works is that I'm using LSP4J server. But I don't see how the problem can be at server side, because the JSON payload from the server side looks correct.

At the client side I'm using `vscode-languageclient` version 3.5.1, I call `registerProposedFeatures()`, and at the server side I can see that the client capabilities include workspace folders and configuration support, that is:

```
    "capabilities": {
      "workspace": {
        "applyEdit": true,
        "didChangeConfiguration": {
          "dynamicRegistration": true
        },
        "didChangeWatchedFiles": {
          "dynamicRegistration": true
        },
        "symbol": {
          "dynamicRegistration": true
        },
        "executeCommand": {
          "dynamicRegistration": true
        },
        "workspaceFolders": true,
        "configuration": true
      },
```

The source code of my VSCode extension is [here][1], and the [package.json is here][2].

[1]: https://github.com/SonarSource/sonarlint-vscode/blob/repro/unhandled-method/src/extension.ts
[2]: https://github.com/SonarSource/sonarlint-vscode/blob/repro/unhandled-method/package.json

**Comment by dbaeumer** [comment]
The corresponding API graduated and is now official in the latest version of the libraries. Can you please use the latest versions to ensure that possible bugs get fixed there.

I also updated the example to use the latest version. Please give it another try and let me know if it works now.

**Comment by dbaeumer** [comment]
Please also not that the version of the libraries need code version 1.22 or later.

**Comment by janos-ss** [comment]
@dbaeumer Thanks for updating the example. I updated to the same versions in [another repro branch](https://github.com/SonarSource/sonarlint-vscode/tree/repro/unhandled-method2). I still get the same unhandled method response.

Not sure it's relevant, there is a difference in behavior: after the first unhandled method call (`workspace/configuration` or `workspace/workspaceFolders`, whichever), the server process gets shutdown from the client side. I see these messages on the console:
```
{
  "jsonrpc": "2.0",
  "method": "exit",
  "params": null
}
rejected promise not handled within 1 second
```

With the previous branch of the client (before updating versions), the same server program continues to run. (That's not important for me, I'm just mentioning this observation.)

Thanks @rcjsuen for the tip. So the above repro branch uses version 4.x. I didn't have time yet to debug deeply.
