### ISSUE TITLE
What is the well property name for ColorPresentationParams:  color or colorInfo?

### ISSUE THREAD

**Issue by angelozerr** [Microsoft/vscode-languageserver-node#348]
I'm trying to consume `ColorPresentationParams `with CSS Language Server with LSP4j and it crashes because LSP4j defines` ColorPresentationParams#colorInfo` like defined in the specification https://microsoft.github.io/language-server-protocol/specification#color-presentation-request-leftwards_arrow_with_hook although in TypeScript you define ` ColorPresentationParams#color` https://github.com/Microsoft/vscode-languageserver-node/blob/eca5fd2f23529315d53b9dad98377fb968ceba56/protocol/src/protocol.colorProvider.ts#L76

Where is the error? In the specification or TypeScript implementation? Thanks for your clarification.

**Comment by dbaeumer** [comment]
@aeschli can you please comment.

**Comment by aeschli** [comment]
That's a bug in the spec. It's `color`
