### ISSUE TITLE
ColorServerCapabilities colorProvider should accept boolean too?

### ISSUE THREAD

**Issue by angelozerr** [Microsoft/vscode-languageserver-node#349]
The declaration of `ColorServerCapabilities#colorProvider`  https://github.com/Microsoft/vscode-languageserver-node/blob/eca5fd2f23529315d53b9dad98377fb968ceba56/protocol/src/protocol.colorProvider.ts#L39 doesn't accept a simple boolean (the specification says that too), but the CSS, HTML, JSON Language Server returns a simple boolean 

`colorProvider : true`

In my case I cannot consume CSS, HTML, JSON Language Server  with LSP4j which doesn't accept a boolean for colorProvider. Could you give me clarification about the use of this boolean please (is an error of CSS, HTML, JSON Language Server or a miss of specification?) Thanks!

**Comment by dbaeumer** [comment]
@aeschli can you please comment.

**Comment by aeschli** [comment]
Boolean is fine for the color provider too, so I added it to the spec.

I change our code to use `{}` in the meantime.
