### ISSUE TITLE
Telemetry support in protocol

### ISSUE THREAD

**Issue by sridmad** [Microsoft/vscode-languageserver-node#35]
Most language services will most probably be interested in the following.

* Requests routed to the extension and the number of each request routed to it based on user action
* Number of responses from language service that were discarded due to various reasons (user cancellation, context changes etc)

* Ability for the language service to log Additional telemetry information like average time tp process each request, number of files it dealt with etc.

Ask

1. In the language server client, automatically log stats about requests sent to the language server as well as stats about responses that were discarded

2. Add a way for server send back telemetry data to client that is automatically logged

3. Extension request telemetry and pass in their key when initializing the client

All of these can be done by each extension but having a standard mechanism will all uniformity across extensions.

**Comment by dbaeumer** [comment]
Good idea to extend the protocol to send telemetry from the server to the client. However I think the client shouldn't automatically log these since it can't know the end point to log to. Each extension could have its own telemetry server. So what we need to do is to all the extensions to plug a telemetry logger into the client.

**Comment by dbaeumer** [comment]
I extended the protocol and the client. To make use of it you can on the client side add a telemetry listener.

client.onTelemetry((data) => {
});

On the server you can send a telemetry notification. The Notidifcation is defined as follows:

```ts
export namespace TelemetryEventNotification {
	export let type: NotificationType<any> = { get method() { return 'telemetry/event'; } };
}
```
