### ISSUE TITLE
CompletionItem data is not preserved between onCompletion and resolve if 0

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode-languageserver-node#351]
`CompletionItem.data` is supposed to be preserved between the `textDocument/completion` and `completionItem/resolve` requests, but if its value is `0`, this is not the case:

![](https://i.imgur.com/pxItgxu.png)

I modified the lsp-sample to demonstrate the problem (tested with vscode-languageclient 4.1.3):
- https://github.com/Gama11/vscode-extension-samples/commit/169b5f19c35f446860ffc8b8f9b97e9dd14f7810

This should either be fixed or at least be documented appropriately. For now this can be worked around by creating a wrapper object (`data: {index: 0}`).
____________

**Background:** in the Haxe Language Server, we ran into an issue where after implementing `completionItem/resolve`, the first item in the list didn't show any documentation and threw an error regarding `data` being `undefined` in the output channel. We were using `data` to store the `index` the item had when it's returned to us from the Haxe compiler, so we can request more info on that item in resolve.

**Comment by dbaeumer** [comment]
Good catch.
