### ISSUE TITLE
Fails to find Content-Length header in `textDocument/definition` response

### ISSUE THREAD

**Issue by Phrohdoh** [Microsoft/vscode-languageserver-node#353]
I am working on a LS written in Rust that is not open-source (so I cannot share the entire project).

The server and client are communicating over stdin/stdout.

The initialization flow works just fine (i.e. vscode does not error at all).

When the client sends any `textDocument/definition` request the server responds with the following hard-coded data (sans message ID which matches the req):

```
Content-Length: 179

{"id":1,"jsonrpc":"2.0","result":{"range":{"end":{"character":2,"line":1},"start":{"character":1,"line":1}},"uri":"file:///home/thill/src/games/openra/mods/ra/rules/player.yaml"}}
```

Note that the  *Content-Length header is present*.

When VSCode gets this response I see the following errors in the console of the ext dev host:

```
[Phrohdoh.orasdk]Header must provide a Content-Length property.
```

```
Error: Header must provide a Content-Length property.
	at StreamMessageReader.onData (/home/thill/src/tools/oraide/node_modules/vscode-jsonrpc/lib/messageReader.js:200:27)
	at Socket.<anonymous> (/home/thill/src/tools/oraide/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
```

### Versions

`vscode-languageclient`: `^4.1.4`

`engines.vscode`: `^1.23.0`

**Comment by Phrohdoh** [comment]
@rcjsuen suggested adding some `console.log` calls into `node_modules/vscode-jsonrpc/lib/messageReader.js` so I have done that.

In `MessageBuffer.prototype.tryReadHeaders` I've added:

```diff
        result = Object.create(null);
        var headers = this.buffer.toString('ascii', 0, current).split(CRLF);
        headers.forEach(function (header) {
+           console.info(header);
            var index = header.indexOf(':');
            if (index === -1) {
```

For the init flow I see:

```
[Extension Host] Content-Length: 78 (at /home/thill/src/tools/oraide/node_modules/vscode-jsonrpc/lib/messageReader.js:66:21)
```

Which verifies that it has the required header and that this module reads it.

And for the go-to-def response I see:

```
[Extension Host] Content-Length: 78 (at /home/thill/src/tools/oraide/node_modules/vscode-jsonrpc/lib/messageReader.js:66:21)
```

Which means this module **also** reads this header but it doesn't match the expected format, I suspect.

---

Upon further inspection it appears that, in this very particular scenario, the header is `\nContent-Length: 179` so this is an error in my server I bet.

---

In that case I will close this ticket, sorry for the noise.

**Comment by Phrohdoh** [comment]
Would it be feasible to trim the header key in `messageReader.js` before storing it to prevent further issues such as this?

**Comment by rcjsuen** [comment]
> Would it be feasible to trim the header key in `messageReader.js` before storing it to prevent further issues such as this?

I would vote for providing a more verbose error message instead. If the jsonrpc library could include the received data in the error message somehow it would make debugging a lot easier.

**Comment by dbaeumer** [comment]
Having a more verbose error message makes sense to me.
