### ISSUE TITLE
A question，when would be command in CompletionItem get used?

### ISSUE THREAD

**Issue by chemzqm** [Microsoft/vscode-languageserver-node#359]
> An optional [command](#Command) that is executed *after* inserting this completion. *Note* that additional modifications to the current document should be described with the [additionalTextEdits](#CompletionItem.additionalTextEdits)-property.

I need a scene, so I could test it.

Thanks.

**Comment by rcjsuen** [comment]
See #201.

**Comment by dbaeumer** [comment]
OK to close.
