### ISSUE TITLE
When comletion item 'mainEdit' is a deletion, it is silently converted to an insertion

### ISSUE THREAD

**Issue by kdvolder** [microsoft/vscode-languageserver-node#361]
This is an example of the kind of item that triggers this behavior:

```
{  
   "label":"foo.nested.bar.bar",
   "kind":"Field",
   "detail":"String",
   "sortText":"00000",
   "filterText":"foo.nested.bar.bar",
   "insertTextFormat":"Snippet",
   "textEdit":{  
      "range":{  
         "start":{  
            "line":5,
            "character":0
         },
         "end":{  
            "line":5,
            "character":16
         }
      },
      "newText":""
   },
   "additionalTextEdits":[  
      {  
         "range":{  
            "start":{  
               "line":3,
               "character":10
            },
            "end":{  
               "line":5,
               "character":0
            }
         },
         "newText":"\n      bar: \nother:"
      }
   ],
   "command":{  
      "title":"Move Cursor",
      "command":"sts.vscode-boot.moveCursor",
      "arguments":[  
         "file:/tmp/workingcopy7749208753331224087.yml",
         {  
            "line":4,
            "character":11
         }
      ]
   },
   "data":"1"
}
```

I think the salient detail is that in the main textEdit we have this:

```
"newText":""
```
I.e. the 'newText' field is set to a empty string.

Instead of deleting the text, as I would expect in this case, instead the completion label is being inserted. This ends up adding unwanted junk.

PS: You may be wonder why we are making 'strange' completions like this one. We have the restriction discussed here https://github.com/Microsoft/language-server-protocol/issues/92 to blame for that. Particularly our attempt to workaround it are described in one of the recent posts. If you really want to know, you can read it there: https://github.com/Microsoft/language-server-protocol/issues/92#issuecomment-395598448 Unfortunately, the workaround doesn't even work because the language client misinterprets a deletion edit and turns it into an insertion.

**Comment by kdvolder** [comment]
This just a guess on my end, but I think something is probably checking the newText for 'falsyness' in the usual javascript way. So when the text is empty string it counts as 'false'. This 'theory' is confirmed by a workaround that I use. I have changed the deletion by something that inserts as space instead. We don't really want to insert a space (so this is still unwanted 'junk') but at least the junk is 'almost invisible' so the user isn't as likely to notice and be annoyed by it. The workaround works so this pretty strong evidence that the reason it behaves this way is precisely because the newText is `""` (since everything else about the completion item is exactly the same).

**Comment by kdvolder** [comment]
PS: I filed the bug with the client, but it is also possible the 'bug' is actualy in vscode. I couldn't really determine exactly who is the blame here (I tried debugging it a bit and also did some searching in both vscode and the client source code on github but after about an hour I gave up because I wasn't getting anywhere).

**Comment by kdvolder** [comment]
> I need to craft an example to see why this is failing. One idea might be that the main and additional edits are touching.

Would it help if I provide a .vsix file with version of our extension that creates these 'weird' completion items? (Along with some instructions to invoke so it does indeed produce it) That wouldn't be too hard for me to do. Just need to checkout the right branch and build it.

**Comment by kdvolder** [comment]
I'll just assume the answer to 'would it be helpful' above is yes. 

This is the .vsix file. (Note I renamed it to .zip because github wouldn't take the attachement otherwise).
[vscode-spring-boot-0.3.1.vsix.zip](https://github.com/Microsoft/vscode-languageserver-node/files/2090923/vscode-spring-boot-0.3.1.vsix.zip)

Unfortunately there are a few steps to setup enough context to invoke the completion. First you need a simple spring-boot project. To save some hassles. I've created one and zipped it up. It also includes the a sample application.yml ready for you to invoke the CA engine:
[hello-world-service.zip](https://github.com/Microsoft/vscode-languageserver-node/files/2090937/hello-world-service.zip)

Unzip this archive. Then open vscode with the archive folder as 'workspace root'. Open the 'application.yml' file which should have this contents:

```
server:
  port: 6666
spring:
  application:
    name: bork
servad
#Put cursor at end of line before this one and invoke CTRL-space select first completion (server.address).
```
You will notice junk gets inserted right after the word 'bork'.

If no completions come, you may need to wait for the extension to obtain classpath information (from maven which may take a bit of time, depending on the state of your maven cache).

**Comment by dbaeumer** [comment]
IMO the conversion code does the right thing. I added a test here: https://github.com/Microsoft/vscode-languageserver-node/blob/master/client-tests/src/converter.test.ts#L752

@kdvolder can you please explain what you would expect?

**Comment by kdvolder** [comment]
I would expect that the text in the given example 'servadd' is deleted because the 'newText' in the textEdits is the empty string (so the text in the range should be replace with nothing. 

When I filed this bug, that was not happening, instead the text is replaced by the completion's label.

It is possible that somehow this bug already got fixed. Let me try to reproduce in a more recent vscode release.

**Comment by kdvolder** [comment]
Bug still is reproducible with the artefacts I attached. But I guess though I am using a current version of vscode :

```
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-66-generic
```

That is still using an old vscode-language-server client.  So I should find some time to try an upgraded client somehow. That is unfortunately a bit more involved as I have to upgrade our extension's ls client version. I will add this to my todo list and try to get to it soon.

BTW: I looked at your test case but I don't see where it is checking the result of applying the edit to the document.

To give you an idea of what I saw going wrong is... editor starts with this contents:

```
server:
  port: 6666
spring:
  application:
    name: bork
servad
```

We invoke content assist at the end of `servad` and select the completion with label `server.address`.

What we get after the completion is applied is:

```

```
server:
  port: 6666
  address: 
spring:
  application:
    name: borkserver.address
```

Notice that the label text was inserted after `bork`. No text should have been inserted there because the completions textEdit is the empty string. So instead the result should have been:

```
server:
  port: 6666
  address: 
spring:
  application:
    name: bork
```

**Comment by kdvolder** [comment]
I found the code that hit this bug in a 1.5 year old branch that was never merged to master (partially because of this bug really standing in the way of it working properly).

Unfortunately I cannot easily get this code to compile as is at the moment and so reproducing this bug is really rather hard for me. 

Basiscally, the feature we were trying to implement in that branch was eventually implemented in another way so that it works properly only in Eclipse. Essentially we return a main edit that encompasses all document edits and uses snippet place holders to indicate cursor position target.

In vscode it doesn't work because of the restriction on the main edit range being completly inside the 'current line'. I think you might remember us having discussions about this a long time ago.

Anyhow, as far this issue is concerned, I have no easy way today, after 1.5 years of no repsonse, to verify if it still occurs. And I don't also care that much anymore since we essentially have long given up on making the affected feature work on vscode and have instead settled for just making it work in eclipse.

I am guessing this bug does probably still occur but as I can't really try it to confirm this, feel free to close this ticket if you don't want to spend more effort on it yourself.

**Comment by dbaeumer** [comment]
Looking at this again the only problem I can see right now is the fact the the insertion format is snippet with an empty string. I have the feeling that this might cause problem when trying to delete text. Will invest into a standalone sample.

**Comment by dbaeumer** [comment]
Actually the snippet delete works as expected:

```ts
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';

// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {

	vscode.languages.registerCompletionItemProvider({ language: 'plaintext' }, {
		provideCompletionItems: () => {
			let result: vscode.CompletionItem = new vscode.CompletionItem('Snippet Delete');
			result.range = new vscode.Range(0, 0, 0, 10);
			result.insertText = new vscode.SnippetString('');
			return [result];
		}
	});
}

// this method is called when your extension is deactivated
export function deactivate() {
}
```

**Comment by dbaeumer** [comment]
Actually there is something wired since this is not working as expected:

```ts
connection.onCompletion(
	(_textDocumentPosition: TextDocumentPositionParams): CompletionItem[] => {
		// The pass parameter contains the position of the text document in
		// which code complete got requested. For the example we ignore this
		// info and always provide the same completion items.
		return [
			{
				label: 'Snippet Delete',
				textEdit: {
					range: { start: { line: 0, character: 0 }, end: { line: 0, character: 0 } },
					newText: ''
				}
			}
		];
	}
);
```

However I have no idea why this fails since this code works as expected:

```ts
	const p2c = createConverter();

	vscode.languages.registerCompletionItemProvider({ language: 'plaintext' }, {
		provideCompletionItems: () => {
			let result = p2c.asCompletionResult([{
				label: 'Snippet Delete',
				textEdit: {
					range: { start: { line: 0, character: 0 }, end: { line: 0, character: 10 } },
					newText: ''
				}
			}]);
			return result;
		}
	}); 
```

which calls the same conversion code :-(

**Comment by dbaeumer** [comment]
There is clearly something broken.

**Comment by dbaeumer** [comment]
I found it. This only happens if the server provides a resolve completion handler. When we convert the VS Code completion item back into a protocol completion item we loose information. I guess a wrong interpretation of a falsy value (e.g. '')

**Comment by dbaeumer** [comment]
Code that makes it fail:

```ts
export function activate(context: vscode.ExtensionContext) {

	const p2c = createProtocolConverter();
	const c2p = createCodeConverter();

	vscode.languages.registerCompletionItemProvider({ language: 'plaintext' }, {
		provideCompletionItems: () => {
			let result = p2c.asCompletionResult([
				{
					label: 'Snippet Delete',
					textEdit: {
						range: { start: { line: 0, character: 0 }, end: { line: 0, character: 10 } },
						newText: ''
					}
				}
			]);
			return result;
		},
		resolveCompletionItem: (item) => {
			return p2c.asCompletionItem(c2p.asCompletionItem(item));
		}
	});
}
```
