### ISSUE TITLE
Some mechanism for a file to inherit the workspace it belongs to

### ISSUE THREAD

**Issue by nrc** [Microsoft/vscode-languageserver-node#363]
I'm not clear if this is a VSCode issue or a vscode-languageserver-node issue, apologies if this is the wrong repo.

My use case is: I have a file open from a workspace, I 'jump to def' into a library, that source file is outside of the workspace folder, but the language server for the original workspace has the information for the library. Currently, VSCode doesn't forward any notifications/requests for the library file to any language server.

This happens with the Rust language server. In Rust there is no equivalent to the `node_modules` directory, library code is in a central registry. E.g., if my project (and workspace directory) is `/Users/nick/projects/foo', my code is in `/Users/nick/projects/foo/src` and libraries are in something like `/Users/nick/.cargo/registry/src/some_library`.

What I would like is that when a file is opened by vscode (c.v, the user opening a file from the folder view) and there is some file that we're coming from and the newly opened file is not otherwise part of a workspace, then the newly opened file is considered to be in the workspace of the 'from' file.

Note that adding the registry folder to a workspace is not good enough (and I don't think possible today anyway) because multiple workspaces could be using the registry.

**Comment by dbaeumer** [comment]
@nrc can you explain why this is necessary. When VS Code opens a file from `/Users/nick/.cargo/registry` an open event should be sent to the server. The server could then react appropriately. 

VS Code itself does't have such a knowledge. How would VS Code distinguish this from the user using the Open dialog and opening a random other file?

**Comment by nrc** [comment]
We use the approach of having one language server per workspace folder approach, rather than having a single language server for the whole workspace. When a file is opened that is not in any workspace folder, then it doesn't get sent to any server. We could have a 'default' server, but that would mean files getting sent to the wrong server some of the time.

> VS Code itself does't have such a knowledge.

Ah, I was hoping it did. I imagined it might have some knowledge of how the file open event was triggered, e.g., from a 'jump to def' or from a file open dialog, etc. In fact if we had that information (and in the case of jump-to-def, which file the jump came from) then we could implement what I want entirely in the client.

Is there any chance of reifying the source of a file open action? Or is the VSCode architecture not suited to that?

**Comment by dbaeumer** [comment]
Actually there is a way how you can do this for something like goto def. The VS Code language client as a middleware which allows you to intercept all message. There could record these cases and when the file opens forward it to the right server. The middleware is documented here: https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/client.ts#L411

**Comment by rcjsuen** [comment]
@nrc How do other language clients handle this problem? Or are you/they not using the concept of workspace folders in that case?

**Comment by nrc** [comment]
@rcjsuen I'm not sure. I think that having one server per folder is not common and also that jumping to files outside the folder (at least shared ones) is also not common.

**Comment by dbaeumer** [comment]
@nrc any objection to close this. IMO the client library can't provide what you are asking for.

**Comment by nrc** [comment]
Seems fine, I'll give the suggestion in your earlier a comment (thanks for that!) a spin when I have some time.
