### ISSUE TITLE
Impossible to prevent process.exit?

### ISSUE THREAD

**Issue by chrismwendt** [microsoft/vscode-languageserver-node#364]
https://github.com/Microsoft/vscode-languageserver-node/blob/6d8ddcc7c2b4f65a7861438df88d46ed4b250fca/server/src/main.ts#L1714-L1735

Is it impossible to prevent `process.exit` in `onExit`?

When using TCP streams for LSP communication to a remote language server, it would be great to be able to serve multiple clients with a single process. When the language server process is forced to exit, the only workaround I see is to somehow fork a process on every connection, which is rather difficult/impossible in Node.js.

**Comment by dbaeumer** [comment]
In node you could monkey patch `process.exit`. But I would accept a PR as well which allows the exitHandler to return a boolean to singal if process.exit should run or not.

**Comment by dbaeumer** [comment]
And please be aware that the LSP is not designed for multi tenant servers. So there might be issues, especially if two clients touch the same files.

**Comment by jonathan-spruce** [comment]
I'm having a similar issue while trying to run a Language Server in a Docker container - since the parent process is not running in the container it exits shortly after connection to the client.

**Comment by dbaeumer** [comment]
@jonathan-spruce I assume you are sending a process id from the host in the initialize request to the server running in the container. You can send `null` so that the node server doesn't do any checking. Or use a process ID that us available in the container but does never exit.

To make this official we would need to allow this in the spec.

**Comment by dbaeumer** [comment]
Actually `null` is already supported. Will update the node files.
