### ISSUE TITLE
LSP Node Client: (testing servers, proxy, other platforms support

### ISSUE THREAD

**Issue by mostafaeweda** [Microsoft/vscode-languageserver-node#365]
The default client here depends & delegates directly to `vscode` extension host API.

However, the fork here https://github.com/TypeFox/vscode-languageserver-node/tree/master/client - or [npm vscode-base-languageclient](https://www.npmjs.com/package/vscode-base-languageclient)  abstracts away `vscode` APIs - enabling it to be used in a Node environment to:
* Test LSP servers.
* Be used to proxy / route LSP messages to other servers.
* Be integrated in other platforms / editors.
* Allow remotable implementation - e.g. remote extension host API, enabling VSCode extensions to run remotely, on a devserver or docker container.

Could we adopt a similar abstraction here on this client to make sure usages are benefiting from the latest and greatest LSP support and integration points?

**Comment by dbaeumer** [comment]
@mostafaeweda the whole protocol with API to create connection is available here https://github.com/Microsoft/vscode-languageserver-node/tree/master/protocol with only node dependencies. 

We use this npm module to write mocha tests ourselve. There is even an example included that demos that running client and server code in one process. If you want to start a real server you need to spawn the process. 

The VS Code client relies on this npm module and actually does nothing more than converting types and hooking up API. Is there anything you are missing in https://github.com/Microsoft/vscode-languageserver-node/tree/master/protocol

**Comment by mostafaeweda** [comment]
@dbaeumer could you point to this demo test?

I could find easy-to-write tests here (but depends on vscode): https://github.com/Microsoft/vscode-extension-samples/blob/master/lsp-sample/client/src/test/diagnostics.test.ts

**Comment by dbaeumer** [comment]
Here is a test. This one run client and server code in one node executable.

https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol/src/test/connection.test.ts
