### ISSUE TITLE
Semantic highlighting protocol extension

### ISSUE THREAD

**Issue by kittaakos** [microsoft/vscode-languageserver-node#368]
I have started to work on a [semantic highlighting extension](https://github.com/Microsoft/vscode-languageserver-node/pull/367) of the LSP.

The semantic highlighting information is pushed from the server to the client as a notification. This notification contains the lines and the ranges where the coloring has the be applied and the desired coloring details are given as TextMate scopes.

In the reference implementation of the client, I was trying to map the TextMate scopes into the appropriate theme I can use as a decoration in the `TextEditor` decoration. How can one map the TextMate scopes into themes (and eventually `TextEditorDecorationType`) with the [current VS Code API](https://github.com/Microsoft/vscode/blob/34ba2e2fbfd196e2d6db5a4db0e42d03a97c655e/src/vs/vscode.d.ts)?

Any suggestions and feedback are welcome. Thanks!

Related issues:
 - [Support semantic highlighting (`Microsoft/language-server-protocol`)](https://github.com/Microsoft/language-server-protocol/issues/18)
 - [Proposal for (Semantic) Coloring (see #18) (`Microsoft/language-server-protocol`)](https://github.com/Microsoft/language-server-protocol/pull/124)
 - [Provide an API for advanced/semantic source highlighting (`Microsoft/vscode`)](https://github.com/Microsoft/vscode/issues/585)
 - [Add support for lexical syntax coloring (`Microsoft/language-server-protocol`)](https://github.com/Microsoft/language-server-protocol/issues/7)

Update:
 - [GH-715: Implemented the semantic highlighting support.](https://github.com/eclipse/eclipse.jdt.ls/pull/746) is a reference LS implementation in Java.
 - [GH-1845: Extended the LSP with the semantic highlighting capabilities.](https://github.com/theia-ide/theia/pull/2332) is a reference client implementation in Theia through the monaco API.

**Comment by dbaeumer** [comment]
I am closing the issue since semantic highlighting is in the upcoming 3.16 spec.
