### ISSUE TITLE
Atom IDE throwing errors

### ISSUE THREAD

**Issue by frost-byte** [Microsoft/vscode-languageserver-node#369]
No matter which ide packages I have enabled within atom, they all throw the same error. (ide-html, ide-typescript, ide-css)

I believe this problem is related to the fact that I'm using npm link in a subdirectory to reference a local package in it's parent directory.  I don't know if the directory structure is parsed by atom or by your package.

```
Error: Message header must separate key and value using :
    at C:\Users\xxxx\.atom\packages\ide-html\node_modules\vscode-jsonrpc\lib\messageReader.js:68:23
    at Array.forEach (<anonymous>)
    at MessageBuffer.tryReadHeaders (C:\Users\xxxx\.atom\packages\ide-html\node_modules\vscode-jsonrpc\lib\messageReader.js:65:17)
    at StreamMessageReader.onData (C:\Users\xxxx\.atom\packages\ide-html\node_modules\vscode-jsonrpc\lib\messageReader.js:194:43)
    at Socket.<anonymous> (C:\Users\xxxx\.atom\packages\ide-html\node_modules\vscode-jsonrpc\lib\messageReader.js:185:19)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

If I examine the contents of the buffer that is leading to the exception: I can see the following

```
<— Last few GCs —>

[13628:078B3110] 573401 ms: Mark-sweep 1076.6 (1354.8) -> 1076.5 (1354.8) MB, 801.9 / 0.2 ms allocation failure GC in old space requested
[13628:078B3110] 574240 ms: Mark-sweep 1076.5 (1354.8) -> 1076.5 (1323.3) MB, 838.6 / 0.2 ms last resort GC in old space requested
[13628:078B3110] 575071 ms: Mark-sweep 1076.5 (1323.3) -> 1076.5 (1315.3) MB, 830.5 / 0.2 ms last resort GC in old space requested

<— JS stacktrace —>

==== JS stack trace =========================================

Security context: 0EA5B091 
1: inflight [C:\Users\xxxx.atom\packages\ide-typescript\node_modules\inflight\inflight.js:~7]
[pc=389204DB](this=0E385525 ,key=576F50E9
<String[459]: readdir\x00
D:/repositories/daterangepicker/website-angular/node_modules/knockout-daterangepicker-fb/website-angular/node_modules/knockout-daterangepicker-fb/website-angular/node_modules/knockout-daterangepicker…
```

**Comment by dbaeumer** [comment]
@frost-byte the exception thrown indicates that `someone` sends a message with a malformed header. The header to be sent is explained here: https://microsoft.github.io/language-server-protocol/specification

Have you ask the Atom IDE guys for help. I am a little puzzled here?

**Comment by frost-byte** [comment]
If you look at the content of the final block of text that I pasted above, the exception is thrown because that is the content of the header; when it starts parsing the header it interprets the < as a key and expects the next character to be a : but it reads the - instead in `<- Last few GCs ->.`  I believe this might be a dump generated as a memory error - a result of recursion in a circular manner, leading to an overflow in a buffer?  Incidentally I did open an issue with atom for the package that all ide packages interact with - there are packages written for many languages and they each provide autocompletion, outlining, type resolution, and resolving docs for types.  This error is being thrown by several different ones.  If you look at the last line of my post, you’ll see a directory path being referenced in a circular manner because it appears to be following the symbolic link

**Comment by dbaeumer** [comment]
@frost-byte I am still not sure what I can do to fix this. The reason why this happens is very likely as follows:

- Atom communicates with the server using stdin / stdout using the vscode-rpc package
- either server or client writes to stdout `<— Last few GCs —> ...` which is then interpreted as a JSON RPC message which of course fails.

To avoid this the client  / server communication should happen using one of the other transports. For example Node IPC, socket, pipe, file streams, ...

But this needs to be fix in Atom which spawns the server and sets up the communication channel. 

Any objection to close?

**Comment by frost-byte** [comment]
I suppose that will be fine, it appears to be atom specific.

**Comment by dbaeumer** [comment]
OK. Closing then.
