### ISSUE TITLE
Module 'vscode' has no exported member 'CompletionList'.

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode-languageserver-node#37]
I was trying to update my linter today and while compile this error messsage came up

> node_modules/vscode-languageclient/lib/protocolConverter.d.ts(10,129): error TS2305: Module 'vscode' has no exported member 'CompletionList'.

It appears that [protocolConverter.ts](https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/protocolConverter.ts#L78) is looking for `code.CompletionList` which does not exit in my `vscode.raw.d.ts` file.

These are my dependencies:

```json
  "dependencies": {
    "vscode-languageclient": "^2.0.0",
    "vscode-set-text": "^1.0.0"
  },
  "devDependencies": {
    "typescript": "^1.8.10",
    "vscode": "^0.11.10"
  }
```

and `node ./node_modules/vscode/bin/install` is executed succesfully.

**Comment by dbaeumer** [comment]
@SamVerschueren this looks strange. You should have a vscode.d.ts file not a vscode.raw.d.ts file. Can you add the following script to you package.json file
```
"update-vscode": "node ./node_modules/vscode/bin/install"
```
and then run npm run update-vscode. This should refetch the correct vscode.d.ts file.

**Comment by SamVerschueren** [comment]
Found the problem. I had my engine specified as `0.10.x`. Updating it to `^0.10.8` fixed the issue. Found out thanks to ESLint :).
