### ISSUE TITLE
TextDocumentWillSaveEvent of vscode-languageserver-types doesn't contain waitUntil field

### ISSUE THREAD

**Issue by chemzqm** [Microsoft/vscode-languageserver-node#370]
Interface `TextDocumentWillSaveEvent` from `VSCode` contains `waitUntil` to make save wait until works, but it's missing in `vsocde-languageserver-types`

https://github.com/Microsoft/vscode-languageserver-node/blob/ca1dc1e523b90348c8c4b8af6b740087d3e00ac0/types/src/main.ts#L1912

I would like to have that feature so please consider extend it.

**Comment by dbaeumer** [comment]
@chemzqm this is only the type definition. The actual request for the LSP is defined here: https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.ts#L1219

Please be aware that the LSP is a client server model and everything is modeled as request, notification and responses. So there aren't any `method` on the interfaces.
