### ISSUE TITLE
Add 'preselect'  field to the CompletionItem

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/vscode-languageserver-node#371]
VS Code 1.25 adds new `preselect` field to the `CompletionItem`. The field allows completion providers to specify which item should be initially selected in the completion list. 

By default clients usually select first or last used items, which is limiting. A completion provider may choose to select different item based on other conditions, such as current code editor context, probability of use of certain items, and so on. 

This request is to add equivalent field to the CompletionItem structure therefore allowing use of preselection in VS Code from language servers as it is possible from the regular completion provider.

https://github.com/Microsoft/vscode/blob/9ba606df0ee5c2a386eac532771ac343a62f1985/src/vs/workbench/api/node/extHostTypes.ts

Per 
https://github.com/Microsoft/vscode/issues/35551
https://github.com/Microsoft/vscode/commit/62e0f34a3569f2cab4d16b2ef36dde285d39a9cf

**Comment by dbaeumer** [comment]
Closing the issue. I have release new client and server version that have support for this.
