### ISSUE TITLE
Trigger signature help after autocompletion

### ISSUE THREAD

**Issue by jackscott6174** [Microsoft/vscode-languageserver-node#376]
Is there currently any way to trigger signature help after we autocomplete a function name?
e.g. type `fo`, press enter to autocomplete to `foo()` and provide signature help on `foo`.

**Comment by Gama11** [comment]
You can invoke `"editor.action.triggerParameterHints"` via `CompletionItem.command`.

**Comment by jackscott6174** [comment]
Doesn't that only work for VSCode/Monaco? The specification says "The protocol currently doesn’t specify a set of well-known commands. So executing a command requires some tool extension code."

**Comment by Gama11** [comment]
Other clients could still check for the command I guess - but yeah, it seems unlikely that they do.

**Comment by rcjsuen** [comment]
@jackscott6174 I think you should raise your question in the [Microsoft/language-server-protocol repository](https://github.com/Microsoft/language-server-protocol) instead. I feel like there was an issue about creating a generic list of commands for clients to support but I can't find it.
