### ISSUE TITLE
Understanding the executeCommand workflow

### ISSUE THREAD

**Issue by sanboxrunner** [Microsoft/vscode-languageserver-node#381]
Hi, 

Apologies if this is the wrong place to ask this, but the documentation is not clear on this. I'm trying to add a command to the VSCode Command Palette (or any other similar set up). I understand that the command "lives" client side, and simply when the user invokes it, the server picks it up and can respond on executeCommand. That works fine. But I want, when the user invokes the command, for a dialogue box (similar to a Git commit asking you for your username and password) to pop up and ask for additional information.

It seems, on the face of it, to be `connection.sendRequest` but I'm unsure how to use it, and the documentation, such as it is, around it is unclear. 

Any help pointing me in the right direction would be appreciated.

**Comment by Gama11** [comment]
You might want to create some custom methods?

https://stackoverflow.com/questions/51041337/vscode-language-client-extension-how-to-send-a-message-from-the-server-to-the

**Comment by sanboxrunner** [comment]
Hmm. That's kind of unfortunate -- that *really* chains the LSP to a specific client. Thanks though!
