### ISSUE TITLE
Targeting es5 for client

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode-languageserver-node#382]
We use the client for monaco-languageclient which is targeting es5. I‘ve tried to target es6 as well but it caused issues for down-stream dependencies who has other dependencies targeting es5.

Would it be an option to target es5 instead of es6 for client?

**Comment by egamma** [comment]
(notice slower responses due to 🏖)

//CC @aeschli

**Comment by aeschli** [comment]
@akosyakov Can you explain why the monaco-languageclient wants to depend on the `vscode-languageclient`? Most of the code of the `vscode-languageclient` is about plumbing LSP types and requests to vscode types and APIs. That doesn't seem to be useful for the Monaco use case to me.

**Comment by akosyakov** [comment]
`vscode-languageclient` not only does conversions between VS Code and LSP types but also has quite a lot of code to handle a connection and different LSP features. We would like to reuse this code and provide an API similar to `LanguageClient`. We can do it by implementing a subset of VS Code APIs used by `BaseLanguageClient` instead of reimplementing the rest.

**Comment by aeschli** [comment]
Hm, didn't know about the `BaseLanguageClient`. Looking at the code I still wonder how small it would get if the vscode specific code is removed...

**Comment by akosyakov** [comment]
It should be of the same size just with Monaco types. We reuse everything from the client except `main.ts` and VS Code to LSP converters. The former is not interesting in the browser and the latter is reimplemented with Monaco specific converters.

Just to be clear: we are not interested into removing features, since Monaco + LSP is used in the sophisticated use cases as [Theia](https://github.com/theia-ide/theia) with workspace, commands and window apis, not only languages.

**Comment by akosyakov** [comment]
we switched to es6
