### ISSUE TITLE
Can't get tracing to work

### ISSUE THREAD

**Issue by glen-84** [Microsoft/vscode-languageserver-node#384]
I added a `trace.server` setting to [my extension](https://github.com/glen-84/vscode-sass-lint) (based on the tslint extension), but I'm not seeing any output in the output window when debugging.

Am I missing some code or configuration to make this work?

**Comment by Gama11** [comment]
I think the exact setting is `"<id>.trace.server"`, where `<id>` is the ID from the `LanguageClient` constructor call. It seems you're actually using the constructor overload without an ID here, not sure what ID it would use in that case:

https://github.com/glen-84/vscode-sass-lint/blob/d5e04e6fc10523aa0de971cd58954792495cc4f5/sass-lint/src/extension.ts#L144

Try something like:

```ts
const client = new LanguageClient("sass", "Sass Lint", serverOptions, clientOptions);
```

And in `settings.json`:

```json
"sass.trace.server": "verbose"
```

**Comment by glen-84** [comment]
I used:

```ts
const client = new LanguageClient("sasslint", "Sass Lint", serverOptions, clientOptions);
```

... and it works! 🎉 

Thank you so much. I will credit you when releasing the fix (tomorrow or next weekend).

**Comment by Gama11** [comment]
Haha, no need. :) Happy to hear you got it working!
