### ISSUE TITLE
Generic `BaseClient.sendNotification(string, param)` method has unexpected array results.

### ISSUE THREAD

**Issue by sanboxrunner** [Microsoft/vscode-languageserver-node#387]
Hello.

I have been attempting to send a notification to a LS like so:
```
client.sendNotification("myMethod", [param0, param1, param2]);
```
This, however, has very strange results! On my server side, doing a:
```
connection.onNotification("myMethod", (params: Array<string>) => {
    console.log(params);
})
```
outputs a string of only the first entry in the array. For now, I can get around the problem by just joining the array into a single string separated by `\n` but it's a little strange.

I can post the unaltered code (I just changed the method names and param names for simplicity) if need be.

**Comment by dbaeumer** [comment]
The LSP only uses single base types or object literals as params. There is no support for n > 1 params nor for arrays (although the underlying JSON-RPC supports this). Major reason is that it is easier to keep things backwards compatible by adding properties to literals than adding additional parameters.

**Comment by dbaeumer** [comment]
If you do the following:

```ts
	let not: NotificationType<string[], void> = new NotificationType<string[], void>('testbed/notification');
	client.onReady().then(() => {
		client.sendNotification(not, ['dirk', 'baeumer']);
	});

```

then the server correctly receives the array. If you use the method that takes a string and a single param it doesn't. For the Language client we could add code that it creates a type under the cover to handle this correctly since we know that we only support 0 or 1 param.

**Comment by dbaeumer** [comment]
Actually this needs to be fixed on the receiving side. In which language is your server implemented.

**Comment by dbaeumer** [comment]
And in TS on the receiving side:

```ts
let not: NotificationType<string[], void> = new NotificationType<string[], void>('testbed/notification');
connection.onNotification(not, (arr) => {
	connection.console.log('Is array: ' + Array.isArray(arr));
});

```

**Comment by sanboxrunner** [comment]
LS is implemented in typescript and I can see now I was not properly implementing the Notification types. Thank you, as always, for the attention and help!

**Comment by dbaeumer** [comment]
OK. Then I will close the issue since declaring the notification will fix the problem.
