### ISSUE TITLE
Organize imports support

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/vscode-languageserver-node#388]
The client should register an additional code action provider with `CodeActionProviderMetadata` including organizing imports kind if the server can provide such code actions.

It seems that LSP does not have means to communicate whether a server can provide such code actions at the moment.

**Comment by Gama11** [comment]
I have an open PR for that here: https://github.com/Microsoft/vscode-languageserver-node/pull/385

**Comment by dbaeumer** [comment]
I fixed this and published new next versions.
