### ISSUE TITLE
LanguageClient invokes dynamically registered `textDocument/didChange` more than once for each change.

### ISSUE THREAD

**Issue by NTaylorMullen** [Microsoft/vscode-languageserver-node#392]
Language servers that return dynamically registered `textDocument/didChange` events get invoked twice when being called from a `LanguageClient` implementation.

Debugged through and found that once you start the `LanguageClient` it registers its built in `textDocument/didChange` handler by calling [this](https://github.com/Microsoft/vscode-languageserver-node/blob/38dbf11c18dd8c9b40eacd9940713c13cfa43a8a/client/src/client.ts#L860). Then, once a dynamic registration for `textDocument/didChange` comes through it re-calls the same method and hits [this](https://github.com/Microsoft/vscode-languageserver-node/blob/38dbf11c18dd8c9b40eacd9940713c13cfa43a8a/client/src/client.ts#L867-L873) code path. That results in two entries in `_changeData`. Therefore, when a text document change event fires it [loops over both](https://github.com/Microsoft/vscode-languageserver-node/blob/38dbf11c18dd8c9b40eacd9940713c13cfa43a8a/client/src/client.ts#L883) change data entries and fires the same bits twice.

**Comment by dbaeumer** [comment]
@NTaylorMullen good catch. But this can only happen if you use the node language server module we provide. There is some legacy compatibility code which adds a sync capability to the server if a `TextDocument` manager is created. This legacy code should respect the users choice in the capabilities and only do this if a `textDocumentSync` capability is not provided.

Can you confirm that you are seeing the with a server implemented in node using `vscode-languageserver-node` npm module?

**Comment by NTaylorMullen** [comment]
> Can you confirm that you are seeing the with a server implemented in node using vscode-languageserver-node npm module?

No. I am seeing this while using https://github.com/OmniSharp/csharp-language-server-protocol. Here's an example output with my LanguageClient's trace set to verbose:

```
[Trace - 10:39:46 AM] Received request 'client/registerCapability - (0)'.
Params: {
    "registrations": [
        {
            "id": "245d7fe1-dc0a-4382-8e91-945a71592f2a",
            "method": "textDocument/didChange",
            "registerOptions": {
                "syncKind": 2,
                "documentSelector": [
                    {
                        "pattern": "**/*.cshtml"
                    }
                ]
            }
        },
        {
            "id": "e9d45e2a-05e0-4f6b-9db5-35eca6049502",
            "method": "textDocument/didOpen",
            "registerOptions": {
                "documentSelector": [
                    {
                        "pattern": "**/*.cshtml"
                    }
                ]
            }
        },
        {
            "id": "67626cc6-407b-4693-ba31-030173e0e5d4",
            "method": "textDocument/didClose",
            "registerOptions": {
                "documentSelector": [
                    {
                        "pattern": "**/*.cshtml"
                    }
                ]
            }
        },
        {
            "id": "04cffce2-ae13-47f0-ab88-a46527e41947",
            "method": "textDocument/didSave",
            "registerOptions": {
                "includeText": true,
                "documentSelector": [
                    {
                        "pattern": "**/*.cshtml"
                    }
                ]
            }
        },
        {
            "id": "a024a94a-d9c2-4719-9d00-c6f0ba9ccfd4",
            "method": "textDocument/completion",
            "registerOptions": {
                "resolveProvider": true,
                "documentSelector": [
                    {
                        "pattern": "**/*.cshtml"
                    }
                ]
            }
        }
    ]
}


[Trace - 10:39:46 AM] Sending response 'client/registerCapability - (0)'. Processing request took 0ms
No result returned.
```

Note the syncKind: 2 inclusion in the registration options.

**Comment by dbaeumer** [comment]
Reopening. This is strange since the client only registers the handler itself if the initialize request tells him to do so. Can you provide the result from the intialize request as well.

**Comment by NTaylorMullen** [comment]
Here's the initialization result that the LanguageClient gets. Doesn't look like the initialization is logged anywhere so had to debug into it to retrieve.

```JSON
{  
   "capabilities":{  
      "textDocumentSync":{  
         "openClose":true,
         "change":2,
         "willSave":false,
         "willSaveWaitUntil":false,
         "save":{  
            "includeText":true
         }
      },
      "hoverProvider":false,
      "definitionProvider":false,
      "referencesProvider":false,
      "documentHighlightProvider":false,
      "documentSymbolProvider":false,
      "workspaceSymbolProvider":false,
      "codeActionProvider":false,
      "documentFormattingProvider":false,
      "documentRangeFormattingProvider":false,
      "renameProvider":false,
      "experimental":{  

      },
      "typeDefinitionProvider":null,
      "implementationProvider":null
   }
}
```

**Comment by dbaeumer** [comment]
OK. This explains it. This one already registers document synchronization using
```js
      "textDocumentSync":{  
         "openClose":true,
         "change":2,
         "willSave":false,
         "willSaveWaitUntil":false,
         "save":{  
            "includeText":true
         }
      }
```

If you add another sync dynamically you get two. Currently the client doesn't de-dupe them since this might be hard to decide. Which document selector do you pass in when creating the LSP client?

**Comment by NTaylorMullen** [comment]
Using `[ { pattern: '**/*.cshtml' } ]` as the document selector. 

@dbaeumer is this something the language server shouldn't be doing?

**Comment by dbaeumer** [comment]
So what happens here is the following:

- the client is created with a document selector of `[ { pattern: '**/*.cshtml' } ]`.
- the server request document sync in the initialize response. So the client hooks up the necessary listeners for the document selectors the client got created with
- the server then dynamically registers for change to `**/*.cshtml`. This is why you receive them twice.

To avoid this either:

- create the client without a default selector, then the request from the initialize request will be ignored
- change the server to either not return the `textDocumentSync` literal or remove the dynamic registration.

OK for you to close the issue ?

**Comment by NTaylorMullen** [comment]
> OK for you to close the issue ?

Closing seems alright. A little sad that the language spec doesn't specify what should happen in this overlap scenario 😢.

/cc @david-driscoll given that the [language server](https://github.com/OmniSharp/csharp-language-server-protocol) you built dynamically registers everything it might be good to make it a bit smarter in regards to what things will be dynamically registered vs. what's returned in the initialize request.

**Comment by david-driscoll** [comment]
The library should only register static methods when the client does not support dynamic registration.

Log a bug in our repo and I'll take a look

**Comment by dbaeumer** [comment]
No, the VS Code LSP client always supports dynamic registration independent whether you provide a document selector to the client.
