### ISSUE TITLE
publishing source maps and declaration maps

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode-languageserver-node#395]
Would it be possible to publish them to easy debugging and development experience to downstream projects?

**Comment by dbaeumer** [comment]
Actually the `d.ts` files are published. I have no problems publishing the source maps. Only downside is that it makes the npm modules larger.

**Comment by chemzqm** [comment]
I don't think publish source code and source map is a good idea, developer could use `npm link` or `yarn link` for debuging.

**Comment by dbaeumer** [comment]
and installing them slower since more files need to be unpacked. So thinking about it again we might invest into an option to install them separately only (e.g. publish a -dev package)

**Comment by dbaeumer** [comment]
Actually I do agree with @chemzqm.
