### ISSUE TITLE
`onReady` is not reinitilaized on restart

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/vscode-languageserver-node#397]
`this._onReady` is assigned once in the constructor, so calling `this._onReadyCallbacks.resolve` or `this._onReadyCallbacks.reject` does not cause any effect on the restart

I wonder how clients can register request and notificaiton handler on restart. A new resolved connection does not have them. For example this code seems to be executed only on first start, never on restart: https://github.com/redhat-developer/vscode-java/blob/1f6783957c699e261a33d05702f2da356017458d/src/extension.ts#L90

**Comment by dbaeumer** [comment]
Good catch and good question. Since people can cache the promise there is no way how I can reinitialize it since promise states can't be altered from the outside. 

I think the best we can do is to send a `event` and then people can re-fetch `onReady`

**Comment by dbaeumer** [comment]
I made the necessary changes which will ship with the next version of the library.

You can then do
````ts
	client.onDidChangeState((event) => {
		if (event.newState === State.Starting) {
			client.onReady().then(() => {
				console.log('Server is ready');
			});
		}
	});

```
