### ISSUE TITLE
Error in importing document symbols in vscode-languageclient

### ISSUE THREAD

**Issue by sanboxrunner** [Microsoft/vscode-languageserver-node#398]
Hello!

I'm getting an error:

```
Module ''vscode'' has no exported member 'DocumentSymbol'.
```

And a few other similar errors. 

I have the `vscode` npm module installed at the current version.

**Comment by dbaeumer** [comment]
Yes, but the version of the vscode engine you prereq doesn't have the DocumentSymbol definied. Upgrade the version of your vscode extension to `1.26` and things should work.

in `package.json`
```js
	"engines": {
		"vscode": "^1.26"
	},

```

**Comment by dbaeumer** [comment]
No problem.
