### ISSUE TITLE
Is it possible to add more FormattingOptions to DocumentFormattingParams?

### ISSUE THREAD

**Issue by NikolasKomonen** [Microsoft/vscode-languageserver-node#401]
Hi,

I'm working on the XML language server and I was wondering if the client is able to configure the FormattingOptions( in DocumentFormattingParams) and add customised configurations when the TextDocumentService's formatting service is called as of now it only seems that TabSize and InsertSpaces are available.

**Comment by dbaeumer** [comment]
In general the literal can contain more options since the signature allows for 

```ts
[key: string]: boolean | number | string;
```

As @rcjsuen pointed out it would be could to standardize those. But this has to happen in the protocol itself. Any objection to move the discussion about this to Microsoft/language-server-protocol#375
