### ISSUE TITLE
console.log messages are seemingly getting redirected to output channel

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-languageserver-node#402]
I feel like this changed in a recent version. Unless I'm just losing it, I remember that `console.log` where making it to the `Debug Console` when attached to the language server, but now I only see them in the `Output Channel` of the instance running the extension. 

Am I losing it or did this change recently?

**Comment by dbaeumer** [comment]
The once from the server always appeared in the Output Channel. The corresponding code was always like this: https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/main.ts#L346

Reason being is that a server can log even when no debugger is attached. Any objection to close ?

**Comment by eamodio** [comment]
Hrm. I swear I used to get console.log messages in the Debug Console when attached. Is there any way to get that to happen?

**Comment by dbaeumer** [comment]
I am pretty sure the once printed from the extension itself appear in the debug console when the extension is started in debug mode.

> Is there any way to get that to happen?

Only by changing the code. And then the question is what to do if no debugger is attached.

**Comment by eamodio** [comment]
I have no issue with them going to the output channel always. But when attached I'd like them to also go to the Debug Console if at all possible. 

And this behavior really didn't change recently?

**Comment by dbaeumer** [comment]
All I can say is that I didn't change the code around this. May be something changed in VS Code itself.

**Comment by eamodio** [comment]
Ah, ok -- Thanks. So is there a way to have the output go to the Debug Console when the debugger is attached?

**Comment by dbaeumer** [comment]
Currently not. That would need a change to the LSP client code.

**Comment by eamodio** [comment]
Yeah, this one regularly impacts me -- I expect to see that output in the Debug console. @dbaeumer is this hard, could you point me in the right direction of possibly contributing this behavior?

**Comment by dbaeumer** [comment]
The code is in this file: https://github.com/Microsoft/vscode-languageserver-node/blob/dbaeumer/projectReferences/client/src/main.ts#L5

Look for the place that listen on `stdout` and `stderr` of the server process (to make this nice we would needs some refactoring that hooks this in one place).

However I have no idea how to forward this to the debug console? @weinand and suggestions?

**Comment by weinand** [comment]
When running the language server from a launch config, you might want to add a `"outputCapture": "std"`.

**Comment by eamodio** [comment]
I tried adding that launch config to both the extension side and the lsp server side and didn't see any difference. Should I have?

**Comment by eamodio** [comment]
@dbaeumer @weinand anything else to try here?

**Comment by eamodio** [comment]
@dbaeumer are you patching console.log?
