### ISSUE TITLE
TextDocumentSyncKind.Incremental gives strange Ranges

### ISSUE THREAD

**Issue by sanboxrunner** [Microsoft/vscode-languageserver-node#405]
Hello!

I have my Language Server responding like such to the `onInitialize` request:
```ts
return {
		capabilities: {
			textDocumentSync: TextDocumentSyncKind.Incremental,
                        // other things
           }
}
```

In the handler for `onDidChangeTextDocument`, however, my contentChanges provide little information. If I begin with a text document:
```
var test;
```
and add more so that the text document now looks like:
```
var test; var test;
```
I receive the following object (as a member of an array of contentChanges):
```json
{
  "range": {
    "start": { "line": 0, "character": 10 },
    "end": { "line": 0, "character": 10 }
  },
  "rangeLength": 0,
  "text": "var test; \r\n"
}
```
As you can see, the start and end of the range are identical, and the rangeLength is 0. That is manageable, since I can check if I'm adding new text by the start range, and then make the length of the range myself, but it seems strange that there's such a drop in information, with seemingly dummy information. If the client can't send an `End` position for whatever reason, a `null` or `undefined` would be preferable. 

It seems possible though that I'm doing something wrong (as I have many times before with this). If anyone has any advice on that front, it would be very appreciated. Thank you!

**Comment by dbaeumer** [comment]
There is only one form of a `TextEdit` in the LSP which is used for insert, delete and replace. The rule is:

- insert: range.start == range.end
- delete: text == ''
- replace: range.start != range.end & text != ''

In that sense the above edit is correct. Any objection to close the issue?

**Comment by sanboxrunner** [comment]
Thank you for the clarification. I'll close it!
