### ISSUE TITLE
Additional documentation for `connection.onCompletion`

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/vscode-languageserver-node#409]
Hi there, thank you for this project! 👋

I hope this is the right place to ask my questions regarding `vscode-languageserver`.

Every time when I checkout https://github.com/Microsoft/vscode-extension-samples/tree/master/lsp-sample I wonder how the completion logic really works.

So we have the `onCompletion` method [here](https://github.com/Microsoft/vscode-extension-samples/blob/c539b990878ac2dc85708dd08d2eb72902481308/lsp-sample/server/src/server.ts#L180) where we return: 

```
[
  {
    label: 'TypeScript',
    kind: CompletionItemKind.Text,
    data: 1
  },
  {
    label: 'JavaScript',
    kind: CompletionItemKind.Text,
    data: 2
  }
];
````

These are only _potentially_ completable items, right? They don't appear _every_ time someone writes a new word, but only if there is some "match" (.e.g. I write `T` and **`T`**`ypeScript` appears or I write `Script` and `Type`**`Script`** and `Java`**`Script`** appears). Who is responsible for this match? VS Code or `vscode-languageserver`? Can I enforce to _always_ return a certain item? Or write `f` and offer `buzz` as a completion instead of `fizz` which begins with `f`?

And can I customize _what_ triggers the auto completion? I think currently one needs to write a _space_ and then some characters. Can I do it with a different character than space as well?

Thank you

**Comment by dbaeumer** [comment]
@donaldpipowitch the LSP doesn't specify what clients need to do in terms of filter and sorting. This is up to the client to decide. So the contract is as follows:

- a server should always return a complete list of items at a given location. This allows the client for example to not contact the server if the users types another character. The client can simple filter the list
- if the server can't compute a complete list or characters can change the list content a server can mark the result value as incomplete. Use the `CompletionList` type in this case
- the serve can define ithe trigger characters used to trigger code complete in the servers initialize result. The corresponding configuration is here: https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.ts#L685

I will close the issue. Please ping if something is still unclear.
