### ISSUE TITLE
Error: The language client requires VS Code version ^1.26 but recevied version 1.25.1 

### ISSUE THREAD

**Issue by tylerl0706** [Microsoft/vscode-languageserver-node#410]
Hi there!

I work on the PowerShell extension for VSCode.

We got [an issue from @shnipov](https://github.com/PowerShell/vscode-powershell/issues/1511) who said that they received:
```
Error: The language client requires VS Code version ^1.26 but recevied version 1.25.1
```

This is strange to me because we [set the engine in the package.json to 1.25](https://github.com/PowerShell/vscode-powershell/blob/master/package.json#L8). 

Let me know how I can help.

**Comment by dbaeumer** [comment]
@tylerl0706 the latest VS Code LSP client require VS Code version 1.26 or greater. It looks like you tried to execute the extension on VS Code `1.25.1`. You need to move our engine filed to 1.26 or greater.

Any objection to close?

**Comment by shnipov** [comment]
VS Code 1.26 has an issue with performance on startup and window switch, that's why I had to rollback to 1.25.1.
And I'd like to use powershell extension with it. Is there any specific reason for 1.26 version dependency?

https://github.com/Microsoft/vscode/issues/56644

**Comment by tylerl0706** [comment]
@dbaeumer thanks for the follow up. Was the requirement of 1.26 done in the 5.0 release of the language client?

@shnipov there's nothing we are leveraging in 5.0 AFAIK so rolling back so that 1.25 still works with the PowerShell extension is the right way to go here.

We can close this issue since the client is acting by design.

Although my initial reaction is that at start up time, the language client should warn or error that 1.25 is an invalid option because the language client requires 1.26 or higher.

That would make it easier to catch these problems in the future 😊

**Comment by dbaeumer** [comment]
@tylerl0706 yes, it got introduced in the 5.0 release. 

We actually warn as soon as the language client starts. Warning earlier (on VS Code start) can't be done since extensions are activated lazily. 

I am closing the issue. Ping if there is still something unclear
