### ISSUE TITLE
Utility functions for Position and Range

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode-languageserver-node#412]
It would be nice to have utility functions similar to vscode apis to implement language servers.

**Comment by aeschli** [comment]
Which ones are the most valuable? I personally only used a few so far.

**Comment by akosyakov** [comment]
I was interested in `Range.intersection`.

**Comment by Jma353** [comment]
This would be nice to have.  I can probably get a PR up for intersection specifically some time this week.

**Comment by Jma353** [comment]
Feel free to assign to me @aeschli

**Comment by aeschli** [comment]
@Jma353 PRs are welcome...
