### ISSUE TITLE
Consider exposing the restartTimes to LanaguageClientOptions

### ISSUE THREAD

**Issue by hokein** [microsoft/vscode-languageserver-node#418]
The languageclient restarts LSP server 5 times if LSP server crashes. The restart time is hard-coded in https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/client.ts#L272. 

Can we expose it as an option like `restartTimes` in `LanguageClientOptions`, so that LSP extension can customize it? I know LSP extension can provide their custom `ErrorHandler` to adjust the restart times, but I think it is still sensible to provide such option.

**Comment by dbaeumer** [comment]
@hokein exposing it makes sense. A PR is welcome for this.
