### ISSUE TITLE
Expose API to determine the state of the client ?

### ISSUE THREAD

**Issue by smarter** [Microsoft/vscode-languageserver-node#422]
Maybe I'm missing something but state(), getPublicState() and isConnectionActive() are all private, making it impossible to figure out if the language client is currently usable or not.

**Comment by chemzqm** [comment]
One problem I found is I want to avoid client again in different location, but I don't know if the client state is starting by just use `onDidChangeState` and the promise returned by `onReady`

**Comment by dbaeumer** [comment]
I am not sure I understand this. Can you give me a more concrete example.
