### ISSUE TITLE
Expose the ensure function ?

### ISSUE THREAD

**Issue by smarter** [microsoft/vscode-languageserver-node#423]
It's kind of weird that ensure is defined in five places, but never exported: https://github.com/Microsoft/vscode-languageserver-node/search?q=%22function+ensure%22&unscoped_q=%22function+ensure%22
It seems like a useful things for users of vscode-languageclient trying to extend the protocol, so why not expose one definition and get rid of the others ?

**Comment by dbaeumer** [comment]
I have no problem of moving it to a utility inside the package, but I am against of exposing it as API. We usually try to keep the API surface as small as possible.

**Comment by smarter** [comment]
> We usually try to keep the API surface as small as possible.

That's reasonable, but considering that extending `DynamicFeature` is part of the API, and that `DynamicFeature#fillClientCapabilities` is seemingly always implemented using `ensure` currently, doesn't it make sense to expose `ensure` ? Otherwise implementers of custom extensions basically need to implement something equivalent.
