### ISSUE TITLE
Document the usage of Object.assign ?

### ISSUE THREAD

**Issue by smarter** [Microsoft/vscode-languageserver-node#424]
This pattern is repeated several times in the codebase:
```typescript
Object.assign({}, { documentSelector: documentSelector })
```
Apologies if this is a common pattern in JS but I did some research and I fail to see how this is different from just writing:
```typescript
{ documentSelector: documentSelector }
```

**Comment by dbaeumer** [comment]
This is actually not different. I usually do this if I expect that more source literals will be used. 

I will close the issue. Please ping if something is still unclear.
