### ISSUE TITLE
Question about the usage of connection.onInitialize

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/vscode-languageserver-node#427]
Hi there,

I have a general question about the usage of `connection.onInitialize`. Would it be correct to call it twice with different configs? (E.g. to keep _code completion_ logic and its config together in one file, but other configs in other files.) Something like this:

```ts
// setup.ts
connection.onInitialize(() => ({
  capabilities: {
    textDocumentSync: documents.syncKind
  }
}));

// completion.ts
connection.onInitialize(() => ({
  capabilities: {
    completionProvider: {}
  }
}));
```

It seems to work, but I'm not sure if this is actually supported. I try to write a tutorial and this would help to keep a linear flow in the logic/explanations.

Is it also okay to call `connection.onInitialize` after `connection.listen();`? This seems to work as well.

**Comment by dbaeumer** [comment]
@donaldpipowitch this actually installs a handler on the server side which is called when the client sends the initialize request to the server. You can modify the handler but it will not be called if the initialize requests has already been received. If it has not been received only the new handler will be called.

Closing. Please ping if something is still unclear.

**Comment by donaldpipowitch** [comment]
Thank you for your answer. So my take away is: you should use `onInitialize` only once, because it overwrites the older handler and it _can_ be used after `listen`, because it depends on the initialize request from the client. Right?

Thank you

**Comment by dbaeumer** [comment]
Right.
