### ISSUE TITLE
Go to Implementation does not find some implementations

### ISSUE THREAD

**Issue by jchurch33** [Microsoft/vscode-languageserver-node#429]
I'm working with a large Typescript codebase, and I have noticed this consistent problem with the "go to implementation" command.

When I invoke this command on a class in _/workspace_root/a/b/c/parent.ts_
I can get results for other classes in the same directory, (_/workspace_root/a/b/c/child1.ts_), but I have other implementing classes in another directory (_/workspace_root/a/b/d/child2.ts_) that do not appear in the results.

This is puzzling because other commands like "go to definition" or "find all references" don't seem to have this problem.

This seems fixable.

**Comment by dbaeumer** [comment]
Please report the issue against VS Code itself (https://github.com/Microsoft/vscode). This repository is for the general LSP libraries.
