### ISSUE TITLE
Invalid Uri in Mac

### ISSUE THREAD

**Issue by scull06** [Microsoft/vscode-languageserver-node#435]
Hi,

I'm implementing a plugin with a language server for JavaScript. I execute specific commands that eventually will push diagnostics to the client. In spite that the diagnostics are pushed I got an Uri error and I don't get the text decorations for the diagnostics. Bellow an example of my server snippet and the warning that I get in the console.

I'm using VSCode 1.28 in mac, because in version 1.29 it doesn't work at all. 

```javascript
connection.onExecuteCommand((params, cancelationToken) => {
     //some code...
    const diagnostics = getDiagnostics(params);
    connection.sendDiagnostics({
        uri: params.docUri,
        diagnostics: diagnostics
     });
}
``` 

[UriError]: Scheme is missing: {scheme: "", authority: "", path: "/path/to/the/file.js", query: "", fragment: ""}

**Comment by rcjsuen** [comment]
Did you try giving it a scheme to the URI then?

**Comment by scull06** [comment]
Yes,
I tried this `const uri = Uri.file('/path to the file')`, and  I get a valid uri with a valid schema but issue remains like this:

[UriError]: Scheme is missing: {scheme: "", authority: "", path: "[object Object]", query: "", fragment: ""}
extensionHostProcess.js:45

**Comment by dbaeumer** [comment]
The code looks OK to me. @scull06 have you tried to debug the client side when the diagnostic is converted. The code is here: https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/client.ts#L2925
