### ISSUE TITLE
textDocument/prepareRename does not prevent rename dialog from appearing

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/vscode-languageserver-node#447]
Has anyone been able to get `textDocument/prepareRename` working? I'm trying this with `vscode-languageclient` 5.2.1.

I have confirmed that `null` is being returned here in the debugger but the popup still shows up asking the user to enter in a name to rename the selected word.

https://github.com/Microsoft/vscode-languageserver-node/blob/9de8809400b7c443bc25f211dfaddcb74675b2d7/client/src/client.ts#L2041-L2055

**Comment by dbaeumer** [comment]
@rcjsuen sorry forgot about that. Then the language client needs to convert null into a rejected promise. Since the VS Code API only fails when the promise is rejected.

**Comment by rcjsuen** [comment]
Thanks for fixing this, Dirk!
