### ISSUE TITLE
[Client] no support for LSP CompletionItem deprecated property

### ISSUE THREAD

**Issue by BoykoAlex** [microsoft/vscode-languageserver-node#450]
LS protocol `CompletionItem` has `deprecated` property https://microsoft.github.io/language-server-protocol/specification#textDocument_completion

I expect the completion label displayed for a CompletionItem with `deprecated` set to `true` to have "strike-through" style on it. However, the style is the same as for completions without `deprecated` property

**Comment by rcjsuen** [comment]
See Microsoft/vscode#50972.

**Comment by dbaeumer** [comment]
@BoykoAlex as @rcjsuen correctly points out this is currently not supported in VS Code.
