### ISSUE TITLE
[Client] Apply workspace edit opens file in editor with changes not saved

### ISSUE THREAD

**Issue by BoykoAlex** [microsoft/vscode-languageserver-node#454]
Suppose my workspace edit is:
- Create file X
- Set text content for file X

Once such a WorkspaceEdit applied the result is file X created and opened in the text editor with content in it. The editor is dirty. Therefore, if editor is closed without saving the content is lost.

Expected behavior would be:
File X wasn't opened in the editor before. Therefore, file should created and content set without opening the editor.

Feels like this should be addressed in Workspace.applyEdit(...) call https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/client.ts#L3209

**Comment by dbaeumer** [comment]
This is how VS Code behaves (even if you call the VS Code API directly). If you think that should change, please file a issue against VS Code itself and then we can adopt this here.

**Comment by BoykoAlex** [comment]
Here is the issue in VSCode: https://github.com/Microsoft/vscode/issues/66673

**Comment by dbaeumer** [comment]
I am closing the issue since it didn't get any traction on the VS Code side.

**Comment by dbaeumer** [comment]
See my latest comment.
