### ISSUE TITLE
Don't show an error message when receiving `ContentModified` error

### ISSUE THREAD

**Issue by matklad** [microsoft/vscode-languageserver-node#457]
`ContentModified` error response is send by the server if, during computation of the normal response, the server received DocumentChanged notification. It is useful for the servers who maintain only a single, "current" copy of all the state. `ContentModified` is not really an "exceptional" error, it is expected to happen on a regular basis.

Currently, VS Code shows a user-visible error popup for this cases, but the correct behavior would be to either silently use the default "empty" response, or to retry the request. 

cc https://github.com/Microsoft/vscode-languageserver-node/commit/e72e16ed9e57ea569b5f1265614d53789f916997

**Comment by dbaeumer** [comment]
Retrying the request doesn't make sense for positional requests since it is hard to tell if the position still makes sense. The right approach would be to have a content modified handler in the client so that this can be controlled by the extension author.
