### ISSUE TITLE
Spec says WorkspaceSymbolParams.query should be non-empty but client sends empty strings

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode-languageserver-node#458]
For `workspace/symbol` the spec defines `WorkspaceSymbolParams` as:

```ts
/**
 * The parameters of a Workspace Symbol Request.
 */
interface WorkspaceSymbolParams {
	/**
	 * A non-empty query string
	 */
	query: string;
}
```

The definition doesn't permit `null` or `undefined` and the comment says it's non-empty, however the language client sends requests with empty strings for the query when opening the workspace symbol list:

<img width="397" alt="screenshot 2019-02-11 at 1 59 06 pm" src="https://user-images.githubusercontent.com/1078012/52567996-7be79700-2e05-11e9-92ef-7e60950baa16.png">

I'm raising this here since it seems to violate the spec, however I wonder if the spec should permit either `null`, `undefined` or `""` since right now it seems like you couldn't list all.

**Comment by dbaeumer** [comment]
Actually the idea behind this is that empty could be sent by coincidence which will put a lot of load onto the server. If someone wants all symbols he should send '*'. 

Let me check when this happens.

**Comment by Gama11** [comment]
I think in the Haxe language server we specifically ignore query strings of length 0 because that used to cause performance issues for us.

**Comment by DanTup** [comment]
> Actually the idea behind this is that empty could be sent by coincidence which will put a lot of load onto the server. If someone wants all symbols he should send '*'.

Aha, that makes some sense, then this sounds like a VS Code bug. What's the correct way for the server to repsond to an empty string then - rejecting the request with `InvalidParams`? Returning an empty list?

**Comment by dbaeumer** [comment]
I checked in VS Code and there it was changed on purpose to leave this up to the provider. So we can have a discussion whether we should do the same for LSP or not. I am open for suggestions.

**Comment by DanTup** [comment]
It sounds sensible to leave up to the server - if it can get the full list quickly (or it knows the list is small) then probably LSP shouldn't prevent it.

In which case, I think the spec shouldn't say this is non-empty, but instead call out that the server can make this decision (to ensure clients are written to handle it nicely), and specify how the server should respond if it doesn't want to handle it (an error, a null, an empty list?).

**Comment by dbaeumer** [comment]
I like that approach.

**Comment by matklad** [comment]
imo, the core problem here is that symbol search returns an array of results and not an async stream.

This really wants to be a stream, so that the client could get & show the first 10 results immediately, and request the rest only when the user scrolls past the first ten. This should also make user-experience better by allowing the editor to drastically lower or even remove the denouncing delay in the workspace symbol UI.

If streaming were available, there wouldn't be a need for working around a potentially large results set.

This is a large feature to design though

**Comment by DanTup** [comment]
>  the client could get & show the first 10 results immediately, and request the rest only when the user scrolls past the first ten. This should also make user-experience better by allowing the editor to drastically lower or even remove the denouncing delay in the workspace symbol UI.

To get the first 10 results *sorted*, wouldn't the server have to do the full search anyway - and then cache the results in case the server asks for "the next page" later? That feels like more complexity to only save the part of time spent transferring the results.

**Comment by matklad** [comment]
If to answer the query server does a naive loop over all symbols, than it should return results in a single batch.

However, good servers would probably use some kind of an index to answer queries fast, and indices are usually pre-sorted. 

In particular, the best index here is probably an hierarchy of finite state transducers. [fst crate](https://docs.rs/fst/0.3.3/fst/) has an awesome introduction to the topic, but the core idea is that you represent the set of symbols as a (large but "simple") finite state machine, encode the query as a state machine as well (so, you can have regex queries, and fuzzy queries are a subset of that), and then walk the intersection of these two state machines, producing matches in the lexicographical order, with an ability to stop and restart the search from arbitrary position.

**Comment by DanTup** [comment]
Interesting, thanks for the info and link!

**Comment by DanTup** [comment]
@dbaeumer I opened https://github.com/microsoft/language-server-protocol/pull/770 to remove the "non-empty string" text from the spec, since VS Code violates this and based on the above I believe VS Code's behaviour is desired.

**Comment by dbaeumer** [comment]
Thanks !

**Comment by DanTup** [comment]
@dbaeumer the PR isn't merged yet - if it can't be merged could you confirm the intent is correct so I can be more confident in my understanding when people ask me about my servers handling of it? :-)

**Comment by DanTup** [comment]
@dbaeumer ping! :-)

**Comment by dbaeumer** [comment]
Updated spec and protocol files
