### ISSUE TITLE
Move SelectionRange and SelectionRangeKind to types

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-languageserver-node#460]
SelectionRange and SelectionRangeKind should go into types

**Comment by rcjsuen** [comment]
I use this package exclusively to separate out the language service logic and the language server logic. So I like it anyway. :P

**Comment by dbaeumer** [comment]
I can move them if the selection range becomes stable. The type package has no proposed support :-(.

**Comment by dbaeumer** [comment]
This got magically done :-)
