### ISSUE TITLE
Hover registration Server / Client ?

### ISSUE THREAD

**Issue by melMass** [Microsoft/vscode-languageserver-node#462]
Hi,

I'm building a Language Extension for VSCode and I have a bit of a hard time while trying to understand client vs server registration for Hover.

I want to process the data on the server and resolve to a popup on the client.
I know how to do it client side and it works well. 

Now I want to implement it server-side instead as I did with `Completion` and `Signatures` but `Hover` seems to **handle it differently**. I hardly managed to get *any* info and mostly looked at other Language Extensions to find answers.

Here are the relevant parts of where I'm at:

Server side: 
```typescript
...
return capabilities: {
    ...
    hoverProvider: true,
    ...
}

...

connection.onHover((params: TextDocumentPositionParams): Hover|undefined => {
  let doc : MarkedString[] = ["# Title","### description"]
  return {
    contents: doc
  }
}
```

But it does not show up the popup. It does get fired on hover as expected but it's not sent back to VSCode's client for some reason. What am I doing wrong ?

**Comment by dbaeumer** [comment]
This works for me without problems. 

![capture](https://user-images.githubusercontent.com/1931590/53009874-c3d97000-343c-11e9-9930-07844a27a605.png)


Are you sure you have configured the document selector correctly?

**Comment by melMass** [comment]
Thanks,

Strange... As I said If I implement it on the client extension it does work:
```typescript
languages.registerHoverProvider([{ scheme: 'file', language: 'vex' }], {
    provideHover(document, position, token) {
				let wordRange = document.getWordRangeAtPosition(position);
				let lineText = document.lineAt(position.line).text;
				let word = wordRange ? document.getText(wordRange) : '';
				if (position.isEqual(wordRange.end) && position.isAfter(wordRange.start)) {
					position = position.translate(0, -1);
				}
				console.log(word,position)
				let c : MarkedString[] = ["# Title",word]
				return {
					contents:c
				}
					;
				
    }
});
```

But not on the server (see previous post code bits).

I'm pretty sure it's about telling the client to receive hover from the server but I can't find the way.

I'm not sure about the document selector configuration, could you point me to documentation regarding that ?

Thanks

**Comment by dbaeumer** [comment]
I actually tested this with a server. How did you configure the language client in the VS Code extension? When you create it you need to pass a document selector to the client options. See https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/client.ts#L461

**Comment by melMass** [comment]
I think this is the issue, I started from the lsp-sample here it is:

```typescript
	let clientOptions: LanguageClientOptions = {
		documentSelector: [{ scheme: 'file', language: 'vex' }],
		synchronize: {
			// Notify the server about file changes to '.vexrc files contained in the workspace
			fileEvents: workspace.createFileSystemWatcher('**/.vexrc')
			
	
		}
	};

```

**Comment by dbaeumer** [comment]
Hmm, which lsp sample. For me the code in the sample is

```
	// Options to control the language client
	let clientOptions: LanguageClientOptions = {
		// Register the server for plain text documents
		documentSelector: [{ scheme: 'file', language: 'plaintext' }],
		synchronize: {
			// Notify the server about file changes to '.clientrc files contained in the workspace
			fileEvents: workspace.createFileSystemWatcher('**/.clientrc')
		}
	};
```

which registers the server for plain text files. Simply change the language to the type you want to support.

Objections to close?

**Comment by melMass** [comment]
?
I don't understand, yes the sample is adapted to my use case VEX per se... I'm asking about the hover event registration server side ?
What more info do you need ?

**Comment by dbaeumer** [comment]
As said this works for me without problem using 

```
hoverProvider: true
```

I changed the example to add hover. It is on this branch https://github.com/Microsoft/vscode-extension-samples/tree/dbaeumer/lsp-sample-hover

**Comment by melMass** [comment]
Thanks a lot for the sample!
The issue was the formatting of the hover return statement... 🤦‍♂️
