### ISSUE TITLE
Inconsistent behavior of `CancellationTokenSource.dispose()`

### ISSUE THREAD

**Issue by siegebell** [microsoft/vscode-languageserver-node#466]
VSCode does not cancel a token upon `dispose` (see https://github.com/Microsoft/vscode/issues/46101 - @bpasero), but [jsonrpc does](https://github.com/Microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/cancellation.ts#L108). This is _at least_ confusing...

**Comment by dbaeumer** [comment]
Got addressed for April. Is in new next version.
