### ISSUE TITLE
Setting extension heap size doesn't seem to affect anything

### ISSUE THREAD

**Issue by maxhillaert** [microsoft/vscode-languageserver-node#467]
- VSCode Version: 1.29.1
- OS Version: Windows 7 

Steps to Reproduce:

I'm developing inhouse language service extension.  The server process seems to be limited to heapsize of around 2000mb

I'm trying to override this in various ways:

`let serverOptions: ServerOptions = {
		run: {
			module: serverModule, transport: TransportKind.ipc,
			args: ["--max_old_space_size=8096"],
			options: {
				execArgv: ["--max_old_space_size=8096"],
				env: {
					"NODE_OPTIONS": "--max_old_space_size=8096"
				}
			}
		},
		debug: {
			module: serverModule,
			transport: TransportKind.ipc,
			options: {
				execArgv: ['--nolazy', '--inspect=6009', '--max_old_space_size=8096'],
				env: {
					"NODE_OPTIONS": "--max_old_space_size=8096"
				}
			},
			args: ["--max_old_space_size=8096"]
		}
	};

None of these seem to have an effect.  The server process is stuck at 2000 mb until it bombs out.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by dbaeumer** [comment]
@maxhillaert you can always pass in a server function to start the node server by itself. This gives you full control over how to start the server.

This could also be an issue with the fact that we start Electron as RUN_AS_NODE instead of a pure node. You can also use the runtime property to point to a pure node runtime.

**Comment by maxhillaert** [comment]
Thanks. I’ll try that.

**Comment by bradleyayers** [comment]
@maxhillaert how'd you go with this, did you find a way to increase the memory for the server?

**Comment by dbaeumer** [comment]
I tested this today and I was able to successfully pass the `--max_old_space_size` to my server. On the server side I did:

```
const arr = new Array(1073741824);
for (let i = 0; i < 1073741824; i++) {
	arr[i] = new String('#'.repeat(4));
}
```

and referencing the array in the validate call.

and the server didn't crash starting it with `--max_old_space_size=8096` 

I will close the issue. Please provide a GitHub repository I can clone that demos what you are seeing if you are still experiencing the problem.
