### ISSUE TITLE
Provide context.diagnostics in codeAction call

### ISSUE THREAD

**Issue by WebFreak001** [Microsoft/vscode-languageserver-node#469]
Diagnostics are only provided on the very first character of the issue, which seems to break vscode detecting it as code fix and confuses a lot of users. I don't think this has ever worked before.

I think maybe this comes from me only providing a position instead of a range for the diagnostic to make vscode automatically select a word (because I don't have any length information), but I would expect it to send me back the proper diagnostics then when requesting code fixes.

![screenshot showing it not working in the middle of a word](https://wfr.moe/fwztsw.png)
here it is missing completely in the middle,

![screenshot showing vscode detection working at the start of a word](https://wfr.moe/fwzrOa.png)
![screenshot showing code actions that should be emitted](https://wfr.moe/fwoZVt.png)
but it works fine when at the start of the word.

![screenshot showing quickfix button](https://wfr.moe/fwoVIH.png)
![screenshot showing no code actions available when clicking it](https://wfr.moe/fw7jw8.png)
and in this UI it doesn't work.

Using `"vscode-languageclient": "^5.3.0-next.1"`

Relevant logs:
```
[Trace - 10:46:36 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "diagnostics": [
        ...
        {
            "code": "dscanner.suspicious.unused_variable",
            "message": "Variable mirror is never used.",
            "range": {
                "end": {
                    "character": 13,
                    "line": 85
                },
                "start": {
                    "character": 13,
                    "line": 85
                }
            },
            "severity": 2,
            "source": "DScanner"
        },
        ...
    ],
    "uri": "file:///home/webfreak/dev/GDB%20Test/source/app.d"
}

[Trace - 10:49:39 AM] Sending request 'textDocument/codeAction - (38)'.
Params: {
    "textDocument": {
        "uri": "file:///home/webfreak/dev/GDB%20Test/source/app.d"
    },
    "range": {
        "start": {
            "line": 85,
            "character": 16
        },
        "end": {
            "line": 85,
            "character": 16
        }
    },
    "context": {
        "diagnostics": []
    }
}

[Trace - 10:56:05 AM] Sending request 'textDocument/codeAction - (57)'.
Params: {
    "textDocument": {
        "uri": "file:///home/webfreak/dev/GDB%20Test/source/app.d"
    },
    "range": {
        "start": {
            "line": 85,
            "character": 13
        },
        "end": {
            "line": 85,
            "character": 13
        }
    },
    "context": {
        "diagnostics": [
            {
                "range": {
                    "start": {
                        "line": 85,
                        "character": 13
                    },
                    "end": {
                        "line": 85,
                        "character": 13
                    }
                },
                "message": "Variable mirror is never used.",
                "severity": 2,
                "code": "dscanner.suspicious.unused_variable",
                "source": "DScanner"
            }
        ]
    }
}
```

**Comment by dbaeumer** [comment]
@WebFreak001 actually the VS Code API and the LSP sends you the diagnostic as you provided it. So the one provided is one with a range having the same start and end position. The reason why you see the whole word underlined is because the editor decides that is can't render a range with `lenght` zero and expands it. The diagnostic model is not expanded.

**Comment by dbaeumer** [comment]
IMO there is little the LSP can do since this is something the editor decides to do. ANy objection to close?

**Comment by WebFreak001** [comment]
I have fixed it now by providing full word ranges, however I really liked having the automatic word ranges because they were never randomly floating around in the source code when changing code without updating the diagnostics. Though right now it doesn't seem too bad.

Maybe instead of passing the 0-length ranges to the editor the client should already discard them as invalid with some warning? Because it seems to work when first implementing but then turns out to not work properly

**Comment by dbaeumer** [comment]
This is a fair point. However breaking this now might not be very nice either.
