### ISSUE TITLE
Define behavior around parameter hints so LSP clients can support the same completion + hints functionality as TypeScript

### ISSUE THREAD

**Issue by vicapow** [microsoft/vscode-languageserver-node#471]
There are some features that the LSP spec supports but that vscode only supports using editor specific APIs like `editor.action.triggerParameterHints`. These can be implemented in LSP without relying on these "escape hatches" to LSP. Otherwise, what's the point of having a Language Server Protocol if it's not editor agnostic?

As an example of a past issue that was rejected: https://github.com/Microsoft/vscode/issues/70239

The advantages to this approach is that extensions written to support LSP don't have to have editor specific code (which is the goal of LSP.)

> The idea behind the Language Server Protocol (LSP) is to standardize the protocol for how such servers and development tools communicate. This way, a single Language Server can be re-used in multiple development tools, which in turn can support multiple languages with minimal effort
see: https://microsoft.github.io/language-server-protocol/

**Comment by vicapow** [comment]
It's not that vscode isn't conforming to the spec, it's that to add the feature outlined in #70239, it would require editor specific directives to the extension but this feature can be implemented in vscode without them using `textDocument/signatureHelp` request after the completion response.

**Comment by vicapow** [comment]
So with the above stated, this is a request on vscode, not LSP

**Comment by vicapow** [comment]
@dbaeumer Doesn't look like I have permission to move tickets. Can you move this one back?

**Comment by dbaeumer** [comment]
@vicapow I still disagree here. The VS Code editor can't simply send a signature help request after each auto complete insert. There are caes where this wouldn't be appropriate and will for sure cause problems in other situations. If we want to support something like automatic parameter complete this needs to be spec and the the VS Code LSP implementation could call the corrsponding VS Code action.

**Comment by vicapow** [comment]
@dbaeumer why could it not work after every completion of an argument type?

> There are caes where this wouldn't be appropriate and will for sure cause problems in other situations.
Which cases would those be?

The spec touches on a similar situation but in the context of request ordering:

> Request, Notification and Response ordering
> Responses to requests should be sent in roughly the same order as the requests appear on the server or client side. So for example if a server receives a textDocument/completion request and then a textDocument/signatureHelp request it will usually first return the response for the textDocument/completion and then the response for textDocument/signatureHelp.
> 
> However, the server may decide to use a parallel execution strategy and may wish to return responses in a different order than the requests were received. The server may do so as long as this reordering doesn’t affect the correctness of the responses. For example, reordering the result of textDocument/completion and textDocument/signatureHelp is allowed, as these each of these requests usually won’t affect the output of the other. On the other hand, the server most likely should not reorder textDocument/definition and textDocument/rename requests, since the executing the latter may affect the result of the former.

**Comment by dbaeumer** [comment]
@vicapow I am not understanding how this relates to what you are asking. As said I have no problem to add support for automatic parameter completion however this needs to be introduced into the spec so that editors can reques it correctly.

**Comment by vicapow** [comment]
@dbaeumer Maybe I’m missing something but it seems like the spec already has all the needed features. What changes to you see needing to be made to the spec to support this?

**Comment by dbaeumer** [comment]
It has the features but they only work with VS Code. The `editor.action.triggerParameterHints` is not spec and there is not desire to spec commands accross editors. So we would need to add something general.

**Comment by vicapow** [comment]
@dbaeumer I feel like I’m missing something but it seems like this can be implemented in vscode by vscode triggering the signature helper.

**Comment by vicapow** [comment]
@dbaeumer that way, no editor specific hints are required

**Comment by rcjsuen** [comment]
@vicapow So you are suggesting that after a `textDocument/completion` proposal is accepted, the LSP client always (?) triggers a `textDocument/signatureHelp` request to the server?

**Comment by dbaeumer** [comment]
As I tried to explain here: https://github.com/Microsoft/vscode-languageserver-node/issues/471#issuecomment-475541600 this is nothing we can do automatically since it drastically changes the current implementation.

**Comment by vicapow** [comment]
@rcjsuen yes or just when it needs too, like after the completion of a method.

@dbaeumer I respect it may be difficult given the current implementation of vscode but it does at least seem possible given the current LSP spec. Do you agree?

**Comment by vicapow** [comment]
@dbaeumer I also see you mentioned in the other thread you believe there are cases where this wouldn’t be appropriate and woul cause problem. It would help me if you could expand on that.

**Comment by rcjsuen** [comment]
The editor (LSP client) does not know if something being completed is a word or a method/function. It just gets the list of `CompletionItem`s from the server and presents it to the user.

It sounds to me like a naive solution would be to add something like `triggerSignatureHelp?: boolean` to `CompletionItem` and that would indicate whether a `textDocument/signatureHelp` request should be sent out or not.

**Comment by vicapow** [comment]
@rcjsuen The completion returns a “kind” already. Can the client not use this?

Also, shouldn’t it be up to the client what it wants?

**Comment by rcjsuen** [comment]
@vicapow If it's a function with zero arguments I'm not sure it makes sense to trigger `textDocument/signatureHelp`.

**Comment by vicapow** [comment]
@rcjsuen Seems like an optimization. Even still, `SignatureInformation` provides useful info even when the function has no parameters (ie., documentation and label).

**Comment by rcjsuen** [comment]
@vicapow Perhaps, although I presume the user already saw that from the original `CompletionItem`.

So in essence, you are suggesting that after a function/method `CompletionItem` has been selected, the LSP client editor should always call `textDocument/signatureHelp`? Are there any other cases where you would need this?

**Comment by Gama11** [comment]
While functions usually support signature help, but not everything that supports signature help is necessarily a function. So I'm not sure how completion item kinds are helpful here.

Examples:
- For languages with type parameters, a language server could provide signature help between angle brackets (`Type<|>`). `Type` is not inserted with a method / function completion item kind though, since it's well.. a type.
- For `new |` completion, the listed items are types as well, yet it's still a function call that has signature help.

**Comment by vicapow** [comment]
@gama11 servers could still trigger these on character triggers, like `<` and `new`. clients can also choose to trigger these for some types of completion kinds.

**Comment by Gama11** [comment]
Yes, of course `<` would be a signature help trigger character in that scenario. But completion might insert a snippet like `Type<$1>`, which wouldn't trigger this, and would still have to use `editor.action.triggerParameterHints` here (in fact, that's a real-world example from the Haxe language server).

I don't think `new` can be a trigger "character" btw.

**Comment by vicapow** [comment]
If we needed that feature for type parameter completion, we could add another completion type. Maybe just "Type" since `TypeParameter` is already a thing.

But that's getting a bit away from the origin intent of this ticket which is that vscode has all the info it needs to be able to implement this feature (function parameter completion) with the existing spec.

**Comment by Gama11** [comment]
It seems quite relevant to me. It means that the feature couldn't work in all the cases it _should_ work for due to its design. To me that indicates bad design.

I agree with @rcjsuen that an explicit `triggerSignatureHelp?: boolean` would be better.

**Comment by vicapow** [comment]
I could see an argument either way. Using `Kind` gives control clients  control for what they want to show signature helpers. ie., configure signature helpers depending on the "Kind". Alternatively, having the `triggerSignatureHelper` gives more control to the server.

**Comment by rcjsuen** [comment]
I think giving servers control would allow for a more consistent behaviour across LSP clients.

Anyway, it sounds to me like we should take this discussion over to the [Microsoft/language-server-protocol repository](https://github.com/Microsoft/language-server-protocol) instead.

**Comment by dbaeumer** [comment]
Although the VS Code client could implement it based on the API it has this is not how we did this in the past in LSP. AS I tried to explain (and @rcjsuen supports this) we need to spec this behaviour and make it explicit. Everything else cause unnecessary friction to existing client and server implementations.

**Comment by dbaeumer** [comment]
We closed this issue because we don't plan to address it in the foreseeable future. You can find more detailed information about our decision-making process here. If you disagree and feel that this issue is crucial: We are happy to listen and to reconsider.

If you wonder what we are up to, please see our roadmap and issue reporting guidelines.

Thanks for your understanding and happy coding!
