### ISSUE TITLE
Include DidChangeTextDocumentParams in documents.onDidChangeContent

### ISSUE THREAD

**Issue by Jma353** [Microsoft/vscode-languageserver-node#473]
Would it be possible to pass additional data (e.g. document content changes) to the `TextDocuments` callback `onDidChangeContent`, preferably data from `DidChangeTextDocumentParams` (passed to the server in connection's `onDidChangeTextDocument` callback)?  

Right now, `TextDocumentChangeEvent` is limited, as it just returns the document, not the change that hit the document.  Additionally, if one wishes to subscribe to document changes w/`Range`'s returned for each change, and one also wishes to keep synchronized `TextDocuments`, there's really no way to do this.

Currently, the only way one can extract `Range`-based changes for documents is by declaring a `connection.onDidChangeTextDocument` callback.  Two issues arise with this:

```javascript
// Issue 1: User-defined callback is overridden, by 
// https://github.com/Microsoft/vscode-languageserver-node/blob/master/server/src/main.ts#L255-L269
connection.onDidChangeTextDocument = mySpecialCallback;
documents.listen(connection);

// Issue 2: User-defined callback overrides document-synchronization 
// logic linked above
documents.listen(connection);
connection.onDidChangeTextDocument = mySpecialCallback;
```

Any advice regarding this?

BTW - happy to instrument this change myself if there's buy-in.

**Comment by Jma353** [comment]
BTW - I saw #456 too, specifically 

>`documents.onDidChangeContent` will stop working.
Are `connection.onDidChangeTextDocument` and `documents.onDidChangeContent` mutually exclusive?  

in the original issue.  My above explanation is why this happens, I believe.  In general, this seems somewhat unexpected, as listening for events / notifications shouldn't affect the ability for these documents to stay in-sync.

**Comment by dbaeumer** [comment]
@Jma353 the document manager provided in the server node module only support full content sync. If used the client doesn't send individual content change events. If you want incremental document changes simply you can't use the document manager and need to handle the events yourself.

Objections to close?

**Comment by Jma353** [comment]
@dbaeumer Thanks for the additional info.  Yes, I understand this is a limitation.  Just repro-ed this as well by forcing `textDocumentSync: TextDocumentSyncKind.Incremental`.  In summary, for others reading this: 

> Based on the current `TextDocuments` implementation, one cannot track lines of the document changed via `TextDocuments`'s `onDidChangeContent` callback, as full document sync's are the only ones supported. 

Is there an issue tracking creating a document manager that handles incremental sync-ing?  Is that out of the scope of this API?  I'd be interested in helping with the effort of adding this support for increased efficiency of document sync-ing.  

I have no objections to closing this.

**Comment by dbaeumer** [comment]
@Jma353 thanks. Closing then.
