### ISSUE TITLE
Handle non-existent NODE_PATH directory in Files.resolve

### ISSUE THREAD

**Issue by glen-84** [Microsoft/vscode-languageserver-node#475]
If `nodePath` refers to a non-existent directory, the following occurs:

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\{user}\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

@egamma handled this in the deprecated `vscode-tslint` extension with [this change](https://github.com/Microsoft/vscode-tslint/commit/36a2e0587ff6c5e28365b650c23eef7d57aa74f6), and I followed suit in [my extension](https://github.com/glen-84/vscode-sass-lint).

However, since `fs.exists` is deprecated, and existence checks in general are not recommended, I was wondering if it was possible for this to be handled by `vscode-languageserver-node` instead?

I see that you're using `on('error')` in addition to a try/catch block – is this just a bug in Electron or Node.js? If so, is there an issue tracking it?

**Comment by dbaeumer** [comment]
@glen-84 this is actually a problem with Electron. It never occurred to us with node.js itself. When we first saw this month ago simply hnadling `onError` fixed it. Are you seeing this with latest releases of the server lib?

**Comment by dbaeumer** [comment]
I am not able to reproduce this:

<img width="723" alt="capture" src="https://user-images.githubusercontent.com/1931590/55318869-064a8f80-5474-11e9-8a59-c7b1bcae01ca.png">

**Comment by glen-84** [comment]
> Are you seeing this with latest releases of the server lib?

https://github.com/glen-84/vscode-sass-lint/blob/612700068407c4013ca1059bc3dfed3bed63252a/sass-lint-server/package-lock.json#L1251

vs

https://github.com/Microsoft/vscode-eslint/blob/29999d39da53ff861dbb3d9e719c3c51fb0cb6ca/server/package-lock.json#L13

```bash
$ npm-check -u
❤️  Your modules look amazing. Keep up the great work. ❤️

$ npm outdated
Package                Current  Wanted        Latest  Location
vscode-languageserver    5.2.1   5.2.1  5.3.0-next.1  sass-lint-server
```

Might be [an issue](https://github.com/dylang/npm-check/issues/244) with `npm-check`. I'll try `5.3.0-next.1` within the next two days, and I'll get back to you.

**Comment by glen-84** [comment]
Same thing happens with `5.3.0-next.1` while debugging my extension in VSC `1.33.0-insider`.

I'll try to test the same thing with `eslint` when I get a chance.

**Comment by dbaeumer** [comment]
Let me know what you find out.

**Comment by glen-84** [comment]
I'm confused.

I installed the same versions of the language client and server, but:

Your extension outputs:

```
Uncaught exception received.
Error: spawn C:\Users\Glen\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

... and continues to run.

My extension outputs:

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\Glen\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

... and crashes.

It's probably something obvious. If you need to close this issue, you can do so. I might look into this again next weekend, but it's not an urgent problem.

**Comment by dbaeumer** [comment]
I will keep it open and see if you find something out. May be we can improve the behaviour in the library as well.

**Comment by dbaeumer** [comment]
@glen-84 please ping if you have any additional info.
