### ISSUE TITLE
TagSupport for Diagnostics should be included in the docs

### ISSUE THREAD

**Issue by tinaschrepfer** [microsoft/vscode-languageserver-node#477]
Looks like TagSupport and DiagnosticTag are in the protocol source code, but not included in the documentation (https://microsoft.github.io/language-server-protocol/specification).  Should add it to specification so they're easier to search for.

**Comment by rcjsuen** [comment]
Great catch, @tinaschrepfer. Looks like it was added in 16c0eacead3e6f3be266033265cc5dc756406b92. I'll bring this up in https://github.com/Microsoft/language-server-protocol/issues/500.

**Comment by dbaeumer** [comment]
The reason why this is not in the spec yet is that it is only in 3.15.0-next.x version of the protocol which is not final.

**Comment by dbaeumer** [comment]
This is in the next version.

https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#diagnostic
