### ISSUE TITLE
CompletionItemKind type mismatch

### ISSUE THREAD

**Issue by Aerijo** [microsoft/vscode-languageserver-node#480]
The [spec says](https://microsoft.github.io/language-server-protocol/specification#textDocument_completion) a `CompletionItem` can have a property `kind` of type `number`. I'm assuming this is so that servers can implement their own kinds if the client supports it. However, this module [declares the type to be](https://github.com/Microsoft/vscode-languageserver-node/blob/df12c101eeacb005157a7248ee7d5d99dff95eab/types/src/main.ts#L1414) `CompletionItemKind`, which is the restricted list of numbers that have predefined meaning.

I think the `kind` type in this module should be changed to `number`, or `CompletionItemKind` should be made an alias for `number` (I prefer the latter). As it is, the type system will not alert clients that do not handle numbers out of the normal range.

**Comment by dbaeumer** [comment]
Good catch. I updated the spec with: 

> The standardized set of available values is defined in `CompletionItemKind`.

The reason why the spec uses number is that most languages don't support or types on constant literals. 

OK to close?
