### ISSUE TITLE
occasionally diagnostics don't get cleared

### ISSUE THREAD

**Issue by stamblerre** [microsoft/vscode-languageserver-node#483]
I'm using VSCode with gopls (https://github.com/golang/go/wiki/gopls), and I've noticed that occasionally, diagnostics can get stuck.

This doesn't happen all of the time, but here is an example of what happens:

There is some open file, `foo.go`, that belongs to a package `foo`. The package also has files `bar.go` and `baz.go`. There is an error in `foo.go`, which results in the language server sending 3 `publishDiagnostics` messages, 2 with empty lists (for `bar.go` and `baz.go`), and 1 with an error (for `foo.go`).

Next, the error in foo.go is deleted, so the language server sends 3 new `publishDiagnostics` messages, each with empty lists of diagnostics. I added logging in the middleware of the VSCode-Go extension (in the `handleDiagnostics` function), and these diagnostics are never received.

However, if a new error is added, i.e., if one of the `publishDiagnostics` messages contains an error rather than an empty list, the diagnostics are received.

I apologize for the lack of a repro case - I have not been able to consistently reproduce this behavior, but it happens often enough that a `gopls` issue was filed about it (https://github.com/golang/go/issues/30786). I tried to debug this, but wasn't able to get very far, so I was hoping for some suggestions or advice on how to investigate this further. Thanks!

/cc @ianthehat @heschik

**Comment by dbaeumer** [comment]
@stamblerre you good way to track this down is to enable client side logging. You can do this by adding the following setting assuming that your language client is created with an id of `gopls` (see https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/main.ts#L154).

`"gopls.trace.server": "verbose"`

In the output viewlet there should now be a channel for your server which contains a trace of the messages flowing back and forth.

I the case you are seeing will the publish notification make it to the client?

**Comment by stamblerre** [comment]
Thanks for the info @dbaeumer! I added the setting and will add more info here when I am able to reproduce (it happens infrequently and unpredictably for me).

**Comment by kjeremy** [comment]
I see this with `rust-analyzer` FWIW.

**Comment by dbaeumer** [comment]
A reproducible case is still welcome.

**Comment by stamblerre** [comment]
I have not seen this issue come up lately, so this issue can be closed unless @kjeremy has a case.

**Comment by dbaeumer** [comment]
@stamblerre thanks for getting back.

I will close the issue then. @kjeremy pls ping if you have a case.
