### ISSUE TITLE
terminateProcess.sh fails with EACCES

### ISSUE THREAD

**Issue by jrvidal** [microsoft/vscode-languageserver-node#484]
I noticed while debugging a language server client extension that the server would not get killed. Logging the `result.error` in:

https://github.com/Microsoft/vscode-languageserver-node/blob/053149a76e7ec147347e41a5847a1cc4ccb3d541/client/src/utils/processes.ts#L34-L36

I got:

```
Error: spawnSync /home/extension/node_modules/vscode-languageclient/lib/utils/terminateProcess.sh EACCES
```

which I guess is reasonable since it's not executable! 

```
$ uname -a
Linux 4.15.0-46-generic #49~16.04.1-Ubuntu SMP Tue Feb 12 17:45:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dbaeumer** [comment]
@sandy081 @joaomoreno the script is installed via an extension. Any hint what I need to do to make the `terminateProcess.sh` executable after the extension has been installed.

**Comment by sandy081** [comment]
Not sure if zipping and unzipping (yazl/yauzl) libraries allows something like this for executables.

**Comment by dbaeumer** [comment]
Lets see if @joaomoreno has an idea.

**Comment by joaomoreno** [comment]
If the extension was packaged in Windows, it's very likely that the executable bit was lost when packaging. Could that be the case?

**Comment by jrvidal** [comment]
Which executable bit? AFAICT `terminateProcess.sh` is not executable in the repo:
```
$ git ls-tree 1cc1046f8f72d68ce24ceca6694759b335e57125  # client/src/utils in e26ed9483dde92d0e483493e191a62e04a55e1f6
100644 blob da81da6cf6938bb91a86ae06e2eac0c12a910e9f	async.ts
100644 blob 572b90d7241fdd2ccf1caa0aa5c58061c45684d7	is.ts
100644 blob d85aec29530c440412709983b9867379bd318b79	processes.ts
100644 blob d86baa7c59436f12ca78b8d71653bd90842c46d8	terminateProcess.sh
100644 blob f09ee1fc42e2005771c49da0648890256809dd30	uuid.ts
```

**Comment by joaomoreno** [comment]
@dbaeumer

**Comment by dbaeumer** [comment]
@joaomoreno  Yes, I package the extension under Windows. If I would do in a docker container under Linux the bit would be kept? Or could I convince vsce to keep it.

**Comment by joaomoreno** [comment]
VSCE doesn't have that functionality right now. We can add it if needed. Might be easiest to setup an automated CI in Azure Pipelines on Linux, tho.

**Comment by dbaeumer** [comment]
OK. Will look into how I could best fix this.

**Comment by dbaeumer** [comment]
Fix by setting the executable bit in Git which is now preserved. 
![capture](https://user-images.githubusercontent.com/1931590/65337387-52c38c00-dbc8-11e9-9cdc-304d60371afa.png)
