### ISSUE TITLE
Consider closing pipe/socket when stopping the client

### ISSUE THREAD

**Issue by matklad** [Microsoft/vscode-languageserver-node#485]
My understanding is that currently vscode client never closes the pipe to the server on exit: it just waits for the child process to terminate/forcefully kills it after a timeout. 

Closing the pipe/socket might be nicer: if the server is implemented using a blocking `read` call, not closing the pipe means that the server's reading thread could be blocked in the `read` until the whole process is teared down. This is unfortunate, because that means that finally blocks/destructors of the server might not be run. 

This could be handled on the server side by not doing the `read` call after the `exit` notification, but this need an explicit coding, and is a slight layering violation: transport layer needs to know about message semantics.

In contrast, if the client closes the file descriptor, the server's reading thread receives a read of size zero and gracefully exits without any special handling.

**Comment by matklad** [comment]
Implementation wise, I think adding

```typescript

void dispose() {
    super.dispose()
    this.socket.destroy()
}
```

here 

https://github.com/Microsoft/vscode-languageserver-node/blob/053149a76e7ec147347e41a5847a1cc4ccb3d541/jsonrpc/src/messageWriter.ts#L178

should do the trick

**Comment by matklad** [comment]
Hm, and looks like the "forcefully kills it after a timeout." is not always working? See https://github.com/rust-analyzer/rust-analyzer/pull/1153

**Comment by jrvidal** [comment]
> Hm, and looks like the "forcefully kills it after a timeout." is not always working? See rust-analyzer/rust-analyzer#1153

FWIW I reported that in https://github.com/Microsoft/vscode-languageserver-node/issues/484

**Comment by dbaeumer** [comment]
@matklad thanks for the suggestion.
