### ISSUE TITLE
How to support CancellationToken?

### ISSUE THREAD

**Issue by APerricone** [Microsoft/vscode-languageserver-node#486]
Hello, in my implementation I have:

```js
var server = require('vscode-languageserver')
var connection = server.createConnection(
        new server.IPCMessageReader(process), 
        new server.IPCMessageWriter(process));
connection.onCompletion((param, cancelled)=> 
{
   var completitions
   for //every possible cancellation
   {
      if//Check for add this completion
         completitions.push(/*ThisCompletition*/)
      if(cancelled.isCancellationRequested) return server.CompletionList.create(completitions,false);
   }
  return server.CompletionList.create(completitions,true);
}
```
But I think, while my code run the messages are not processed, so how can CancellationToken change?
Should I call something?
Thanks,

PS. If you prefer I can move this question on StackOverflow...

**Comment by dbaeumer** [comment]
No, it is fine here. 

You need to yield your code yourself by using process.nextTick(...) or process.setTimeout(...). This will allow the server to process incoming cancel notifications. 

I will close the issue. Please ping if this doesn't help.
