### ISSUE TITLE
insertText marked as deprecated

### ISSUE THREAD

**Issue by Razzeee** [microsoft/vscode-languageserver-node#492]
`insertText` marked as deprecated here:
https://github.com/microsoft/vscode-languageserver-node/blob/9de8809400b7c443bc25f211dfaddcb74675b2d7/types/src/main.ts#L1467

The docs say to use `textEdit` instead, which is misleading. As the only way I can create working snippets is to populate `insertText`.

**Comment by rcjsuen** [comment]
@Razzeee I don't have this problem with my language server. Which LSP client(s) are you having issues with?

**Comment by Razzeee** [comment]
VSCode is what I tested.

This works for me, but uses the deprecated field.

https://github.com/elm-tooling/elm-language-server/blob/master/server/src/providers/completionProvider.ts#L222-L238

I also tried, this which didn't seem to work (I just typed this up again without an working editor, it may have errors):

```js
  private createSnippet(
    label: string,
    snippetText: string | string[],
    markdownDocumentation: string | undefined,
	position: Position
  ): CompletionItem {
    return {
      documentation: {
        kind: MarkupKind.Markdown,
        value: markdownDocumentation ? markdownDocumentation : "",
      },
      textEdit: TextEdit.insert(position, snippetText),
      insertTextFormat: InsertTextFormat.Snippet,
      kind: CompletionItemKind.Snippet,
      label,
    };
}
```

**Comment by rcjsuen** [comment]
@Razzeee Your code looks very similar to [mine](https://github.com/rcjsuen/dockerfile-language-service/blob/c4c9502af172be0d52c7d0d0cc0b87d5c84fa528/src/dockerAssist.ts#L672-L688) anyway.

Although I don't understand why `snippetText` is a `string | string[]`. It should only be a `string`. It doesn't look like `string[]` is supported.

https://github.com/microsoft/vscode-languageserver-node/blob/c1e8923f8ea3b1f9c61dadf97448244d9ffbf7ae/types/src/main.ts#L684-L691

**Comment by Razzeee** [comment]
`string[]` was a copy and paste error, ignore that.

**Comment by dbaeumer** [comment]
@Razzeee the actual conversion happens here: https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/protocolConverter.ts#L387. Can you check if your code runs through that correctly?

**Comment by dbaeumer** [comment]
This works for me as expected:

```ts
connection.onCompletion((params, token): CompletionItem[] => {
	let item = CompletionItem.create('negate');
	item.insertTextFormat = InsertTextFormat.Snippet;
	item.textEdit = TextEdit.insert(params.position, 'negate ${1:number}');
	return [
		item
	]
});
```

**Comment by Razzeee** [comment]
So i tested this again, both cases add the snippet correctly and I can find it via `control+space` and some scrolling.

`textEdit`: if I type negate, it does not show up in the completions. but if i hit `control+space` and type it does complete.
`insertText`: seems to work, but not when you already have another item with the same label. as I have a `negate` snippet and a `negate` function, that's not good.

**Comment by dbaeumer** [comment]
Here is what I see:

![cast](https://user-images.githubusercontent.com/1931590/58168985-e1aeaf00-7c8f-11e9-8718-a01a60673217.gif)

To make sure we talk about the same thing can you please create a test case I can clone. You can take https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-sample as a starting point.

**Comment by Razzeee** [comment]
I pushed an example here https://github.com/Razzeee/vscode-extension-samples/tree/completion-text-edit

This is when using `editText`
![Peek 2019-05-22 19-54](https://user-images.githubusercontent.com/5943908/58197043-be095a00-7ccb-11e9-80c5-9715a1f9576a.gif)

So it seems like the matching not happens? I tried to set `filterText` and `sortText`, but that did not change anything.

**Comment by dbaeumer** [comment]
The problem is that the insert position for the text edit needs to cover the whole region to be replaced not only the remaining part. So if the user types `T` and then code complete is computed the insert edit needs to look like

```ts
textEdit: TextEdit.insert(Position.create(position.line, position.character - 1), 'TypeScript'),

```

This being said I think we should consider to un-deprecate `insertText` since there we do the prefix matching automatically since both are strings.

**Comment by dbaeumer** [comment]
Done.

**Comment by rcjsuen** [comment]
Well, that changes thing. I'll have to start including `insertText` again then...

**Comment by dbaeumer** [comment]
@rcjsuen can you let me know where you need to include it again. Testing this showed that only having text edit makes things unnecessary complicated for simple use cases.

**Comment by rcjsuen** [comment]
@dbaeumer I basically stopped including `insertText` in my `CompletionItem`s after I realized it was deprecated (try to save "space" on JSON responses).

My completions are either:

- as-is on one line
- snippets with `$1` and `$2` and so on on one line

I do **not** have anything that spans multiple lines.

Should I start including `insertText` in my `CompletionItem`s again or no? Thank you for your clarification!

**Comment by dbaeumer** [comment]
No, there is no need to switch back to `insertText`

**Comment by thesmallbang** [comment]
I think this still needs reviewed. Your type documentation states that insertText is depreciated and to use editText but the official vscode documentation state exactly the opposite.

https://github.com/microsoft/vscode/issues/75859#issuecomment-504323594
