### ISSUE TITLE
Python 3.7 - f-strings showing invalid syntax error

### ISSUE THREAD

**Issue by shivendra90** [microsoft/vscode-languageserver-node#494]
There is an issue open on the vscode-python repo about non functioning f-strings. The OP posted the issue when using Python 3.6 and it's still open. I'm having similar problems running  code that has several f-strings and I get an invalid syntax whenever a f-string is run.

Reproducing is simple, using Python 3.7.3:
```
world = "world"
print(f"Hello {world}!")

Invalid Syntax: print(f"Hello {world}")
```
I'm not sure if this is the right place to post this bug but one of the members in the original thread requested to post it under a language server repo and this is the only one I was able to find.

**Comment by rcjsuen** [comment]
@shivendra90 This repository is probably not what you want. What is the original GitHub issue link?

**Comment by shivendra90** [comment]
@rcjsuen [This](https://github.com/microsoft/vscode-python/issues/5210#issuecomment-495859320) is the reply to the original thread.

**Comment by shivendra90** [comment]
Found the appropriate repo this time. Closing.
