### ISSUE TITLE
Use language server to validate front-matter (document being partially yaml)?

### ISSUE THREAD

**Issue by MrDienns** [microsoft/vscode-languageserver-node#499]
Hello,

We are trying to create a small DSL, which includes a front-matter on top of the document. This means that part of the document is yaml while the rest is our own syntax. What I am trying to achieve is to use this language server to validate this front-matter (the yaml part) and ignore the rest. Note that all features should still work; validation, suggestions, autocompletion, and so forth.

I've tried filtering out the yaml and only sending that to the client (by manually sending notifications and creating the parameters) but it seems like there's something already sending a notification every time I save (which clashes with what I'm doing manually). We already have our schema's ready.

For some extra information, please assume that my text document looks something like this:
```
---
name: Dennis
description: test
someObject:
    someValue: 1
---
My
    Cool
Custom
    DSL
Syntax
    Here
```

Is there any way I can use use this language server easily by tricking the client into sending only the yaml bit to the server and thus only validating that?

Would appreciate any help!

**Comment by dbaeumer** [comment]
The problem might be that the server does some dynamic registration for certain events. Do you reuse the ESLint client / extension code as well or have you written your own?
