### ISSUE TITLE
wrong node version used during installServerIntoExtension

### ISSUE THREAD

**Issue by NigelRook** [microsoft/vscode-languageserver-node#50]
installServerIntoExtension invokes `npm update` with the currently active node version. If this version is not v5.x, any native packages (eg. oniguruma) will be compiled with the incorrect NODE_MODULE_VERSION, and can not be loaded in VSCode.

**Comment by NigelRook** [comment]
Though, in retrospect. this is probably more of an issue with how VSCode itself runs its compile scripts. adding the --engine-strict flag might make spotting the error easier, but otherwise this is probably out of scope here.

**Comment by dbaeumer** [comment]
The script it actually deprecated. The new way to setup the extension and server is documented in the lsp example here: https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-sample

I added a log statement to the script.
