### ISSUE TITLE
language client's output channel is not removed when stopping/disposing

### ISSUE THREAD

**Issue by bcanzanella** [microsoft/vscode-languageserver-node#500]
I'm seeing the `outputChannel not being removed on disposal` issue again. Previously reported below:

https://github.com/microsoft/vscode-languageserver-node/issues/87
https://github.com/microsoft/vscode-languageserver-node/issues/224

I'm using vscode-languageclient version 5.2.1, and I have an example of it here: https://github.com/bcanzanella/vscode-extension-samples/commit/eb0400a29a2c424b18dbdb461e0c8e9eeeec7cb8

**Comment by Gama11** [comment]
I've also been seeing this issue again recently...
