### ISSUE TITLE
Language client never sends selection range requests even if supported by server

### ISSUE THREAD

**Issue by mattacosta** [microsoft/vscode-languageserver-node#501]
I'm not sure if this is a bug, or it's not implemented, or if I'm just doing something wrong, but I set the selection range capability of my language server to `true` and added the appropriate callback only for it to never receive selection range requests. I then checked the client capabilities that my server receives and `selectionRange` is always `undefined` as well.

I was finally able to get everything working by going into my language client and copy/pasting the [default provider implementation](https://github.com/microsoft/vscode-languageserver-node/blob/8801c20b667945f455d7e023c71d2f741caeda25/client/src/selectionRange.ts#L64-L76) into it and then calling `languages.registerSelectionRangeProvider()`, so I guess it was just never registered?

**Comment by dbaeumer** [comment]
Selection ranges are only available in the next version of the libraries (e.g. 5.3.0-next.6 for the client and 5.3.0-next.8 for the server)

**Comment by dbaeumer** [comment]
Please ping if you already use the next version.

**Comment by dbaeumer** [comment]
To opt into them you need to call `client.registerProposedFeatures();` and create the server connection using `let connection = createConnection(ProposedFeatures.all);` 

This is done that way since the API can still change for proposed features.

**Comment by mattacosta** [comment]
Yes, I just double checked and can confirm those are the versions being used.

**Comment by dbaeumer** [comment]
Strange, it works for me:

<img width="783" alt="capture" src="https://user-images.githubusercontent.com/1931590/60960598-a97c3200-a30a-11e9-9754-79ab64e8ac04.png">

**Comment by dbaeumer** [comment]
I hit the breakpoint on my server with the latest version of the libs. Please note that it requires VS Code version 1.35. as well.

**Comment by mattacosta** [comment]
Just to clarify, I should have `client.registerProposedFeatures()` and `createConnection(ProposedFeatures.all, ...)` even when using the latest versions, right? As long as I add the first one, my server works with or without the second one. This is with the latest insiders.

**Comment by rcjsuen** [comment]
@mattacosta Yes, it is a requirement because it is not official API yet.

**Comment by mattacosta** [comment]
My confusion must be around the finalization process then. In earlier versions, I would expect to need the proposed feature calls, but in the latest version the selection range stuff was moved out of the *.proposed.ts files, so I figured that the API was, well, no longer proposed.

**Comment by dbaeumer** [comment]
It is still half proposed :-). Sorry for that. reason being is that it is not official in the LSP specification. This happens in August.
