### ISSUE TITLE
LSP/Vscode : how to connect vscode client to my own server

### ISSUE THREAD

**Issue by houdaM97** [microsoft/vscode-languageserver-node#502]
I want to create a client side which is a vscode extension in order to communicate with the new language server written in OCaml by LSP. After looking at the LSP sample in vscode documentation i find those lines of code that i couldn't adapt to my situation :

`// The server is implemented in node
let serverModule = context.asAbsolutePath(path.join('server', 'out', 'server.js'));
// The debug options for the server
// --inspect=6009: runs the server in Node's Inspector mode so VS Code can attach to the server for debugging
let debugOptions = { execArgv: ['--nolazy', '--inspect=6009'] };

// If the extension is launched in debug mode then the debug server options are used
// Otherwise the run options are used
let serverOptions: ServerOptions = {
run: { module: serverModule, transport: TransportKind.ipc },
debug: {
module: serverModule,
transport: TransportKind.ipc,
options: debugOptions
}
};`

Because i don't have server.ts file in my project where can i get the server options which i need in order to create the language client?

**Comment by dbaeumer** [comment]
The server options can be either an executable, a node module or a function returing a child process or stream infos. See https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/main.ts#L144

For your case your either use `Executable` or a function.

**Comment by houdaM97** [comment]
thank you for your reply,
i have a question about the serverModule. If my own server is written in OCaml 'server.ml' what do i need to have in this line of code : 

let serverModule = context.asAbsolutePath(path.join('server', 'out', 'server.js'));

is it let serverModule = context.asAbsolutePath(path.join('XX', 'XX', 'server.ml')); ?

**Comment by rcjsuen** [comment]
@houdaM97 How do you usually run OCaml files from the command line?

**Comment by houdaM97** [comment]
i'm running OCaml usually using OCamlbuild command

**Comment by dbaeumer** [comment]
Yes, but you need to use a `Executable` server option and tell to use the `OCamlbuild` command.
