### ISSUE TITLE
Can we allow `isTrusted` configuration for MarkdownString?

### ISSUE THREAD

**Issue by MangelMaxime** [microsoft/vscode-languageserver-node#503]
In VSCode `MarkdownString` can have a property `isTrusted` set to `true` in order to:

> Indicates that this markdown string is from a trusted source. Only trusted markdown supports links that execute commands, e.g. [Run it](command:myCommandId).

Currently, it seems that we don't have an option to configure it. [Source](https://github.com/microsoft/vscode-languageserver-node/blob/58551741af1d90dd96d9c8a5b0069619884d8f22/client/src/protocolConverter.ts#L279-L312)

Would it be possible to add a way to configure `isTrusted` property?

My use case would be to allow people to click on a type definition inside a tooltip and see the documentation of that types in a documentation panel. This is already something we are doing from inside that documentation panel.

**Demo**

![2019-07-12 12 56 21](https://user-images.githubusercontent.com/4760796/61123438-a0bf6380-a4a4-11e9-8cd4-d91f8cc20c4d.gif)

**Use case**

The user could click on `string` to see that type documentation.

<img width="820" alt="Capture d’écran 2019-07-12 à 12 56 49" src="https://user-images.githubusercontent.com/4760796/61123496-c9dff400-a4a4-11e9-9f76-0200f739643c.png">

**Comment by rcjsuen** [comment]
@MangelMaxime 

1. Are you suggesting to only configure this for Visual Studio Code or are you suggesting an addition to the language server protocol?
1. As a server, when would I ever want to set `isTrusted` to `false`? Is this the difference between the server generating the documentation themselves and the server farming out to a third-party service for calculating the URL so it might not be trustworthy?

**Comment by MangelMaxime** [comment]
> Are you suggesting to only configure this for Visual Studio Code or are you suggesting an addition to the language server protocol?

If I understand correctly the server protocol is expecting a `string` or `markdown string` and it will sanitize it.

[Hover documentation](https://microsoft.github.io/language-server-protocol/specification#textDocument_hover)

However, Visual Studio Code is adding an extra layer of protection by not allowing by default the execution of command URL.

If I pass the following markdown:

```markdown
[string](command:fsharp.showDocumentation)


[https://google.com](https://google.com)
```

I get this result:

<img width="243" alt="Capture d’écran 2019-07-12 à 13 19 01" src="https://user-images.githubusercontent.com/4760796/61124669-c1d58380-a4a7-11e9-8a92-321df6a173e7.png">

The `https://google.com` link is working but `string` link has been protected.

So for me this should be an addition to `vscode-languageserver-node` API as it's the layer responsible for converting the `markdown` into a `MarkdownString` instance.

Others language server (for others IDE) don't know about this security feature as it's specific to VSCode implementation.

>     2\. As a server, when would I ever want to set `isTrusted` to `false`? Is this the difference between the server generating the documentation themselves and the server farming out to a third-party service for calculating the URL so it might not be trustworthy?

I would say you never want to set `isTrusted` to `false` unless you are not trusting your dependencies or third party service. 

But because this is a security layer I proposed to make to configurable by the maintainer decision. We could also decide to always set it to `true`.

**Comment by MangelMaxime** [comment]
Hello @rcjsuen ,

I give a second think about this issue and your questions.

I think we should simply just set `isTrusted` to `true` all the time. 

Would you accept a PR doing that?

**Comment by octref** [comment]
I'm looking at the same thing and you can see the `isTrusted` design rationale in https://github.com/microsoft/vscode/issues/29076 and https://github.com/microsoft/vscode/issues/33577.

It would make sense to me to add an option/method for `LanguageClient` to always enable `isTrusted`.

**Comment by rcjsuen** [comment]
@MangelMaxime I don’t work for Microsoft so I can’t speak to your question about a PR but I agree with what @octref has proposed in any case.

**Comment by dbaeumer** [comment]
@octref agree that this should be an option on the client side. It should be off by default

@MangelMaxime I would accept a PR.

Should be added to the client options here: https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/client.ts#L460

Something like `markdown: { isTrused: boolean }`

**Comment by manav-a** [comment]
I would also like to see this be possible. Is there any update on this issue?

**Comment by dbaeumer** [comment]
Here is what I did to address this:

- client options can now specify a `markdown: { isTrused: boolean }`.
- ensured that clients can tweak that in the middleware

I decided to not add this as a concept to LSP since this is very VS Code specific.
