### ISSUE TITLE
Can we get "open" events for already open editors?

### ISSUE THREAD

**Issue by Razzeee** [microsoft/vscode-languageserver-node#504]
So I'm basically using `open`, `change` on a text document to control, what happens. Which works fine, if VSCode doesn't save your previously opened files for that project.
At the moment my code needs a file to have an "open" to unlock the other code paths.

https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L7849-L7861
Basically says, that open won't be called if a file is already in your visible editors. 

So what am I missing here? This also does seem to ignore that aspect https://github.com/Microsoft/vscode-languageserver-node/blob/73180893ca/server/src/main.ts#L124

**Comment by Razzeee** [comment]
This would also need a new function on `TextDocuments` that is able to add items to the document list. https://github.com/Microsoft/vscode-languageserver-node/blob/73180893ca/server/src/main.ts#L126

Looking around for a solution today made me aware, that even the lsp-sample seems to suffer from this https://github.com/microsoft/vscode-extension-samples/blob/master/lsp-sample/server/src/server.ts

**Comment by rcjsuen** [comment]
@Razzeee What is the exact scenario you are describing?

1. Open a file for the language your language server supports.
1. Check that the language features are working.
1. Ensure that VS Code preserves opened editors across restarts.
1. Close VS Code.
1. Restart VS Code.
1. Editor is restored as expected without any user action.
1. Wait for the language server to start up.
1. Try out some language features in the (already) opened editor but now they don't work.

Is the above correct?

**Comment by Razzeee** [comment]
Correct.

**Comment by dbaeumer** [comment]
Actually this works for me. When the language client is up and the server is initialized it syncs all open editor documents to the server here: https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/client.ts#L794

But as said they are only synced after the server has been initialized. 

Can you explain in more detail when you see this behaviour.

**Comment by Razzeee** [comment]
Sorry, meant to close it, was due to a refactoring that I reverted. Where I basically missed the `open` on start due to the server still setting up.

https://github.com/elm-tooling/elm-language-server/commit/159ec787056ff3f78a7bd628c95dbf50a8997d9e

I'm still trying to find a way that what I reverted to work. It would be really handy if there was something between `initalize` and `initalized`, where events are not yet setup, but the client configuration is already available.

**Comment by dbaeumer** [comment]
Not sure I understand the request. The client is initialized when the server has received the `initialized` request. What exactly are you looking for?

**Comment by Razzeee** [comment]
At the moment I'm doing my own init (going through some files and grabbing some things) before setting up the listeners.

1. Initialize (configuration is not yet ready/available)
2. Initialized (event's are generated by the client and I need to act, but I haven't initialized my own stuff yet)


So I'm caught between `Error: Unhandled method workspace/configuration`
 if I try it in initalize.
Or `[Error - 12:11:39 AM] Request textDocument/documentSymbol failed.
  Message: Unhandled method textDocument/documentSymbol
  Code: -32601 `
if I do it in initialized. I guess that's due to the server expecting all listeners to be already setup correctly. If I would first set them up and then do my init, it will probably work, but I will miss out on the first round of most events, which would lead to a bad experience.
Maybe/hopefully I'm missing something.

**Comment by Razzeee** [comment]
Or if I get it to wait correctly my init seems to take that long, that I'm missing out on the open calls, which was where this issue originated.
https://github.com/elm-tooling/elm-language-server/commit/955a1df9ed740595ed9077711fdd92e5f40baee9

**Comment by dbaeumer** [comment]
I have to say I am still not understanding this. Are you talking about the client or server side. And what kind of listeners are you setting up.

**Comment by Razzeee** [comment]
Server side.
This is the init, which is fine at the moment, but as soon as I change the implementation to take longer (due to a call to another binary) it fails. https://github.com/elm-tooling/elm-language-server/blob/master/src/server.ts#L91

The providers in the following lines setup listeners in the `this.connection.onDocumentFormatting(this.handleFormattingRequest);` kind of way. https://github.com/elm-tooling/elm-language-server/blob/master/src/providers/documentFormatingProvider.ts#L19

**Comment by Razzeee** [comment]
So I started to look around to figure out how other servers handle this.

Vetur seems to just send all config items https://github.com/vuejs/vetur/blob/master/client/client.ts#L16 on startup as  as `intializationOption` https://github.com/vuejs/vetur/blob/master/client/client.ts#L46

I guess this works fine, but feels a bit like a workaround :)

**Comment by dbaeumer** [comment]
I think this needs to be handle in the application layer. The VS Code client library for example does the same when it comes to open documents. When hooking the listener in VS Code's API there could already be open document and the user could have opened some between the time when the listener is hooked and the server is ready. So I queue those and replay events for already open documents.

In general I think this is the nature of async programming :-)
