### ISSUE TITLE
requiring file within workspace throws if file requires a module with org namespace

### ISSUE THREAD

**Issue by knownasilya** [microsoft/vscode-languageserver-node#508]
```js
connection.onInitialize(async (params: InitializeParams) => {
	// Initially load the config
	let settings = await getDocumentSettings();
	if (params.rootPath) {
		subsetConfig = require(path.join(params.rootPath, settings.configPath));
	}

        return {
		capabilities: {
			textDocumentSync: documents.syncKind,
			// Tell the client that the server supports code completion
			completionProvider: {
				resolveProvider: true
			}
		}
	};
});
```

Which imports a file called `.subsetcss.js` from the workspace, which looks like so:

```js
const polished = require('polished');
const { getVariables } = require('@subsetcss/config-helpers');
// ...more
```

The error is:

```
[Error - 2:51:29 PM] Server initialization failed.
  Message: Request initialize failed with message: Cannot find module '@subsetcss/config-helpers'
  Code: -32603 
```

Installed with npm or yarn, no difference.
Also if I remove the namespaced import, everything works fine with the `polished` library.
You can see `@subsetcss/config-helpers` here: https://github.com/subsetcss/config-helpers
The server can be found here: https://github.com/subsetcss/vscode-language-server/blob/master/server/src/server.ts#L59

**Comment by dbaeumer** [comment]
@knownasilya can you explain to me why you think this is a problem of the LSP server library. In your case you ask node to load a library which fails with an exception. What else should the server do then letting the initialization fail. 

And please be aware that path.rootPath points to the workspace folder. Loading files from the wortkspace folder is relatively tricky especially in node. You might want to have a look how the ESLint server does this using https://github.com/Microsoft/vscode-languageserver-node/blob/master/server/src/files.ts#L42

**Comment by knownasilya** [comment]
@dbaeumer I probably want something like eslint has. This might be a good thing to include as a helper as part of the api.

**Comment by knownasilya** [comment]
Closing this because it seems the issue was on my end. The publish of the module didn't work as expected. Thanks for the help!
