### ISSUE TITLE
Clarify the `contentChanges` in `DidChangeTextDocumentParams`

### ISSUE THREAD

**Issue by kenkangxgwe** [microsoft/vscode-languageserver-node#509]
In the specification, the state transition of multiple `TextDocumentContentChangeEvent` is listed below, where I assume that `contentChanges = [c1, c2]`, and the `textDocument` is changed from `s` to `s'` and then to `s''`.

https://github.com/microsoft/vscode-languageserver-node/blob/58551741af1d90dd96d9c8a5b0069619884d8f22/protocol/src/protocol.ts#L1286-L1291

However, in [VSCode Vim mode](https://github.com/VSCodeVim/Vim), when I try to paste a `)` to overwrite a `}`, by <kbd>v</kbd><kbd>p</kbd>, the log tells me that the `contentChanges` in the `didChange` notification sent is 

``` javascript
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 88,
                    "character": 25
                },
                "end": {
                    "line": 88,
                    "character": 25
                }
            },
            "rangeLength": 0,
            "text": ")"
        },
        {
            "range": {
                "start": {
                    "line": 88,
                    "character": 25
                },
                "end": {
                    "line": 88,
                    "character": 26
                }
            },
            "rangeLength": 1,
            "text": ""
        }
    ]
``` 

This is exactly the reverse order of [c1, c2]. Maybe more explanation should be added or is it a bug from the VSCode vim extension?

**Comment by dbaeumer** [comment]
This indeed looks strange.

**Comment by dbaeumer** [comment]
It works correctly when not in Vim Mode.

**Comment by dbaeumer** [comment]
I can not reproduce this. Here is what I do

- have a `}` on line 0
- copy a `)`
- position the cursor over `}`
- paste over using vp

I get the following notification sent

```
[Trace - 2:23:52 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "vscode-file:///c%3A/Users/dirkb/Projects/mseng/VSCode/Playgrounds/bat/test.bat",
        "version": 8
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 0
                },
                "end": {
                    "line": 0,
                    "character": 1
                }
            },
            "rangeLength": 1,
            "text": ""
        },
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 0
                },
                "end": {
                    "line": 0,
                    "character": 0
                }
            },
            "rangeLength": 0,
            "text": ")"
        }
    ]
}
```

which is correct.

I will close the issue.

@kenkangxgwe if you can reproduce this on the latest version please provide detailed steps on how to do this.

**Comment by kenkangxgwe** [comment]
This is a way that, I believe, you can reproduce it:

0. With Vim mode on.

1. Open a new file and select a language so that you may trace the messages (`batch` file in your example).

2. type a `}`.

3.  use <kbd>Ctrl+Shift+P</kbd> to execute `Developer: Reload Window` command.

4. type a `)` and use <kbd>x</kbd> to delete it (to the clipboard).

5. put the cursor block on the `}` and press <kbd>vp</kbd> to overwrite the `}` with `)`.

6. see the trace to figure out what is in the `didChange`'s `params`.

This seems to be a bug, but I have no ideas about whom to blame.

**Comment by dbaeumer** [comment]
Followed your steps but I still get:

```
[Trace - 12:02:05 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "vscode-file:///c%3A/Users/dirkb/Projects/mseng/VSCode/Playgrounds/bat/new.bat",
        "version": 13
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 0
                },
                "end": {
                    "line": 0,
                    "character": 1
                }
            },
            "rangeLength": 1,
            "text": ""
        },
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 0
                },
                "end": {
                    "line": 0,
                    "character": 0
                }
            },
            "rangeLength": 0,
            "text": ")"
        }
    ]
}
```

which is correct.

Can you add the Vim modes you are in when doing this ? May be that makes a difference
