### ISSUE TITLE
Module '"vscode"' has no exported member 'DocumentSymbol'.Module '"vscode"' has no exported member 'DefinitionLink'.

### ISSUE THREAD

**Issue by YLQZ** [microsoft/vscode-languageserver-node#510]
These are my dependencies:
```
 "dependencies": {
	"vscode": "^1.1.36",
	"vscode-languageclient": "^5.2.1"
}
```
vscode  last publish  14 days ago
vscode-languageclient  last publish 2 months ago

there are more problem like title

mail:1194979849@qq.com

**Comment by dbaeumer** [comment]
@YLQZ using `vscode` is deprecated since it requires running a script to install the vscode.d.ts file. You better do the following:

```
	"devDependencies": {
		"@types/vscode": "^1.37.0"
	},

```
