### ISSUE TITLE
Completion requests are not sent when typing in a snippet

### ISSUE THREAD

**Issue by alexander-novo** [microsoft/vscode-languageserver-node#513]
When typing with a snippet-spawned cursor (i.e. from a snippet like `'<$1>'`), completion requests are not sent to the server. This can be resolved by moving the cursor elsewhere and then back to the original spot, where typing will send a completion request again.

**Comment by dbaeumer** [comment]
@alexander-novo I am pretty sure that this is also the case for the VS Code extension API. Do you see the same only using that? The LSP library basically forwards requests it receives from the VS Code API.
