### ISSUE TITLE
Hover Request is sent over and over again

### ISSUE THREAD

**Issue by stfuzz** [microsoft/vscode-languageserver-node#514]
When hovering something in VS Code, sometimes the same request to the language server is sent over and over again while hovering. The request is properly resolved by the server. If the request takes long to be answered (e.g. 500ms) it will continue to send the same request although it might not be hovered anymore.

I am using [Omnisharp](https://github.com/OmniSharp/csharp-language-server-protocol) on the server side and VS Code ("vscode-languageclient": "^3.4.2") on the client side.

**Comment by dbaeumer** [comment]
Actually the library exactly forwards what it receives from the VS Code extension host. @stfuzz can you reproduce this using the VS Code API?

**Comment by stfuzz** [comment]
@dbaeumer thanks for looking into this issue!

Do you mean this one:
[https://code.visualstudio.com/api/references/vscode-api#HoverProvider](https://code.visualstudio.com/api/references/vscode-api#HoverProvider)?

**Comment by dbaeumer** [comment]
@stfuzz Yes.

**Comment by stfuzz** [comment]
I'll check it out

**Comment by stfuzz** [comment]
Yes, it is the same behaviour!

Tested with this simple code snippet
```
vscode.languages.registerHoverProvider('xml', {
	provideHover() {
		console.log(Date.now());
		return {
			contents: ['Hover Content']
		};
	}
});
```

**Comment by stfuzz** [comment]
Shall I close this issue then and open another one in the vscode repo?

**Comment by dbaeumer** [comment]
@stfuzz yes, please do so.

**Comment by stfuzz** [comment]
thanks ✌

**Comment by stfuzz** [comment]
Oh, the contribution guideline of microsoft/vscode helped me find out that the issue was caused by the now deprecated plugin [https://github.com/bryphe/vscode-relative-line-numbers](https://github.com/bryphe/vscode-relative-line-numbers)

**Comment by dbaeumer** [comment]
Wow, good to know.
