### ISSUE TITLE
Allow an npm command prefix

### ISSUE THREAD

**Issue by SimonSimCity** [microsoft/vscode-languageserver-node#515]
I'm using `meteor`, which - in order to make it simple for the user - packs NPM and Node into it's development environment. I don't know if there are similar systems out there, but at least for Meteor it would be fine if you'd allow me to prefix the NPM command by `meteor` so it runs `meteor npm` instead of `npm`.

I guess this here is the right place, but I don't know how to take in something from a configuration.
https://github.com/microsoft/vscode-languageserver-node/blob/master/server/src/files.ts#L121

If there is another place like this where you run `node`, it would also apply there.

See:

* https://docs.meteor.com/commandline.html#meteornpm
* https://docs.meteor.com/commandline.html#meteornode

**Comment by dbaeumer** [comment]
Actually I think that having this in the server code as a mistake in the first place. A server that needs to resolve node modules should do this themselves since there are too many variables for this (different package managers and environments).

So I would like to close the issue unless you convince me otherwise.

**Comment by SimonSimCity** [comment]
Just so I get this right ...

You're saying that you'd rather drop this helper-methods `resolveGlobalNodePath()` and `resolveGlobalYarnPath()` in the long run?

Because Meteor in is just using `npm` as is - it just doesn't install it as a separate global command but wraps it into its own command.

It's very convenient when having different Meteor projects, since all commands are piped through the `meteor` command, which chooses the correct version of `npm` and `node` for my project. I don't have to use e.g. `nvm` to switch the versions anymore when switching form the one to the other project.

**Comment by dbaeumer** [comment]
The idea is to drop this from this library and ask servers to support this. For ESLint support for `meteor` should go into the ESLint server and not generally provided by the vscode server library.
