### ISSUE TITLE
Support ELECTRON_RUN_AS_NODE

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-languageserver-node#52]
Our next update of Electron will remove the deprecated ATOM_SHELL_INTERNAL_RUN_AS_NODE. To support both old and new world, I suggest to set both flags wherever you set ATOM_SHELL_INTERNAL_RUN_AS_NODE currently.

**Comment by dbaeumer** [comment]
@bpasero this is very bad since it requires all extensions to upgrade to a new version of the language server client. Is there any kind of work around? Actually we would need to bump up our VSCode major version number since it is from that respective a breaking change.

**Comment by bpasero** [comment]
@dbaeumer I am not sure what you mean by "workaround"? Electron removed ATOM_SHELL_INTERNAL_RUN_AS_NODE and replaced it with (the previous already existing) ELECTRON_RUN_AS_NODE. Unless we fork Electron to bring the old environment variable back, I am not seeing a solution.

**Comment by dbaeumer** [comment]
Fixed by supporting both properties.

@bpasero just out of interest. Is the old one still supported by Electron?

**Comment by bpasero** [comment]
@dbaeumer not as far as I know, I think it got removed once Electron moved to 1.x.
