### ISSUE TITLE
Improve the `textDocument/callHierarchy` extension 

### ISSUE THREAD

**Issue by MaskRay** [microsoft/vscode-languageserver-node#520]
Requested to create a new issue. I haven't looked closely to the latest updates.

Pasted from https://github.com/microsoft/vscode-languageserver-node/pull/420#issuecomment-513513964

I think the proposal has several deficiency that require further improvement. Comments inlined below:

```typescript
export interface CallHierarchyCall {
  // If there are multiple `CallHierarchyCall` elements with the same `from`, will the `from: CallHierarchySymbol` be duplicated multiple times?
  range: Range;
  from: CallHierarchySymbol;
  to: CallHierarchySymbol;
}
result: CallHierarchyCall[] | null

export interface CallHierarchySymbol {
  // There is no id field. `name` or `detail` may not identify a specific target that can be suitable for further requests (e.g. node expansion).
  name: string;
  detail?: string;
  kind: SymbolKind;
  uri: string;
  range: Range;
  selectionRange: Range;
}
```

In ccls (https://github.com/MaskRay/ccls/blob/master/src/messages/ccls_call.cc), we use:

```cpp
struct Out_cclsCall {
  Usr usr;  // language server specific
  std::string id;
  std::string_view name;
  Location location;
  CallType callType = CallType::Direct;
  int numChildren;
  // Empty if the |levels| limit is reached.
  std::vector<Out_cclsCall> children;
};
```

The method `$ccls/call` was designed so that the result can either be a hierarchy or a flattened list (like `textDocument/references`).

**Comment by dbaeumer** [comment]
@jrieken @aeschli FYI.

**Comment by jrieken** [comment]
We have discussed to model the call hierarchy as object graph and decided against it because it raises questions about loops, recursion, and depth. Instead we went with retrieving nodes only (and repeatedly). The latest proposal (which addresses some of your feedback) is here: https://github.com/microsoft/vscode/issues/70231#issuecomment-530387021

**Comment by KamasamaK** [comment]
The [VS Code API](microsoft/vscode#70231) has been finalized.

**Comment by kjeremy** [comment]
Since the VS Code API has been finalized can the LSP side be stabilized?

**Comment by dbaeumer** [comment]
Yes. A PR would currently speed this up :-).

**Comment by kjeremy** [comment]
@dbaeumer I don't see any steps for moving something out of the proposed state. Is that mechanically just moving everything out of `proposed` and updating the `md` file?

**Comment by kjeremy** [comment]
@dbaeumer I've updated the protocol for this in the protocol directory and I export the types but how do I see them under `client`?

**Comment by dbaeumer** [comment]
I merge the PR and did some cleanup work and added it to the spec.

**Comment by dbaeumer** [comment]
Closing the issue since the PR is merged.
