### ISSUE TITLE
sendRequest and sendNotification unclear

### ISSUE THREAD

**Issue by Yuhanun** [microsoft/vscode-languageserver-node#525]
So I'm writing a languageserver for a hobby-compiler of mine, im writing the server itself in Java, using the lsp4j framework / library, and I'm using the `@JsonNotification` thing, code is as follows

```java
public interface ExtendedLanguageClient extends LanguageClient {

    @JsonNotification("exampleLang/endpoint")
    void endpoint(HTMLString htmlString);
}
```

And I want to invoke this endpoint from the JS side of things (in VSCode)

I do this as follows:
```js
	client.onReady().then(() => {
		client.onNotification(new NotificationType(`exampleLang/endpoint`), (event: any) => {
			console.log(event);
		});
		console.log("Sending notif");
		client.sendNotification(new NotificationType(`exampleLang/endpoint`));
		console.log("Sent notif");
	});
```

But the onNotification event never gets called, any idea why? It's kind of urgent and the documentation on this specific function is very lacking.

I of course also tried to use sendRequest but it takes a `method`, and the rest isn't really that well documented.

Is there a proper documentation page I could look at?

Or maybe one of you could guide me in the right direction?

Thanks in advance.

**Comment by dbaeumer** [comment]
@Yuhanun `sendNotification` and `sendRequest` on the client API send a notification or a request to the server. The server API will send them to the client.

You might want to have a look at https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-sample for an example implementation of a server in node and an LSP client triggered from withing VS Code.

If you only want to implement your language as a pure VS Code extension please refer to the VS Code language API here: https://code.visualstudio.com/api/references/vscode-api#languages
