### ISSUE TITLE
Use of server to provide scope context around cursor

### ISSUE THREAD

**Issue by pke** [microsoft/vscode-languageserver-node#529]
I am sure I am just missing that in the documentation.
For my extension I would need to know if the cursor is currently inside an array in a js or json file.
It would be best to get the AST of that array somehow, but the text representation would be fine. I want to sort the array and create a `WorkspaceEdit` for the result (which ideally should not alter the original formatting.

Main question is: do the language servers for json (there does not seem to be one for JS) export the current documents structure?

**Comment by dbaeumer** [comment]
This is unrelated to this repsository. This is better discussed here: https://github.com/microsoft/vscode-json-languageservice
