### ISSUE TITLE
MarkupContent uses different font in Hover and CompletionItem

### ISSUE THREAD

**Issue by sumneko** [microsoft/vscode-languageserver-node#531]
![字体1](https://user-images.githubusercontent.com/5213431/67189166-5002c380-f420-11e9-8060-de77ba67008a.png)
![字体2](https://user-images.githubusercontent.com/5213431/67189171-51cc8700-f420-11e9-8a56-1464fcf80261.png)

The text in CompletionItem uses a non equal width font, ignoring my font settings in VSCode.

**Comment by dbaeumer** [comment]
@sumneko please file the issue against vscode. This is not controlled by the LSP and is up to the editor. 

I am pretty sure the same is true when using the VS Code API directly. The LSP doesn't tweak any font settings.
