### ISSUE TITLE
Declaration error

### ISSUE THREAD

**Issue by orblazer** [microsoft/vscode-languageserver-node#534]
Hello,
I tray to debug the extension https://github.com/onecentlin/laravel-blade-snippets-vscode.
I have update dependencies to the last version.

Dependencies :
- @types/node: 12.12.3
- vscode: 1.1.36
- vscode-css-languageservice: 4.0.2
- vscode-html-languageservice: 3.0.3
- vscode-languageclient: 5.2.1
- vscode-languageserver-types: 3.14.0

And when i run `npm run compile` but this is make that error :
```
node_modules/vscode-languageclient/lib/declaration.d.ts:1:75 - error TS2305: Module '"vscode"' has no exported member 'Declaration'.
1 import { Disposable, TextDocument, ProviderResult, Position as VPosition, Declaration as VDeclaration } from 'vscode';
                                                                            ~~~~~~~~~~~

node_modules/vscode-languageclient/lib/protocolConverter.d.ts:40:59 - error TS2694: Namespace '"vscode"' has no exported member 'LocationLink'.
40     asDeclarationResult(item: ls.DeclarationLink[]): code.LocationLink[];
                                                             ~~~~~~~~~~~~

node_modules/vscode-languageclient/lib/protocolConverter.d.ts:42:95 - error TS2694: Namespace '"vscode"' has no exported member 'Declaration'.
42     asDeclarationResult(item: ls.Declaration | ls.DeclarationLink[] | undefined | null): code.Declaration | undefined;
                                                                                                 ~~~~~~~~~~~                                                                                                                                                             
```

**EDIT** : OK i have look and is just because this is wrong path.
- The right path of `code.Declaration` is `ls.Declaration`
- For `code.LocationLink` is `ls.LocationLink`
- And for `Declaration as VDeclaration` this is need move to import from `vscode-languageserver-protocol`

Thanks.

**Comment by dbaeumer** [comment]
The reason is that you are compile against a very old VS Code version. See this in your package json file

```
    "engines": {
        "vscode": "^1.26.0"
    },

```

Move this up to `1.39` and things are fine.
