### ISSUE TITLE
MessageType is defined twice

### ISSUE THREAD

**Issue by ahe-humio** [microsoft/vscode-languageserver-node#536]
I'm using the node module vscode-languageserver-protocol@3.14.1 and have found that `MessageType` is defined twice.

This is a minor inconvenience as I'm auto-generating Scala case classes using the TypeScript Compiler API. Here's the output from my generator:

```
Duplicated definition of MessageType (Interface(64) -> undefined(524800)).
.../node_modules/vscode-jsonrpc/lib/messages.d.ts: 91:1
.../node_modules/vscode-languageserver-protocol/lib/protocol.d.ts: 933:1
.../node_modules/vscode-languageserver-protocol/lib/protocol.d.ts: 954:1
```

**Comment by dbaeumer** [comment]
```ts
/**
 * The message type
 */
export namespace MessageType {
	/**
	 * An error message.
	 */
	export const Error = 1;
	/**
	 * A warning message.
	 */
	export const Warning = 2;
	/**
	 * An information message.
	 */
	export const Info = 3;
	/**
	 * A log message.
	 */
	export const Log = 4;
}

export type MessageType = 1 | 2 | 3 | 4;
```

This is actually OK since TS supports this.

I will close the issue since this TS language feature is used very often in the protocol.

**Comment by ahe-humio** [comment]
What about MessageType from vscode-jsonrpc:

```
/**
 * An interface to type messages.
 */
export interface MessageType {
	readonly method: string;
	readonly numberOfParams: number;
}
```

**Comment by dbaeumer** [comment]
These are two different modules which of course can have the same names. MessageType in jsonrpc is renamed in protocol to RPCMessageType when used.

**Comment by ahe-humio** [comment]
Oh, sorry for the noise, I must not be interpreting the exports correctly in my generator. Thanks for letting me know.
