### ISSUE TITLE
Use TextDocumentEdits in completion and formatting

### ISSUE THREAD

**Issue by stamblerre** [microsoft/vscode-languageserver-node#541]
Is there a reason that `textDocument/completion` and `textDocument/formatting` use `TextEdits` rather than `TextDocumentEdits`? It would be helpful to associate a version with these requests. Thanks!

**Comment by rcjsuen** [comment]
This sounds more like a question for the [Microsoft/language-server-protocol repository](https://github.com/microsoft/language-server-protocol) to me.

**Comment by stamblerre** [comment]
Oh absolutely, I must've gotten confused between the two repositories. I'll move the issue there.
