### ISSUE TITLE
Allow a mixture of NodeModule and Executable in ServerOptions

### ISSUE THREAD

**Issue by disposedtrolley** [microsoft/vscode-languageserver-node#543]
Hello!

I'm writing a server which is going to be packaged as a standalone executable or globally installed NPM module. When debugging the client and server, I'd like to run the server as a `NodeModule` so I don't need to spend time building and packaging it, but while running normally I'd like to run it as an `Executable`.

The definition of the `ServerOptions` type in `vscode-languageclient` is the following:

```ts
export declare type ServerOptions = Executable | {
    run: Executable;
    debug: Executable;
} | {
    run: NodeModule;
    debug: NodeModule;
} | NodeModule | (() => Thenable<ChildProcess | StreamInfo | MessageTransports | ChildProcessInfo>);
```

which restricts the ability to use a mixture of `Executable` and `NodeModule` for run and debug configurations. Would it be possible to allow this behaviour in the future?

**Comment by dbaeumer** [comment]
As a tip: you can always pass in a function (e.g. `() => Thenable<ChildProcess | StreamInfo | MessageTransports | ChildProcessInfo>`) in which you could program that yourself.
