### ISSUE TITLE
JSON-RPC read buffer hangs onto a lot of memory if on big request or response is used.

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-languageserver-node#544]
https://github.com/microsoft/vscode/issues/84940#issuecomment-555440222

**Comment by alexandrudima** [comment]
There's one more performance aspect to it... If a response has 15MB, and it comes in chunks of 8KB, it means it will come in 1920 chunks. So 1920 times the `buffer` will be resized and the previous contents copied over.

**Comment by alexandrudima** [comment]
I'd also not feel so bad about it, it is a common issue that has hit even nodejs -- https://github.com/nodejs/node/issues/3145 -- https://github.com/italoacasas/node/commit/cdfa056ba111670341d5e5c03a5c377ef427a872

**Comment by mjbvz** [comment]
See https://github.com/microsoft/vscode-languageserver-node/commit/c4467373f9fc4f720ff3eca9cec531f1b45dbe79 for an example fix
