### ISSUE TITLE
language client throws error "items.map is not a function" for prepareCallHierarchy request

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-languageserver-node#548]
Error is described in the title. The root cause is the language client tries to iterate the result from prepareCallHierarchyRequest, which just returns a CallHierarchyItem instead of an array.

See source code in the file https://github.com/microsoft/vscode-languageserver-node/blob/master/client/src/callHierarchy.proposed.ts
```typescript
public prepareCallHierarchy(document: TextDocument, position: VPosition, token: CancellationToken): ProviderResult<VCallHierarchyItem> {
		const client = this.client;
		const middleware = this.middleware;
		const prepareCallHierarchy: PrepareCallHierachySignature = (document, position, token) => {
			const params = client.code2ProtocolConverter.asTextDocumentPositionParams(document, position);
			return client.sendRequest(CallHierarchyPrepareRequest.type, params, token).then(
				(result) => {
					return protocol2code.asCallHierarchyItems(this.client.protocol2CodeConverter, result);
				},
				(error) => {
					client.logFailedRequest(CallHierarchyPrepareRequest.type, error);
					return Promise.resolve(null);
				}
			);
		};
```

**Comment by testforstephen** [comment]
Just found the vscode api for call hierarchy provider is to return a callHierarchyItem for prepareCallHierarchy. See https://github.com/microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4018

But the protocol.callHierarchy.proposed.ts in the LSP is to return an array for prepareCallHierarchy, see https://github.com/microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.callHierarchy.proposed.ts#L125

So if we follow the LSP definition, no need to fix this.

**Comment by dbaeumer** [comment]
Actually the VS Code API will move to an array as well. So having an array in LSP is fine.
