### ISSUE TITLE
CallHierarchyIncomingCall.fromRanges comment is unclear

### ISSUE THREAD

**Issue by kjeremy** [microsoft/vscode-languageserver-node#552]
At:
https://github.com/microsoft/vscode-languageserver-node/blob/12b8b968b9d5c7f56493f0070895a491fab9bd52/protocol/src/protocol.callHierarchy.proposed.ts#L62-L66

Does that mean that each element of `fromRanges` is relative to the `from`'s `range` field? As in a range starting with 0 would point to `from.range.start`?

**Comment by dbaeumer** [comment]
No, that range values are relative to the beginning of the file (as always in LSP). I will clarify this.
