### ISSUE TITLE
How to use the new progress reporting stuff?

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode-languageserver-node#556]
I'm trying to figure out how we can use the new progress reporting from the Julia language server, but I'm stuck. I have some _very_ basic questions, but aren't able to find any documentation for them :)

First, do I need to code up the UI for this, or is it enough that our LS sends the correct messages, and then UI automatically appears in VS Code? So far I thought the UI would be handled for us by `LanguageClient`, but I'm no longer sure...

Our scenario is that we have a long running indexing operation in the LS and we want to show a progress bar for that.

What I'm doing right now is: I send a `window/workDoneProgress/create` message [1]. That seems to work, i.e. I get a response that seems to indicated everything is ok [2]. After that I send a `$/progress` message [3], but then I get an error message back [4].

Any help with this would be great!

I think as a meta-point, it would be really awesome if there was some reference documentation for `LanguageClient` and friends. The [existing documentation](https://code.visualstudio.com/docs/extensions/example-language-server) is great to get started, but it really is not very helpful beyond that (unless I'm missing something!).

[1] `{"method":"window/workDoneProgress/create","id":"98723548","params":{"token":"98237846234"},"jsonrpc":"2.0"}`
[2] `{"jsonrpc":"2.0","id":"98723548","result":null}`
[3] `{"method":"$/progress","id":"987256348","params":{"token":"98237846234","value":{"kind":"begin","title":"Julia indexing..."}},"jsonrpc":"2.0"}`
[4] `{"jsonrpc":"2.0","id":"987256348","error":{"code":-32601,"message":"Unhandled method $/progress"}}`

**Comment by dbaeumer** [comment]
Actually that looks OK to me. Here is the trace I see when testing this with the following code https://github.com/microsoft/vscode-languageserver-node/blob/dbaeumer/semanticTokens/testbed/server/src/server.ts#L156:

```
[Trace - 12:14:47 PM] Received request 'window/workDoneProgress/create - (20)'.
Params: {
    "token": "fb1e1bfa-465d-4831-9ed6-44faa076cbed"
}
[Trace - 12:14:47 PM] Sending response 'window/workDoneProgress/create - (20)'. Processing request took 0ms
No result returned.
[Trace - 12:14:47 PM] Received notification '$/progress'.
Params: {
    "token": "fb1e1bfa-465d-4831-9ed6-44faa076cbed",
    "value": {
        "kind": "begin",
        "title": "Validating",
        "percentage": 0,
        "message": "happy coding",
        "cancellable": true
    }
}
[Trace - 12:14:48 PM] Received notification '$/progress'.
Params: {
    "token": "fb1e1bfa-465d-4831-9ed6-44faa076cbed",
    "value": {
        "kind": "report",
        "percentage": 10
    }
}
[Trace - 12:14:49 PM] Received notification '$/progress'.
Params: {
    "token": "fb1e1bfa-465d-4831-9ed6-44faa076cbed",
    "value": {
        "kind": "report",
        "percentage": 20
    }
}
[Trace - 12:14:50 PM] Received notification '$/progress'.
Params: {
    "token": "fb1e1bfa-465d-4831-9ed6-44faa076cbed",
    "value": {
        "kind": "report",
        "percentage": 30
    }
}
[Trace - 12:14:51 PM] Received notification '$/progress'.
Params: {
    "token": "fb1e1bfa-465d-4831-9ed6-44faa076cbed",
    "value": {
        "kind": "report",
        "percentage": 40
    }
}
[Trace - 12:14:52 PM] Received notification '$/progress'.
Params: {
    "token": "fb1e1bfa-465d-4831-9ed6-44faa076cbed",
    "value": {
        "kind": "report",
        "percentage": 50
    }
}
[Trace - 12:14:53 PM] Received notification '$/progress'.
Params: {
    "token": "fb1e1bfa-465d-4831-9ed6-44faa076cbed",
    "value": {
        "kind": "report",
        "percentage": 60
    }
}
[Trace - 12:14:54 PM] Received notification '$/progress'.
Params: {
    "token": "fb1e1bfa-465d-4831-9ed6-44faa076cbed",
    "value": {
        "kind": "report",
        "percentage": 70
    }
}
[Trace - 12:14:55 PM] Received notification '$/progress'.
Params: {
    "token": "fb1e1bfa-465d-4831-9ed6-44faa076cbed",
    "value": {
        "kind": "report",
        "percentage": 80
    }
}
[Trace - 12:14:56 PM] Received notification '$/progress'.
Params: {
    "token": "fb1e1bfa-465d-4831-9ed6-44faa076cbed",
    "value": {
        "kind": "report",
        "percentage": 90
    }
}
[Trace - 12:14:57 PM] Received notification '$/progress'.
Params: {
    "token": "fb1e1bfa-465d-4831-9ed6-44faa076cbed",
    "value": {
        "kind": "report",
        "percentage": 100
    }
}
[Trace - 12:14:58 PM] Received notification '$/progress'.
Params: {
    "token": "fb1e1bfa-465d-4831-9ed6-44faa076cbed",
    "value": {
        "kind": "end"
    }
}
```

Which version of the client libarary are you using. You need at least 6.0.x.

**Comment by davidanthoff** [comment]
I'm using 6.0.1. I think the error code I'm getting suggests that [this](https://github.com/microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/main.ts#L671) here is happening? I don't understand that code, though, to understand why :)

And just to be clear: I don't need to add anything in the extension itself, right? It should be enough that our LS sends these new messages for the UI to appear?

**Comment by dbaeumer** [comment]
Yes, it doesn't find the handler. But I don't understand why :-) Need to dig a little.

**Comment by dbaeumer** [comment]
I looked into this but I don't know why it is failing. Would you be able to debug this. A handler must be registered here https://github.com/microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/main.ts#L1013 which is then access https://github.com/microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/main.ts#L1180

The root to install the handler is here: https://github.com/microsoft/vscode-languageserver-node/blob/master/client/src/progressPart.ts#L33

**Comment by davidanthoff** [comment]
I figured out what the problem was. I accidentally sent the `$/progress` as a request, not a notification. Sorry for the noise!

**Comment by dbaeumer** [comment]
No problem.
