### ISSUE TITLE
Adopt API changes in call hierarchy

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-languageserver-node#559]
See https://github.com/microsoft/vscode/issues/85533

**Comment by rcjsuen** [comment]
@kjeremy @dbaeumer Time to close since #614 has been merged?

**Comment by kjeremy** [comment]
SGTM though I haven't had time to write the LSP docs so if you want to take that on...

**Comment by rcjsuen** [comment]
> SGTM though I haven't had time to write the LSP docs so if you want to take that on...

@kjeremy Looks like @dbaeumer has aslready added it in https://github.com/microsoft/language-server-protocol/commit/e73586714908822dec381f9ff719620a6094d379.

**Comment by dbaeumer** [comment]
Yes, I wrote the doc :-).
