### ISSUE TITLE
Server does not respect package.json "main"

### ISSUE THREAD

**Issue by tp** [Microsoft/vscode-languageserver-node#56]
This took me a long while to figure out, that the extensions always wants to start the server/server.js file instead of looking at the package.json's main.

Do you think it would be reasonable to respect that for Node.js servers?

(Sorry if this is not the right projects.)

**Comment by Seairth** [comment]
The client controls this.  Look at https://github.com/Microsoft/vscode-languageserver-node-example/blob/master/client/src/extension.ts Line 15.  If you want a different path,  you change it where you instantiate the LanguageClient.

**Comment by tp** [comment]
Oh yeah, just found that as well when reviewing the client. Was also thinking how starting other server types would be facilitated. Now it's clear to me.

Thanks!
