### ISSUE TITLE
unable to update from 5.2 to 6.1

### ISSUE THREAD

**Issue by APerricone** [microsoft/vscode-languageserver-node#564]
Hello, I think it is more an help request than an issue report, but the documantion lacks this part.

In my language server I had:
```JS
var documents = new server.TextDocuments();
documents.listen(connection);
```

that with 5.2 version works fine, base on testbed/server/src/server.ts, I changed it with
```JS
var documents = new server.TextDocuments(server.TextDocument);
documents.listen(connection);
```

but still crashes in 
![image](https://user-images.githubusercontent.com/22457168/73378662-3bf11c80-42c1-11ea-9c29-b50d146c481f.png)

My language server is written in JS not in TS.

Any hint?

**Comment by dbaeumer** [comment]
@APerricone sorry for not considering JS implementations. In TS this will give you an error with a JS doc comment about what to do. For the 6.x release we moved text documents to its own npm package to allow servers to implement their own text documents in case they already have an implementation in their parser land. So you need to do the following:

- add a dependency onto: ` "vscode-languageserver-textdocument": "1.0.0"`
- change the code to:
```
var textDocument = require('vscode-languageserver-textdocument');

var documents = new server.TextDocuments(textDocument .TextDocument);
documents.listen(connection);
```

I will add something to the change notes

**Comment by APerricone** [comment]
many thanks
