### ISSUE TITLE
SelectionRangeProvider not affecting ranges

### ISSUE THREAD

**Issue by Razzeee** [microsoft/vscode-languageserver-node#568]
Hey,

I've implemented a selectionRangeProvider which returns the correct object and get's called, as I added it to the server capatabilities.

Is there anything more I need to do? It seems like it still defaults to the VSCode default. I'm testing via setting the cursor and `Expand selection`. As stated, it gets called in that case, and I can debug it. What am I missing?

**Comment by dbaeumer** [comment]
@Razzeee can you debug the client side as well to see if something goes bad converting it to VS Code's API. The code is here: https://github.com/microsoft/vscode-languageserver-node/blob/master/client/src/selectionRange.ts#L59

**Comment by Razzeee** [comment]
Can you advise me on how to do that? Breakpoints in the `client/node_modules` folder do not seem to get picked up.

**Comment by dbaeumer** [comment]
Strange. This works for me by simply setting the breakpoint into the JS file. 

![capture](https://user-images.githubusercontent.com/1931590/73728857-5cdbc680-4734-11ea-80ad-d8fda3fea3c6.png)

**Comment by dbaeumer** [comment]
Do you use any form of symbolic  linking.

**Comment by Razzeee** [comment]
Sorry, tried again, it seems like it just doesn't hit the error path. 

I also rechecked the ranges I return and the selectionRange implementation you linked to returns. They still seem to match at that point.

**Comment by dbaeumer** [comment]
This is really strange. Do any kind of breakpoints work for you. What you can do is setting a breakpoint into your extension and then step into the constructor of the LSP client to see which path the debugger has in that case.

**Comment by Razzeee** [comment]
Yeah, debugging works fine. It just doesn't seem to leave the "happy path". The results I mentioned before are from debugging my part and https://github.com/microsoft/vscode-languageserver-node/blob/master/client/src/selectionRange.ts#L59

Now that I used that link again, I originally though you wanted me break at https://github.com/microsoft/vscode-languageserver-node/blob/master/client/src/selectionRange.ts#L61 which does not happen.

**Comment by Razzeee** [comment]
According to the debugger, I'm hitting this line https://github.com/microsoft/vscode/blob/master/src/vs/workbench/api/common/extHostLanguageFeatures.ts#L1201 and for some reason https://github.com/microsoft/vscode/blob/master/src/vs/workbench/api/common/extHostLanguageFeatures.ts#L1203

None of the below. And unfortunatly, I can't access the variables.

**Comment by dbaeumer** [comment]
I digged a little deeper and this seems to be a problem in VS Code itself. See https://github.com/microsoft/vscode/issues/90214

Lets see what they come up with.

**Comment by dbaeumer** [comment]
OK. I think the problem is that VS Code first selects the word. If your range is larger than the word you need to execute the command a second time. This is by design.

**Comment by Razzeee** [comment]
My range is not bigger then a word. I actually execute the command multiple times, most times the first execution is still correct (probably matches with VSCodes logic) but goes of the path thereafter.

Unrelated, vscode seems to treat `testVar` as two words `test` and `Var` I guess?

**Comment by dbaeumer** [comment]
Yes it does because of camel case.

**Comment by dbaeumer** [comment]
Can you reproduce this using a simple extension like the code in microsoft/vscode#90214 ?

**Comment by Razzeee** [comment]
I'll try to look into that over the weekend, thank you for digging into this.

**Comment by Razzeee** [comment]
I'm sorry, I found my oversight. Not sure why the compiler did not help. Sorry for the noise.

https://github.com/elm-tooling/elm-language-server/pull/213/commits/10c3c65901439d7ec38d73f0aeec8991d804623c
