### ISSUE TITLE
Allow client to define the progress location

### ISSUE THREAD

**Issue by larshp** [microsoft/vscode-languageserver-node#569]
For the progress indicator, eg. during `connection.onInitialize`, the `ProgressLocation` is set to `Notification` if the progress is cancelable, otherwise `Window`

I would like to show a notification progress indicator with percentage and without a cancel button, this is currently not possible.

Suggest adding a setting on the client-side as how to display the indicators. Eg 2 different settings
* ByCancellation (default) - Show as notification if the progress is cancelable otherwise Window
* AlwaysWindow - Always show as window progress, cancel button is shown if the progress is cancelable

ref
https://github.com/microsoft/vscode-languageserver-node/blob/0a93b43a54ab68e6139bc3dea18286ee9131e015/client/src/progressPart.ts#L49

**Comment by dbaeumer** [comment]
This got addressed. The progress is now shown using a new silent mode in VS code which combines a notification with a cancel button and a status bar item.
