### ISSUE TITLE
Move additional types to `vscode-languageserver-types`

### ISSUE THREAD

**Issue by david-driscoll** [Microsoft/vscode-languageserver-node#57]
Would it be possible to move some more interfaces over to types so that they may be shared?
https://github.com/Microsoft/vscode-languageserver-node/blob/master/server/src/protocol.ts#L128

I can understand anything referencing json-rpc shouldn't be shared, but it would be great to see `ServerCapabilities` and friends available for creating implementations using TypeScript.  As it stands I have to make a copy of `protocol.ts`.

It would also be great to have a methods namespace as well, to make those constants and available.

**Comment by dbaeumer** [comment]
@david-driscoll these got move to a separate npm module called vscode-languageserver-protocol. Please ping if this doesn't do the trick for you.
