### ISSUE TITLE
Need way to remove TextMate tokens completely with semantic highlighting

### ISSUE THREAD

**Issue by rcjsuen** [microsoft/vscode-languageserver-node#570]
The TextMate grammar is causing unclosed strings to bleed over to subsequent lines. I expect my second `a` to be white. I am ultimately trying to address microsoft/vscode-docker#860 but can't as the TextMate tokens are being merged with the semantic highlighting tokens.

<img width="198" alt="image" src="https://user-images.githubusercontent.com/15629116/74260368-68486800-4cc7-11ea-89c2-1bc57137a9e6.png">

This is what I'm sending back, I'm only highlighting:

1. the first `RUN` keyword
1. the unclosed string `'a`
1. the second `RUN` keyword

```TypeScript
[
    {
        line: 0,
        startCharacter: 0,
        length: 3, // RUN keyword of length 3
        tokenType: 0,
        tokenModifiers: 0
    },
    {
        line: 0,
        startCharacter: 4,
        length: 2, // string of length 2: 'a
        tokenType: 7,
        tokenModifiers: 0
    },
    {
        line: 1, // second RUN keyword on the subsequent line
        startCharacter: 0,
        length: 3,
        tokenType: 0,
        tokenModifiers: 0
    }
]
```

**Comment by dbaeumer** [comment]
@alexdima any idea how to tackle this?

**Comment by alexdima** [comment]
Currently, semantic tokens replace TM tokens, but only on those ranges that are defined, and of those ranges only properties that are defined by the theme are overwritten.

So, in this case, if there is no semantic token for the `a` on the second line, the `a` on the second line uses the TM tokens.
