### ISSUE TITLE
Requesting new build to sync with 1.42.0

### ISSUE THREAD

**Issue by rcjsuen** [microsoft/vscode-languageserver-node#571]
Can a new release be made now that 1.42.0 has gone out the door? I need it for 094917781ba66902f587554dd0e1c1a11ec10d7a and 99e583a9977341f6805b916817e80303f6ea640e as I continue my experiments with the semantic highlighting support.

Thanks!

**Comment by dbaeumer** [comment]
Published 6.1.1 client and server.

**Comment by rcjsuen** [comment]
Thanks, @dbaeumer!
