### ISSUE TITLE
Returning semanticsTokenProvider in server capabilities causes vscode to warn about using proposed apis

### ISSUE THREAD

**Issue by kjeremy** [microsoft/vscode-languageserver-node#572]
If I use a language server that adverstises semantic token support vscode 1.42 and insiders complain that I am trying to use proposed apis. Simply advertising that the server supports this feature should not trigger this.

**Comment by rcjsuen** [comment]
@kjeremy I did not encounter this issue though the extension is still using `vscode-languageclient` 5.x in my case. Did you upgrade to 6.x?

**Comment by rcjsuen** [comment]
@kjeremy Can you share your code or a link to your branch?

**Comment by kjeremy** [comment]
`vscode-languageclient` 6.1.0

It's a branch of https://github.com/rust-analyzer/rust-analyzer ... I will try to come up with something.

**Comment by rcjsuen** [comment]
@kjeremy Thanks. And which branch should I be looking at?

**Comment by kjeremy** [comment]
I can publish it in a bit. Actually it looks like we are calling `LanguageClient.registerProposedFeatures()` in the client. Maybe that's bad?

**Comment by kjeremy** [comment]
Though enabling call hierarchy on the server side works fine and that's supposed to be proposed...

**Comment by rcjsuen** [comment]
> I can publish it in a bit. Actually it looks like we are calling `LanguageClient.registerProposedFeatures()` in the client. Maybe that's bad?

@kjeremy Yes, that part will trigger the error.

> Though enabling call hierarchy on the server side works fine and that's supposed to be proposed...

They are not the same. I believe the call hierarchy API is live for VS Code but for the LSP it is still considered to be in a proposed state. Proposed VS Code API and proposed LSP API are not 1-to-1.

**Comment by rcjsuen** [comment]
@kjeremy If you search in the [VS Code API](https://code.visualstudio.com/api/references/vscode-api), you will see they have the call hierarchy stuff there. Searching for semantic tokens will get you nothing though.

**Comment by rcjsuen** [comment]
@kjeremy Use this instead of `client.registerProposedFeatures()` perhaps?
```TypeScript
client.registerFeatures(new CallHierarchyFeature(client));
```

**Comment by kjeremy** [comment]
@rcjsuen Thanks that at least allowed me to avoid the crash on stable while still getting call hierarchy. Though I think that I will probably have to use `lient.registerProposedFeatures()` while working on semantic token support.

**Comment by rcjsuen** [comment]
@kjeremy Yeah, that's what I've been doing as well.

**Comment by dbaeumer** [comment]
There is a difference between LSP proposed features and VS Code proposed feature. A feature can be final in VS Code but still proposed in LSP. An example is the call hierarchy. A feature can also be proposed in VS Code and LSP. VS Code has very strict rules when an extension can use proposed features. It needs to opt in, the are only available in dev mode and an extension will not work in the market place. There is nothing LSP can do about this so if you want to use proposed feature A but not B you need to register them by hand as outlined by @rcjsuen  (btw thanks for posting this).

**Comment by dbaeumer** [comment]
I will close the issue since there is little LSP can do about it.

**Comment by kjeremy** [comment]
Thanks. I initially assumed the issue was because we were returning that we
supported the capability on the server and didn't realize the issue was the
client side.

**Comment by kjeremy** [comment]
@dbaeumer Is there a recommended way to catch and handle this error? I would like to attempt to initialize proposed features so that all people have to do is run code with `--enable-proposed-api` to enable this.

**Comment by dbaeumer** [comment]
@kjeremy no, you can't and I can't either. This is VS Code policy. The reason is that VS Code doesn't want to have extensions published using proposed API and then the API changes and the extensions are broken. IMO this does make sense.

**Comment by kjeremy** [comment]
Makes sense I guess. Thanks.
