### ISSUE TITLE
TextDocument & TextDocumentContentChangeEvent breaking changes?

### ISSUE THREAD

**Issue by Razzeee** [microsoft/vscode-languageserver-node#573]
Hey,

I might have missed something, but I'm experiencing surprising behavior, when it comes to the new `vscode-languageserver-textdocument` vs the old implementation in `vscode-languageserver`.

I could not find anything about these working differently then before?

But after reverting and hotfixing a marketplace release, my users should be back to a working version.

This is the revert, that fixed the problem:
https://github.com/elm-tooling/elm-language-server/commit/d7e417a9b0d516d7100e7c38dafdacc259d1b8d6

**Comment by dbaeumer** [comment]
@Razzeee yes, the change is breaking and got documented here: https://github.com/microsoft/vscode-languageserver-node#3150-protocol-600-client--600-server

This is why we incremented the major version number :-).

Please ping if this doesn't help to fix your problem.

**Comment by Razzeee** [comment]
I think I even read that back then, but forgot about it. Will try to migrate to the new implementation later today.
