### ISSUE TITLE
SemanticTokenTypes.type is ambigious

### ISSUE THREAD

**Issue by matklad** [microsoft/vscode-languageserver-node#577]
I think `type` might mean either of these three different things:

* type alias, like `type Foo = ();` or `typedef int uint32_t;`
* type reference, like `let x: (i32, i32)  = (0, 0)` or `int x = 92;`
* type as a modifier: structs, interfaces, enums are "types"

I suggest renaming it to `typeAlias / typedef`, as that is much more specific, and probably the most useful one.

**Comment by dbaeumer** [comment]
@aeschli can you please comment?

**Comment by aeschli** [comment]
`type` is intended to be the super type of all types. In VSCode we map `type` to TextMate scope `entity.name.type`
We can also add `typeAlias`, if there are multiple languages can use it.
But that said, language servers are free to come up with their own custom token types.
The plan is to introduce a naming convention for custom token types such as`type>typeAlias` to signal that `typeAlias` is extending `type`.

**Comment by matklad** [comment]
So, it is indeed a benefit that `type` cleanly maps to `entity.name.type`. However it is still unclear to me for which tokens should my server produce a `type`. If the intention behind `type` is to be a super type of types, I probably should not use at all, and instead define my language specific concrete types, like `typeAlias` or `union`. I see how it can be useful once we add `>`, but it is not in the spec now.

I imagine that, if we leave `type` in, some folks would use it as a fallback for everything that is not `struct`, `class`, `enum` or `interface`, some folks would use it for `typeAlias`, and some folks would not use it at all, and instead define `typeAlias` or `typedef` types. To avoid this inconsistent usage, I think it might be a good idea to 

* add `typeAlias`: it is present at least in C, C++, TypeScipt, Go, Kotlin, Rust, and by having a `typeAlias` we make it clear that `type` is the "super type of all types", and not a `typeAlias`.
* remove `type` until we add `>`, as adding langauge specific types seems a better solution at the moment. 

To be clear, I don't have strong feelings here, I think this doesn't matter much in the end: textmate scopes are also widely inconsistent, but work out OK in practice.

**Comment by dbaeumer** [comment]
@aeschli any recommendation what we need to do?

**Comment by dbaeumer** [comment]
@aeschli ping

**Comment by aeschli** [comment]
We should document the standard token-types in LSP and clarify that `type` is a fallback for all types that don't have a more specific mapping (such as `class`)

**Comment by dbaeumer** [comment]
There are documented here https://github.com/microsoft/vscode-languageserver-node/blob/master/protocol/src/common/protocol.semanticTokens.ts#L18 and in the 3.16.0 spec. I will add something for the type value.
