### ISSUE TITLE
client: cancellation from middleware

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode-languageserver-node#578]
Our [Go extension](https://github.com/microsoft/vscode-go) was affected by the recent change in VS Code that no longer cancels CodeAction that takes too long. See https://github.com/microsoft/vscode/issues/90851 and https://github.com/microsoft/vscode/issues/91610 for discussion.

We are using [`vscode-languageclient`](https://github.com/microsoft/vscode-go/blob/610e4720481e79fda4a396a5ff66df45dd3a47fa/src/goLanguageServer.ts#L98). One of the case that triggered this issue is when our language server (`gopls`) couldn't respond on time, especially when users are working in completely misconfigured set up or when the language server is overloaded. 

This requires significant changes on `gopls` side, so we are looking for a solution that can mitigate from the client side.

Our initial attempt was to set timers from the middleware and cancel the outstanding request and return an empty or failure result upon timeout. But we couldn't find a way to tell the server about the cancellation (so the server doesn't have to waste time/resources to send back unexpected responses). Is it feasible?

If there is a better approach to deal with this, please let us know. Thanks!

**Comment by dbaeumer** [comment]
That is feasible. What you need to do in the middleware is the following:

- create your own `CancellationTokenSource` using the VS Code API
- pass the token from that source to the next handler
- when your timeout kicks in cancel the source and reesolve/reject the original promise

**Comment by hyangah** [comment]
Thank you for the quick response, @dbaeumer !

I saw the cancellation of the token source trigger the cancellation message to be sent to the language server, which is good.
 
I am still not sure about handling of the promise though. (Sorry, I am a newbie in JS). What is the original promise to resolve here?

I tried various things including returning a new `Promise` that's rejected when the timer expires and resolved when the `next` returns. But none of them worked correctly. 

Especially if I return a new Promise,
```
 provideCodeActions: (
		document: vscode.TextDocument,
		range: vscode.Range,
		context: vscode.CodeActionContext,
		token: vscode.CancellationToken,
		next: ProvideCodeActionsSignature
) => {
   const source = new vscode.CancellationTokenSource();
   const newToken = source.token;
   token.onCancellationRequested(() => { ... source.cancel(); ... });
   return new Promise((resolve, reject) => {
        setTimeout(() => { ... source.cancel(); resolve([]);  ... }, 500);
        resolve(next(..., newToken));
   })
}
```   

it causes the "Running Save Participant" popup hangs indefinitely even after the server returns a response after some time.

**Comment by dbaeumer** [comment]
@hyangah 

> I am still not sure about handling of the promise though. (Sorry, I am a newbie in JS). What is the original promise to resolve here?

This depends on the request. Usually resolving it to `undefined` should work. The signature for code actions is defined here: https://github.com/microsoft/vscode-languageserver-node/blob/dbaeumer/encodingSupport/protocol/src/protocol.ts#L2172
