### ISSUE TITLE
Add a postinstall script to check minimum VSCode requirement

### ISSUE THREAD

**Issue by Gama11** [microsoft/vscode-languageserver-node#579]
If vscode-languageclient requires a newer VSCode version than the user has specified in his extension's `package.json`, an error message should be printed. This would help prevent accidental broken releases (see this discussion for more info: https://github.com/microsoft/vscode-languageserver-node/commit/f5542d9f912e5a54b6bc81ae2df0d12cf7ee9082#r37530736).

**Comment by dbaeumer** [comment]
The feature has not gain any traction in the community. I therefore close the issue. Still a big Thank You to you for taking the time to create this issue! To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).

Happy Coding!
