### ISSUE TITLE
Semantic of commands returned from CompletionItem

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode-languageserver-node#580]
As the discussion for https://github.com/microsoft/vscode-languageserver-node/issues/471 is on going, we are implementing Completion -> Signature Help functionality by utilizing the CompletionItem's Command field.

```
export interface CompletionItem {
    ...
   	/**
	 * An optional command that is executed *after* inserting this completion. *Note* that
	 * additional modifications to the current document should be described with the
	 * additionalTextEdits-property.
	 */
	command?: Command;
    ...
```
[Our language server](https://github.com/golang/tools/blob/71482053b885ea3938876d1306ad8a1e4037f367/internal/lsp/completion.go#L128) sets `editor.action.triggerParameterHints` for the extra command.

Recently, we saw [an evidence](https://github.com/microsoft/vscode-go/issues/3075) that relevant editor settings such as `editor.parameterHints.enabled` do not affect the execution of the command, which confuses users.

We may try to interpret all the editor's  settings from the language server client side and tell language server to send or not send some commands. But editor settings is beyond what we control, so I am afraid our extension is not the right place for long term. I wonder if that can be done from the `vscode-languageclient` or `vscode` side instead.

Thanks. (reopening the issue after updating the comment)

**Comment by dbaeumer** [comment]
@hyangah I would recommend to may be not fill in the VS Code specific editor command on the server but instead do it in the middleware (since they are VS Code specific). This would allow you to interpret`editor.parameterHints.enabled`

And if you think there is a bug in VS Code that the if `"editor.parameterHints.enabled": false` is set to false `editor.action.triggerParameterHints` shouldn't trigger a paramter hint please open an issue agaisnt VS Code. However I do think that the settings should only affect user trigger parameter hints and not programmatically once. So I would say the current behavior is correct.

**Comment by hyangah** [comment]
Thanks for the suggestion. We will try to handle from our middleware and adopt based on how #471 moves in the future.

I agree that the flag guard does not belong to the language server or the vscode's command. It should be done somewhere in between (i.e., vscode language client or extensions that use the client). 

On the other hand, given there are a hundred different editor-specific flags, and letting each individual extension interpret them to mimic the editor behavior when not using language service is not ideal for both extension developers or users.

**Comment by dbaeumer** [comment]
I think that this has nothing to do with LSP. It is how an editor decides if a setting affect the behavior of a user triggered command, a programmatically triggered command or both.

**Comment by hyangah** [comment]
I didn't mean it should be a role of LSP. I meant it would be nice the editor specific library that interacts between the protocol and the editor could do it. (For both code sharing, correctness, and consistency) If 'vscode-languageclient` is just a pure LSP client-side implementation, that's my misunderstanding. I will file a feature request to vscode.
