### ISSUE TITLE
Using SocketTransport with the LanguageClient

### ISSUE THREAD

**Issue by jfacorro** [microsoft/vscode-languageserver-node#582]
First of all, thank you for working on this project! Awesome work! 🎉 

From the following comment in `main.ts`:
```
/**
 * To avoid any timing, pipe name or port number issues the pipe (TransportKind.pipe)
 * and the sockets (TransportKind.socket and SocketTransport) are owned by the
 * VS Code processes. The server process simply connects to the pipe / socket.
 * In node term the VS Code process calls `createServer`, then starts the server
 * process, waits until the server process has connected to the pipe / socket
 * and then signals that the connection has been established and messages can
 * be send back and forth. If the language server is implemented in a different
 * programm language the server simply needs to create a connection to the
 * passed pipe name or port number.
 */
```

I might be very wrong but is it correct to interpret that the server is expected to connect to the client? And if this is the case, isn't the whole concept backwards? Shouldn't the client connect to the server?

Is the expectation that the server should implement a special case when being used by VS Code? Other clients (e.g. Emacs' `lsp-mode`, vim's `coc` and probably others) are connecting to the server which starts by listening on a port and then the client maybe retries a couple of times (maybe with exponential back-off).

And thank you again for the work on this project, I really appreciate it!

**Comment by dbaeumer** [comment]
> I might be very wrong but is it correct to interpret that the server is expected to connect to the client?

Yes, that is correct in the model of a locally started server. For remote servers this is different. If you want to have control over this you can always pass a function as a server option to implement a different mode. See https://github.com/microsoft/vscode-languageserver-node/blob/dbaeumer/encodingSupport/client/src/main.ts#L142
