### ISSUE TITLE
Compile with the sources included

### ISSUE THREAD

**Issue by mrakgr** [microsoft/vscode-languageserver-node#585]
[See this.](https://stackoverflow.com/questions/60576319/is-there-a-way-to-include-the-typescript-sources-along-with-the-npm-package/60576514)

Would you consider compiling the package with the inline sources, so I can trace through it properly?

Until then, I am going to have to figure out how to put the `lsp-sample` files into `vscode-languageserver-node` project in order to get proper debugging support.

**Comment by dbaeumer** [comment]
Actually I did that at the beginning and then I got ask to not do so since it simply doubles the size of the package. IMO this needs to be addressed more broadly either by TypeScript or npm. I would have no problem to publish the map file including the sources which then people can install as a dev dependency. 

Does anyone know if this is possible ?

**Comment by mrakgr** [comment]
> Actually I did that at the beginning and then I got ask to not do so since it simply doubles the size of the package.
Was that with `sourceMap` (which includes the source raw) or `inlineSourceMap` (which compresses the source)?

**Comment by dbaeumer** [comment]
Sources inlined into the map file if I remember correctly

**Comment by mrakgr** [comment]
Then it might be worth trying out `inlineSourceMap` and `inlineSources` in tandem as that will compress the sources before inlining them at the end of the `.js` file. That having said, It is not guaranteed that this will give a benefit as no doubt NPM is compressing the files on its side which might end up cancelling out the compression benefits of those two options.

**Comment by dbaeumer** [comment]
Actually that will put me back to square one and I am sure others will them complain about the fact that it is there. IMO the right solution is still to have that as a dev package that can be installed as a dev dependency. But I don't know how to best do this. Has anyone an idea?
