### ISSUE TITLE
Compleiton is broken in 6.1.2

### ISSUE THREAD

**Issue by matklad** [microsoft/vscode-languageserver-node#594]
For some reason, code completions shows no results in 6.1.2. It works with 6.1.1. The server does send completions to the client:

![image](https://user-images.githubusercontent.com/1711539/77076463-29a77b00-69f4-11ea-8965-78aee4e3bbcd.png)

I have not investiragted this further yet.

**Comment by dbaeumer** [comment]
Will have a look. Sorry for that.

**Comment by dbaeumer** [comment]
OK. The problem was that I didn't publish `6.1.2` from the correct branch. Published `6.1.3`. Sorry for that.

**Comment by matklad** [comment]
Confirmed that 6.1.3 fixes the issue, thanks for the timely fix!

**Comment by dbaeumer** [comment]
@matklad could you do me a favor. I publish client and server with version 6.2.0-next.1 which has support for insert /replace in completion items. It is basically the code I published last week by accident. I tested completion and it works in my cases. But I want to make sure I am not overlooking something. THANKS!

**Comment by matklad** [comment]
Sure, just build rust-analyzer with 6.2.0-next.1, and quick testing shows that it works as before. 

I haven't tried actually took advantage of insert/replace tweaks, but I am looking forward to it.

**Comment by rcjsuen** [comment]
> @matklad could you do me a favor. I publish client and server with version 6.2.0-next.1 which has support for insert /replace in completion items.

@dbaeumer Where can I read up about the `InsertReplaceEdit`?

**Comment by dbaeumer** [comment]
Great. Thanks for giving it a try

**Comment by dbaeumer** [comment]
Best for now is https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3534

**Comment by rcjsuen** [comment]
Thank you, @dbaeumer. Will make further comments in microsoft/language-server-protocol#846 instead.

**Comment by dbaeumer** [comment]
OK. Added some more JS Doc.
