### ISSUE TITLE
Be able to see progress for multiple activities

### ISSUE THREAD

**Issue by robertoaloi** [microsoft/vscode-languageserver-node#595]
The LSP protocol allows the language server to update a client about the progress of multiple background activities via the `WorkDoneProgress` mechanism, where each activity is identified by a unique _token_. The VSCode status bar, though, can only show one activity at the time. If the server notifies the client about multiple activities, the _last one wins_ and progress of the original activity is not shown to the user any longer. This is sub-optimal for a server like the Erlang one which performs many activities concurrently. As an example, we can parallelize the indexing process, but currently report progress only for a single indexer.

**Comment by dbaeumer** [comment]
@robertoaloi I see the point but I don't know how to fix this given the limitation the VS Code API / implementaiton has.

Using notification to report this progress IMO not an alternative since it will glutter the UI too much.

**Comment by dbaeumer** [comment]
Or do you have a suggestion in mind.

**Comment by robertoaloi** [comment]
I am not familiar with the VS Code API or implementation, but I can explain what I would expect to see as a user.  Something like this:

<img width="878" alt="Screenshot 2020-03-20 at 18 30 54" src="https://user-images.githubusercontent.com/91769/77190108-f38ff700-6ad8-11ea-8fad-23329c188293.png">

**Comment by dbaeumer** [comment]
Fully agree. But something like this doesn't exist in VS Code (except of using notifications which IMO ill make a not nice UI)

@jrieken has something like this come up in VS Code?

**Comment by jrieken** [comment]
>  (except of using notifications which IMO ill make a not nice UI)

We have progress notifications that can work like this. Adding @bpasero who also demo'ed something with progress notifications rooted in the status bar

**Comment by bpasero** [comment]
Something @isidorn recently added is "silent" notification progress, it works like this:
* you use `IProgressService#withNotificationProgress` with the `silent` option enabled
* you can call this multiple times for each individual progress you want to report
* the status bar will show the currently active (= last reported progress) message
* clicking on the statusbar will reveal all progress notifications

I think that is a good compromise of not showing all notifications at once, but still be able to transition into more progress feedback as needed.

**Comment by dbaeumer** [comment]
That sounds great. But I have the feeling this is not exposed in the VS Code API yet. @isidorn any plans to do so?

**Comment by isidorn** [comment]
@dbaeumer we could add the property `silent` to the [`ProgressOptions`](https://github.com/microsoft/vscode/blob/a2ea73efe1ac0c0ddca918a63742fd9bcf4191ed/src/vs/vscode.d.ts#L7938) however no plans at the moment. 
If you would use it and if @bpasero thinks it makes sense we could add it.

**Comment by bpasero** [comment]
If you can express it as API that makes sense given what we have today, sure go for it. But we would need to make sure that `ProgressOptions.silent` is only available when using `ProgressLocation.Notification`. 

It should probably not be called just `silent` but something else. Alternatively we could introduce a new progress location `IProgressLocation.NotificationAndStatus`? All not great options...

**Comment by dbaeumer** [comment]
I would adopt it in LSP if available.

**Comment by jrieken** [comment]
> Alternatively we could introduce a new progress location IProgressLocation.NotificationAndStatus

This could also be the new default for `ProgressLocation.Window`

**Comment by bpasero** [comment]
@jrieken oh yeah, I like that 👍

**Comment by dbaeumer** [comment]
OK. Great. @isidorn ping me when it is available in VS Code and I will adapt it in LSP.

**Comment by bpasero** [comment]
I opened https://github.com/microsoft/vscode/pull/93363

**Comment by bpasero** [comment]
@dbaeumer this landed on `master`

**Comment by dbaeumer** [comment]
@bpasero THANKS!

**Comment by dbaeumer** [comment]
@robertoaloi are you willing to provide a PR that adapts this. But would require the next stable build from VS Code.

**Comment by robertoaloi** [comment]
@dbaeumer Not a TypeScript developer, so probably not the best person to implement this :)
