### ISSUE TITLE
DiagnosticCode.create is missing

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-languageserver-node#602]
Testing microsoft/vscode#93754

DiagnosticCode.create should be added for consistency

**Comment by dbaeumer** [comment]
Actually I am not sure anymore if adding all these create function was a good idea in the first place. Due to the new JS features I thing they are not very valuable anymore.

**Comment by dbaeumer** [comment]
Also depend on what we decide for https://github.com/microsoft/vscode-languageserver-node/issues/601

**Comment by dbaeumer** [comment]
The diagnostic code got removed in favour of the new `codeDescription` property which is optional.
