### ISSUE TITLE
Diagnostic.is not testing code correctly

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-languageserver-node#603]
Testing microsoft/vscode#93754

https://github.com/microsoft/vscode-languageserver-node/blob/master/types/src/main.ts#L660

needs to be adopted for `Diagnostic.code` to be a `DiagnosticCode`

**Comment by dbaeumer** [comment]
Good catch. Thanks !

**Comment by dbaeumer** [comment]
Depends on how we resolve https://github.com/microsoft/vscode-languageserver-node/issues/601
