### ISSUE TITLE
Error when I bundling extension with webpack

### ISSUE THREAD

**Issue by smallp** [microsoft/vscode-languageserver-node#605]
vscode-languageserver-protocol@3.15.3
```
ERROR in /home/small/projects/others/vscode-ci/client/node_modules/vscode-languageserver-protocol/lib/main.d.ts
[tsl] ERROR in /home/small/projects/others/vscode-ci/client/node_modules/vscode-languageserver-protocol/lib/main.d.ts(19,27)
      TS1005: ',' expected.

ERROR in /home/small/projects/others/vscode-ci/client/node_modules/vscode-languageserver-protocol/lib/main.d.ts
[tsl] ERROR in /home/small/projects/others/vscode-ci/client/node_modules/vscode-languageserver-protocol/lib/main.d.ts(19,206)
      TS1005: '(' expected.
......
```
It works with 3.14.1 (webpack runs well), but this extension cannot start.

**Comment by dbaeumer** [comment]
@smallp this works for me without problems when I web pack for example the ESLint extension which depends on LSP client and LSP server. 

The latest version of protocol are build using the latest version of TS. Perhaps this causes problems for you.

**Comment by smallp** [comment]
Yes, it works after I update tsc to 3.8.3, but this extension still cannot start.
I try to debug that, and figure out it stops in `LanguageClient.start()`. The error is just "1"(Starting client failed\n 1) so I don't know what it means. VScode shows it stops in 
```
Couldn't start client MY-EXTENSION
onDidChangeNotification | @ | notificationsAlerts.ts:40

[Extension Host] rejected promise not handled within 1 second: 1 (at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:851:521)
```
So have any one has the same issue? If not, I can just let it go.  It works fine with client compiled with tsc + server compiled with webpack.

**Comment by dbaeumer** [comment]
I haven't seen this before.

**Comment by smallp** [comment]
So just let it go.
