### ISSUE TITLE
executeCommandProvider fails with `'semantic.refactor.command' already exists` with multi-root servers 

### ISSUE THREAD

**Issue by haifengkao** [microsoft/vscode-languageserver-node#607]
When I tried to start multiple sourcekit-lsp servers, the vscode shows `'semantic.refactor.command' already exists`. 
This issue is similar to https://github.com/Microsoft/vscode-languageserver-node/issues/333, but I didn't call `registerCommand`. The `registerCommand` is called by the `initialize` function of `client.ts`.  https://github.com/Microsoft/vscode-languageserver-node/issues/333 says we should register command with uuid, but I didn't see `client.ts` doing the same thing. 

I think `client.ts` should be patched

```ts
initialize(capabilities) {
        if (!capabilities.executeCommandProvider) {
            return;
        }
        this.register(this.messages, {
            id: UUID.generateUuid(),
            registerOptions: Object.assign({}, capabilities.executeCommandProvider)
        });
    }

```

**Comment by dbaeumer** [comment]
Actually statically registering commands in a multi server setup will only work if we allow to pass a prefix to the client when created. Can't you use dynamic registration in our case?

**Comment by haifengkao** [comment]
I am following the example code at https://github.com/microsoft/vscode-extension-samples/blob/master/lsp-multi-server-sample/client/src/extension.ts

It doesn't provide any dynamic registration examples. Where can I find them?

**Comment by dbaeumer** [comment]
An example is the ESLint server which registers the formatter dynamically. See https://github.com/microsoft/vscode-eslint/blob/master/server/src/eslintServer.ts#L1002

Ping if you have additional questions.

**Comment by haifengkao** [comment]
thx
