### ISSUE TITLE
json-rpc: documentation

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vscode-languageserver-node#61]
I can't find any documentation for your `vscode-jsonrpc` NPM package anywhere. I've had to reverse engineer it so far and still haven't gotten an app up and running yet.

**Comment by aeschli** [comment]
@AArnott https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#base-protocol has more information on the base protocol.

**Comment by AArnott** [comment]
Thanks, @aeschli. I know about that document, which seems to focus on the protocol. But what I'm looking for is a document describing how to use this package.
For example, nowhere can I find documentation that I need to call `listen()` after calling `createClientMessageConnection` and before sending a request out. I was seeing hangs for a while before finally figuring that out.

**Comment by AArnott** [comment]
Another missing piece that we're figuring out from test failures by reverse-engineering: disposing a connection doesn't close the underlying stream. I think this should be documented, or fixed. Preferably fixed. :)

**Comment by kofno** [comment]
I'm similarly stumped. I'm building my server in another language. I seem to have gotten it to launch, but I'm trying to figure out how to connect to it (tcp over port 6004?). And I want to get stdout from the external process to appear in the debugging console, if possible.

**Comment by AArnott** [comment]
Thanks.
