### ISSUE TITLE
Output panel for Aura/LWC Language Server steals focus

### ISSUE THREAD

**Issue by danielstrong** [microsoft/vscode-languageserver-node#612]
I am having an issue with the plugin where the output panel keeps stealing focus to print out informational messages in the Aura and LWC Language Servers. (messages such as "loadCustomTagsFromFiles: processed 40 files in 5751.15 ms", messages like these don't require my attention unless I am troubleshooting something with the extension itself. 

It would be preferable to either not have the Output panel steal focus when presenting messages for the Aura and LWC Language servers, or have a setting for the extension to toggle this on and off. It can be very annoying to have the output panel pop up constantly. (Especially some messages pop up while working on/typing/scrolling in code)

**Comment by dbaeumer** [comment]
There is an option for this. See https://github.com/microsoft/vscode-languageserver-node/blob/master/client/src/client.ts#L500
