### ISSUE TITLE
Retrieve word range at hover position

### ISSUE THREAD

**Issue by anweiss** [microsoft/vscode-languageserver-node#616]
I'm trying to return hover information based on the word over which the user is hovering. However, it doesn't look like there are any properties in the `HoverParams` argument from the `onHover` handler that provide a range. There only seems to be a single `Position` property. The `@types/vscode` module includes a `getWordRangeAtPosition()` function that makes this easy, but it doesn't look like I can import this module into a language server built with the `vscode-languageserver` node library. Is there an alternative way to get the word range from the `onHover` handler? Thanks!

**Comment by rcjsuen** [comment]
@anweiss I think you have no choice but to calculate this yourself. Different languages have different definitions of what a "word" is.

See microsoft/language-server-protocol#937.

**Comment by anweiss** [comment]
thanks @rcjsuen. yea as I was writing this out, that was dawning on me. Appreciate the clarity.
