### ISSUE TITLE
How to send custom options (completion, formatting etc.) to the server?

### ISSUE THREAD

**Issue by xorye** [microsoft/vscode-languageserver-node#617]
If I had this on the language server:
```
connection.onDocumentFormatting((formattingParams: DocumentFormattingParams) => {

});
```
How can I specify the `formattingParams.options` from the client side?

For reference, `DocumentFormattingParams` looks like this: https://github.com/microsoft/vscode-languageserver-node/blob/e5d7ad881b1a51b486e3f0e4aa0fbc25dad2be58/protocol/src/protocol.ts#L2390-L2400

https://github.com/microsoft/vscode-languageserver-node/blob/e5d7ad881b1a51b486e3f0e4aa0fbc25dad2be58/types/src/main.ts#L2483-L2519

Ideally, from the client side, I would like to set something like `formattingParams.options.insertFinalNewline = true` and have that sent to the server when the `textDocument/formatting` request happens, so that the server act accordingly.

Is this possible? I have been struggling with this for a while, could someone please point me in the right direction?

**Comment by rcjsuen** [comment]
> How can I specify the `formattingParams.options` from the client side?

What client editor are you using to test? Visual Studio Code?

**Comment by rcjsuen** [comment]
@xorye Those values aren't sent to the formatter at the moment. The [`FormattingOptions` interface in Visual Studio Code](https://github.com/microsoft/vscode/blob/66744e3b25fcb7ca77ced2bf9590f7c01d246fb1/src/vs/vscode.d.ts#L3402-L3421) is quite limited and does not have attributes like `trimTrailingWhitespace` and so on.

@dbaeumer Do you agree that the `FormattingOptions` API should be enhanced in VS Code?

**Comment by xorye** [comment]
@rcjsuen thank you for clarifying. How about `insertSpaces`? Is it possible to set that from the client VS code extension within typescript code? Not that I would do this. I am wondering if I could edit the formatting request before the server receives it.

**Comment by rcjsuen** [comment]
> How about `insertSpaces`? Is it possible to set that from the client VS code extension within typescript code? Not that I would do this. I am wondering if I could edit the formatting request before the server receives it.

@xorye Yes, you can use middleware to intercept these things and change the parameters. I don't know if there are any readily available examples though. You might have to dig around the issues in this repository.

https://github.com/microsoft/vscode-languageserver-node/blob/e5d7ad881b1a51b486e3f0e4aa0fbc25dad2be58/client/src/client.ts#L2047-L2050

**Comment by xorye** [comment]
Awesome, that was what I was looking for!

So if I understand correctly, I cannot just add a new option (like `trimTrailingWhitespace`) from within the `provideDocumentFormattingEdits` function from the client-side, and have the server receive the new option? I guess the client-side needs some sort of official support?

**Comment by rcjsuen** [comment]
> So if I understand correctly, I cannot just add a new option like:
> 
> ```
> provideDocumentFormattingEdits: (document, options, token, next): ProviderResult<TextEdit[]> => {
>           options.trimFinalNewlines = false;
>           return next(document, options, token);
> }
> ```
> 
> from the client, and have the server receive the new option? I guess the client-side needs some sort of official support?

@xorye Your sample code looks reasonable to me. Is it not working?

**Comment by xorye** [comment]
Yes, I am not getting it from the server side:

Here is the sample code:
https://github.com/microsoft/vscode-extension-samples/compare/master...xorye:format_sample

When formatting a Plain Text document, I am not receiving the `trimFinalNewlines` that the middleware adds: 
![image](https://user-images.githubusercontent.com/20326645/80142837-d5a32f80-8579-11ea-982a-22e0cf5a2f6b.png)

**Comment by rcjsuen** [comment]
@xorye Oh, right. Sorry, yes, you're right. It's because the converter doesn't copy/paste those values over.

https://github.com/microsoft/vscode-languageserver-node/blob/e5d7ad881b1a51b486e3f0e4aa0fbc25dad2be58/client/src/client.ts#L2080-L2084

**Comment by xorye** [comment]
No problem, thank you for the info

**Comment by angelozerr** [comment]
LSP 3.15 specifies those 3 formatting options:

```ts
/** 
 	 * Trim trailing whitespaces on a line. 
 	 * 
 	 * @since 3.15.0 
 	 */ 
 	trimTrailingWhitespace?: boolean; 
  
 	/** 
 	 * Insert a newline character at the end of the file if one does not exist. 
 	 * 
 	 * @since 3.15.0 
 	 */ 
 	insertFinalNewline?: boolean; 
  
 	/** 
 	 * Trim all newlines after the final newline at the end of the file. 
 	 * 
 	 * @since 3.15.0 
 	 */ 
 	trimFinalNewlines?: boolean; 
```

the question is how to consume it without extra code?

@dbaeumer is there any issues, plan to consume those 3 formatting settings in LS? 

vscode defines `files.trimFinalNewlines` which is used on save, perhaps `vscode.FormattingOptions` could define the trimFinalNewlines and could be populated by default with this `files.trimFinalNewlines` settings?

**Comment by dbaeumer** [comment]
The LSP client libraries for VS Code should fill the once it that are available in VS Code. If there is not a setting defined there is nothing I can do.

**Comment by giltho** [comment]
Hi!
I do agree on the "fixed options" that they need VSCode's API to work be updated.

However, for the "non-fixed" part  `[key: string]: boolean | number | string | undefined;`, I don't think VSCode could provide any way of doing this. Maybe this should be extracted directly from the workspace configurations if it has a certain pattern like `langId.formatting.<param>` ?

**Comment by dbaeumer** [comment]
@jrieken do you have any plans to extend the formatting options with this. I could also read the configuration for those that are supported in VS Code.

**Comment by dbaeumer** [comment]
For now I read the config myself. @jrieken please ping if you think that has to go into the `FormattingOptions` inside the VS Code API.
