### ISSUE TITLE
How can I make sure my LS gets config change notifications?

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode-languageserver-node#620]
My understanding is that `LanguageClientOptions.synchronize.configurationSection` is deprecated, correct? And that instead I'm supposed to pull config values via sending `workspace/configuration` from the server to the client.

One thing I don't understand in this model is how the client (VS Code/`LanguageClient`) then knows for which config setting changes it should send `workspace/didChangeConfiguration` notifications? And in fact, when I remove the `LanguageClientOptions.synchronize.configurationSection` part, then I don't seem to receive any `workspace/didChangeConfiguration` notifications on the server, even when I edit some settings from my extension.

**Comment by dbaeumer** [comment]
Since the server issues the request the server needs to register for change events as well. In the VS Code LSP implementation this is done using:

`connection.client.register(DidChangeConfigurationNotification.type);`

Let me know if there is still something that is unclear.

**Comment by davidanthoff** [comment]
Ah, yes, when I register for that client capability, I do get the `workspace/didChangeConfiguration` notifications now!

But I'm getting them for _any_ settings change now, even if I for example change a setting in the Python extension, I get that notification in my Julia language server. Is there some way to scope this a little bit more?

I think I still don't fully understand the best strategy to implement this here... Would we essentially implement a cache for settings in our LS, and whenever we receive a `workspace/didChangeConfiguration` message we just wipe the entire cache?

**Comment by dbaeumer** [comment]
@davidanthoff this is exactly what I do. The problem is that most clients don't have a fine grained invalidation event. VS Code has one since a couple of month so we could thing about adopting it.

**Comment by davidanthoff** [comment]
Great, then we’ll do it that way as well :) Thanks!
