### ISSUE TITLE
Api to get the VsCode autodetected indentation spaces of a file

### ISSUE THREAD

**Issue by nvuillam** [microsoft/vscode-languageserver-node#622]
In order to format a document (in my case, Groovy & Jenkinsfile using [VsCode Groovy Lint](https://marketplace.visualstudio.com/items?itemName=NicolasVuillamy.vscode-groovy-lint)) , I need to be able to programatically get a file auto-detected indentation type ( number of spaces for indentation, like 2 or 4 )

![image](https://user-images.githubusercontent.com/17500430/82291034-7bdf2b00-99a8-11ea-8917-fd2691aa0ef1.png)
Bassically, I need to be able to get what has been auto-detected when this settings has been activated.

Is there an API allowing that , maybe related to TextDocument ?

**Comment by rcjsuen** [comment]
@nvuillam I just use what's in the `FormattingOptions` of the passed in `DocumentFormattingParams` and it appears to match the indentation that VS Code detects. You shouldn't have to do anything extra here.

**Comment by nvuillam** [comment]
Oops, I should have searched more, sorry and thanks for the answer :)

![image](https://user-images.githubusercontent.com/17500430/82315746-0be29c00-99cc-11ea-8306-e9c36bd7869e.png)
