### ISSUE TITLE
Why does the response to my request (to client) for config settings contain nulls?

### ISSUE THREAD

**Issue by ZacLN** [microsoft/vscode-languageserver-node#623]
Hi, 
We're sending a "workspace/configuration" request to the vscode client (as per [this](https://github.com/microsoft/vscode-languageserver-node/issues/620)) and are receiving `null` values instead of `false` for a group of boolean properties. When set to `true` the properties are returned as expected. These properties all set within the vscode extension similar to the following snippet within the relevant contributes/configuration/properties of the client extension's package.json.
```json
"julia.lint.run": {
                    "type": "boolean",
                    "default": true,
                    "description": "Run the linter on active files."
                }
```
Other, non-boolean, properties are returned as expected. What are we missing?

This relates to the [julia-vscode](https://github.com/julia-vscode/julia-vscode) extension.

**Comment by rcjsuen** [comment]
Sounds like some TypeScript/JavaScript conversion issue...?

@ZacLN Do you have issues with `0` or `""` and other such "falsy" values?

**Comment by ZacLN** [comment]
Not that I'm aware of. I'm assuming this is something to do with how we're specifying the properties as it seems such an odd behaviour that couldn't possibly have gone unnoticed before.

**Comment by rcjsuen** [comment]
@ZacLN What did you find when you added breakpoints and/or print statements in [`configuration.ts`](https://github.com/microsoft/vscode-languageserver-node/blob/03179b00aef101d4a46e705c048717e3f4560e08/client/src/configuration.ts)?

**Comment by ZacLN** [comment]
I don't have any idea of how to get started with debugging the editor in unison with the extension, is there some guide available?

**Comment by rcjsuen** [comment]
> I don't have any idea of how to get started with debugging the editor in unison with the extension, is there some guide available?

Not sure. The only document I'm aware of is the [Language Server Extension Guide](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide). Otherwise, I just go inside my `node_modules` folder and just add breakpoints and print statements to see what's happening.

**Comment by ZacLN** [comment]
Thanks! It seems [this](https://github.com/microsoft/vscode-languageserver-node/blob/03179b00aef101d4a46e705c048717e3f4560e08/client/src/configuration.ts#L67) is the culprit. I assume it's checking against result being `null` but also prevents returning `false`  - is this likely to be intended behaviour?

**Comment by rcjsuen** [comment]
> Thanks! It seems [this](https://github.com/microsoft/vscode-languageserver-node/blob/03179b00aef101d4a46e705c048717e3f4560e08/client/src/configuration.ts#L67) is the culprit.

Can you test that code with `""` and `0`? I feel like they should return `null` also... 🤔

**Comment by ZacLN** [comment]
Yep it does

**Comment by rcjsuen** [comment]
@ZacLN Definitely looks like a bug to me.

**Comment by davidanthoff** [comment]
@dbaeumer do you agree that this is a bug and should be fixed, or are we misunderstanding something in the spec?

This is our highest priority bug for the Julia extension right now, we need to find some way to work around this. Just having some official guidance from you would help us decide how to proceed :) Thanks!

**Comment by dbaeumer** [comment]
Agree that this is a bug.

Two things you can do: convert it to false on the server side. Use a client side middle ware to convert it back to false.

**Comment by davidanthoff** [comment]
Great, thanks! We have a workaround for now and then we'll just wait for the next release here :)
