### ISSUE TITLE
Notifications are not being handled

### ISSUE THREAD

**Issue by afonsojramos** [microsoft/vscode-languageserver-node#625]
As previously discussed in https://github.com/microsoft/language-server-protocol/issues/993, I have just discovered that neither `connection.onDidChangeTextDocument`, `connection.onDidCloseTextDocument`, nor `connection.onDidOpenTextDocument` are being run when a notification is sent (which I can observe happening with the verbose mode). 

Any idea on why this might be happening? `connection.onCodeAction`, `connection.onDidChangeConfiguration` and `connection.onInitialize` are all working!

**Comment by rcjsuen** [comment]
@afonsojramos Please share your code.

**Comment by afonsojramos** [comment]
> @afonsojramos Please share your code.

You can check it out here: https://gist.github.com/afonsojramos/5dc8b928e1b9a8aa32958f9728b300cc

Please feel free to give any further criticisms and thank you for your help, again!

**Comment by rcjsuen** [comment]
https://gist.github.com/afonsojramos/5dc8b928e1b9a8aa32958f9728b300cc#file-server-ts-L28-L30

@afonsojramos The issue is likely your use of the `TextDocuments` manager class. It sounds just like https://github.com/microsoft/vscode-languageserver-node/issues/176#issuecomment-324633001.

**Comment by afonsojramos** [comment]
After several tries of seemingly random things I have, against what is demonstrated in [lsp-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-sample), I have placed
 ```js
documents.listen(connection);
``` 
call immediately after 
```js
const documents: TextDocuments<TextDocument> = new TextDocuments(TextDocument);
```
and now it all works! I still cannot feel happyness for solving this issue, due to all the frustrastions it has brought me.

**Comment by dbaeumer** [comment]
@afonsojramos sorry for hearing that. But unfortunately your fix will break other things. I threfore closed the PR you opened. The connection only offers handlers, no events. I explain the reason in the PR. To make this more clear I added the following comment to the listen method

```
	/**
	 * Listens for `low level` notification on the given connection to
	 * update the text documents managed by this instance.
     *
	 * Please note that the connection only provides handlers not an event model. Therefore
	 * listening on a connection will overwrite the following handlers on a connection:
	 * `onDidOpenTextDocument`, `onDidChangeTextDocument`, `onDidCloseTextDocument`,
	 * `onWillSaveTextDocument`, `onWillSaveTextDocumentWaitUntil` and `onDidSaveTextDocument`.
	 *
	 * Use the correspnding events on the TextDocuments instance instead.
	 *
	 * @param connection The connection to listen on.
	 */
```

The right fix on your end is to use the events on the TextDocuments instance for document changes instead of installing handlers on the conneciton.

**Comment by dbaeumer** [comment]
From the example:

```
// Only keep settings for open documents
documents.onDidClose(e => {
	documentSettings.delete(e.document.uri);
});

// The content of a text document has changed. This event is emitted
// when the text document first opened or when its content has changed.
documents.onDidChangeContent(change => {
	validateTextDocument(change.document);
});

```

**Comment by afonsojramos** [comment]
@dbaeumer In my case, since the connection handler only shows the difference towards the previous file save whereas the Document Manager sends the whole document to be parsed, I would prefer to use the connection handler. Is it possible to not use any of the Document Manager handlers?

**Comment by rcjsuen** [comment]
@afonsojramos Not sure I completely follow what you're saying but it sounds like you want to just not use `TextDocuments` and delete your `documents` field...?

**Comment by afonsojramos** [comment]
@rcjsuen Well, yes because all the handlers that I was using from the document manager were the `onDidSave` and the `onDidOpen`. On another location, I also had the `documents.all()` call, but I can live without it and validate just the open document.

**Comment by rcjsuen** [comment]
> @rcjsuen I also had the `documents.all()` call, but I can live without it and validate just the open document.

You can also keep the opened documents in memory and validate them if you have that requirement.

**Comment by dbaeumer** [comment]
@afonsojramos there is no need to use a `TextDocuments` instance. You can do everything yourself on the connection. The `TextDocuments` has some nice helper code for incremental text document updates.
