### ISSUE TITLE
Sending arguments through a CodeLens request

### ISSUE THREAD

**Issue by zepedrob16** [microsoft/vscode-languageserver-node#627]
Hello

I have created an array of CodeLenses using `connection.OnCodeLens()` function, which are filled with objects like the following:
```typescript
codeLenses.push({
    range: {
       start: { line: i, character: 0 },
       end: { line: i, character: 8 }
     },
     command,
     data: 0,
     arguments: i
});
```
Also, here is how the command is created in the package.json file
```json
{
    "command": "extensionName.commandName",
     "title": "Run Test",
     "category": "CodeLens Sample",
     "arguments": []
}
```
The command is created before pushing to the `codeLenses` array and has the title of 'Run Test'. When I press 'Run Test' on the client extension, the function `connection.onExecuteCommand(handler)` is called, but the handler does not have any arguments attached to it (i.e. it has an array of length 0). 

I want to know the line where the 'Run Test' command was clicked. How can I send arguments through the codeLens so that I can read them on the `executeCommand` function?

**Comment by dbaeumer** [comment]
@zepedrob16 the `arguments` property is on the command literal and not on the codeLenses. And for these internal commands there is no need to register them in the package.json. It is enough to register them in code on extension activation.

**Comment by dbaeumer** [comment]
Please ping if this doesn't help
