### ISSUE TITLE
How to get the lsp response in vscode-language-client?

### ISSUE THREAD

**Issue by Abbyyan** [microsoft/vscode-languageserver-node#628]
I'm working on a vscode lsp extension development and want to ask if there are some methods that i can get the lsp response in the vscode-language-client ? Hope for your help. Thanks a lot.

**Comment by dbaeumer** [comment]
@Abbyyan the LSP client has a middleware which all requests and response go through.

**Comment by Abbyyan** [comment]
How can i get the full completion items in the server response? Should i use `provideCompletionItem` or `resolveCompletionItem`  ? Thanks for your help.

**Comment by Abbyyan** [comment]
Is there some documents shows how to use them please?

**Comment by rcjsuen** [comment]
> How can i get the full completion items in the server response? Should i use `provideCompletionItem` or `resolveCompletionItem` ? Thanks for your help.

You probably want the former but you may want both depending on your exact use case.

> Is there some documents shows how to use them please?

Maybe the code from #322 may serve as a bit of a reference for you.

**Comment by Abbyyan** [comment]
Learned from [lsp-example](https://github.com/microsoft/vscode-extension-samples/blob/1c9a14f3e481d8fbfeec4a645e476bbaf8333d7a/lsp-embedded-request-forwarding/client/src/extension.ts#L47) that i can change the input send to server (just as the uri in the example). But i still confused about get the response (or other info ) from server.  For example , how can i get the completion list in provideCompletionItem? Hope for your answer please. Thanks for your help！ 
```js
let clientOptions: LanguageClientOptions = {
		documentSelector: [{ scheme: 'file', language: 'html1' }],
		middleware: {
			provideCompletionItem: async (document, position, context, token, next) => {
				// If not in `<style>`, do not perform request forwarding
				if (!isInsideStyleRegion(htmlLanguageService, document.getText(), document.offsetAt(position))) {
					return await next(document, position, context, token);
				}

				const originalUri = document.uri.toString();
				virtualDocumentContents.set(originalUri, getCSSVirtualContent(htmlLanguageService, document.getText()));

				const vdocUriString = `embedded-content://css/${encodeURIComponent(
					originalUri
				)}.css`;
				const vdocUri = Uri.parse(vdocUriString);
				return await commands.executeCommand<CompletionList>(
					'vscode.executeCompletionItemProvider',
					vdocUri,
					position,
					context.triggerCharacter
				);
			}
		}
	};
```

**Comment by dbaeumer** [comment]
The result of `next(document, position, context, token)` is the result from the LSP server. It is like next handlers in web servers.

**Comment by Abbyyan** [comment]
> The result of `next(document, position, context, token)` is the result from the LSP server. It is like next handlers in web servers.

Thanks for your help. It really works! Thanks a lot. By using `next` , I can get the response now . Thanks a lot. 
```js
provideCompletionItem: async (document: TextDocument,
                                      position: Position, context: CompletionContext,
                                      token: CancellationToken, next: ProvideCompletionItemsSignature) => {
          if (true) {
            const temp_result: any = await next(document, position, context, token);
            if (temp_result) {
              const temp_result_info: CompletionList = temp_result;
              logChan("temp_result is not null " + temp_result_info.toLocaleString);
              const items: any = temp_result_info.items;
              items.forEach((element: CompletionItem) => {
                logChan("completion element label = " + element.label + "  detail = " + element.detail);
              });
            }
            return temp_result;
          }
          return [];
        }
      },
```

**Comment by Abbyyan** [comment]
> The result of `next(document, position, context, token)` is the result from the LSP server. It is like next handlers in web servers.
How can i send the Intercepted and processed response to the vscode client? 
Should i get the `next` function result by `await next`, then process the response and send the processed response to vscode client by `return processed_response  ` in the `provideCompletionItem ` function just like follows?
```js
provideCompletionItem: async (document: TextDocument,
                                      position: Position, context: CompletionContext,
                                      token: CancellationToken, next: ProvideCompletionItemsSignature) => {
            const temp_result: any = await next(document, position, context, token);
            const processed_result = some_process_func(temp_result)
            return processed_result;
        }
```
I've tried it but it seems something doesn't work like this. Hope for your advice . Thanks a lot.

**Comment by rcjsuen** [comment]
> I've tried it but it seems something doesn't work like this. Hope for your advice . Thanks a lot.

@Abbyyan I don't understand. You just said it worked an hour ago (https://github.com/microsoft/vscode-languageserver-node/issues/628#issuecomment-638822141)?

**Comment by Abbyyan** [comment]
> > I've tried it but it seems something doesn't work like this. Hope for your advice . Thanks a lot.
> 
> @Abbyyan I don't understand. You just said it worked an hour ago ([#628 (comment)](https://github.com/microsoft/vscode-languageserver-node/issues/628#issuecomment-638822141))?

Yes, I can get the completion list can print it out. I intercept the response and process it .  It confused me now that  how can i send my processed response to vscode client? Thanks a lot.

**Comment by rcjsuen** [comment]
> I intercept the response and process it . It confused me now that how can i send my processed response to vscode client?

Aren't you doing that already with your `return processed_result;` line?
