### ISSUE TITLE
json-rpc: onRequest and onNotify callbacks should be invoked with args separated

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vscode-languageserver-node#63]
It seems that methods invoked by `vscode-jsonrpc` have all arguments crammed into the first argument as an array. The second argument is a CancellationToken.
Shouldn't these methods be invoked with a more natural set of arguments instead of an array?

Per the [json-rpc spec](http://www.jsonrpc.org/specification#parameter_structures), the `params` property should be an **array** of ordered arguments, *or* an object of named arguments. Your array support should therefore invoke methods with the array elements exploded into individual method parameters. And your object support should be removed, since named arguments support isn't possible in javascript.

**Comment by dbaeumer** [comment]
Fully agree. I never needed it for the language server protocol so I didn't implement it.

**Comment by dbaeumer** [comment]
Fixed for 3.0 version of vscode-jsonrpc. Available as 3.0.0-alpha.1

**Comment by AArnott** [comment]
Thanks
