### ISSUE TITLE
vscode-jsonrpc arg handling is vulnerable to parameter count causing odd behaviors

### ISSUE THREAD

**Issue by AArnott** [microsoft/vscode-languageserver-node#630]
It seems that calling `sendRequest('someMethod', 'arg1', 'arg2')` will result in sending a JSON-RPC request with `params: ['arg1', 'arg2']`. But if I drop the second argument leaving just `sendRequest('someMethod', 'arg1')` then the request contains `params: 'arg1'` which is both illegal (because `params` must be either a JSON array or a JSON object) and unexpected because removing one element from an array should not change the array to something else.

Why is this the behavior? And is this documented somewhere? It seems I can possibly workaround it by always wrapping all args in an array.

https://github.com/microsoft/vscode-languageserver-node/blob/9466bf38aef41849b3d48a882e399a34e3127eb2/jsonrpc/src/common/connection.ts#L1080-L1131

**Comment by AArnott** [comment]
In fact this issue is not noticeable when vscode-jsonrpc is on both sides of the connection because the server accepts illegal `params` values such as a single JSON string or number. This only becomes noticeable when calling more strictly conforming JSON-RPC servers such as StreamJsonRpc which rejects requests where `params` is anything other than `null`, an array or a JSON object.

**Comment by dbaeumer** [comment]
Good catch. I see two things that we need to do to fix this:

- on the one param typings allow specifying whether this position or a named request.
- for the generic sendRequest have an overload that allows specifying this in cases only one arg is passed.

We could throw if a named call with a scalar value is made.

**Comment by dbaeumer** [comment]
Got fixed.
