### ISSUE TITLE
Add API documentation for MessageReader

### ISSUE THREAD

**Issue by AArnott** [microsoft/vscode-languageserver-node#633]
I'm implementing my own `MessageReader` and `MessageWriter`. The `MessageReader.onPartialMessage` isn't documented and I'm having a difficult time figuring out what it's for. I may have to go digging into the source code to figure it out.
Can API docs be added?

**Comment by dbaeumer** [comment]
Yes, of course. If I recall it correctly I added this a long time ago based on your suggestion. If signals the fact the a message after some timeout did not fully make it to the receiver.

**Comment by AArnott** [comment]
Funny. I don't remember making that suggestion, but thanks for taking the PR.
