### ISSUE TITLE
Message transmission order undefined (6.0.0 regression)

### ISSUE THREAD

**Issue by AArnott** [microsoft/vscode-languageserver-node#634]
The changes to add message encoding as an extensibility point in vscode-jsonrpc introduced a timing regression. The `contentTypeEncoder.encode` method is called and returns a promise. Only *after* encoding has completed does the ordering of the message get "locked in". 

So if I use vscode-jsonrpc to send two messages in a row, the second message could be sent *first* if it happens to finish encoding first.

https://github.com/microsoft/vscode-languageserver-node/blob/f28df80995e8a3a39e272616ed055c8676ebb606/jsonrpc/src/common/messageWriter.ts#L111-L118

You might need to use a semaphore to 'lock in' the order for messages from when you first receive them rather than when you're done encoding them. This would help you match pre-6.0 behavior.

**Comment by dbaeumer** [comment]
Nice catch. The semaphore is already there :-) needs to be moved up a little: https://github.com/microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/common/messageWriter.ts#L142
