### ISSUE TITLE
DidChangeWatchedFiles only reports changes within workspace

### ISSUE THREAD

**Issue by stamblerre** [microsoft/vscode-languageserver-node#641]
It seems to me that `didChangeWatchedFiles` only ever reports changes for files within a user's workspace, no matter the GlobPattern. Is there any way to get notifications for all matching files, even if they are outside of the workspace?

Please correct me if I am mistaken in my understanding -- I only experimented with this briefly.

Some context for why this is necessary: In Go, users typically work in [modules](https://blog.golang.org/using-go-modules), but they may open subdirectories of those modules in VS Code. An on-disk change to any file in the module may affect the subdirectory opened by the user. Furthermore, dependencies of modules can be [replaced](https://thewebivore.com/using-replace-in-go-mod-to-point-to-your-local-module/) with files on-disk. I would like the [Go language server](golang.org/s/gopls) to watch all files in the module and replace directives, not just the files in the workspace.

**Comment by stamblerre** [comment]
@dbaeumer: Is there any possibility of this changing in the future? Opening a subdirectory of a module is quite common, as is having replace targets in a module. Without file watching on those directories, something as simple as switching branches results in incorrect diagnostics, since we don't have all of the correct file contents.

Without this, we will probably have to resort to implementing file watching server-side, which is explicitly not recommended in the [`didChangeWatchedFiles` documentation](https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#workspace_didChangeWatchedFiles).

**Comment by dbaeumer** [comment]
@stamblerre sorry, my comment from yesterday didn't make it into the issue.

This is currently not possible. The `didChangeWatchedFiles` is currently scope to the workspace. I should clarify the documentation around this. The reason for this is that on some platforms watching arbitrary file location can be expensive. 

Regarding your question:

I see your need for this. But supporting this would first need support in the corresponding VS Code API. All I can recommend for now is that you open an issue against VS Code itself to see if we can extend it there.

And yes, I still think it is better to have one source for file events than having every server implement their own.

**Comment by stamblerre** [comment]
Thanks for following up! I just filed https://github.com/microsoft/vscode/issues/100870.
