### ISSUE TITLE
Accessing registered language providers

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode-languageserver-node#642]
Is it possible to access the document symbol provider of the language client? 
(e.g. https://github.com/microsoft/vscode-languageserver-node/blob/4c20a1536dde04eb1a54fc1844d75e1e13b80a8e/client/src/common/client.ts#L1792)

Our extension (go) has features that require document symbol information, but they
do not fit well as general features the Go language server is interested in offering.
Currently we retrieve the information by running a third-party command line tool.
I wish we could use the language client instead.

Thanks!

**Comment by rcjsuen** [comment]
@hyangah Perhaps you can use a middleware to get a reference to the provider and then you can call it whenever you feel like to get symbol information?

**Comment by dbaeumer** [comment]
The latest version of the LSP client offers a `getFeature` method to access the feature on which you can then call the VS Code provide methods. They are forwarded to the server. See https://github.com/microsoft/vscode-languageserver-node/blob/master/client-node-tests/src/integration.test.ts#L250 as an example.

**Comment by hyangah** [comment]
Thanks @dbaeumer  - that's neat!
 
I found DocumentSymbolRequest.method is not one of them exposed. Is there any reason it is omitted?

**Comment by rcjsuen** [comment]
> I found DocumentSymbolRequest.method is not one of them exposed. Is there any reason it is omitted?

@hyangah It looks like it's there or am I looking at the wrong thing?

https://github.com/microsoft/vscode-languageserver-node/blob/d2a3322666101a3c246369f4098d430adc18f2d5/protocol/src/common/protocol.ts#L2107-L2108

**Comment by hyangah** [comment]
@rcjsuen I am talking about `getFeatures` https://github.com/microsoft/vscode-languageserver-node/blob/master/client/src/common/client.ts#L3315-L3342

**Comment by dbaeumer** [comment]
@hyangah it is a bug :-). You can use the string for now.

**Comment by dbaeumer** [comment]
Added
