### ISSUE TITLE
Crash with SyntaxError: Unexpected token C in JSON at position 1644

### ISSUE THREAD

**Issue by rlivings39** [microsoft/vscode-languageserver-node#643]
I saw a case very similar to https://github.com/microsoft/vscode-languageserver-node/issues/436

```
SyntaxError: Unexpected token C in JSON at position 1644
    at JSON.parse (<anonymous>)
    at StreamMessageReader.onData (node_modules/vscode-jsonrpc/lib/messageReader.js:182:29)
    at Socket.listen.readable.on (node_modules/vscode-jsonrpc/lib/messageReader.js:148:18)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

It looks like with certain characters the Emacs lsp-mode LSP client sends a bogus request. I've entered an issue with them to improve the situation https://github.com/emacs-lsp/lsp-mode/issues/1246

That issue contains repro steps and shows how to repro the example using a fork of the lsp-sample language server integrated into Emacs.

Could this repo be updated to more gracefully handle what looks to be a bogus request? That would help so that language servers don't get killed because of an issue in an LSP client.

Please let me know other info/debug output I can provide to help.

**Comment by dbaeumer** [comment]
@rlivings39 The problem might be that there is no way to get things in sync again. This must not necessarily be a request. It could also be a response and then we have dangling promises hanging around with no good indication what happened.

**Comment by rlivings39** [comment]
I see. That makes sense on the response side. Here I'm pretty sure this is the result of a request coming in from Emacs. Is there any info I could gather to motivate adding something in that case?

**Comment by dbaeumer** [comment]
You can add an onError handler on the connection to recognize this.

**Comment by rlivings39** [comment]
Thanks @dbaeumer  I did some poking around using that. In messageReader.js right before the error the buffer is:

```
this.buffer.buffer.toString()
"{"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///home/ry/lsptest/foo.txt","version":7},"contentChanges":[{"text":"%�"}]}}
Content-Length: 140

{"jsonrpc":"2.0","method":"textDocument/didSave","params":{"textDocument":{"uri":"file:///home/ry/lsptest/foo.txt","version":7},"text":null}}
...stuff...
```

Then after `var msg = this.buffer.tryReadContent(this.nextMessageLength);` we have:

```
this.buffer.buffer.toString()
"ontent-Length: 140

{"jsonrpc":"2.0","method":"textDocument/didSave","params":{"textDocument":{"uri":"file:///home/ry/lsptest/foo.txt","version":7},"text":null}}
```
and `msg` is:

```
msg
"{"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///home/ry/lsptest/foo.txt","version":7},"contentChanges":[{"text":"%�"}]}}
C"
```
That trailing "C" that breaks the JSON parse.

Presumably there's something broken with that initial request?

**Comment by dbaeumer** [comment]
The response has a wrong Content-Length set. This is why you end up with the additional "C". It basically belongs to the header of the next message.
