### ISSUE TITLE
Is it possible to implement a non-vscode LSP client using vscode-languageclient?

### ISSUE THREAD

**Issue by MozarellaMan** [microsoft/vscode-languageserver-node#645]
I've been trying to find out different resources on building custom language clients, that could be editor agnostic. Would it be possible to use the vscode-languageclient package to make a a "headless" client? It would only have access to the file system of the code - and can delegate navigation, highlighting etc. to other places.

Basically I'm trying to figure out ways to create a remote language server "proxy", or something to that effect

**Comment by rcjsuen** [comment]
@MozarellaMan I believe that is kind of the approach taken by the [monaco-languageclient project](https://github.com/TypeFox/monaco-languageclient/). They originally had a fork of `vscode-languageclient` but they don't do that anymore.

**Comment by dbaeumer** [comment]
@MozarellaMan this is currently not possible since the client depends on VS Code API. Abstracting that out is possible but requires quite some work.

I will keep it as a feature request if someone wants to work on it.

**Comment by MozarellaMan** [comment]
@dbaeumer If it's not much trouble, could you point me to where to look at in the repository and other resources that would help developing an abstraction? I wouldn't mind doing that work for my project

**Comment by dbaeumer** [comment]
Most of the VS Code specific code sits here: https://github.com/microsoft/vscode-languageserver-node/blob/master/client/src/common/client.ts#L1 and in the feature specific files (like `foldingRange.ts`)

**Comment by MozarellaMan** [comment]
@dbaeumer Thanks. Ha, you weren't lying about quite some work. Just so I have some sort of jumping point... If you were going to do it, the abstraction, where would you start?

**Comment by dbaeumer** [comment]
You first need to define all VS Code types used by LSP outside of VS Code. That is a lot of work and I am actually not sure if it is worth it. Have you considered using the protocol only package which has everything you need in terms of talking LSP messages and it is VS Code free.

**Comment by MozarellaMan** [comment]
No I haven't tried this package, I had thought the only other package was the server. That's a good shout. Thanks for all the info. This has really helped me understand my approach better!

**Comment by dbaeumer** [comment]
Great. I will close the issue then.
