### ISSUE TITLE
How to clear diagnostic when the file is closed.

### ISSUE THREAD

**Issue by Abbyyan** [microsoft/vscode-languageserver-node#648]
How can i clear the diagnostic info when the file is closed with LanguageClient? I can get the `didClose` info with `middleware`, but how can i remove the diagnostic in IDE? Hope for your help. Thanks a lot. 
```javascript
const clientOptions: LanguageClientOptions = {
  diagnosticCollectionName: 'test',
  middleware:{
    didClose:{xxx}
  }
}
```
![image](https://user-images.githubusercontent.com/12140508/87941071-27058100-cacd-11ea-9649-235c95212daf.png)

**Comment by dbaeumer** [comment]
You can do that from the server as  well. Simply push diagnostics using an empty array.

**Comment by Abbyyan** [comment]
> You can do that from the server as well. Simply push diagnostics using an empty array.

Is there any methods used in LanguageClient to realize this function? The editor can get the didClose info and clear will be implied on the client side. After the file is closed, there is no need to send the request on the server side

**Comment by Abbyyan** [comment]
`didClose` is a notification rather than requests.

**Comment by dbaeumer** [comment]
Yes, that is correct. You can still push an empty diagnostic array using the same notification you used to push the initial diagnostics.
