### ISSUE TITLE
json-rpc: Outstanding request promises should be rejected when MessageConnection is disposed

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vscode-languageserver-node#65]
The [promises that accumulate](https://github.com/Microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/main.ts#L117) from outbound requests that haven't resolved yet shouldn't be left unresolved forever if the `MessageConnection` is disposed or its underlying stream is ended.

And a stream's `end` event should result in these promises being rejected as well.

**Comment by dbaeumer** [comment]
Good catch.

**Comment by AArnott** [comment]
Thank you!

**Comment by riverar** [comment]
Is this issue actually resolved? This is in VS production installers...
```
JsonRpcConnection.prototype.dispose = function () {
    // Reject any pending outbound requests that haven't resolved already, since we won't get responses here on out.
    // TODO: code here, or get fix for https://github.com/Microsoft/vscode-languageserver-node/issues/65
    this.stream.end();
    this.connection.dispose();
};
```
