### ISSUE TITLE
Clicking on find references result leads to a textDocument/didOpen without a close

### ISSUE THREAD

**Issue by stamblerre** [microsoft/vscode-languageserver-node#652]
<details><summary>Versions used</summary><br><pre>
1.48.0-insider
0a7364f00514c46c9caceece15e1f82f82e3712f
x64
</pre>
<pre>
vscode-language-client version: 7.0.0-next.7
</pre>
</details>

I'm not sure if this is a VS Code or language client issue, so please transfer this if it's the wrong repository.
After calling find references, I clicked on the link to the file in the results (shown in the image below).

<img width="252" alt="Screen Shot 2020-07-22 at 8 49 30 PM" src="https://user-images.githubusercontent.com/5856771/88242967-da50b000-cc5c-11ea-824b-e3d410b50096.png">

This sent a `textDocument/didOpen` request for the file in question (`server_gen.go`). I then navigated back to the file explorer view and never looked at the references results again, but the server never received a `textDocument/didClose` for the file. I also tried clearing the results, but that also did not send a `textDocument/didClose`.

Is this intended behavior? Some of the logic in the Go language server relies on showing different diagnostics if a file is opened or closed, and this results in some unexpected behavior.

Thanks!

**Comment by dbaeumer** [comment]
@jrieken can you please comment on this. I am pretty sure that the event is not lost in the LSP client. I guess the file will never be closed in VS Code itself.

**Comment by dbaeumer** [comment]
Reopeing and ping a @jrieken

**Comment by kjeremy** [comment]
I can reproduce this using `rust-analyzer`

**Comment by kjeremy** [comment]
@jrieken 

![scratch-1596304308312](https://user-images.githubusercontent.com/4325700/89107346-6fdb0500-d3fe-11ea-9cb4-ec0fa83407b0.gif)

**Comment by kjeremy** [comment]
I believe that this can be closed. In vscode there is a 3 minute timer for references. Once triggered it sends a `didClose` notification.

**Comment by dbaeumer** [comment]
@kjeremy thanks for getting back. Closing then.
