### ISSUE TITLE
Dynamic documentSelector for multi-root workspace

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode-languageserver-node#653]
I'm wondering if there's a good way to achieve the following to support multi-root workspace in my case:

1. For each workspace folder, start a language server/client to handle the files in the workspace folder.
2. For untitled and external files (not in any workspace), start a default language server/client to handle.

I don't find a way to make this work as the `documentSelector` does not seem to work dynamically, i.e. overwriting the `documentSelector` of a started language client does not seem to have any effect.

I'm wondering if there's a programmable interface of document filtering?

**Comment by dbaeumer** [comment]
There is an example showing this here: https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-multi-server-sample

The trick is to have a client instance per server.

**Comment by renkun-ken** [comment]
I've implemented exactly one client per server but the lsp-multi-server-sample does not say how to handle untitled document and non-workspace files by one standalone server.

For example,

```
workspace1: test1.txt
workspace2: test2.txt
```

For workspace1, I start language server1, client1; for workspace2, start language server2, client2.
For an untitled document, and external document `~/test0.txt`, start language server3, client3.

But it looks not obvious how I should write the documentSelector of client3 to make it work only with untitled document and external documents.

**Comment by dbaeumer** [comment]
Simply create a selector without a pattern. VS Code first tries to find a selector with an exact match and the takes less exact selectors. So [scheme, language, pattern] wins over [scheme, language] which wins over [scheme]

**Comment by renkun-ken** [comment]
I tried creating two language client/servers with the following document selectors:

```typescript
const pattern = `${folder.uri.fsPath}/**/*`;
const documentSelector: DocumentFilter[] = [
    { scheme: 'file', language: 'r', pattern: pattern },
    { scheme: 'file', language: 'rmd', pattern: pattern },
];
```

and 

```typescript
const documentSelector: DocumentFilter[] = [
    { scheme: 'untitled', language: 'r' },
    { scheme: 'untitled', language: 'rmd' },
    { scheme: 'file', language: 'r' },
    { scheme: 'file', language: 'rmd' },
];
```

From the language server results (completion, document symbol), both langauge clients handles the same file that matches the pattern `${folder.uri.fsPath}/**/*`.

**Comment by dbaeumer** [comment]
You are correct  for those requests were VS Code implements a merge result behavior. What I described works only for the requests that a single target (for example folding ranges). Sorry about that.

What you can also do is to implement the right filtering in the middleware that you can plug into the LSP client. Every request sent to the server is going through that middleware (see https://github.com/microsoft/vscode-languageserver-node/blob/master/client/src/common/client.ts#L486 and https://github.com/microsoft/vscode-languageserver-node/blob/master/client/src/common/client.ts#L506)
