### ISSUE TITLE
Closing the window/extension host does not clean up language server processes

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-languageserver-node#654]
1. Have VS Code OSS opened to a custom user data dir.
1. Debug the "VS Code" launch config. Wait until language servers get spawned from the extension host process
1. Close the opened VS Code window
1. Observe that the "extension host" config stays around (which is my bug) but the language server processes are still running, even though the extension host process and associated vscode window are closed 🐛 

    ![](https://memes.peet.io/img/20-07-62210d09-25e0-4fe3-8e08-e9bf2f3b88b6.png)
    
    ![](https://memes.peet.io/img/20-07-57280895-d5ee-489f-97fc-d489b2703b31.png)

1. It seems that something is respawning them as well -- killing the processes in the task manager will close the servers but they get respawned
1. Close the remaining OSS window. Only at this point are the language server processes stopped

**Comment by dbaeumer** [comment]
I the extension host process still running. The servers are `owned` by the extension host process and as long as we have such a process the servers will not go away if their corresponding extension is activated. If we restart an extension host we even restart the servers if necessary

Are you sure that the extension host is not running anymore. There is no one  else that would start a server.

**Comment by connor4312** [comment]
I'm sure. But also, restarting the extension host in the parent window made them go away. I'm not sure how js-debug was able to attach to those -- that should only happen if the environment variables were shared between the extension host processes 🤔

**Comment by dbaeumer** [comment]
What the LSP client does is the following: if the extension is started in debug mode then all node servers started from the extension host are started in debug mode as well. Could that be the reason why JS Debug was able to attach to them?

**Comment by connor4312** [comment]
Looking more at the code it looks like the environment is shared when starting to debug. So I think this is actually working as designed, though we may need a guard in js-debug to avoid this.
