### ISSUE TITLE
Cleanup dangling WorkDoneProgress notifications when a language server crashes.

### ISSUE THREAD

**Issue by hokein** [microsoft/vscode-languageserver-node#656]
From https://github.com/clangd/vscode-clangd/issues/58.

the current implement cleans up the WorkDone notifications after receiving `WorkDoneProgressEnd` from a language server. If the language server crashes (the connect is not alive), the client side should cleanup the dangling notifications.

**Comment by dbaeumer** [comment]
Good catch.
