### ISSUE TITLE
Missing "shell" options in ChildProcess.spawn() method cause a UNKNOWN spawn Error when start a Java Language Service at Windows Platform 

### ISSUE THREAD

**Issue by GitPopcorn** [microsoft/vscode-languageserver-node#660]
I'm sorry I cannot record the very detail of this issue. I got only a few screenshots to describe it. So it's fine to close this issue if it cannnot be reproduced.

The error in VSCode window log.
![Snipaste_2020-08-20_09-26-15](https://user-images.githubusercontent.com/31797624/90706544-f1b8a280-e2c7-11ea-8b2c-4e9b085a4733.png)

The arguments used in spawn() method.
![Snipaste_2020-08-20_09-26-00](https://user-images.githubusercontent.com/31797624/90706543-efeedf00-e2c7-11ea-93a6-660fedc781e4.png)

Try to rerun the command in REPL of NodeJS
![Snipaste_2020-08-20_09-27-59](https://user-images.githubusercontent.com/31797624/90706549-f2e9cf80-e2c7-11ea-9c85-328c88117b8a.png)

In fact, I do keep a sh.exe/bash.exe in my PATH variables and can run "sh c:\Users\QQ370\.vscode\extensions\georgewfraser.vscode-javac-0.2.33\dist\\lang_server_windows.sh" immediately in terminal, but I'm not familiar with NodeJS so I don't know if it's necessary to adding the "shell = true" in the options of spawn.

**Comment by GitPopcorn** [comment]
I'm sorry I have check the source code of vscode-languageclient/lib/main.js and it seemed that there is no duty for vscode-languageclient to check the enviroment of current OS, all options except "cwd" or "env" come from the arguments gived by invoker. So I have closed this issue and moved it to the java-language-server project.

Give my sincere apology for you again.

**Comment by dbaeumer** [comment]
No problem :-)
