### ISSUE TITLE
vscode-languageclient@7.0.0-next.9 is not published to npmjs

### ISSUE THREAD

**Issue by jakebailey** [microsoft/vscode-languageserver-node#664]
The releases that happened yesterday left `@next` in an inconsistent state, as vscode-languageclient wasn't published to npmjs. We have to use a consistent version of vscode-jsonrpc to make the CancellationStrategy work, but the transient deps being different breaks things (which is another bug to file that's out of scope of this, how to make sure users of CancellationStrategy don't have to rely on hidden stuff).

Marginally related, but vscode-jsonrpc@6.0.0-next.5 is is published but the GitHub release claims it is 6.0.0-next.7. (Doesn't have any effect on the code, just GitHub.)

**Comment by dbaeumer** [comment]
Thanks for pointing this out. Fixed both.
