### ISSUE TITLE
Calling client.stop() may produce error in output panel

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode-languageserver-node#666]
In https://github.com/REditorSupport/vscode-r-lsp/pull/59, the language client works with a spawned process that runs the language server, and they communicate with each other via TCP socket.

The usage is, when the first untitled document is created with `r` language, then a new language server is started. All untitled documents share the same language client/server. If all untitled documents are closed, then shutdown the language server by calling `client.stop()`.

However, it usually (randomly) causes the following error in the output channel, which shift the view of the side panel to the error logging. This is quite annoying.

Output channel:

```
R Language Server (391970) started
[Error - 4:29:24 PM] Connection to server is erroring. Shutting down server.
[Error - 4:29:24 PM] Connection to server is erroring. Shutting down server.
R Language Server (391970) exited with exit code 0
```

Extension debug console

```
Error: Unexpected SIGPIPE
	at process.<anonymous> (/usr/share/code/resources/app/out/bootstrap.js:5:284)
	at process.emit (events.js:203:13)
```

This error seems to come from the language client but I'm not sure if there's a way to handle this error somewhere?

**Comment by dbaeumer** [comment]
Can you enable tracing so that we can see what messages are causing this?

**Comment by renkun-ken** [comment]
Here's a log I created with the problem reproduced:

[r-lsp.log](https://github.com/microsoft/vscode-languageserver-node/files/5162442/r-lsp.log)

Not sure if it is useful as I find little relevant information:

```
[Trace - 9:01:23 PM] Received response 'shutdown - (1)' in 229ms.
Result: []


[Trace - 9:01:23 PM] Sending notification 'exit'.
No parameters provided.


[Error - 9:01:23 PM] Connection to server is erroring. Shutting down server.
[Error - 9:01:23 PM] Connection to server is erroring. Shutting down server.
```

As the file is closed, `client.stop()` is called then the error occurs.

**Comment by dbaeumer** [comment]
That is strange since the client should not send anything after the exit. So unclear why it is erroring. I will have a look.

**Comment by dbaeumer** [comment]
OK. I looked through the doc and code and IMO the problem is that the connections needs to end their write streams. I have added code to the node server and the client to handle this poperly.

This being said server implemented in their own language need to do the same.

**Comment by renkun-ken** [comment]
Thanks!
