### ISSUE TITLE
Possibility of different diagnostic collections based on source

### ISSUE THREAD

**Issue by stamblerre** [microsoft/vscode-languageserver-node#667]
I was wondering if you had considered allowing language servers to have separate diagnostic collections, much like VS Code extensions. In the case of the Go language server, some types of diagnostics appear as files change and others are computed only when files are saved, etc. Having separate diagnostic collections would allow us to update only the relevant collections, rather than resending all of the current diagnostics + the new diagnostics.

Obviously this is something that the language server can handle without diagnostic collections, so it's certainly not a necessity, but it was something that came up for us in a discussion.

**Comment by rcjsuen** [comment]
@stamblerre It sounds like this is something that would be applicable to other LSP clients. Did you mean to create an issue in the [microsoft/language-server-protocol repository](https://github.com/microsoft/language-server-protocol/)?

**Comment by stamblerre** [comment]
Oh yes, I'm sorry, yes I did mean the other repo - opened https://github.com/microsoft/language-server-protocol/issues/1088 there and will close this issue.
