### ISSUE TITLE
Can I install multiple Completion handers?

### ISSUE THREAD

**Issue by CGQAQ** [microsoft/vscode-languageserver-node#668]
Can I call multiple times of [this method](https://github.com/microsoft/vscode-languageserver-node/blob/77c3a10a051ac619e4e3ef62a3865717702b64a3/server/src/common/server.ts#L1248) to install multiple handlers?

**Comment by rcjsuen** [comment]
@CGQAQ I don't think so. You should use a middleware to farm out the tasks to your different handlers.

**Comment by CGQAQ** [comment]
OK, I see, thank you

**Comment by rcjsuen** [comment]
@dbaeumer Would you agree?

**Comment by dbaeumer** [comment]
Currently you can't. But there are requests to support this.
