### ISSUE TITLE
Provide an API to get diagnostic from the client

### ISSUE THREAD

**Issue by XVincentX** [Microsoft/vscode-languageserver-node#67]
I open this issue after https://github.com/Microsoft/vscode/issues/9973#issuecomment-237245214

I'd like the ability to get diagnostic collection for a document from the client side.

//cc @dbaeumer

**Comment by XVincentX** [comment]
This is really cool! Thanks a lot!

**Comment by XVincentX** [comment]
When will this eventually land into VSCode? I'm still not able to find the new function!

**Comment by dbaeumer** [comment]
Is available in the 2.5.0 version of the client.

**Comment by XVincentX** [comment]
@dbaeumer I've just updated but still I'm not able to find this method. Which object should now have it? `textEditor`?
