### ISSUE TITLE
Feature request: mechanism for intercepting progress reports

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode-languageserver-node#671]
I want to intercept the progress messages sent from the server, but don't see how yet.
Other LSP messages, Middleware in LanguageClientOptions provides the functionality.
https://github.com/microsoft/vscode-languageserver-node/blob/f9c16a950d0791aab269b1a5507487d058712421/client/src/common/client.ts#L456-L488

Background: we want to enhance our integration tests by monitoring the progress reports from the language server, and ensuring the language server's internal state to be ready for probing/testing. If there is other way to achieve this, that's also appreciated.

**Comment by dbaeumer** [comment]
@hyangah this is currently not possible. Two ideas:

- we allow to access a set handler so that you can chain them
- we add middleware support for this

A PR would be welcome.

**Comment by DanTup** [comment]
@dbaeumer which option do you prefer, and can you give me some pointers? I'm trying to port some of my tests to LSP, and discovered that I can't get at the progress events (if I use `this.client.onProgress`, it complains that they're already being handled - I presume by the code that reports the progress to VS Code).

**Comment by dbaeumer** [comment]
@DanTup thanks for offering help. The right approach is a middle ware handler along the lines of the `handleDiagnostics` middleware since progress flows from the server to the client as well.

**Comment by DanTup** [comment]
@dbaeumer does this seem like the right idea?

https://github.com/DanTup/vscode-languageserver-node/commit/5812e670832d0ec7635addd73b0e65877d3acc47

I'm not sure how to simulate the progress from the server in the test though - I couldn't find a similar test to copy (I couldn't find any diagnostic one, for example).

**Comment by dbaeumer** [comment]
Added a comment here: https://github.com/DanTup/vscode-languageserver-node/commit/5812e670832d0ec7635addd73b0e65877d3acc47#commitcomment-43610915

**Comment by DanTup** [comment]
@dbaeumer in case you didn't see it, I responded here with a question or two:

https://github.com/DanTup/vscode-languageserver-node/commit/5812e670832d0ec7635addd73b0e65877d3acc47#commitcomment-43611962

**Comment by dbaeumer** [comment]
Sorry, too many things on my plate. I commented in the PR.

**Comment by ericdallo** [comment]
@dbaeumer @DanTup I just realized that I can't add `client.onProgress` for progress that server sends during `initialize` via the `$/progress` notification, which is allowed to be sent during server initialization.
When I try to `client.onProgress(...)` I get a `Language client is not ready yet when trying to send progress` not calling the `handleWorkDoneProgress`.
Is it possible to intercept the `$/progress` notifications during server initialization?

**Comment by dbaeumer** [comment]
@ericdallo this is currently not possible due to the limitation how the language client handles progress on initialize. You can open a issue to request that support.
