### ISSUE TITLE
Error codes are assigned an inappropriate ordinal for JSON-RPC spec

### ISSUE THREAD

**Issue by AArnott** [microsoft/vscode-languageserver-node#672]
The error codes defined below:

https://github.com/microsoft/vscode-languageserver-node/blob/66f91b3583a19ae621214d908ce19c9b2d182626/jsonrpc/src/common/messages.ts#L46-L49

are set to values within the [JSON-RPC spec](https://www.jsonrpc.org/specification#error_object) reserved range for server implementations:

code | message | meaning
-- | -- | --
-32000 to -32099 | Server error | Reserved for implementation-defined server-errors.

This JSON-RPC library does not ever use `ServerNotInitialized`. Who is using this? If [LSP is using it](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#responseMessage), shouldn't it be using a value defined in the range for the application layer?

> The remainder of the space is available for application defined errors.

It may be too late to 'fix' this, but I wanted to file this issue to draw attention that there is a JSON-RPC spec reserved range for error codes including a subrange reserved for the JSON-RPC implementation itself. Having the app-layer overlap with the implementation layer means that other JSON-RPC implementations (e.g. StreamJsonRpc) that want to use this particular value within their reserved range may cause malfunctions in the remote party that receives the error code and misinterprets it as an app-layer error.

To call out the conflicts we *already* have:

vscode-jsonrpc | error code | StreamJsonRpc
--|--|--
UnknownErrorCode | -32001 | NoMarshaledObjectFound
ServerNotInitialized | -32002 | ResponseSerializationFailure (proposed)
serverErrorEnd | -32000 | InvocationError
serverErrorStart | -32099 | (undefined)

While it's understandable that JSON-RPC implementations may define a given error code to mean different things, at least it's all in the implementation layer and won't be misinterpreted by the application. But when we have higher level protocols like LSP using error codes within the implementation-reserved range, we're going to get some bad behavior in the app that misinterprets the error code.

Can we add a comment to the source code (and LSP spec perhaps) so that future error codes are *not* defined in the library-reserved range?

**Comment by dbaeumer** [comment]
`serverErrorStart` and `serverErrorEnd` are not real error codes. That is why they are lower case. They denote the range that is blocked for server errors and shoouldn't be used by the application layer.

I agree on `ServerNotInitialized` and `UnknownErrorCode`. But shouldn't StreamJsonRpc avoid that range as well unless the error code makes it into the standard?

**Comment by AArnott** [comment]
> But shouldn't StreamJsonRpc avoid that range as well unless the error code makes it into the standard?

Per the spec:

> error codes from and including -32768 to -32000 are reserved for pre-defined errors

The spec then goes on to document some of that reserved range, including:

code | message | meaning
-- | -- | --
-32000 to -32099 | Server error | Reserved for implementation-defined server-errors.

I consider "implementation-defined" to mean JSON-RPC implementations, which is StreamJsonRpc in this case. It is within this range that all of StreamJsonRpc's custom errors are in fact defined.

**Comment by dbaeumer** [comment]
But wouldn't that again result in the same problem that you and me use the same code for a different meaning ?

**Comment by dbaeumer** [comment]
Then it would be OK to leave `UnknownErrorCode` in as well. I could even make arguments for `ServerNotInitialized` :-)

**Comment by rcjsuen** [comment]
> But wouldn't that again result in the same problem that you and me use the same code for a different meaning ?

That isn't the issue. That's what people are supposed to do. The error codes in that range are not for the application layer to interpret.

People that **use** a JSON RPC library should not assign meaning to error codes in those ranges because every JSON RPC implementation is going to be using error codes in that range for different purposes.

The people that **implement** a JSON RPC library should be the ones assigning their own custom meaning to an arbitrary code within that range. The application layer should simply surface it to the user as a generic "server error" failure case.

The issue here is that the LSP (the application layer) currently specifically defines -32002 as the error code for `ServerNotInitialized`. However, JSON RPC library A may be calling -32002 as `OutOfMemory` and JSON RPC library B may be calling it `SocketClosed`. These two very different error messages are going to be interpreted by LSP clients as "the server hasn't initialized yet" because they use the code -32002 when that isn't what either JSON RPC library is trying to convey at all.

**Comment by AArnott** [comment]
@rcjsuen explained my concern perfectly.

Except that I *am* interested in interop of certain JSON-RPC library-level error codes because we are effectively defining JSON-RPC "extensions" that the two libraries *should* to understand errors for. So two takeaways:

1. Don't use this range for LSP or other app-level error codes.
1. When defining new library-level error codes, let's each cross reference each other and try to not define new meaning to an existing code.

**Comment by rcjsuen** [comment]
> Except that I _am_ interested in interop of certain JSON-RPC library-level error codes because we are effectively defining JSON-RPC "extensions" that the two libraries _should_ to understand errors for.

@AArnott Are you just trying to interop the C# [microsoft/vs-streamjsonrpc](https://github.com/microsoft/vs-streamjsonrpc) library with `vscode-jsonrpc`?

**Comment by AArnott** [comment]
@rcjsuen In general we want to conform to the JSON-RPC spec and interop with any other library that does so.
However we do have extensions like support for `CancellationToken`, `Stream`, `IAsyncEnumerable<T>`, etc. While any library can implement the same extension, we particularly want to make sure that vscode-jsonrpc can interop with it because we own products that run either library that must be able to communicate over the wire.

**Comment by rcjsuen** [comment]
@AArnott By the way, since the values are defined in the LSP, I suggest you raise an issue in the [microsoft/language-server-protocol](https://github.com/microsoft/language-server-protocol/) repository.

**Comment by AArnott** [comment]
@rcjsuen That makes sense, but to what end? We're probably not going to be able to change the LSP spec. @dbaeumer is there any value in filing an issue on the LSP repo?

**Comment by rcjsuen** [comment]
> @rcjsuen That makes sense, but to what end? We're probably not going to be able to change the LSP spec.

If we can't remove them then we should at least deprecate those values and introduce new ones. At least new clients and servers won't make this mistake then.

By doing nothing we are continuing to make things difficult for people who implement the JSON RPC specification.

**Comment by dbaeumer** [comment]
> If we can't remove them then we should at least deprecate those values and introduce new ones. At least new clients and servers won't make this mistake then.

This has already happened. I can look to add a capability but I am not sure if this isn't overkill.

IMO what needs to be ensured as well is that error codes defined in the range of `-32099` to `-32000` are not allowed to flow over the wire. This was the confusion on my end when I saw `NoMarshaledObjectFound` and `ResponseSerializationFailure`. These are only use on the client or on the server but not for communication between them. Right?

**Comment by AArnott** [comment]
> error codes defined in the range of -32099 to -32000 are not allowed to flow over the wire.

I don't understand why. Anything that doesn't flow over the wire is out of scope of the spec as it is a wire protocol. Why would we need error codes for messages that don't get transmitted? To be sure, StreamJsonRpc has a variety of internal error conditions which we never transmit, and we do not assign error codes to them.

> NoMarshaledObjectFound and ResponseSerializationFailure. These are only use on the client or on the server but not for communication between them. Right?

Wrong. We do transmit them. The first is part of my general object marshaling extension and the second is just an error code that we use to signify a specific internal server error, not because the client should do anything specific with it, but to distinguish it from other error codes which the client _should_ handle.

**Comment by dbaeumer** [comment]
Very likely me not gettting it. 

If these internal error code flow over the wire how can be ensure that StreamJsonRpc is not returning error with meaning X and vscode-jsonrpc is interpreting it as an error of meaning Y?

**Comment by AArnott** [comment]
> If these internal error code flow over the wire how can be ensure that StreamJsonRpc is not returning error with meaning X and vscode-jsonrpc is interpreting it as an error of meaning Y?

That's the million dollar question. I suppose the best interoperable thing would generally be to consider all error codes in the 'internal range' _when they come in from a remote source_ as the same thing "internal error" and not branch on them at all if you don't know the remote source is running the same library that you are.

For those error codes that we _do_ specifically want to interop with across implementations, we obviously need to coordinate and share specs. But it doesn't answer the question of "*what range* do we define these codes within?" Should we use the internal server error code range, since no one else can claim ownership? Or should we use the reserve range for updates to the json-rpc spec? If there was a formal extension process like RFCs then each extension could "claim" a code from some reserved range so everyone knows that code means something specific. But AFAIK there is no such active forum for exchanging RFCs.

**Comment by dbaeumer** [comment]
> That's the million dollar question. 

That makes now sense to me. 

I do agree with everything you said. May be it is the easiest then to interpret these as internal errors as you suggested. Inside MS we could come up with a shared spec so that we can be more detailed if we know that both ends adhere to it.

How do you currently know that the other end is `StreamJsonRpc ` as well?

**Comment by AArnott** [comment]
> How do you currently know that the other end is StreamJsonRpc as well?

We don't. There's no "initialize" method in the json-rpc protocol itself. We haven't need it so far.
The `CancellationToken` extension is benign if the remote side doesn't recognize it. But some of these other extensions that deal with marshaled objects are definitely *not* benign if ignored since memory can leak on the originating side. So basically you shouldn't use those extensions unless you know the other side supports them. Whether the other side is streamjsonrpc or vscode-jsonrpc or a 3rd party library doesn't matter -- it's just whether it supports the extension. And if it supports the extension, then you can assume it recognizes the 'internal' error codes that the extension uses.

> Inside MS we could come up with a shared spec so that we can be more detailed if we know that both ends adhere to it.

Where do you think is the best place to put this shared spec? Would it just be a table of error codes and their meanings, perhaps with links to the extension spec that use them? 
And/or we could put hyperlinks in our source code where we define our own private error code enums that link to the other library's similar enum so that whenever we add an error code we know to double-check that the value we're assigning isn't already used by the other library.
