### ISSUE TITLE
No workDoneProgress for command execution

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode-languageserver-node#674]
Unsure if this is me doing something wrong, a bug, or just not yet implemented. I'm trying to use progress notifications for some longer running tasks (for example commands executed from code actions).

My server capabilities have `workDoneProgress: true`:

```js
{
	"id": 0,
	"jsonrpc": "2.0",
	"result": {
		"capabilities": {
			"executeCommandProvider": {
				"commands": [
					"edit.sortMembers",
					"edit.organizeImports",
					"edit.sendWorkspaceEdit",
					"refactor.perform"
				],
				"workDoneProgress": true
			},
		},
	}
}
```

Then in a Code Actions response, I include this command:

```js
{"id": 2,
	"jsonrpc": "2.0",
	"result": [
		{
			"title": "Extract Method",
			"kind": "refactor.extract",
			"command": {
				"title": "Extract Method",
				"command": "refactor.perform",
				"arguments": [
					"EXTRACT_METHOD",
					"/Users/danny/Desktop/dart_sample/lib/refactortest.dart",
					1,
					30,
					99,
					null
				]
			}
		}
	]
}
```

However, the call to execute the command does not pass a `workDoneToken`:

```js
{
	"jsonrpc": "2.0",
	"id": 5,
	"method": "workspace/executeCommand",
	"params": {
		"command": "refactor.perform",
		"arguments": [
			"EXTRACT_METHOD",
			"/Users/danny/Desktop/dart_sample/lib/refactortest.dart",
			1,
			30,
			99,
			null
		]
	}
}
```

I can make the server fall back to creating its own (if the client supports them) when this happens, but I wasn't sure if this is expected to work (if servers just fall back to creating their own tokens, I'm not sure what the benefit to the per-request tokens are).

**Comment by dbaeumer** [comment]
VS Code has no support for work done progress in requests. The capability is set to false (see also https://microsoft.github.io/language-server-protocol/specifications/specification-current/#signalingWorkDoneProgressReporting)

The property in the server capability is to flag the principal support on the server side. See same link.

Closing the issue since there is nothing I can do as long as VS Code is not setting up progress reporting in its UI.

**Comment by DanTup** [comment]
@dbaeumer maybe I have misunderstood the spec, but it reads like the `window.workDoneProgress` capability (which VS Code sets to `true`) signals that it's supported, and then the server can request it for individual requests (in its capabilities). It doesn't seem like there's a capability specifically for requests?

If so, it may be worth being clearer in the spec that just because the client has `workDoneProgress:true` and a server sets it on a provider, does not mean that a token will be provided (I had assumed it would, and that the client library would just use its standard progress indicator if it had no request-specific UI for it).

I've made the server fallback to a standard (server-created) token if one is not provided anyway, so it's working all the same.

**Comment by dbaeumer** [comment]
Sorry for the confusion, my fault. You are correct. The capability is for progress notification from the server to the client. Since every request has the option to provide work done progress (it doesn't make sense for every request) the availability of such a progress is signal by the token in the params.

**Comment by DanTup** [comment]
@dbaeumer am I right in assuming that just because the client has `workDoneProgress` support and the server says it would like (supports?) a token for a specific request, the client is not obliged to send one? If so, I think it's worth adding a note to that effect in the spec to ensure clients/servers have the same expectations.

My initial understanding was that if the client says it's supported and the server then "requests" it in its capabilities, that the client would definitely send one - though I now don't think that is the case (if it is, then this would be a bug).

Thanks!

**Comment by dbaeumer** [comment]
As the chapter tries to explain there are two different forms of progress: client initiated progress and server initiated progress. The capability `windows.workDoneProgress` is for server initiated progress. I will clarify this in the specification better.

**Comment by DanTup** [comment]
> The capability `windows.workDoneProgress` is for server initiated progress

Does this mean client-initiated progress reporting is possible even without that? If so, I think this is a bit misleading:

> To keep the protocol backwards compatible servers are only allowed to use work done progress reporting if the client signals corresponding support using the client capability window.workDoneProgress

I think it should say "servers are only allowed to *initiate* work done progress if the client supports it" as it sounds like client-initiated (where the server advertised support for it on a specific provider) is still allowed?

Otherwise, if servers should gate advertising workDoneProgress on their providers also on the client capability (which was my original assumption), then I think it's worth amending this text:

> For the above find references example a server would signal such a support by setting the referencesProvider property in the server capabilities as follows:

To include that a client may not send a `workDoneToken` even if the server advertised the support for it (in which case a server is free to either do its own server-initiated progress, or report no progress).

Thanks!

**Comment by dbaeumer** [comment]
Done. I spilt it into client and server initiated progress.

**Comment by DanTup** [comment]
Changes lgtm, thanks!
