### ISSUE TITLE
Semantic client capabilities: is refreshNotification in or out?

### ISSUE THREAD

**Issue by huguesv** [microsoft/vscode-languageserver-node#677]
I'm wondering about `refreshNotification` defined here:
https://github.com/microsoft/vscode-languageserver-node/blob/master/protocol/src/common/protocol.semanticTokens.ts#L186

Language client supports the notification, but is not setting that capability property to true.

LSP 3.16 is not documenting it.

Will the field be removed in a future update, or will it be added to the spec/language client?

thanks

**Comment by dbaeumer** [comment]
It will be supported in VS Code and part of the spec. I just didn't have the time yet to implement it :-)
