### ISSUE TITLE
Extend the documentFormattingProvider and documentRangeFormattingProvider interface with document selectors

### ISSUE THREAD

**Issue by DaanV2** [microsoft/vscode-languageserver-node#678]
**Feature Request**:

Extend the interface: `documentFormattingProvider`, `documentRangeFormattingProvider` with a document selector.

I'm currently developing a vscode plugin that uses a language server to support a new programming language. However, it is dependent on the content of JSON files. so in the `clientoptions` I had to define that it supports JSON files.

```ts
  let clientOptions: LanguageClientOptions = {
    // Register the server for plain text documents
    documentSelector: [
      { scheme: "file", language: McFunctionIdentifier },
      { scheme: "file", language: McLanguageIdentifier },
      { scheme: "file", language: "json" },
      { scheme: "file", language: "jsonc" },
    ],
}
```

I recently added a code formatter for the first two custom languages, but vscode now also tries to format json files using my language server.

Therefor, if we can configure on what language these features can be used. would resolve this issue.

**Comment by dbaeumer** [comment]
@DaanV2 dynamic registration (if support by the client which is the case or VS Code) is your friend here. See https://microsoft.github.io/language-server-protocol/specifications/specification-current/#client_registerCapability and https://github.com/microsoft/vscode-eslint/blob/master/server/src/eslintServer.ts#L887 as an example.
