### ISSUE TITLE
Using Languageclient with external server - conflicting spawn events

### ISSUE THREAD

**Issue by SeeBasTStick** [microsoft/vscode-languageserver-node#679]
Hello, 
I hope this is the right place to ask my question:
With the help of https://github.com/microsoft/language-server-protocol/issues/604 and https://github.com/microsoft/vscode-languageserver-node/issues/662 I was able to configure my client to deal with my external java server. When I start the plugin in the sandbox everything works fine and dandy, but problems start when I pack my extension to test it in the real world. I identified the problem at the point where I spawn the server:
```export function activate(context: ExtensionContext) {


	const serverHome = "serverHome" //my java server home
	const javaHome: string = workspace.getConfiguration("common").get("javaHome")



	//Start the server
	let prc : ChildProcessWithoutNullStreams
	prc = spawn(javaHome, ['-jar', serverHome])

        prc.stdout.on('data', function (data) {

		let connectionInfo = {
			port: 55555,
		}

                //Set up client
       ...
```
I start the server in every instance of the extension and this will lead to conflicts when the extension is activated on workspace level, leading to the extansion not working (thats my assumption). When I deactivated the extension for workspace level everything works normal. My question: Is there an elegant way to deal with this problem out of the box? I have tried to store the prc variable with a construct like
```
if(globalState.get("probLanguageServer")!=null){
		prc = globalState.get("probLanguageServer")
	}else{
		prc = spawn(javaHome, ['-jar', serverHome])
		globalState.update("probLanguageServer", prc)
	}
```
and set it to 'null' when the extension is closed but that seems not the right way to do the things. Every help would be appreciated.

**Comment by dbaeumer** [comment]
The recommended way to start a server available as a executable is to use a function as the server options. See https://github.com/microsoft/vscode-languageserver-node/blob/master/client/src/node/main.ts#L123 and the definition `() => Promise<ChildProcess | StreamInfo | MessageTransports | ChildProcessInfo>`

You should then use the `onReady()` promise to know when the server and client is ready to do further configuration of the server.

**Comment by dbaeumer** [comment]
Please ping if this doesn't help.
