### ISSUE TITLE
New converter trustMarkdown check is inverted

### ISSUE THREAD

**Issue by jakebailey** [microsoft/vscode-languageserver-node#681]
The new trustMarkdown boolean for #503 is inverted:

https://github.com/microsoft/vscode-languageserver-node/blob/ccb894231aae0942d2cc29fd2381ccf51ac4f823/client/src/common/protocolConverter.ts#L249

I think this is a typo and should have been `!!trustMarkdown` to convert to a default value of `false`. Maybe the more readable `trustMarkdown ?? false`... :)

**Comment by dbaeumer** [comment]
Good catch. I don't even know why that was in there since the line is totally unnecessary since the test is `if (trustMarkdown === true)`

Removed the line.
