### ISSUE TITLE
DocumentSelector has wrong type

### ISSUE THREAD

**Issue by rchl** [microsoft/vscode-languageserver-node#685]
`DocumentSelector` defined in https://github.com/microsoft/vscode-languageserver-node/blob/e3d3314932ea92fbc175d96c400f7ac9ae81985b/protocol/src/common/protocol.ts#L118-L118 has wrong type. The spec only allows the `DocumentSelector` to be an array of `DocumentFilter`, not an array of strings [1].

[1] https://microsoft.github.io/language-server-protocol/specification#documentFilter

**Comment by dbaeumer** [comment]
Actually this is some legacy compatibility code. I should document this since in an early version this was supported as a string. We could break it though.

**Comment by rchl** [comment]
> Actually this is some legacy compatibility code. I should document this since in an early version this was supported as a string. We could break it though.

Can you clarify whether you mean that this library has supported a plain string or that the spec has supported it before?
