### ISSUE TITLE
codeLens resolve request not work

### ISSUE THREAD

**Issue by johnsoncodehk** [microsoft/vscode-languageserver-node#689]
I have try `onCodeLensResolve()` and `onRequest('codeLens/resolve')`, behaves like not registered.

When I force the trigger it will throw:
```
(node:97732) UnhandledPromiseRejectionWarning: Error: Request client/registerCapability failed with message: No feature implementation for codeLens/resolve found. Registration failed.
    at handleResponse (/***/node_modules/vscode-jsonrpc/lib/main.js:449:48)
    at processMessageQueue (/***/node_modules/vscode-jsonrpc/lib/main.js:276:17)
    at Immediate.<anonymous> (/***/node_modules/vscode-jsonrpc/lib/main.js:260:13)
    at processImmediate (internal/timers.js:439:21)
(node:97732) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:97732) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Info  - 1:53:16 PM] Registering request handler for codeLens/resolve failed.
```

Reproduce: https://github.com/johnsoncodehk/vscode-extension-samples/tree/codeLens-resolve-bug/lsp-sample

**Comment by dbaeumer** [comment]
Which version of the library are you using?

**Comment by johnsoncodehk** [comment]
@dbaeumer I'm using 3.15.3, and the reproduce sample project should be show the problem.

**Comment by dbaeumer** [comment]
The feature is marked for 3.16 which is not officially released yet. You can use a 3.16 next build but the API might not be stable yet and might change until 3.16 is released.

**Comment by johnsoncodehk** [comment]
@dbaeumer I will try 3.16, thanks!

**Comment by johnsoncodehk** [comment]
@dbaeumer I have try 3.16.0-next.11 but still not work, is this expected?
this is what I changed to reproduce project: https://github.com/johnsoncodehk/vscode-extension-samples/commit/d5d59ee33bf3be07b8cf602370d4e61a80e8d5d5

**Comment by dbaeumer** [comment]
Hmm, what do you mean by `3.16.0-next.11`. Since you are developing a VS Code extension you need to pull in the latest VS Code client LSP libs which are `vscode-languageclient@7.0.0-next.14`

**Comment by johnsoncodehk** [comment]
@dbaeumer sorry I didn't make it clear. I mean `vscode-languageserver-protocol@3.16.0-next.11`.
I tried `vscode-languageserver@7.0.0-next.11`+`vscode-languageclient@7.0.0-next.14` and it still doesn't work.
changes: https://github.com/johnsoncodehk/vscode-extension-samples/commit/e91184695dfe263a67995ffda49bdd6da36f6e39

**Comment by dbaeumer** [comment]
Hmm, are you telling the client to call the server for code actions and code action resolve request ?

**Comment by dbaeumer** [comment]
Actually there seems to be something missing here. Let me investigate.

**Comment by dbaeumer** [comment]
Looked into it. The client side is wired up correctly, but for the server side you need to register the handler on the connection itself using `connection.onRequest(CodeActionResolveRequest.type, ....)`

**Comment by johnsoncodehk** [comment]
@dbaeumer I tried `CodeActionResolveRequest.type` but it throw this error:
> ```
> (node:97732) UnhandledPromiseRejectionWarning: Error: Request client/registerCapability failed with message: No feature implementation for codeLens/resolve found. Registration failed.
>     at handleResponse (/***/node_modules/vscode-jsonrpc/lib/main.js:449:48)
>     at processMessageQueue (/***/node_modules/vscode-jsonrpc/lib/main.js:276:17)
>     at Immediate.<anonymous> (/***/node_modules/vscode-jsonrpc/lib/main.js:260:13)
>     at processImmediate (internal/timers.js:439:21)
> (node:97732) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:97732) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> [Info  - 1:53:16 PM] Registering request handler for codeLens/resolve failed.
> ```

**Comment by dbaeumer** [comment]
@johnsoncodehk you can't dynamically register for `CodeActionResolveRequest.type`. You can only register for `CodeActionRequest.type`

**Comment by johnsoncodehk** [comment]
@dbaeumer I think it has nothing to do with `CodeAction`, it should just be about `CodeLens`?

**Comment by dbaeumer** [comment]
Sorry, misread. You can't register for CodeLensResolveRequest either. You need to register for CodeLensRequest and specify that you will provide a resolve provider.

**Comment by johnsoncodehk** [comment]
@dbaeumer we should have `CodeLensResolveRequest`, otherwise there has serious performance issue.

for example, many extensions has references codeLens like this: https://stackoverflow.com/questions/48131241/how-to-move-codelens-references-indicator

`CodeLensRequest` need to return all codeLens text in current script, it mean if the script have 100 codeLens locations, will execute 100 times `find references` on each code edit to show references count. we expected only visible codeLens to do `fine references`.

**Comment by dbaeumer** [comment]
There is a code lens resolve request since a very long time. See here: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#codeLens_resolve and the implementation for VS Code here: https://github.com/microsoft/vscode-languageserver-node/blob/master/protocol/src/common/protocol.ts#L2659

**Comment by johnsoncodehk** [comment]
@dbaeumer yes I know but it throw error and not work, it is why I open this issue... so this is a bug or I'm doing wrong?

**Comment by dbaeumer** [comment]
It throws when registering. As said you can't register for a resolve request since it doesn't make sense by itself. You register for a code lens request and specify that you provide a resolve provider. See https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_codeLens 'Server Capability' and 'RegistrationOptions'

**Comment by johnsoncodehk** [comment]
@dbaeumer I tried before but no effect: https://github.com/johnsoncodehk/vscode-extension-samples/commit/006f41557cee007dee6493f0512b4fa408061f24#diff-1d9e3f731e806171e44f99395224c664e78cf42edec01303f9dca7d328f05427L57

`connection.onCodeLensResolve` will never trigger.

**Comment by dbaeumer** [comment]
Resolving code actions works for me in my test bed without problems.

Looking at your code the code lens you are returning is already completely resolved (e.g. has a command). This is why the resolve hook is not called.

**Comment by dbaeumer** [comment]
Change this
```
connection.onCodeLens(
	(_textDocumentPosition: CodeLensParams): CodeLens[] => {
		// The pass parameter contains the position of the text document in
		// which code complete got requested. For the example we ignore this
		// info and always provide the same completion items.
		return [
			{
				range: Range.create(0, 0, 0, 0),
				command: {
					title: 'not resolve',
					command: ''
				}
			}
		];
	}
);
```
too
```
connection.onCodeLens(
	(_textDocumentPosition: CodeLensParams): CodeLens[] => {
		// The pass parameter contains the position of the text document in
		// which code complete got requested. For the example we ignore this
		// info and always provide the same completion items.
		return [
			{
				range: Range.create(0, 0, 0, 0)
			}
		];
	}
);

```

**Comment by johnsoncodehk** [comment]
@dbaeumer This is the answer! if post on first comment will be better. but nice to see it can be resolve, thanks a lot!

On my test it seem not trigger on visible, I'm not sure it can be avoid the performance issue I say. but anyway my problem is resolve.
