### ISSUE TITLE
LanguageClientOptions.initializationOptions not passed to server

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-languageserver-node#69]
i'm trying to pass custom data from the client to the server through LanguageClientOptions.initializationOptions and I want to access them in server's onInitialize method.  

In the client:

``` javascript
	let clientOptions: LanguageClientOptions = {
		documentSelector: ['javascript', 'javascriptreact'],
		synchronize: {
			configurationSection: 'jscs',
			fileEvents: workspace.createFileSystemWatcher('**/.jscsrc')
		},
		
		initializationOptions: 'dirk, why doesnt this get passed to the server?!?'

	}
```

In the server i get 'undefined':

``` javascript
onnection.onInitialize((params): Thenable<server.InitializeResult | server.ResponseError<server.InitializeError>> => {
	let rootPath = params.rootPath;

	// why don't we get the string from the client?
	connection.console.log(params.initializationOptions);

```

see https://github.com/Microsoft/vscode-jscs/tree/chrisdias/bugbug and search for "Dirk" in both the jscs and jscs-server projects.

**Comment by chrisdias** [comment]
client:
https://github.com/Microsoft/vscode-jscs/blob/chrisdias/bugbug/jscs/extension.ts#L29

server:
https://github.com/Microsoft/vscode-jscs/blob/chrisdias/bugbug/jscs-server/src/server.ts#L189

**Comment by dbaeumer** [comment]
Works for me using the latest version of the libraries. I see

```ts
	let clientOptions: LanguageClientOptions = {
		documentSelector: ['bat'],
		synchronize: {
			configurationSection: 'testbed'
		},
		diagnosticCollectionName: 'markers',
		initializationOptions: 'Chris it gets passed to the server',
       }
```

Server side:
```ts
	connection.console.log('Initialization options recevied on server: ' + JSON.stringify(params.initializationOptions));
```

![capture](https://cloud.githubusercontent.com/assets/1931590/17629029/9ab0a28e-60b8-11e6-8cfc-2885cbba3ab2.png)

**Comment by dbaeumer** [comment]
Which version of the client and server lib are you using?

**Comment by dbaeumer** [comment]
You can also debug the server using options like
```ts
	let debugOptions = { execArgv: ["--nolazy", "--debug-brk=6005"] };
	let serverOptions = {
		run: { module, transport: TransportKind.ipc },
		debug: { module, transport: TransportKind.ipc, options: debugOptions}
	};
```

**Comment by chrisdias** [comment]
Argh, it works today, didn't work yesterday.  I have no idea why... :(

**Comment by chrisdias** [comment]
Debugging now works for me too, i couldn't get it to break in onInitialize yesterday either (with --debug-brk).  At least I'm in a good state now.
