### ISSUE TITLE
Unregistering semantic token does not fall back to original highlighting

### ISSUE THREAD

**Issue by stamblerre** [microsoft/vscode-languageserver-node#691]
I would expect that unregistering the `textDocument/semanticTokens` capability would change the highlighting back to the original implementation, but it doesn't seem to switch back to the default VS Code highlighting--it appears to still be using the server's highlighting.

**Comment by dbaeumer** [comment]
@alexdima I debugged my code and when semantic tokens get unregistered in LSP I basically dispose the provider I registered (e.g. I call dispose on the Disposable returned from `registerDocumentSemanticTokensProvider`). Is there anything else I need to do or is this a bug on VS Code side?

**Comment by dbaeumer** [comment]
@alexdima can you please comment.

**Comment by dbaeumer** [comment]
Ping @alexdima

**Comment by alexdima** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/97196

**Comment by dbaeumer** [comment]
@alexdima thanks!
