### ISSUE TITLE
Can the asWorkspaceEdit in protocolConverter exposed as a utility method?

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-languageserver-node#698]
Here is the background for the question.

In Java extensions, sometimes the extension may need to resolve some LSP-formatted workspace edit in their Java OSGI bundle, for example:

- Resolving a quickfix for a Checkstyle violation
- Generating a test class for a focal class

and when the LSP-formatted workspace edit return to the typescript side, they need to be converted to the VS Code's format before calling `workspace.applyEdit()`.

The method `asWorkspaceEdit()` is an instance method inside the language client, it's not easy for the Java extensions (Test Runner, Checkstyle, etc...) to do such converts since they do not have a language client instance. Is it possible to make it as a utility method?

@dbaeumer Do you have any suggestion on this? Or do I miss any background context here?

Thanks in advance!

**Comment by dbaeumer** [comment]
The protocol converter depends on the URI converter which is set by the client. You can always import the protocol converter directly and instantiate your own if you need to.

```typescript
import * as codeConverter from 'vscode-languageclient/lib/common/codeConverter';
import * as protocolConverter from 'vscode-languageclient/lib/common/protocolConverter';
```

I don't have any plans to make the official API sine it will not allow me to restructure the code if needed.

Will this work for you?

**Comment by jdneo** [comment]
Thank you @dbaeumer, I think this is a good idea!

I'm also thinking about export an API from the Java Language extension side, which converts the protocol edit to code edit. The benefit of this is that the implementation will always be align with the real language client. On the other hand, this is also a little bit wired since the convert thing is not a Java specific functionality, but we put it as an API.

Do you have any preference for this?

**Comment by dbaeumer** [comment]
If you expose such an API I would always only forward to the above converters. Then you can catch up with changes.

**Comment by jdneo** [comment]
Thank you for the help. I think I can first use the above import statement. If in the future there are more use scenarios, we can consider make it as an extension API for the Java Language Server extension. :)
