### ISSUE TITLE
onLinkedEditingRange should not define `never` as error type

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-languageserver-node#700]
https://github.com/microsoft/vscode-languageserver-node/blob/53d122831050088171296dc02b57257f5178f0b6/server/src/common/linkedEditingRange.ts#L21

All other messages define `void`, e.g.
https://github.com/microsoft/vscode-languageserver-node/blob/53d122831050088171296dc02b57257f5178f0b6/server/src/common/server.ts#L1249

**Comment by dbaeumer** [comment]
Good catch. Will fix.

**Comment by aeschli** [comment]
Still not fixed here: https://github.com/microsoft/vscode-languageserver-node/blob/277eb6dd7a5207cb80091a3d8d2c17decd1f5723/server/src/common/linkedEditingRange.ts#L21

**Comment by dbaeumer** [comment]
Finally https://github.com/microsoft/vscode-languageserver-node/pull/1679
