### ISSUE TITLE
Make FileOperationPattern more like document filters

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-languageserver-node#704]
Currently the pattern doesn't allow to specify a scheme like we do for document filters. We should make this consistent and should support scheme filtering as well.

**Comment by dbaeumer** [comment]
@DanTup please note that this changes the API surface which you need to adopt when 3.16 is released. But for consistency I opted to do the change.

**Comment by dbaeumer** [comment]
Here is an example how this looks now: https://github.com/microsoft/vscode-languageserver-node/blob/master/client-node-tests/src/servers/testServer.ts#L127

**Comment by DanTup** [comment]
Makes sense to me - I'll update my server to match and re-test. Do you plan to push a new pre-release version?

**Comment by dbaeumer** [comment]
Actually I didn't since I hoped that VS Code ships today. If it doesn't I will tomorrow. Is that OK for you?

**Comment by DanTup** [comment]
Ah, even better. No need to make a pre-release if the release is that close. It's a little easier for me to test the server with a release from npm (I had some weird issues with `npm pack`) so I just wondered whether to wait for it.

Thanks!

**Comment by dbaeumer** [comment]
@DanTup the new VS Code release is out but it happened this morning. Due to that I shifted the 3.16 release to Monday next week since it need to do quite some editing work to make it happen and I don't want to break people over the weekend. 

I did do a new next release in case you want to adopt.

**Comment by DanTup** [comment]
Sounds good to me, thanks!

**Comment by dbaeumer** [comment]
@DanTup  Just one additional hint: please use the next version with 1.51.

**Comment by DanTup** [comment]
> Just one additional hint: please use the next version with 1.51.

Not entirely sure what this means - can you elaborate? Do you mean just to do some extra testing? (I was going to update the required version to v1.52 for the next version of Dart-Code as I wasn't sure how compatible the client was intended to be with older versions).

**Comment by dbaeumer** [comment]
The next version has compile errors with 1.52 due to the move of proposed API in VS Code to final.

**Comment by DanTup** [comment]
Ah, got it. I didn't get around to trying the next version, so if you're likely to publish final versions today, tomorrow I'll just hang fire for them and use them (+ increasing requirements to 1.52) together. Thanks!
