### ISSUE TITLE
How can codeLens showing be triggered manually?

### ISSUE THREAD

**Issue by bpringe** [microsoft/vscode-languageserver-node#705]
Hi, just a question here. My extension has a setting for enabling references code lens. I use middleware to provide this enable/disable capability (`provideCodeLenses` and `resolveCodeLenses`).

When I disable code lens in settings while a code file with visible code lenses is in another editor column, the code lenses do not disappear, but if I open another editor in that column and reopen the first editor, they show up.

How can I manually make VS Code recompute/re-show (or not show) code lenses for all visible editors? The only solution I've found thus far is pretty hacky - I apply an edit so that the code lenses are recomputed, and then I delete the edit.

```typscript
                const edit1 = new vscode.WorkspaceEdit();
                edit1.insert(editor.document.uri, new vscode.Position(0, 0), '\n');
                await vscode.workspace.applyEdit(edit1);
                const edit2 = new vscode.WorkspaceEdit();
                edit2.delete(editor.document.uri, new vscode.Range(0, 0, 1, 0));
                await vscode.workspace.applyEdit(edit2);
```

I feel there must be a better way. I've also called `sendRequest` to send a `textDocument/codeLens` request and a `codeLens/resolve` request, and I see the response come back, but VS Code does not do anything automatically with the response, which is where I feel my understanding is lacking.

**Comment by johnsoncodehk** [comment]
I have same request to semanticTokens, I just reregister to force trigger refresh, I think is should be work to codeLens too.
```ts
let semanticTokensRequest = await connection.client.register(SemanticTokensRegistrationType.type, { ... });

function forceReloadTokens() {
	semanticTokensRequest.dispose();
	semanticTokensRequest = await connection.client.register(SemanticTokensRegistrationType.type, { ... });
}
```

**Comment by dbaeumer** [comment]
You have two options:

- the upcoming 3.16 release has a mechanism to retrigger all code lenses in all files for a given provider (https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#codeLens_refresh)
- better would be to dynamically register code lenses. When you then disabled code lenses simple de-register the code lens provider (see https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#client_registerCapability)

**Comment by bpringe** [comment]
Thank you both for the information.
