### ISSUE TITLE
Can't disable full document semantic tokens request

### ISSUE THREAD

**Issue by johnsoncodehk** [microsoft/vscode-languageserver-node#706]
I try to disable providing semantic tokens for a full document. But when I edit document, `semanticTokens.on()` is allways trigger ,not `semanticTokens.onRange()`.

codes:
```ts
connection.languages.semanticTokens.on((handler, token, workDoneProgress, resultProgress) => {
	const t = Date.now();
	try {
		// ...
	}
	finally {
		console.log(`semanticTokens.on, time: ${Date.now() - t}ms`);
	}
})
connection.languages.semanticTokens.onRange((handler, token, workDoneProgress, resultProgress) => {
	const t = Date.now();
	try {
		// ...
	}
	finally {
		console.log(`semanticTokens.onRange, time: ${Date.now() - t}ms, lines: ${handler.range.start.line} ~ ${handler.range.end.line}`);
	}
});
connection.client.register(SemanticTokensRegistrationType.type, {
	// ...
	range: true,
	full: false, // <------------ disabled
});
```

log:
```log
semanticTokens.onRange, time: 342ms, lines: 0 ~ 94
semanticTokens.on, time: 1447ms
semanticTokens.onRange, time: 21ms, lines: 0 ~ 93
semanticTokens.on, time: 2206ms
semanticTokens.on, time: 1419ms
semanticTokens.on, time: 1382ms
semanticTokens.on, time: 1435ms
semanticTokens.on, time: 1375ms
semanticTokens.on, time: 1372ms
semanticTokens.on, time: 1916ms
semanticTokens.on, time: 1937ms
```

**Comment by dbaeumer** [comment]
I think the spec is not clear here and I will clarify it. 

Clients can decide that they need a full document request to function correctly (for example to color a minimap). So if a server doesn't provide it a client might not show semantic tokens even if the server does provide a range request. The range request for example is an optimization when a file gets opened.

**Comment by johnsoncodehk** [comment]
Thanks for reply.

I need the same behavior as `typescript-language-features`, `typescript-language-features` only call range document request don't used full document request. I can only register `DocumentRangeSemanticTokensProvider` in client to do it.

It mean base on spec, LSP won't support `range only request` even has `{ full: false }` option? It is like a wrong design.

**Comment by dbaeumer** [comment]
The spec can't force all clients to handle range only. There are clients out there that simply can't implement this. This is why the spec behaves that way and it does in all other cases. So it is not a wrong design. It is on purpose!

This being said VS Code does support it and there was a problem in the library that didn't call range in the absence of full. I fixed that.

**Comment by johnsoncodehk** [comment]
I no need to color the minimap, so this is the correct behavior for me. I will test it in the next version, thank you.

**Comment by johnsoncodehk** [comment]
`{ full: false }` still not working in 7.0.0.

log:
```log
[Info  - 4:04:50 PM] Registering request handler for textDocument/semanticTokens/full failed.
(node:63936) UnhandledPromiseRejectionWarning: Error: Request client/registerCapability failed with message: No feature implementation for textDocument/semanticTokens/full found. Registration failed.
    at handleResponse (/Users/johnsonchu/Desktop/GitHub/volar/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
    at processMessageQueue (/Users/johnsonchu/Desktop/GitHub/volar/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
    at Immediate.<anonymous> (/Users/johnsonchu/Desktop/GitHub/volar/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
    at processImmediate (internal/timers.js:439:21)
(node:63936) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:63936) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by dbaeumer** [comment]
The registration method for semantic tokens is `textDocument/semanticTokens` (see https://github.com/microsoft/vscode-languageserver-node/blob/master/protocol/src/common/protocol.semanticTokens.ts#L268)

**Comment by dbaeumer** [comment]
See also https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_semanticTokens

**Comment by johnsoncodehk** [comment]
@dbaeumer please check this changes: https://github.com/johnsoncodehk/vscode-languageserver-node/commit/8325a4ae5e2796d1659d3e8e1867236df6ebb6f5

when I changed `full: { delta: true }` to `full: false`, and remove `connection.languages.semanticTokens.on()`, server just output [this error](https://github.com/microsoft/vscode-languageserver-node/issues/706#issuecomment-753446028).

this problem make me can't register semantic tokens by LSP, so I only can [register in client](https://github.com/johnsoncodehk/volar/blob/master/packages/client/src/semanticTokens.ts) now.

**Comment by dbaeumer** [comment]
This works for me

```
[Trace - 11:53:11 AM] Received request 'client/registerCapability - (2)'.
Params: {
    "registrations": [
        {
            "id": "06c1741e-11fc-4cef-b929-3b436c657f56",
            "method": "textDocument/semanticTokens",
            "registerOptions": {
                "documentSelector": [
                    "bat"
                ],
                "legend": {
                    "tokenTypes": [
                        "comment",
                        "keyword",
                        "string",
                        "number",
                        "regexp",
                        "type",
                        "class",
                        "interface",
                        "enum",
                        "typeParameter",
                        "function",
                        "type",
                        "property",
                        "variable",
                        "parameter",
                        "function"
                    ],
                    "tokenModifiers": [
                        "abstract",
                        "deprecated"
                    ]
                },
                "range": true,
                "full": false
            }
        }
    ]
}


[Trace - 11:53:11 AM] Sending response 'client/registerCapability - (2)'. Processing request took 0ms
No result returned.
```

Did you run `npm run symlink:testbed` before using the testbed?

**Comment by johnsoncodehk** [comment]
I will try again with `npm run symlink:testbed`.
