### ISSUE TITLE
LanguageClient doesn't show any error if initialization fails

### ISSUE THREAD

**Issue by llali** [Microsoft/vscode-languageserver-node#71]
I created a LanguageClient passing the path to a dll for Language Server. If the dll doesn't exist, the initialization fails but I don't see any error in the extension. I tracked the problem and realized in main.js/Initialize method when it's handling the error, the error.data is undefined so that's why the onReadyCallbacks.reject() is never get called. I added check null for error.data and error.data.retry and it fixed the problem. Not sure if there's something I'm missing or there's actually a bug in the main.ts

**Comment by dbaeumer** [comment]
There is actually a real bug. The code can't assume that the error is of type response error since the error could be a normal program exception as well.
