### ISSUE TITLE
semver violation, vscode-languageclient 6.1.3 can install vscode-languageserver-protocol 3.16  but they don't work together

### ISSUE THREAD

**Issue by tetron** [microsoft/vscode-languageserver-node#710]
I have a language server client with a dependency `"vscode-languageclient": "^6.1.3"` in package.json.

vscode-languageclient has a dependency `"vscode-languageserver-protocol": "^3.15.3"`.  This means that minor version increments are supposed to be compatible.

When I did `npm install` it installed vscode-languageserver-protocol 3.16.  However, that version IS NOT compatible with vscode-languageclient 6.1.3, this is what happens:

```
node_modules/vscode-languageclient/lib/client.d.ts:2:19 - error TS2305: Module '"../../vscode-languageserver-protocol/lib/common/api"' has no exported member 'RPCMessageType'.

2 import { Message, RPCMessageType, ResponseError, RequestType, RequestType0, RequestHandler, RequestHandler0, GenericRequestHandler, NotificationType, NotificationType0, NotificationHandler, NotificationHandler0, GenericNotificationHandler, MessageReader, MessageWriter, Trace, Event, ClientCapabilities, TextDocumentRegistrationOptions, InitializeParams, InitializeResult, InitializeError, ServerCapabilities, DocumentSelector, DidOpenTextDocumentNotification, DidChangeTextDocumentNotification, DidCloseTextDocumentNotification, DidSaveTextDocumentNotification, WillSaveTextDocumentNotification, WillSaveTextDocumentWaitUntilRequest, FileEvent, CompletionRequest, HoverRequest, SignatureHelpRequest, DefinitionRequest, ReferencesRequest, DocumentHighlightRequest, WorkspaceSymbolRequest, CodeActionRequest, DocumentFormattingRequest, DocumentRangeFormattingRequest, DocumentOnTypeFormattingRequest, RenameRequest, DocumentLinkRequest, ProgressType, StaticRegistrationOptions, DocumentColorRequest, DeclarationRequest, FoldingRangeRequest, ImplementationRequest, SelectionRangeRequest, TypeDefinitionRequest, Proposed } from 'vscode-languageserver-protocol';
                    ~~~~~~~~~~~~~~

node_modules/vscode-languageclient/lib/client.d.ts:413:33 - error TS2314: Generic type 'RequestType0<R, E>' requires 2 type argument(s).

413     sendRequest<R, E, RO>(type: RequestType0<R, E, RO>, token?: CancellationToken): Promise<R>;
                                    ~~~~~~~~~~~~~~~~~~~~~~

node_modules/vscode-languageclient/lib/client.d.ts:414:36 - error TS2314: Generic type 'RequestType<P, R, E>' requires 3 type argument(s).

414     sendRequest<P, R, E, RO>(type: RequestType<P, R, E, RO>, params: P, token?: CancellationToken): Promise<R>;
                                       ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/vscode-languageclient/lib/client.d.ts:417:31 - error TS2314: Generic type 'RequestType0<R, E>' requires 2 type argument(s).

417     onRequest<R, E, RO>(type: RequestType0<R, E, RO>, handler: RequestHandler0<R, E>): void;
                                  ~~~~~~~~~~~~~~~~~~~~~~

node_modules/vscode-languageclient/lib/client.d.ts:418:34 - error TS2314: Generic type 'RequestType<P, R, E>' requires 3 type argument(s).

418     onRequest<P, R, E, RO>(type: RequestType<P, R, E, RO>, handler: RequestHandler<P, R, E>): void;
                                     ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/vscode-languageclient/lib/client.d.ts:420:32 - error TS2315: Type 'NotificationType0' is not generic.

420     sendNotification<RO>(type: NotificationType0<RO>): void;
                                   ~~~~~~~~~~~~~~~~~~~~~

node_modules/vscode-languageclient/lib/client.d.ts:421:35 - error TS2314: Generic type 'NotificationType<P>' requires 1 type argument(s).

421     sendNotification<P, RO>(type: NotificationType<P, RO>, params?: P): void;
                                      ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/vscode-languageclient/lib/client.d.ts:424:30 - error TS2315: Type 'NotificationType0' is not generic.

424     onNotification<RO>(type: NotificationType0<RO>, handler: NotificationHandler0): void;
                                 ~~~~~~~~~~~~~~~~~~~~~

node_modules/vscode-languageclient/lib/client.d.ts:425:33 - error TS2314: Generic type 'NotificationType<P>' requires 1 type argument(s).

425     onNotification<P, RO>(type: NotificationType<P, RO>, handler: NotificationHandler<P>): void;
                                    ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/vscode-languageclient/lib/client.d.ts:498:32 - error TS2708: Cannot use namespace 'Proposed' as a value.

498     getFeature(request: typeof Proposed.CallHierarchyPrepareRequest.method): DynamicFeature<TextDocumentRegistrationOptions> & TextDocumentProviderFeature<TypeDefinitionProvider>;
                                   ~~~~~~~~

node_modules/vscode-languageclient/lib/workspaceFolders.d.ts:3:48 - error TS2305: Module '"../../vscode-languageserver-protocol/lib/common/api"' has no exported member 'RPCMessageType'.

3 import { ClientCapabilities, InitializeParams, RPCMessageType, ServerCapabilities, WorkspaceFoldersRequest } from 'vscode-languageserver-protocol';
```

I fixed this by explicitly downgrading and pinning to vscode-languageserver-protocol 3.15.3.

It seems like vscode-languageserver-protocol has some critical backwards-incompatible change between 3.15 and 3.16 where either it should have maintained backwards compatibility or been a major (4.0) version increment by the semver rules used by npm.

**Comment by hmmmmniek** [comment]
so temporary fix is:

Client package.json
```
{
  ...
  "engines": {
    "vscode": "^1.42.0"
  },
  "dependencies": {
    ....
    "vscode-languageclient": "6.1.1",
    "vscode-languageserver-protocol": "3.15.3"
  },
  "devDependencies": {
  ...
    "@types/vscode": "^1.42.0"
  }
}
```

Server package.json
```
{
  ...
  "engines": {
    "node": "*"
  },
  "dependencies": {
    ...
    "vscode-languageserver": "6.1.1",
    "vscode-languageserver-protocol": "3.15.3"
  },
  "devDependencies": {
    ...
    "@types/vscode": "^1.42.0"
  }
}
```

This seems to work for me

**Comment by dbaeumer** [comment]
Actually, this is quite tricky: the protocol package follows the version number of the LSP specification. Although the LSP spec version 3.16 is backwards compatible with 3.15 the TypeScript interfaces aren't. I agree that from a semver point of view we should have move to 4.0 but that would be very confusing since the protocol package 4.0 would be for LSP version 3.16. 

To avoid such a confusion in the future the LSP client and server package have no a concrete version dependency on protocol (e.g. no ^version).

I can if necessary make a 6.x version of the client and server package which pins 3.15.3 of the protocol. Let me know how important that is for you.

**Comment by valentjn** [comment]
I'm not OP, but I'm also affected by this.

IMO, if there's the possibility that the LSP spec is backward compatible but the Typescript interfaces aren't, then the versions need to be decoupled. The LSP spec is then treated as a "dependency" of the Typescript interfaces. The LSP version that the interface uses can be documented in the changelog of the interfaces. Possible confusion of the version numbers are avoided if the numbers are clearly distinct (e.g., let the interface version start from 10 or so). This would also enable having independent bugfix releases for spec and interfaces.

For me, that would be better than the confusion that follows from not adhering to the SemVer spec.

That being said, a bugfix release is not necessary for me as the workaround is only one line.

**Comment by tetron** [comment]
> I can if necessary make a 6.x version of the client and server package which pins 3.15.3 of the protocol. Let me know how important that is for you.

I think that would be a good idea.  The workaround isn't difficult but understanding the cause of the error in order to get to the workaround was a headache.

(For me this came up trying to contribute to a project where I was trying to build for the first time, it is off-putting when it doesn't build.)

**Comment by dbaeumer** [comment]
Decoupling the protocol version from the package version would require to move the node specific code of the protocol package to its own package. But even then a change in the TS compile might still result in compile errors.

The protocol package is actually backwards compatible in the sense of JSON schemas. It is not in terms of TS typings. When we last discussed this we decided to do explicit versioning since there was a expressed need to keep with LSP version and the protocol version in sync.

I will create a 6.1.x version to avoid the problem.

**Comment by dbaeumer** [comment]
Release `vscode-languageclient@6.1.4` which precisely depends on `3.15.3` of the protocol.
