### ISSUE TITLE
Request to move semantic token types to the types package

### ISSUE THREAD

**Issue by rcjsuen** [microsoft/vscode-languageserver-node#711]
Right now, the semantic token types are all in the protocol package. Can these (or some of them at least) be moved to the types package instead?
- `SemanticTokenTypes`
- `SemanticTokens`
- `SemanticTokensDelta`
- `SemanticTokensDeltaPartialResult`
- `SemanticTokensEdit`
- `SemanticTokensLegend`
- `SemanticTokensPartialResult`

**Comment by dbaeumer** [comment]
Moved minus `SemanticTokensDeltaPartialResult` and `SemanticTokensPartialResult` because they are request specific.

**Comment by rcjsuen** [comment]
@dbaeumer Thanks for moving them over.

Can you update this issue when you make a release of the packages to npm? Thank you!

**Comment by dbaeumer** [comment]
I currently plan to make a new release end of January (aligned with the next VSCode release)
