### ISSUE TITLE
client/registerCapability sent for workspace/didChangeWorkspaceFolder even if dynamicRegistration set to false during initialization

### ISSUE THREAD

**Issue by mjlbach** [microsoft/vscode-languageserver-node#713]
Moving from https://github.com/microsoft/pyright/issues/1302

**Describe the bug**

We have support for pyright as one of the language servers for neovim's built in language client which uses vscode-languageserver-node. One issue seems to be cropping up on node 15 where failed callbacks result in node terminating the process. The main callback that is failing is client/registerCapability, (our client doesn't support dynamic registration). When we report dynamicRegistration as false, pyright is still sending client/registerCapability requests

```
[ DEBUG ] 2020-12-20T13:55:08-0800 ] /home/michael/neovim/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	
"decoded"	{  id = 0,  jsonrpc = "2.0",  method = "client/registerCapability",  params = {    registrations = { {        
id = "807eedda-04cf-4637-9cb7-81d5f5d0e225",        method = "workspace/didChangeWorkspaceFolders",       
 registerOptions = vim.empty_dict()      } }  }}
```
We're initializing the server with all dynamicRegistration capabilities registered as false

<details open>
<summary>json of initialization params</summary>

```json
{
  "initialize_params": {
    "capabilities": {
      "callHierarchy": {
        "dynamicRegistration": false,
        "textDocument": {
          "codeAction": {
            "codeActionLiteralSupport": {
              "codeActionKind": {
                "valueSet": [
                  "",
                  "Empty",
                  "QuickFix",
                  "Refactor",
                  "RefactorExtract",
                  "RefactorInline",
                  "RefactorRewrite",
                  "Source",
                  "SourceOrganizeImports",
                  "quickfix",
                  "refactor",
                  "refactor.extract",
                  "refactor.inline",
                  "refactor.rewrite",
                  "source",
                  "source.organizeImports"
                ]
              }
            },
            "dynamicRegistration": false
          },
          "completion": {
            "completionItem": {
              "commitCharactersSupport": false,
              "deprecatedSupport": false,
              "documentationFormat": [
                "markdown",
                "plaintext"
              ],
              "preselectSupport": false,
              "snippetSupport": false
            },
            "completionItemKind": {
              "valueSet": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23,
                24,
                25
              ],
              "contextSupport": false,
              "dynamicRegistration": false
            },
            "declaration": {
              "linkSupport": true
            },
            "definition": {
              "linkSupport": true
            },
            "documentHighlight": {
              "dynamicRegistration": false
            },
            "documentSymbol": {
              "dynamicRegistration": false,
              "hierarchicalDocumentSymbolSupport": true,
              "symbolKind": {
                "valueSet": [
                  1,
                  2,
                  3,
                  4,
                  5,
                  6,
                  7,
                  8,
                  9,
                  10,
                  11,
                  12,
                  13,
                  14,
                  15,
                  16,
                  17,
                  18,
                  19,
                  20,
                  21,
                  22,
                  23,
                  24,
                  25,
                  26
                ]
              }
            },
            "hover": {
              "contentFormat": [
                "markdown",
                "plaintext"
              ],
              "dynamicRegistration": false
            },
            "      implementation": {
              "        linkSupport": true
            },
            "references": {
              "dynamicRegistration": false
            },
            "rename": {
              "dynamicRegistration": false,
              "prepareSupport": true
            },
            "signatureHelp": {
              "dynamicRegistration": false,
              "signatureInformation": {
                "documentationFormat": [
                  "markdown",
                  "plaintext"
                ]
              }
            },
            "      synchronization": {
              "didSave": true,
              "dynamicRegistration": false,
              "willSave": false,
              "willSaveWaitUntil": false
            },
            "      typeDefinition": {
              "        linkSupport": true
            }
          },
          "workspace": {
            "applyEdit": true,
            "configuration": true,
            "symbol": {
              "dynamicRegistration": false,
              "hierarchicalWorkspaceSymbolSupport": true,
              "symbolKind": {
                "valueSet": [
                  1,
                  2,
                  3,
                  4,
                  5,
                  6,
                  7,
                  8,
                  9,
                  10,
                  11,
                  12,
                  13,
                  14,
                  15,
                  16,
                  17,
                  18,
                  19,
                  20,
                  21,
                  22,
                  23,
                  24,
                  25,
                  26
                ]
              }
            },
            "workspaceFolders": true
          }
        },
        "initializationOptions": {},
        "processId": 53558,
        "rootPath": "/home/michael/Repositories/pytorch_learning",
        "rootUri": "file:///home/michael/Repositories/pytorch_learning",
        "trace": "off",
        "workspaceFolders": [
          {
            "name": "/home/michael/Repositories/pytorch_learning",
            "uri": "file:///home/michael/Repositories/pytorch_learning"
          }
        ]
      }
    }
  }
}
```
</details>

**To Reproduce**
This can't be reproduced in vscode. I believe lsp-mode for emacs also implements dynamic registration, so the only way to reproduce this is to install neovim and nvim-lspconfig on node 14 (which doesn't crash). I know this is out of scope for pyright so I will do all of the legwork on fixing this.

**Expected behavior**
Pyright doesn't send registerCapability requests to the client if dynamicRegistration is set to false (or unset)

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool? Which version? You can find the version of the VS Code extension by clicking on the Pyright icon in the extensions panel.

**Additional context**
As mentioned I'm happy to submit a PR to fix this if acceptable, I've just had trouble finding exactly where in the pyright languageserver extension dynamicRegistration is read from initialization params, and where the registerCapability request is triggered.

**Comment by dbaeumer** [comment]
@mjlbach there is little I can do in the VS Code LSP libraries to avoid this. I recommend that you open an issue against the corresponding LSP server that should respect that setting.

Please ping if you think otherwise.

**Comment by mjlbach** [comment]
@dbaeumer The problem seems to be common to all language servers that use vscode-languageserver-node as a basis, and opt into workspace support. Clients that also indicate workspace support, but disable dynamic registration, still receive a 'client/registerCapability' handler for notifications. I did chat with the pyright author about this, and looked through pyright to confirm the issue was in the functionality implemented in this library. I'll try to put together a PR. I did end up adding dynamicRegistration support to our client for now.

**Comment by bmewburn** [comment]
I think this is where it's happening https://github.com/microsoft/vscode-languageserver-node/blob/5b93b5b655c2e6daf9b15ed3295263b819958775/server/src/common/workspaceFolders.ts#L40

**Comment by dbaeumer** [comment]
The server lib doesn't auto register for the notification. It only does so if the server that uses the lib accesses `onDidChangeWorkspaceFolders` to register a listener. Does the client at all support workspace folders (e.g. the get request and the change notification0?

**Comment by dbaeumer** [comment]
https://github.com/microsoft/vscode-languageserver-node/blob/master/server/src/common/workspaceFolders.ts#L35

**Comment by mjlbach** [comment]
We don't support notification client/registerCapability, generally, so when the server sends workspace/didChangeWorkspaceFolders to register for notifications, it would historically have throw an UnhandledPromiseRejectionWarning until node 15 changed it such that unhandled promises terminated node. 

Currently our users manually add/remove workspace folders, each time our client sends a `workspace/didChangeWorkspaceFolders`. So it is in effect providing the notification for which the server is trying to register for, but I still thought according to the spec, if we set dynamicRegistration to false for workspace folders, we shouldn't be receiving `client/registerCapability` at all.

**Comment by dbaeumer** [comment]
The workspace folder support has no `dynamicRegistration` property so a client can't disable registering for change notifications if it opts into workspace folder support. 

What I can do in the lib is to check for `workspace.workspaceFolders.supported`

**Comment by mjlbach** [comment]
Ah sorry, I was referring to all of the capabilities listed under `workspace.fileOperations` which includes dynamicRegistration.  There's also `didChangeWatchedFiles` which we set to false. We currently broadcast `workspace.workspaceFolders.supported` as true since we do technically support it, just not the callback for `client/registerCapability`.

**Comment by dbaeumer** [comment]
Actually there is already a property on the server side to control this. It is `changeNotifications` defined here: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_workspaceFolders

I changed the code to honor that flag when accessing `onDidChangeWorkspaceFolders`. I will also clarify the spec around this.

**Comment by mjlbach** [comment]
Thank you! And also thank you for your work in supporting the broader language server protocol ecosystem!
