### ISSUE TITLE
createConnection overloads not visible in package

### ISSUE THREAD

**Issue by DaanV2** [microsoft/vscode-languageserver-node#716]
I recently tried to update my language server to 7.0.0

but my connection creation on the server-side keeps returning an error. And I cannot find any documentation on the new parameters that are apparently needed on how to properly set it up.

The code that I used:

```ts
  let connection = createConnection(ProposedFeatures.all);
```

returns the following error:
`Expected 2-3 arguments`.

So I went looking through the package and found the following:

in `lib/common/server.d.ts` is the function for:

```ts
export declare function createConnection<PConsole = _, PTracer = _, PTelemetry = _, PClient = _, PWindow = _, PWorkspace = _, PLanguages = _>(connectionFactory: (logger: Logger) => ProtocolConnection, watchDog: WatchDog, factories?: Features<PConsole, PTracer, PTelemetry, PClient, PWindow, PWorkspace, PLanguages>): _Connection<PConsole, PTracer, PTelemetry, PClient, PWindow, PWorkspace, PLanguages>;
```

But there are 4 overloads in `lib/node/main.d.ts` that I believe to be the correct overloads for the user to be using.
However, the only one I get recommended or seems to exist is the one in `server.js`

I'm unsure if it is something I have done wrong gets wrongly exported or is just missing documentation atm.

My project in question: https://github.com/Blockception/VSCode-Bedrock-Development-Extension/tree/Language-server-update

**Comment by rcjsuen** [comment]
@DaanV2 I ran into this yesterday as well. I had to fix it by importing from `vscode-languageserver/node` instead of `vscode-languageserver`.

**Comment by DaanV2** [comment]
while normal compiling works, my web package has problems with using `vscode-languageserver/node` as it cannot find a defined module.

**Comment by rcjsuen** [comment]
> while normal compiling works, my web package has problems with using `vscode-languageserver/node` as it cannot find a defined module.

@DaanV2 Can you share your code and/or error message?

**Comment by DaanV2** [comment]
https://github.com/Blockception/VSCode-Bedrock-Development-Extension/tree/master

And I run the build task in vscode. And the error messages:
```
ERROR in ./server/src/server/Setup.ts 33:15-52
Module not found: Error: Can't resolve 'vscode-languageserver/node' in 'F:\Projects\Blockception\VSCode-Bedrock-Development-Extension\server\src\server'
 @ ./server/src/server.ts 8:16-41

ERROR in F:\Projects\Blockception\VSCode-Bedrock-Development-Extension\server\src\progress\ProgressHandler.ts
./server/src/progress/ProgressHandler.ts
[tsl] ERROR in F:\Projects\Blockception\VSCode-Bedrock-Development-Extension\server\src\progress\ProgressHandler.ts(37,21)
      TS2709: Cannot use namespace 'WorkDoneProgress' as a type.
 @ ./server/src/progress/include.ts 15:13-41
 @ ./server/src/include.ts 37:32-61
 @ ./server/src/types/minecraft/resource/Process.ts 6:18-45
 @ ./server/src/process/traverse.ts 36:18-64
 @ ./server/src/process/include.ts 31:13-34
 @ ./server/src/server/onInitialized.ts 37:18-47
 @ ./server/src/server/Setup.ts 37:24-50
 @ ./server/src/server.ts 8:16-41

ERROR in F:\Projects\Blockception\VSCode-Bedrock-Development-Extension\server\src\progress\ProgressHandler.ts
./server/src/progress/ProgressHandler.ts
[tsl] ERROR in F:\Projects\Blockception\VSCode-Bedrock-Development-Extension\server\src\progress\ProgressHandler.ts(40,76)
      TS2709: Cannot use namespace 'WorkDoneProgress' as a type.
 @ ./server/src/progress/include.ts 15:13-41
 @ ./server/src/include.ts 37:32-61
 @ ./server/src/types/minecraft/resource/Process.ts 6:18-45
 @ ./server/src/process/traverse.ts 36:18-64
 @ ./server/src/process/include.ts 31:13-34
 @ ./server/src/server/onInitialized.ts 37:18-47
 @ ./server/src/server/Setup.ts 37:24-50
 @ ./server/src/server.ts 8:16-41

ERROR in F:\Projects\Blockception\VSCode-Bedrock-Development-Extension\server\src\progress\ProgressHandler.ts
./server/src/progress/ProgressHandler.ts
[tsl] ERROR in F:\Projects\Blockception\VSCode-Bedrock-Development-Extension\server\src\progress\ProgressHandler.ts(128,27)
      TS2709: Cannot use namespace 'WorkDoneProgress' as a type.
 @ ./server/src/progress/include.ts 15:13-41
 @ ./server/src/include.ts 37:32-61
 @ ./server/src/types/minecraft/resource/Process.ts 6:18-45
 @ ./server/src/process/traverse.ts 36:18-64
 @ ./server/src/process/include.ts 31:13-34
 @ ./server/src/server/onInitialized.ts 37:18-47
 @ ./server/src/server/Setup.ts 37:24-50
 @ ./server/src/server.ts 8:16-41

ERROR in F:\Projects\Blockception\VSCode-Bedrock-Development-Extension\server\src\server\Setup.ts
./server/src/server/Setup.ts
[tsl] ERROR in F:\Projects\Blockception\VSCode-Bedrock-Development-Extension\server\src\server\Setup.ts(30,52)
      TS2307: Cannot find module 'vscode-languageserver/node' or its corresponding type declarations.
 @ ./server/src/server.ts 8:16-41
 ```

**Comment by rcjsuen** [comment]
@DaanV2 You should also update your `vscode-languageserver` dependency to 7.x instead of using 6.x. That's what I did with my language server.

**Comment by DaanV2** [comment]
Thanks!, I had it correct on a different branch but not the main branch, sorry for that.

**Comment by dbaeumer** [comment]
Looks like this got resolved. Ping if not the case.

**Comment by dbaeumer** [comment]
@rcjsuen thanks for helping out.

**Comment by rwalle** [comment]
Just a note for anyone who run into this issue while following the [lsp-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-sample):

The code in the lsp-sample has been [updated](https://github.com/microsoft/vscode-extension-samples/blob/d81f44d8897cb8a6c249f498ce2ef3dea68f50ab/lsp-sample/server/src/server.ts#L18) just a few days ago, and it uses the exact same change @rcjsuen mentioned in this issue -- changing `vscode-languageserver` to `vscode-languageserver/node`. So, if you run into this problem it means you need to update your local clone of the repository.

**Comment by gustavosimon** [comment]
I was facing this problem, and this issue had the response to my problem. Thank u guys!
