### ISSUE TITLE
LanguageClient type not found

### ISSUE THREAD

**Issue by freesonlee** [microsoft/vscode-languageserver-node#718]
Hi, I installed client 7.0 and found that the LanguageClient is defined in main.d.ts, however, the typings in packages.json is api.d.ts, which doesn't have LanguageClient defined.

Here is the [package json](https://github.com/microsoft/vscode-languageserver-node/blob/master/client/package.json)
And here is the [api.ts](https://github.com/microsoft/vscode-languageserver-node/blob/master/client/src/common/api.ts)

In 6.1.3 client, the typings is main https://github.com/microsoft/vscode-languageserver-node/blob/release/client/6.1.x/client/package.json

Maybe I missing something in setup?

**Comment by larshp** [comment]
see https://github.com/microsoft/vscode-eslint/blob/master/client/src/extension.ts#L15

try changing the import to
`import {LanguageClient} from 'vscode-languageclient/node';`

**Comment by freesonlee** [comment]
that works.
Thanks
