### ISSUE TITLE
Is $/cancelRequest only effective if it is the next request after the one to be cancelled?

### ISSUE THREAD

**Issue by bmewburn** [microsoft/vscode-languageserver-node#722]
I'm debugging an issue in the intelephense php extension and trying to understand when `CancellationToken.isCancellationRequested` is set to true.

Say I have the following messages sent (in order):

```
[Trace - 6:13:44 pm] Sending notification 'textDocument/didChange'.
[Trace - 6:13:44 pm] Sending request 'textDocument/foldingRange - (25)'.
[Trace - 6:13:44 pm] Sending request 'textDocument/codeAction - (26)'.
[Trace - 6:13:44 pm] Sending notification '$/cancelRequest'.
[Trace - 6:13:44 pm] Sending notification 'textDocument/didChange'.
[Trace - 6:13:44 pm] Sending notification '$/cancelRequest'.
```

If I look at `triggerMessageQueue` and `processMessageQueue` here
https://github.com/microsoft/vscode-languageserver-node/blob/5bc82ac3c1c656aa70615c9e3e065fa04e41506e/jsonrpc/src/common/connection.ts#L572

It looks like a single request/notification is dispatched and then the next and so on.
Now looking at `callback` here
https://github.com/microsoft/vscode-languageserver-node/blob/5bc82ac3c1c656aa70615c9e3e065fa04e41506e/jsonrpc/src/common/connection.ts#L602

It looks like the messages that haven't been queued yet are inspected to see if there is a `$/cancelRequest`, but unless there is some middleware provided by the consumer of the connection then nothing appears to happen to the undispatched messages.

https://github.com/microsoft/vscode-languageserver-node/blob/5bc82ac3c1c656aa70615c9e3e065fa04e41506e/jsonrpc/src/common/connection.ts#L534

There doesn't appear to be any change to the order when queued
https://github.com/microsoft/vscode-languageserver-node/blob/4495ea1c881c7b919ce4a151233cf1b20f3e73ba/jsonrpc/src/common/connection.ts#L527

Now say my server request handlers are async (`setImmediate`) but not the notifications which are run synchronously.
So `processMessageQueue` sticks `textDocument/foldingRange` on the event loop, which my handler just `setImmediate`s so its back on the event loop and `processMessageQueue` grabs the next and so on.

My understanding is the sequence of events would be

eventLoop = [];
push dispatchFoldingRange -> [dispatchFoldingRange]
shift dispatchFoldingRange which pushes foldingRangeHandler -> [foldingRangeHandler]
push dispatchCodeAction -> [foldingRangeHandler, dispatchCodeAction]
shift foldingRangeHandler (maybe big expensive routine) -> [dispatchCodeAction]
push dispatchCancelRequest  ->  [dispatchCodeAction, dispatchCancelRequest]
shift dispatchCodeAction which pushes codeActionHandler -> [dispatchCancelRequest, codeActionHandler]
push dispatchDidChange ->  [dispatchCancelRequest, codeActionHandler, dispatchDidChange]
shift dispatchCancelRequest **Too late foldingRangeHandler already executed**

So the expensive foldingRangeHandler appears to get executed before cancellation is processed. Have I got this correct or am I missing something? Would it be more effective to have the cancellation tokens generated in the message reader callback and then matched up to the target request when that request is dispatched?

**Comment by dbaeumer** [comment]
Couple of comments:

- cancelling undispatched message by removing them from the queue requires the support from the server. Reason is that the server needs to send a response for a updispatch message and the library itself can't decide how the response has to look like in all cases. Hence the `cancelUndispatched` handler
- being able to cancel things highly depends on the server using async code patterns. If a request is already dispatch and no async code is executed the event loop and not be processed and hence the request can't be canceled. To work around this the library has support for a pluggable cancelation strategy. See https://github.com/microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/node/test/customCancellationStrategy.ts#L56 for an example that uses a file system to cancel a request which makes it work even if the server doesn't use any async code.

This being said we should do one improvement here: https://github.com/microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/common/connection.ts#L624. Before adding the message to the queue we should set the token source as canceled which will help if the request is not dispatched yet.

**Comment by dbaeumer** [comment]
I added some code to improve the situation. See https://github.com/microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/common/connection.ts#L625

**Comment by bmewburn** [comment]
Great! thanks @dbaeumer
