### ISSUE TITLE
enable willRenameFiles for folder rename

### ISSUE THREAD

**Issue by ShuiRuTian** [microsoft/vscode-languageserver-node#724]
LSP 3.16 add `willRenameFiles`.
This works well for files change. But how to enable this feature for folder rename?
For my case, the clientOption is something like 
```
   // this is not important, only means I want to log, and here is a good place to set breakpoint.
    const workspace:lc.WorkspaceMiddleware = {
        willRenameFiles:function<P extends vscode.FileRenameEvent,R extends Thenable<vscode.WorkspaceEdit | null | undefined>>(this: void, data: P, next:(data: P) => R ){
            console.log(data);
            return next(data);
        }
    }


    const clientOption = {
            documentSelector: [
                { scheme: 'file', language: 'rust' }
            ],
            ...
            middleware:{
                ...
                workspace
            }
    }

    const client = new lc.LanguageClient(
        'rust-analyzer',
        'Rust Analyzer Language Server',
        serverOptions,
        clientOptions,
    );
    ....
```
I guess the key is documentSelector? But how to select folder?

**Comment by dbaeumer** [comment]
The `willRenameFiles` event is not bound to document selector. When registering you need to provide a pattern. See `FileOperationPattern` here: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_willCreateFiles

**Comment by ShuiRuTian** [comment]
Whoops, thanks so much for the kind answer. This really helps me a lot!
