### ISSUE TITLE
The diagnosis of multiple files with dependencies won't clear until reopening file

### ISSUE THREAD

**Issue by myfirenze** [microsoft/vscode-languageserver-node#728]
There are two files A and B in the project. The code of file A depends on file B. The server pushes an error diagnosis about A. To modify it, I need to modify file B. However,  the server does not push new error diagnosis and the error diagnosis of the file is not eliminated after I fix the error code in file A. The diagnosis won't clear until I re-open A. How does the server recompute diagnosis of multiple files with dependencies after one of them changed?  The language is c++ and the server is clangd.

**Comment by dbaeumer** [comment]
@myfirenze please ask the question with the clangd language server. This repository only provides libs to create language server and it is up to the server to decide how it deals with file dependencies.
