### ISSUE TITLE
Don't show "request has failed" on rejected rename request

### ISSUE THREAD

**Issue by matklad** [microsoft/vscode-languageserver-node#730]
Problem: when the user tries to rename element which can't be renamed, VS Code shows both the inline error message from the server (expected behavior) as well as the "request has failed" internal error:

![rename](https://user-images.githubusercontent.com/1711539/104446356-60660780-55ab-11eb-8782-cde817b013df.png)

I think this is a problem with the prepare rename protocol. At the moment, the client can't really distinguish between "request failed because the element can't be renamed" and "request failed due to internal problem with the server". Only the second case should trigger the output dialog. 

Perhaps we need a special error code for the server to signify that the error is normal?

**Comment by matklad** [comment]
Thanks~

**Comment by MetalSlime0** [comment]
FYI I am still seeing this behavior on 1.69.1.

**Comment by dbaeumer** [comment]
The fix depends on the version of the LSP libraries but not on the version of VS Code.
