### ISSUE TITLE
[Feature Request] support snippet in WorkspaceEdits

### ISSUE THREAD

**Issue by heejaechang** [microsoft/vscode-languageserver-node#731]
currently, snippet (not the snippet feature but functionality) is only supported in completion (https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_completion). but the snippet functionality seems generally useful for any text edits.

for example, code action that creates an identifier which is referenced in multiple places (ex, extract method or generate method), snippet (${0:newMethod}) can be used to let users to change auto generated identifier name. (I know this particular example can be done through rename, but let's assume rename is not available for whatever reason)

it would be nice if we can get this functionality in any text edits.

**Comment by dbaeumer** [comment]
Dups https://github.com/microsoft/language-server-protocol/issues/592
