### ISSUE TITLE
disabling snippetSupport from client side

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode-languageserver-node#732]
Is there any way to adjust the `snippetSupport` client capability? 
The Go language server supports snippets but some users don't want them
because they don't like `()` included in the completion items.

I was told other editor plugins allow to control by adjusting the `snippetSupport` 
completion feature. Currently this is hard-coded here.

https://github.com/microsoft/vscode-languageserver-node/blob/296be84f9afea51e0878fed65ca2e4847ce0ce39/client/src/common/client.ts#L1521-L1533

Is there a way to change this configuration?

**Comment by dbaeumer** [comment]
No. This is a capability and not a setting. If that should be user controlled then the editor needs to provide a setting which the server can read using the `getConfiguration` request. Or the client provides a generic setting to filter them out. VS Code for example has settings to make snippets less prominent and sort them to the end of a completion list.

Does that make sense?

**Comment by hyangah** [comment]
Thanks @dbaeumer. That totally makes sense.

The question arose in the context of https://github.com/golang/go/issues/43903, where some users don't like the language server includes `()` or place holders in its completion items. But this is a capability, so I don't think this is the right knob to control that. Moreover, I am not sure if whether to include brackets should be controlled by snippets related settings.

I am curious how other language feature providers handle this problem (i.e. whether to include `()` in the function completion item). Is there a general vscode setting that the client should watch, or each language extension defines their own settings?

Thanks for the response, and I am fine with closing this issue.

**Comment by dbaeumer** [comment]
In VS Code every language defines its own setting. TS has one which to my knowledge fills in the whole signature.

**Comment by jwalton** [comment]
The setting for TypeScript, for reference is `typescript.suggest.completeFunctionCalls`.  It behaves like gopls with `ui.completion.usePlaceholders` turned on.  I don't think there's a typescript option to add ()s and not the full signature.

**Comment by dbaeumer** [comment]
@jwalton that is correct and is what I meant with 

> TS has one which to my knowledge fills in the whole signature

**Comment by hyangah** [comment]
Thank you so much @jwalton and @dbaeumer!
I wish there was a common flag used across all language extensions to control the level of info suggestions fill in. But that's beyond the scope of LSP client libraries.
I am closing this because all my questions were answered.
