### ISSUE TITLE
fail message for onPrepareRename

### ISSUE THREAD

**Issue by johnsoncodehk** [microsoft/vscode-languageserver-node#735]
currently I can return ResponseError to show rename fail message:

```ts
connection.onPrepareRename(handler => {
  return new ResponseError(0, 'fail by some reason');
});
```

<img width="246" alt="螢幕截圖 2021-02-02 下午1 17 30" src="https://user-images.githubusercontent.com/16279759/106555725-185a5500-6559-11eb-98c2-94a8be12d0e3.png">

but it well also display error message box:

<img width="431" alt="螢幕截圖 2021-02-02 下午1 19 32" src="https://user-images.githubusercontent.com/16279759/106555868-62dbd180-6559-11eb-923d-c87a42d04b00.png">

I think onPrepareRename should allow return fail message instead of ResponseError.

**Comment by dbaeumer** [comment]
This got already addressed in master https://github.com/microsoft/vscode-languageserver-node/blob/master/client/src/common/client.ts#L2319
