### ISSUE TITLE
Only indeterminate progress shown in VS Code

### ISSUE THREAD

**Issue by wiseman** [microsoft/vscode-languageserver-node#739]
Using VS Code Version: 1.53.0, vscode-languageserver 7.0.0, vscode-languageclient 7.0.0, when I use work done progress, I only see the indeterminate progress indication in VS Code even though I'm sending percentages.

Here's an example (my title is "Creating dialogue", message is "test1", percentage is 10):

![Screen Shot 2021-02-04 at 3 31 45 PM](https://user-images.githubusercontent.com/52466/106968695-31e8d180-66fe-11eb-993e-f5c8b1e8fb1a.png)

Is this expected, or am I doing something wrong?

**Comment by dbaeumer** [comment]
@wiseman this is expected in VS Code. You can click on the progress in the status bar and you get a dialog with a discrete progress.
