### ISSUE TITLE
Intercept client paths

### ISSUE THREAD

**Issue by nojaf** [microsoft/vscode-languageserver-node#746]
I'm trying to run my language server inside a docker container.
```js
    var _require = __webpack_require__(/*! child_process */ "child_process"),
        spawn = _require.spawn;

    return new Promise(function (resolve, reject) {
      var cp = spawn("docker", args);
      cp.stderr.on('data', function (data) {
        console.error("stderr: ".concat(data));
      });
      resolve({
        reader: cp.stdout,
        writer: cp.stdin
      });
    });
```

This works out but the host is on Windows and the language server is running inside Docker.
So I'm getting errors like:
```
stderr: [14:24:50.423 ERR] [LSP Server] HandleClientMessage - Error {"Code": -32601, "Message": "Method not found", "Data": null, "$type": "Error"} when handling notification {"Version": "2.0", "Method": "$/cancelRequest", "Params": {"Value": [[[]]], "$type": "Some"}, "$type": "Notification"}

c:\Users\nojaf\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js:5
stderr: [14:24:50.679 ERR] [LSP] PositionHandler - Getting file checker options for /workspace/c:\Users\nojaf\Projects\fantomas\src\Fantomas\RangeHelpers.fs failed
```

Notice: `/workspace/c:\Users\nojaf\Projects\fantomas\src\Fantomas\RangeHelpers.fs`
`/workspace` is the folder inside the container where the server is running.
`c:\Users\nojaf\Projects\fantomas\src\Fantomas\RangeHelpers.fs` is the client path.

Could I somehow intercept messages on the client before they go to the server to update the file path?

PS: Yes, I'm aware of [devcontainers](https://code.visualstudio.com/docs/remote/containers), that is not an option as I'm not running my extension in VSCode.
Please answer if file path interception is a thing here.

**Comment by dbaeumer** [comment]
LanguageClientOptions#uriConverters is your friend.

**Comment by nojaf** [comment]
@dbaeumer thank you for this pointer.
I noticed it is currently not used for the root path. Is that by design?
https://github.com/microsoft/vscode-languageserver-node/blob/7d7b7023941e3c6285987f10d3de5ef324695712/client/src/common/client.ts#L3188-L3190

**Comment by dbaeumer** [comment]
That is an oversight.

**Comment by dbaeumer** [comment]
My mistake. It is by design. The rootPath is a path not a URI. The rootURI goes through the transformer. See https://github.com/microsoft/vscode-languageserver-node/blob/master/client/src/common/client.ts#L3207
