### ISSUE TITLE
onNotification side effects cannot be tested

### ISSUE THREAD

**Issue by fiksen99** [microsoft/vscode-languageserver-node#747]
Consider a test framework where we want to enable easy integration/E2E testing of a language server.

The test spins up a mock client, with a json-rpc `MessageConnection` to send/receive messages to the server under test on.

The server has behaviour such that when it receives notifications, it begins executing code, including notifications/requests sent to the client. The notification from client to server could be `textDocument/didOpen` and the server reports back statuses for the client to display to the user as the text document opens.

We'd like to test that these callbacks will be received as expected, so we set up a jest test like so:

```
describe('my e2e test', () => {
  it('testOpenCallbacks', async() => {
    // test setup
    const languageServer = new LanguageServer();
        
    // set the input connection in LS as output connection in client, and vice versa.
    const mockedClient = new MockedLanguageClient(languageServer.input, languageServer.output);
    await mockedClient.onReady();
    
    let callbackCounter = 0;
    mockedClient.onNotification('foo', () => {callbackCounter++;});
    mockedClient.onRequest('bar', () => {callbackCounter++; return {});
    
    await mockedClient.sendRequest('initialize', mockInitParams);
    
    // test setup finished, now call the code to be tested, expect 1 notification and 1 requests to be sent to client.
    mockedClient.sendNotification('textDocument/didOpen', openParams);
    
    // await 1 second timeout gives enough time for async context to execute and callbacks to be hit
    // await new Promise(resolve => setTimeout(resolve, 1000))
    
    expect(callbackCounter).toBe(2);
  }
}
```

As implemented, the test fails, as the executing thread can never switch to the server side async context until after the test has failed and the test infra is being torn down.

Uncommenting the timeout code usually allows the test to succeed, as the context can switch, and usually all async code under test is executed in that time. Setting a timeout of e.g. 1 ms enables some server code to be executed before switching back to the test context, however it's hit or miss if all of my server code gets executed before the test completes.

Obviously we'd want to avoid arbitrary (And likely flaky) timeouts in our test code. 

Is it possible to extend the onNotification code to wait for some event before it can finish executing, or some other similar construct? This seems like a general challenge for extension authors building E2E tests for their extensions.

**Comment by dbaeumer** [comment]
This is a general problem of notifications since there is no way a client can now when a notification is delivered to the server. Even if  `sendNotification` would return a promise you can't ensure that when the promise resolves the server has received and processed the notification. 

This is why new things in LSP are usually requests and not notifications unless there is a strong reason for a notification (e.g. don't want to let the client wait for the result).

The only way I can see how this can work is to have the server run in test mode and for the example above sends a notification `textDocument/didOpen/processed`. The client can then await that notification.

I will close the issue since there is nothing the library can do about it due to the nature of notifications.

Please ping if you have an idea how to address this

**Comment by fiksen99** [comment]
> The only way I can see how this can work is to have the server run in test mode and for the example above sends a notification textDocument/didOpen/processed. The client can then await that notification.

I was attempting something similar to this. Unfortunately I can't see a clear way for the client to await on the event. I keep finding creative ways to get back to the fundamental problem of not being able to guarantee that the notification handler code has ever been consumed before my test proceeds (either with an expectation verification, or a request to be sent to the server). In my mind it comes back to a `while (!received) { await sleepAsync(someSmallTimeout) }` type of construct, to allow the context switch to occur and the other code to execute while the test blocks on it.

**Comment by dbaeumer** [comment]
Usually you would do the following:

- return a promise from the test method
- inside the promise wait for the confirmation notification to arrive using an onNotificationHandler.
- test your assertions
- resolve the promise.

**Comment by fiksen99** [comment]
Thanks so much @dbaeumer! This appears to be the pattern that unlocks the test for me. May be obvious to some, but this was evading me. The pattern below in my test code, and injecting a `textDocument/didOpen/processed` notification on the server side when the notification handler has completed is exactly what I needed.

```
      const emitter = new EventEmitter();

      client.onNotification("textDocument/didOpen/processed", () =>
      {
        emitter.emit("notificationProcessed");
      });

      client.sendNotification(
        testData.clientRequest.method,
        testData.clientRequest.params,
      );

      await new Promise((resolve) => {
        emitter.on("notificationProcessed", (_args) => {
          resolve();
        })
      });
  ```
