### ISSUE TITLE
Incorrect Content-Length for JSON RPC messages containing diagnostics

### ISSUE THREAD

**Issue by erictraut** [microsoft/vscode-languageserver-node#751]
A Pyright user reported this bug: https://github.com/microsoft/pyright/issues/1576

Pyright uses vscode-languageserver to provide all of its JSON RPC communication with the language server client, so if there is a problem with the Content-Length calculation, it is within the vscode-languageserver library.

**Comment by 540692039** [comment]
> @erictraut I commented on [microsoft/pyright#1576](https://github.com/microsoft/pyright/issues/1576). Lets continue the discussion there for now. Reason is that I never saw this and without steps to reproduce it is very hard to say why this fails.

any help for you ? [stylelint can't work](https://github.com/stylelint/vscode-stylelint/issues/145)

**Comment by erictraut** [comment]
I think we can close this one. There's good evidence that the problem was with the client, not the server.
