### ISSUE TITLE
CompletionItemKind for type attributes

### ISSUE THREAD

**Issue by asklar** [microsoft/vscode-languageserver-node#754]
It looks like CompletionItemKind is an enum of about 25 values representing different kinds of things in a language; I could not find a category for representing attributes on a type, e.g. many languages have something like:
```csharp
[MyAttribute]
class MyClass { }
```

What would be the recommended approach? is there a way to extend this enum?
Related: #480 
CC @dbaeumer

**Comment by dbaeumer** [comment]
The extension has to happen in the protocol and then needs to be implemented here. There is an item in the protocol for more kinds already.
