### ISSUE TITLE
SemanticTokensBuilder.buildEdits() returning incorrect deleteCount

### ISSUE THREAD

**Issue by isc-bsaviano** [microsoft/vscode-languageserver-node#758]
I'm working on an issue where the users of a language server that I'm the maintainer of see their semantic coloring go haywire when doing deletes. I've confirmed that if I modify my language server to provide full tokens for a document every time (it currently registers as a full and delta provider), the tokens are correct after a delete. However, when registering as a delta provider and using the SemanticTokensBuilder.buildEdits() function, I observe this behavior:

My document upon open contains this text:
```objectscript
Class User.short
{

/// desc
ClassMethod t()
{
    q 1
}

}
```

And these tokens:

```
[ 0, 0, 5, 4, 0 ]
[ 0, 6, 4, 5, 0 ]
[ 0, 4, 1, 5, 0 ]
[ 0, 1, 5, 5, 0 ]
[ 1, 0, 1, 8, 0 ]
[ 2, 0, 3, 7, 0 ]
[ 0, 4, 4, 7, 0 ]
[ 1, 0, 11, 4, 0 ]
[ 0, 12, 1, 11, 0 ]
[ 0, 1, 2, 8, 0 ]
[ 1, 0, 1, 8, 0 ]
[ 1, 4, 1, 60, 0 ]
[ 0, 2, 1, 51, 0 ]
[ 1, 0, 1, 8, 0 ]
[ 2, 0, 1, 8, 0 ]
```

If I delete the line `///  desc` (tokens 6 & 7), the result of `textDocument/semanticTokens/full/delta` is:

```
{
    "resultId": "1618608792098",
    "edits": [
        {
            "start": 27,
            "deleteCount": 9,
            "data": []
        }
    ]
}
```

and the expected result is:

```
{
    "resultId": "1618608792098",
    "edits": [
        {
            "start": 27,
            "deleteCount": 10,
            "data": []
        }
    ]
}
```

I'm using VSCode 1.55.2 and vscode-languageclient/server 7.0.0

Original issue: https://github.com/intersystems/language-server/issues/29

**Comment by dbaeumer** [comment]
@isc-bsaviano thanks for the report. Could you add the source code behind the tokens so that I can easier relate the tokens. Then I can create that programmatically and see why it fails. Thanks!

**Comment by isc-bsaviano** [comment]
Hi @dbaeumer, thanks for looking into this. `textDocument/semanticTokens/full` and `textDocument/semanticTokens/full/delta` both call function [`parseText()`](https://github.com/intersystems/language-server/blob/87fad7b5d59d36158ef5b687166a81f1f2acea50/server/src/sem.ts#L20): 

```typescript
export function parseText(text: string, moninfo: monikerinfo, builder: SemanticTokensBuilder) {

	//console.log('parseText: ' + moninfo.moniker + ':' + moninfo.monikeropt);

	const jsonform = parsedocument(moninfo.moniker,moninfo.monikeropt,text).compressedlinearray;
	if (parserlogcompressedresult) {
		logcompressedresult(jsonform);
	}

	let anyerrors = false;
	for (let lineno in jsonform) {
		const line = jsonform[lineno];
		for (let itemno in line) {
			const item = line[itemno];
			if (item.s === 0) {
				anyerrors = true;
			}
			const tokenmodifiers = (item.w === 0) ? [] : [WARNING];
			builder.push(+lineno, item.p, item.c, lookupattr(item.l,item.s), encodeTokenModifiers(tokenmodifiers));
		}
	}

	if (makeclsparsetree && !anyerrors && moninfo.moniker === 'CLS') {

		try {
			const ast = parseClassDocument(jsonform, text);
			console.log(ast);
		}
		catch (error) {
			console.log('error calling parseClassDocument: ' + error);
		}
	}
}
```

`parseText()` calls out to our proprietary C++ parsers to parse the document into an array of tokens of type `compresseditem[][]`, where each token has these properties:

```typescript
export type compresseditem = {
    'p': number, // offset within line
    'c': number, // count (length of source of this item)
    'l': number, // language index
    's': number, // coloring attribute index
    'w': number // 0=>no warning, 1=>warning
};
```

`parseText()` then pushes each one of the parser-generated tokens into the SemanticTokensBuilder. The only difference between our handlers for `textDocument/semanticTokens/full` and `textDocument/semanticTokens/full/delta` is that `textDocument/semanticTokens/full` just pushes the tokens into the builder, then calls `builder.build()` while `textDocument/semanticTokens/full/delta` first loads the previous result, then calls `builder.buildEdits()`. The source for `textDocument/semanticTokens/full` and `textDocument/semanticTokens/full/delta` can be found [here](https://github.com/intersystems/language-server/blob/87fad7b5d59d36158ef5b687166a81f1f2acea50/server/src/server.ts#L6235) and [here](https://github.com/intersystems/language-server/blob/87fad7b5d59d36158ef5b687166a81f1f2acea50/server/src/server.ts#L6272). Let me know if you need any more details.

**Comment by isc-bsaviano** [comment]
@dbaeumer Thanks for addressing this promptly! Do you know when a new "next" version of the modules will be released so I can pick them up in my LS?

**Comment by dbaeumer** [comment]
My plan is to ship a new next version beginning of May when the next version of VS Code has shipped.

**Comment by gjsjohnmurray** [comment]
@dbaeumer are you able to ship this soon?

**Comment by dbaeumer** [comment]
Sorry for that. I can make a next version beginning on next week.

**Comment by dbaeumer** [comment]
Release server@7.1.0-next.5 and client@7.1.0-next.5
