### ISSUE TITLE
Extensionless "typings" entries in package.json no longer work as of TypeScript 2.1.0-dev.20160820

### ISSUE THREAD

**Issue by rbuckton** [Microsoft/vscode-languageserver-node#76]
A [recent change](https://github.com/Microsoft/TypeScript/pull/9646) in TypeScript has caused a breaking change that affects the `vscode-languageserver`, `vscode-languageserver-types`, `vscode-languageclient` and `vscode-jsonrpc` packages. Specifically, extensions are now **required** in the `"typings"` field in package.json.  These packages all have something like the following in their package.json files:

```
"typings": "lib/main"
```

Due to this change, all of these references must instead now point to something like the following:

```
"typings": "lib/main.d.ts"
```

**Comment by mhegazy** [comment]
TS should not be breaking this scenario. @andy-ms can you take a look at the original change.

**Comment by rbuckton** [comment]
Fixed in #10480
