### ISSUE TITLE
Use Vs code as client 

### ISSUE THREAD

**Issue by SoilihBenSoilih** [microsoft/vscode-languageserver-node#763]
Hello guys,

Hope you are good !

I am developing an lsp server for a developing language named Typer with files with `.typer` extensions. I have used emacs so before for testing and my server works.I would like to use vs code as a client as well. I want to make a pipe connection. I start my server with the `typer-lsp-server` command. I tried this **https://vscode.readthedocs.io/en/latest/extensions/example-language-server/** but it doesn't want to work maybe because I'm doing it wrong. Can someone help me to solve this problem?

Thank you very much, best to you!

**Comment by dbaeumer** [comment]
In which language is the server implemented. If you re not using the vscode-languageserver libraries to implement a server in Node then the best way is to use a function as a server options (see https://github.com/microsoft/vscode-languageserver-node/blob/dbaeumer/workspacePull2/client/src/node/main.ts#L124) and start the process and the pipe setup yourself. If you are interested on how to do this you might want to have a look at TransportKind.pipe (https://github.com/microsoft/vscode-languageserver-node/blob/dbaeumer/workspacePull2/client/src/node/main.ts#L56) and how it is used together with a Node server.
