### ISSUE TITLE
Deviation from LSP 3.16 for prepareSupportDefaultBehavior 

### ISSUE THREAD

**Issue by swissiety** [microsoft/vscode-languageserver-node#767]
Hello,
while adapting JimpleLSP to use 3.16 features (i.e. semantic tokens) I updated to 7.0.0 and stumbled over a problem.
lsp4j complained "java.lang.IllegalStateException: Expected a boolean but was NUMBER at line 1 column 3218 path $.params.capabilities.textDocument.rename.prepareSupportDefaultBehavior".

**TLDR**
My guess is its caused by the following code lines which assign an **int** but according to [LSP 3.16 - Rename](https://microsoft.github.io/language-server-protocol/specification#textDocument_rename) a **boolean** is expected.

https://github.com/microsoft/vscode-languageserver-node/blob/532f81175ea3dfd241526841226becd0bdf318de/protocol/src/common/protocol.ts#L3001

**Comment by dbaeumer** [comment]
@swissiety `prepareSupport` is speced as a boolean and sent as a `boolean`. The `prepareSupportDefaultBehavior` is a speced as a number enum and is sent as such.

See https://github.com/microsoft/vscode-languageserver-node/blob/main/client/src/common/client.ts#L2321

Anything I am missing?

**Comment by swissiety** [comment]
@dbaeumer thanks for the clarification! Makes sense to me now - so its a deviation/bug in lsp4j - sorry for the inconvenience.
