### ISSUE TITLE
TextDocument.positionAt(...) calculcates wrong target position.

### ISSUE THREAD

**Issue by triforcely** [microsoft/vscode-languageserver-node#774]
Hi,

I think positionAt function is not working correctly, I first noticed it while working on a bug in Vetur extension but I also could reproduce it on a small project that just depends on 'vscode-languageserver-textdocument' package.

positionAt function returns wrong position in file, following screenshot shows the reproduction of this issue:
![image](https://user-images.githubusercontent.com/12202969/121740691-c4aada00-cafd-11eb-9f00-3f035bda850c.png)
Hand calculated position of 792 offset should point to the start of '@Emit' decorator. I can verify it by splicing string file content (moving x character forward). Function returns position 262/2, for testing I moved my cursor to this position and verified with the position display in right bottom corner of VS Code that in fact this position is incorrect.

You can find code samples and the file that I was testing with in the spoiler below

<details>
  <summary>Repro</summary>
 
  
  ```typescript
import { TextDocument } from "vscode-languageserver-textdocument";

import * as fs from "fs";
(() => {

    const fileContent = fs.readFileSync("./src/Samplefile.vue").toString();
    const document = TextDocument.create("file://test.ts", "ts", 1, fileContent);


    const textAfterCursor = fileContent.slice(792);
    const calculatedLocation =  document.positionAt(792);

    debugger;

})()
  ```

```vue
<template>
  <div>
    <p v-if="true" @click="onHelloClick">{{ helloMessage }}</p>
    <AnotherComponent2 @helloClick="() => null" :helloMessage="'test'" />
    <another-component @hello-click="() => null" :hello-message="'test'" />
  </div>
</template>

<script lang="ts">
import { Component, Vue, Prop, Emit } from "vue-property-decorator";
import AnotherComponent from './AnotherComponent.vue';


@Component({
  components: {
    AnotherComponent2: AnotherComponent,
    AnotherComponent
  }
})
export default class HelloWorld extends Vue {
  @Prop({default: "hi"}) public helloMessage!: string;
  // @Prop() public disable!: string;
  // @Prop() public get!: string;
  // @Prop() public helpText!: string;

  /** Event emitted when hello text is clicked 🐇 */
  @Emit("helloClick")
  public async onHelloClick(e: MouseEvent) {
    return {} as Generic<Promise<number>>;
  }
}

interface Generic<T> {
  prop?: T;
}
</script>

```
  
</details>

**Comment by rcjsuen** [comment]
@triforcely I'm not sure I understand what the issue is. The `line` in `Position` is zero-based whereas the line numbers in the VS Code editor margin's are one-based. So your `@Emit` in line 27 is correctly line 26 in `Position`.

**Comment by triforcely** [comment]
@rcjsuen Hmm, maybe this repro is bad. I've definitely experienced a very strange desync of offset and calculated position, especially with large files. I'll try to find better example.

**Comment by triforcely** [comment]
I did some more debugging and I found out that I was calling "positionAt" on the wrong TextDocument instance 🙈. Sorry for the trouble, I'm closing the issue since it is working correctly after all.
