### ISSUE TITLE
is there an equivalent of vscode.workspace.textDocuments ?

### ISSUE THREAD

**Issue by ganezdragon** [microsoft/vscode-languageserver-node#777]
hi all,

I'm trying to get all my currently opened files using `vscode-languageserver/node` 's connection object. But there is no equivalent of `vscode.workspace.textDocuments` that I could find.

I didn't want to use the `vscode` as a dependency, since i want to be able to port my server to other text editors properly.
So it there any equivalent at all? or any work around?

my repo - https://github.com/ganezdragon/perl-language-server

Thanks,
Ganesan

**Comment by rcjsuen** [comment]
@ganezdragon Seems like your question may be more suited for the [microsoft/language-server-protocol repository](https://github.com/microsoft/language-server-protocol/) if you're wondering what is possible in LSP.

As to your question, no, there is no request that the server can send to ask the clients for a list of the currently opened editors. Typically, servers listen to `textDocument/didOpen` notifications and record this information in its own internal cache.

**Comment by ganezdragon** [comment]
okay got it.. let me close this issue then.

Thank you @rcjsuen

**Comment by ganezdragon** [comment]
@rcjsuen , this is related to https://github.com/microsoft/language-server-protocol/issues/1301,

So I could get answers here?

**Comment by rcjsuen** [comment]
https://github.com/microsoft/vscode-languageserver-node/blob/d58c00bbf8837b9fd0144924db5e7b1c543d839e/textDocument/src/main.ts#L344-L351

@ganezdragon Add some breakpoints here and see what's going on. Looks like you don't have a `FullTextDocument`.

**Comment by ganezdragon** [comment]
@rcjsuen , oh okay let me test this out and get back!

**Comment by dbaeumer** [comment]
The problem is a missing document manager that is not setup by default for the node server to give servers the change to implement their own.

See https://github.com/microsoft/vscode-extension-samples/blob/main/lsp-sample/server/src/server.ts#L29 how to setup a document manager. Note that the manager can work with full documents and incremental sync.
