### ISSUE TITLE
Help: need a simple example of showing how to use the progress feature

### ISSUE THREAD

**Issue by xg-github-00** [microsoft/vscode-languageserver-node#783]
In the server side, it contains searching files，parsing and indexing，and the three steps will cost some time, and I will caculate the progress and want the client to show the progress in the status bar.
I use it like this:
in client side:
In clientoptions, I set 'progressOnInitialization: true'
In server side:
I use the code from the testbed:
	 connection.window.createWorkDoneProgress().then((progress) => {
	 	progress.begin('Validating', 0, 'happy coding', true);
	 	let counter = 1;
	 	let interval = setInterval(() => {
	 		if (counter === 11) {
				clearInterval(interval);
				progress.done();
	 		} else {
				progress.report(counter++ * 10);
	 		}
	 	}, 1000);
	 	progress.token.onCancellationRequested(() => {
	 		progress.done();
			clearInterval(interval);
	 	});
	 });

the status bar only shows:    Validating: happy coding, but the percentage is not shown
please help to check, thanks~

**Comment by xg-github-00** [comment]
In the server side, it contains searching files，parsing and indexing，and the three steps will cost some time, and I will caculate the progress and want the client to show the progress in the status bar.
I use it like this:
in client side:
In clientoptions, I set 'progressOnInitialization: true'
In server side:
this.parseProgress.type = new langserver_1.ProgressType(); --in the construct function
conn.sendProgress(this.parseProgress.type, "parse", percent.toFixed(2)) ---report parse progess
and I'm not sure it it right or not. and also I need to report search progress and index progress.
please help to check, thanks~

**Comment by dbaeumer** [comment]
When you use `progressOnInitialization` then the server will receive a progress token in the intialize method you can use. See https://github.com/microsoft/vscode-languageserver-node/blob/main/testbed/server/src/server.ts#L109
