### ISSUE TITLE
How many Command and CodeAction?

### ISSUE THREAD

**Issue by YeomanYe** [microsoft/vscode-languageserver-node#788]
Thank you very much for providing this tool, it is very useful for me.But I have some doubts about this tool.How many `Command` and `CodeAction` are used in VS Code and what are they.I can only find convert in the code, but I can't find where to use it.

![image](https://user-images.githubusercontent.com/18027354/125300388-8bfc5b80-e35c-11eb-9cbe-1a6d2e5fe8c8.png)

![image](https://user-images.githubusercontent.com/18027354/125299611-e2b56580-e35b-11eb-9f14-d469bce0fd32.png)

**Comment by rcjsuen** [comment]
@YeomanYe You can find a list of commands [here](https://code.visualstudio.com/api/references/commands) though it's not clear to me how you intend to use this information.

**Comment by YeomanYe** [comment]
Thank you very much. We want to implement a map editor. In the communication section, we think that language-server-protocol is very valuable for reference, so we will learn the details of language-server-protocol implementation

**Comment by dbaeumer** [comment]
I will close the issue. Please ping if something is still unclear.
