### ISSUE TITLE
Add wordWrapColumn to formatting request options

### ISSUE THREAD

**Issue by johnsoncodehk** [microsoft/vscode-languageserver-node#789]
Related: https://github.com/johnsoncodehk/volar/issues/321

Formatting option `wordWrapColumn` can be deduced by VSCode's `editor.wordWrap` and `editor.wordWrapColumn` settings, in particular `editor.wordWrap` is `on` or `bounded`, `wordWrapColumn` need to compute viewport width, language server can't easily get it.

**Comment by rcjsuen** [comment]
@johnsoncodehk It seems like you are asking for changes to be made to `FormattingOptions`. I suggest you raise an issue in the [microsoft/language-server-protocol repository](https://github.com/microsoft/language-server-protocol/) to get some input from the community.

**Comment by johnsoncodehk** [comment]
Sure, thanks for the suggestion!
