### ISSUE TITLE
Intercept server responses

### ISSUE THREAD

**Issue by phil294** [microsoft/vscode-languageserver-node#790]
For example, for `completionItem`, we can specify a middleware using

https://github.com/microsoft/vscode-languageserver-node/blob/0cb3812e7d540ef3a904e96df795bc37a21de9b0/client/src/common/client.ts#L492

but this only goes for outgoing requests. What if I wanted to alter the response by the server?

Is there some documentation available I missed? As far as I can tell, not even usage the outgoing middleware is mentoined anywhere.

Use case:
There are many languages which compile to JavaScript, but only very few of them have IntelliSense support via VSCode extension or elsewhere. I would like to develop a basic LSP proxy-like extension for some of these that transpiles the source to JS, asks tsserver for diagnostics etc., and remaps server responses using source maps back to the original language, before handing it over to vscode. This should enable about half of LSP features for several languages in a relatively straightforward way. It looks like this is impossible with this library, however. Any way to reasonably handle this or am I forced to make a fork of this repo? – Sure, I could instead also fork tsserver or build a standalone proxy server from scratch without vscode-languageserver-node, but that would be a *lot* more hassle. Hope I'm not misunderstanding the whole thing. Thanks!

**Comment by rcjsuen** [comment]
@phil294 Not sure I understand. You should be able to use the middleware to alter the response before the VS Code client gets it back. Do you have some sample code that shows how middleware is not satisfying your use case?

**Comment by phil294** [comment]
> You should be able to use the middleware to alter the response before the VS Code client gets it back

I should? Sorry, I cannot see how that would be possible. Sample code:

```ts
let clientOptions: LanguageClientOptions = {
	documentSelector: [{ scheme: 'file', language: 'plaintext' }],
	middleware: {
		async provideCompletionItem(document: TextDocument, position: Position, context: CompletionContext, token: CancellationToken, next: ProvideCompletionItemsSignature) {
			// 1. Alter outgoing request: Possible
			const alteredPosition = new Position(42, position.character);
			// 2. Request is being sent
			const result = await next(document, position, context, token);
			// 3. Alter incoming response: Not possible!
			return result;
		}
	},
};
client = new LanguageClient('...', '...', serverOptions, clientOptions);
```
Awaiting `result` does not provide you with anything, it is undefined. Maybe I am missing something but I was expecting there to be a `provideCompletionItemResponse` middleware method.

**Comment by rcjsuen** [comment]
@phil294 Thank you for sharing your code. For me, the `await next(document, position, context, token)` functions correctly and I got an array of items and not `undefined` like you.

![image](https://user-images.githubusercontent.com/15629116/127138399-a36193a3-a290-48d8-81f7-750b504bef7b.png)

**Comment by phil294** [comment]
Thanks @rcjsuen! You are right, it works. The requests were actually eaten up by the server >.> Sorry!
