### ISSUE TITLE
Executable doesn't handle TransportKind

### ISSUE THREAD

**Issue by davidmatson** [microsoft/vscode-languageserver-node#791]
Currently, the code always launches an EXE without any command-line parameters. If a Transport is specified in the server options, it is entirely ignored. For example:

```typescript
import * as vscode from 'vscode';
import { LanguageClient, LanguageClientOptions, ServerOptions, TransportKind } from 'vscode-languageclient/node';
import * as path from 'path';

export function activate(context: vscode.ExtensionContext) {
  let serverOptions: ServerOptions = {
    command: path.join(__dirname, 'TestLanguageServer.exe'),
    transport: TransportKind.pipe // or TransportKind.socket
  }

  let clientOptions: LanguageClientOptions =
  {
    documentSelector: [{ scheme: 'file', language: 'testfiletype' }],
    synchronize: {
      fileEvents: vscode.workspace.createFileSystemWatcher('**/testfilename')
    }
  }

  const client = new LanguageClient('testLanguageServer', 'Test Language Server', serverOptions, clientOptions);

  let disposable = client.start();

  context.subscriptions.push(disposable);
}

export function deactivate() { }

```

Is the same as if the ```transport:``` line was not specified.

The [specification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#implementationConsiderations) lists how to pass these, and they are implemented for Node module, just not for Executable.

It looks like a previous issue was filed (#197) and we thought it was fixed, but that does not appear to be the case.

See:
https://github.com/microsoft/vscode-languageserver-node/blob/0cb3812e7d540ef3a904e96df795bc37a21de9b0/client/src/node/main.ts#L431-L435
(for Executable)

vs:
https://github.com/microsoft/vscode-languageserver-node/blob/0cb3812e7d540ef3a904e96df795bc37a21de9b0/client/src/node/main.ts#L378-L387
(for Node module)

**Comment by dbaeumer** [comment]
This might got broken again when I did the split common, browser and node.

**Comment by dbaeumer** [comment]
Fixed it. @davidmatson would be cool if you could give it a try. Published client@8.0.0-next.2

**Comment by davidmatson** [comment]
@dbaeumer - yes, that worked. Thanks!

David

**Comment by davidmatson** [comment]
@dbaeumer - when is this change likely to appear in a non-prerelease version?

**Comment by dbaeumer** [comment]
@davidmatson when we ship the 3.17 version of the LSP protocol which is very likely still a couple of month out.
