### ISSUE TITLE
support smart indentation in LSP

### ISSUE THREAD

**Issue by heejaechang** [microsoft/vscode-languageserver-node#792]
can smart indenting capability added to LSP? I know that there is a concern on perf, but if LS chooses to take that perf hit for better indentation on vertical cursor move or enter, I think LSP should allow LS to do so.

many complex indentation requires parse tree and can't be done using regex alone. so, it feels like it should be LS's decision to take the perf hit or not.

with smart cancellation, (no cancel if "enter" + key typed, but cancel previous smart indentation request if cursor moved vertically and etc), a lot of perf concern, I feel like, can be mitigated.

thank you.

ex) 
```
method( { 1: 'apple', 
                  * align caret to "1" on "arrow down"
```

PS: is the reason this is not supported due to vscode doesn't support such indentation?

**Comment by rcjsuen** [comment]
> can smart indenting capability added to LSP?

@heejaechang I think you want the [microsoft/language-server-protocol repository](https://github.com/microsoft/language-server-protocol/).

**Comment by heejaechang** [comment]
@rcjsuen thank you.
