### ISSUE TITLE
Make server startup cli arg `--clientProcessId` optional

### ISSUE THREAD

**Issue by phil294** [microsoft/vscode-languageserver-node#794]
It seems that `--clientProcessId=...` is hard-coded in two places: [here](https://github.com/microsoft/vscode-languageserver-node/blob/main/client/src/node/main.ts#L333) and [here](https://github.com/microsoft/vscode-languageserver-node/blob/main/client/src/node/main.ts#L388). But this option [does not seem to be part of the specification](https://microsoft.github.io/language-server-protocol/specification#implementationConsiderations), so shouldn't it be optional?

When you start [theia-ide/typescript-language-server](https://github.com/theia-ide/typescript-language-server) with vscode-lsp-node
```ts
let server_module = context.asAbsolutePath(path.join('node_modules', '.bin', 'typescript-language-server'))
```
the server startup fails as the server does not recognize this option.

In Go on the other hand, [theia-ide/go-language-server added this option two years ago](https://github.com/theia-ide/go-language-server/commit/efa486bc607cc80540fb3910f3f1e45058faff5), presumably to establish compability with vscode.

**Comment by dbaeumer** [comment]
Instead of removing it I would opt to document it. The reason is that not having the arg will make it hard for servers to do cleanup work when the editor crashes.

**Comment by dbaeumer** [comment]
Another reason why this should be documented is the fact that the process id is already part of the protocol in the initialization params.

**Comment by dbaeumer** [comment]
Done for `3.17` version of the spec.
