### ISSUE TITLE
Latest FormattingOptions not passed to server

### ISSUE THREAD

**Issue by davidmatson** [microsoft/vscode-languageserver-node#795]
I'm not sure if this is an issue with LanguageClient or VS Code itself. I can't get VS Code + LanuageClient to pass any of the newer [FormattingOptions](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#formattingOptions) to the server, even when using .editorconfig (and the extension for it).

The specific options missing are:
```typescript
/**
* Trim trailing whitespace on a line.
*
* @since 3.15.0
*/
trimTrailingWhitespace?: boolean;

/**
* Insert a newline character at the end of the file if one does not exist.
*
* @since 3.15.0
*/
insertFinalNewline?: boolean;

/**
* Trim all newlines after the final newline at the end of the file.
*
* @since 3.15.0
*/
trimFinalNewlines?: boolean;
```

**Comment by rcjsuen** [comment]
@daviddossett This is working for me. I have `"files.trimFinalNewlines": true` in my `settings.json` file and then invoked a formatting request. My language server got `trimFinalNewlines: true` included as an option.

I am using `vscode-languageclient` 7.0.0 and my VS Code is 1.58.2.

**Comment by davidmatson** [comment]
@rcjsuen - thanks! yes, all of the following items in ```settings.json``` work for me (get passed along to the language server):
```json
  "files.trimFinalNewlines": true,
  "files.trimTrailingWhitespace": true,
  "files.insertFinalNewline": true
```

However, if I use the following .editorconfig file (with its extension installed):
```ini
root = true

[*]
indent_style = tab
indent_size = 5
trim_trailing_whitespace = true
insert_final_newline = true
```

It only includes the following options in the request:
```json
    "options": {
        "tabSize": 5,
        "insertSpaces": false
    }
```

Is that a bug in .editorconfig, or a limitation in VS Code or the LanguageClient? I'm guessing this isn't the right repo for that problem, but if you could direct to the correct one, that would be appreciated. Thanks!

**Comment by 14JeffMcc** [comment]
from: PC owner. sO, as i continue to document every conributor, the retail store who put this software on my home computer inappropriately, et cetera, I just wonder, do ya'll know that this is hacking, black hat, illegal hacking. /I'm an adult who just was tricked by a family member so they could micro/ macro spyware && malware snoop into my PC just being nosey, this that ya'll r doing is tearing a family apart. do you guys feel good a/b destroying a $$1k desktop pc that's six months old, creating irrepreble damage in a father son relationship as the dad has blood cancer, anaplastic, non-Hodgkin's lymphoma [the Round Up cancer u hear a/b on tv. thanks. thanks or ruining the last time w/ my step father who raised me as his own. He JUST lost a son in his mid forties. this thing here...it's disgusting!

**Comment by rcjsuen** [comment]
> Is that a bug in .editorconfig, or a limitation in VS Code or the LanguageClient? I'm guessing this isn't the right repo for that problem, but if you could direct to the correct one, that would be appreciated. Thanks!

Could be both. It's not clear how your extension "intercepts" or "hijacks" formatting requests. I would start with consulting the developers of the extension to see how this is done.

**Comment by dbaeumer** [comment]
A good way to determine whether this is LSP or VS Code or the extension is to write a normal non LSP based extension and see if you get the formatting options. If not it points to the extension or VS Code itself.

Let me know how it goes.

**Comment by davidmatson** [comment]
Good idea. I tested, and it's not the LSP.

```typescript
import * as vscode from 'vscode';

function provideDocumentFormattingEdits(document: vscode.TextDocument, options: vscode.FormattingOptions, token: vscode.CancellationToken): vscode.TextEdit[] {
  return [vscode.TextEdit.insert(document.lineAt(0).range.start, 'foo\n')];
}

export function activate(context: vscode.ExtensionContext) {
  context.subscriptions.push(vscode.languages.registerDocumentFormattingEditProvider(
    { scheme: 'file', language: 'test.language' }, { provideDocumentFormattingEdits: provideDocumentFormattingEdits }));
}

export function deactivate() { }
```

(in the debugger, with the .editorconfig file above, options shows only tabSize and insertSpaces.)

So it must be either VS Code or the extension.

Thanks for your help.
