### ISSUE TITLE
Extension Activates and communicates with LS but no hover/autocompletion is displayed.

### ISSUE THREAD

**Issue by shadycuz** [microsoft/vscode-languageserver-node#803]
I'm looking for help for a user of my extension. https://github.com/DontShaveTheYak/groovy-guru/issues/20 

This is the first issue I have for my extension where it just doesn't work. The extension is being activated. The LS is running and the client is communicating with the LS. But for some reason, nothing is being displayed in the code editing window. 

I'm not really sure what to do next from a debugging perspective.

**Comment by dbaeumer** [comment]
You can ask the user to enable tracing. Usually the LSP client has a hidding setting `${language server id / name}.trace.server`. Set the setting to `"verbose"`. A trace should show up in the corresponding output channel.

**Comment by shadycuz** [comment]
User never replied but it has been very helpful for debugging other issues. Thanks
