### ISSUE TITLE
use in nodejs environment

### ISSUE THREAD

**Issue by link89** [microsoft/vscode-languageserver-node#804]
Hi, I want to use the lsp server & client in the nodejs environment for some semantics analysis tasks. I was redirected to here from this document https://microsoft.github.io/language-server-protocol/implementors/sdks/ .

I find that if I use the `vscode-languageclient` it will throw error `Cannot find module 'vscode'` under the nodejs environment.  I can use the `vscode-jsonrpc` to communicate with lsp server but I am not sure if it is the best choice. So my question is what's the recommended way to use the lsp client under nodejs environment? Thank you!

**Comment by rcjsuen** [comment]
@link89 I'm not totally sure what you are trying to do. Which of the following applies to you?

1. you are writing a language server to provide features for an editor
2. you are creating a editor client and you want to hook connect language servers to your editor
3. something else?

**Comment by link89** [comment]
It's something else, it has nothing todo with editor or IDE. I just want to get result from LSP server get information like "find all functions/class in a file" for further process.

**Comment by rcjsuen** [comment]
> It's something else, it has nothing todo with editor or IDE. I just want to get result from LSP server get information like "find all functions/class in a file" for further process.

OK, well, in that case I would still consider you a client since you are asking the language server questions. Yeah, I'm not sure how far you'll get using `vscode-languageclient` given that it has dependencies on `vscode`.

You should be able to achieve what you want with `vscode-jsonrpc` or just write your own "client" that sends and receives JSON-RPC messages to and from the server. I have some examples in my [language server's `README.md` file](https://github.com/rcjsuen/dockerfile-language-server-nodejs/blob/0389e333b013c69f8f5d1b548876c5601751d69b/README.md) that may help.

**Comment by link89** [comment]
Here is my test inspired by https://github.com/microsoft/vscode-languageserver-node/blob/main/client-node-tests/src/integration.test.ts

```typescript
import * as lsclient from 'vscode-languageclient/node'
test('test vscode-languageclient', async t => {

  const middleware = {};
  const documentSelector: lsclient.DocumentSelector = [{ scheme: 'lsptests', language: 'typescript' }];
  const serverOption: lsclient.ServerOptions =  async () => cp.spawn('typescript-language-server', ['--stdio']);
  const clientOptions: lsclient.LanguageClientOptions = {
    documentSelector, synchronize: {}, initializationOptions: {}, middleware
  };

  const client = new lsclient.LanguageClient('test svr', 'Test Language Server', serverOption, clientOptions);
  client.registerProposedFeatures();
  client.start();
  await client.onReady();
})
```
It will throw `  Error: Cannot find module 'vscode'` because it is required in the `vscode-languageclient/lib/node/main.js`

**Comment by rcjsuen** [comment]
> It will throw ` Error: Cannot find module 'vscode'` because it is required in the `vscode-languageclient/lib/node/main.js`

Yeah, that's not going to work as aforementioned. You could try subclassing `CommonLanguageClient` or `BaseLanguageClient` instead maybe but I expect those will likely fail also.

**Comment by dbaeumer** [comment]
I will close the issue. Please ping if you need further help.
