### ISSUE TITLE
Investigate if we can transfer objects in Web without serialization

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-languageserver-node#807]
See https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage `transfer` argument

**Comment by jrieken** [comment]
fyi @dbaeumer - I have experimented with this in anycode: https://github.com/microsoft/vscode-anycode/commit/16e53ec04893d4416693418db9985603d1ad1d19. The change is quite simple more or less a special message type that can be used to mark transferable data. I see a 10 to 20% speed-up when send file replies

**Comment by dbaeumer** [comment]
Cool. I will have a look!

**Comment by jrieken** [comment]
Nevermind - my commit wasn't actually doing it... This needs further work and I have undone my changes for now

**Comment by dbaeumer** [comment]
Reading through the specification I think the only thing we can look into is the following: serialize the JSON RPC data into a uint array and then transfer the array instead of a string. To my understanding the string is really sent where the array would stay in memory.

**Comment by dbaeumer** [comment]
I read through the spec again and there is only a limited number of object types that can be transferred. For LSP this would mean that we need to invent our own binary format (we could use wit) and transfer the data in arrays. Given that JSON is highly optimized I am not sure that we gain a lot here. I will close this for now. Please ping if I have overlooked something.
