### ISSUE TITLE
"arguments" as key in an object within an arrow function is reported as error

### ISSUE THREAD

**Issue by stagefright5** [microsoft/vscode-languageserver-node#810]
Steps:

1. Create a .js file
2. Paste this below code:
```javascript
const a = () => {
    const conf = {
        arguments: [],
    };
};
```
3. This error is reported:
![image](https://user-images.githubusercontent.com/15051871/132494061-7d421ead-2c16-4dcc-ae25-377aef24904c.png)

Additional Info:

- jsconfig.json:
```jsonc
{
	"compilerOptions": {
		"target": "ES6",
		"moduleResolution": "node",
		"checkJs": true,
		"strictBindCallApply": true,
		"strictFunctionTypes": true,
		// "strict": true,
		"resolveJsonModule": true,
		"noImplicitAny": false,
		"lib": [
			"es2020"
		]
	}
}

```

**Comment by rcjsuen** [comment]
@stagefright5 Did you mean to open this in the [microsoft/vscode repository](https://github.com/microsoft/vscode) instead?

**Comment by stagefright5** [comment]
Isn't this the repo responsible for implementing LSP for TS/JS analysis?

**Comment by rcjsuen** [comment]
> Isn't this the repo responsible for implementing LSP for TS/JS analysis?

@stagefright5 No, it is not. Think of it more as a library to use the LSP. No LSP server implementations exist in this repository.

**Comment by stagefright5** [comment]
Okay then, we can move it to the correct repo.

**Comment by stagefright5** [comment]
Raised here: https://github.com/microsoft/vscode/issues/132731

Closing this.
