### ISSUE TITLE
Passing TextDocumentSyncOptions object instead of a TextDocumentSyncKind to textDocumentSync: causes errors

### ISSUE THREAD

**Issue by thomasballinger** [microsoft/vscode-languageserver-node#813]
Using an object for the textDocumentSync property in the InitializeResult capabilities object causes errors on notification that look like `Notification handler 'textDocument/didChange' failed with message: TextDocument.update: document must be created by TextDocument.create`

---

Check out https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-sample, npm install, and change [line 54](https://github.com/microsoft/vscode-extension-samples/blob/4bad174eb8cadc75cda4c5ffe359bb634d19b7fc/lsp-sample/server/src/server.ts#L54) in lspsample/server/src/server.ts from
```
textDocumentSync: TextDocumentSyncKind.Incremental,
```
to 
```
textDocumentSync: {
    change: TextDocumentSyncKind.Incremental,
    save: true
},
```
The types suggest this should work, but after this change updates fail with

`Notification handler 'textDocument/didChange' failed with message: TextDocument.update: document must be created by TextDocument.create`

**Comment by rcjsuen** [comment]
@thomasballinger What a strange bug you have uncovered! Please use the workaround below to fix the issue. Note the addition of `openClose: true` in the options.
```Diff
diff --git a/lsp-sample/server/src/server.ts b/lsp-sample/server/src/server.ts
index afd81c3..82527d8 100644
--- a/lsp-sample/server/src/server.ts
+++ b/lsp-sample/server/src/server.ts
@@ -51,7 +51,11 @@ connection.onInitialize((params: InitializeParams) => {
 
 	const result: InitializeResult = {
 		capabilities: {
-			textDocumentSync: TextDocumentSyncKind.Incremental,
+			textDocumentSync: {
+				change: TextDocumentSyncKind.Incremental,
+				openClose: true,
+				save: true,
+			},
 			// Tell the client that this server supports code completion.
 			completionProvider: {
 				resolveProvider: true
```

**Comment by dbaeumer** [comment]
Actually this is expected. The protocol allows that the client send change event without open / close events. However the text document manager needs these. I will add a comment to text documents to make this clear.
