### ISSUE TITLE
DocumentLink#tooltip is not implemented correctly

### ISSUE THREAD

**Issue by AkatQuas** [microsoft/vscode-languageserver-node#815]
> Related issue #523 .

As the function [`DocumentLink#create`](https://github.com/microsoft/vscode-languageserver-node/blob/main/types/src/main.ts#L3157-L3159) shows, the `tooltip` is not required in the function.

However, there's no modification methods for `tooltip` else.

So maybe the usage is something like ?

```javascript
const documentLink = DocumentLink.create(range, target, data);
documentLink.tooltip = 'My tooltip';
```

**Comment by dbaeumer** [comment]
Yes this is correct and your example is the expected usage.
