### ISSUE TITLE
How to get stderr output of a language server?

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode-languageserver-node#82]
@dbaeumer 
I justed implemented my language server and did not find a way to get the stack trace or logs it outputs on stderr when it crashes.

**Comment by dbaeumer** [comment]
Thanks to @sqs this will be available in the next release.

What you can do in the meantime is the following:

```ts
        // Use a function as the server Options
	let serverOptions = (): Thenable<any> => {
                // Start the server using child_process.spawn(...);
                // Hook the childProcess.stderr.on('data', data => ...)); 	}
```

Hope that helps.

Since we have https://github.com/Microsoft/vscode-languageserver-node/pull/83 I will close this.

**Comment by felixfbecker** [comment]
Thanks for the help!
