### ISSUE TITLE
Include information about document change in `TextDocumentChangeEvent`

### ISSUE THREAD

**Issue by esSteres** [microsoft/vscode-languageserver-node#820]
Currently, `TextDocumentChangeEvent` only includes the document that was changed, and no information about how it was changed. #473 mentions this, but at the time the document manager was unable to handle incremental updates, so it was impossible to offer this feature. It seems (based on a cursory look at the code) as though that is no longer the case - the `TextDocuments` class seems to handle incremental updates fine - but the event still includes only the document that was changed. I would appreciate being able to take advantage of the text document manager, but I really need the ability to know where the document was modified to optimize certain features. Is it possible now to include the places that were altered (perhaps by simply passing through the list of `TextDocumentContentChangeEvent`?)

**Comment by dbaeumer** [comment]
This exist. If only the text is send it is a full change. See also https://github.com/microsoft/vscode-languageserver-node/blob/7dda0910ac433e5e2976b42e7aaae89db796dbcb/textDocument/src/main.ts#L309-L309

**Comment by esSteres** [comment]
I think I didn't communicate well enough. I'm not looking for support for incremental updates; I am aware that the document manager currently supports that. Rather, I am proposing that the event passed to the callback for `documents.onDidChangeContent` includes information about the content change, if possible.

The key here is the distinction between `TextDocumentChangeEvent` - which is created by the document manager - and `TextDocumentContentChangeEvent` - which comes from the LSP client.

**Comment by dbaeumer** [comment]
If you want the raw events you can always listening to them on the connection and manage the text documents yourself. There is no need to use TextDocuments. You can still use the text documents npm module to create a corresponding full text document instance.

**Comment by esSteres** [comment]
It's not a matter of needing the raw events - just the information on where the content change occurred. I am fully aware that I can manage the documents myself, but that seems excessive when all I need is the range in which the edit occurred. What I am proposing is that the `TextDocumentChangeEvent` contain the details of the edit that triggered it.
