### ISSUE TITLE
Confusion over deprecated TextDocument

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode-languageserver-node#823]
HI there, im (trying to) maintain [TypeScript-styled-plugin](https://github.com/microsoft/typescript-styled-plugin) ive noticed there's a deprecation notice on TextDocument in `vscode-languageserver-types` .

It sells us to "Use the text document from the new vscode-languageserver-textdocument package" instead. but looking at that package it seems dead also: https://www.npmjs.com/package/vscode-languageserver-textdocument (no release for 2 years)
What should we be using here?
Screenshot:
![image](https://user-images.githubusercontent.com/936006/135724121-205ed24d-511a-4801-b37e-26677f07a2d5.png)

"vscode-languageserver-types": "^3.16.0"

**Comment by rcjsuen** [comment]
> HI there, im (trying to) maintain [TypeScript-styled-plugin](https://github.com/microsoft/typescript-styled-plugin) ive noticed there's a deprecation notice on TextDocument in `vscode-languageserver-types` .
> 
> It sells us to "Use the text document from the new vscode-languageserver-textdocument package" instead. but looking at that package it seems dead also: https://www.npmjs.com/package/vscode-languageserver-textdocument (no release for 2 years) What should we be using here?

You should be using `vscode-languageserver-textdocument`. It's a pretty simple library so it has not seen any changes but it is what you should be using.

**Comment by dbaeumer** [comment]
@rcjsuen is correct.
