### ISSUE TITLE
Show message to the user in case of language server starting error

### ISSUE THREAD

**Issue by robertoaloi** [microsoft/vscode-languageserver-node#824]
Starting a language server via a `client.start()` can result in an error. Usually the stdout or stderr for the server process contain hints to what the problem could be. In case of such an error while starting the server, the only message displayed to the user is something like:

```
[Error - 1:33:53 PM] Connection to server got closed. Server will not be restarted.
```

I wonder if there's any way to improve the situation and display the stdout/stderr from the server to the user when the language server fails to start. The `clientOptions` include a `errorHandler` that can be customized, but that doesn't seem to help, since when the issue occurs the `closed()` method does not get any arguments.

Note: I'm not a Typescript / JS developer myself, so there may be something I'm missing.

**Comment by dbaeumer** [comment]
If the communication channel is NOT stdout/stdin then everything a server write to stdout/stderr is printed to the output channel. The corresponding code is here: https://github.com/microsoft/vscode-languageserver-node/blob/f271aef201b38bedabd442d45d3b28bbbdb2b6c2/client/src/node/main.ts#L341

So in your case it looks like the server doesn't start and even capturing stderr/stdout doesn't work.

**Comment by robertoaloi** [comment]
The communication channel does use stdout/stdin (code at https://github.com/erlang-ls/vscode/blob/main/client/src/extension.ts#L19 and https://github.com/erlang-ls/vscode/blob/main/client/src/client.ts#L46). As a language server maintainer, what I'm trying to figure out is how can I improve things in the VS Code client so that eventual issues which cause the server to fail to start (e.g. due to environmental issues) can be propagated to the user via the UI.

**Comment by dbaeumer** [comment]
If the communication happens over stderr / stdout the server can't use these to write message to the console. It will interfere with the communication. 

The protocol defines alternative message which work in all cases. See https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#window_logMessage

**Comment by robertoaloi** [comment]
Alan's interpretation is correct. I'm raising this with the Emacs LSP client as well.

**Comment by robertoaloi** [comment]
Here is a workaround for this issue in Erlang LS: https://github.com/erlang-ls/vscode/issues/113

**Comment by dbaeumer** [comment]
The handler now allows to return a message that will be presented to the user with a button to open the output channel (which contains stdout)

**Comment by robertoaloi** [comment]
That's nice. Will try this asap, thanks!

**Comment by axelson** [comment]
> The handler now allows to return a message that will be presented to the user with a button to open the output channel (which contains stdout)

That's great! Are there any examples of a client that utilizes it?

**Comment by dbaeumer** [comment]
The LSP client itself uses it :-). Search for references.
