### ISSUE TITLE
Document pull diagnostics never passes previousResultId

### ISSUE THREAD

**Issue by dibarbet** [microsoft/vscode-languageserver-node#826]
Hit this in 1.60 with the proposed diagnostics API, but from a quick glance at the latest code I think it still applies.

When requesting document diagnostics, `pullAsync` calls into `track` without passing a resultId. 
https://github.com/microsoft/vscode-languageserver-node/blob/10b56de150ad67c3c330da8e2df53ebf2cf347c4/client/src/common/proposed.diagnostic.ts#L295

In the implementation of `track`, the `resultId` variable is set to the value of `arg1` (when passed in a URI for the document) which is not passed into the method for document pull as above.
https://github.com/microsoft/vscode-languageserver-node/blob/10b56de150ad67c3c330da8e2df53ebf2cf347c4/client/src/common/proposed.diagnostic.ts#L198-L202

The document's `state.resultId` is overwritten with the `resultId` variable (undefined).
https://github.com/microsoft/vscode-languageserver-node/blob/10b56de150ad67c3c330da8e2df53ebf2cf347c4/client/src/common/proposed.diagnostic.ts#L207-L209

Later on document pull attempts to find the previousResultId by calling into the `documentStates` but that was just overwritten
https://github.com/microsoft/vscode-languageserver-node/blob/10b56de150ad67c3c330da8e2df53ebf2cf347c4/client/src/common/proposed.diagnostic.ts#L302

**Comment by dbaeumer** [comment]
Good catch. Thanks for reporting.
