### ISSUE TITLE
FileOperation request such as WillRenameFile doesn't provide cancellation token

### ISSUE THREAD

**Issue by heejaechang** [microsoft/vscode-languageserver-node#827]
it looks like even if user clicks cancel button on vscode for file operation that takes long time, LSP doesn't raise cancellation on file operation request.

https://github.com/microsoft/vscode-languageserver-node/blob/main/client/src/common/fileOperations.ts#L315

no cancellation token is given to client.sendRequest call.

...

though, it feels like it is inherited issue from vscode file operation API where willrenamefile event doesn't pass along cancellation token from progress bar it creates for file operation.

https://github.com/microsoft/vscode/blob/main/src/vs/base/common/event.ts#L610

it feels like data should have cancellation token. in current design. once event is fired, operation (to calculate workspace edits) can't be cancelled.

**Comment by dbaeumer** [comment]
Fixed.

**Comment by DanTup** [comment]
@dbaeumer awesome! Do you have a rough idea of when this might make a release (either for the current version, or vnext)?  Not urgent, will just help me plan (I have an improvement for Dart that I don't want to merge until this is available). Thanks!

**Comment by dbaeumer** [comment]
Somewhen in January. Will not make it before Christmas.

**Comment by DanTup** [comment]
Thanks, that helps! :)

**Comment by DanTup** [comment]
@dbaeumer are you still hoping to ship this in the near future? (does it require VS Code to ship https://github.com/microsoft/vscode/issues/135391 first, which I presume is early feb?)

**Comment by dbaeumer** [comment]
I did make a new next version a week ago. But will only work with the next stable VS Code which ships early Feb.

**Comment by DanTup** [comment]
Great - I'll give that a try after VS Code ships. If it seems to work, are there any known issues that might make it a bad idea for me to ship with the next version (assuming it all appears to work to me and pass my tests, ofc)?
