### ISSUE TITLE
Support `$/progress` notifications while server is initializing

### ISSUE THREAD

**Issue by ericdallo** [microsoft/vscode-languageserver-node#828]
Related https://github.com/microsoft/vscode-languageserver-node/issues/671#issuecomment-932838714

It seems it's not possible to handle `$/progress` notifications during server initialize since there are checks that return that the  client is not ready yet.
`clojure-lsp` is an example of server that returns `$/progress` notifications during server initialize, this seems to work with Emacs `lsp-mode`, the lsp client for Emacs, but not with vscode

**Comment by dbaeumer** [comment]
This is possible right now, but the server can't use create progress. The client needs to send a progress token with the initialize request. If you use the VS Code LSP client the following client option setting is your friend: `progressOnInitialization`

**Comment by dbaeumer** [comment]
You need to await `onReady()`. However due to the way how initialization works you can't intercept it. The lib takes care of presenting the progress in the UI.

**Comment by ericdallo** [comment]
@dbaeumer  The issue is that [calva](https://calva.io/) has a custom statusBar text on the vscode extension for the LSP server, and I would like to hide that status bar when receiving the first progress report during server initialization.
So it'd behave to something like this:
- time 0s: calva extension loads on vscode and display `Starting clojure-lsp...` at statusBar
- time 3s: clojure-lsp sends its first progressReport, so calva remove the text on statusBar and let the progress report works by default.

**Comment by dbaeumer** [comment]
The only thing I can then recommend is to do the initialization in the `initialized` notification. There you can handle your own progress messages since the client will be ready.

**Comment by ericdallo** [comment]
but clojure-lsp needs to analyze whole project and can take even some minutes for some huge projects to return the initialized notification

**Comment by dbaeumer** [comment]
Why does the server block on the `initialize` request. All communication is async. So it doesn't need to wait until it has analyzed the whole project.

If you really need to report progress during the `initialize` all I can suggest for now is to use the LSP lib client setting. 

If you want to look into making the progress customizable in the LSP libs for the initialize request then this need to happen here: https://github.com/Microsoft/vscode-languageserver-node

**Comment by ericdallo** [comment]
The server blocks because it makes no sense to initialize the LSP without server analysis, if we do not block initialize, all features like navigation and other things wouldn't work.
This works good for emacs, lsp-mode accepts progress report even during the initialization which follows what the spec proposes AFAICS, so I think we should allow vscode support the same

**Comment by dbaeumer** [comment]
Actually the spec states something different. See: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialize

This is why the VS Code client only supports the token on the initialize request.

**Comment by ericdallo** [comment]
I can probably be misunderstanding something, but won't this apply for this issue?
> In case the client sets up a progress token in the initialize params (e.g. property workDoneToken) the server is also allowed to use that token (and only that token) using the $/progress notification sent from the server to the client.

Since clients send a workDoneToken during the initialize request, the server can then report progress during initialization, this is how clojure-lsp does at the moment with emacs as a example:
![clojure-lsp-startup (1)](https://user-images.githubusercontent.com/7820865/140316193-362d0b55-f584-4367-aa40-bd36e42ae6ef.gif)

**Comment by dbaeumer** [comment]
Actually this is what is possible in the VS Code LSP libs as well. See

![cast](https://user-images.githubusercontent.com/1931590/140750847-7bc89ff1-2736-4077-ae5b-01f1eabcd214.gif)
