### ISSUE TITLE
Allow manually killing the server process

### ISSUE THREAD

**Issue by bostick** [microsoft/vscode-languageserver-node#834]
I am developing an LSP client extension.

Let's say that I had a typo in my `command` of the `ServerOptions` object that I'm creating.

The command is now some command that hangs when given the usual traffic from an LSP client.

I am already showing an error message after 10 seconds if this happens.

I am interested in also manually killing the server process that was started.

I could not see if there was already an API for doing that, so I am creating this issue.

This is not anything to do with the actual protocol, because I am talking about a process that does not even understand the protocol.

This is low-level error handling and cleanup.

The real-world case that I am trying to solve is running a command that may not have the proper packages installed yet, and so hangs on startup.

**Comment by bostick** [comment]
I have not had success in the past with setting up debugging of my language server extension, but I will try it again.

**Comment by dbaeumer** [comment]
OK. Let me know any outcome.
