### ISSUE TITLE
`instanceof` checks in `codeConverter.ts` make interface conformity insufficient

### ISSUE THREAD

**Issue by colin-grant-work** [microsoft/vscode-languageserver-node#841]
In the [codeConverter](https://github.com/microsoft/vscode-languageserver-node/blob/main/client/src/common/codeConverter.ts) file, there are [a](https://github.com/microsoft/vscode-languageserver-node/blob/4a418adf81486540b8eb9c243b1008cecc9b9d0f/client/src/common/codeConverter.ts#L498-L501) [number](https://github.com/microsoft/vscode-languageserver-node/blob/4a418adf81486540b8eb9c243b1008cecc9b9d0f/client/src/common/codeConverter.ts#L702-L704) [of](https://github.com/microsoft/vscode-languageserver-node/blob/4a418adf81486540b8eb9c243b1008cecc9b9d0f/client/src/common/codeConverter.ts#L807-L809) [`instanceof`](https://github.com/microsoft/vscode-languageserver-node/blob/4a418adf81486540b8eb9c243b1008cecc9b9d0f/client/src/common/codeConverter.ts#L784-L787) checks that determine whether or not particular bits of the incoming object will be included in the object returned, many of them associated with the addition of a `data` field to the LSP interface. Those checks mean that for any client that depends on this code, conformity to the interface defined by the LSP isn't sufficient: the objects have to include the `ProtocolX` type in their prototype chain. This can be worked around: either the creator of the object can use the appropriate constructor or the client can supply middleware that does its own conversion; but I'm not sure I understand the need for the `instanceof` checks. In most cases, the fields that are or aren't included are typed as `unknown | undefined` or `any | undefined` , so their values don't matter, and they can never be used safely - why be picky about the exact prototype chain that led to their presence?

**Comment by colin-grant-work** [comment]
@dbaeumer, thanks for the answer. The origin of the code handling the `.data` field - the mismatch between LSP and VSCode types - was clear. The problem is the specific form of the `instanceof` check: that means that the object has to have a particular history, not just a particular form. Is there any reason not to replace this

https://github.com/microsoft/vscode-languageserver-node/blob/4a418adf81486540b8eb9c243b1008cecc9b9d0f/client/src/common/codeConverter.ts#L807-L809

with this

```typescript
if (value.data !== undefined) {
    result.data = value.data;
}
```

Certainly the primary use case will be `ProtocolCallHierarchyItem`s, but it would also allow other callers to pass in objects that conform to the same interface and get the same results.

**Comment by dbaeumer** [comment]
This ensures that the data I will transfer back actually originated from an LSP server since the library has created the `ProtocolCallHierarchyItem`. 

Were do you want to use the converter. It is not API outside a LSP client interface.

**Comment by colin-grant-work** [comment]
@dbaeumer, I [ran into the problem](https://github.com/eclipse-theia/theia/pull/10310#issuecomment-952109208) with call hierarchy items using the [VSCode CLangD plugin](https://github.com/clangd/vscode-clangd) in [Eclipse Theia](https://github.com/eclipse-theia/theia). Basically, call hierarchy items in Theia get passed around and type-converted quite a bit, and so the type converter in the CLangD plugin, which uses the code I've pointed out here, was failing until I monkey-patched away the `instanceof` check. Eventually, Theia will depend on a version of the LSP code that has the constructor that could make the problem go away, but since LSP entities are [defined as interfaces](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#callHierarchyItem), it seems odd to write checks that require correct inheritance as well as interface conformity.

**Comment by dbaeumer** [comment]
But `ProtocolCallHierarchyItem` is not a LSP entity it is a internal VS Code entity. The LSP entity is `CallHierarchyItem` which is defined here: https://github.dev/microsoft/vscode-languageserver-node/blob/7fe768781e9e0c8e5f1b126f886a967e52fe1b2a/types/src/main.ts#L3334

**Comment by colin-grant-work** [comment]
@dbaeumer, I'm not sure what you mean? It's true that `ProtocolCallHierarchyItem` is not an LSP entity, and I think that that's exactly the thing that makes it strange to check whether something is a `ProtocolCallHierarchyItem` when handling its `data` field. Since the `data` field exists in the LSP interface you linked to, it's strange for code that's handling communication with a language server using the LSP to check whether the `data` field it sees has a particular provenance. The language server won't know and shouldn't care whether the `data` got there by way of having been transmitted as a `ProtocolCallHierarchyItem` - that's not an LSP entity, and the LSP only cares about the interface - so why check whether the `data` comes from a `ProtocolCallHierarchyItem` before transmitting it?

**Comment by dbaeumer** [comment]
The code is SPECIFIC for VS Code and a LSP `CallHierarchyItem` received from a server is converted to a `ProtocolCallHierarchyItem` when passed to VS Code. The reason is that for resolve calls VS Code ensures object identity and object identify is implemented in LSP via a data pointer. It also helps to bridge gaps between LSP data structures and VS Code data structures. A more complicated example why this is done that way is the `ProtocolCompletionItem` (https://github.com/microsoft/vscode-languageserver-node/blob/6d1e2fcdd40e193a8eee1c073db6a8458c5bb88f/client/src/common/protocolCompletionItem.ts#L9) which stores a lot more LSP state to resend the correct state on a resolve call.

If you want to use a VS Code type independent way to talk to a server then the `vscode-languageserver-protocol` library should be used. This doesn't introduce any VS Code specific types.
