### ISSUE TITLE
Allow array of MarkupContent in Hover

### ISSUE THREAD

**Issue by DifficultNick** [microsoft/vscode-languageserver-node#843]
The `contents` property of `Hover` interface has type `MarkupContent | MarkedString | MarkedString[]` where `MarkedString` is deprecated now. So why there is no `MarkupContent[]` in this type?

P.S. however `vscode.Hover.contents` is still `MarkdownString[]`

**Comment by dbaeumer** [comment]
There is a difference between vscode API and LSP. LSP tries to work across different editors that is why it might be different.

`MarkupContent` allows to have different languages in one value. This is why no array variant exists. With `MarkedString` that was not possible.
