### ISSUE TITLE
VSCode UI freezes intermittently when an extension is using a language server 

### ISSUE THREAD

**Issue by lispercat** [microsoft/vscode-languageserver-node#845]
I started to develop my own language server (for embedded XML) and I noticed that when I type text in the editor while debugging the language server the text window stops responding for a few seconds once in a while.

When I tried to run [this sample](https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-sample) I noticed the same periods of UI freeze. 

When I edit Java code (which uses a language server in the background) I have a similar experience as well.
I wonder if it's the right place for this issue or I'll need to post it in VSCode github?

I am using VSCode on Windows 10 version 1.61.2.
The computer I am using is IdeaPad Flex 5, so it should be powerful enough to handle it without freezes.

**Comment by dbaeumer** [comment]
Do you see the same with TS and ESLint ?

**Comment by lispercat** [comment]
No, I don't see this issue when editing a ts file with ESLint enabled.
Seems like the problem starts to creep in when I have a Java file open
(with "Language support for Java ™ for Visual Studio Code" extension
running).
In this case, I have UI delays with my extension and editing a ts file as
well.
Without Java in the picture, it seems to be working smoothly.
I guess I'll take this issue to the VSCode Java extension.
Thanks, Dirk!

**Comment by lispercat** [comment]
@dbaeumer Dirk, did you employed BufferedMessageQueue so to alleviate the issue of UI freezing for your extension?

**Comment by dbaeumer** [comment]
The VS Code design should already prevent the UI from freezing since the actual extension code is executed in a separate process. So the editor itself should always be responsive.

No, the BufferedMessageQueue is to be able to skip unnecessary validation requests (e.g. computing problems)

**Comment by dbaeumer** [comment]
Since you don't see this with ESLint nor TS I would recommend you open an issus against the Java extension since it is reproducible there.
