### ISSUE TITLE
Inconsistency in $/setTrace

### ISSUE THREAD

**Issue by Scaremonger** [microsoft/vscode-languageserver-node#846]
When building a language server I came across an inconsistency between the Specification and VSCode and thought I should log it here first to confirm if the specification or the IDE is at fault.

The specification for a Set Trace Notification says that the method will be  
```
method: '$/setTrace'
```
In reality I receive the following message (from VSCode):
```
method: '$/setTraceNotification'
```
Please could you confirm if this is a bug I should report for VSCode or for the Specification?

**Comment by Scaremonger** [comment]
I am running:
Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T14:58:13.605Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-74-generic

The language server I am developing is in BlitzMaxNG so I am not using any Node libraries.

**Comment by Scaremonger** [comment]
Hi,
This one can be closed. I tracked the issue down to the VSCode extension and the author has updated it.

Many thanks for your time.

Regards,
SI...

**Comment by dbaeumer** [comment]
Closing then.
