### ISSUE TITLE
Semantic highlighting flicker as you type is back

### ISSUE THREAD

**Issue by HighCommander4** [microsoft/vscode-languageserver-node#851]
I'm noticing that recently, https://github.com/clangd/vscode-clangd/issues/161 appears to be back.

Not exactly sure what changed, i.e. a clangd update (I use a trunk build that's usually at most a few weeks out of date) or a vscode update.

**Comment by dbaeumer** [comment]
@HighCommander4 can you provide a screen cast and a LSP trace. The setting for enable tracing however depends on the clangd server. Usually it is something like `${servername}.trace.server`

**Comment by HighCommander4** [comment]
With some experimentation, I determined this to be a regression neither from clangd nor the vscode-clangd plugin (which is what pulls in vscode-languageclient), but in vscode itself.

Specifically, the issue started when upgrading from vscode 1.61 to vscode 1.62.

The good news is: the issue was resolved by a recent minor-version update, from 1.62.1 to 1.62.3!

**Comment by HighCommander4** [comment]
Looking through the release notes, it was clearly https://github.com/microsoft/vscode/issues/136540.

**Comment by dbaeumer** [comment]
@HighCommander4 thanks for getting back and closing the issue.
