### ISSUE TITLE
Support for NodeJS `ReadableStream` and `WritableStream`

### ISSUE THREAD

**Issue by AArnott** [microsoft/vscode-languageserver-node#853]
The stream support in vscode-jsonrpc:

https://github.com/microsoft/vscode-languageserver-node/blob/dca3c1a04797aaaa7d48060cca38b16efdf4392f/jsonrpc/src/common/messageWriter.ts#L114
https://github.com/microsoft/vscode-languageserver-node/blob/dca3c1a04797aaaa7d48060cca38b16efdf4392f/jsonrpc/src/common/messageReader.ts#L179

seem centered around this proprietary definition of what streams should do:

https://github.com/microsoft/vscode-languageserver-node/blob/dca3c1a04797aaaa7d48060cca38b16efdf4392f/jsonrpc/src/common/ral.ts#L38-L52

This seems to make consuming the much more broadly used `NodeJS.ReadableStream` and `NodeJS.WritableStream` interfaces with the library much harder. Is there some reason the library cannot accept these interfaces as well?

**Comment by AArnott** [comment]
FWIW I whipped up some adapters that I _think_ will work. It would sure be nice if the library could use these internally in order to accept the NodeJS variety natively:

```ts
import { Disposable, RAL } from "vscode-jsonrpc";

export class ReadableStreamAdapter implements RAL.ReadableStream {
    constructor(private readonly readable: NodeJS.ReadableStream) {
    }

    onData(listener: (data: Uint8Array) => void): Disposable {
        this.readable.on('data', listener);
        return Disposable.create(() => this.readable.off('data', listener));
    }
    onClose(listener: () => void): Disposable {
        this.readable.on('close', listener);
        return Disposable.create(() => this.readable.off('close', listener));
    }
    onError(listener: (error: any) => void): Disposable {
        this.readable.on('error', listener);
        return Disposable.create(() => this.readable.off('error', listener));
    }
    onEnd(listener: () => void): Disposable {
        this.readable.on('end', listener);
        return Disposable.create(() => this.readable.off('end', listener));
    }
}

export class WritableStreamAdapter implements RAL.WritableStream {
    constructor(private readonly writable: NodeJS.WritableStream) {
    }

    onClose(listener: () => void): Disposable {
        this.writable.on('close', listener);
        return Disposable.create(() => this.writable.off('close', listener));
    }
    onError(listener: (error: any) => void): Disposable {
        this.writable.on('error', listener);
        return Disposable.create(() => this.writable.off('error', listener));
    }
    onEnd(listener: () => void): Disposable {
        this.writable.on('end', listener);
        return Disposable.create(() => this.writable.off('end', listener));
    }
    write(data: Uint8Array): Promise<void>;
    write(data: string, encoding: "ascii" | "utf-8"): Promise<void>;
    write(data: any, encoding?: any): Promise<void> {
        return new Promise<void>((resolve, reject) => {
            this.writable.write(data, encoding, (err: Error | null | undefined) => {
                if (err) {
                    reject(err);
                } else {
                    resolve();
                }
            });
        });
    }
    end(): void {
        this.writable.end();
    }
}
```

**Comment by dbaeumer** [comment]
Actually it does. The code is here: https://github.com/microsoft/vscode-languageserver-node/blob/44ab977c6a54407d725048e33201f7ad9899cae9/jsonrpc/src/node/main.ts#L224

The implementation is here https://github.com/microsoft/vscode-languageserver-node/blob/dca3c1a04797aaaa7d48060cca38b16efdf4392f/jsonrpc/src/node/ril.ts#L50 and can be instantiated here https://github.com/microsoft/vscode-languageserver-node/blob/dca3c1a04797aaaa7d48060cca38b16efdf4392f/jsonrpc/src/node/ril.ts#L156

The reason for that interface is that the library now has support for Node and Browser environments and the common code works in both.

I will close the issue. Please ping if I missed something and I will reopen

**Comment by AArnott** [comment]
Nice. Just by changing my existing `import ... from 'vscode-jsonrpc'` to `import ... from 'vscode-jsonrpc/node'` I can see the overload I was looking for. Thank you.
