### ISSUE TITLE
Possible error in documentation for `export interface Telemetry`

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/vscode-languageserver-node#854]
The documentation for the `logEvent(data: any): void;` method of `export interface Telemetry` says [` * @param data The data to log. Must be a JSON serializable object.`](https://github.com/microsoft/vscode-languageserver-node/blob/167254d2246b98976dc240bfa26dca05932096b0/server/src/common/server.ts#L898).

However, in `server/src/server.ts`, I'm able to do `connection.telemetry.logEvent("some string");` without any errors, and it seems not to break anything. Telemetry seems to work just fine on the backend, and I think I'm able to see "some string" in Application Insights on the Azure Portal using [`vscode-extension-telemetry`](https://github.com/Microsoft/vscode-extension-telemetry#setup).

Is the documentation misleading? It appears `data` can really be `any`thing as the type suggests, and not just a "JSON serializable **object**" as the documentation states.

Or, is a `string` a `JSON serializable object`? There could be a gap in my understanding.

**Comment by dbaeumer** [comment]
Yes, a string is a JSON serializable object (e.g. `JSON.stringify('some string')` is valid).
