### ISSUE TITLE
Be more verbose about watchdog-related process.exit

### ISSUE THREAD

**Issue by sethidden** [microsoft/vscode-languageserver-node#857]
[This repo contains logic that makes the server close itself if the client process that started the sever in the first place got closed](https://github.com/microsoft/vscode-languageserver-node/blob/d58c00bbf8837b9fd0144924db5e7b1c543d839e/server/src/node/main.ts#L89). This is a nice feature — if vscode closes it makes sense to close its langservers also. This is standard operation and it's understandable nothing is logged to stderr in that case. But what if the client process could never be found in the first place? 

Examples of this happening:
* client process is *outside* a podman container but server is started *inside* a container. vscode-languageserver-node's watchdog is looking for process id eg. 33421 that exists on the host, but is not visible from within the container (fixed by --pid=host arg in docker/podman) https://github.com/johnsoncodehk/volar/issues/706#issuecomment-974820245 
* Manually starting the server with a non-existent client process id https://github.com/typescript-language-server/typescript-language-server/issues/262

## Is this really a problem?
If you look for what people post in those issues, you'll see:
* > Is there any way to [...] print an error when exiting, rather than exiting silently?
* > Set up "pause on exceptions" but volar just dies without any exception happening (this one is mine :P)
* > what make me confuse is the language server may exist without any log

The lack of logs in this case is particularly tragic since a developer's first reflex in the case I described above is to fire up the debugger, but the debugging will only give you information about "how far can the perfectly good server code go till watchdog kills after 3 seconds" (unless you actually put a breakpoint on the watchdog, which is a separate timer). I would know since I spent 8 hours debugging exactly that :P

## Potential solutions
Right now the [watchdog code](https://github.com/microsoft/vscode-languageserver-node/blob/d58c00bbf8837b9fd0144924db5e7b1c543d839e/server/src/node/main.ts#L89) treats the "client pid closed so the server should also close" case as if it's always somewhat intended. It naively assumes that since the server started, the client has always been available since the server's launch. 

There are two cases to consider:
1. the client started the server and the server knows the client PID exists when the server was starting
2. (what isn't supported and what this issue talks about) the client started the server and for some reason the client PID is not available in the server's context at the very beginning of the server's life. In that case there's no point in waiting the 3 seconds for the watchdog to kill it, since we know right now the process doesn't exist

Would it make sense to check if the client pid even exists at the very start of the server's life instead of waiting for the watchdog to kill it? 
Like in [initialize](https://github.com/typescript-language-server/typescript-language-server/blob/bd2a889a23f19aae1ac7fb902ed161f26009624d/src/lsp-server.ts#L90) there could be a ping to check if the params.processId exists and if not, we know we're dealing with case number 2. from above, so an exception should be thrown

**Comment by sethidden** [comment]
Also, `process.exit(_shutdownReceived ? 0 : 1);` should be `process.exit(_shutdownReceived 0 : 3)` no?
Since error code 3 is "no such process"

**Comment by dbaeumer** [comment]
How do you connect to / start the server. The library has support for `detached` mode which tells the client that it doesn't own the server and hence can't kill it when the client stops. However the concrete way how to let the client know about detached mode depends on how you connect to the server. You might want to look at https://github.com/microsoft/vscode-languageserver-node/blob/f9faf63b7f1acef6a619ac06f78bc3b1bcfed2e2/client/src/node/main.ts#L1 and the use of `detached`.

Let me know if this helps.

**Comment by sethidden** [comment]
>How do you connect to / start the server.

I think the most relevant code parts to this question are:
https://github.com/johnsoncodehk/volar/blob/6a37398fdf3fe7c7c360d615075328d45d1a39cf/packages/server/src/index.ts#L8
https://github.com/johnsoncodehk/volar/blob/6a37398fdf3fe7c7c360d615075328d45d1a39cf/packages/server/src/common.ts#L31

> The library has support for detached mode which tells the client that it doesn't own the server and hence can't kill it when the client stops

I already resolved the issue I was having (this is not a "somethings not working please help" issue, it's more of a "I already fixed the issue I was having, but fixing it was really hard, can you add more logs for this case?". 
It's just that fixing it was really difficult because vscode-languageserver was failing silently and I a PR could be submitted to this repo to improve the logging in the case I was facing.

The default non-detached mode works OK for my usecase. I'm just asking for the default non-detached mode to be more verbose when the client's process is dead on arrival when the server starts. As I outlined above, this can happen when working with Docker when e.g. the client is on the host machine, but the server starts inside a container (so the host machine's client PID is not available within). So from the very start of the server's life, the client process is dead, but the watchdog will still wait 3s to kill the server.

**Comment by sethidden** [comment]
I guess this is a rough draft of the change that addresses this issue:
https://github.com/sethidden/vscode-languageserver-node/commit/ba2d831621b1eba7259281b980509ffda36bd923

**Comment by dbaeumer** [comment]
@sethidden my questions was more around how the client code starts the server. Clients can decide this and it has an impact on how the client handles the server process when the client stops. I am asking since the pointers you send me are about the server implementation not the client starting the server.

**Comment by WhyNotHugo** [comment]
I'm starting LSPs in containers (via podman). I hope this answers the "how are clients starting the LSP".

More context here: 
https://github.com/johnsoncodehk/volar/issues/706

The client should have set processId=null, but this was hard to figure out beforehand, due to the LSP simply exiting silently.

**Comment by dbaeumer** [comment]
The way to handle this is to pass a server function to the client and return a `MessageTransport` with the detached flag set to true. This tells the client that it doesn't own the server.

I want to point out that this used case is not officially supported. Main use case of the lib is to have client and server on the same machine. 

I will close the issue since the necessary support is there. Please ping if this doesn't work.

**Comment by WhyNotHugo** [comment]
> Main use case of the lib is to have client and server on the same machine.

I'm okay with this, but maybe failing with an error instead of failing silently would be helpful, especially for each time anyone comes across this issue.

The issue here isn't about supporting this scenario better, but yielding a clearer output for those of us who come across this issue (which is super hard to debug). I can't image that running a client and a server on different environments is very common -- the opposite even sounds kinda insecure.

**Comment by sethidden** [comment]
> The way to handle this is to pass a server function to the client and return a MessageTransport with the detached flag set to true. This tells the client that it doesn't own the server.

I agree with you on this. Later, you mention this about detached mode:

> I want to point out that this used case is not officially supported. Main use case of the lib is to have client and server on the same machine.

Since `Client Owns The Server Mode` is the official/default mode, I assume your intention is to have users of this library go through this flow:
1. Try to implement their server using the official `Client Owns The Server Mode` <- most people will stop here as it'll work for them
2. See that mode doesn't work for their use case for some reason
3. Switch to the secondary "Detached mode"

My point with this issue is that the step 2 of this process is difficult and perhaps it'd be nice to add some more logging at this point to guide users:
* they should consider using detached mode (Hugo's case) — your recommendation
* that there's something wrong with their client-server setup and they need to fix it on their side order to make the server see the client's PID in `Client Owns The Server Mode` normally (my case)

Right now the 3 step process from above looks like this in detail:
1. Ask the client to start the server using `Client Owns The Server Mode`
2. The server for some reason can't find the client's PID. The answer to this is detached mode, but the user doesn't know this yet. **The server will close without anything logged to the console**. The watchdog just kills the server after 3 seconds, even though the client's PID was unavailable since the very start of the server, before the watchdog was initialized.
3. Switch to the secondary "Detached mode"

How I'm suggesting it could look like:
1. Ask the client to start the server using `Client Owns The Server Mode`
2. (assuming something similar to https://github.com/sethidden/vscode-languageserver-node/commit/a310c60e535cf521ebbd96d8aecb2aada3770366 is added to the repo)  The server for some reason can't find the client's PID. The answer to this is detached mode, but the user doesn't know this yet. **The server closes, but logs that client's processId e.g. 3352 does not even before the watchdog is initialized.** The server closes immediately, not after 3 seconds.
3. The user realizes their usecase does not work with attached mode due to some caveats with client passing PID to server and switches to detached mode.

@dbaeumer do you agree with us that the user experience on step 2 could be improved by adding something like https://github.com/sethidden/vscode-languageserver-node/commit/a310c60e535cf521ebbd96d8aecb2aada3770366 ?

**Comment by dbaeumer** [comment]
Yes, I do agree but the way you addressed this is not correct. If the client crashed before the server did the first check then the server hangs.

IMO the right fix should be to not send the process id in this case. The code where it is filled in is here: https://github.com/microsoft/vscode-languageserver-node/blob/f9faf63b7f1acef6a619ac06f78bc3b1bcfed2e2/client/src/node/main.ts#L237

PR welcome.
