### ISSUE TITLE
How to get strike-through text not just for hover items in list, but also after selecting a deprecated keyword?

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/vscode-languageserver-node#860]
I'm able to get a deprecated keyword have strike-through text when it appears in a list of suggested completion items, but after selecting that keyword, I'm not able to have it with strike-through text.

https://user-images.githubusercontent.com/43425812/143143561-80bc3ff1-1c9c-4eb9-aa0b-931582a38f21.mov

How would I go about getting strike-through text after selecting a deprecated keyword in a completion item menu?

It appears JavaScript's language server has this support. I'd like to be able to implement this, too, if it's possible.

https://user-images.githubusercontent.com/43425812/143143544-c9565ab9-037d-49f7-aba3-833104e56241.mov

**Comment by rcjsuen** [comment]
> How would I go about getting strike-through text after selecting a deprecated keyword in a completion item menu?

Your server has to publish diagnostics to support this. The diagnostic you publish would also need to be tagged with `DiagnosticTag.Deprecated` to hint to the client that it should render this diagnostic a particular way (in this case, by applying strikethrough on the text).

**Comment by hamirmahal** [comment]
Ah, I see. I'll give this a shot, and reopen this if I'm not able to get it to work. Thank you very much, @rcjsuen!

**Comment by hamirmahal** [comment]
At what phase would we send the diagnostics?

Perhaps before returning from `connection.onCompletion(`?

**Comment by rcjsuen** [comment]
> At what phase would we send the diagnostics?

Generally speaking, you would publish diagnostics when you've detected changes to the file in the editor and/or the files on disk.

> Perhaps before returning from `connection.onCompletion(`?

That would not work because there would be nothing to highlight. Your user has not even selected `const` so the editor is empty. If the editor is empty then there is nothing to highlight.

I suggest going through [this tutorial](https://github.com/microsoft/vscode-docs/blob/2eb899e24b6f8e0594395a92d3437b3a6803e8a0/api/language-extensions/language-server-extension-guide.md). I followed this tutorial back in 2017 when I started working on my language server.

**Comment by hamirmahal** [comment]
Okay, okay, I see. That makes sense.

I was hoping there was some event that fired when users select a keyword from the hover options, so that we could immediately "strike-through" a keyword once they select it. That's the behavior the JavaScript language server _appears_ to have, although it could just be doing a lot more actions very, very quickly.

I have some trepidation about "striking through" deprecated keywords on every keystroke, which is how often we're calling `validateTextDocument()`, since that requires a linear search through a source file just to find the few deprecated keywords, if there even are any, to "strike-through" them.

I actually have gone through that tutorial already, but it seems like I'm lacking a deep understanding, so I'm going to go through it again. Thank you very much for your response!

**Comment by rcjsuen** [comment]
> I was hoping there was some event that fired when users select a keyword from the hover options

There is no such event in the language server protocol.

> I have some trepidation about "striking through" deprecated keywords on every keystroke, which is how often we're calling `validateTextDocument()`, since that requires a linear search through a source file just to find the few deprecated keywords, if there even are any, to "strike-through" them.

You would have to search the source file in other scenarios also. Consider the case where your user typed in the keyword manually or if the user comments and then subsequently uncomments the keyword. You would want the editor to decorate the word even though the user did not use code completion.

Open this [page](https://rcjsuen.github.io/dockerfile-language-service/) and then type the word `maintainer` at the beginning of a line and you will see the strikethrough is essentially applied instantaneously irregardless of whether you use code completion or you’ve typed out the word by hand. The editor is responsive despite the fact that my language server is scanning the whole file whenever its content has changed.

**Comment by hamirmahal** [comment]
> There is no such event in the language server protocol.

Ah, I see.

> You would have to search the source file in other scenarios also. Consider the case where your user typed in the keyword manually or if the user comments and then subsequently uncomments the keyword. You would want the editor to decorate the word even though the user did not use code completion.

We have `validateTextDocument()` inside of `documents.onDidChangeContent()`, so this should handle all of the above, correct?

> Open this [page](https://rcjsuen.github.io/dockerfile-language-service/) and then type the word `maintainer` at the beginning of a line and you will see the strikethrough is essentially applied instantaneously irregardless of whether you use code completion or you’ve typed out the word by hand. The editor is responsive despite the fact that my language server is scanning the whole file whenever its content has changed.

Thank you for the link! How does one look at just the diff between the current version of a `textDocument` and the previous version, and not the _entire_ `textDocument`?

If we have a 1,000 line program, and someone types `// hello!`, we wouldn't want to look at each word in the 1,001 lines to see if there are any deprecated keywords. Instead, we would just want to look at words in the lines that have new content, like `// hello!`, to check for deprecated keywords. Is that possible?

I did some very informal testing with what I think is the JavaScript language server in VSCode, and it seems to just "turn off" validation after 40,000 lines, I'm assuming for performance reasons.

https://user-images.githubusercontent.com/43425812/143496815-502ba1cc-cd33-4693-b56e-0d117083dfc0.mov

I realize most programs won't be anywhere near this long, and for our language, we'll probably have 1,000-line programs at most, in most circumstances, but it would be nice if someone charged with the task of making changes to a 100,000-line source file didn't have to choose between turning off validation altogether and validating every word in a source file every time we run validation. It would be more efficient to just look at lines that have new changes, if that's an option.

To its credit, the JavaScript language server seems to handle validation relatively well around the 10,000-line mark, although perhaps it's only looking at a `textDocument`'s diff instead of validating the entire `textDocument` from scratch each time. I'm not sure what source file to check to verify this.

https://user-images.githubusercontent.com/43425812/143497253-5e00970b-792d-45a5-9d67-3bba83d2c8ab.mov

**Comment by rcjsuen** [comment]
> > You would have to search the source file in other scenarios also. Consider the case where your user typed in the keyword manually or if the user comments and then subsequently uncomments the keyword. You would want the editor to decorate the word even though the user did not use code completion.
> 
> We have `validateTextDocument()` inside of `documents.onDidChangeContent()`, so this should handle all of the above, correct?

Correct.

> How does one look at just the diff between the current version of a `textDocument` and the previous version, and not the _entire_ `textDocument`?

You can use the `textDocument/didChange` event for that. The LSP editor will then send you a payload that indicates if content was inserted, replaced, or deleted.

https://github.com/microsoft/vscode-languageserver-node/blob/6fb9751243546b12ca8358df746d1248e465c714/protocol/src/common/protocol.ts#L1344-L1355

However, this assumes that you are using `TextDocumentSyncKind.Incremental` which [you are not](https://github.com/reach-sh/reach-lang/blob/79ffde30352b232e62f5dbfa5b4fce7388ff8bfa/vsce/server/src/server.ts#L121). If you want to keeping using [`TextDocuments`](https://github.com/reach-sh/reach-lang/blob/79ffde30352b232e62f5dbfa5b4fce7388ff8bfa/vsce/server/src/server.ts#L57-L59) then you have no choice but to keep asking for a full sync from the editor.

> If we have a 1,000 line program, and someone types `// hello!`, we wouldn't want to look at each word in the 1,001 lines to see if there are any deprecated keywords. Instead, we would just want to look at words in the lines that have new content, like `// hello!`, to check for deprecated keywords. Is that possible?

That's not for me to answer and is dependent on how you are parsing the document and the incoming changes. Consider a user that types `//` and then types `hello` two seconds later. You will only get the `//` event and `hello` event separately with a delay between them and your parser would have to determine that the user is typing inside a comment. If the user later deletes the `//` you would then only be notified that `//` has been removed and react to it accordingly.

> I realize most programs won't be anywhere near this long, and for our language, we'll probably have 1,000-line programs at most, in most circumstances, but it would be nice if someone charged with the task of making changes to a 100,000-line source file didn't have to choose between turning off validation altogether and validating every word in a source file every time we run validation. It would be more efficient to just look at lines that have new changes, if that's an option.

As I stated above, if your language server can react to the changes and respond in a timely manner then you are good to go.

**Comment by hamirmahal** [comment]
> That's not for me to answer and is dependent on how you are parsing the document and the incoming changes. Consider a user that types // and then types hello two seconds later. You will only get the // event and hello event separately with a delay between them and your parser would have to determine that the user is typing inside a comment. If the user later deletes the // you would then only be notified that // has been removed and react to it accordingly.

Ah, I did not consider this. I think for the moment, we're going to look at implementing other features, and then our team will revisit how we want to handle deprecated keywords in the future, although it seems like the approach you use for your language server, with a `Full` `TextDocumentSyncKind`,  is the way to go.

The information you posted is very helpful. Thank you very much for taking the time to write it all up, @rcjsuen!

**Comment by rcjsuen** [comment]
> it seems like the approach you use for your language server, with a `Full` `TextDocumentSyncKind`, is the way to go.

@hamirmahal Just to be clear, I use `Incremental` and not `Full`. Your code is currently using `Full`.

**Comment by hamirmahal** [comment]
@rcjsuen Ah, you're correct; my mistake. Thank you for the clarification!
