### ISSUE TITLE
Incorrect engines field on vscode-jsonrpc

### ISSUE THREAD

**Issue by nwolverson** [microsoft/vscode-languageserver-node#861]
The JS code for this module contains optional chaining but the declared node engines are incompatible with this.

Eg this issue:
https://github.com/justinwoo/easy-purescript-nix/pull/172#issuecomment-978930296

Optional chaining is supported from node 14: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

**Comment by dbaeumer** [comment]
Got a PR that fixed it.
