### ISSUE TITLE
How we should handle null values when using .net based server

### ISSUE THREAD

**Issue by nndobrev** [microsoft/vscode-languageserver-node#863]
Hi guys,

We have a .net based language server implementing the LSP. For CodeActions following the description here: https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/ when we don't have diagnostics we send back null. After updating our dependency from vscode 1.43 to 1.60 our CodeActions stopped working with the error below. We see you are checking if the diagnostics are undefined but we don't have a way to send undefined from .net.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/85873063/143620603-ee6a7257-92f2-422d-b5b0-a620ddb94790.png)

How should we approach the problem? Should we open an issue for vscode or would you handle null values as well or should we send empty arrays (this doesn't sound right)?

**Comment by rcjsuen** [comment]
https://github.com/microsoft/language-server-protocol/issues/355 was open but I can't find seem to find the clarification in the 3.17 specification. Perhaps you could try commenting in that issue.

**Comment by nndobrev** [comment]
It seems like vscode has introduced a parsing breaking change.
