### ISSUE TITLE
Code actions commands are not run automatically as they were in the past with vscode-languageclient

### ISSUE THREAD

**Issue by bpringe** [microsoft/vscode-languageserver-node#864]
When our extension used version 6.1.3 of vscode-languageclient and code actions were run, a call to `workspace/executeCommand` would be called with the appropriate command for the code action, without our extension needing to call that command manually.

With version 7.0.0, this stopped happening. I noticed version 3.16 of the LSP introduced the `codeAction/resolve` request, and I noticed that those requests are being sent, but the `command` in the `codeAction/resolve` response is not being run.

The protocol specification suggests that the command will be executed:

```
	/**
	 * A command this code action executes. If a code action
	 * provides an edit and a command, first the edit is
	 * executed and then the command.
	 */
	command?: Command;
```

I've implemented a fix in our extension using middleware, but I have a feeling this shouldn't be needed:

```typescript
            async resolveCodeAction(item, token, next): Promise<CodeAction> {
                const { command } = await next(item, token);
                if (command) {
                    sendCommandRequest(command.command, command.arguments);
                    return null;
                }
                return next(item, token);
            },
```

Is there an issue with vscode-languageclient, or am I misunderstanding something?

**Comment by dbaeumer** [comment]
Actually, VS Code has NO support to resolve the command lazy. It must be filled in when the code action is returned. The protocol specifies the properties that can be resolved lazy in the client capability `textDocument.codeAction.resolveSupport.properties` which VS Code sets to `['edit']`. See https://github.com/microsoft/vscode-languageserver-node/blob/caf2317bb661c066860c76f36ed841e44f06339b/client/src/common/client.ts#L2066

Closing the issue since this works as expected.

**Comment by dbaeumer** [comment]
To clarify further. The resolve request should only be used if the code action request return a `CodeAction` literal and not a `Command` literal.

**Comment by bpringe** [comment]
Thanks for the details. I'm don't think I'm really following, though.

> The resolve request should only be used if the code action request return a CodeAction literal and not a Command literal. Are you seeing this with the resolve request already returning a Command?

Here's an example of a complete interaction from my editor, from getting the available code actions at a position in the editor, to selecting one in the menu, then seeing the change applied in the editor.

When I select a code action in the menu that pops up, a `codeAction/resolve` request is automatically sent, then the `codeAction/resolve` response contains a command. We then send that command ourselves.

I just want to verify that the protocol is being used as intended, both from the server and the client perspective, with regards to this scenario.

```logs
[Trace - 8:15:29 PM] Sending request 'textDocument/codeAction - (7)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/brandon/development/clojure-test/src/core.clj"
    },
    "range": {
        "start": {
            "line": 3,
            "character": 5
        },
        "end": {
            "line": 3,
            "character": 5
        }
    },
    "context": {
        "diagnostics": []
    }
}


[Trace - 8:15:29 PM] Received response 'textDocument/codeAction - (7)' in 5ms.
Result: [
    {
        "title": "Change coll to map",
        "kind": "refactor",
        "data": {
            "id": "refactor-change-coll",
            "uri": "file:///Users/brandon/development/clojure-test/src/core.clj",
            "line": 3,
            "character": 5,
            "coll": "map"
        }
    },
    {
        "title": "Change coll to vector",
        "kind": "refactor",
        "data": {
            "id": "refactor-change-coll",
            "uri": "file:///Users/brandon/development/clojure-test/src/core.clj",
            "line": 3,
            "character": 5,
            "coll": "vector"
        }
    },
    {
        "title": "Change coll to set",
        "kind": "refactor",
        "data": {
            "id": "refactor-change-coll",
            "uri": "file:///Users/brandon/development/clojure-test/src/core.clj",
            "line": 3,
            "character": 5,
            "coll": "set"
        }
    },
    {
        "title": "Cycle privacy",
        "kind": "refactor.rewrite",
        "data": {
            "id": "refactor-cycle-privacy",
            "uri": "file:///Users/brandon/development/clojure-test/src/core.clj",
            "line": 3,
            "character": 5
        }
    },
    {
        "title": "Extract function",
        "kind": "refactor.extract",
        "data": {
            "id": "refactor-extract-function",
            "uri": "file:///Users/brandon/development/clojure-test/src/core.clj",
            "line": 3,
            "character": 5
        }
    },
    {
        "title": "Clean namespace",
        "kind": "source.organizeImports",
        "data": {
            "id": "clean-ns",
            "uri": "file:///Users/brandon/development/clojure-test/src/core.clj",
            "line": 3,
            "character": 5
        }
    }
]


[Trace - 8:15:33 PM] Sending request 'codeAction/resolve - (8)'.
Params: {
    "title": "Cycle privacy",
    "data": {
        "id": "refactor-cycle-privacy",
        "uri": "file:///Users/brandon/development/clojure-test/src/core.clj",
        "line": 3,
        "character": 5
    },
    "kind": "refactor.rewrite"
}


[Trace - 8:15:33 PM] Received response 'codeAction/resolve - (8)' in 11ms.
Result: {
    "title": "Cycle privacy",
    "kind": "refactor.rewrite",
    "command": {
        "title": "Cycle privacy",
        "command": "cycle-privacy",
        "arguments": [
            "file:///Users/brandon/development/clojure-test/src/core.clj",
            3,
            5
        ]
    }
}


[Trace - 8:15:33 PM] Sending request 'workspace/executeCommand - (9)'.
Params: {
    "command": "cycle-privacy",
    "arguments": [
        "file:///Users/brandon/development/clojure-test/src/core.clj",
        3,
        5
    ]
}
```

**Comment by dbaeumer** [comment]
As said VS Code doesn't support filling in a command in a resolve request. Only the edit property can be set in a resolve request. Reason is that a command is already somehow lazy and not hard to compute. A full edit tree however is. This is why only this property of a Code action can be added in a resolve request: https://github.com/microsoft/vscode-languageserver-node/blob/1fe84c5b656d9db07f812cb573d2c0d82f9d8366/types/src/main.ts#L3091 The command property https://github.com/microsoft/vscode-languageserver-node/blob/1fe84c5b656d9db07f812cb573d2c0d82f9d8366/types/src/main.ts#L3098 CAN'T be filled in in a resolve request.

**Comment by bpringe** [comment]
Thanks for the clarification!
