### ISSUE TITLE
How to move custom language server `CompletionItem`s to top of suggestion list?

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/vscode-languageserver-node#868]
Using https://github.com/Microsoft/vscode-extension-samples/tree/main/completions-sample as a template, I created some custom `CompletionItem`s as an extension of JavaScript.

However, these custom `CompletionItem`s show up last in the suggestions dropdown. How do I move them to the top?

Setting `item.sortText = 'A';` in `connection.onCompletionResolve( (item: CompletionItem): CompletionItem => {` doesn't seem to push my custom `CompletionItem`s to the top of the suggestions list.

https://user-images.githubusercontent.com/43425812/144787820-03894eb3-2a7a-4ff8-898e-1aa28929256b.mov

**Comment by dbaeumer** [comment]
There is no way that servers can control this. The reason is that every extensions thinks that its completion item will be the most important once. A server can only control the sorting for his own items.

VS Code has some ways to control this, but only on the general provider level. It mostly depends on the document selector passed in when registering the completion provider. I assume that in your example you didn't specify a `language` in the document selector hence VS Code thinks these items are of less importance than the items contributed for the `javascript` language. See https://code.visualstudio.com/api/references/document-selector for more information.

**Comment by hamirmahal** [comment]
> There is no way that servers can control this. The reason is that every extensions thinks that its completion item will be the most important once. A server can only control the sorting for his own items.
>
> VS Code has some ways to control this, but only on the general provider level. It mostly depends on the document selector passed in when registering the completion provider. 

I understand. I think we will try to adjust settings in `extension.ts`, then, because we really want our language's suggestions to show up at the top of the list, and not all the way at the bottom.

> I assume that in your example you didn't specify a language in the document selector hence VS Code thinks these items are of less importance than the items contributed for the javascript language.

@dbaeumer Actually, the first parameter I passed to `vscode.languages.registerCompletionItemProvider(` is `'javascript'`. Is that what you're referring to?

We get the same behavior regardless of whether we make the first parameter to `vscode.languages.registerCompletionItemProvider(` be `'javascript'` or

```
{
	scheme: 'file',
	language: 'javascript'
}
```

Our full example `extension.ts` file is

```
/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/

import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	const selector: vscode.DocumentSelector = {
		scheme: 'file',
		language: 'javascript'
	};
	const provider2 = vscode.languages.registerCompletionItemProvider(
		'javascript',
		{
			provideCompletionItems(
				document: vscode.TextDocument,
				position: vscode.Position
			) {
				// get all text until the `position` and check if it reads `console.`
				// and if so then complete if `log`, `warn`, and `error`
				const linePrefix = document.lineAt(position).text.substr(0, position.character);
				console.log(
					'linePrefix',
					linePrefix,
					new Date().toLocaleTimeString()
				);
				if (!linePrefix.endsWith('console.')) {
					return undefined;
				}

				return [
					new vscode.CompletionItem('this should be at the top of the list, not near the bottom', vscode.CompletionItemKind.Method),
					new vscode.CompletionItem('this should be closer to the top', vscode.CompletionItemKind.Method),
					new vscode.CompletionItem('this should not be at the bottom of the list', vscode.CompletionItemKind.Method),
				];
			}
		},
		'.' // triggered whenever a '.' is being typed
	);

	context.subscriptions.push(provider2);
}
```

It's very similar to [`completions-sample/src/extension.ts`](https://github.com/microsoft/vscode-extension-samples/blob/main/completions-sample/src/extension.ts).

https://user-images.githubusercontent.com/43425812/144938520-6e725a04-e65c-49f1-a7cd-a192b490bd41.mov

**Comment by dbaeumer** [comment]
Yes, you are passing the `javascript` selector which is correct. Since the other items come from a provider for `javascript` as well it is up to VS Code to decide which one it takes first. To my knowledge there is not way you can influence this. As said it is by design in VS Code since otherwise everyone would fight about being at the top.

**Comment by hamirmahal** [comment]
Ah, I see. I notice that our language's keywords even show up after all the `abc` suggestions, i.e., the order seems to be

1. JavaScript keywords
2. All the words in the source file
3. Our language's keywords

I understand that we can't move our language's keywords into the 1 position, but can we maybe at least move it into the 2 position, above all the words in the source file, @dbaeumer? It would be nice if developers didn't have to scroll down past every word in the file before arriving at our language's keywords.

https://user-images.githubusercontent.com/43425812/145081425-e2573b7e-4638-4977-b090-0a85ec481aba.mov

We made our language very similar to JavaScript, by design, so that it's more familiar to new developers. I think we want to keep letting VSCode auto-detect our source files as JavaScript, since we get a lot of nice functionality like variable renaming that way, but it would be nice if we could layer features specific to our language on top of JavaScript's language server, and do things like give priority to our language's keywords in the `CompletionItem` suggestions dropdown list.

**Comment by dbaeumer** [comment]
All I can recommend is to open a request against VS Code itself since this is not under the control of the LSP libraray.

**Comment by hamirmahal** [comment]
Okay, I appreciate the information. Thank you for your responses!
