### ISSUE TITLE
language client's output channel is not removed when stopping/disposing

### ISSUE THREAD

**Issue by nadako** [Microsoft/vscode-languageserver-node#87]
I'm not sure if it's a bug or not, but I was expecting LanguageClient's `outputChannel` to be removed with I call `dispose` on whatever's returned by the `start()` method.

**Comment by nadako** [comment]
BTW, I tried manually disposing `client.outputChannel`, but it still shows in the output panel (tho that's probably a vscode issue).

**Comment by dbaeumer** [comment]
Agree.
