### ISSUE TITLE
languageclient: add API to register specific feature in proposed state

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-languageserver-node#873]
### Use case

To collect feedbacks about the proposed type hierarchy feature, we want to build a private version of VS Code Java extension, then we can deliver it to more users (e.g. via [pre-release extensions](https://code.visualstudio.com/updates/v1_63#_pre-release-extensions)).

### Problem

Currently I enable it via this API, which in fact enables **all** proposed features.
https://github.com/microsoft/vscode-languageserver-node/blob/2020cb4254abe91de1749cecad8283d397eea0b7/client/src/common/commonClient.ts#L28-L30

The proposed "diagnostic" feature requires to enable API proposal "tab" in vscode. So I cannot make a private build which can run on vscode stable versions. And I probably cannot publish it as a pre-release extension either.

### Expectation

Can enable specific features instead of all of them. Maybe to add corresponding API for each proposed feature?

**Comment by Eskibear** [comment]
Looks like I can use `client.registerFeature` to specifically register it. 
```
languageClient.registerFeature(new TypeHierarchyFeature(languageClient));
```

**Comment by dbaeumer** [comment]
Correct.
