### ISSUE TITLE
[Uncaught errors] Message header must separate key and value using  

### ISSUE THREAD

**Issue by XuMingxing** [microsoft/vscode-languageserver-node#874]
When I open vscode to edit code, I would find there are some uncaught errors in the c/c++ extension. How can I  get better logging for what the malformed json message is.

![image](https://user-images.githubusercontent.com/29743580/146854521-b3465b97-b958-4c4f-af97-3fad06e23266.png)

**Comment by dbaeumer** [comment]
Please report the issue against the owner of the extension. This repository doesn't provide any C++ features.

**Comment by sean-mcmanus** [comment]
@dbaeumer Our team doesn't know what could be causing this. We were hoping you might have a better idea what could cause the error and/or how to get more diagnostics. It looks like the vscode-jsonrpc API is receiving an invalid header.

**Comment by dbaeumer** [comment]
You can enable tracing which should print the JSON-RPC traffic between VS code and the server to the server's output channel. The name of the channel is the name you provided when creating the client.

**Comment by sean-mcmanus** [comment]
@dbaeumer Cool, thanks for the info - I got the trace logging enabled (i.e. `"cpptools.trace.server":"verbose"`)

**Comment by sean-mcmanus** [comment]
@dbaeumer The user provided logging at https://github.com/microsoft/vscode-cpptools/files/7804850/cpptools.json.txt, but I don't see anything unusual that could cause the "Message header must separate key and value using :" error. It appears to be properly formatted json (excluded the root Params, but I assume that's just due to how it's being logged).

**Comment by dbaeumer** [comment]
Yes, that trace looks fine and complete. All I can recommend is to debug it. The code were the exception is thrown is here: https://github.com/microsoft/vscode-languageserver-node/blob/244baa3983a7760a043ab90d84e3373e6676d175/jsonrpc/src/common/messageBuffer.ts#L103

Best it to set a breakpoint to see why a header with an incorrect key value separation is received.

**Comment by hacke2** [comment]
Can we add try catch in this line:

https://github.com/microsoft/vscode-languageserver-node/blob/ca74870b194b533a5da52c3eb8ef02ab8edb6319/jsonrpc/src/common/messageReader.ts#L214

**Comment by dbaeumer** [comment]
Will not help since there is no way I can recover from such an error.
