### ISSUE TITLE
Is the capabilities of the server side can be set or modified after the iInitialization. For example : callHierarchyProvider property is set to false when some condition is not  provided.

### ISSUE THREAD

**Issue by xg-github-00** [microsoft/vscode-languageserver-node#875]
@dbaeumer   please help to check, thanks~

**Comment by dbaeumer** [comment]
You can use dynamic registration which allows to register and un-register a provider. See https://microsoft.github.io/language-server-protocol/specifications/specification-current/#client_registerCapability
