### ISSUE TITLE
Ignoring certain files in the workspace

### ISSUE THREAD

**Issue by shadycuz** [microsoft/vscode-languageserver-node#876]
My extension activates on `groovy` files in the workspace. This is sometimes a problem for the language server because of duplicate filenames and class/function definitions. See https://github.com/DontShaveTheYak/groovy-guru/issues/25. 

I'm trying to figure out how I would ignore a folder or file. Is this functionality built into the node client? Is it a part of the protocol for the server? Or is this custom functionality that I need to build into the server?  

I have tried searching the issues in this repo and I did not find anything. I then tried google and only found documentSelector, which doesn't seem like the right thing.

Thanks,
Levi

**Comment by shadycuz** [comment]
Judging by how java LSP did it, it will need to be implemented server side? 

https://github.com/redhat-developer/vscode-java/blob/247b7db39dfd1e70e9b87d71f034479d5645f9cf/src/utils.ts

**Comment by dbaeumer** [comment]
Two solutions:

- server side
- VS Code client side using a custom middleware layer. https://github.com/microsoft/vscode-languageserver-node/blob/756cf416e98bc9ce843416cf1c03881ddd1ef322/client/src/common/client.ts#L513

**Comment by shadycuz** [comment]
@dbaeumer 

I still have never been able to implement this 😞 

Here is what I got: 

```typescript
let clientOptions: LanguageClientOptions = {
          documentSelector: [{ scheme: "file", language: "groovy" }],
          synchronize: {
            configurationSection: "groovy",
          },
          middleware: {
            workspace: {
              didChangeWatchedFile: async (event: FileEvent, next: DidChangeWatchedFileSignature) => {
                let channel = vscode.window.createOutputChannel('Groovy Guru Client');
                console.log('Hello')
                console.debug('Hello?')
                channel.appendLine(`Event: ${event.type} on ${event.uri}`)
                channel.appendLine(`File ${next.name}`)

                return next(event)
              }
            }
          },
```

Unfortunately nothing gets logged when running my extension. Maybe I choose the wrong middleware, but I expected my middleware to be triggered every time I changed a file in the workspace.

**Comment by shadycuz** [comment]
I will open  new issue
