### ISSUE TITLE
Questions about how syntax highlighting works?

### ISSUE THREAD

**Issue by Hebe970217** [microsoft/vscode-languageserver-node#877]
I support token in the initialization request, and the returned field contains: "documentHighlightProvider": true,
But I try to use textdocument / documenthighlight, It returns no array result.
So I want to know how it works.
Thank you all for your answers.

**Comment by Hebe970217** [comment]
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "initialize",
    "params": {
        "capabilities": {
            "textDocument": {
                "codeAction": {
                    "codeActionLiteralSupport": {
                        "codeActionKind": {
                            "valueSet": []
                        }
                    }
                },
                "documentSymbol": {
                    "hierarchicalDocumentSymbolSupport": true
                },
                "publishDiagnostics": {
                    "relatedInformation": true
                },
                "semanticTokens": {
                    "formats": [
                        "relative"
                    ],
                    "requests": {
                        "full": {
                            "delta": true
                        },
                        "range": true
                    },
                    "tokenModifiers": [],
                    "tokenTypes": [
                        "namespace",
                        "type",
                        "class",
                        "enum",
                        "interface",
                        "struct",
                        "typeParameter",
                        "parameter",
                        "variable",
                        "property",
                        "enumMember",
                        "event",
                        "function",
                        "method",
                        "macro",
                        "keyword",
                        "modifier",
                        "comment",
                        "string",
                        "number",
                        "regexp",
                        "operator"
                    ]
                }
            },
            "workspace": {
                "workspaceFolders": true
            }
        },
        "processId": 15739,
        "rootPath": "/home/funning",
        "rootUri": "file:///home/funning",
        "workspaceFolders": []
    }
}

{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "capabilities": {
            "astProvider": true,
            "callHierarchyProvider": true,
            "codeActionProvider": {
                "codeActionKinds": [
                    "quickfix",
                    "refactor",
                    "info"
                ]
            },
            "compilationDatabase": {
                "automaticReload": true
            },
            "completionProvider": {
                "allCommitCharacters": [
                    " ",
                    "\t",
                    "(",
                    ")",
                    "[",
                    "]",
                    "{",
                    "}",
                    "<",
                    ">",
                    ":",
                    ";",
                    ",",
                    "+",
                    "-",
                    "/",
                    "*",
                    "%",
                    "^",
                    "&",
                    "#",
                    "?",
                    ".",
                    "=",
                    "\"",
                    "'",
                    "|"
                ],
                "resolveProvider": false,
                "triggerCharacters": [
                    ".",
                    "<",
                    ">",
                    ":",
                    "\"",
                    "/"
                ]
            },
            "declarationProvider": true,
            "definitionProvider": true,
            "documentFormattingProvider": true,
            "documentHighlightProvider": true,
            "documentLinkProvider": {
                "resolveProvider": false
            },
            "documentOnTypeFormattingProvider": {
                "firstTriggerCharacter": "\n",
                "moreTriggerCharacter": []
            },
            "documentRangeFormattingProvider": true,
            "documentSymbolProvider": true,
            "executeCommandProvider": {
                "commands": [
                    "clangd.applyFix",
                    "clangd.applyTweak"
                ]
            },
            "hoverProvider": true,
            "implementationProvider": true,
            "memoryUsageProvider": true,
            "referencesProvider": true,
            "renameProvider": true,
            "selectionRangeProvider": true,
            "semanticTokensProvider": {
                "full": {
                    "delta": true
                },
                "legend": {
                    "tokenModifiers": [
                        "declaration",
                        "deprecated",
                        "deduced",
                        "readonly",
                        "static",
                        "abstract",
                        "dependentName",
                        "defaultLibrary",
                        "functionScope",
                        "classScope",
                        "fileScope",
                        "globalScope"
                    ],
                    "tokenTypes": [
                        "variable",
                        "variable",
                        "parameter",
                        "function",
                        "method",
                        "function",
                        "property",
                        "variable",
                        "class",
                        "interface",
                        "enum",
                        "enumMember",
                        "type",
                        "type",
                        "unknown",
                        "namespace",
                        "typeParameter",
                        "concept",
                        "type",
                        "macro",
                        "comment"
                    ]
                },
                "range": false
            },
            "signatureHelpProvider": {
                "triggerCharacters": [
                    "(",
                    ","
                ]
            },
            "textDocumentSync": {
                "change": 2,
                "openClose": true,
                "save": true
            },
            "typeHierarchyProvider": true,
            "workspaceSymbolProvider": true
        },
        "serverInfo": {
            "name": "clangd",
            "version": "Ubuntu clangd version 13.0.0-2 linux x86_64-pc-linux-gnu"
        }
    }
}

**Comment by rcjsuen** [comment]
@Hebe970217 I don't understand your question at all.

Please describe in detail what you are doing, what you see, and what you expected to see. Please also provide your code and some screenshots to show the strange and/or incorrect behaviour.

**Comment by dbaeumer** [comment]
LSP has no support for syntax highlighting since this is usually something that is already built into the editor / tool and each editor uses a different machanism.

LSP does have support for sematic highlighting which could be used for syntax highlighting as well, but this is not recommended since it has bad user experience in a remote setup.

The document highlight request is for `mark occurences` and not for syntax coloring.

**Comment by Hebe970217** [comment]
3q
