### ISSUE TITLE
"Error [ERR_STREAM_WRITE_AFTER_END]: write after end" when the test takes a few more time

### ISSUE THREAD

**Issue by macabeus** [microsoft/vscode-languageserver-node#878]
I'm developing a library to run vscode extension tests using Jest ([`jest-environment-vscode`](https://github.com/macabeus/jest-environment-vscode-extension)), and updating the extension [`vscode-ocaml-platform`](https://github.com/ocamllabs/vscode-ocaml-platform) to use the library.
The extension is using `vscode-languageclient` at the version `7.0.0`.

I notice that the tests work well _if_ it takes a short time.
For example:
```js
it("shows the parameters and return types", () => {
  return using(
    {
      files: {
        "main.ml": 'let hello () = print_endline "hey there"',
      },
      mocks: {
        "window.showQuickPick": jest
          .fn()
          .mockImplementation(async (items) => {
            return items.find(({ label }) => label === "default");
          }),
      },
    },
    async (mapFileToUri) => {
      await commands.executeCommand("ocaml.select-sandbox");

      const hovers = await waitForHovers(
        mapFileToUri["main.ml"],
        new Position(0, 5)
      );

      expect(hovers).toEqual(["```ocaml\nunit -> unit\n```"]);

      // wait 2 seconds
      await wait(2_000)
    }
  );
});
```

By removing the `await wait(2_000)`, the test always works. But if we add it, the test fails with the following error:
```
  ● #Hover › on a function declaration › shows the parameters and return types

    Error [ERR_STREAM_WRITE_AFTER_END]: write after end

      20 |     };
      21 |     var step = (x2) => x2.done ? resolve(x2.value) : Promise.resolve(x2.value).then(fulfilled, rejected);
    > 22 |     step((generator = generator.apply(__this, __arguments)).next());
         |                                                             ^
      23 |   });
      24 | };
      25 |

      at node_modules/vscode-jsonrpc/lib/node/ril.js:90:29
      at WritableStreamWrapper.write (node_modules/vscode-jsonrpc/lib/node/ril.js:80:16)
      at StreamMessageWriter.<anonymous> (node_modules/vscode-jsonrpc/lib/common/messageWriter.js:100:33)
      at dist/vscode_ocaml_platform.bc.js:22:61
      at __async (dist/vscode_ocaml_platform.bc.js:6:10)
      at StreamMessageWriter.doWrite (node_modules/vscode-jsonrpc/lib/common/messageWriter.js:98:39)
      at node_modules/vscode-jsonrpc/lib/common/messageWriter.js:91:29
```

By the stack trace, I guess this isn't an extension error, but an error on `vscode-jsonrpc`.

### How to reproduce

1 - `git clone git@github.com:macabeus/vscode-ocaml-platform.git`
2 - `git checkout  vscode-jsonrpc-bug`
3 - install OCaml and [`ocaml-lsp-server`](https://github.com/ocaml/ocaml-lsp)
4 - on terminal, run `yarn test:ci:with-workspace`

**Comment by dbaeumer** [comment]
This got fixed in the 8.x-next version of the module. Reason for the failure is that not all processing was awaited correctly. However to make it work notification return a promise now as well and you might need to await them. See https://github.com/microsoft/vscode-languageserver-node/blob/f16ca298dac93a99b2338129a2149a0ada9021dc/README.md#L41

Not sure if it is helpful but the language client allows you to access feature and directly talk to the server. This is helpful to write tests.

**Comment by macabeus** [comment]
@dbaeumer Thanks for the quick feedback!

> Not sure if it is helpful but the language client allows you to access feature and directly talk to the server. This is helpful to write tests.

Do you have an example? I could try to send a message telling them to finish all the process. Or check if all process was finished.

**Comment by dbaeumer** [comment]
Here is an example: https://github.dev/microsoft/vscode-languageserver-node/blob/2020cb4254abe91de1749cecad8283d397eea0b7/client-node-tests/src/integration.test.ts#L229
