### ISSUE TITLE
Return promise from server Connection.sendNotification

### ISSUE THREAD

**Issue by mroch** [microsoft/vscode-languageserver-node#884]
as of #776 and 092c2afc3ad7e4d2b03fe8ac0deb418ec4276915, jsonrpc and client's `sendNotification` returns `Promise<void>`. but the server's types are still just `void`.

https://github.com/microsoft/vscode-languageserver-node/blob/23474b0adb70a23ab390e79d210a5ad0a0bde75d/server/src/common/server.ts#L1165-L1182

if i'm understanding correctly, the implementation returns a promise already:

https://github.com/microsoft/vscode-languageserver-node/blob/23474b0adb70a23ab390e79d210a5ad0a0bde75d/server/src/common/server.ts#L1699

I think the `sendDiagnostics` type should also return a Promise, as its implementation does

https://github.com/microsoft/vscode-languageserver-node/blob/23474b0adb70a23ab390e79d210a5ad0a0bde75d/server/src/common/server.ts#L1340
https://github.com/microsoft/vscode-languageserver-node/blob/23474b0adb70a23ab390e79d210a5ad0a0bde75d/server/src/common/server.ts#L1737

**Comment by dbaeumer** [comment]
@mroch very good catch. That slipped. Will fix it before we release the next stable.
