### ISSUE TITLE
"TypeError: Cannot read property 'then' of undefined" using 8.0.0-next.12 with latest VS Code stable

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode-languageserver-node#893]
@dbaeumer I'm not sure whether this is expected to work yet (using 8.0.0-next.12 from npm with the newly published VS Code stable), but I'm seeing this issue when my server calls `showMessage`:

```
[12:39:38 PM] [CI] [Error] TypeError: Cannot read property 'then' of undefined
    at LanguageClient.showNotificationMessage ([/Users/danny/Dev/Dart-Code/node_modules/vscode-languageclient/lib/common/client.js:2256:1]())
    at LanguageClient.error ([/Users/danny/Dev/Dart-Code/node_modules/vscode-languageclient/lib/common/client.js:2246:1]())
    at LanguageClient.handleFailedRequest ([/Users/danny/Dev/Dart-Code/node_modules/vscode-languageclient/lib/common/client.js:2948:1]())
    at [/Users/danny/Dev/Dart-Code/node_modules/vscode-languageclient/lib/common/client.js:1917:1]()
```

If I put a breakpoint, it seems that the call to `messageFunc` is returning `undefined` but a `Promise` is assumed (it's taking the error path):

<img width="872" alt="Screenshot 2022-02-07 at 12 39 29" src="https://user-images.githubusercontent.com/1078012/152790085-abf5f374-490b-4e6f-8c75-f36a15572a59.png">

(why showMessage is being called here with an error is another issue I need to investigate, but this feels like an issue on its own).

**Comment by DanTup** [comment]
I think this might be related to Sinon. I'm using it to stub `vs.window.showInputBox` and it seems that all calls to `vs.window.xxx` go through its proxy. I'm not sure why it's doing this only when using the new version of this library though (the test works fine with the current published version), but I'll do some more digging.

I'll re-open this if it seems like there is something wrong here, and it's not just that some change has triggered different behaviour in Sinon.

**Comment by dbaeumer** [comment]
Let me know what the outcome is. The `messageFunc` should point to existing VS Code API.

**Comment by DanTup** [comment]
Will do! Is there any easy existing way to run a completely in-memory language server to make a simpler repro to debug?

**Comment by DanTup** [comment]
Oh, I figured it out, and it's entirely my fault :-)

I was also stubbing `vs.window.showErrorMessage` in one of the tests, but I never bothered to return a promise from it (since the test only verifies it was called). The older version of this lib didn't call `.then()` on it so it never failed when it was given a non-Promise, but the new version does.

The fix is simple - my test that stubs this method should return a promise as the VS Code API specifies.

Sorry for the noise!

**Comment by dbaeumer** [comment]
No problem.

**Comment by DanTup** [comment]
@dbaeumer I resolved the issue, although there's a difference in behaviour I'm uncertain about. My test previously asserted that `window.showErrorMessage` would be called once, but now it's called twice:

```
Request workspace/executeCommand failed.
Method name must not contain '"'.
```

We have some middleware that's already handling failed these failed calls to `executeCommand` for refactors here:

https://github.com/Dart-Code/Dart-Code/blob/3c7ff14939bb366e04c0b6db5e0c9d8151653f35/src/extension/analysis/analyzer_lsp.ts#L226-L238

Is it reasonable for us to handle our own errors in this way? (If so, can we opt out of this extra message)? We could change the command to return this data in a more structured way, but this seemed like a reasonable option when I did it (and there will be some lead time in getting server changes out to not reject in this way).

**Comment by DanTup** [comment]
Actually, this has always been this way - but before it was just an Information message and the test missed it. Most of the errors handled by this are actually prevented earlier by validation before we send the request, so I'll just amend the test to handle it. There is no regression here (only a change in the severity of the error message shown by the LSP client).

(Sorry for another misfire 😬)
