### ISSUE TITLE
document selector is just strings

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode-languageserver-node#9]
I can't register for a pattern etc

**Comment by BoykoAlex** [comment]
I'm trying to add language server support for various flavours of YAML files: Spring Boot application properties YAML, Cloud Foundry application deployment manifest YAML etc. Each of these different flavours of YAML should get its own validation/reconciling, content assist, hovers etc.
The only way to accomplish this is pass `documentSelector` parameter with `DocumentFilter` object that has a `pattern` property such that i can at least provide differrent YAML support for different YAML file names. `LanguageClientOptions` only accepts `string|string[]` :-(
Should be relatively straight-forward to make `LanguageClient` support `documentSelector` with `DocumentFilter` values... In fact all features are supported already except for doc changes synchronization code.
Any chance this can be fixed soon?

**Comment by dbaeumer** [comment]
A started to work on this in master.

**Comment by dbaeumer** [comment]
This got addressed in 3.0.x
