### ISSUE TITLE
Issue with orphaned dotnet process after exit.

### ISSUE THREAD

**Issue by bobbytreed** [microsoft/vscode-languageserver-node#900]
This might be a duplicate of #726, but for me it's not resolved.  When I just kill vscode by closing the window when debugging the extension, I notice a dotnet.exe process still hanging around.  When I attach back to it, I can see that it's not still in any of my code.  

I do implement a ShutdownHandler to ensure that everything is cleaned up, and I also have code in the deactivation event to wait for client.stop, but I want to figure out how to ensure that dotnet process is not hanging around.

I'm on version 7 of the language server.

Thanks in advance.

Note: I'm on EST, so my responses will be delayed until tomorrow.

Cheers

**Comment by dbaeumer** [comment]
The process ID is also provided in the initialize request to the server. However only reacting to that might be too late since VS Code might crash before sending the initialize request.
