### ISSUE TITLE
Use language client in a CLI App

### ISSUE THREAD

**Issue by kushal-ti** [microsoft/vscode-languageserver-node#901]
I'm trying to use the language client as a simple CLI app. I have a laguage server already running and want to connect to it using the (CLI) client which will run a set of default commands and save the response to a file. All the documentation and examples i found use the client as a vscode extension, which is not really an option for me (the CLI app ultimately has to run on a remote server.

I tried going through the lsp-sample example in https://code.visualstudio.com/api/language-extensions/language-server-extension-guide
and just calling the client ued in that example in a normal node.js file, but it gave me the following error 

    
     Error: Cannot find module 'vscode'

     Require stack:

    - {workspace}/LSP/Trial/node_modules/vscode-languageclient/lib/node/main.js

    - {workspace}/LSP/Trial/node_modules/vscode-languageclient/node.js

    - {workspace}/LSP/Trial/src/client.ts

is there any way i can use the client as a standalone app and if not, is there any other implementation of language server client as that can be used as such?

**Comment by dbaeumer** [comment]
This is not working since the language client depends on type from VS Code. What does work in a CLI app is the `vscode-languageserver-protocol` since it only depends on node types.

**Comment by vladfaust** [comment]
I'm constantly getting 

```
!MESSAGE Errors running builder 'Java Builder' on project 'player'.
!STACK 0
org.eclipse.jdt.internal.core.builder.AbortIncrementalBuildException
	at org.eclipse.jdt.internal.core.builder.NameEnvironment.findClass(NameEnvironment.java:574)
	at org.eclipse.jdt.internal.core.builder.NameEnvironment.findType(NameEnvironment.java:654)
        ...
```

After `{"jsonrpc":"2.0","method":"language/status","params":{"type":"Started","message":"Ready"}}` messages if using `vscode-jsonrpc` instead of a home-grown JSON RPC implementation adapted from https://github.com/ImperiumMaximus/ts-lsp-client.

I wonder what's the difference and how an LSP may fail depending on the JSON RPC implementation. 😕
