### ISSUE TITLE
vscode-jsonrpc throwing ReferenceError: setImmediate is not defined

### ISSUE THREAD

**Issue by osortega** [microsoft/vscode-languageserver-node#904]
The error gets thrown when using this vscode-jsonrpc in a web client.

Looks like `setImmediate` is not a [standard function](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate#browser_compatibility) and is not supported by the majority of browsers.

Is it possible to change those calls to `setTimeout(()=>(),0)` or something similar?

**Comment by dbaeumer** [comment]
You need to use the browser entry point for the Web which doesn't use setImmediate. See https://github.com/microsoft/vscode-languageserver-node/blob/292dd0d88b6465337e42ba40ad986fdfdeb42d4d/jsonrpc/src/browser/ril.ts#L166

**Comment by dbaeumer** [comment]
And https://github.com/microsoft/vscode-languageserver-node/blob/292dd0d88b6465337e42ba40ad986fdfdeb42d4d/jsonrpc/browser.js
