### ISSUE TITLE
What is the destination IP and port number of the language server protocol?

### ISSUE THREAD

**Issue by ymdymdymd** [microsoft/vscode-languageserver-node#907]
What is the destination IP and port number of the language server protocol?

**Comment by dbaeumer** [comment]
No predefined since the client is starting and managing a LS it is under the clients control to determine them.

**Comment by ymdymdymd** [comment]
thank you.Please let me check.
Since the language server protocol has a language server inside VS Code and is completed inside the client terminal, isn't it necessary to go through a proxy?
Does that mean that you don't need to drill holes in the proxy?

**Comment by ymdymdymd** [comment]
I'm sorry. It was listed here.
