### ISSUE TITLE
Example in vscode-jsonrpc README not working 

### ISSUE THREAD

**Issue by aduerig** [microsoft/vscode-languageserver-node#909]
1. `npm install vscode-jsonrpc`

2. Copied this code into `server.ts` from the README.md exactly:
```
import * as rpc from 'vscode-jsonrpc';


let connection = rpc.createMessageConnection(
	new rpc.StreamMessageReader(process.stdin),
	new rpc.StreamMessageWriter(process.stdout));

let notification = new rpc.NotificationType<string, void>('testNotification');
connection.onNotification(notification, (param: string) => {
	console.log(param); // This prints Hello World
});

connection.listen();
```

3. Run with `ts-node server.ts`

4. I get this error:
```
(3) attempt_vscode_rpc_again$ ts-node server.ts                                     
/REDACTED_PATH/node/14.18.2_64bit/lib/node_modules/ts-node/src/index.ts:820
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
server.ts:5:10 - error TS2551: Property 'StreamMessageReader' does not exist on type 'typeof import("/REDACTED_PATH/node_modules/vscode-jsonrpc/lib/common/api")'. Did you mean 'AbstractMessageReader'?

5  new rpc.StreamMessageReader(process.stdin),
           ~~~~~~~~~~~~~~~~~~~
server.ts:6:10 - error TS2551: Property 'StreamMessageWriter' does not exist on type 'typeof import("/REDACTED_PATH/node_modules/vscode-jsonrpc/lib/common/api")'. Did you mean 'AbstractMessageWriter'?

6  new rpc.StreamMessageWriter(process.stdout));
           ~~~~~~~~~~~~~~~~~~~
server.ts:8:45 - error TS2558: Expected 1 type arguments, but got 2.
```

**Comment by dbaeumer** [comment]
I already fixed this (see https://github.com/microsoft/vscode-languageserver-node/blob/d5334e8a5882fbd9c9ff4935a96f8bab7fe51b00/jsonrpc/README.md#L13)

The correct import is

```ts
import * as rpc from 'vscode-jsonrpc/node';
``

**Comment by aduerig** [comment]
It's not fixed in the example server code, it's only fixed in example client code. Look at [the second code block in the README from the master branch](https://github.com/microsoft/vscode-languageserver-node/blob/main/jsonrpc/README.md).

Fixing the import does make the code run, thanks.

**Comment by dbaeumer** [comment]
Thanks fixed it as well.

**Comment by vladfaust** [comment]
`Cannot find module 'vscode-jsonrpc/node' or its corresponding type declarations.`, `StreamMessageReader` does not exist in `"vscode-jsonrpc"`.

@

```json
"vscode-jsonrpc": "^8.2.1",
```

**Comment by median-dxz** [comment]
> `Cannot find module 'vscode-jsonrpc/node' or its corresponding type declarations.`, `StreamMessageReader` does not exist in `"vscode-jsonrpc"`.
> 
> "vscode-jsonrpc": "^8.2.1",

@vladfaust

I encountered exactly the same issue when I tried to import `vscode-languageserver-protocol/node` version `3.17.5`. The problem is that the stable releases (`vscode-jsonrpc@8.2.1` and `vscode-languageserver-protocol@3.17.5`) are actually quite old—they were published about a year ago, or even two years ago. The definition of `export` in their `package.json` files is actually incomplete, which causes this problem. You can see more information in this issue: https://github.com/microsoft/vscode-languageserver-node/issues/1144.

So, just use the `next` version of them, like:

```json
"vscode-jsonrpc": "^9.0.0-next.10",
"vscode-languageserver-protocol": "^3.17.6-next.15",
```
