### ISSUE TITLE
unexpected numeric constant in "00~library(data.table)01"

### ISSUE THREAD

**Issue by rrchai** [microsoft/vscode-languageserver-node#914]
I just follow the [instruction](https://code.visualstudio.com/docs/languages/r) and install the `languageserver`, as well as its requirements.

When I hit "cmd + Enter" (mac) on `library(data.table)`,  I get this error:
```
unexpected numeric constant in "00~library(data.table)01"
```

Basically, all lines do not work with similar errors. I am not sure if it is because of languageserver or other settings in vscode.

**Comment by dbaeumer** [comment]
@rrchai this repository is about the language server libraries maintained for VS Code. It is not about a specific language server. Please report the issue to the owner of the extension here: https://github.com/REditorSupport/vscode-R/issues
