### ISSUE TITLE
"Header must provide a Content-Length property" error when there is content length available in the header

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-languageserver-node#917]
This is hard to reproduce, but I occasionally run into this when debugging LSP responses:
![image](https://user-images.githubusercontent.com/3840081/161891407-73aa0af1-b8f9-452f-b17f-a76cdb45834c.png)

**Comment by dbaeumer** [comment]
This looks very much like a broken message sent from the server. A message must look like this:

```
Content-Length: ...\r\n
\r\n
{
	"jsonrpc": "2.0",
	"id": 1,
	"method": "textDocument/didOpen",
	"params": {
		...
	}
}
```

where the header part (including the `\r\n`) is encoded using ascii encoding and the body part is encoded using utf-8. See also: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#baseProtocol

In our example there is either:

- a misconstructed mesage
- or more likely the content length of the previous message was not calculated correctly hence resulting a bad split message.

Please also note that the content length must be caclulated in bytes using utf-8 encoding and not in chacaters.

Let me know if this help.

I am pretty sure that the client receives a message before where the `Content-Length` is not set correctly (I guess in that example too short) and hence the message is not broken up correctly.

**Comment by karthiknadig** [comment]
That sounds about right. Thanks Dirk.
