### ISSUE TITLE
What middleware should be used to ignore duplicate files in the workspace? 

### ISSUE THREAD

**Issue by shadycuz** [microsoft/vscode-languageserver-node#920]
I'm looking for a middleware that will allow me to drop duplicate file in the workspace. For examples files `test.groovy` and `docs/test.groovy`. 

I would like to inspect the file names being sent to the language server and if the file path includes `docs`, I want to drop the request. 

I tried `workspace: { didChangeWatchedFile }` but it was never triggered. `didOpen` seemed to work when I opened files but the duplicate file bug I'm dealing with happens even if the duplicate files are never opened. It seems like the language server processes those files even if they are not open in vscode. 

How can I stop the language server from processing a file even if that file is never opened by the user?

**Comment by dbaeumer** [comment]
@shadycuz you can't use the middleware to do this. This would need to be a feature of the language server (e.g. TypeScript server has a config file to include and exclude files from a project).
