### ISSUE TITLE
Failures in textDocument/documentColor are reported as textDocument/colorPresentation

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode-languageserver-node#923]
Very minor, but confusing.. I noticed that if my server returns an error for the `textDocument/documentColor` request, for ex:

```
1650470714385:Req:{"jsonrpc"::"2.0","id"::2,"method"::"textDocument/documentColor","params"::{"textDocument"::{"uri"::"file::///Users/danny/Desktop/dart_samples/dartcode_3929/bin/dartcode_3929.dart"}}}
1650470714389:Res:{"id"::2,"jsonrpc"::"2.0","error"::{"code"::-32007,"message"::"File is not being analyzed","data"::"fake file"}}
```

The LSP client reports it as `textDocument/colorPresentation`:

```
[Error - 5:05:14 PM] Request textDocument/colorPresentation failed.
  Message: File is not being analyzed
  Code: -32007 
fake file
```

I did look through the code, but couldn't figure out how this was happening though!

**Comment by dbaeumer** [comment]
Bug on my end: https://github.com/microsoft/vscode-languageserver-node/blob/f97bb73dbfb920af4bc8c13ecdcdc16359cdeda6/client/src/common/colorProvider.ts#L83

**Comment by dbaeumer** [comment]
Fixed on branch. Will merge into master today.

**Comment by DanTup** [comment]
Ah, that's where it was - I was looking at the `method` on the protocol class. Thanks!
