### ISSUE TITLE
Getting all files in the workspace

### ISSUE THREAD

**Issue by MetalSlime0** [microsoft/vscode-languageserver-node#928]
It seems to me that my language server needs to have its own code for scanning the workspace folders for relevant files that are necessary to get proper diagnostics in the open files. (As a side note, I'm curious whether this is the wrong approach or how other languages manage this sort of thing. If I'm "doing it wrong" let me know.) On the other hand, there is the `workspace/didChangeWatchedFiles` notification, which is really convenient for determining when those files have changed.

Is there a way to just get the list of files in the workspace (matching a pattern) from the client, instead of writing my own code for it? It is challenging that my server code has to handle different platforms and can't use the same "glob pattern" syntax when searching for files. If this doesn't exist, might I suggest adding an optional "found" event to `didChangeWatchedFiles` that simply reports all of the files matching the pattern when the capability is registered? (I suppose it would also need a "lost" event so it could handle changes to the registered globPattern and/or changes to the workspace folders.)

Sorry if this is the wrong place for a question like this; please let me know if there's somewhere more appropriate.

**Comment by rcjsuen** [comment]
@MetalSlime0 It seems to me that your question is about the language server protocol so your question would be better suited for the [microsoft/language-server-protocol repository](https://github.com/microsoft/language-server-protocol/).

**Comment by MetalSlime0** [comment]
Ah ok, thanks.
