### ISSUE TITLE
Do not point @latest dist tag to prereleases

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode-languageserver-node#94]
The `latest` dist tag is what users get when they `npm install vscode-languageclient`. It should install the stable version, not the prerelease.

https://docs.npmjs.com/cli/dist-tag

> By default, the latest tag is used by npm to identify the current version of a package, and npm install <pkg> (without any @<version> or @<tag> specifier) installs the latest tag. Typically, projects only use the latest tag for stable release versions, and use other tags for unstable versions such as prereleases.
>
> The next tag is used by some projects to identify the upcoming version.

**Comment by dbaeumer** [comment]
It does for me. Am I missing something.

**Comment by felixfbecker** [comment]
Seems like someone fixed it 🙂
I swear a week ago [the badges in the readme](https://github.com/Microsoft/vscode-languageserver-node) all showed the prereleases (in orange)

**Comment by felixfbecker** [comment]
It's here again
```js
  'dist-tags':
   { next: '2.6.0-next.1',
     latest: '3.0.0-alpha.2',
     vnext: '2.0.0-pre.3' },
```
Gemnasium tells me my deps are outdated because of this
[![Dependency Status](https://gemnasium.com/felixfbecker/vscode-php-intellisense.svg)](https://gemnasium.com/felixfbecker/vscode-php-intellisense)

**Comment by dbaeumer** [comment]
Need to see why this is happening.

**Comment by dbaeumer** [comment]
Fixed it. now correctly points to 2.4.0
