### ISSUE TITLE
Breaking change in minor revision

### ISSUE THREAD

**Issue by rchl** [microsoft/vscode-languageserver-node#952]
Hi,

Just wanted to mildly complain that the `3.17.1` version of `vscode-languageserver-protocol` is actually a breaking change relative to the previous `3.16.0` version.

According to semantic versioning it shouldn't be a breaking change but due to it bumping `vscode-jsonrpc` from version  6 to 8, it has caused node version requirements to change from v8 (or so) to v14 and caused https://github.com/typescript-language-server/typescript-language-server/issues/466

We have to move on at some point so requiring node 14 is not necessarily a bad thing but then the parent `vscode-languageserver-protocol` should also get a major version bump. I don't necessarily want this to be addressed now but considered in the future at least when similar situation occurs.

There is also another issue that might actually be actionable for this report. The `vscode-languageserver` dependency, that I'm also using in the same project, has `vscode-languageserver-protocol` pinned to version `3.16.0` so if I upgrade `vscode-languageserver-protocol` to the latest version, my project will end up with two different versions of that library. And that's never a good thing.

**Comment by dbaeumer** [comment]
This is a known problem with how we version the protocol extension and we decided a long time ago to reflect the protocol version number against the specification and not a pure semantic version. 

I agree that this should be documented in the readme though.

**Comment by rchl** [comment]
Thanks for the explanation, it makes sense.
