### ISSUE TITLE
Add deprecated field to the meta model

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-languageserver-node#962]
The documentation states that this is deprecated, it should be a field similar to `since` and `proposed`:
https://github.com/microsoft/vscode-languageserver-node/blob/e4d802f6c3ec826174bc2a801dfdd058940aa554/protocol/metaModel.json#L13977-L13985

expected:
```
 { 
 	"name": "rangeLength", 
 	"type": { 
 		"kind": "base", 
 		"name": "uinteger" 
 	}, 
 	"optional": true, 
 	"documentation": "The optional length of the range that got replaced.\n\n@deprecated use range instead.",
        "deprecated": "use range instead"
 },
```

**Comment by dbaeumer** [comment]
Good point.
