### ISSUE TITLE
signatureInformation documentation property

### ISSUE THREAD

**Issue by RblSb** [microsoft/vscode-languageserver-node#966]
After update of `vscode-languageclient` to `8.0.1`, i found that there is no signature hints in haxe extension for functions without documentation, so `{label: "foo", parameters: "foo", documentation: null}` hint does not show anymore, if you do not change `documentation` to `""` value, or parse actual function comment. But hint should not be skipped with `null` value too, based on spec:
```js
/**
 * The human-readable doc-comment of this signature. Will be shown
 * in the UI but can be omitted.
 */
documentation?: string | MarkupContent;
```

**Comment by dbaeumer** [comment]
Not sure I understand this. `null` was actually not an allowed value for `documentation`. If not documentation is available you can omit the property. 

I will close the issue. Please ping if things are still unclear.
