### ISSUE TITLE
What is the difference between `optional` and `or` base type `null` in the meta model?

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-languageserver-node#967]
For the `documentSelector` property it uses `or`  with  `DocumentSelector` reference type and `null` base type.
```
                {
                    "name": "documentSelector",
                    "type": {
                        "kind": "or",
                        "items": [
                            {
                                "kind": "reference",
                                "name": "DocumentSelector"
                            },
                            {
                                "kind": "base",
                                "name": "null"
                            }
                        ]
                    },
                    "documentation": "A document selector to identify the scope of the registration. If set to null\nthe document selector provided on the client side will be used."
                }
```

Here is an example of a optional property:
```
                {
                    "name": "workDoneProgress",
                    "type": {
                        "kind": "base",
                        "name": "boolean"
                    },
                    "optional": true
                }
```

Why can't documentSelector be:
```
                {
                    "name": "documentSelector",
                    "type": {
                       "kind": "reference",
                       "name": "DocumentSelector"
                    },
                    "documentation": "A document selector to identify the scope of the registration. If set to null\nthe document selector provided on the client side will be used.",
                    "optional": true
                }
```

**Comment by DanTup** [comment]
My understanding is that `null` is an explicit value in the JSON message:

```js
"foo": null
```

Whereas `optional` is whether the key can be omitted entirely. Sometimes an explicit `null` might be treated differently to being omitted. For example, `workspaceFolders` in `InitializeParams` can be `null` if a client supports `workspaceFolders` but there are none open, which is different to it being omitted (client doesn't support `workspaceFolders`).

**Comment by dbaeumer** [comment]
@DanTup thanks for the great answer.

We basically type JSON messages and JSON can't transport a value of undefined. It only supported omitted values. If, in the protocol we want to enforce a value (so that a developer thinks about it) we use `null` as a default value. Since using the clients selector should be the exception a server signals that using the `null` value.
