### ISSUE TITLE
Add LSP version data to the meta model.

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-languageserver-node#984]
The meta model should have a `version` field indicating the version of the LSP

**Comment by dbaeumer** [comment]
Agree.

**Comment by michaelpj** [comment]
Bonus points: change the type of since to `SpecVersion`!

**Comment by dbaeumer** [comment]
IMO since is a well established name for this. And the meta model should always refer to the spec version.

**Comment by michaelpj** [comment]
I meant change the *type* to use the version type rather than a string. That would make it easy for tools to actually use and ensure it's always a version.

**Comment by dbaeumer** [comment]
Sorry, misunderstood. 

Some of the @since tags have additional text info if only a specific aspect got added for a version. So it would require more than simply SpecVersion.

So I am not sure if this is worth the effort

**Comment by michaelpj** [comment]
To give you an idea of where it would be useful: my Haskell library offers users "complete" capability objects for each version of the spec, so you can test with server/client capabilities that advertise "everything". This is currently done fairly manually, but if the introduction version was reliably reported in the metamodel we could probably do it automatically.
