### ISSUE TITLE
request: document how to migrate from breaking change of removing onReady

### ISSUE THREAD

**Issue by a-h** [microsoft/vscode-languageserver-node#985]
In the release notes at https://github.com/microsoft/vscode-languageserver-node#3170-protocol-800-json-rpc-800-client-and-800-server

It says...

> cleanup of client start and stop methods. Both methods now return a promise since these methods are async. This is a breaking change since start returned a disposable before. Extensions should now implement a deactivate function in their extension main file and correctly return the stop promise from the deactivate call. As a consequence the onReady() got removed since extensions can await the start() call (even multiple times).

I have no idea how to do this - an example of code before, and after this change would be useful.

Previously I had this...

```typescript
export async function activate(ctx: vscode.ExtensionContext) {
    try {
        const lc = await buildLanguageClient()
        lc.start()
        await lc.onReady();
    } catch (err) {
        const msg = err && err as Error ? (err as Error).message : 'unknown'
        vscode.window.showErrorMessage(`error initializing templ LSP: ${msg}`);
    }
}
```

What do I need to do now?

I've guessed at:

```typescript
export async function activate(ctx: vscode.ExtensionContext) {
    try {
        const lc = await buildLanguageClient()
        await lc.start()
    } catch (err) {
        const msg = err && err as Error ? (err as Error).message : 'unknown'
        vscode.window.showErrorMessage(`error initializing templ LSP: ${msg}`);
    }
}
```

But there's an implication that I need to do something else.

**Comment by dbaeumer** [comment]
Yes, this is the way to do it. I will add a small example to the readme.

**Comment by a-h** [comment]
Thanks, the comment also says: 

> Extensions should now implement a deactivate function in their extension main file and correctly return the `stop` promise from the deactivate call.

I'm not sure how I'd do this. If I've got something like this...

```
export async function activate(ctx: vscode.ExtensionContext) {
    try {
        const lc = await buildLanguageClient()
        await lc.start()
    } catch (err) {
        const msg = err && err as Error ? (err as Error).message : 'unknown'
        vscode.window.showErrorMessage(`error initializing templ LSP: ${msg}`);
    }
}
```

Would it become:

```
I'm not sure how I'd do this. If I've got something like this...

```
let lc: LanguageClient

export async function activate(ctx: vscode.ExtensionContext) {
    try {
        lc = await buildLanguageClient()
        await lc.start()
    } catch (err) {
        const msg = err && err as Error ? (err as Error).message : 'unknown'
        vscode.window.showErrorMessage(`error initializing templ LSP: ${msg}`);
    }
}

export async function deactivate(): Promise<void> {
    if(lc) {
        return lc.stop()
    } catch (err) {
        const msg = err && err as Error ? (err as Error).message : 'unknown'
        vscode.window.showErrorMessage(`error initializing templ LSP: ${msg}`);
    }
}
```
