### ISSUE TITLE
Failed requests show two error notifications

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode-languageserver-node#990]
If I fail an `executeCommand` request like this:

```
<== {"id":9,"jsonrpc":"2.0","error":{"code":-32008,"data":"/Users/danny/Desktop/dart_sample/test/savetest.dart","message":"Unable to Organize Imports because the file contains parse errors"}}
```

There are two toast notifications shown:

<img width="582" alt="Screenshot 2022-06-07 at 15 37 18" src="https://user-images.githubusercontent.com/1078012/172408030-b6246eeb-9425-4dd1-8d6b-d415109bb61f.png">

Really, I'd prefer only the top one to appear (since it's the message my server provided), however it's not really clear how servers should handle this sort of error (a user error, not a server crash, that prevents a request from being fulfilled). While it's possible for the server to use `showMessage` and then return a successful responses, that's not very good from an API standpoint (eg. if my local extension code is running the command, or middleware is wrapping it, it won't have a clear picture of failed commands).

Is it possible to either opt-out of the "Request xxx failed" message, or have some way that a server can mark a failed request as one that should just show the friendly message to the user, and not something that makes it seem like the server has failed in some way?

@dbaeumer I can't find an existing way to suppress this, but if there is one, please let me know - thanks!

**Comment by dbaeumer** [comment]
@DanTup you can set `revealOutputChannelOn` to never. That should also suppress the dialog.

**Comment by dbaeumer** [comment]
Let me know if it works

**Comment by DanTup** [comment]
Yes, that works great - thanks! 🙂
