### ISSUE TITLE
Some fields have literal type definition with empty property lists.

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-languageserver-node#997]
The following fields have empty literal properties list:
* `SemanticTokensClientCapabilities.range`
* `SemanticTokensOptions.range`

```
"name": "range",
"type": {
    "kind": "or",
    "items": [
        {
            "kind": "base",
            "name": "boolean"
        },
        {
            "kind": "literal",
            "value": {
                "properties": []
            }
        }
    ]
},

```

**Comment by dbaeumer** [comment]
This is expected since the type is defined as follows:

```
	/**
	 * Server supports providing semantic tokens for a specific range
	 * of a document.
	 */
	range?: boolean | {
	};

```

We did this to have a way to extends this. See the corresponding `full` property as an example.

I will close the issue since the meta model mirrors here what is in the specification
