### ISSUE TITLE
Applying WorkspaceEdit that changes many files

### ISSUE THREAD

**Issue by BoykoAlex** [microsoft/vscode-languageserver-node#999]
A WorkspaceEdit that involves changes to 10s or 100s of files results in all these files opened in editors which does seem as an ideal behaviour.

Perhaps with more than 5 files changed it'd make sense to save the changes or save the changes for files that are not opened in the editor... The expected behaviour is unclear...

(cc @martinlippert)

**Comment by martinlippert** [comment]
I think @BoykoAlex means *does NOT seem to be an ideal behavior"... :-)

> A WorkspaceEdit that involves changes to 10s or 100s of files results in all these files opened in editors which does seem as an ideal behaviour.

**Comment by dbaeumer** [comment]
Actually, this is not under the control of LSP (nor under the control of this library) It is up to the editor to decide how to handle this. If we want to change this, it must be done in VS Code itself. There is nothing LSP can do to influence this for VS Code.

**Comment by martinlippert** [comment]
@dbaeumer In case the language server does a refactoring and for that changes maybe a few hundred files, would you still recommend to send back a workspace edit from the language server to the client for all those changes to all those files? Or would you recommend to do it totally differently? Looking for your advice here... :-)

**Comment by martinlippert** [comment]
Ok, thanks for the advice @dbaeumer, much appreciated!!!
We should then probably report this to VS Code itself to see if we can improve the way VS Code deals with this situation (@BoykoAlex)
